### ISSUE TITLE
[Proposal] PHP 'Signature mismatch during inheritance' sniff

### ISSUE THREAD

**Issue by turboezh** [squizlabs/PHP_CodeSniffer#1001]
Since PHP 7 "Signature mismatch during inheritance" emits E_WARNING ("Declaration of [method] should be compatible with [parent method]"). Is it possible to detect such things with static code analyse?

http://php.net/manual/en/migration70.incompatible.php

**Comment by aik099** [comment]
No. The analysis is done on per-file basis and it's impossible to determine where parent class of analyzed one is located.
