### ISSUE TITLE
PSR-2 alternative condition syntax demanding a space before colon

### ISSUE THREAD

**Issue by amcsi** [squizlabs/PHP_CodeSniffer#1008]
`if ($something):` <- PHPCS is complaining here that there's a space missing before the colon. I couldn't find it in the PSR-2 documentation that this is needed in the alternative syntax. Also this is really unusual for me; I've mostly seen the alternative syntax's colon without a space in other code I've seen before.

**Comment by gsherwood** [comment]
PSR-2 doesn't specify any specific rules for alternate syntax, so PHPCS applies what rules it can.

PSR-2 says `There MUST be one space between the closing parenthesis and the opening brace`, so PHPCS requests that you place a single space after the closing parenthesis.

If you think alternate syntax should follow different rules, I encourage you to ask on the mailing list. You've got almost no chance of getting PSR-2 changed, but maybe you'll be able to get something put into PSR-12.

**Comment by amcsi** [comment]
There are more things PSR-2 doesn't specify rules for than does. I don't see how you come to the conclusion that if a rule is not defined, then "apply this rule" rather than not apply any rule at all. I could argue that I think the switch-case rules should apply, because we're dealing with a colon, and thus there should never be spaces before colons.

I'm not saying that I want that to be the case, I'm just a bit bothered by the fact that I would need to follow a part of a coding style that not only does not exist, but is not popular. I looked at the first 10 results in Google when searching for "alternate php syntax", and nowhere in the 10 results did I see anyone put spaces before the colon.

So this doesn't make sense to me.
In any case do you happen to know where that google group is? Ever since the the PHP-FIG website changed, I can't find the PSR-2 group link anymore.

**Comment by gsherwood** [comment]
> In any case do you happen to know where that google group is?

It's just one big group for everything: https://groups.google.com/forum/?fromgroups#!forum/php-fig
