### ISSUE TITLE
Regular expressions aren't fully supported

### ISSUE THREAD

**Issue by PatrickRose** [squizlabs/PHP_CodeSniffer#1009]
I've just been bit by the fact that the PHPCS replaces `*` with `.*`. I was using `^((?!upgrade\/).)*$`, and couldn't understand why it was working when I tested the preg_match in a PHP shell but wasn't in PHPCS.

Is there the possibility of adding an extra attrib to the `exclude-pattern` element for "This is actually a regex, don't do anything to it"? Happy to send a PR if you think it's worth considering.

**Comment by gsherwood** [comment]
This is the only char that is replaced (docs here to confirm that: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#ignoring-files-and-folders). Other than that, the pattern works as a regex.

I don't think that adding an option to turn off a single replacement is worth it, but I'll leave this open for anyone else to comment on.

**Comment by gsherwood** [comment]
Closing as didn't receive any feedback
