### ISSUE TITLE
Add a bash/zsh auto-complete script

### ISSUE THREAD

**Issue by aik099** [squizlabs/PHP_CodeSniffer#1013]
Please add a bash/zsh auto-complete script into `scripts` folder for `phpcs` and `phpcbf` commands.

**Comment by TomasVotruba** [comment]
How would that look like?
Could you send PR?

**Comment by aik099** [comment]
Probably something like `phpcs --generate-autocomplete-hook`, that would return usual bash switch/case construct for `complete` command. 

Then you place `eval(that_command)` in your `.bash_profile`.

No PR coming any time soon.

**Comment by gsherwood** [comment]
Closing this as I can't see it ever happening.

**Comment by TysonAndre** [comment]
It seems like someone wrote one for zsh in https://github.com/voronkovich/phpcs.plugin.zsh (found google searching for "bash completion" and "phpcs". I haven't searched for a bash completion script.

Mentioning this in case anyone sees this issue in the future.
