### ISSUE TITLE
Duplicate spaces after opening bracket error with PSR2 standard

### ISSUE THREAD

**Issue by nkovacs** [squizlabs/PHP_CodeSniffer#1022]
Using phpcs 2.6.0, with the following php file:

```php
<?php

if ( $a) {
    foo();
}
```

I get two identical errors instead of one: `PSR2.ControlStructures.ControlStructureSpacing.SpacingAfterOpenBrace` and `Squiz.WhiteSpace.ControlStructureSpacing.SpacingAfterOpenBrace`

**Comment by gsherwood** [comment]
That second error message was supposed to be muted when I added the fix for #883. Thanks for reporting this.
