### ISSUE TITLE
PSR2.Classes.ClassDeclaration fails if class extends base class and "implements" is on trailing line

### ISSUE THREAD

**Issue by AlexHowansky** [squizlabs/PHP_CodeSniffer#1023]
I have a file foo.php:

    class A extends B
        implements C
    {
    }

I want to run the PSR2.Classes.ClassDeclaration sniff but exclude the PSR2.Classes.ClassDeclaration.ImplementsLine test, so I create this phpcs.xml file:

    <?xml version="1.0"?>
    <ruleset name="foo">
        <rule ref="PSR2.Classes.ClassDeclaration">
            <exclude name="PSR2.Classes.ClassDeclaration.ImplementsLine"/>
        </rule>
    </ruleset>

Then I run this command:

    phpcs -s foo.php

And get this output:

    ----------------------------------------------------------------------
    FOUND 1 ERROR AFFECTING 1 LINE
    ----------------------------------------------------------------------
     3 | ERROR | [x] Expected 0 spaces between "B" and comma; 1 found
       |       |     (PSR2.Classes.ClassDeclaration.SpaceBeforeComma)
    ----------------------------------------------------------------------

This test should not fail in this case.

**Comment by gsherwood** [comment]
This has been fixed now. Thanks for the report.
