### ISSUE TITLE
Squiz FunctionDeclarationArgumentSpacing gives incorrect error when first arg is a variadic

### ISSUE THREAD

**Issue by firegate666** [squizlabs/PHP_CodeSniffer#1034]
I have the following function

    function o(...$args) {
        $args_len = sizeof($args);
        ...
    }

which should be valid, but the code sniffers complains about it

     51 | ERROR | [x] Expected 1 space between type hint and argument
     |       |     "$args"; 0 found
     |       |     (Squiz.Functions.FunctionDeclarationArgumentSpacing.SpacingAfterHint)

Within the same file, there is a similar method that uses the variadic parameter as second parameter

    function p($text, ...$arguments) {
        $text = call_user_func_array('vsprintf', [$text, $arguments]);
        print $text;
        print PHP_EOL;
    }

no complains here

**Comment by gsherwood** [comment]
Fixed now. Thanks for reporting.

**Comment by firegate666** [comment]
Awesome, thx for fixing it.
