### ISSUE TITLE
Generic.WhiteSpace.ScopeIndent indenting not as expected

### ISSUE THREAD

**Issue by photodude** [squizlabs/PHP_CodeSniffer#1038]
In some cases the Generic.WhiteSpace.ScopeIndent sniff reduces indenting resulting in poorly formatted code. (Note: using tabs for spacing)

Examples

#### Nested arrays
**Expected/original code**

```php
	/**
	 * Private/critical data that we don't want to share
	 *
	 * @var    array
	 *
	 * @since  3.5
	 */
	protected $privateSettings = array(
		'phpInfoArray' => array(
			'CONTEXT_DOCUMENT_ROOT',
			'Cookie',
			'DOCUMENT_ROOT',
			'extension_dir',
			'error_log',
			'Host',
			'HTTP_COOKIE',
			'HTTP_HOST',
			'HTTP_ORIGIN',
			'HTTP_REFERER',
			'HTTP Request',
			'include_path',
			'mysql.default_socket',
			'MYSQL_SOCKET',
			'MYSQL_INCLUDE',
			'MYSQL_LIBS',
			'mysqli.default_socket',
			'MYSQLI_SOCKET',
			'PATH',
			'Path to sendmail',
			'pdo_mysql.default_socket',
			'Referer',
			'REMOTE_ADDR',
			'SCRIPT_FILENAME',
			'sendmail_path',
			'SERVER_ADDR',
			'SERVER_ADMIN',
			'Server Administrator',
			'SERVER_NAME',
			'Server Root',
			'session.name',
			'session.save_path',
			'upload_tmp_dir',
			'User/Group',
			'open_basedir',
		),
		'other' => array(
			'db',
			'dbprefix',
			'fromname',
			'live_site',
			'log_path',
			'mailfrom',
			'memcache_server_host',
			'memcached_server_host',
			'open_basedir',
			'Origin',
			'proxy_host',
			'proxy_user',
			'proxy_pass',
			'secret',
			'sendmail',
			'session.save_path',
			'session_memcache_server_host',
			'session_memcached_server_host',
			'sitename',
			'smtphost',
			'tmp_path',
			'open_basedir',
		)
	);
```

**Post phpcbf fixer**

```php
	/**
	 * Private/critical data that we don't want to share
	 *
	 * @var    array
	 *
	 * @since  3.5
	 */
	protected $privateSettings = array(
	'phpInfoArray' => array(
	'CONTEXT_DOCUMENT_ROOT',
	'Cookie',
	'DOCUMENT_ROOT',
	'extension_dir',
	'error_log',
	'Host',
	'HTTP_COOKIE',
	'HTTP_HOST',
	'HTTP_ORIGIN',
	'HTTP_REFERER',
	'HTTP Request',
	'include_path',
	'mysql.default_socket',
	'MYSQL_SOCKET',
	'MYSQL_INCLUDE',
	'MYSQL_LIBS',
	'mysqli.default_socket',
	'MYSQLI_SOCKET',
	'PATH',
	'Path to sendmail',
	'pdo_mysql.default_socket',
	'Referer',
	'REMOTE_ADDR',
	'SCRIPT_FILENAME',
	'sendmail_path',
	'SERVER_ADDR',
	'SERVER_ADMIN',
	'Server Administrator',
	'SERVER_NAME',
	'Server Root',
	'session.name',
	'session.save_path',
	'upload_tmp_dir',
	'User/Group',
	'open_basedir',
	),
	'other' => array(
	'db',
	'dbprefix',
	'fromname',
	'live_site',
	'log_path',
	'mailfrom',
	'memcache_server_host',
	'memcached_server_host',
	'open_basedir',
	'Origin',
	'proxy_host',
	'proxy_user',
	'proxy_pass',
	'secret',
	'sendmail',
	'session.save_path',
	'session_memcache_server_host',
	'session_memcached_server_host',
	'sitename',
	'smtphost',
	'tmp_path',
	'open_basedir',
	)
	);
```

#### `if(){}` added spaces rather than tabs
**expected/original code**

```php
		if (!$privateSettings)
		{
			return $dataArray;
		}
```

**Post phpcbf fixer**

```php
	 if (!$privateSettings)
	 {
	  return $dataArray;
	 }
```

#### Nested for/if
**expected/original code**

```php
		foreach ($dataArray as $section => $values)
		{
			if (is_array($values))
			{
				$dataArray[$section] = $this->cleanPrivateData($values, $dataType);
			}

			if (in_array($section, $privateSettings, true))
			{
				$dataArray[$section] = $this->cleanSectionPrivateData($values);
			}
		}
```

**Post phpcbf fixer**

```php
	 foreach ($dataArray as $section => $values)
	 {
	  if (is_array($values))
	  {
	   $dataArray[$section] = $this->cleanPrivateData($values, $dataType);
	  }

	  if (in_array($section, $privateSettings, true))
	  {
	   $dataArray[$section] = $this->cleanSectionPrivateData($values);
	  }
	 }
```

full source with errors and the post fix file that has bad formatting
[models.zip](https://github.com/squizlabs/PHP_CodeSniffer/files/317443/models.zip)

**Comment by aik099** [comment]
1. All sniffs fix using spaces. Then sniff that only allows tabs for indentation fixes that.
2. Nested arrays are only supported by special array processing sniffs. Since array by itself doesn't create any scope the ScopeIndent sniff have no idea how to format them.

**Comment by photodude** [comment]
The problem is I expect the indent to be something like `tab tab` or `tab tab tab` but I'm getting `tab space` or `tab space space`

**Comment by aik099** [comment]
I see. Then I guess some sniff does `space space space space space space` (6 spaces) and then tab sniff just converts Tabs replaces 4 spaces with 1 and lefts other spaces as-is.

Are you sure it's `ScopeIndent` sniff alone that does it. Have you tried running auto-fixer by specifying `--sniffs=...ScopeIndent...` (full name of sniff). Then when fixing using given standard it would only use that sniff(-s)?

**Comment by photodude** [comment]
I just started testing our custom ruleset with the fixers. I'm not sure about what's doing what. I'll try running with just `ScopeIndent`

**Comment by photodude** [comment]
Yes, same result with just `Generic.WhiteSpace.ScopeIndent` or `PEAR.WhiteSpace.ScopeIndent`

my ruleset.xml only has this rule (replacing `Generic` with `PEAR` to test with the PEAR version)
```xml
	<rule ref="Generic.WhiteSpace.ScopeIndent">
		<properties>
			<property name="tabIndent" value="true"/>
		</properties>
	</rule>
```

**Comment by photodude** [comment]
I think I have a lead on where the issue is. If you don't specify the tab-width the [sniff is suppose to assume the tab-width=4](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/Generic/Sniffs/WhiteSpace/ScopeIndentSniff.php#L149-L159)

I tried specifying `--tab-width=4` in the command line and there is no errors detected (and no fixes needed) 

So for whatever reason the sniff fails to set/enforce assuming tab-width is 4 if not specified. I assume [the failing condition is at line 151](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/Generic/Sniffs/WhiteSpace/ScopeIndentSniff.php#L151)

**Comment by gsherwood** [comment]
You need to specify the `tab-width` setting to PHPCS if you indent using tabs. This tells PHPCS to replace all tabs with spaces before it goes ahead and checks the file. If you are using tabIndent for the ScopeIndent sniff, it will fix code using tabs and assume that 4-space tab width, but it will be detecting each tab as a single character. So you end up with it thinking you have indented your code 3 spaces (for example) when you actually have 3 tabs.

Assuming you are using a tab-width of 4, you should include these rules in your ruleset:
```xml
<arg name="tab-width" value="4"/>
<rule ref="Generic.WhiteSpace.DisallowSpaceIndent"/>
<rule ref="Generic.WhiteSpace.ScopeIndent">
    <properties>
        <property name="indent" value="4"/>
        <property name="tabIndent" value="true"/>
    </properties>
</rule>
```
This tells PHPCS to convert tabs to 4 spaces during checking (the file is not actually changed), to disallow space indenting and thus enforce tab indenting, and to check scope indents using tabs.

The two referenced sniffs will work together when using PHPCBF to ensure space indentation is turned into tab indentation and that the number of tabs is correct.

Does this help?

**Comment by photodude** [comment]
Ok, so `tabIndent=true` is insufficient to have the ScopeIndent indent with tabs, and we also need to use both `tab-width=4` and `indent=4`. 

[The Documentation](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options#setting-the-default-tab-width) should probably be updated to reflect the full requirements needed to have ScopeIndent indent with tabs.

**Comment by gsherwood** [comment]
> Ok, so tabIndent=true is insufficient to have the ScopeIndent indent with tabs, and we also need to use both tab-width=4 and indent=4.

Actually, no. You really just need tab-width set, which has always been the case for PHPCS and also makes all other sniffs work as well. The key to enforcing tab usage for indenting is actually the `Generic.WhiteSpace.DisallowSpaceIndent` sniff. So you can get away with this:
```xml
<arg name="tab-width" value="4"/>
<rule ref="Generic.WhiteSpace.DisallowSpaceIndent"/>
<rule ref="Generic.WhiteSpace.ScopeIndent"/>
```
I included the other options from the ScopeIndent sniff because you can set those if you care about tab widths and error messages (ScopeIndent will say "tabs" instead of "spaces" in messages).

If you just want to make sure you are using tabs for indentation, and you want them to be auto-fixed, just make sure you include `Generic.WhiteSpace.DisallowSpaceIndent` and the tab-width setting in your ruleset.

Everything seems to be working in my testing, so I'll close this issue.

**Comment by photodude** [comment]
In the [current draft of our code style using PHPCS2 the ruleset.xml](https://github.com/photodude/coding-standards/blob/phpcs-2/Joomla/ruleset.xml) includes the `Generic.WhiteSpace.DisallowSpaceIndent` I've added the `<arg name="tab-width" value="4"/>` and will be officially adding `<rule ref="Generic.WhiteSpace.ScopeIndent"/>` with `<property name="tabIndent" value="true"/>` to insure the errors are reported as tabs not spaces.

`<arg name="tab-width" value="4"/>` was the major missing component
