### ISSUE TITLE
https://squizlabs.github.io

### ISSUE THREAD

**Issue by ravage84** [squizlabs/PHP_CodeSniffer#1039]
GitHub now supports HTTPS for github.io websites:
https://github.com/blog/2186-https-for-github-pages

Such as the Analysis of Coding Conventions page:
https://squizlabs.github.io/PHP_CodeSniffer/analysis/

But the page contains assets that get loaded through HTTP instead of HTTPS, like:
http://squizlabs.github.io/PHP_CodeSniffer/analysis/cakephp/cakephp/grade.svg

This produces a warning in web browsers.

**Comment by gsherwood** [comment]
Good idea. HTTPS enforced and URLs changed for those images now.
