### ISSUE TITLE
is there a maximum severity?

### ISSUE THREAD

**Issue by andykais** [squizlabs/PHP_CodeSniffer#1048]
I've looked over the docs and I know the default severity is 5 and that severity can go up to at least 8, but I have not seen a maximum severity mentioned anywhere. 
Do you just allow each standard to define their own maximum? It is important for me to have a complete scale of severities to use phpcs

**Comment by gsherwood** [comment]
There is no maximum severity.

The way it works is that a sniff sets a severity when it generates an error message. So an error code has a severity - not a standard and not an entire sniff. The developer who wrote the sniff decides the severity, but you can override that in a ruleset.xml file and thus decide on severities for each error code yourself. 

But again, there is no maximum here either. It's just a number. I prefer just using "warning" and "error" but I added that numeric value as well for some reason I can't remember. I'd be surprised if anyone is even using it.

I hope that answers your question.
