### ISSUE TITLE
Possible to exclude specific error from specific file

### ISSUE THREAD

**Issue by oligriffiths** [squizlabs/PHP_CodeSniffer#1050]
Hi

Is it possible to exclude a specific error within a sniff, for a specific file/dir? 

For example:

`<exclude name="Squiz.Commenting.FunctionComment.MissingReturn" />`
AND
`<exclude-pattern>./tests/*</exclude-pattern>`

Combined, so I don't have to add `@return` to tests as they never return anything.

Thanks

**Comment by aik099** [comment]
It is possible. As demonstrated on https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-ruleset.xml page this can be done using following construct:

```xml
<rule ref="Squiz.Strings.DoubleQuoteUsage">
    <exclude-pattern>*/tests/*</exclude-pattern>
    <exclude-pattern>*/data/*</exclude-pattern>
 </rule>
```

**Comment by oligriffiths** [comment]
That's for the entire sniff though, not for a specific error that's part of a sniff...

**Comment by aik099** [comment]
Same would work for specific error as well. You can find more examples in the example page I've mentioned before.

**Comment by gsherwood** [comment]
Yes, you can exclude a specific message. This example is also from https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-ruleset.xml
```xml
 <!--
    You can also be more specific and just exclude some messages.
    Please note that all message-specific ignore patterns are
    checked using absolute paths.

    The code here will just hide the ContainsVar error generated by the
    Squiz DoubleQuoteUsage sniff for files that match either of the two
    exclude patterns.
 -->
 <rule ref="Squiz.Strings.DoubleQuoteUsage.ContainsVar">
    <exclude-pattern>*/tests/*</exclude-pattern>
    <exclude-pattern>*/data/*</exclude-pattern>
 </rule>
```

**Comment by oligriffiths** [comment]
Awesome. Thanks Greg.
