### ISSUE TITLE
Logic not operator followed by a space

### ISSUE THREAD

**Issue by eclipxe13** [squizlabs/PHP_CodeSniffer#1051]
Would you consider to add a Sniff for logic not operator followed by a space?

```php
// changes
if (!$someVar || !$x instanceOf 'stdClass') {
// to
if (! $someVar || ! $x instanceOf 'stdClass') {
```

In FriendsOfPHP/PHP-CS-Fixer they use the fix [logical_not_operators_with_successor_space](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.11/Symfony/CS/Fixer/Contrib/LogicalNotOperatorsWithSuccessorSpaceFixer.php)

Also, other developers and projects like http://auraphp.com/contributing/#standards use this style

It would be great to have it on PHP_CodeSniffer (thanks for your great work!)

**Comment by gsherwood** [comment]
Seemed like a good idea and an easy sniff to create, so I've committed a sniff and it will be in the next release.

The sniff does checking and fixing for PHP and JS files. Include it n a ruleset using this tag:
```xml
<rule ref="Generic.Formatting.SpaceAfterNot" />
```
Or run only that check over your entire code base:
`phpcs --standard=Generic --sniffs=Generic.Formatting.SpaceAfterNot /path/to/code`

Or just fix that in the code base:
`phpcbf --standard=Generic --sniffs=Generic.Formatting.SpaceAfterNot /path/to/code`

Thanks for the suggestion.

**Comment by aik099** [comment]
Maybe it also makes sense to create another sniff that would enforce the opposite checking/fixing behavior?

**Comment by glen-84** [comment]
I agree with @aik099, except that I think that it could have been done with a single sniff.

Something like `Generic.Formatting.LogicalNotSpacing` with options `spacesBefore` and `spacesAfter`.

**Comment by mkarnicki** [comment]
I know this is old as the world, but I can't seem to find it - has enforcing a space after the logical not operator been added perhaps? Thanks!

**Comment by jrfnl** [comment]
@mkarnicki As stated above, the `Generic.Formatting.SpaceAfterNot` sniff does just that (enfore one space after the not operator).
Open PR #2233 will make the sniff configurable, so you would also be able to use it to, for instance, enforce _no_ space after the not operator.

**Comment by yamenarahman** [comment]
@eclipxe13 Would you help me here? https://github.com/ikappas/vscode-phpcs/issues/178
