### ISSUE TITLE
Support for include-pattern

### ISSUE THREAD

**Issue by josephzidell** [squizlabs/PHP_CodeSniffer#1052]
Can you support `<include-pattern>` to work on top of `<exclude-pattern>`?

We have multiple use-cases for this where a directory should be excluded except for 1 or 2 subdirectories.

- main_dir/
     - dir_a/
     - dir_b/

```
<exclude-pattern>main_dir/*</exclude-pattern>
<include-pattern>main_dir/dir_b/*</include-pattern>
```

If agreed, I can whip up a PR.

**Comment by gsherwood** [comment]
This was requested in #656 and has been committed to the 3.0 branch. I have chosen not to include it in the 2.x branch at this stage. Best to keep any discussion over on the other issue anyway, so I'm closing this one.
