### ISSUE TITLE
Generic.Files.LineLength.MaxExceeded - non-UTF wrong count

### ISSUE THREAD

**Issue by wareczek** [squizlabs/PHP_CodeSniffer#1054]
```php
<?php

$none = 'Nie udało się usunąć wybranego repozytorium.';
```
phpcs error:

> line 3, col 59, Error (Generic.Files.LineLength.MaxExceeded) Line exceeds maximum limit of 50 characters; contains 59 characters

This line has **55**, not **59** characters.

You should use `mb_strlen` not `strlen` - http://php.net/manual/en/function.strlen.php#118484

**Comment by aik099** [comment]
You should specify `--encoding UTF-8` when running `phpcs` instead.

**Comment by wareczek** [comment]
ok, thx :)
