### ISSUE TITLE
some ruleset.xml arguments fail

### ISSUE THREAD

**Issue by photodude** [squizlabs/PHP_CodeSniffer#1057]
I tried adding the following ruleset arguments to hard code command line values into the standard, but got an error saying they were unknown

```xml
	<arg name="report_width" value="150"/>
	<arg name="show_progress" value="1"/>
```

the messages are
`ERROR: option "--report_width=150" not known.`
`ERROR: option "--show_progress=1" not known.`

**Comment by gsherwood** [comment]
The arg names you use in the `arg` tags need to be the ones you use on the command line and not the config values.

So try:
```
<arg name="report-width" value="150"/>
<arg name="p" />
```
There is a basic example, including the show progress flag, here: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-ruleset.xml

**Comment by photodude** [comment]
`<arg name="p" />` works
but `<arg name="report-width" value="150"/>` causes `ERROR: option "--report_width=150" not known.`

**Comment by gsherwood** [comment]
The error message indicates you are still using `report_width` and not `report-width`.

**Comment by photodude** [comment]
LOL, I guess my eyes are seeing what they want to see. When I get back I'll re-run properly using a dash.

**Comment by photodude** [comment]
`<arg name="report-width" value="150"/>` (dash not underscore) works as expected.
