### ISSUE TITLE
Squiz ArrayDeclarationSniff does not return on empty array without an error

### ISSUE THREAD

**Issue by nkovacs** [squizlabs/PHP_CodeSniffer#1058]
I ran into this when modifying and extending the Squiz ArrayDeclarationSniff.

The comment above this claims that "All code below can assume that the array is not empty":
https://github.com/squizlabs/PHP_CodeSniffer/blob/2d3a4a80cc7df70884ba072dfecda7028b37f1d0/CodeSniffer/Standards/Squiz/Sniffs/Arrays/ArrayDeclarationSniff.php#L126
But this isn't true because the return only happens if there's a `SpaceInEmptyArray` error. It should be moved outside that if.

**Comment by gsherwood** [comment]
Makes sense to me and doesn't cause any unit test failures. There is no failed test cases, so I think this one is just a saving on useless processing time for empty arrays. Thanks for reporting it.
