### ISSUE TITLE
Squiz.WhiteSpace.LanguageConstructSpacing forces spaces even if parenthesis are used

### ISSUE THREAD

**Issue by aik099** [squizlabs/PHP_CodeSniffer#1062]
The `Squiz.WhiteSpace.LanguageConstructSpacing` sniff wants language constructs (e.g. `echo`, `print`, `return`, `include`, `include_once`, `require`, `require_once`, `new`) to have single space after them.

The `PEAR.Functions.FunctionCallSignature` wants to see no space before `(` in function calls.

This creates a conflict because some of above mentioned language constructs (e.g. `include_once`, `include`, `require_once`, `require`) can be written in 2 forms:

* `include_once('file.php');`
* `include_once 'file.php';`

The space after language construct only makes sense to have when 2nd form (without parentheses) is used.

**Comment by gsherwood** [comment]
The sniff was designed specifically to force a space even if parenthesis are used. But the clash between this sniff and a standard sniffs that check function calls makes it less useful, so I think it makes sense to change it.

But this is a BC break.

**Comment by aik099** [comment]
Thanks.
