### ISSUE TITLE
[Feature request] Sniff for class opening braces on same line ?

### ISSUE THREAD

**Issue by jrfnl** [squizlabs/PHP_CodeSniffer#1068]
Would there be any interest in having a sniff for class opening braces on the same line as the class statement ?
I imagine it could be added to `Generic` ?

All currently existing sniffs for class opening structures I could find check for the brace on a new line AFAICS.

I'd be happy to send in a PR.

**Comment by gsherwood** [comment]
These sniff exist for functions and closures, so I don't see any reason why they shouldn't exist for classes and interfaces as well.
