### ISSUE TITLE
Ignore comments in Squiz.WhiteSpace.FunctionSpacing

### ISSUE THREAD

**Issue by VasekPurchart** [squizlabs/PHP_CodeSniffer#1075]
Hi,

I was going through excluded rules in my ruleset and I have excluded `Squiz.WhiteSpace.FunctionSpacing.After`, because it does not work with comments, which are on the line after a function/method. Unfortunately this is sometimes necessary when using PHPUnit code coverage:

``` php
class Foo
{

    public function foo()
    {
        Bar::throwException();
        // @codeCoverageIgnoreStart
        // return from this method is never invoked (always throws exception)
    }
    // @codeCoverageIgnoreEnd

}
```

I can imagine, that there are also other reasons why some needs to put a comment right after the function/method (because it essentially belongs to it in these cases).

Would it be possible to ignore these comments? Maybe only inline comments (`//`, `#`), not multiline ones (`/* */`). I think this is a similar case as #768, #794.

Or if it is a problem to do this by default, maybe introduce a new property to configure this?

**Comment by gsherwood** [comment]
Closing as I've had no additional interest or PRs for this.

**Comment by bugreportuser** [comment]
I'm also interested in this. Would you accept a PR?
