### ISSUE TITLE
Make phpcs installable via Phive (phar.io)

### ISSUE THREAD

**Issue by sebastianfeldmann** [squizlabs/PHP_CodeSniffer#1082]
PHIVE can be used to install PHARs, a kind of composer for PHAR files.
The good thing is, it verifys the downloaded file via GPG signature to make sure you installed the right tool.
## ToDo

Add a signature file to your github releases
## HowTo

-- Copied from the phive howto (https://phar.io/howto/sign-and-upload-to-github.html) --
## Create a signature

You need a personal or company GPG key. If you don't have one, [this explains how to generate a GPG key](https://phar.io/howto/generate-gpg-key.html).

```
gpg -u john@doe.com --detach-sign --output your.phar.asc your.phar
```

About the options:
- -u (optional) Provide a search term for the USER-ID you intend to use, if you have more than one.
- --detach-sign Create a detached signature (do not wrap the original file).
- --output Specify the filename of the signature (PHIVE currently searches for your.phar.asc).
- Last argument is the PHAR you want to sign.
## Upload in GitHub's release section
1. \- Go to https://github.com/<your-vendor>/<your-project>/releases
2. \- Klick "Edit" on your latest tag/release
3. \- Add your.phar and your.phar.asc in the "Attach binaries..." section
4. \- Klick "Update release"

**Comment by KingCrunch** [comment]
You should add a GPG-key (maybe the same one) for `phpcbf.phar` too. It would really help handling tools for those who don't like to add them as dev-dependency.

**Comment by aik099** [comment]
Just to verify:

1. the PHAR file remains unchanged
2. the `.phar.asc` file containing GPG signature is added next to in in release attachments

?

If you're downloading PHAR over HTTPS, then signature isn't needed. The https://github.com/padraic/phar-updater package prooves that (in there signature is used to differentiate between different PHAR versions only).

**Comment by KingCrunch** [comment]
@aik099 Maybe that'll be an improvement for Phive itself, but right now Phive requires the signature file

**Comment by jk** [comment]
@aik099
> If you're downloading PHAR over HTTPS, then signature isn't needed. The https://github.com/padraic/phar-updater package prooves that (in there signature is used to differentiate between different PHAR versions only).

The intention to place separate signature file is to mitigate an attack where the attacker replaces the binary on a server with a version that spreads his malware. HTTPS only secures the transfer itself. It the binary.

**Comment by aik099** [comment]
> The intention to place separate signature file is to mitigate an attack where the attacker replaces the binary on a server with a version that spreads his malware. HTTPS only secures the transfer itself. It the binary.

I see. I guess an attacker could also replace signature unless the signature is signed and attacker doesn't have that key. But to make it work the code, that verifies downloaded file need to be able to process signed signature file.

**Comment by jk** [comment]
Those signatures use the inverse of your public key (or private key … I don't recall the details of the implementation details anymore, but should be the public one. What matters is that a signature from an unknown key is worthless) by definition but you got a point that the attacker might also replace the signature matching the malformed binary. To mitigate this it's a common practise to accept only a few parent certificates in case of public key infrastructure (PKI) or a web of thrust. GPG utilises the latter. 

But I haven't looked into Phive if they only accept certain keys/thrust relationships. Point is: automate the signature creation and forget about it. Chances are high that it adds some security :)

**Comment by aik099** [comment]
Security related topics are interesting ones to discuss indeed.

**Comment by gsherwood** [comment]
I've added the keys for the latest 3.2.0 release and installing with `phive install squizlabs/php_codesniffer` is working. So all looks good.

**Comment by sebastianfeldmann** [comment]
Awesome! Thank you so much

**Comment by theseer** [comment]
FYI: The alias `phpcs` as been added as well, so the shorthand `phive install phpcs` should also work (as soon as the new repositories.xml has been propagated, you can use `phive update-repository-list` to force a refresh).
