### ISSUE TITLE
Error in wiki ?

### ISSUE THREAD

**Issue by jrfnl** [squizlabs/PHP_CodeSniffer#1083]
Seems I can't edit the wiki, so leaving this here for someone who can to fix it:

Page: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Fixing-Errors-Automatically
Section: Using the PHP Code Beautifier and Fixer
Error: first line of last code block of the section.

`$phpcs /path/to/code --suffix=.fixed`

Should read:

`$phpcbf /path/to/code --suffix=.fixed`

**Comment by gsherwood** [comment]
Thanks for reporting this. I've fixed it now.

**Comment by jrfnl** [comment]
Thanks ;-)
