### ISSUE TITLE
Ignoring line limit lenght for use statements

### ISSUE THREAD

**Issue by JeroenDeDauw** [squizlabs/PHP_CodeSniffer#1094]
In my project there are classes that have a long fully qualified name. Sometimes due to many directories, sometimes due to long class and directory names, and sometimes both. This can lead to import statements significantly longer than what we want to use for our line length limit. Is there a way to have the rule not apply to import statements? If not, consider this a feature request.

**Comment by gsherwood** [comment]
There is no way to ignore specific types of statements, and no way to ignore really long use statements. Sounds like a good feature though.

**Comment by gsherwood** [comment]
Closing as this is obviously not going to be done after all these years
