### ISSUE TITLE
Squiz.Commenting.FunctionComment type hint breaks on multi-version php support

### ISSUE THREAD

**Issue by ofbeaton** [squizlabs/PHP_CodeSniffer#1103]
I support PHP 5.6 and PHP 7.0 for my application, and I'm trying to use `Squiz.Commenting.FunctionComment` in my ruleset.

Unfortunately many of the type hints are not available for PHP 5.6. I use travis to make sure my application works, including phpcs, on php 5.6 and php 7.0.

The PHP 5.6 build works great but when it runs against php 7.0, I get type hint errors because my docblocks say a variable is `string` but I didn't provide the type hint in the function.

I looked at the code and I see:

```
} else if (version_compare(PHP_VERSION, '7.0.0') >= 0) {
```

this is clever but means that I can either make my code have syntax errors in 5.6, or style errors in 7.0.

I propose that that a new configuration setting be added to specify the version that phpcs should use when evaluating the code. If it is not provided, it should default to PHP_VERSION.

In this way I could lock my sniffs to php 5.6 enforcement until such a time I can drop php 5.6 and only support php 7.0, no matter what version of php is currently running phpcs.

**Comment by gsherwood** [comment]
Can you not just run your build using the path to php 5.6? Like `/path/to/php5.6/php phpcs ...`

**Comment by ofbeaton** [comment]
This would only work for the development environment, and require all developers to keep php 5.6 installed at all times. It would not work for having phpcs as part of continuous integration testing. 

I suppose it could be argued it does not belong there, but I feel that it's a great place to put it and make sure that all commits have indeed followed the ruleset. This turns travis into a similar service as https://styleci.io/

Here are some examples of my own public projects where I have historically used phpcs with travis-ci.
https://github.com/ofbeaton/db-ping/blob/master/.travis.yml (phpcs only)
https://github.com/ofbeaton/command-running/blob/master/.travis.yml (phpcs + phpunit)
https://github.com/ofbeaton/php-timeago/blob/master/.travis.yml (phpcs + phpunit)
https://github.com/ofbeaton/console-tester/blob/master/.travis.yml (phpcs + phpunit)

I don't want to suppress all type hints errors, after all I use the PHP 5.6 ones.

**Comment by ofbeaton** [comment]
I would be remiss in not mentioning that another solution exists, to disable `phpcs` only in my php 7.0 using something like:
```
- bash -c 'if [ "$TRAVIS_PHP_VERSION" != "7.0" ]; then bin/phpcs; fi;'
```

I don't think that's as good as a configuration setting however, as it would still require all developers to have php 5.6 installed, which isn't always realistic unfortunately.

It also seems strange for a sniff to behave differently based on the php version, though I get why it is done that way.

**Comment by ofbeaton** [comment]
I can't submit a PR for documentation, so I will post them here in the ticket so you can keep this ticket open until the docs are updated.

First I did not see your `php_path` documented. It probably belongs here:
https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options#generic-coding-standard-configuration-options

> ## Setting the path to CSSLint
> 
> The Generic coding standard [includes a sniff](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/Generic/Sniffs/PHP/SyntaxSniff.php) that will check each PHP file for syntax errors using the [built-in PHP linter](http://php.net/manual/en/features.commandline.options.php). Optionally use the `php_path` configuration option to tell the Syntax sniff where to find a specific php binary.
> 
> $ phpcs --config-set php_path /path/to/php
> 

Then for my change, it probably belongs right bellow the `Ignoring warnings when generating the exit code` and above `Generic Coding Standard Configuration Options`.
https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options#ignoring-warnings-when-generating-the-exit-code

> ## Setting the PHP Version
> 
> A few of the coding standards sniffs change their behaviour based on the [PHP version](http://php.net/manual/en/function.phpversion.php). To trick phpcs into using a specific version, set the `php_version` configuration option to make the sniffs use this version instead of `PHP_VERSION_ID` when determining features. For example, to lock it to PHP 5.6 and bellow, use:
> 
> $ phpcs --config-set php_version 560000
> 

I'm not sure where you highlight that these configurations options can also be set in the ruleset, but it should probably be emphasised here.

**Comment by gsherwood** [comment]
Sorry, forgot about this. PHP Version is now documented. I haven't documented PHP Path because that has been removed in the 3.0 version. Even 2.x users should use auto-discovery if possible.

**Comment by gsherwood** [comment]
Docs are done now.
