### ISSUE TITLE
Ignore "annotations" in Generic.Commenting.DocComment.TagValueIndent

### ISSUE THREAD

**Issue by glen-84** [squizlabs/PHP_CodeSniffer#1110]
We have the following code:

``` php
    /**
     * List of comments
     *
     * @Orm\ManyToMany(targetEntity="App\Discussions\Entities\Comment")
     * @Orm\OrderBy({"createdAt" = "DESC"})
     *
     * @var Comment[]|ArrayCollection
     */
    protected $comments;
```

Is there a way to ignore the tag value indentation error for "annotations" (non phpDoc)?

**Comment by aik099** [comment]
I'm also using custom annotations in my code and they look like this:

```php
/**
     * Button
     *
     * @var WebElement
     * @find-by('css' => '.submit-button')
     */
    protected $button;
```

Unfortunately if I add spaces between `@find-by` and `(` to indent the code as PHP_CodeSniffer wants I'll end up in non-recognizable annotation.

Maybe an exclusion can be added to consider `@annotation-name(....)` part as single entity and only look at whitespaces after it.

**Comment by gsherwood** [comment]
There is no way to ignore that message just for this annotation syntax. You'd have to ignore it for all docblocks.

**Comment by gsherwood** [comment]
Closing as I've had no additional interest or PRs for this.
