### ISSUE TITLE
Question: is there a sniff to check for mistaken assignation in an if condition?

### ISSUE THREAD

**Issue by u01jmg3** [squizlabs/PHP_CodeSniffer#1111]
For example to pick up:

```php
if($a = ''){
    //
}
```

And correct to:
```php
if($a == ''){
    //
}
```

**Comment by aik099** [comment]
There are no such built-in sniff, but I've written my own sniff for that purpose: https://github.com/aik099/CodingStandard/blob/master/CodingStandard/Sniffs/ControlStructures/AssignmentInConditionSniff.php

You can just copy-paste it into your own standard.

**Comment by u01jmg3** [comment]
Super, thank you

**Comment by u01jmg3** [comment]
Added using the following in `phpcs-ruleset.xml`:

```xml
<rule ref="Squiz.ControlStructures.AssignmentInConditionSniff" />
```

**Comment by aik099** [comment]
@u01jmg3 , that can't be true, because `Squiz` standard doesn't contain such sniff: https://github.com/squizlabs/PHP_CodeSniffer/tree/master/CodeSniffer/Standards/Squiz/Sniffs/ControlStructures

**Comment by u01jmg3** [comment]
It is if you add your sniff alongside the other Control Structures. Otherwise, where would you store your sniff?

**Comment by aik099** [comment]
Sniffs are stored within ruleset. There are:

* built in rulesets like Squiz and Generic
* custom rulesets like one I've linked.

With custom rulesets you don't have to wait for new PHP_CodeSniffer release to use new sniffs.

One huge disadvantage though is lack of custom ruleset distribution system (you can't easily extend your ruleset off custom one).

**Comment by u01jmg3** [comment]
How would I call that sniff? I have downloaded your [CodingStandards](https://github.com/aik099/CodingStandard) repo and added the following to [`ruleset.xml`](https://github.com/aik099/CodingStandard/blob/master/CodingStandard/ruleset.xml) but it errors saying it cannot find the sniff.

```xml
<rule ref="CodingStandard.ControlStructures.AssignmentInConditionSniff" />
```

**Comment by aik099** [comment]
What you can do depends on how your standard is created:

1. just a `phpcs.xml` in root of the project
2. the `StandardName` folder somewhere in the project, that has `ruleset.xml` file inside it

If you've used my standard via Composer (the `aik099/coding-standard` package), then it will be present in `/vendor/aik099/coding-standard/CodingStandard` folder. In that case you can specify relative path to that sniff in it like so:

```xml
<rule ref="vendor/aik099/coding-standard/CodingStandard.ControlStructures.AssignmentInConditionSniff" />
```
