### ISSUE TITLE
File docblock not recognized when require_once follows it

### ISSUE THREAD

**Issue by cweiske** [squizlabs/PHP_CodeSniffer#1112]
The file docblock in the PEAR coding standard is not recognized if it is followed by a `require_once` statement:

```
<?php
/**
 *
 */
require_once 'dummy.php';
?>
```

Output:
```
$ phpcs csbug.php 

FILE: /home/cweiske/tmp/csbug.php
----------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
----------------------------------------------------------------------
 1 | ERROR | Missing file doc comment
 2 | ERROR | Doc comment is empty
----------------------------------------------------------------------

Time: 20ms; Memory: 3.5Mb
```

This is on phpcs 2.6.2

**Comment by gsherwood** [comment]
The sniff ignores any comment at the top of the file if it is followed by another element that the comment can belong to, like a function, class, interface, etc. 

The ability to document require and include statements was added in 2.6.0. So in this case, PHPCS believes that the comment belongs to the require_once statement.

Given that require and include statements tend to come at the top of the file, I think it makes sense to remove them from this specific sniff.

**Comment by gsherwood** [comment]
Thanks for the report.
