### ISSUE TITLE
CodeSniffer does not locate Expand Drive files

### ISSUE THREAD

**Issue by dnsahoo** [squizlabs/PHP_CodeSniffer#1116]
Hi,

I am using windows 10 and trying to run codesniffer on files located in Expand Drive (i.e Expand drive gets all the files from a remote machine and create a virtual drive like C:\ drive on windows).

I am trying to run the following command
 `c:\>c:\php5\php c:\php_codesniffer\scripts\phpcs E:\myfilename.cls`

Here, PHP and Codesniffer located in my local machine C:\ drive. and  E:\ drive is the expand drive location. I am getting following error

![codesniffer_error](https://cloud.githubusercontent.com/assets/1394129/17641738/4807cf5c-614a-11e6-9204-02c5dbe13b1b.png)

If I tried to run the same command on a file located in local machine, it is running successfully.

Please guide.

**Comment by gsherwood** [comment]
I don't know anything about Expandrive, but it would seem like the file does not have the correct permissions for the PHP script to be able to read it. I'd suggest writing a very basic PHP script to open the file for reading, or get it's contents, or do what PHPCS does and just call `is_readable()` on the file path.

If you want to use the PHP interactive shell, you could just do this:
```
$ php -a
Interactive shell

php > var_dump(is_readable('E:\myfilename.cls'));
```
Then see if you get a boolean `true` or `false`.

**Comment by dnsahoo** [comment]
Hi,
Thank you for your reply.

I have tried to run the commands in Interactive shell, but, I am getting `false` here.

But while I run `php -l E:\myfilename.cls` it return success i.e `No syntax error...`.

**Comment by gsherwood** [comment]
Thanks for testing that. Given that core PHP doesn't think the file is readable using is_readable(), there is either a problem in that core PHP function or some problem with the network sharing that ExpanDrive is doing. Neither of those two things help you obviously, but it's all I could find out.

So I don't think there is anything I can really do in PHPCS to fix this for you. I could stop using is_readable(), but then I'd have to just attempt opening files, mute any errors using `@`, and test the connection to see if it is open. That doesn't feel clean, and opens a file pointer when it is not necessarily needed.

Sorry I don't have a solution for you.

**Comment by dnsahoo** [comment]
Hi Greg,

Thank you for your support.
