### ISSUE TITLE
Invalid considers the length of string in UTF-8

### ISSUE THREAD

**Issue by Aliaxander** [squizlabs/PHP_CodeSniffer#1118]
Invalid considers the length of string in UTF-8
In comments in Russian said bytes rather than characters
psr-2

**Comment by Aliaxander** [comment]
--encoding=utf-8

**Comment by obmenltd** [comment]
> --encoding=utf-8

ЗАЕБАЛ ОТВЕТЬ В ТЕЛЕГЕ!!!
