### ISSUE TITLE
simplexml_load_file and paths with %

### ISSUE THREAD

**Issue by kevinwinahradsky** [squizlabs/PHP_CodeSniffer#1123]
I am having a problem running phpcs when there is a % character somewhere in the path. It looks like this is noted in the php documentation for [simplexml_load_file](https://secure.php.net/manual/en/function.simplexml-load-file.php) in that paths will be url decoded. This then causes the file to not be found. The % character in the path happens when using a multi branch build in jenkins where the branches have a feature/something, bugfix/something, etc.. format. Modfying CodeSniffer.php to use rawurlencode when calling simplexml_load_file, as suggesting in the php docs, does fix the issue for me but I do not know if this can potentially break other use cases.

**Comment by aik099** [comment]
Looks like it was fixed in #1089. Not sure if that change was released in 2.6.2 (latest now) version. Does it work properly on `master` branch?

**Comment by kevinwinahradsky** [comment]
Indeed it does, `master` branch works fine. Will this be making it into the next release?

**Comment by gsherwood** [comment]
> Will this be making it into the next release?

Yes, which should be fairly soon, depending on how busy I get this week.
