### ISSUE TITLE
Squiz.Operators.ComparisonOperatorUsage does not detect bracketed conditions for inline IF statements

### ISSUE THREAD

**Issue by rhorber** [squizlabs/PHP_CodeSniffer#1124]
This sniff does not work on inline ifs.
`$value = ($foo == true) ? $bar : "baz";` does not trigger an error, which imho is one.

**Comment by rhorber** [comment]
Created pull request with bugfix: #1125

**Comment by gsherwood** [comment]
Fixed by PR #1127
