### ISSUE TITLE
Add command description to help text

### ISSUE THREAD

**Issue by neclimdul** [squizlabs/PHP_CodeSniffer#1126]
The READ lists the commands several times without explaining them. It also tells you to just dive in and start using them with:

```
./vendor/bin/phpcs -h
./vendor/bin/phpcbf -h
```

But it never tells you what the commands actually do. A quick line or two of text at the top of the command would quickly provide a starting place for that and also acquaint someone coming across the command as part of an existing project.

**Comment by gsherwood** [comment]
This project has a wiki with quite a lot of information in it: https://github.com/squizlabs/PHP_CodeSniffer/wiki

Is this the sort of info you are looking for? Maybe the README could just link to it.

**Comment by neclimdul** [comment]
I guess, though that doesn't really address what a user sees from the command help but it would help acquaint users. Another case where a user would run into this would be when coming in to a project already including phpcs through their composer.json for example.

**Comment by gsherwood** [comment]
The very first part of the README says:
```
PHP_CodeSniffer is a set of two PHP scripts; the main phpcs script that tokenizes PHP, JavaScript and CSS files to detect violations of a defined coding standard, and a second phpcbf script to automatically correct coding standard violations. PHP_CodeSniffer is an essential development tool that ensures your code remains clean and consistent.
```
I put that there to describe the two commands that PHPCS includes. I just realised that I already link the wiki in the README as well, so the full docs about PHPCS can be reached pretty easily for someone just scanning the README.

So I'm not really sure what you specifically think is missing. Do you think that first part of the README doesn't describe what the scripts do properly? Do you have any suggestions for different text I can use?
