### ISSUE TITLE
Sniffs documentation and ``-e`` flag

### ISSUE THREAD

**Issue by Asnelchristian** [squizlabs/PHP_CodeSniffer#1140]
I am a user, and i would like to know if it is possible to improve on the options `-e` of `phpcs` so that it prints the sniffs' variables that can be modified what the explain what the sniff is for?

Actually i am trying to write a simple program that generate a `ruleset.xml` file for the user, so actually i am struggling to know how to identify sniffs's vars. :sweat_smile:

**Comment by gsherwood** [comment]
The `-e` command line argument only lists the sniffs that have been loaded by a ruleset. It doesn't go through and parse (or use reflection) to get a list of public member vars and comments, so adding that would be a significant change.

If you want to know if a sniff has any config options, look at the sniff class's member vars. Any that are public can have their values set in ruleset.xml files.

**Comment by Asnelchristian** [comment]
thanks @gsherwood, maybe it will be a good idea to collect all those vars to make things simple for the rules writers :sweat_smile:

**Comment by gsherwood** [comment]
Closing as the doc now exists.
