### ISSUE TITLE
phpcbf errors with PSR2 with some code comments

### ISSUE THREAD

**Issue by photodude** [squizlabs/PHP_CodeSniffer#1142]
The attached code will cause the fixers to error and exit
#### Error
```php
Processing bbcode.php [PHP => 30 tokens in 12 lines]... DONE in 12ms (1 fixable violations)
        => Fixing file: 1/1 violations remaining [made 50 passes]... ERROR in 973ms
Fixed 0 files
```
#### Code
```php
<?php
/**
 * File comment
 */


// [list=greek] Ordered list, lowercase Greek letters, starting at alpha
// [list=01] Ordered list, two-digit numeric with 0-padding, starting at 01
/**
* @param $bbcode
* @param $action

```
(we are also seeing this with our in development custom code style which also uses parts of PSR2 as reported in this comment https://github.com/joomla/coding-standards/pull/109#issuecomment-244628614)

Possibly related to #1141
[bbcode.zip](https://github.com/squizlabs/PHP_CodeSniffer/files/454138/bbcode.zip)

**Comment by gsherwood** [comment]
This was fixed as a side-effect of fixing #1141.
