### ISSUE TITLE
Updating to 2.7.0 with composer

### ISSUE THREAD

**Issue by dingo-d** [squizlabs/PHP_CodeSniffer#1147]
I'm new to the composer, and don't use it that much.

I wanted to update to the 2.7.0 version so I went to my `\AppData\Roaming\Composer` and ran

```
composer update squizlabs/php_codesniffer
```

And it said that it removed the old codesniffer (2.6.2) and installed the new version. Now, I have installed WordPress coding standards, so I went to \wpcs folder and did the same, and there it also removed the old and installed the new version, but when I type 

```
phpcs --version
```

I still get:

```
PHP_CodeSniffer version 2.6.2 (stable) by Squiz (http://www.squiz.net)
```

What am I doing wrong? Is there something else I'm missing? I cleared cache but nothing helped...

**Comment by dingo-d** [comment]
Any tips on finding out how many installations I have? Any command? I know I had some troubles installing it on Windows so I used pear, and then later composer. This could be causing it.

**Comment by aik099** [comment]
If you don't need phpcs installed over pear you can uninstall it, e.g. `pear uninstall PHP_CodeSniffer`. Then you should get error when you try to use `phpcs` command.

**Comment by aik099** [comment]
Either way use `vendor/bin/phpcs` instead of just `phpcs` from project folder and you should have no conflicts.

**Comment by dingo-d** [comment]
I'm afraid that if I uninstall it that everything will stop working :\

**Comment by aik099** [comment]
I'm a bit confused. You have 2 installations of phpcs and you want to use one, installed in the project. Then use it via `vendor/bin/phpcs` command and problem is solved.

Am I missing something?

**Comment by aik099** [comment]
Ah, the `\AppData\Roaming\Composer ` is what I missed. I guess you've did sort of `composer global update squizlabs/php_codesniffer` command (yes, you can do that without needing to go to any folder).

Then order of system-wide composer's in your environment %PATH% variable compared to pear folder determines which composer installation is used.

**Comment by dingo-d** [comment]
In my `%PATH%` variable I have `\AppData\Roaming\Composer\vendor\bin` this means that I am using that installation whenever I run `phpcs`, right?

**Comment by dingo-d** [comment]
The weird part is that I searched for all `php_codesniffer` folders in my computer, and when checking the versions in the `CodeSniffer.php` all show 2.7.0...

**Comment by aik099** [comment]
> In my %PATH% variable I have \AppData\Roaming\Composer\vendor\bin this means that I am using that installation whenever I run phpcs, right?

if you `echo %PATH%` (I'm on Mac, so I'm just guessing how Windows commands could look like), then you should have not only Composer's bin folder but also PEAR folder. Depending on which of them goes first you'll get either Composer one version or PEAR one.

**Comment by aik099** [comment]
* for PEAR folder is named: `C:\path\to\pear\PHP\CodeSniffer`
* for Composer folder is named: `C:\path\to\composer\vendor\squizlabs\php_codesniffer`

**Comment by dingo-d** [comment]
I echoed it out and I can only see the Composer's path, so I'm guessing that the Composer is pulling the version.

I went to `C:\Users\myname\AppData\Roaming\Composer` and typed `composer info` and it returned 

```
squizlabs/php_codesniffer 2.7.0 PHP_CodeSniffer tokenizes PHP, JavaScript and CSS files and detects violations of a defined set of coding standards.
```

And when checking with `phpcs --version` I still get 2.6.2 returned.

I guess I'll have to clean install everything again :\

**Comment by aik099** [comment]
Maybe you have path combined from different sources (e.g. system one and user one) and the %PATH% is only showing user one, where Composer is. Anyway uninstalling the PEAR version of PHP_CodeSniffer shouldn't hurt because after system reboot now Composer version should be used system wide.
