### ISSUE TITLE
Custom Sniff and PHPCBF support

### ISSUE THREAD

**Issue by PommeVerte** [squizlabs/PHP_CodeSniffer#1160]
Hey guys,

I've gone through the wiki and google and can't find an answer to this question. If it was in plain site and I just missed it please point me in the right direction.

We use some custom sniffs and `phpcbf` does not suggest fixes for the errors generated by our sniffs. I'm guessing that they are outdated and never really supported this feature. Yet I can not find any documentation on how one would proceed to remedy this.

FYI we extend `PHP_CodeSniffer_Standards_AbstractPatternSniff` and provide custom patterns.. so I'm guessing no fixes are submitted. Is this something that could be added eventually? 

Any help would be appreciated.

Cheers.

**Comment by aik099** [comment]
The sniff you mentioned (`PHP_CodeSniffer_Standards_AbstractPatternSniff`) doesn't support automatic fixing.

If in report of `phpcs` reported errors doesn't have `[x]` in `Fixable` column, then particular error can't be auto-fixed.

**Comment by gsherwood** [comment]
> Is this something that could be added eventually?
>
> Nothing I'm afraid. This sniff will eventually be replaced with more specific sniffs (e.g. Squiz standard already have something) that can auto-fix.

I agree. It's far too complex to fix a piece of code just using a second regex. I'm sure it can be done for some code blocks where you are just moving pieces around, but not enough to make it generically useful. I can't see AbstractPatternSniff ever supporting it.

**Comment by PommeVerte** [comment]
Ok thanks guys. That's all I really need to know. I'll look into alternative paths for this. 

Cheers
