### ISSUE TITLE
Absolute report path is treated like a relative path if it also exists within the current directory

### ISSUE THREAD

**Issue by schmittjoh** [squizlabs/PHP_CodeSniffer#1161]
If you pass an absolute report path like this ``--report-checkstyle=/tmp/phpcs-results``, this is still prefixed with the current directory. 

In the 2.x versions, the current path is not prepended when it is absolute already.

**Comment by schmittjoh** [comment]
The 2.x versions seem also to be affected. Further debugging suggests that this error happens if you have a file named ``tmp`` in the current directory based on how the check is currently implemented.

I would suggest to check whether the path starts with a ``/`` as absolute and not prefix with ``getcwd`` in that case. Problematic code paths are here:

- 2.x version: https://github.com/squizlabs/PHP_CodeSniffer/blob/a71771e813541fee035c8c85105dac75dc161d7c/CodeSniffer/CLI.php#L774
- 3.x version: https://github.com/squizlabs/PHP_CodeSniffer/blob/e85ff8a6dc016743d23211e19061a696ae7aa1d3/src/Config.php#L923

**Comment by gsherwood** [comment]
> I would suggest to check whether the path starts with a / and treat it as absolute in that case.

Sounds like a good plan to me.

**Comment by gsherwood** [comment]
Fixed now. Thanks for the report.
