### ISSUE TITLE
JS Tokenizer generates errors when processing some doc comments

### ISSUE THREAD

**Issue by photodude** [squizlabs/PHP_CodeSniffer#1172]
The following custom change in our file comments sniff causes errors when run with -ps 
There is no error if -s is not used for running phpcs

``` php
// We don't use package tags in namespaced code
if ($tag == '@package')
{
    // Check for a namespace token, if certain other tokens are found we can move on. This keeps us from searching the whole file.
    $namespaced = $phpcsFile->findNext(array(T_NAMESPACE, T_CLASS, T_INTERFACE, T_TRAIT), 0); 

    // If we found a namespace token we skip the error, otherwise we let the error happen
    if ($namespaced === T_NAMESPACE)
    {
        continue;
    }
}
```

run this way `phpcs -ps --extensions=js --standard=Joomla --sniffs=Joomla.Commenting.FileComment "path/to/folders"`

``` php
PHP Notice:  Undefined index: */ in C:\Bitnami\joomla-3.6.2-0\php\PEAR\PHP\CodeSniffer\Tokenizers\JS.php on line 726
PHP Stack trace:
PHP   1. {main}() C:\Bitnami\joomla-3.6.2-0\php\phpcs:0
PHP   2. PHP_CodeSniffer_CLI->runphpcs() C:\Bitnami\joomla-3.6.2-0\php\phpcs:25
PHP   3. PHP_CodeSniffer_CLI->process() C:\Bitnami\joomla-3.6.2-0\php\PEAR\PHP\CodeSniffer\CLI.php:113
PHP   4. PHP_CodeSniffer->processFiles() C:\Bitnami\joomla-3.6.2-0\php\PEAR\PHP\CodeSniffer\CLI.php:986
PHP   5. PHP_CodeSniffer->processFile() C:\Bitnami\joomla-3.6.2-0\php\PEAR\PHP\CodeSniffer.php:636
PHP   6. PHP_CodeSniffer->_processFile() C:\Bitnami\joomla-3.6.2-0\php\PEAR\PHP\CodeSniffer.php:1755
PHP   7. PHP_CodeSniffer_File->start() C:\Bitnami\joomla-3.6.2-0\php\PEAR\PHP\CodeSniffer.php:1877
PHP   8. PHP_CodeSniffer_File->_parse() C:\Bitnami\joomla-3.6.2-0\php\PEAR\PHP\CodeSniffer\File.php:474
PHP   9. PHP_CodeSniffer_File::tokenizeString() C:\Bitnami\joomla-3.6.2-0\php\PEAR\PHP\CodeSniffer\File.php:698
PHP  10. PHP_CodeSniffer_Tokenizers_JS->tokenizeString() C:\Bitnami\joomla-3.6.2-0\php\PEAR\PHP\CodeSniffer\File.php:1438
```

**Comment by gsherwood** [comment]
I tried replicating this by cloning the Joomla coding standards, guessing where you made that change and putting it in, then running it over a test JS file. I got no errors, either with or without `-ps`.

Chances are that the code has nothing to do with the error, especially given your stack trace says it happens during initial file tokenizing. I also can't see how `-s` could have any impact because that's only used during the final reporting phase, and your PHPCS run clearly doesn't get there.

It's more likely that the file just isn't tokenizing correctly for some reason, but I'd need the content of the JS file you are checking to confirm that, and to fix this problem.

**Comment by photodude** [comment]
Opps, bad me for forgetting to rerun with -v to try to get the file(s) that had the issue.

the file that errored in processing this way was [joomla-cms\media\editors\codemirror\mode\swift\swift.js](https://github.com/joomla/joomla-cms/blob/staging/media/editors/codemirror/mode/swift/swift.js)

**Comment by gsherwood** [comment]
I can't replicate any errors on that file using any of the built-in sniffs, or the modified Joomla sniff. The tokenizer looks to be working fine on that file.

Do you have any steps I can run to replicate this problem? What version of PHPCS are you running?

**Comment by photodude** [comment]
Here is a link to the current version of our sniff.
https://github.com/photodude/coding-standards/blob/phpcs-2/Joomla/Sniffs/Commenting/FileCommentSniff.php

I'm running phpcs 2.7.0
The only steps I have at this point is our code standard, the specific file, phpcs 2.7.0 and `phpcs -psv --extensions=js --standard=Joomla --sniffs=Joomla.Commenting.FileComment "path to\joomla-cms\media\editors\codemirror\mode\swift\swift.js"`

**Comment by gsherwood** [comment]
I tried running 2.7.0 on that file with that sniff, and cannot reproduce any errors. PHPCS outputs a single error message for the file: `You must use "/**" style comments for a file comment` on line 1.

I tried on a couple of different PHP version as well, so I don't think that's the problem.

I'm really not sure how to reproduce this issue.

**Comment by gsherwood** [comment]
It might also be good if you could run PHPCS with the `-vv` command line argument and paste the output. That will show what the tokenzier is doing and let me compare it to my output.

**Comment by photodude** [comment]
I'm not sure if -vv was helpful since it looks like the error happened at the moment before processing the ruleset
```php
C:\> phpcs -psvv --extensions=js --standard=Joomla --sniffs=Joomla.Commenting.FileComment "F:\path to github\joomla-cms\media\editors\codemirror\mode\swift\swift.js" | Out-File c:\scripts\test.txt
PHP Notice:  Undefined index: */ in C:\path to php\php\PEAR\PHP\CodeSniffer\Tokenizers\JS.php on line 726
PHP Stack trace:
PHP   1. {main}() C:\path to php\php\phpcs:0
PHP   2. PHP_CodeSniffer_CLI->runphpcs() C:\path to php\php\phpcs:25
PHP   3. PHP_CodeSniffer_CLI->process() C:\path to php\php\PEAR\PHP\CodeSniffer\CLI.php:113
PHP   4. PHP_CodeSniffer->processFiles() C:\path to php\php\PEAR\PHP\CodeSniffer\CLI.php:986
PHP   5. PHP_CodeSniffer->processFile() C:\path to php\php\PEAR\PHP\CodeSniffer.php:636
PHP   6. PHP_CodeSniffer->_processFile() C:\path to php\php\PEAR\PHP\CodeSniffer.php:1755
PHP   7. PHP_CodeSniffer_File->start() C:\path to php\php\PEAR\PHP\CodeSniffer.php:1877
PHP   8. PHP_CodeSniffer_File->_parse() C:\path to php\php\PEAR\PHP\CodeSniffer\File.php:474
PHP   9. PHP_CodeSniffer_File::tokenizeString() C:\path to php\php\PEAR\PHP\CodeSniffer\File.php:698
PHP  10. PHP_CodeSniffer_Tokenizers_JS->tokenizeString() C:\path to php\php\PEAR\PHP\CodeSniffer\File.php:1438
PHP Notice:  Undefined index: */ in C:\path to php\php\PEAR\PHP\CodeSniffer\Tokenizers\JS.php on line 726
PHP Stack trace:
PHP   1. {main}() C:\path to php\php\phpcs:0
PHP   2. PHP_CodeSniffer_CLI->runphpcs() C:\path to php\php\phpcs:25
PHP   3. PHP_CodeSniffer_CLI->process() C:\path to php\php\PEAR\PHP\CodeSniffer\CLI.php:113
PHP   4. PHP_CodeSniffer->processFiles() C:\path to php\php\PEAR\PHP\CodeSniffer\CLI.php:986
PHP   5. PHP_CodeSniffer->processFile() C:\path to php\php\PEAR\PHP\CodeSniffer.php:636
PHP   6. PHP_CodeSniffer->_processFile() C:\path to php\php\PEAR\PHP\CodeSniffer.php:1755
PHP   7. PHP_CodeSniffer_File->start() C:\path to php\php\PEAR\PHP\CodeSniffer.php:1877
PHP   8. PHP_CodeSniffer_File->_parse() C:\path to php\php\PEAR\PHP\CodeSniffer\File.php:474
PHP   9. PHP_CodeSniffer_File::tokenizeString() C:\path to php\php\PEAR\PHP\CodeSniffer\File.php:698
PHP  10. PHP_CodeSniffer_Tokenizers_JS->tokenizeString() C:\path to php\php\PEAR\PHP\CodeSniffer\File.php:1438
Processing ruleset C:\path to php\php\PEAR\PHP\CodeSniffer\Standards\Joomla\ruleset.xml
	Adding sniff files from "/.../Joomla/Sniffs/" directory
```
continued in attached file
[test.txt](https://github.com/squizlabs/PHP_CodeSniffer/files/498715/test.txt)

**Comment by photodude** [comment]
I replaced my JS tokenizer file with the current version in the repo and I'm still getting the error. 
I'm going to try replacing the other files listed in the stack trace.

**Comment by photodude** [comment]
I replaced all the files listed in the stack track with the current versions in the repo and I'm still getting the error with any standard and the joomla-cms\media\editors\codemirror\mode\swift\swift.js file (oddly no other file, just that one)

**Comment by gsherwood** [comment]
The line the tokenizer errors occurs on only runs while a piece of JS content is being tokenized. If that happens before the file is being tokenized at all, then it's got nothing to do with the file contents itself.

What this stack trace looks like is that PHPCS is running and processing a file before the main PHPCS run starts. I can't see how this could happen unless you've got a second PHPCS process firing off somewhere.

What would be good to test is if you could:
- go to a completely clean directory somewhere
- clone PHPCS into that dir
- clone the Joomla coding standard into that dir
- copy the swift.js file into the dir
- php PHP_CodeSniffer/scripts/phpcs swift.js --standard=joomla-coding-standards/Joomla

(change paths and dir names as required - I'm going it from memory)

And then see if you get any errors in a completely clean environment running from clones. If you can reproduce an error in that setup, I should be able to reproduce an error (although I can't).

**Comment by photodude** [comment]
I have wiped my local install and started again with rebuilding my local development setup. 

I unfortunately still have this issue. 

I'm going to try to get this to run on Travis CI to see if I can reproduce with a non-windows environment.

**Comment by gsherwood** [comment]
> I have wiped my local install and started again with rebuilding my local development setup.

Did you try my steps above, which is just running PHPCS from the clone, or are you setting up your environment a different way?

**Comment by photodude** [comment]
here is what I did
- I'm installing a fresh bitnami application stack for Joomla (basically installing a form of wamp to run php on windows)
- installing code sniffer with pear on the new stack
- cloning the coding standard into the new pear source directory
- running a test on a copy of the file having an issue.

**Comment by photodude** [comment]
As of PHPCS v2.8.0 I am no longer able to replicate this issue. now I only get a single error message for the file: `You must use "/**" style comments for a file comment on line 1.` which is expected.
