### ISSUE TITLE
Possible to make PHPCS ignore one given rule for a particular file?

### ISSUE THREAD

**Issue by rodrigoprimo** [squizlabs/PHP_CodeSniffer#1179]
I wonder if it is possible to make PHPCS ignore one given rule for a particular file or line of code? Sometimes for different reasons I have to use `// @codingStandardsIgnoreLine` but this will make PHPCS completely ignore the line.

As a example, I would like to be able to do something like `// @codingStandardsIgnoreLine Generic.WhiteSpace.ScopeIndent` to make PHPCS ignore just indentation for the line. Is there a way to do that?

**Comment by gsherwood** [comment]
There is no way to do this using annotations in your files. See issue #604 for a feature request.

You can add exclusions for entire files using a ruleset.xml file. See https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-ruleset.xml for an example of hard-coding exclude patterns for specific sniffs. But you cannot do this for individual lines.

**Comment by systemovich** [comment]
Put this at the top of the file:

`// phpcs:disable PSR1.Classes.ClassDeclaration.MissingNamespace`

**Comment by iltar** [comment]
@systemovich this does not work for me in combination with slevomat, it will either remove the comment or keep complaining. No other solution than to remove it for me.

**Comment by jrfnl** [comment]
@iltar Not sure about the details of your issue, but...
1. You can add the annotation to a file docblock like so:
    ```php
    <?php
    /**
     * File description
     *
     * @tags
     * @phpcs:disable Standard.Cat.SniffName
     */
    ```
2. You can exclude a file for a particular rule or errorcode from a custom ruleset:
    ```xml
    <rule ref="Standard.Cat.SniffName.ErrorCode">
        <exclude-pattern>/path/to/file\.php</exclude-pattern>
    </rule>

**Comment by iltar** [comment]
@jrfnl That seems to work, thanks!

**Comment by bkdotcom** [comment]
Now we just need the ability to do it at the class and method level

**Comment by tiagofrancafernandes** [comment]
> Put this at the top of the file:
> 
> `// phpcs:disable PSR1.Classes.ClassDeclaration.MissingNamespace`

Can you show a example?

**Comment by jrfnl** [comment]
@tiagofrancafernandes See https://github.com/squizlabs/PHP_CodeSniffer/issues/1179#issuecomment-446988725

**Comment by darius-v** [comment]
> @iltar Not sure about the details of your issue, but...
> 
> 1. You can add the annotation to a file docblock like so:
>    ```
>    <?php
>    /**
>     * File description
>     *
>     * @tags
>     * @phpcs:disable Standard.Cat.SniffName
>     */
>    ```
> 2. You can exclude a file for a particular rule or errorcode from a custom ruleset:
>    ```
>    <rule ref="Standard.Cat.SniffName.ErrorCode">
>        <exclude-pattern>/path/to/file\.php</exclude-pattern>
>    </rule>
>    ```

is the @tags needed? or this is just example of other random tags? I tried without @tags and for me it did not work

**Comment by darius-v** [comment]
> @systemovich this does not work for me in combination with slevomat, it will either remove the comment or keep complaining. No other solution than to remove it for me.

I also cannot make it work with 

SlevomatCodingStandard.TypeHints.DeclareStrictTypes rule unless I add exclude pattern tag in phpcs.xml

**Comment by jrfnl** [comment]
> is the @tags needed? or this is just example of other random tags? I tried without @tags and for me it did not work

`@tags` was just an example of other random tags and should not be needed.
