### ISSUE TITLE
update homepage in pear package

### ISSUE THREAD

**Issue by glensc** [squizlabs/PHP_CodeSniffer#1184]
please set homepage in
http://pear.php.net/package/PHP_CodeSniffer

current one points to http://www.squizlabs.com/php-codesniffer
whose latest post is about 2.2.0, that's from last year!

**Comment by gsherwood** [comment]
That's the home page for now. Eventually I hope to have a new site where I can migrate that content and provide more, but I haven't had time so far this year.
