### ISSUE TITLE
 Undefined index: scope_condition in Standards/PSR2/Sniffs/ControlStructures/SwitchDeclarationSniff.php on line 157, PHP_CodeSniffer version 2.5.1

### ISSUE THREAD

**Issue by puggan** [squizlabs/PHP_CodeSniffer#1185]
When running phpcs (2.5.1) on some old code, I get alot of:

> PHP Notice:  Undefined index: scope_condition in /usr/share/php/PHP/CodeSniffer/Standards/PSR2/Sniffs/ControlStructures/SwitchDeclarationSniff.php on line 157

and

> PHP Notice:  Undefined index: scope_condition in /usr/share/php/PHP/CodeSniffer/Standards/Squiz/Sniffs/ControlStructures/SwitchDeclarationSniff.php on line 172

**Comment by puggan** [comment]
Tested to remove code while keeping the error, ended up with the same failer on this bit of code:
```
<?php
        $a = 1;
        switch ($a)
        {
                case 3:         // a comment
                default :
                {
                        break;
                }
        }
```

**Comment by aik099** [comment]
Does same happen with PHP_CodeSniffer 2.7.0 (latest release)?

**Comment by puggan** [comment]
cloned it, and no error in the current master, did a bisect, and found
407959dc28adbd24a636be656cc45f823c6cfefb

so this Issue is a duplicate of #887
