### ISSUE TITLE
XML report throws invalid character value error for some file paths

### ISSUE THREAD

**Issue by vceratti** [squizlabs/PHP_CodeSniffer#1189]
Im using PHP Storm and since last version (2016.2.1) phpcs was not working properly, giving me this warnkings:

phpcs: Warning: XMLWriter::writeAttribute(): invalid character value in C:\Projects\composer\vendorsquizlabs\php_codesniffer\CodeSniffer\Reports\Xml.php on line 66

PHP Warning:  XMLWriter::writeAttribute(): invalid character value in C:\Projects\composer\vendor\squizlabs\php_codesniffer\CodeSniffer\Reports\Xml.php on line 66

After some checks, o found the problem was with my temp path name. It turns out my user path has an accent (bad idea, many problems...): "C:\Users\Vinícius\AppData\Local\Temp... " 

For me, changing \Reports\XML.php line 66 to: 

$out->writeAttribute('name', utf8_encode($report['filename']));

...solved the problem

This is hapenning php_codesniffer 2.7.0

**Comment by gsherwood** [comment]
Associated PEAR bug report: http://pear.php.net/bugs/bug.php?id=21035

**Comment by ktomk** [comment]
I think it is crucial that you check all paths in your project to be from the *portable character set* (see POSIX).

PHPCS can decline to operate on paths which are not portable. It actually does as this report shows, however the report should be done more upfront with a more clear warning/error message so that this is less unexpected.

**Comment by gsherwood** [comment]
I couldn't ever replicate this, but I could replicate invalid chars appearing in the XML output. I fixed that by telling XMLWrite what the encoding of the document is, so I'm hoping that also fixes this issue without having to UTF-8 encode manually.

Are you able to apply the change manually and see if it works for you? I know this change is for version 3, but it should be the same change for version 2.

**Comment by gsherwood** [comment]
Closing as I've at least fixed one issue. If it still doesn't work with this change, please comment or open a new issue.
