### ISSUE TITLE
Javascript sniffer fails with function called "Function"

### ISSUE THREAD

**Issue by gsouf** [squizlabs/PHP_CodeSniffer#1191]
Running php code sniffer on javascript file that has the function ``Function`` will detect it as the ``keyword`` function. See the example:

```js 
var a = Function('return 1+1');
```

Code fixer returns this error:

```
Expected 1 space after FUNCTION keyword; 0 found (Squiz.Functions.MultiLineFunctionDeclaration.SpaceAfterFunction)
```
But this line is actually correct and there is no fix needed

**Comment by gsherwood** [comment]
Just out of interest, do you actually define a function called `Function` or were you just looking for ways to trick the tokenizer? It would be nice to know if there is some real code that it had trouble parsing.

**Comment by gsherwood** [comment]
Thanks for the report. Still keen to know if the code is real or not.

**Comment by gsouf** [comment]
Hi @gsherwood yes the code is real, I'm using the javascript [function ``Function``](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Function) in order to provide a way to send user defined functions from a php string to a phantomjs running webpage; https://github.com/gsouf/phantomphp/blob/master/src/phantom/page.handlers.js#L71

**Comment by gsouf** [comment]
Btw thanks for the fix, I will check soon for the fix

**Comment by gsherwood** [comment]
> Hi @gsherwood yes the code is real

Thanks for confirming that. Please let me know if the fix doesn't work for you, although I did test the file you linked (minus the `@codingStandardsIgnore` comments) and confirmed the error is no longer shown.
