### ISSUE TITLE
Checkstyle XML output and Jenkins

### ISSUE THREAD

**Issue by lyda** [squizlabs/PHP_CodeSniffer#1192]
The [Jenkins](https://jenkins.io) checkstyle [plugin](https://wiki.jenkins-ci.org/display/JENKINS/Checkstyle+Plugin) is a nice tool for tracking a project's health.

However [phpcs](https://github.com/squizlabs/PHP_CodeSniffer/)'s `checkstyle` report option apparently misses a `description` tag that the plugin wants. There's a rather [old bug](https://issues.jenkins-ci.org/browse/JENKINS-20516) about this issue in the checkstyle plugin's issue tracker.

The last update to it (I'll link in this issue to it):

> Right now it appears, that http://pear.php.net/package/PHP_CodeSniffer/ doesn't add anything as a description.
> 
> However maybe adding actual Sniff name used (the PHP class name that did the check) as a description might be used.
> 
> This however needs to be implemented on PHP_CodeSniffer side.

Would it be possible to add that tag?

**Comment by gsherwood** [comment]
I'm not sure what actually needs to be added, but I would certainly add it if I knew.

If this is the still the current XML logger for checkstyle (https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java) then it doesn't have a description field per message. The message content is contained within the "message" attribute and the code for the sniff is contained within the "source" attribute.

This is exactly what PHPCS does as well, so I'm not sure what changes would be needed. It almost seems like a completely different format is expected.

**Comment by aik099** [comment]
I'm guessing there is new `<description>` or similar node, that by sniff error code returns general error message. Not sure if PHP_CodeSniffer even has this kind of message stored for every error code.

Maybe the Checkstyle Jenkins plugin has hardcoded descriptions by Java error codes and since they don't match any of PHP_CodeSniffer errors it shows that `no description` text.

**Comment by lyda** [comment]
I'll see if I can find a sample checkstyle file that java's checkstyle emits...

**Comment by gsherwood** [comment]
Closing as it appears the issue was with the plugin itself and not the checkstyle format (see linked bug in original post).
