### ISSUE TITLE
Pear install failing

### ISSUE THREAD

**Issue by ChrisWiegman** [squizlabs/PHP_CodeSniffer#1197]
While pear can find PHP_CodeSniffer I've been unable to install it on Ubuntu 16.04 or Ubuntu 1404 for the last week. Here's what I'm running

`pear search codesniffer
Retrieving data...0%
# Matched packages, channel pear.php.net:

Package         Stable/(Latest) Local
PHP_CodeSniffer -n/a- (stable)        PHP_CodeSniffer tokenizes PHP, JavaScript and CSS files to detect and fix violations of a defined set of coding standards.`

and then install gives

`pear install PHP_CodeSniffer
No releases for package "pear/PHP_CodeSniffer" exist
install failed`

Is there something here I'm missing?

**Comment by aik099** [comment]
Maybe you need to update channel protocols?

**Comment by ChrisWiegman** [comment]
Tried that. Still no luck

**Comment by gsherwood** [comment]
I have no idea. I've seen it before too, but it resolved itself with no changes from me. I tried it again this morning to ensure it is still working on my setup, and it is:
```
$ pear install php_codesniffer
downloading PHP_CodeSniffer-2.7.0.tgz ...
Starting to download PHP_CodeSniffer-2.7.0.tgz (511,841 bytes)
.......................................................................................................done: 511,841 bytes
install ok: channel://pear.php.net/PHP_CodeSniffer-2.7.0
```
The PEAR website also still shows quite a lot of PEAR installs of PHP_CodeSniffer, so it's probably not a core problem with the package or PEAR.

I don't have any experience working with PEAR directly, so I don't think I can help you get it working.

You can install from a git clone though:
```
git clone https://github.com/squizlabs/PHP_CodeSniffer.git
cd PHP_CodeSniffer
pear install package.xml
```
I found this to work even when PEAR was playing up for me.

**Comment by ChrisWiegman** [comment]
Thanks. I hadn't tried the clone with pear. I'll give it a shot
