### ISSUE TITLE
Github pages 

### ISSUE THREAD

**Issue by flashinnl** [squizlabs/PHP_CodeSniffer#1199]
Looks like the Github Pages site is down? Can't download the binaries there unfortunately. 

https://squizlabs.github.io

**Comment by aik099** [comment]
You can also download release from GitHub itself: https://github.com/squizlabs/PHP_CodeSniffer/releases

**Comment by gsherwood** [comment]
There never was a site at https://squizlabs.github.io - that would be the Github pages site for the Squizlabs organisation.

The Github pages site for this repo is: https://squizlabs.github.io/PHP_CodeSniffer

That site is an analysis of coding conventions, although the latest Phar files are also hosted there. Their URLs are in the README.

**Comment by flashinnl** [comment]
Yes thanks!

That was my point. The phar files were not available there, seems to be working now :+1 thanks
