### ISSUE TITLE
possible to Sniff smarty templates php code inside {php}

### ISSUE THREAD

**Issue by designerno1** [squizlabs/PHP_CodeSniffer#1204]
is it possible to sniff code with the extensions set to html inside smarty php tags

```
{php}
session_register('name');
{/php}
```

fir example

**Comment by gsherwood** [comment]
PHPCS will not detect PHP code inside tags that look like that, so no, it is not possible to sniff Smarty template code.

**Comment by designerno1** [comment]
ok any workaround on this?

**Comment by MarkMaldaba** [comment]
Could another tokenizer reasonably be added?  Or some kind of pre-transform?

**Comment by gsherwood** [comment]
A tokenizer for Smarty templates could be added. But I know nothing about Smarty templates or what sort of tokenizing would be required within them to make it useful (including new Smarty-specific tokens) so I could not ever consider adding this myself.

An alternative is to write a wrapper for PHPCS that takes the template file, replaces the {php} syntax with standard PHP tags, then feeds that into PHPCS for checking. Presumably, you'd at least get standard PHPCS checks running for that.

**Comment by gsherwood** [comment]
I'm going to close this as I can't see myself ever getting around to it. But if anyone wants to work on it, please let me know.

**Comment by MarkMaldaba** [comment]
Is it not worth leaving open with a tag indicating that it requires a third-party to implement it?  That's what I've seen other projects do with useful features that they would accept a PR for but which they don't plan on implementing themselves.
