### ISSUE TITLE
Ignoring unused parameters when implementing PSR-7

### ISSUE THREAD

**Issue by skyzyx** [squizlabs/PHP_CodeSniffer#1209]
The specific issue I'm running into is that I always want to catch when I've added an unused variable to a function/method, but I end up adding unused variables a lot when implementing the [PSR-7](http://www.php-fig.org/psr/psr-7/) [middleware](http://weierophinney.github.io/2015-10-20-PSR-7-and-Middleware/#/43).

```php
function (
    ServerRequestInterface $request,
    ResponseInterface $response,
    callable $next
) : ResponseInterface
```

I follow this pattern, but I don't always _use_ all of these parameters, and CodeSniffer warns on them.

```
----------------------------------------------------------------------
FOUND 0 ERRORS AND 10 WARNINGS AFFECTING 8 LINES
----------------------------------------------------------------------
  36 | WARNING | The method parameter $request is never used
  36 | WARNING | The method parameter $args is never used
  48 | WARNING | The method parameter $request is never used
  66 | WARNING | The method parameter $request is never used
  66 | WARNING | The method parameter $args is never used
  78 | WARNING | The method parameter $request is never used
  90 | WARNING | The method parameter $request is never used
  95 | WARNING | The method parameter $request is never used
 107 | WARNING | The method parameter $request is never used
 119 | WARNING | The method parameter $args is never used
----------------------------------------------------------------------
```

Would it be possible to add a new rule to CodeSniffer which allows the _unused variables_ rule to ignore those that are accepting PSR-7 values? Or some way to flag it as `@psr7` or something?

----
/cc @smoshysmosh

**Comment by gsherwood** [comment]
> Would it be possible to add a new rule to CodeSniffer which allows the unused variables rule to ignore those that are accepting PSR-7 values?

I can't see how this could be done in a clean way.

These are just warnings anyway - there for you to do a manual review to determine if you want to change anything. If you've determined that this file doesn't need those warnings (either the whole sniff or just a single message), you could modify your ruleset.xml file and ignore that file, directory, or a pattern of files.

The examples of this from the [annotated ruleset](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-ruleset.xml) are:
```xml
 <!--
    You can hard-code ignore patterns for specific sniffs,
    a feature not available on the command line. Please note that
    all sniff-specific ignore patterns are checked using absolute paths.

    The code here will hide all messages from the Squiz DoubleQuoteUsage
    sniff for files that match either of the two exclude patterns.
 -->
 <rule ref="Squiz.Strings.DoubleQuoteUsage">
    <exclude-pattern>*/tests/*</exclude-pattern>
    <exclude-pattern>*/data/*</exclude-pattern>
 </rule>

 <!--
    You can also be more specific and just exclude some messages.
    Please note that all message-specific ignore patterns are
    checked using absolute paths.

    The code here will just hide the ContainsVar error generated by the
    Squiz DoubleQuoteUsage sniff for files that match either of the two
    exclude patterns.
 -->
 <rule ref="Squiz.Strings.DoubleQuoteUsage.ContainsVar">
    <exclude-pattern>*/tests/*</exclude-pattern>
    <exclude-pattern>*/data/*</exclude-pattern>
 </rule>
```
