### ISSUE TITLE
Configuration options - eslint?

### ISSUE THREAD

**Issue by dingo-d** [squizlabs/PHP_CodeSniffer#1210]
I used JSHint for my linting so far, but the more I read I can see that ESLint is becoming more and more popular. In the [config wiki](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options) I only see that the mentioned several linters (CSSLint, JSHint, JSLint...), but no mention of ESLint.

Does this means that you do not support ESLint, or can I simply do 
```
phpcs --config-set eslint_path ... path to linter ...
```

and it will work, or should I just stick with JSHint when sniffing php files?

**Comment by gsherwood** [comment]
The other linters have config setting because there are sniffs within PHPCS that use those linters (the JSHint one is here: https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/Generic/Sniffs/Debug/JSHintSniff.php).

There is no sniff included with PHPCS that uses ESLint, so there is no config option for it. That means you can't currently use PHPCS with ESLint.

I'll leave this as a feature request to add a sniff to support ESLint.

**Comment by dingo-d** [comment]
Thanks for clearing it up :)

**Comment by rmccue** [comment]
I [wrote a sniff for ESLint](https://github.com/humanmade/coding-standards/blob/master/HM/Sniffs/Debug/ESLintSniff.php) for our coding standards, happy to contribute it as a PR if you want one?

**Comment by grappler** [comment]
I would like to use the Sniff for ESLint.

@gsherwood Could you give a confirmation that you would like a PR otherwise I will ask @rmccue to make a PR to the WordPress coding standards. Thanks :)

**Comment by gsherwood** [comment]
> Could you give a confirmation that you would like a PR

If the sniff was changed to drop the constant, and @rmccue was ok with using the copyright and licence from PHPCS, then I'd be happy to look at a PR for an ESLint sniff.

**Comment by rmccue** [comment]
Happy to clean up and submit a PR, will try and do that this week 👍

**Comment by jrfnl** [comment]
@rmccue Looking forward to the PR. Any idea on when it can be expected ?

**Comment by rmccue** [comment]
PR is up at #1374. :)

**Comment by alexdesignworks** [comment]
so how to actually pass CLI config options to ESLint itself? Or at least a path to `.eslintrc.json`?

**Comment by grappler** [comment]
@alexdesignworks There is [a line of code](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/Generic/Sniffs/Debug/ESLintSniff.php#L69) that tries to work out where you have included the config file.

If that does not work for you could you extend the `ESLintSniff` Class and override the `$configFile` property. 

Or define the following in your `phpcs.xml` config file.

```xml
<rule ref="Generic.Debug.ESLint">
	<properties>
		<property name="configFile" value="your/lint/.eslintrc.jsonl"/>
	</properties>
</rule>
```

@gsherwood It may be a good idea to document this here: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options#generic-coding-standard-configuration-options

**Comment by gsherwood** [comment]
> It may be a good idea to document this

Thanks. I obviously missed that sniff while documenting sniff properties. It is now documented here: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Customisable-Sniff-Properties#genericdebugeslint
