### ISSUE TITLE
Start CS programmatically without CLI code

### ISSUE THREAD

**Issue by mniewrzal** [squizlabs/PHP_CodeSniffer#1215]
I'm trying to use Code Sniffer with php-language-server. Initial integration was easy but recently we noticed an [issue](https://github.com/felixfbecker/php-language-server/issues/144) that is breaking whole language server. Language server is using stdin/stdout to communicate with client (e.g. VSCode) but Code Sniffer is also trying to read parameters from stdin (see https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/CLI.php#L407). This somehow is breaking php-language-server and make it unresponsive. So my main question is if there is an option to use Code Sniffer programmatically without triggering code related to CLI.

**Comment by gsherwood** [comment]
> So my main question is if there is an option to use Code Sniffer programmatically without triggering code related to CLI.

Not in the 2.x versions. They always attempt to read from STDIN.

Try the 3.x versions (current one is 3.0.0RC1, or grab latest from the 3.0 branch) as they will only read from STDIN if you pass a `-` on the command line. Plus, that version is a complete rewrite of the CLI code and is easier to call programatically as well.

**Comment by mniewrzal** [comment]
Thanks, I will try it.

**Comment by mniewrzal** [comment]
I was able to use version 3.0.0RC1. My code looks like this:
```php
        $config = new Config(['dummy'], false);
        $file = new File(null, new Ruleset($config), $config);
        $file->setContent($content);
        $file->process();
        $fixed = $file->fixer->fixFile();
```
I have two problems:
* need to create not empty dummy array to prevent Config from reading stdin
* I don't know how set default standard to PSR2 and how I can set path to custom configuration file

**Comment by gsherwood** [comment]
@mniewrzal Should have linked this as it might help: https://gist.github.com/gsherwood/aafd2c16631a8a872f0c4a23916962ac

**Comment by mniewrzal** [comment]
Thanks for snippet. My final version looks like this:
```php
        if (defined('PHP_CODESNIFFER_CBF') === false) {
            define('PHP_CODESNIFFER_CBF', true);
        }

        if (defined('PHP_CODESNIFFER_VERBOSITY') === false) {
            define('PHP_CODESNIFFER_VERBOSITY', false);
        }

        $path = uriToPath($uri);
        $config = new Config(['dummy'], false);
        $config->standards = self::findConfiguration($path);

        // Create this class so it is autoloaded and sets up a bunch
        // of PHP_CodeSniffer-specific token type constants.
        new Tokens();

        $file = new DummyFile($content, new Ruleset($config), $config);
        $file->process();
        $fixed = $file->fixer->fixFile();
        $file->fixer->getContents()
```
Its not pretty but it works. `Runner` class was not usable for me because `init()` is private.

**Comment by gsherwood** [comment]
> Runner class was not usable for me because init() is private.

You'll want to use the current 3.0 branch, where that method has been made public. That change will be released in RC2.

**Comment by mniewrzal** [comment]
Ok, thanks.
