### ISSUE TITLE
Function/Variable: short/long phpDoc

### ISSUE THREAD

**Issue by f3l1x** [squizlabs/PHP_CodeSniffer#1216]
Hi guys.

I have a little problem, perhaps I don't know how to define it in ruleset.

I would prefer this:
```
/**
 * @return int
 */
protected function foo()
```

Instead of this:
```
/** @return int */
protected function foo()
```

-----

And also I would like to allow both of following:

```php
/** @var int */
private $a;
```

```php
/** 
 *@var int 
 */
private $b;
```

-----

Can you help me please? Thank you very much.

**Comment by gsherwood** [comment]
For the first problem, you can include the two sniffs `Squiz.Commenting.DocCommentAlignment` and `Generic.Commenting.DocComment` in a ruleset.xml file along with your other checks. This will throw errors for your first code block and allow `phpcbf` to automatically reformat your code blocks as well.

For the second problem, there are no sniffs that allow those formats. Including the two sniffs that I mentioned above will also throw errors for your last two code blocks and reformat them like this:
```php
/**
 * @var int
 */
private $a;

/**
 * @var int
 */
private $b;
```
