### ISSUE TITLE
Override PHP7+ sniffs via command line flag

### ISSUE THREAD

**Issue by darcyrush** [squizlabs/PHP_CodeSniffer#1217]
So I am in a situation where I need to run PHP7 on my machine in order to use my IDE (VS code) but develop across many tens of projects which all run PHP5. This means the CLI must run PHP7 as I develop and test.

As such, when my automated test suite runs through command line I get hundreds of PHP7 specific errors

> Type hint "string" missing 

Initially I tried ignoring this specific sniff but [was informed][1] that only the group that sniff belongs to can be ignored from command line. This is undesirable since I only want to ignore this explicit sniff rather than the other rules in that group.

The suggested answer was to edit the `ruleset.xml` file to ignore that single sniff and have separate ruleset files for PHP5 and PHP7. This too is not desirable as we work on lots of projects and this would mean editing every single one and testing the results with our docker CI images. We run docker CI images for both PHP5 and PHP7 on every project (in preparation for upgrading far in the future) using the same codebase and having to make separate rulesets and set them up individually for every CI environment is simply not an option.

One remaining option is to write a bash script to filter out these sniffs locally but I feel this functionality would be appreciated by others. Visual Studio code is slowly becoming fairly feature complete in relation to PHP support (the PHP intellisense plugin requires PHP7+) while sublime ecosystem seems to be slowly dying. I don't think I am the only person using a free IDE to develop.

As such, I feel the request of either allowing specific sniffs to be ignored via command line or the ability to 'force' PHP5 sniffs when running PHP7 via command line flag to be a fair request.

[1]: http://stackoverflow.com/questions/40467940/phpcs-exclude-sniffs-not-working

**Comment by boesing** [comment]
I am experiencing the same issue. There might be a way to specify which PHP Version should be tested against. I actually use PHPStorm as my IDE and therefore the IDE is running the sniffs during development. In PHPStorm I can specify either if I am developing PHP 5.5, 5.6, 7.0, e.g.

Therefore an automatted way to specify the version running against might pretty easy, there is just missing the way to handle this within Codesniffer.

I've created a PR #1395 which can overwrite PHP Version if passed by long parameter `--phpVersion=5.6`.

**Comment by jrfnl** [comment]
@boesing The PHP Version can already be overruled.... `$ phpcs --config-set php_version 50403`

See: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options#setting-the-php-version
Was added in: https://github.com/squizlabs/PHP_CodeSniffer/pull/1104

**Comment by boesing** [comment]
My fault, didnt dig that deep into the code.

**Comment by jrfnl** [comment]
@boesing Happens to the best of us ;-)

**Comment by gsherwood** [comment]
Sorry, it looks like I missed this.

Yes, this feature exists via the `php_version` configuration option. My stackoverflow answer was very generic. But if you're wanting to limit things to this message, the PHP version setting should do the trick.

If you don't want to set it as a config option, you can also use `phpcs --runtime-set php_version 50403 ...` to set it for a single run of PHPCS only.
