### ISSUE TITLE
CASE conditions using class constants named NAMESPACE/INTERFACE/TRAIT etc are incorrectly tokenized

### ISSUE THREAD

**Issue by felixfbecker** [squizlabs/PHP_CodeSniffer#1218]
https://travis-ci.org/felixfbecker/php-language-server#L189

**Comment by gsherwood** [comment]
I ran your phpcs.xml file over that file from the error message using 2.7.0, 3.0.0RC1 and both the master and 3.0 branches and I can't replicate any problems.

I've also cloned your repo and run PHPCS directly inside it to see if it is an integration issue, and I get no errors.

I've tried PHP 7 and PHP 5 version, with no difference either.

Is this an error you can actually reproduce?

**Comment by felixfbecker** [comment]
Yes, it happens locally and in CI, on the `completion` branch.

**Comment by gsherwood** [comment]
Thanks. I missed the branch name. Strangely, Travis shows master as the branch for that failed build, but that's obviously not the case.

**Comment by gsherwood** [comment]
Smallest bit of code to replicate:
```php
switch ($foo) {
    case Foo::NAMESPACE:
        return true;
}
```

**Comment by gsherwood** [comment]
Thanks for the report. It has been fixed.

I've moved the code that determines that `NAMEPSACE` (etc) in `Foo::NAMESPACE` from the second pass to the first pass so that scope matching works correctly.

**Comment by felixfbecker** [comment]
any ETA for a release containing the fix?

**Comment by gsherwood** [comment]
> any ETA for a release containing the fix?

Hopefully next week.

**Comment by felixfbecker** [comment]
@gsherwood I need to merge that PR, but it breaks the build because of this bug. Tried updating to latest master, but apparently the `Config` class was removed?

**Comment by gsherwood** [comment]
The Config class doesn't exist in the master branch. It's a new class in 3.x, so you'd want to pull from the 3.0 branch.

**Comment by felixfbecker** [comment]
Thanks, it works now

**Comment by felixfbecker** [comment]
I really need this fix and depending on the dev branch broke my builds multiple times now. Could you tag a new RC?
