### ISSUE TITLE
cant get it working

### ISSUE THREAD

**Issue by saltnpixels** [squizlabs/PHP_CodeSniffer#1220]
I used composer and for some reason i cannot access it globally?
What did I do wrong?
I was in the path ~/.composer/vendor/bin/ and then I ran the require global code and now when i type phpcs I get no such command.

Im on mac osx

**Comment by PatrickRose** [comment]
Is that directory in your path?

**Comment by aik099** [comment]
1. can you echo value of `PATH` to confirm, that `~/.composer/vendor/bin` is really there?
2. is `phpcs` symlink present in `~/.composer/vendor/bin` folder?
3. I was using `composer global require squizlabs/php_codesniffer` command

**Comment by saltnpixels** [comment]
my $path echoes back:
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

**Comment by aik099** [comment]
Then you don't have `~/.composer/vendor/bin` in your PATH. That's why it doesn't work.

**Comment by saltnpixels** [comment]
I ran this:
echo 'export PATH="$PATH:$HOME/.composer/vendor/bin"' >> ~/.bashrc

and now i do!

**Comment by gsherwood** [comment]
This isn't a PHPCS issue - so it's probably best to get help from the composer project if you are still having problems. But it seems like it might be solved now anyway.

If not, and PHPCS is running via composer but not actually working, please let me know and I'll take a look into it.
