### ISSUE TITLE
Default config file location

### ISSUE THREAD

**Issue by sminnee** [squizlabs/PHP_CodeSniffer#1223]
It would be of benefit if you could define the result of a `phpcs` call without arguments for your project.

For example, eslint lets you define an `.eslintrc` file.

This could either take the form of a default location for a ruleset.xml file, or a new file such as `.phpcsrc` that would provide default values for arguments.

Some benefits of this:

 * newcomers to a project don't need to guess at the right command to run to lint their code
 * IDEs could make use of project-specific linting settings by consistently running phpcs without a standard argument.

Does this feature already exist? If not, could we add it? What approach would be preferred by the maintainers?

**Comment by gsherwood** [comment]
Yes, this feature exists. The file is called phpcs.xml (or phpcs.xml.dist) and is documented here: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#using-a-default-configuration-file

**Comment by sminnee** [comment]
Ah thanks, perfect! Sorry, I googled around a bit and didn't find the docs ref ;-)
