### ISSUE TITLE
Composer bin path

### ISSUE THREAD

**Issue by knockoutMice** [squizlabs/PHP_CodeSniffer#1225]
The readme suggests to add **~/.composer/vendor/bin** into $PATH, but it the bin path could be different, in my case it's: **~/.config/composer/vendor/bin** (debian-testing)

You can check the composer bin path with the following command:

`composer global config bin-dir --absolute`

I think it should be added to the readme.

**Comment by gsherwood** [comment]
Good suggestion - I've updated the README. Thanks.
