### ISSUE TITLE
Warning for translate triggers class function

### ISSUE THREAD

**Issue by thomasplevy** [squizlabs/PHP_CodeSniffer#1226]
I have a class function in my plugin:

`abstract class myclass {
    public function translate( $key ) {}
}
`

This function doesn't do anything by default, but allows extending classes to pull a database value by `$key` and translate it. The extending classes ultimately run through some WP core i18n function like `__()`

During PHPCS runs this function triggers the i18nSniff error: The $text arg should be single a string literal, not "$key".

I see that some sniffs -- the "DontExtract" for example -- seem to allow this pattern, but this translate function doesn't follow the pattern

I tried to figure out how to rewrite the tests to allow for this exception to submit a PR but after some digging and attempts I decided I am not qualified to do so. Sorry...

Thanks,

**Comment by gsherwood** [comment]
The sniffs you are talking about are not included with PHP_CodeSniffer. They are custom sniffs written for whatever coding standard you are using, so you'll need to open a bug report for the standard.

From the sniff names, I think you might be using the WordPress coding standard, so you can submit a report at their repo: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards
