### ISSUE TITLE
Defined XML namespace

### ISSUE THREAD

**Issue by bradynpoulsen** [squizlabs/PHP_CodeSniffer#1227]
Is there a defined XML namespace for `phpcs.xml` files? If so, what is a web link that I can access if from?

**Comment by gsherwood** [comment]
There isn't one. The format is quite simple, and it shown here: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Reporting#printing-an-xml-report

**Comment by gsherwood** [comment]
Note that the link above is wrong. The proper link is: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-ruleset.xml

`phpcs.xml` files are `ruleset.xml` files, just with a specific name that lets PHPCS auto-detect them.

**Comment by bradynpoulsen** [comment]
So that would be used as such:
```xml
<?xml version="1.0" ?>
<ruleset xmlns="https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-ruleset.xml">
    <!-- ... -->
</ruleset>
```

**Comment by gsherwood** [comment]
No, there is no namespace link that can be used, as I mentioned above. The link was pointing to the documentation for the XML report and not the ruleset.xml format.

**Comment by bradynpoulsen** [comment]
Why can't that be used as a namespace link? Namespace URIs don't have to encoded or formatted documents. They can be human readable documentation on what the different elements mean. Which, that appears to be the closest documentation beside the source code itself

**Comment by gsherwood** [comment]
If you don't want to use it for validation, the yes, that's the link.

**Comment by bradynpoulsen** [comment]
Hmm, it doesn't really validate since 'ruleset' is unknown, but you win some and lose some without a full schema I guess.
