### ISSUE TITLE
[Feature request] Sniffer for `!` operator

### ISSUE THREAD

**Issue by chris-fa** [squizlabs/PHP_CodeSniffer#1229]
The Laravel community adopts a convention where the negation operator have one space before the variable it negates, improving readability and easy scan through the code. Example:

```
if (! $this->auth->isLogged() {

}
```

I didn't find a sniffer for that so I thought creating a feature request.

**Comment by aik099** [comment]
This is already implemented. Connect `Generic.Formatting.SpaceAfterNot` sniff to your standard.

**Comment by chris-fa** [comment]
Yay :D
