### ISSUE TITLE
PHPCS Fatal Error HHVM-3.15.3

### ISSUE THREAD

**Issue by aftabnaveed** [squizlabs/PHP_CodeSniffer#1232]
When trying to execute phpcs through hhvm version 3.15.3  I get this fatal error

`Fatal error: syntax error, unexpected '`' in phar://phpcs.phar/CodeSniffer/CLI.php on line 34
`

I am not sure if the issue has been reported before. I apologize if it has been already.

**Comment by aik099** [comment]
There is a comment on 34th line: https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/CLI.php#L34 . That's strange.

1. what PHP_CodeSniffer version are you using
2. does the same happen if you use non-phar code of same version
3. does the same happen if you use non-phar code from `master` branch
?

**Comment by aftabnaveed** [comment]
I copied this from the installation README curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar

I would assume this is the latest phar version.

**Comment by gsherwood** [comment]
I don't have a HHVM installation to test this right now, so it's best if you try and run PHPCS directly from a git clone and see if you get a more accurate error message, or if it works.
```
git clone https://github.com/squizlabs/PHP_CodeSniffer.git
cd PHP_CodeSniffer
hhvm scripts/phpcs ...
```

**Comment by aftabnaveed** [comment]
This seems to work now. 

Thank you
