### ISSUE TITLE
DisallowShortOpenTagSniff inconsistent with "short_open_tag" in php.ini

### ISSUE THREAD

**Issue by mindplay-dk** [squizlabs/PHP_CodeSniffer#1234]
It appears the [`DisallowShortOpenTagSniff`](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/Generic/Sniffs/PHP/DisallowShortOpenTagSniff.php) inspection is inconsistent with the behavior of the `short_open_tag` setting in php.ini.

According to the [manual entry](http://php.net/manual/en/ini.core.php#ini.short-open-tag):

> This directive also affected the shorthand `<?=` before PHP 5.4.0, which is identical to `<? echo`. Use of this shortcut required `short_open_tag` to be on. Since PHP 5.4.0, `<?=` is always available

This aligns with the [PSR-1](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-1-basic-coding-standard.md) code standard as well, which states that:

> Files MUST use only `<?php` and `<?=` tags

Presently, it appears there is no way to configure a matching inspection in CS - it seems to be an "all or nothing" inspection, e.g. disallowing both `<?` and `<?=` as though they were one thing, which doesn't align with either `short_open_tags = off` or the PSR-1 code standard.

**Comment by gsherwood** [comment]
The PSR1 coding standard's ruleset has this is it:
```
 <!-- PHP code MUST use the long <?php ?> tags or the short-echo <?= ?> tags; it MUST NOT use the other tag variations. -->
 <rule ref="Generic.PHP.DisallowShortOpenTag.EchoFound">
  <severity>0</severity>
 </rule>
```
That just allows short echo syntax. You could do the same thing if you want.

From version 3.0, you can just include the single message instead of the whole sniff + an exclusion:
```
<rule ref="Generic.PHP.DisallowShortOpenTag.Found" />
```
Does that help?
