### ISSUE TITLE
Uninitialized string offset in PHP Tokenizer on PHP 5.2

### ISSUE THREAD

**Issue by jrfnl** [squizlabs/PHP_CodeSniffer#1237]
I'm receiving a PHP notice on PHP5.2 with PHPCS 2.7.1/master since commit 531a73143a17098b422d319787473c5279d352f1 which is breaking our builds on PHP5.2

`Notice: Uninitialized string offset: 0 in /tmp/phpcs/CodeSniffer/Tokenizers/PHP.php on line 688`

**Comment by jrfnl** [comment]
More detailed information:

Test code:
```php
<?php
// Comment:
$a ?: $c;
```

will eventually tokenize as:
```
0 :: T_OPEN_TAG :: <?php
1 :: T_COMMENT :: // Comment:
2 :: T_NONE ::
3 :: T_VARIABLE :: $a
4 :: T_WHITESPACE ::
6 :: T_INLINE_ELSE :: :
7 :: T_WHITESPACE ::
8 :: T_VARIABLE :: $c
9 :: T_SEMICOLON :: ;
```

And gives the unitialized string offset issue when dealing with the `$a` `T_VARIABLE` token, so it looks like the issue is related to the `T_NONE` (which I would have expected to be a `T_WHITESPACE` anyhow).

**Comment by gsherwood** [comment]
I can't get a 5.2 install to check the fix on, so it would be great if you could see if this change fixes the issue. I think it will given the issue itself looks pretty obvious in the code.

**Comment by jrfnl** [comment]
All ok now.
Example of build which was failing & now passing: https://travis-ci.org/jrfnl/PHPCompatibility/builds/183551067 (second build in the list - PHP 5.2 with PHPCS master)

**Comment by gsherwood** [comment]
Good news. Thanks a lot for testing that for me.
