### ISSUE TITLE
Getting Code Consistency Badge

### ISSUE THREAD

**Issue by iranianpep** [squizlabs/PHP_CodeSniffer#1242]
Hi,

I would like for my project to be added to https://squizlabs.github.io/PHP_CodeSniffer/analysis/. Following is the project details:

```
    {
        "name": "Slackbot",
        "url": "iranianpep/slackbot",
        "path": "src",
        "ignore": "*/vendors/*",
        "extensions": ""
    }
```

Cheers,
Ehsan

**Comment by gsherwood** [comment]
The report has been generated: https://squizlabs.github.io/PHP_CodeSniffer/analysis/iranianpep/slackbot/index.html

**Comment by iranianpep** [comment]
Thanks! Also I assume the check gets updated everyday. Am I right?

**Comment by gsherwood** [comment]
> Also I assume the check gets updated everyday. Am I right?

They are generated once per month, using whatever code was in the repository on the 1st of the month. So whatever code is in your repo on the 1st of Jan will be included in the next report.

**Comment by iranianpep** [comment]
Hi,

Sorry to re-open this. I had to change the project name from "Slackbot" to "Botonomous". Could you please update this repo details as follow:
```
    {
        "name": "Botonomous",
        "url": "iranianpep/botonomous",
        "path": "src",
        "ignore": "*/vendors/*",
        "extensions": ""
    }
```

Cheers,
Ehsan

**Comment by gsherwood** [comment]
I've renamed the project for you: https://squizlabs.github.io/PHP_CodeSniffer/analysis/iranianpep/botonomous/index.html

**Comment by iranianpep** [comment]
Beautiful. Thanks!
