### ISSUE TITLE
Why do you support PHP 5.4 on 3.x?

### ISSUE THREAD

**Issue by gmponos** [squizlabs/PHP_CodeSniffer#1244]
I guess the question is simple. Why to support [version 5.4](https://github.com/squizlabs/PHP_CodeSniffer/blob/3.0/composer.json#L35) at the 3.x version? I believe that since you are moving to a new major version you should either start from 5.5.9 or 5.6

**Comment by gsherwood** [comment]
I wrote about this here: https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.0.0a1

**Comment by gmponos** [comment]
Pfff... I remembered just now that I have read this. Sorry. Anyway.
