### ISSUE TITLE
GitBlame report requires a .git directory

### ISSUE THREAD

**Issue by sbuzonas** [squizlabs/PHP_CodeSniffer#1249]
Using `git-worktree` has a file at `.git` pointing to the git directory, as well as the `GIT_DIR` environment variable that could change the location.

**Comment by gsherwood** [comment]
I'm not really sure what you are describing here. Presumably, the git blame report isn't work for you because the `git blame` command has either failed or is always looking at the main working tree, but you'll have to explain things a bit more for me to know for sure.

**Comment by sbuzonas** [comment]
The `git blame` command respects all the various ways to have a git repository.  The report class only checks for the existence of a git directory, and quits otherwise.  https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Reports/Gitblame.php#L96

**Comment by gsherwood** [comment]
@sbuzonas Thanks for the extra information. I understand your problem now.

**Comment by gsherwood** [comment]
@sbuzonas It looks to me like a solution might be to just chdir into the same dir that the file exists within instead of trying to find a .git directory in the path. Presumably, `git blame` will work when run from within the same dir as the file, picking up the correct repo for more complex setups.

**Comment by gsherwood** [comment]
@sbuzonas I've pushed a change to make the report more simple. Are you able to try out the code on master, or manually patch the Gitblame report class with this change: https://github.com/squizlabs/PHP_CodeSniffer/commit/9b5f4fb31ed4d46536181342386e8dfd5f634377

**Comment by sbuzonas** [comment]
That works

**Comment by gsherwood** [comment]
@sbuzonas Thanks a lot for testing that for me.
