### ISSUE TITLE
Squiz.Strings.ConcatenationSpacing fix creates syntax error when joining a number to a string

### ISSUE THREAD

**Issue by gseric** [squizlabs/PHP_CodeSniffer#1252]
This fixer generates invalid PHP code in some cases. E.g.:
```php
// Original PHP code:
echo 1 . 'test';

// After fix (syntax error!!!):
echo 1.'test';

// Should be:
echo (1).'test';
```

PHP reports the following error:
> Parse error: syntax error, unexpected ''test'' (T_CONSTANT_ENCAPSED_STRING), expecting ',' or ';'

PHP treats dot as decimal separator instead of concat operator if used directly after number.

PHP_CodeSniffer 2.7.1

**Comment by gsherwood** [comment]
Thanks for the report.

The fixer now puts parenthesis around LNUMBER and DNUMBER tokens before and after string concats without spaces. It doesn't technically need to do DNUMBER before a string concat, but I don't think it hurts.

**Comment by gseric** [comment]
Thank you!
