### ISSUE TITLE
Use of internal sniffs

### ISSUE THREAD

**Issue by grappler** [squizlabs/PHP_CodeSniffer#1256]
I have changed the message for `Internal.Tokenizer.Exception` and changed `Internal.LineEndings.Mixed` from a warning to an error in my ruleset.

Are there any issues in doing this?

**Comment by gsherwood** [comment]
> Are there any issues in doing this?

There are no issues. I gave them proper error codes so you could do those things. You can even mute them entirely (set their severity to zero) if you don't want to be notified of those things.

**Comment by grappler** [comment]
Thanks! 😄
