### ISSUE TITLE
3.0: Autoloader not properly working

### ISSUE THREAD

**Issue by dereuromark** [squizlabs/PHP_CodeSniffer#1259]
We have some abstract sniffs as base ones for sniffs to extend and share common functionality.
Those have been working before 3.0 (via namespacing and psr4 autoloading).
Your 3.0 branch kills that now - see https://github.com/spryker/code-sniffer/compare/develop for the diff.
```
PHP Fatal error:  Class 'Spryker\Sniffs\AbstractSniffs\AbstractMethodAnnotationSniff' not found in
 /.../vendor/spryker/code-sniffer/Spryker/Sniffs/Plugin/AbstractPluginMethodAnnotationSniff.php on line 8
```

Those are never found, even though they still should be.
Is the sniffer autoloader messing with the composer one? Shouldnt both use the composer one now? That would resolve those issues afaik.

**Comment by gsherwood** [comment]
I wont have a chance to try out your coding standard until next week, but just wanted to comment and say that the PHPCS autoloader should be running before the composer autoloader, but both should run (they did last time I was testing it).

The PHPCS autoloader *must* run before any other so it can record what files (and thus, what sniffs and sniff codes) are being used and what namespace they are being used within. Without this, PHPCS can't translate a sniff code in a ruleset file into a properly namespaced class name or file location. It also can't properly provide it's caching function as it needs to detect when the content of sniff classes change so the cache can be invalidated.

So no, PHPCS shouldn't be using the composer autoloader. Not only would it causes a few places in PHPCS to fail when using 3rd-party sniffs, but it would also mean PHPCS would have to be installed via composer, which is not a current requirement.

**Comment by dereuromark** [comment]
Do you have any idea how this can be resolved? Where to look etc?
I still couldn't get the rep to work.

**Comment by gsherwood** [comment]
The above commit is the first try and moving towards a fix for this issue. The composer autoloader wasn't being included by PHPCS (I must have removed that and forgotten to re-add) but simply including it doesn't work either. PHPCS needs to know the class name for included sniffs so it can determine which sniff to apply ruleset rules to, so the PHPCS autoloader now makes use of the composer autoloader to help out, if it is available.

I still have more changes to make to ensure PHPCS works in various other configurations, so it's not done yet.

I can tell you that even with this change, you need to change your sniffs that reference AbstractVariableSniff and AbstractScopeSniff because they are not done properly in your develop branch. The upgrade guide shows you what to do: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Version-3.0-Upgrade-Guide#abstractvariablesniff

**Comment by gsherwood** [comment]
With the above commits, and some changes to your sniffs, your phpcs.sh script now runs for me (after a `composer update` to get new PHPCS code).

The diff I applied for your sniffs is:
```diff
diff --git a/Spryker/Sniffs/Classes/ClassDeclarationSniff.php b/Spryker/Sniffs/Classes/ClassDeclarationSniff.php
index e302f05..7f83e16 100644
--- a/Spryker/Sniffs/Classes/ClassDeclarationSniff.php
+++ b/Spryker/Sniffs/Classes/ClassDeclarationSniff.php
@@ -15,11 +15,6 @@ use PHP_CodeSniffer\Standards\PEAR\Sniffs\Classes\ClassDeclarationSniff as PearC
 use PHP_CodeSniffer\Files\File;
 use PHP_CodeSniffer\Util\Tokens;
 
-if (class_exists('PEAR_Sniffs_Classes_ClassDeclarationSniff', true) === false) {
-    $error = 'Class PEAR_Sniffs_Classes_ClassDeclarationSniff not found';
-    throw new \Exception($error);
-}
-
 /**
  * Class Declaration Test.
  *
diff --git a/Spryker/Sniffs/Classes/MethodDeclarationSniff.php b/Spryker/Sniffs/Classes/MethodDeclarationSniff.php
index 550b845..edad8c7 100644
--- a/Spryker/Sniffs/Classes/MethodDeclarationSniff.php
+++ b/Spryker/Sniffs/Classes/MethodDeclarationSniff.php
@@ -15,7 +15,7 @@
 namespace Spryker\Sniffs\Classes;
 
 use PHP_CodeSniffer\Files\File;
-use PHP_CodeSniffer_Standards_AbstractScopeSniff;
+use PHP_CodeSniffer\Sniffs\AbstractScopeSniff;
 use PHP_CodeSniffer\Util\Tokens;
 
 /**
@@ -29,7 +29,7 @@ use PHP_CodeSniffer\Util\Tokens;
  * @version Release: @package_version@
  * @link http://pear.php.net/package/PHP_CodeSniffer
  */
-class MethodDeclarationSniff extends PHP_CodeSniffer_Standards_AbstractScopeSniff
+class MethodDeclarationSniff extends AbstractScopeSniff
 {
 
     /**
@@ -135,4 +135,8 @@ class MethodDeclarationSniff extends PHP_CodeSniffer_Standards_AbstractScopeSnif
         }
     }
 
+protected function processTokenOutsideScope(File $phpcsFile, $stackPtr)
+{
+}
+
 }
diff --git a/Spryker/Sniffs/Commenting/DocBlockReturnTagSniff.php b/Spryker/Sniffs/Commenting/DocBlockReturnTagSniff.php
index d0d6216..33dd88b 100644
--- a/Spryker/Sniffs/Commenting/DocBlockReturnTagSniff.php
+++ b/Spryker/Sniffs/Commenting/DocBlockReturnTagSniff.php
@@ -3,7 +3,7 @@
 namespace Spryker\Sniffs\Commenting;
 
 use PHP_CodeSniffer\Files\File;
-use PHP_CodeSniffer_Standards_AbstractScopeSniff;
+use PHP_CodeSniffer\Sniffs\AbstractScopeSniff;
 
 /**
  * Verifies that a `@return` tag exists for all functions and methods and that it does not exist
@@ -12,7 +12,7 @@ use PHP_CodeSniffer_Standards_AbstractScopeSniff;
  * @author Mark Scherer
  * @license MIT
  */
-class DocBlockReturnTagSniff extends PHP_CodeSniffer_Standards_AbstractScopeSniff
+class DocBlockReturnTagSniff extends AbstractScopeSniff
 {
 
     /**
@@ -93,5 +93,8 @@ class DocBlockReturnTagSniff extends PHP_CodeSniffer_Standards_AbstractScopeSnif
             return;
         }
     }
+protected function processTokenOutsideScope(File $phpcsFile, $stackPtr)
+{
+}
 
 }
diff --git a/Spryker/Sniffs/Whitespace/MemberVarSpacingSniff.php b/Spryker/Sniffs/Whitespace/MemberVarSpacingSniff.php
index 19873e3..ffe777d 100644
--- a/Spryker/Sniffs/Whitespace/MemberVarSpacingSniff.php
+++ b/Spryker/Sniffs/Whitespace/MemberVarSpacingSniff.php
@@ -3,7 +3,7 @@
 namespace Spryker\Sniffs\Whitespace;
 
 use PHP_CodeSniffer\Files\File;
-use PHP_CodeSniffer_Standards_AbstractVariableSniff;
+use PHP_CodeSniffer\Sniffs\AbstractVariableSniff;
 use PHP_CodeSniffer\Util\Tokens;
 
 /**
@@ -12,7 +12,7 @@ use PHP_CodeSniffer\Util\Tokens;
  * @author Mark Scherer
  * @license MIT
  */
-class MemberVarSpacingSniff extends PHP_CodeSniffer_Standards_AbstractVariableSniff
+class MemberVarSpacingSniff extends AbstractVariableSniff
 {
 
     /**
```

**Comment by dereuromark** [comment]
Thanks, I can confirm that with your recent changes the autoloading works as expected.
The rest I can figure out now - I will close then :)

**Comment by gsherwood** [comment]
@dereuromark I'm still working on some fixes around the autoloader, but I'll keep testing with your repo to make sure it is working. But please let me know if I break something again.
