### ISSUE TITLE
non printable check snif

### ISSUE THREAD

**Issue by selul** [squizlabs/PHP_CodeSniffer#1262]
I've been working for https://github.com/WPTRT/WordPress-Coding-Standards, which is a fork of PHP_CodeSniffer, on a sniff for checking if the js, css and php files contains non-printable chars.

Being a pretty general sniff, i'm wondering if would make sense also for the upstream to have it, maybe in the `Generic` ruleset ? 

Thanks !

**Comment by gsherwood** [comment]
If you could point me at the sniff, I'll certainly take a look. If it's a generic sniff, I'd be happy to include it in the Generic standard.

**Comment by selul** [comment]
Hey, 

Here you have the [sniff](https://github.com/selul/WordPress-Coding-Standards/blob/feature/badchars/WordPress/Sniffs/Theme/NonPrintableCheckSniff.php ), [unit test](https://github.com/selul/WordPress-Coding-Standards/blob/feature/badchars/WordPress/Tests/Theme/NonPrintableCheckUnitTest.php) and [php](https://github.com/selul/WordPress-Coding-Standards/blob/feature/badchars/WordPress/Tests/Theme/NonPrintableCheckUnitTest.inc),[css](https://github.com/selul/WordPress-Coding-Standards/blob/feature/badchars/WordPress/Tests/Theme/NonPrintableCheckUnitTest.css) and [js](https://github.com/selul/WordPress-Coding-Standards/blob/feature/badchars/WordPress/Tests/Theme/NonPrintableCheckUnitTest.js) test files

Let me know your feedback.

Thanks !

**Comment by gsherwood** [comment]
Closing as I've had no additional interest or PRs for this.
