### ISSUE TITLE
ES6 arrow function raises unexpected operator spacing errors

### ISSUE THREAD

**Issue by alexiscott** [squizlabs/PHP_CodeSniffer#1265]
Definition of arrow function:
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/Arrow_functions

Example ES6 Javascript:

var materialsLength3 = materials.map(material=> material.length);

Error raised :
 1 | ERROR | [x] Expected 1 space before "="; 0 found
 1 | ERROR | [x] Expected 1 space after "="; 0 found
 1 | ERROR | [x] Equals sign not aligned correctly; expected 1 space but found 0 spaces
 1 | ERROR | [x] Expected 1 space before ">"; 0 found

Expectation: 
No error.

Other: File is OperatorSpacingSniff.php. In 3.0 ./src/Standards/Squiz/Sniffs/WhiteSpace/OperatorSpacingSniff.php

**Comment by aik099** [comment]
There no much support for ES6 in general. The only features from ES6, that is correctly recognized was implemented in #1251.

**Comment by alexiscott** [comment]
Thanks for your super fast response. 

That is a pity, as it's being used a lot already both in documentation and with transpilers, such as Babel.

**Comment by aik099** [comment]
Not too much I guess, since you're the 2nd person asking about this in last 2 days and before nobody asked about it. The ES6 is out there for more than 1 year if I'm not mistaken.

**Comment by gsherwood** [comment]
This just needs a new token. PHP already has one for it, so I can't see this being much of a problem.

**Comment by gsherwood** [comment]
The commit adds the double arrow as a valid JS token. The sniff still reports an error because there is no space before the `=>` operator, but it doesn't see it as two operators any more. As far as I can tell, the space before/after is used in all the arrow function specs, but please let me know if the space actually causes invalid code and I can have the sniff ignore it.

**Comment by aik099** [comment]
Cool. Thanks.
