### ISSUE TITLE
PHP Notices: Undefined index: bracket_closer - JS Files

### ISSUE THREAD

**Issue by grappler** [squizlabs/PHP_CodeSniffer#1271]
I ran PHPCS on all of the [WordPress themes](https://wordpress.org/themes/) that have been updated in the last two years. When doing so I got a PHP notice while processing certain JS files. I did not write the code and do not have access to change it.

When running PHPCS on [theme-customizer.js](https://themes.svn.wordpress.org/anarcho-notepad/2.9/js/theme-customizer.js) I get the following errors while using PHPCS 2.7.1

```
Processing theme-customizer.js PHP Notice:  Undefined index: bracket_closer in  CodeSniffer/Tokenizers/JS.php on line 1078

Notice: Undefined index: bracket_closer in  CodeSniffer/Tokenizers/JS.php on line 1078
PHP Notice:  Undefined offset: 480 in  CodeSniffer/File.php on line 731

Notice: Undefined offset: 480 in  CodeSniffer/File.php on line 731
[JS => 481 tokens in  lines]... PHP Notice:  Undefined index: content in  CodeSniffer/Fixer.php on line 139

Notice: Undefined index: content in  CodeSniffer/Fixer.php on line 139
DONE in 4ms (0 errors, 0 warnings)
```

Here are further list of files that get the same errors.
- [theme-customizer.js](https://themes.svn.wordpress.org/anarcho-notepad/2.9/js/theme-customizer.js)
- [wrapper_start.js](https://themes.svn.wordpress.org/silk-lite/1.2.0/assets/js/main/wrapper_start.js)
- [rtpanel/intro.js](https://themes.svn.wordpress.org/rtpanel/4.1.6/assets/foundation/bower_components/jquery/src/intro.js), [planet-foundation/intro.js](https://themes.svn.wordpress.org/planet-foundation/1.4.1/foundation/bower_components/jquery/src/intro.js), [fotographia/intro.js](https://themes.svn.wordpress.org/fotographia/1.3/vendor/jquery/src/intro.js)
- [marked.js](https://themes.svn.wordpress.org/gitsta/1.4.2/vendor/marked.js)
- [options-custom.js](https://themes.svn.wordpress.org/encrypted-lite/1.4.2/inc/path/js/options-custom.js)
- [respond.js](https://themes.svn.wordpress.org/bootbiz-for-wedding/1.9/js/respond.js)

**Comment by gsherwood** [comment]
These files produce errors because they have unmatched parenthesis in them, which would also be causing syntax errors.

I've made some changes over recent versions to hide errors caused by syntax errors in PHP code, so I think it makes sense to do the same here.

**Comment by gsherwood** [comment]
I've added guard code for this specific syntax error. Thanks for reporting this.
