### ISSUE TITLE
<file> tag in custom ruleset does not work

### ISSUE THREAD

**Issue by SidIcarus** [squizlabs/PHP_CodeSniffer#1275]
Setup: 
- phpcs installed via composer
- tested both 2.7.1 & 3.0RC2
- Project root contains: `composer.json application/ config/ vendor/ ` among others
  - custom ruleset located at `config/phpcs.xml`
  - Exclusion-pattern works just fine 
    `<exclude-pattern>*/application/third_party/*</exclude-pattern>`
- alias command via composer `"cs": "vendor/bin/phpcs --standard=config/phpcs.xml"`
  - example run cmd `composer cs application/` (which works fine)

[Th Annotated Ruleset](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-ruleset.xml) states that the following syntax will set a default file in a custom ruleset given no CLI provided dir/file option
`<file>./path/to/directory</file>`
`<file>./path/to/file.php</file>`

Issue: Setting a default dir in my ruleset **does not work** on either **2.7.1** or **3.0RC2**
`<file>./application</file>`
`ERROR: The file ".application" does not exist"`

I've tried using various syntax for the dir-path to get it to work but none seem to work
- `./dir/` `/dir/` `*/dir/*` `*/dir/` `/dir/*` etc.
Overriding the default file works fine by providing a CLI dir/file option (see example cmd)

I can currently bypass the issue by simply setting my composer alias to include that directory by default but that won't get overridden via CLI, which will be problematic for me once I get this integrated into my teams project.

**Comment by gsherwood** [comment]
The `<file>` paths are relative to the ruleset's location. This allows you to run PHPCS from anywhere, but still have the file paths work correctly if you pass in that ruleset with a file or directory on the CLI.

Given you have your ruleset in `config/`, have you tried `<file>../application</file>`?

If that was the problem, I'll fix the docs to make sure that is clear.

**Comment by SidIcarus** [comment]
It was indeed. I did read that `<file>` paths were relative and I tried doing `././` but I guess I just I didn't think of `../`.
¯\_(ツ)_/¯ whoops

Thanks! @gsherwood

**Comment by gsherwood** [comment]
> It was indeed.

Thanks for letting me know. I'll fix the docs.
