### ISSUE TITLE
Commenting.FunctionComment.InvalidReturnVoid conditional issue with anonymous classes

### ISSUE THREAD

**Issue by pavloivanov** [squizlabs/PHP_CodeSniffer#1276]
Commenting a method with `@return void` triggers an 
`InvalidReturnVoid` error:
`Function return type is void, but function contains return statement (....Commenting.FunctionComment.InvalidReturnVoid)`
 when the method contains anonymous class that contains a return.

Example:

```
<?php

namespace Test;

/**
 * Class AnonTest
 */
class AnonTest
{
    /**
     * do something
     *
     * @return void
     */
    public function someFunc(): void
    {
        $class = new class
        {
            /**
             * Getter
             *
             * @return string
             */
            public function getString(): string
            {
                return 'some string';
            }
        };
        echo $class->getString();
    }
}
```

**Comment by gsherwood** [comment]
Fixed now. Thanks for the bug report.

**Comment by pavloivanov** [comment]
NP, Thank you!

**Comment by pavloivanov** [comment]
Will it be included in 2.* version?

**Comment by gsherwood** [comment]
> Will it be included in 2.* version?

Yes, it will be in both the next 2.x and 3.x release.
