### ISSUE TITLE
Adding nullable scalar type hint to function breaks PSR2 switch statement sniffing.

### ISSUE THREAD

**Issue by samdjstevens** [squizlabs/PHP_CodeSniffer#1279]
When running `phpcs --extensions=php --colors --standard=PSR2` against this file:

    <?php
    namespace App;

    class TestClass
    {
        public function testMethod(int $errorCode, ?string $errorMessage = null)
        {
            switch ($errorCode) {
                case 404:
                    throw new NotFoundException();
                default:
                    throw new \Exception();
            }
       }
    }

The output is:

    ----------------------------------------------------------------------
    FOUND 1 ERROR AFFECTING 1 LINE
    ----------------------------------------------------------------------
     9 | ERROR | CASE statements must be defined using a colon
    ----------------------------------------------------------------------

Removing the nullability of the `?string` typehint (to just `string`) makes the error go away.

I'm running PHP 7.1.0

**Comment by jrfnl** [comment]
I can see the issue in PHPCS 2.7.1, but can no longer reproduce this with `master`, so this looks to have been fixed already.

**Comment by gsherwood** [comment]
Yes, this has been fixed and will be in the next release. It was fixed by commit ee3ce4b.
