### ISSUE TITLE
Uninitialized string offset in PHP Tokenizer on PHP 5.2

### ISSUE THREAD

**Issue by jrfnl** [squizlabs/PHP_CodeSniffer#1280]
I'm receiving a PHP notice on PHP5.2 with PHPCS master since commit https://github.com/squizlabs/PHP_CodeSniffer/commit/b2b4b2861972280d3217800f03fb033415bdd7a6 which is breaking our builds on PHP5.2

Notice: Uninitialized string offset: 0 in /tmp/phpcs/CodeSniffer/Tokenizers/PHP.php on line 690
Notice: Uninitialized string offset: 0 in /tmp/phpcs/CodeSniffer/Tokenizers/PHP.php on line 694

**Comment by gsherwood** [comment]
This sort of thing is typically caused by not checking if the token is an array or not. I've just added that check to try it out, but there are so many 5.2 failures that I can't really tell if it did anything. Can you try that code out for me please?

**Comment by jrfnl** [comment]
Thanks for that! Your fix looks a lot simpler than mine ;-)

I've restarted the test build I created & linked to in #1283 which at the time was failing against master & passing against the PR branch.

https://travis-ci.org/jrfnl/PHPCompatibility/builds/193080359

Looks like it's passing against both now, so as far as I can see, that part is fixed now.

**Comment by gsherwood** [comment]
Thanks for getting back to me.
