### ISSUE TITLE
Google Summer of Code

### ISSUE THREAD

**Issue by sils** [squizlabs/PHP_CodeSniffer#1285]
Hey @gsherwood  specifically as you're by far the biggest contributor and I assume maintainer.

[coala](https://coala.io) will most likely participate in GSoC this year. [We are using PHP_CodeSniffer](https://github.com/coala/bear-docs/blob/master/docs/PHPCodeSnifferBear.rst) to power part of the python code analysis we offer in coala.

Now here's the thing: would you be willing to take on a GSoC student? We might be able to get you one, functioning as an umbrella organization.

## How it works

- You define a project with us.
- You provide at least one mentor, two ideally. 
- One member of coala will be paid for administering, that includes:
    - helping you making a great idea
    - helping you with any problems you might have
    - checking up on all students, finding out if mentors fail to do so themselves :)

## Why do it

- You get a student that works on your project, ideally sticks with your project long term
- You don't have to bother about the admin work
- Our communities can share knowledge

## Why we do it

- We get better integration of your tool
- We get upstream improvements
- We get another student, google likes umbrella orgs as they are their chance to pull in more projects like you
- Our communities can share knowledge

Does this sound interesting to you? We will submit the initial application somewhen today, the deadline is later. However **we need to know if this is going to happen within the next week sharp.**

CC @jayvdb @sims1253

**Comment by gsherwood** [comment]
Sorry, but I barely have time to maintain the project with work and family commitments. There is no way I could consider participating in GSoC. Thanks for asking though.
