### ISSUE TITLE
Undefined offset Tokenizers/CSS.php

### ISSUE THREAD

**Issue by grappler** [squizlabs/PHP_CodeSniffer#1304]
When running PHPCS(master) I got a PHP notice while processing certain CSS files. I did not write the code and do not have access to change it.

The error is: `Processing style.css PHP Notice:  Undefined offset: 93 in Tokenizers/CSS.php on line 452`

An example file is https://themes.trac.wordpress.org/browser/bizznis/1.4.0/style.css

**Comment by gsherwood** [comment]
Again, this is caused by a syntax error in the file. Line 89 has a close comment token but a comment was never opened. You might want to consider reporting these syntax errors to the theme authors instead of me, if you aren't already.

I see if I can hide this error like I did for the JS ones.

**Comment by gsherwood** [comment]
I've muted those errors, but there are obviously some pretty bad token results from a large string of uncommented dashes.

**Comment by grappler** [comment]
Thanks @gsherwood for fixing these the notices. As there are a number of themes with issues, it will take some time. We are planning of using PHPCS to help improve automated code reveiws for themes being uplaoded to WordPress.org/themes.
