### ISSUE TITLE
Q: How to debug fixer output ?

### ISSUE THREAD

**Issue by jrfnl** [squizlabs/PHP_CodeSniffer#1307]
I'm trying to debug several issues with fixers included in the `Squiz.Commenting.FunctionComment` sniff and am running into some trouble.

When I run `phpbf -p -s ./path/to/testfile.inc --standard=Squiz` the `testfile.inc` remains the same as it was without the patches I'm trying to test. (same result when I add the `--suffix` or `--no-patch` options)

When I run `phpcs -p - s ./path/to/testfile.inc --standard=Squiz --report=diff` the diff output shows me the expected output indicating that the patch is supposed to work fine.
And when I add `-vv` I can see that the lines involved are changes twice in different loops - once for the type hints, once for the alignment.

Help ?

**Comment by aik099** [comment]
So that built-in sniff isn't fixing something you suppose it should fix?

Can you post code before and after the fix and indicate what went wrong or wasn't fixed?

**Comment by aik099** [comment]
If you're asking in general, then I'd recommend using real-time debugging, like xDebug + IDE (e.g. PhpStorm).

**Comment by jrfnl** [comment]
> So that built-in sniff isn't fixing something you suppose it should fix?

It's fixing it, but the fixes are wrong. My patches should correct it, but don't seem to get applied when running `phpcbf`, but they do work correctly when using `phpcs --report=diff`.

There are a number of issues with the fixer for this sniff (minimal examples):

#### Param variable types disappearing.

Original code:
```php
/**
 * @param double|int     $a2 Comment here.
 * @return void
 */
public function mixedType($a2) {}
```

Expected output:
```php
/**
 * @param float|integer $a2 Comment here.
 * @return void
 */
public function mixedType($a2) {}
```

Fixer output:
```php
/**
 * @param float $a2 Comment here.
 * @return void
 */
public function mixedType($a2) {}
```

#### Multi-line param description alignment

Original code:
```php
/**
 * @param boolean   $stackPtr   The position in @ @unknown
 *          the stack of the token
 *                           that opened the scope.
 * @param integer $depth               How many scope levels
 *  down we are.
 * @return void
 */
function _functionCall($stackPtr, $depth=1, $index) {}
```

Expected output:
```php
/**
 * @param boolean $stackPtr The position in @ @unknown
 *                          the stack of the token
 *                          that opened the scope.
 * @param integer $depth    How many scope levels
 *                          down we are.
 * @return void
 */
function _functionCall($stackPtr, $depth=1, $index) {}
```

Fixer output:
```php
/**
 * @param boolean $stackPtr The position in @ @unknown
 *      the stack of the token
 *                       that opened the scope.
 * @param integer $depth    How many scope levels
 *down we are.
 * @return void
 */
function _functionCall($stackPtr, $depth=1, $index) {}
```

#### Other issues

The sniff also throws a `Function return type is not void, but function has no return statement` error if using multiple types including void, i.e. `array|void`.

And the patches I'm working on would also solve the issue you reported in #1018 ;-)

**Comment by aik099** [comment]
The fixes isn't that clever to replace `double|int` with `float|integer` 😄

**Comment by aik099** [comment]
> The sniff also throws a Function return type is not void, but function has no return statement error if using multiple types including void, i.e. array|void.

I'm aware of that. I think PhpStorm inspections aren't that clever either.

**Comment by jrfnl** [comment]
@aik099 It will be with my patch ;-)

**Comment by jrfnl** [comment]
It started with me getting annoyed with the incorrect return type / void message, so I started to fix that. Then came across a previous fix which was similar related to #1018 which was reverted as it caused bugs for other fixers in the sniff.
So I figured I should probably create a fixed file to make sure that my version of the patch (which would cover the return type void + #1018 issues) would not be causing any similar regression.
Then had a good look at the fixer file and found even more bugs... so adding the fixer file would fail the build, even if my patch was not causing any regressions.

And so on...

**Comment by aik099** [comment]
Probably you need to send PR for every change even though if they are for same sniff.

**Comment by jrfnl** [comment]
@aik099 I would ;-)

**Comment by jrfnl** [comment]
Oh ^%*^%^%*^darn... PEBKAC

Figured it out and got it working....

For anyone wondering: the `phpcbf.bat` registered in my `PATH` variable was pointing to the wrong install of PHPC..... duh....
