### ISSUE TITLE
Create a PSR-5 and PSR-12

### ISSUE THREAD

**Issue by gmponos** [squizlabs/PHP_CodeSniffer#1309]
I was wondering if there could be a way for developers to start working and creating sniffs on these PSRs ([PSR-5](https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md) - [PSR-12](https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md))

For instance I have a sniff that checks for deprecated PHPDoc tags according to PSR-5. If I make a PR creating a new standard named PSR-5 having only this sniff will it be accepted? This way more developers can influenced to create more PRs about these PSRs. 

I know that these PSRs are currently in Draft state and you might reasonably say that things might change but for instance for the sniff that I mention I don't think that these tags that are deprecated in PSR-5 will become un-deprecated.

**Comment by gsherwood** [comment]
Yes, I would accept that PR. But given they are in draft, I'd rather include them in the 3.0 branch because I don't think the PSRs will be approved before 2.x has finished its run. I don't want to include an incomplete (or worse, incorrect) standard in there.

**Comment by gsherwood** [comment]
Closing this as question was answered. To my knowledge, nobody is currently working on sniffs for either PSR.
