### ISSUE TITLE
"?:" sometimes triggers Squiz.ControlStructures.InlineIfDeclaration.SpacingAfterThen & SpacingBeforeElse

### ISSUE THREAD

**Issue by puggan** [squizlabs/PHP_CodeSniffer#1311]
```
<?php
        $c = $argv[1] ?: "";
        $filepath = realpath($argv[1]) ?: $argv[1];
```
Line 3 triggers both Squiz.ControlStructures.InlineIfDeclaration.SpacingAfterThen & SpacingBeforeElse
Line 2 also uses "?:" but is fine

`phpcs /tmp/s.php -s`

phpcs /tmp/s.php -s

```
FILE: /tmp/s.php
-------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 1 LINE
-------------------------------------------------------------------------------------------------------------------------------------------------
 3 | ERROR | Inline shorthand IF statement requires 1 space after THEN; 0 found (Squiz.ControlStructures.InlineIfDeclaration.SpacingAfterThen)
 3 | ERROR | Inline shorthand IF statement requires 1 space before ELSE; 0 found (Squiz.ControlStructures.InlineIfDeclaration.SpacingBeforeElse)
-------------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by puggan** [comment]
both rows gives the same tokens for the "?:"
```
        Process token 11 on line 2 [col:19;len:1;lvl:0;]: T_INLINE_THEN => ?
        Process token 12 on line 2 [col:20;len:1;lvl:0;]: T_INLINE_ELSE => :
```

Shouldn't thous 2 become a single token for the "?:" operator?

**Comment by puggan** [comment]
The reason the line 2 is fine, is that it never reach the test, as an earlier addError() exits the tests as its followed by a return:
https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/Squiz/Sniffs/ControlStructures/InlineIfDeclarationSniff.php#L89

I see no reason to not do the rest of the test, there no possible conflict, or what did I miss?

**Comment by gsherwood** [comment]
> Shouldn't thous 2 become a single token for the "?:" operator?

There isn't a `?:` operator in PHP. You are just able to leave the middle part of the expression empty. So you can write `? :` and it will work perfectly fine as well.

> I see no reason to not do the rest of the test, there no possible conflict, or what did I miss?

Sniffs often do this so they don't generate errors for statements that are incorrectly configured. If you fix the original problem, you may get more error now that the statement looks like it might be correct.

I think the best thing to do in this case is just change the sniff to enforce no space between `?` and `:` when the `then` statement is missing. That makes it look like an operator even though it isn't one. I could make a T_ELVIS token and assign it to this, but the fact that PHP doesn't enforce a no-space rule means it wouldn't always pick it up.

**Comment by puggan** [comment]
> There isn't a ?: operator in PHP
Oh, didn't know that.

> If you fix the original problem,
In this case, I silenced the "original", as it doesn't match how I code, so in the few cases where it's not triggered, as when I use a function, I mostly just have a variable before as the "comparison". The right thing to do here is probably to copy the sniff, and cut out the first part, and save it in my own profile.

> I think the best thing to do in this case is just change the sniff to enforce no space between ? and : when the then statement is missing.

Sounds good.

**Comment by gsherwood** [comment]
I've made this change now.
