### ISSUE TITLE
Merge conflict in master branch

### ISSUE THREAD

**Issue by zookee1** [squizlabs/PHP_CodeSniffer#1314]
Hej Team,
you've got a merge-conflict on master in this file:
/master/CodeSniffer/Standards/Squiz/Tests/PHP/HeredocUnitTest.inc

Cheers,
Nick

**Comment by jrfnl** [comment]
@zookee1 No, that's a valid test case. See the actual commit which added the test case. 8129f9b034f1868c76e9552db5469e08c9a4839c

**Comment by zookee1** [comment]
I see.. My PHPStorm just found it and I thought this was an actual error. :)
Thanks for the clarification!
