### ISSUE TITLE
Add more in LanguageConstructSpacingSniff

### ISSUE THREAD

**Issue by gmponos** [squizlabs/PHP_CodeSniffer#1317]
I was wondering if

`yield`, `throw`, `namespace` and `use` should also be inside [here](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/Squiz/Sniffs/WhiteSpace/LanguageConstructSpacingSniff.php#L43)

**Comment by gsherwood** [comment]
That sniff is just for language constructs that can be defined with and without braces (the ones that looks like functions), but I get your point. The sniff itself is a bit outdated and could be used to enforce a single space after many PHP keywords.

There isn't currently a sniff in PHPCS to do that, and it seems like something many people would want, so a new Generic sniff might be the way to go, followed by a deprecation of this one.
