### ISSUE TITLE
Filtering a unit tests may cause a divide by zero error

### ISSUE THREAD

**Issue by PatrickRose** [squizlabs/PHP_CodeSniffer#1332]
We've just had an issue where we added a unit test for a sniff we were writing which would only trigger PHPCS warnings. If we filtered the unit tests to only run that, we get a divide by zero error.

It looks to be because `AbstractSniffUnitTest::generateFailureMessages()` doesn't add warnings to the `PHP_CODESNIFFER_SNIFF_CODES` global variable, but does add errors.

**Comment by gsherwood** [comment]
I've tried filtering the built-in test suite to only run a sniff that generates warnings (and confirmed this through debug code) and I don't get any issues.

It would be good to have some more steps to reproduce the problem. If possible, cloning your repo and trying it there would be prefect. If not, at least knowing what the error message is, and where it is being reported, may help.

**Comment by PatrickRose** [comment]
I'll make a quick reproduction tomorrow if I have time!

**Comment by PatrickRose** [comment]
I've just tried to create a reproduction but it didn't work. Looking at the code, it looks like we're running an older version of the TestSuite which doesn't have the fix in. I'll close this!

**Comment by gsherwood** [comment]
Thanks for getting back to me.
