### ISSUE TITLE
Undefined offset when explaining standard with custom sniffs

### ISSUE THREAD

**Issue by dereuromark** [squizlabs/PHP_CodeSniffer#1334]
When running

    vendor/bin/phpcs --standard=PSR2R/ruleset.xml -e

I get

    The PSR2R standard contains 103 sniffs

    ...
    Notice: Undefined offset: 4 in ...\squizlabs\php_codesniffer\src\Ruleset.php on line 263
    Notice: Undefined offset: 5 in ...

for current [develop](https://github.com/php-fig-rectified/psr2r-sniffer/pull/7) branch.

Using 3.0RC3

**Comment by gsherwood** [comment]
This doesn't happen for the included sniffs. Can you please post your custom ruleset?

**Comment by dereuromark** [comment]
It is linked in the above Development branch: https://github.com/php-fig-rectified/psr2r-sniffer/blob/master/PSR2R/ruleset.xml

**Comment by gsherwood** [comment]
I don't get any notices when running outside your repository, but I can replicate after cloning your repo and running it from there. I'll take a look and see if I can figure out what is going on.

**Comment by dereuromark** [comment]
Thx!
PS: your tokenizer requires a constant somewhere inside which makes it quite the overhead to get it up and running (seee [here](https://github.com/php-fig-rectified/psr2r-sniffer/blob/develop/PSR2R/Tools/Tokenizer.php#L86-L100)) without overhead. Ideally this should only be new File() with empty config and ruleset and then be able to tokenize a file IMO.

**Comment by gsherwood** [comment]
If you want to tokenize a file or string with reports etc, this is the code: https://gist.github.com/gsherwood/aafd2c16631a8a872f0c4a23916962ac

Or just to get tokens (this is a JS example, but would work for PHP too): https://gist.github.com/gsherwood/f17cfc90f14a9b29eeb6b2e99e6e7f66

I don't think it's that bad.

**Comment by gsherwood** [comment]
There was an easier way to do the explain in 3.0 because all the codes are recorded elsewhere, so I've changed the method to use the information the Ruleset already had, which fixes this issue.

Thanks for reporting it.
