### ISSUE TITLE
Backfill for new token T_COALESCE_EQUAL

### ISSUE THREAD

**Issue by jrfnl** [squizlabs/PHP_CodeSniffer#1342]
The RFC for the null coalescing assignment operator has been accepted and is pending merge for PHP 7.2.
The token name (based on the PR) will be `T_COALESCE_EQUAL` and will look like `??=`.
Ref: https://wiki.php.net/rfc/null_coalesce_equal_operator
Ref: https://github.com/php/php-src/pull/1795

**Comment by gsherwood** [comment]
Thanks for bringing it to my attention. Added now.

**Comment by jrfnl** [comment]
Excellent! Thank you very much for this!

**Comment by TomasVotruba** [comment]
Also see the author under RFC itself: https://github.com/php/php-src/pull/1795#issuecomment-425748467

**Comment by jrfnl** [comment]
@TomasVotruba Yes, the token got maybe added to PHPCS a bit too soon, but as it will never be assigned (as the feature is not in PHP yet), it will never cause a sniff to be run anyway.
The PHP RFC _is_ approved and the intention is still to implement this in PHP, so removing the token now would only mean that it will have to be reintroduced again later and may cause issues if external standards already take the token into account (BC-break).
IMO, it should only be removed if PHP would decide that this will no longer be implemented.

**Comment by jrfnl** [comment]
Yeah, I've been keeping an eye on it, but the RFC is still listed as "Pending implementation", so it hasn't been (formally) abandoned (yet): https://wiki.php.net/rfc#pending_implementation

**Comment by TomasVotruba** [comment]
I'm concerned about `T_COALESCE_EQUAL` token here only.

**Comment by TomasVotruba** [comment]
@jrfnl Cool, thanks for the ping!

**Comment by jrfnl** [comment]
@TomasVotruba Looks like it's been merged in the mean time. This feature (and presumably the token though I will confirm that later) will be included in PHP 7.4: https://twitter.com/nikita_ppv/status/1087662379037528064

**Comment by TomasVotruba** [comment]
I saw on Reddit. That's good news, thanks for the ping :+1:
