### ISSUE TITLE
Invalid Squiz.Formatting.OperatorBracket error when using namespaces

### ISSUE THREAD

**Issue by ofbeaton** [squizlabs/PHP_CodeSniffer#1350]
I ran `phpcs` and got the following error:
`[x] Arithmetic operation must be bracketed`

So I ran `phpcbf` to auto-fix it, and it changed the code line from:
`$results = $stmt->fetchAll(\PDO::FETCH_ASSOC | \PDO::FETCH_GROUP | \PDO::FETCH_UNIQUE);`

to a syntax error:
`$results = $stmt->fetchAll(\(PDO::FETCH_ASSOC | ) \(PDO::FETCH_GROUP | ) \PDO::FETCH_UNIQUE);`

**Comment by gsherwood** [comment]
Thanks for reporting this. That code shouldn't produce any errors at all, so I've fixed that up.

**Comment by ofbeaton** [comment]
Thanks for the quick fix as always! Can't wait for stable v3!
