### ISSUE TITLE
class documentation in single-class files

### ISSUE THREAD

**Issue by lkmorlan** [squizlabs/PHP_CodeSniffer#1357]
In accordance with widely-followed practice, I have my code structured to have one class per file with nothing in the file besides the class. PHP_CodeSniffer wants me to have both a file docblock and a class docblock. I don't see the reason to have both. If there should be both, what should each say? I don't think it makes sense for the file docblock to say "contains class foo"; that is self-evident.

**Comment by gsherwood** [comment]
PHPCS enforces coding standards. It's likely you are using the PEAR coding standard (the default) which requires both a file and class docblock. I didn't write the standard (it was written before PHPCS existed) but PHPCS enforces it if that's what you want.

If you don't care about comments, use something more modern like the included PSR2 standard.

If you want to create your own, you can create a ruleset.xml file and customise the sniffs and sniff settings that you want run over your code. If you like the PEAR standard but you don't use file comments, that should be as simple as:
```xml
<?xml version="1.0"?>
<ruleset name="MyStandard">
    <description>My custom coding standard.</description>
    <rule ref="PEAR">
        <exclude name="PEAR.Commenting.FileComment"/>
    </rule>
</ruleset>
```

Does that help?

**Comment by lkmorlan** [comment]
Yes, thanks very much.
