### ISSUE TITLE
Add new keyword in a standard

### ISSUE THREAD

**Issue by Mte90** [squizlabs/PHP_CodeSniffer#1361]
I am working on a standard for wordpress and I want that function with name `add_action` or `add_filter` and for my standard I need that them became for the syntax T_FUNCTION.
The doc of wordpress is: https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/#4-hooks-actions-and-filters

So for me need to be managed like a function but after hours on reading the code I don't understand what to do.

**Comment by jrfnl** [comment]
@Mte90 Please ping me in the WP Slack about this as this is not a PHPCS issue.

**Comment by Mte90** [comment]
I think that is a PHPCS issue because I didn't find a way to define what fora standard is a function.
Looking at the code is looking for the `function` keyword but is not possible to add another one where looking for.
In WordPress add_action and add_filter needs to be managed like a function only for the docs part but I didn't find a way.

**Comment by gsherwood** [comment]
I'm sorry, but I really don't know what you are asking, but I doubt this is a core PHPCS issue.

Code is tokenized by PHPCS and sniffs need to listen for whatever tokens they want (1 or more token types). The T_FUNCTION token is the PHP keyword `function`. Function names are T_STRING tokens but you can't tell PHPCS you only want to listen for T_STRING tokens that have a specific value and represent a function name. You need to listen for T_FUNCTION, find the function name, and validate that.

I don't know if that information helps, but it's all I can offer without a lot more information.
