### ISSUE TITLE
False positive for "Interface" in namespace

### ISSUE THREAD

**Issue by ajmichels** [squizlabs/PHP_CodeSniffer#1366]
I am working on a project that has interface files defined in a directory called "Interface" this means the namespace ends up having "Interface" in it. This is resulting in false positives for the rules `Generic.PHP.LowerCaseKeyword.Found`, `PSR2.Classes.ClassDeclaration.MissingBrace`, and `Squiz.Classes.ValidClassName.MissingBrace`

**Comment by orlangur** [comment]
This project is not going to support PHP 7? See http://be2.php.net/manual/en/reserved.keywords.php#119738

**Comment by ajmichels** [comment]
Ah. Good point. Thanks.
