### ISSUE TITLE
Empty line in multi-line function declaration cause infinite loop

### ISSUE THREAD

**Issue by duzhe** [squizlabs/PHP_CodeSniffer#1369]
Test this case
```
<?php

class Test
{
    public function a(
        $b,

        $c
    )
    {
    }
}
```

**Comment by gsherwood** [comment]
I've fixed a few bugs that were causing issues around here with code fixing. Thanks for reporting this.

I'm not 100% sure what standard you are using, but when I use the PSR2 standard to fix this code, I now get the following:
```php
<?php

class Test
{
    public function a(
        $b,
        $c
    ) {
    }
}
```
