### ISSUE TITLE
Error in tab expansion results in white-space of incorrect size

### ISSUE THREAD

**Issue by MarkMaldaba** [squizlabs/PHP_CodeSniffer#1373]
Hi there,

I have just upgrade from CodeSniffer 1.x to 2.x and have come across what appears to be a bug in the way tabs are expanded.  As far as I can see, this has existed since 2.0 and still exists in the latest 2.8 version.  I have not tested on 3.x.

Consider the following (invalid, but illustrative) line in a file:
```123	56```  (the gap in the middle is a tab character, i.e. ````123\t56````)

Expected result (assuming a tab-width of 4 characters):
* Translated content: " " (single space character)
* Reported line length = 6

Actual result:
* Translated content: "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;" (5 space characters)
* Reported line length = 10

As far as I can see, the problem is in the calculation of ````$firstTabSize```` in ````Files.php```` on line 1542.
Instead of:
````php
$firstTabSize = ($tabWidth - ($currColumn % $tabWidth) + 1);
````
it should be
````php
$firstTabSize = ($tabWidth - (($currColumn - 1) % $tabWidth));
````

The reason I spotted this was because I suddenly started getting errors from ````Generic.Files.LineLength.MaxExceeded```` which I wasn't getting prior to the upgrade.

I am surprised no-one else has spotted this issue - I know this code path is only travelled for white-space composed entirely of tabs, but I wouldn't expect that to be particularly uncommon.

**Comment by orlangur** [comment]
> I am surprised no-one else has spotted this issue

With PSR-2 expansion tabs could be met rarely in source code whilst `LineLength.MaxExceeded` is just a warning in it :) Also, meeting such error there is a reflex just to change the line instead of calculating whether PHPCS calculation is correct or not. Nice boundary check!

**Comment by gsherwood** [comment]
Thanks a lot for reporting and fixing this. It is strange that it has never come up, but was clearly wrong on those tab boundaries.

**Comment by MarkMaldaba** [comment]
:-)  No problem.  Thanks for accepting it so quickly.
