### ISSUE TITLE
XML Tokenizer

### ISSUE THREAD

**Issue by orlangur** [squizlabs/PHP_CodeSniffer#1375]
I didn't manage to find any configurable tool to make XML files look consistently.

Some pretty basic stuff would be enough: checking indentation of attributes and child nodes, maximum line length, absence of blank lines etc.

Was such (or maybe HTML) tokenizer creation ever considered? Does it look feasible within `PHP Code Sniffer` infrastructure? Maybe there are some fundamental limitations, like "never parse HTML with regular expressions" or something...

**Comment by gsherwood** [comment]
A HTML tokenizer (which would probably work for basic XML tokenizing) is something I have wanted to do for a while, but have never got the time to.

**Comment by gsherwood** [comment]
Closing as I've had no additional interest or PRs for this.

**Comment by jrfnl** [comment]
@orlangur Have you considered using [XMLLint](http://xmlsoft.org/xmllint.html) ? We've been using it for WPCS to ensure the PHPCS rulesets are consistent in their layout.
It's pretty basic, but can check for consistent indentation, tabs versus spaces and validate against a DTD.

For an example on how to add this to a Travis script, have a look here: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/b605c77951d1e0cc43170d9612831db6bb1d7fca/.travis.yml#L90
