### ISSUE TITLE
Incorrect bug links in changelog

### ISSUE THREAD

**Issue by MarkMaldaba** [squizlabs/PHP_CodeSniffer#1378]
Hi there,

Most issues seem to be reported/managed on Github now, but the changelogs on the [pear.php.net download page](https://pear.php.net/package/PHP_CodeSniffer/download) are linking the ticket numbers to tickets on pear.php.net instead.  This means that you get very random results if you follow the ticket links!

For example
> Fixed [bug #622](https://pear.php.net/bugs/622) : Wrong detection of Squiz.CSS.DuplicateStyleDefinition with media queries

instead of 
> Fixed [bug #622](https://github.com/squizlabs/PHP_CodeSniffer/issues/622) : Wrong detection of Squiz.CSS.DuplicateStyleDefinition with media queries

This needs to be fixed for existing changelog entries as well as for any new releases.

**Comment by gsherwood** [comment]
My changelogs are all plain text on PEAR. PEAR is creating those links and there isn't anything I can do about them.

**Comment by MarkMaldaba** [comment]
Oh - that's annoying!  Perhaps using the word 'git issue' instead of 'bug' for the git ones will stop the auto-linking from kicking in?

**Comment by gsherwood** [comment]
I could change it, but I'd rather not change the way the changelogs read. I've stopped linking to the PEAR notes quite a while ago because I have very little control over them.

**Comment by MarkMaldaba** [comment]
It is confusing, though, as some of the numbers still refer to tickets on pear.php.net, whilst others refer to Github.  If you know what you're doing you can probably work it out by the size of the number, but it is pretty counter-intuitive.  Personally, I think it would read better if you distinguished between the two ticketing systems somehow, regardless of the auto-linking issue.

**Comment by MarkMaldaba** [comment]
Plus 'issue' is the terminology that Github uses, and 'bug' is the terminology that PEAR uses, so it makes sense to use the correct term in the relevant context.

**Comment by MarkMaldaba** [comment]
Hi @gsherwood - just checking you saw my above comments, as you closed this ticket rather hastily.

I don't know how much work it is to update the existing release notes (which would be the best outcome, and would help make the web better!), but I think that at the very least you should adopt this approach for all future releases, to stop more confusing links being incorrectly generated.

**Comment by gsherwood** [comment]
I'm not going to change the release notes. This is how I format bug fixes for all products I work on and I moved away from the PEAR bug tracker years ago.

**Comment by MarkMaldaba** [comment]
A bit of an exaggeration - last closed bug mentioned in release notes was July last year: https://pear.php.net/bugs/bug.php?id=21050

Maybe you could ask for the auto-linking to be disabled for this package?

Given this project is all about standards and best-practice, I would have thought you would be more opposed to generating bad links which break the web and cause confusion.
