### ISSUE TITLE
phpcbf adds (incorrect) positional designations to format strings

### ISSUE THREAD

**Issue by paulschreiber** [squizlabs/PHP_CodeSniffer#1380]
Here's a before and after, using the WordPress-VIP ruleset:
```
-_doing_it_wrong( __FUNCTION__, sprintf( __( 'Analytics entry for %s is missing one of the following keys: `type`, `attributes`, or `config_data` (array keys: %s)', 'amp' ), esc_html( $id ), esc_html( implode( ', ', array_keys( $analytics_entry ) ) ) ), '0.3.2' );
+_doing_it_wrong( __FUNCTION__, sprintf( __( 'Analytics entry for %1$s is missing one of the following keys: `type`, `attributes`, or `config_data` (array keys: %1$s)', 'amp' ), esc_html( $id ), esc_html( implode( ', ', array_keys( $analytics_entry ) ) ) ), '0.3.2' );
```

PHPCBF changed %s to %1$s. It should leave those as-is and/or not use %1$s twice in the same string.

**Comment by jrfnl** [comment]
@paulschreiber This is not a PHPCS issue, but an issue with the WordPress Coding Standards, previously reported in https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/698 and fixed October last year in https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/710
