### ISSUE TITLE
Final underscore in class names

### ISSUE THREAD

**Issue by marcosh** [squizlabs/PHP_CodeSniffer#1382]
As per `PSR-1` specifications, class names must be in `StudlyCaps`.

However, if I want to define a class named `Echo` (or any other Php keyword), I am not able to do that  beacuse if I do so I obtain a parse error.

It seems that the standard solution to this issue is to add an `_` at the end of the class, as in `Echo_`. For example, look in [https://github.com/nikic/PHP-Parser/tree/3.x/lib/PhpParser/Node/Stmt](https://github.com/nikic/PHP-Parser/tree/3.x/lib/PhpParser/Node/Stmt).

Such a solution produces an error when running CodeSniffer, since the `_` in not an allowed character in a class name.

I was wondering if it makes sense to allow the presence of a final underscore in a class name, maybe only when the class name in a reserved keyword

**Comment by gsherwood** [comment]
This isn't a question that I could answer as I wasn't involved with the writing of the PSR1 or PSR2 standards. You might want to post this question to the PHP-FIG mailing list directly and see if they had some intention of allowing this, or would incorporate a recommendation into the PSR-12 standard.

**Comment by marcosh** [comment]
As per FIG answer (https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/php-fig/0yEk60y2RVE), `StudlyCaps` should be interpreted strictly and not allow the presence of a final underscore

**Comment by gsherwood** [comment]
Thanks a lot for sorting that out.
