### ISSUE TITLE
Option to cancel word wrapping in reports

### ISSUE THREAD

**Issue by mityukov** [squizlabs/PHP_CodeSniffer#1389]
Good morning!

Here's what `phpcs --no-colors` produces:
```
----------------------------------------------------------------------
FOUND 69 ERRORS AFFECTING 66 LINES
----------------------------------------------------------------------
  35 | ERROR | [x] Spaces must be used to indent lines; tabs are not
     | | allowed
  37 | ERROR | [x] Spaces must be used to indent lines; tabs are not
     | | allowed
  47 | ERROR | [x] Spaces must be used to indent lines; tabs are not
     | | allowed
  56 | ERROR | [x] Spaces must be used to indent lines; tabs are not
     | | allowed
```

Is there an option to cancel those word wraps at the end of lines? I usually send these reports into an internal bug tracker, so, it's really not for reading in console.

Thank you in advance.

**Comment by jrfnl** [comment]
@mityukov You could use the ` --report-width=##` option and set it to a high number maybe ?

```bash
phpcs --no-colors --report-width=1000
```
Ref: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Usage#getting-help-from-the-command-line

You can also change the report-width for every report generated by your install of phpcs:
```bash
phpcs --config-set report_width 500
```
Ref: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options#setting-the-default-report-format

**Comment by gsherwood** [comment]
What @jrfnl said :)

There is no option to disable word wrapping, but you can't set the width to a really high number so that wrapping never takes place.

I'll leave this as a feature request to add an option for disabling wrapping, but I think it would be pretty low priority if the workaround can be used.

**Comment by gsherwood** [comment]
Closing as there is no additional interest. I suggest using a really high report width value instead.
