### ISSUE TITLE
Empty queue in docker container

### ISSUE THREAD

**Issue by zajca** [squizlabs/PHP_CodeSniffer#1391]
I have following ruleset.xml in my project
```
<?xml version="1.0"?>
<ruleset name="MY">
    <description>MY coding standart</description>
    <file>./src</file>
    <exclude-pattern>*/Tests/*</exclude-pattern>
    <exclude-pattern>app/*</exclude-pattern>
    <exclude-pattern>var/*</exclude-pattern>
    <exclude-pattern>web/*</exclude-pattern>
    <!-- Include the whole PSR-2 standard -->
    <rule ref="PSR2">
        <!-- to disable a single error -->
        <exclude name="Generic.Files.LineLength"/>
    </rule>
</ruleset>
```

When I run ```./vendor/bin/phpcs ``` on my local machine sniffer works ```Creating file list... DONE (184 files in queue)```
But when I run the same from same place inside container I get ```Creating file list... DONE (0 files in queue)```

I try to debug command with ```-vvv``` but output is same. It same root directory and parsing same XML file.

php version:
container:
```
PHP 7.1.2 (cli) (built: Feb 28 2017 17:50:42) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.2, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.1, Copyright (c) 2002-2017, by Derick Rethans

```
local:
```
PHP 7.1.2 (cli) (built: Mar 12 2017 21:40:31) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.1, Copyright (c) 2002-2017, by Derick Rethans
```

phpcs version:
```
PHP_CodeSniffer version 2.8.1 (stable) by Squiz (http://www.squiz.net)
```

**Comment by gsherwood** [comment]
Have you tried running PHPCS with a different standard (e.g., `--standard=PSR2`) and specifying the `./src` directory on the command line? Does it find files to run over?

**Comment by zajca** [comment]
When I run ```./vendor/bin/phpcs --standard=PSR2 ./src``` it work's.
...
I'm stupid problem was in exclude-pattern.

I'm excluding stuff which are above src folder, which is nonsense.

And main problem was with ```var/*``` in docker container is project in ```/var/www``` which will match pattern.

Sorry for wasting your time :/

**Comment by gsherwood** [comment]
Thanks for investigating that and getting back to me.

**Comment by danepowell** [comment]
I don't think this is the user's fault at all. This seems like a pretty clear bug, or at least an unintuitive foot-gun that's bound to cause frustration. In what scenario would it make sense for an exclude pattern to apply to the entire directory where you are running PHPCS?
