### ISSUE TITLE
PSR-2 EndFileNewlineSniff is wrong

### ISSUE THREAD

**Issue by Xerkus** [squizlabs/PHP_CodeSniffer#1401]
PSR-2 specifies `All PHP files MUST end with a single blank line.`
While sniff is actually checking for a single ***line feed***, essentially enforcing there is NO empty lines at the end of the file.

Enforced rule is of currently proposed extended coding standard: `All PHP files MUST end with a non-blank line, terminated with a single LF.` 

I'm not sure if this issue should be fixed.

**Comment by gsherwood** [comment]
I had this clarified by the PHP FIG back in 2012: https://groups.google.com/d/msg/php-fig/PSzmcFVQst0/cfxJvzTw3qkJ

The proposed extended coding standard changes the wording so it is actually clear, but the intention of PSR-2 is that there is a single LF char at the end of the file. It just so happens that some text editors (like Sublime Text) show this as an empty line at the end of the file, which is probably why it was written that way.
