### ISSUE TITLE
Version 3.0.0 Release Date and Upgrade Process

### ISSUE THREAD

**Issue by grappler** [squizlabs/PHP_CodeSniffer#1410]
When is Version 3.0.0 planned to be released? An estimated idea would be sufficient. 

What expected changes need to be made to custom sniffs so that they are compatible with version 3.0.0?

3.0.0 has some cool features like https://github.com/squizlabs/PHP_CodeSniffer/issues/1215 I would like to take advantage of but need to figure out the investment needed in updating custom sniffs.

Thanks

**Comment by gsherwood** [comment]
> When is Version 3.0.0 planned to be released? An estimated idea would be sufficient.

My plan is for the current RC to be the last RC before stable. I don't have a date, but it's probably only a few weeks away. I just need to make some decisions on pending PRs.

> What expected changes need to be made to custom sniffs so that they are compatible with version 3.0.0?

There is a complete guide here: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Version-3.0-Upgrade-Guide

It's not overly complex. The biggest change is the enforcement of namespaces.
