### ISSUE TITLE
Option to disable all checking of STDIN

### ISSUE THREAD

**Issue by MetalArend** [squizlabs/PHP_CodeSniffer#1417]
I'm trying to run some script with bash and docker. I got some unexpected behavior, simplest way to reproduce it is running a bash script as follows:

```shell
#!/usr/bin/env bash

mkdir bug && echo "<?php phpinfo();" > bug/index.php
docker run -i --rm --name phpcs -v "$PWD":/usr/src/bug -w /usr/src/bug -e COMPOSER_ALLOW_SUPERUSER=1 php:7.1-cli bash <<EOC
    # Install tools
    apt-get update -q && apt-get install -y wget zip
    # Get composer 1.4.1
    wget https://raw.githubusercontent.com/composer/getcomposer.org/a68fc08d2de42237ae80d77e8dd44488d268e13d/web/installer -O - -q | php -- --quiet
    # Require PHP_CodeSniffer
    php composer.phar global require --dev --no-progress squizlabs/php_codesniffer
    # Run PHP_CodeSniffer
    ~/.composer/vendor/bin/phpcs -n -vv ./bug
    # Rest of the script
    echo "this could have been visible"
EOC
rm -rf bug/index.php
```

If you run this, the last part of the verbose output looks like this:
```
[...]
=> Ruleset processing complete; included 70 sniffs and excluded 0
	*** START PHP TOKENIZING ***
	Process token [0]: T_OPEN_TAG => <?php·
	Process token [1]: T_FUNCTION => function
	Process token [2]: T_WHITESPACE => ·
	Process token [3]: T_STRING => ?>
	*** END PHP TOKENIZING ***
	*** START PHP TOKENIZING ***
	Process token [0]: T_OPEN_TAG => <?php·
	Process token  1 : T_OPEN_PARENTHESIS => (
	Process token [2]: T_CLOSE_TAG => ?>
	*** END PHP TOKENIZING ***
	*** START PHP TOKENIZING ***
	Process token [0]: T_OPEN_TAG => <?php·
	Process token  1 : T_SEMICOLON => ;
	Process token [2]: T_CLOSE_TAG => ?>
	*** END PHP TOKENIZING ***
	*** START PHP TOKENIZING ***
	Process token [0]: T_OPEN_TAG => <?php·
	Process token [1]: T_FUNCTION => function
	Process token [2]: T_WHITESPACE => ·
	Process token [3]: T_STRING => ?>
	*** END PHP TOKENIZING ***
	*** START PHP TOKENIZING ***
	Process token [0]: T_OPEN_TAG => <?php·
	Process token  1 : T_OPEN_PARENTHESIS => (
	Process token [2]: T_CLOSE_TAG => ?>
	*** END PHP TOKENIZING ***
	*** START PHP TOKENIZING ***
	Process token [0]: T_OPEN_TAG => <?php·
	Process token [1]: T_ABSTRACT => abstract
	Process token [2]: T_WHITESPACE => ·
	Process token [3]: T_FUNCTION => function
	Process token [4]: T_WHITESPACE => ·
	Process token [5]: T_STRING => ?>
	*** END PHP TOKENIZING ***
	*** START PHP TOKENIZING ***
	Process token [0]: T_OPEN_TAG => <?php·
	Process token  1 : T_OPEN_PARENTHESIS => (
	Process token [2]: T_CLOSE_TAG => ?>
	*** END PHP TOKENIZING ***
	*** START PHP TOKENIZING ***
	Process token [0]: T_OPEN_TAG => <?php·
	Process token  1 : T_SEMICOLON => ;
	Process token [2]: T_CLOSE_TAG => ?>
	*** END PHP TOKENIZING ***
Creating file list... DONE (1 files in queue)
Changing into directory /usr/src/bug/bug
Processing index.php 
	*** START PHP TOKENIZING ***
	Process token [0]: T_OPEN_TAG => <?php·
	Process token [1]: T_STRING => phpinfo
	Process token  2 : T_OPEN_PARENTHESIS => (
	Process token  3 : T_CLOSE_PARENTHESIS => )
	Process token  4 : T_SEMICOLON => ;
	Process token [5]: T_WHITESPACE => \n
	*** END PHP TOKENIZING ***
	*** START TOKEN MAP ***
	*** END TOKEN MAP ***
	*** START SCOPE MAP ***
	*** END SCOPE MAP ***
	*** START LEVEL MAP ***
	Process token 0 on line 1 [col:1;len:6;lvl:0;]: T_OPEN_TAG => <?php·
	Process token 1 on line 1 [col:7;len:7;lvl:0;]: T_STRING => phpinfo
	Process token 2 on line 1 [col:14;len:1;lvl:0;]: T_OPEN_PARENTHESIS => (
	Process token 3 on line 1 [col:15;len:1;lvl:0;]: T_CLOSE_PARENTHESIS => )
	Process token 4 on line 1 [col:16;len:1;lvl:0;]: T_SEMICOLON => ;
	Process token 5 on line 1 [col:17;len:0;lvl:0;]: T_WHITESPACE => \n
	*** END LEVEL MAP ***
	*** START ADDITIONAL PHP PROCESSING ***
	*** END ADDITIONAL PHP PROCESSING ***
[PHP => 6 tokens in 1 lines]... 
DONE in 3ms (0 errors, 0 warnings)
Processing STDIN 
	*** START PHP TOKENIZING ***
	Process token [0]: T_INLINE_HTML => ····#·Rest·of·the·script\n····echo·"this·could·have·been·visible"\n
	*** END PHP TOKENIZING ***
	*** START TOKEN MAP ***
	*** END TOKEN MAP ***
	*** START SCOPE MAP ***
	*** END SCOPE MAP ***
	*** START LEVEL MAP ***
	Process token 0 on line 1 [col:1;len:24;lvl:0;]: T_INLINE_HTML => ····#·Rest·of·the·script\n
	Process token 1 on line 2 [col:1;len:39;lvl:0;]: T_INLINE_HTML => ····echo·"this·could·have·been·visible"\n
	*** END LEVEL MAP ***
	*** START ADDITIONAL PHP PROCESSING ***
	*** END ADDITIONAL PHP PROCESSING ***
[PHP => 2 tokens in 2 lines]... 
DONE in 1ms (0 errors, 0 warnings)
```

I would expect no STDIN to be read, as I provided a "./bug" directory to the phpcs script. Probably there is something going on while detecting the end of STDIN inside the HEREDOC syntax. I have tried this with some other tools as well (like phpstan, psalm and php-cs-fixer), and all of them are working like expected.

I have no clue at all as to what is going on, so if you have any idea to what I could try to pinpoint the misbehaving part, I'm happy to help.

* Edited, provided the complete log starting after ruleset processing
* Edited, removed the hardcoded xml code standard, not needed to reproduce

**Comment by gsherwood** [comment]
There was obviously content on STDIN that PHPCS detected due to the way it was run. If content is passed on STDIN, it will be processed along with any files that are specified on the command line.

**Comment by MetalArend** [comment]
Yes, it detects the rest of the content from the HEREDOC as being from the STDIN:
```
    # Rest of the script
    echo "this could have been visible"
```
as is reported by the verbose output
```
Process token [0]: T_INLINE_HTML => ····#·Rest·of·the·script\n····echo·"this·could·have·been·visible"\n
```

Basically, if I would put any commands after the `~/.composer/vendor/bin/phpcs -n -vv --standard=./phpcs.xml ./bug` line, they would all be detected as STDIN, and thus not being executed.

Right now, I'm running PHPCS as the last program in a series of six tools, because it is the only one not correctly detecting the STDIN stops where it stops, so it will take every line after it's call and try to analyse it.
I'm not ruling out though that there is a chance that the other tools incorrectly detect that there is no STDIN, but the result is still the same, phpcs has to run as the last one.

Is there any way I can help you with some debug information to sort this out? Anything I could do to help?

**Comment by MetalArend** [comment]
It seems this comes directly from the php://stdin stream. The code doing this is around [CLI.php#L409](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/CLI.php#L409).

If I try to get the PHP STDIN input at any point with `gets(STDIN)`, it always returns the lines that should not be there. I'm wondering by now how the other tools are avoiding this.

**Comment by MetalArend** [comment]
It's not phpcs related, it seems, but it might have something to do with the way php handles STDIN. Take this very simple example:

```
#!/usr/bin/env bash

echo -e "\n\033[4mSingle fgets:\033[0m"
docker run -i --rm -v "$PWD":/usr/src/app -w /usr/src/app php:7.1-cli bash <<EOC
    php -r 'var_dump("line read by single fgets: " . fgets(STDIN));'
    php -r 'while ((\$line = fgets(STDIN)) !== false) { var_dump("line read by stdin loop: " . \$line); }'
    php -r 'var_dump("this line is not read by fgets, but is also not executed");'
EOC
echo -e "\n\033[4mWhile loop:\033[0m"
docker run -i --rm -v "$PWD":/usr/src/app -w /usr/src/app php:7.1-cli bash <<EOC
    php -r 'while ((\$line = fgets(STDIN)) !== false) { var_dump("line read by stdin loop: " . \$line); }'
    php -r 'var_dump("this line is read by the while loop");'
EOC
echo -e "\n\033[4mSimple echo:\033[0m"
docker run -i --rm -v "$PWD":/usr/src/app -w /usr/src/app php:7.1-cli bash <<EOC
    php -r 'var_dump("this is what I would expect");'
EOC
```

However, still wondering how other tools like php_cs, phpstan, composer, ... are doing this another way, as I would expect doing such a while loop is quite the logical thing to do. Odd, very odd.

**Comment by gsherwood** [comment]
> I'm wondering by now how the other tools are avoiding this.

Maybe they either don't read from STDIN, or they ignore STDIN when they have a file to check?

**Comment by MetalArend** [comment]
Is there some option or environment variable that I could send phpcs to ignore STDIN completely? Or is it that something that could be added?

**Comment by gsherwood** [comment]
> Is there some option or environment variable that I could send phpcs to ignore STDIN completely?

There isn't.

It could be added, but this check is done before any CLI processing occurs, so I'd probably only give it a go in the 3.x version, and I'm not really sure what the best way to do it would be just yet.

I'll leave this idea as a feature request for that.

**Comment by mwgamble** [comment]
I'm running into this same situation when attempting to run PHPCS inside of a docker container via PhpStorm's built-in integration. It hangs indefinitely when the container isn't allocated a pesudo-TTY, and PhpStorm simply can't use it. Ideally it would be an environment variable, as PhpStorm doesn't let you control arbitrary arguments to PHPCS or Docker.

**Comment by gsherwood** [comment]
@mwgamble Are you trying this on the 3.2.0 version?

**Comment by mwgamble** [comment]
Yep.

**Comment by gsherwood** [comment]
> Yep.

Thanks. This was reported with different STDIN processing code, so it's helpful to know the new code is the same.

**Comment by gsherwood** [comment]
@mwgamble If possible, can you grab the latest master code and try PHPStorm again. I managed to replicate the issue and have changed the STDIN processing code to fix it for my install.

**Comment by arnested** [comment]
FYI: I ran my "CLI tests" on master and they still work.

**Comment by gsherwood** [comment]
Closing as I believe these STDIN issues are now resolved. If not, please report a new issue with specific details.
