### ISSUE TITLE
Code Consistency report for private repositories

### ISSUE THREAD

**Issue by krukru** [squizlabs/PHP_CodeSniffer#1418]
Hi. Will it ever be possible to generate a code consistency report [like this one](https://squizlabs.github.io/PHP_CodeSniffer/analysis/index.html) for private repositories?

**Comment by jrfnl** [comment]
Hi @krukru You already can ;-) The layout may not be as nice, but if you use the `info` report style and combine it with a number of different standards (in this case, the more, the better), you will get a report showing the predominant styles used in your project.

```
phpcs . --standard=PEAR,PSR2,Zend --report=info
```

For more information: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Reporting#printing-an-information-report

**Comment by gsherwood** [comment]
Yep, that info report is the closest you'll get for private repos.

The code that generates those web reports uses the same metric data but also uses a custom report class to output it as JSON. Custom scripts then go over the data to determine trends and generates the HTML output.

It works best when you've got a lot of repos, and I've got no plans to ever turn it into an actual product or package.

**Comment by krukru** [comment]
Awesome, many thanks
