### ISSUE TITLE
Ignore code style issues in method signature of interface implementations

### ISSUE THREAD

**Issue by arnaud-lb** [squizlabs/PHP_CodeSniffer#1422]
Sometimes we have to implement interfaces that use a different code style. For instance, the builtin `SessionIdInterface` in PHP has a method `create_sid` that violates some rules in PSR2.

It would be great if PHP_CodeSniffer could ignore any code style violation in _signature_ of methods that are an implementation of an interface. The actual code style violation is on the interface. If the interface itself is part of the project being checked, then PHP_CodeSniffer will report a violation while analyzing the interface anyway. If it's not part of the project, then PHP_CodeSniffer will not report a violation, and this is fine, since the project can not do anything about that.

**Comment by jrfnl** [comment]
@arnaud-lb Which sniff are you talking about ? I can't seem to find a CamelCase sniff in PSR2...
If you're unsure, run PHPCS with the `-s` option to see the sniff name in the report.

**Comment by arnaud-lb** [comment]
@jrfnl For example, PSR1.Methods.CamelCapsMethodName.NotCamelCaps. Also, PEAR.Functions.ValidDefaultValue.NotAtEnd.

**Comment by jrfnl** [comment]
@arnaud-lb Ah, thanks. I thought I'd send in a PR for that, but I guess that was for an external standard.

Actually - it was, I just checked. In the [WPCS sniff for function names](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/develop/WordPress/Sniffs/NamingConventions/ValidFunctionNameSniff.php), any methods within extended classes or classes which implement an interface are ignored for precisely the reason you mention in the original issue description.

**Comment by gsherwood** [comment]
Closing due to the fact that changes to these sniffs would require changes in their published coding standards as well, which isn't going to happen.
