### ISSUE TITLE
ERROR: Job failed: exit code 1

### ISSUE THREAD

**Issue by JoyG42** [squizlabs/PHP_CodeSniffer#1426]
When I use following command to gitlab-ci analysis stage Build Failed with exit code 1

- phpcs -s -q --standard="PSR1,PSR2" . >>  error.txt

Can You Help me to solve It??

I also used  together
phpcs --config-set ignore_warnings_on_exit 1 
phpcs -s -q --standard="PSR1,PSR2" .

But still failed.... :(

**Comment by gsherwood** [comment]
Closing as this is now very old. If you still have this issue, please re-report with more output as there isn't enough here to diagnose an issue.
