### ISSUE TITLE
Add OpenEMR Project to Code Analysis

### ISSUE THREAD

**Issue by robertdown** [squizlabs/PHP_CodeSniffer#1427]
Hello,

I'm one of the Project Administrators of the [OpenEMR](http://github.com/openemr/openemr) project and would love to see our project added to the list of code analysis.

OpenEMR is an open source electronic health record management and practice management web based app. Here is some info for you (Based on [this SO question](http://stackoverflow.com/questions/38928162/code-consistency-badge-for-packages-using-php-codesniffer)). Note we are GPL-licensed

Name: **OpenEMR**
URL: **https://github.com/openemr/openemr**
Path: **Root**
Ignore: **Inside phpcs.xml document located in root** (Can provide more info if needed)
Extension: **Unsure about this one**

Thanks for your consideration

**Comment by gsherwood** [comment]
I've added the repo here: https://squizlabs.github.io/PHP_CodeSniffer/analysis/openemr/openemr/index.html

See if you think those metrics looks right to you. If not, maybe there are some other exclusions that need to be added. I pulled the ones from the bottom of your phpcs.xml file for the reports.

Something appears to have happened to the repo between Sep and Oct 2016, with lots of files being removed. I haven't had time to go looking to see if that is accurate, but please let me know if you think something has been picked up incorrectly.

**Comment by robertdown** [comment]
Thanks for accepting the project. I'll review the report and see if things look right.

Is this report static, or as we improve our code standards can we expect to see the C+ bump it's way up?

**Comment by gsherwood** [comment]
> Is this report static, or as we improve our code standards can we expect to see the C+ bump it's way up?

I run it on the 1st of each month and recalculate the consistency ratings then. So yes, ratings can move significantly as they are only based on the latest run.
