### ISSUE TITLE
Dependency on patch command 

### ISSUE THREAD

**Issue by ghunti** [squizlabs/PHP_CodeSniffer#1428]
Hi.
I'm using `phpcbf` on a Docker container based on `php:7-cli` official image, and had to install the `patch` command in order for the `phpcbf` to fix my file.
I've searched and I haven't found a mention to this dependency either on the docs or wiki.

Cheers

**Comment by jrfnl** [comment]
It is mentioned in the wiki page about fixing (first paragraph): https://github.com/squizlabs/PHP_CodeSniffer/wiki/Fixing-Errors-Automatically

**Comment by ghunti** [comment]
@jrfnl My bad. Although it's not "screaming" at you for that dependency, it states that the `patch` command is used, so we can infer the dependency.
Sorry for the trouble

**Comment by jrfnl** [comment]
No worries, just trying to point you in the right direction ;-)

**Comment by jrfnl** [comment]
Oh and FYI: you can also run PHPCS with the `--no-patch` or the `--suffix=.myfixed` command line option. Neither of those two use `patch`.

Both are documented in the [Using the PHP Code Beautifier and Fixer](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Fixing-Errors-Automatically#using-the-php-code-beautifier-and-fixer) section, `no-patch` about half-way through that section, `suffix` towards the end.

**Comment by gsherwood** [comment]
Also note that the 3.x version no longer uses `patch`. From the changelog:

- PHPCBF no longer uses patch
    - Files are now always overwritten
    - The --no-patch option has been removed
