### ISSUE TITLE
"Must be absolute paths" error when installing on distant server

### ISSUE THREAD

**Issue by Tekover** [squizlabs/PHP_CodeSniffer#1429]
Good Day,

I'm trying to install PHPCS through Bedrock, with success if done on a local server, however, when I tried to install it on a distant dev server it gives me the following error.

`Installs: squizlabs/php_codesniffer:2.8.1
  - Installing squizlabs/php_codesniffer (2.8.1): Loading from cache Extracting archive

  [InvalidArgumentException]
  $from (\\192.168.205.29\WWW\agsrecordsmanagement\bedrock\192.168.205.29\www
  \agsrecordsmanagement\bedrock\vendor\bin/phpcs) and $to (\\192.168.205.29\W
  WW\agsrecordsmanagement\bedrock\vendor\squizlabs\php_codesniffer\scripts\ph
  pcs) must be absolute paths.
`

All the other dependencies have been installed with success.

Below is the result from --verbose:
Exception trace:
 () at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Util/Filesystem.php:325
 Composer\Util\Filesystem->findShortestPath() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Installer/Bin                                                   aryInstaller.php:189
 Composer\Installer\BinaryInstaller->generateUnixyProxyCode() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Compos                                                   er/Installer/BinaryInstaller.php:167
 Composer\Installer\BinaryInstaller->installUnixyProxyBinaries() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Com                                                   poser/Installer/BinaryInstaller.php:146
 Composer\Installer\BinaryInstaller->installFullBinaries() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/                                                   Installer/BinaryInstaller.php:86
 Composer\Installer\BinaryInstaller->installBinaries() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Inst                                                   aller/LibraryInstaller.php:91
 Composer\Installer\LibraryInstaller->install() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Installer/I                                                   nstallationManager.php:173
 Composer\Installer\InstallationManager->install() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Installe                                                   r/InstallationManager.php:160
 Composer\Installer\InstallationManager->execute() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Installe                                                   r.php:584
 Composer\Installer->doInstall() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Installer.php:223
 Composer\Installer->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Command/InstallCommand.php:119
 Composer\Command\InstallCommand->execute() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Comma                                                   nd/Command.php:267
 Symfony\Component\Console\Command\Command->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console                                                   /Application.php:846
 Symfony\Component\Console\Application->doRunCommand() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/co                                                   nsole/Application.php:191
 Symfony\Component\Console\Application->doRun() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/App                                                   lication.php:227
 Composer\Console\Application->doRun() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Applicatio                                                   n.php:122
 Symfony\Component\Console\Application->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Appli                                                   cation.php:100
 Composer\Console\Application->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/bin/composer:54
 require() at C:\ProgramData\ComposerSetup\bin\composer.phar:24

any idea ?

Thanks for your help.

**Comment by gsherwood** [comment]
Some similar composer-based error was report before: https://github.com/squizlabs/PHP_CodeSniffer/issues/905

I never found out if that was resolved, but no PHPCS code was running during install, so there was nothing I could do.

This is probably the same sort of thing. PHPCS does not have any install scripts, so this is probably an issue with whatever installer you are using, not returning absolute paths to composer, or composer not understanding them. You'll have to seek help from one of those projects as there isn't anything I can do here.
