### ISSUE TITLE
PHPDoc: Multiple exceptions in one catch block

### ISSUE THREAD

**Issue by alexz707** [squizlabs/PHP_CodeSniffer#1437]
HI!
With phpcs 2.8.1 as well as with 3.0.0RC4 I have a Problem with multiple excpetions in one catch block:

When I catch two exceptions with the | operator the exceptions are not treated as catched.

Example is attached
![bildschirmfoto 2017-04-29 um 18 14 53](https://cloud.githubusercontent.com/assets/562324/25556975/ea190106-2d07-11e7-9e33-6a9830927d52.png)

**Comment by gsherwood** [comment]
That doesn't look like an error from an included PHPCS sniff. What coding standard are you using? Can you run PHPCS on the command line and replicate the issue? If so, running it with the `-s` argument will tell you which sniff is reporting the error.

Also, it's a lot easier to replicate issues if you can paste the code as well as showing the screenshot of the error.
