### ISSUE TITLE
Proper way to specify file path for STDIN input?

### ISSUE THREAD

**Issue by Arcanemagus** [squizlabs/PHP_CodeSniffer#1440]
It seems the output of `phpcs --help` shows that the correct way to specify the file name for STDIN input is to write the command as it it were a regular file, and then simply add `-` on the end, like this:
```
phpcs --options foo.php -
```

Is this correct and the "right" way to do this for PHPCS v3? Currently I'm using the older `--stdin-path` option which still seems to be working in v3, but isn't documented, so I'd like to make sure it is as correct as possible for v3.

**Comment by gsherwood** [comment]
The `--stdin-path` option is still the way to do this, but it looks like I forgot to add it to the help output back when I first merged it, so I'll do that now.

The `-` option is only used to tell PHPCS that you want it to wait for input if nothing was found (no files specified, and no STDIN redirect to it). In version 2.x, PHPCS would always wait, which looked like it was doing something when it really wasn't.

Summary: keep doing things the way you were doing them with version 2.

**Comment by gsherwood** [comment]
I've added the help text now. Thanks for letting me know it was missing.

**Comment by Arcanemagus** [comment]
Thanks for the clarification!
