### ISSUE TITLE
[Feature request] Add stats at the end

### ISSUE THREAD

**Issue by steevanb** [squizlabs/PHP_CodeSniffer#1445]
Hi !

Could you please add some stats after sniffs finished ?
Some ideas :
- files count without error
- files count  with errors
- errors count
- warnings count
- errors could be resolved automaticaly count

Thanks !

**Comment by gsherwood** [comment]
The report types are in charge of showing information about a run, and they already show all these stats.

You might want to take a look at the various report types, starting with the full and summary reports: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Reporting#printing-full-and-summary-reports

If you want something more specific, you can write your own report class and have PHPCS output content in a very specific way.

**Comment by steevanb** [comment]
Ok, didn't know that, thanks !
