### ISSUE TITLE
Extension points to implement custom report filtering in PHP_CodeSniffer 3.0

### ISSUE THREAD

**Issue by morozov** [squizlabs/PHP_CodeSniffer#1446]
I maintain (mostly for myself) [a tool](https://github.com/morozov/diff-sniffer-pre-commit) which uses PHP_CodeSniffer internally and reports on the code standard violations introduced by a given git commit. It runs PHP_CodeSniffer on the changed files and displays only the errors in the lines affected by the commit.

In PHP_CodeSniffer 2, I found the needed extension point in the `PHP_CodeSniffer_Report` interface. I [replace the actual report implementation with a wrapper](https://github.com/morozov/diff-sniffer-core/blob/2.3.0.1/src/DiffSniffer/Runner.php#L175) on the fly and then [filter the report data](https://github.com/morozov/diff-sniffer-core/blob/2.3.0.1/src/DiffSniffer/CodeSniffer/Reports/DiffSniffer.php#L116-L130).

I tried different approaches hooking this logic into the flow of PHP_CodeSniffer 3 but didn't find a decent solution yet. To my understanding, it could be either a wrapper around the `LocalFile` class, or a wrapper around `Reporter`.

Which APIs would you suggest using?

**Comment by gsherwood** [comment]
I don't have time at the moment to try out a few things and see what you need, but I'd start with building your own runner for 3.x and override the report they selected on the command line so you can replace it with your own. There is a gist with some example code here: https://gist.github.com/gsherwood/aafd2c16631a8a872f0c4a23916962ac

You can store the reports they asked for by accessing `$runner->config->reports` and then override that value with your own.

Is that something like what you are after?

**Comment by morozov** [comment]
> Is that something like what you are after?

Not really. The existing runner is almost 800 LOC, and I wouldn't like to re-implement it myself. If at some point in time a new feature lands in the original runner, I want it to be available automatically in my tool by just updating dependencies.

I was more alluding to having some dependency injection around the APIs I mentioned above. E.g. instead of instantiating `Reporter` in a private method, `Runner` could get it injected as a constructor argument.

To the point of extensibility and testability, in version 2, `PHP_CodeSniffer_CLI::process()` could be used outside of PHP_CodeSniffer so that its return value (the number of errors) was handled by the caller. In version 3, `Runner` `exit()`s which makes it harder to reuse or test (I mean unit testing). Instead, it could return exit code and delegate `exit` to _bin/php{cs|cbf}_.

Not sure if the above aligns with the project goals, so I'd like to hear your opinion first.

Thank you for your time and work.

**Comment by gsherwood** [comment]
> The existing runner is almost 800 LOC, and I wouldn't like to re-implement it myself.

I didn't mean "write your own runner". I meant, write a wrapper that uses the existing runner, which is what I was showing in the sample code I linked to. That's like writing your own runPHPCS method.

> In version 3, Runner exit()s which makes it harder to reuse or test (I mean unit testing).

It only exists on error or if you call runPHPCS or runPHPCBF directly, which you wouldn't be doing if you were trying to overwrite CLI values and get at the raw data.

It would be nice to know if you tried to use the linked code and which values you were unable to retrieve.

**Comment by morozov** [comment]
Yeah, it seems working. By re-implementing runner, I meant implementing the logic in `runPHPCS()` and `run()` but apparently using the example you provided I will not need it.

We can consider the issue resolved. Thank you.

**Comment by gsherwood** [comment]
> We can consider the issue resolved. Thank you.

Great. Glad you've sorted it out. Let me know if you hit any roadblocks and need some changes.
