### ISSUE TITLE
Running the unit tests with a phpunit config file breaks the test suite

### ISSUE THREAD

**Issue by jrfnl** [squizlabs/PHP_CodeSniffer#1447]
Running the unit tests with a custom phpunit config file like:
`phpunit -c customphpunit.xml`

breaks the unit test suite quite badly (sniffs can no longer be tested) with the following backtrace:
```
PHP_CodeSniffer\Exceptions\RuntimeException: ERROR: unable to get value of property "values"

PHP_CodeSniffer\src\Config.php:183
PHP_CodeSniffer\src\Config.php:638
PHP_CodeSniffer\src\Config.php:414
PHP_CodeSniffer\src\Config.php:324
PHP_CodeSniffer\tests\Standards\AbstractSniffUnitTest.php:134
PHP_CodeSniffer\tests\TestSuite.php:26
```

Some light debugging shows that the `Config::processShortArgument()` method chokes on the `-c`.

This used to work fine with PHPCS 2.x

**Comment by gsherwood** [comment]
The code to handle unknown CLI args didn't work in 3.0 due to some extra checks. I've added a specific setting `unknown` to store all the unknown args when they are being ignored (like during unit testing).

Thanks for reporting this.

**Comment by jrfnl** [comment]
Thanks for the quick fix!

**Comment by wimg** [comment]
@gsherwood : Any idea when 3.0.1 would be released ? Just to know if we can include the upgrade PHPCS to 3.x in the PHPCompatibility 7.1.5 release or we need to wait for 7.1.6.

**Comment by gsherwood** [comment]
@wimg I'm aiming for next week. Just finished up the last few things yesterday.
