### ISSUE TITLE
PHPCS 3.x: Autoloading of abstract base sniff not working when using a custom ruleset

### ISSUE THREAD

**Issue by jrfnl** [squizlabs/PHP_CodeSniffer#1453]
Quite apart from #1452, I'm still having trouble with the autoloader not finding files.

I'm testing on a git checkout of PHPCS `master` on PHP 5.6.23 with a local work-in-progress branch for the [PHPCompatibility](https://github.com/wimg/PHPCompatibility) standard.

### Issue 1 (PR submitted)
If I run just the one sniff against a set of files, no sniffs are being registered. This should be fixed by #1451.
```
phpcs ./test.inc --standard=PHPCompatibility --sniffs=PHPCompatibility.PHP.NewClasses
```

### Issue 2 (PR submitted)
If I run the complete standard against a set of files, the sniffs are being registered, but the first two are misidentified causing errors along the lines of `Fatal error:  Call to undefined method PHP_CodeSniffer\Util\Tokens::register()`. This should be fixed by #1452.
```
phpcs ./test.inc --standard=PHPCompatibility
```

### Issue 3 (not yet resolved)
Next, I'm trying to run the standard via a custom ruleset:
```
phpcs -vv ./test.inc --standard=phpcs.xml
```

Custom ruleset (minimal example):
```xml
<?xml version="1.0"?>
<ruleset name="PHPCS Coding Standards for PHPCompatibility">
	<arg value="sp"/>
	<arg name="extensions" value="php"/>

	<!-- Exclude test case code. -->
	<exclude-pattern>/Tests/sniff-examples/*</exclude-pattern>

	<config name="testVersion" value="5.3-99.0"/>
	<rule ref="PHPCompatibility"/>

	<rule ref="PSR2"/>
</ruleset>
```

I can see that the sniffs are being registered, but now it's not auto-loading the base sniff:
```
Fatal error: Class 'PHPCompatibility\Sniff' not found in \PHPCompatibility\PHPCompatibility\Sniffs\PHP\CaseSensitiveKeywordsSniff.php on line 29

Call Stack:
    0.0010     124464   1. {main}() PHP_CodeSniffer\bin\phpcs:0
    0.0050     288584   2. PHP_CodeSniffer\Runner->runPHPCS() PHP_CodeSniffer\bin\phpcs:18
    0.2790     711312   3. PHP_CodeSniffer\Runner->init() PHP_CodeSniffer\src\Runner.php:67
    0.2900     978352   4. PHP_CodeSniffer\Ruleset->__construct() PHP_CodeSniffer\src\Runner.php:273
    1.4431    1012328   5. PHP_CodeSniffer\Ruleset->registerSniffs() PHP_CodeSniffer\src\Ruleset.php:222
    1.4441    1018064   6. PHP_CodeSniffer\Autoload::loadFile() PHP_CodeSniffer\src\Ruleset.php:1089
    1.4481    1045680   7. include('I:\correct\path\to\PHPCompatibility\PHPCompatibility\Sniffs\PHP\CaseSensitiveKeywordsSniff.php') PHP_CodeSniffer\autoload.php:156
```

The directory structure is still the same and the sniffs are properly namespaced etc (well, otherwise the previous two runs wouldn't work either obviously).

Let me know if you need more information.

**Comment by gsherwood** [comment]
Any chance you could point me to the WIP branch so I can replicate these issues?

**Comment by jrfnl** [comment]
@gsherwood I've put the WIP branch online, the only thing I still need to sort out is the native unit test framework for the non-utility function tests, other than that things *should* be working ...
https://github.com/jrfnl/PHPCompatibility/tree/WAIT-429-4/feature/issue-367-phpcs-3.x-compatibility

Mind: it's a dirty branch and includes commits for four other PRs which will be pulled before I pull this one. The relevant commits start with the first `PHPCS 3.x compat` prefixed commit.

**Comment by gsherwood** [comment]
This 3rd issue is caused by PHPCS not being able to autoload files it doesn't know about. I have added an unreleased feature to the autoloader that also looks inside the directories for loaded custom standards, but it's not being registered in this case.

I'll take a look and see if I can figure out why not, and if there is a way to find this file. If not, it needs to be autoloaded by another autoloader, such as composer's one. Or it could be manually included I guess.

**Comment by gsherwood** [comment]
I've committed a change that adds the dirs inside installed_paths to the autoloader so it can find files like `PHPCompatibility\Sniff` and this seems to work for PHPCompat. Please let me know if it works for you too.

**Comment by jrfnl** [comment]
@gsherwood Thanks, will that later today as well.

It was just weird that the loading of the file worked when directly requesting the standard, but not when it was one of several standards being requested.

I'm really keeping my fingers crossed on this one as:
> Or it could be manually included I guess

Would mean having to include it from every single sniff class as the bootstrap loads after the sniffs have been loaded, so can't be used for that.

**Comment by jrfnl** [comment]
Tested & found working (with one small remark on the fix commit). Thanks.

**Comment by jrfnl** [comment]
Oh and just checking: Can I remove the WIP process ? Wouldn't want anyone to accidentally start using it yet.

**Comment by gsherwood** [comment]
> Can I remove the WIP branch ?

Yep, it looks like I'm all done. Thanks a lot for providing that though - it helped a huge amount.

**Comment by jrfnl** [comment]
Ok, thanks & happy to help.
