### ISSUE TITLE
Inconsistently overrides command line arguments

### ISSUE THREAD

**Issue by UziTech** [squizlabs/PHP_CodeSniffer#1457]
When `ruleset.xml` hard-codes command line values (e.g. `<arg name="report" value="summary"/>`) some can be overridden by command line arguments and some can not.

**Comment by UziTech** [comment]
This creates problems like #1444

**Comment by gsherwood** [comment]
I rewrote that code in version 3 to allow CLI values to easily override those from rulesets, but obviously didn't finish putting it everywhere. I've done that now, and all CLI values will override or merge with those in rulesets.

**Comment by Arcanemagus** [comment]
Looks like this has been broken since v2 from the testing I did while updating specs for AtomLinter/linter-phpcs.

Glad to see it will be fixed! (even if it means another special case handling there 😛)
