### ISSUE TITLE
Benefits of using install_paths

### ISSUE THREAD

**Issue by gmponos** [squizlabs/PHP_CodeSniffer#1476]
Hello,

Is there anyone here who is willing to explain to me the benefits of using [installed_paths](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options#setting-the-installed-standard-paths) with the new version of Codesniffer?

I believe that this configuration option is misleading and makes people misuse the new version. Since Codesniffer can now easily be installed as composer dependancy and all the packages that have been move to the new version can be also installed like a composer dependancy what is the use of this anymore?

**Comment by gsherwood** [comment]
The `installed_paths` setting is used used to tell PHPCS where coding standards are installed so they appears when running `phpcs -i`. Then you can use them with `--standard` without specifying their location on the file system.

Projects may contain custom coding standards somewhere deep within their directory structure. While PHPCS doesn't need to know where they are, it can help make PHPCS commands easier to run.

Of course, this is also a useful setting for when projects are not using composer. Again, it's not typically essential, but it certainly helps the autoloader figure out where things are, and again keeps the PHPCS commands simpler.
