### ISSUE TITLE
Exceptions to exclude-pattern?

### ISSUE THREAD

**Issue by davetgreen** [squizlabs/PHP_CodeSniffer#1494]
Is it possible to add exceptions to exclusions?

For example, I'd like to exclude all WordPress plugins, with the exception of one or two core plugins that we pull in during the initial project scaffold that still need to be checked before commit.

So, I'm currently excluding everything in the plugins folder like so...

`<exclude-pattern>build/wp-content/plugins/*</exclude-pattern>`

Here's some pseudo-code to illustrate what I'm after.

```
<exclude-pattern>build/wp-content/plugins/*</exclude-pattern>
<exclude-pattern>!build/wp-content/plugins/example-plugin</exclude-pattern>
```

I've tried adding an include after my list of excludes...

`<include-pattern>build/wp-content/plugins/example-plugin/*</include-pattern>`

...but this doesn't make any difference.

**Comment by gsherwood** [comment]
There is no specific feature to support this, so you'd have to get creative with the regular expression for the exclude pattern, probably using a negative lookahead to match everything except the folders you want checked.

I haven't tested this, but it's probably a regex like this (where `foo` and `bar` are the names of the plugins you want checked):

`<exclude-pattern>build/wp-content/plugins/(?!foo/|bar/)*/*</exclude-pattern>`

Does that help you out?

**Comment by davetgreen** [comment]
@gsherwood that regex worked **perfectly**, thank you so much for that. 🎉

**Comment by gsherwood** [comment]
Good news. Thanks for getting back to me.
