### ISSUE TITLE
3.x: Fatal error "illegal character in input string"

### ISSUE THREAD

**Issue by jrfnl** [squizlabs/PHP_CodeSniffer#1499]
When running `phpcs -p -s ./test.php --standard=PSR2 --report-code`, I receive a fatal error about an illegal character (stack trace below).

Test.php = Minimal code sample to test with:
```php
<?php
// XMLDiff — XML diff and merge.

```

Stack trace:
```
PHP Fatal error:  Uncaught exception 'PHP_CodeSniffer\Exceptions\RuntimeException' with message 'iconv_strlen(): Detected an illegal character in input string in path\to\PHP_CodeSniffer\src\Tokenizers\Tokenizer.php on line 194' in path\to\PHP_CodeSniffer\src\Runner.php:543
Stack trace:
#0 [internal function]: PHP_CodeSniffer\Runner->handleErrors(8, 'iconv_strlen():...', '...', 194, Array)
#1 path\to\PHP_CodeSniffer\src\Tokenizers\Tokenizer.php(194): iconv_strlen('// XMLDiff \x97 XM...', 'utf-8')
#2 path\to\PHP_CodeSniffer\src\Tokenizers\Tokenizer.php(75): PHP_CodeSniffer\Tokenizers\Tokenizer->createPositionMap()
#3 path\to\PHP_CodeSniffer\src\Files\File.php(498): PHP_CodeSniffer\Tokenizers\Tokenizer->__construct('<?php\r\n/**\r\n * ...', Object(PHP_CodeSniffer\Config), '\r\n')
#4 path\to\PHP_CodeSniffer\src\Reports\Code.php(53): PHP_CodeSniffer\Files\File->parse()
#5 path\to\PHP_CodeSniffer\src\Reporter.php(258): PHP_CodeSniffer\Reports\Code->generateFileReport(Array, Object(PHP_CodeSniffer\Files\LocalFile), true, 100)
#6 path\to\PHP_CodeSniffer\src\Runner.php(592): PHP_CodeSniffer\Reporter->cacheFileReport(Object(PHP_CodeSniffer\Files\LocalFile), Object(PHP_CodeSniffer\Config))
#7 path\to\PHP_CodeSniffer\src\Runner.php(383): PHP_CodeSniffer\Runner->processFile(Object(PHP_CodeSniffer\Files\LocalFile))
#8 path\to\PHP_CodeSniffer\src\Runner.php(112): PHP_CodeSniffer\Runner->run()
#9 path\to\PHP_CodeSniffer\bin\phpcs(18): PHP_CodeSniffer\Runner->runPHPCS()
#10 {main}
  thrown in path\to\PHP_CodeSniffer\src\Runner.php on line 543
```

This seems to only happen with the `code` report, using a different report type, the report is generated and shows the error in the report, like so:
```
----------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------
 1 | ERROR | An error occurred during processing; checking has been aborted. The error message was:
   |       | iconv_strlen(): Detected an illegal character in input string in
   |       | path\to\PHP_CodeSniffer\src\Tokenizers\Tokenizer.php on line 193
   |       | (Internal.Exception)
----------------------------------------------------------------------------------------------------
```

In PHPCS 2.x the file used to process without issue. Could this be related to the change in the default encoding used with PHPCS 3.x ?
The original file is encoded as ANSI (Windows).

If I run the same command on a directory containing the problem file, `phpcs -p -s . --standard=PSR2 --report-code`, a different fatal error is thrown, but I suspect that this is related.

```
PHP Fatal error:  Uncaught exception 'PHP_CodeSniffer\Exceptions\RuntimeException' with message 'Undefined variable: stackPtr in path\to\PHP_CodeSniffer\src\Reports\Code.php on line 91' in path\to\PHP_CodeSniffer\src\Runner.php:543
Stack trace:
#0 path\to\PHP_CodeSniffer\src\Reports\Code.php(91): PHP_CodeSniffer\Runner->handleErrors(8, 'Undefined varia...', '...', 91, Array)
#1 path\to\PHP_CodeSniffer\src\Reporter.php(258): PHP_CodeSniffer\Reports\Code->generateFileReport(Array, Object(PHP_CodeSniffer\Files\LocalFile), true, 100)
#2 path\to\PHP_CodeSniffer\src\Runner.php(592): PHP_CodeSniffer\Reporter->cacheFileReport(Object(PHP_CodeSniffer\Files\LocalFile), Object(PHP_CodeSniffer\Config))
#3 path\to\PHP_CodeSniffer\src\Runner.php(383): PHP_CodeSniffer\Runner->processFile(Object(PHP_CodeSniffer\Files\LocalFile))
#4 path\to\PHP_CodeSniffer\src\Runner.php(112): PHP_CodeSniffer\Runner->run()
#5 path\to\PHP_CodeSniffer\bin\phpcs(18): PHP_CodeSniffer\Runner->runPHPCS()
#6 {main}
  thrown in path\to\PHP_CodeSniffer\src\Runner.php on line 543
```

**Comment by gsherwood** [comment]
Yes, this may be caused by the default encoding changing to UTF-8. If this case, you'll need to specify the encoding with `--encoding=windows-1252`.

**Comment by jrfnl** [comment]
@gsherwood In practice I will change the code in that file to prevent the issue from occurring, but that wasn't the reason to open the issue.

The issue which - I believe - should be fixed in PHPCS, is that in other reports the internal error is displayed as part of the report, while when using the `code` report, the internal error breaks the PHPCS run with a fatal error.

**Comment by gsherwood** [comment]
Sorry misunderstood the report.

The code report does a second parse of the file to get the tokens array back after it was cleaned up during processing, so it can encounter those exceptions a second time. It now ignores them (they've already been reported) and is able to print error messages without being able to generate a code diff for them.

So you now get this:
```
FILE: temp.php
-----------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-----------------------------------------------------------------------------------------------------------------------------------------------
LINE 1: ERROR An error occurred during processing; checking has been aborted. The error message was: iconv_strlen(): Detected an illegal
              character in input string in /Users/gsherwood/Sites/Projects/PHP_CodeSniffer/src/Tokenizers/Tokenizer.php on line 193
-----------------------------------------------------------------------------------------------------------------------------------------------

-----------------------------------------------------------------------------------------------------------------------------------------------
Time: 121ms; Memory: 24Mb
```

**Comment by jrfnl** [comment]
@gsherwood Excellent! Thanks for that fix. Looks good to me.

**Comment by icanhazstring** [comment]
I do stumble accross the same issue related to my lastname :(

phpcs will abort processing there is an äöü or something in a comment which is pretty annoying.
Only way to solve this is to change my lastname, which is not a good idea in terms of copyright an stuff.

**Comment by jrfnl** [comment]
@icanhazstring Well, you can pass a different `--encoding` to PHPCS or change the file encoding to UTF-8 ?

**Comment by icanhazstring** [comment]
I just changed every file to utf-8 again now it works on command line.

However there is probably a bug in the Intellij/PHPStorm Code Sniffer plugin.
This will raise this bug. Don't know how to fix this now. But this has nothing to do with your code tho :)

Thanks 👍

**Comment by downhiller** [comment]
I've just had a similar error due to degree symbol (°) in a UTF-8 file, using the latest version of phpcs and with --encoding specifically set to UTF-8.  I deleted the degree symbol and it then worked fine.
