### ISSUE TITLE
Alternative control structure syntax not always recognized as scoped

### ISSUE THREAD

**Issue by jrfnl** [squizlabs/PHP_CodeSniffer#1503]
Going out of PHP breaks recognition of scope for alternative control structure syntax.

In the below code sample, the `continue` in the first example has the `T_FOR` token as a condition in the tokens array, while the `continue` in the second example does not.

```php
for ($x=0;$x<5;$x++):
  if ($x) continue;
endfor;

for ($x=0;$x<5;$x++):
  if ($x) continue ?> <?php
endfor;
```

This bug exists in both the PHPCS 2.x as well as the PHPCS 3.x branches.

**Comment by gsherwood** [comment]
Fixed in master, but I'd only want to back-port a tokenizer change if it's been there for a while.

Thanks for the report.

**Comment by jrfnl** [comment]
@gsherwood Appreciated! A backport at some point ("after a while") would be appreciated!
