### ISSUE TITLE
PSR2.Namespaces.UseDeclaration hangs fixing use statement with no trailing code

### ISSUE THREAD

**Issue by u01jmg3** [squizlabs/PHP_CodeSniffer#1504]
Using this code:

```php
<?php use App\Models\Assessment\Exam ?>
```

with this rule `PSR2.Namespaces.UseDeclaration.MultipleDeclarations`

PHPCBF will hang and show no errors. Eventually you have to terminate the command.

If you change the code to have a semi-colon PHPCBF does not hang.

```php
<?php use App\Models\Assessment\Exam; ?>
```

**Comment by gsherwood** [comment]
Thanks for the report. PHPCBF now fixes that sample code like this:
```diff
--- temp.php
+++ PHP_CodeSniffer
@@ -1 +1 @@
-<?php use App\Models\Assessment\Exam ?>
+<?php use App\Models\Assessment\Exam;
```
There was a second problem if you had a semicolon but not end tag, right at the end of the file. Also fixed.
