### ISSUE TITLE
[Q] psr2 try catch block intendation

### ISSUE THREAD

**Issue by silverqx** [squizlabs/PHP_CodeSniffer#1505]
Really :eyes:? I'm serious :)

```
        try {
            unlink($filename);
        } catch (\ErrorException $e) {
        }
```

```
  74 | ERROR | [x] Line indented incorrectly; expected 0 spaces, found 8
  76 | ERROR | [x] Line indented incorrectly; expected 0 spaces, found 8
  77 | ERROR | [x] Line indented incorrectly; expected 0 spaces, found 8
```

**Comment by gsherwood** [comment]
These errors don't actually show anything unless I can see the code in context.

If you have a try/catch block indented 8 spaces and it is not contained within any other code blocks (classes, functions etc) then yes, these errors are valid.

If this try/catch on line 74 is contained within other constructs, then the errors may be incorrect. But I'd need to see the rest of the file, or a small sample file that replicates the issue, to be able to debug and fix it. Is that possible?

**Comment by szachara** [comment]
I'm sending whole file, try / catch block is inside the class method.

[ExportService.zip](https://github.com/squizlabs/PHP_CodeSniffer/files/1076857/ExportService.zip)

**Comment by szachara** [comment]
And this is how I call phpcs:
```
phpcs --standard="PSR2" --ignore="./app/Http/Routes/*" --encoding=UTF-8 ./app
```

**Comment by szachara** [comment]
Updated file, in previous was try / catch unintended ( 0 spaces ), in this file is intendatation 8 spaces, I tried `phpcs --standard="PSR2" .` only on this one file and I get `Line indented incorrectly`.

[ExportService.zip](https://github.com/squizlabs/PHP_CodeSniffer/files/1082408/ExportService.zip)

**Comment by gsherwood** [comment]
@silverqx I'm really sorry. I obviously missed the comment you added 6 months ago and have finally seen this.

I've tested the file you included in the ZIP and I still can't replicate any error when running PHPCS over it with the PSR2 standard. I've tried a few different PHPCS versions as well.

Do you still have this problem? If so, what version of PHPCS are you running and is it still failing on the file you included in the ZIP?
