### ISSUE TITLE
Missing `.fixed` test case file for the `Squiz.WhiteSpace.ControlStructureSpacing` sniff

### ISSUE THREAD

**Issue by jrfnl** [squizlabs/PHP_CodeSniffer#1519]
Leaving the autofixes made by that sniff without unit tests.

**Comment by gsherwood** [comment]
> Leaving the autofixes made by that sniff without unit tests.

The unit tester still fixes the main file and then confirms that there are no fixable errors remaining. That's a basic level of checking to ensure the fixing isn't conflicting with itself, or marking errors as fixable but not actually fixing them.

But now the sniff also has .fixed files to confirm the fixes themselves are accurate.

**Comment by jrfnl** [comment]
Thanks!
