### ISSUE TITLE
Debugging fixer: unit tests vs manual run give different results

### ISSUE THREAD

**Issue by jrfnl** [squizlabs/PHP_CodeSniffer#1520]
I'm testing an update of one of the WordPress sniffs which includes fixers and having trouble debugging it.

I'm using the PHPCS 2.9/2.x-dev branch as WPCS is not yet compatible with PHPCS 3.x.

The WIP branch can be found here: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/tree/feature/issue-973-multi-line-array-value-indentation

I've manually created a `.fixed` file to make sure it's in line with what's intended.

Next I run the fixer against the test file:
`phpcbf -p ./WordPress/Tests/Arrays/ArrayIndentationUnitTest.inc --standard=WordPress-Core --suffix=.myfixed --sniffs=WordPress.Arrays.ArrayIndentation`

When I compare the `.myfixed` output file with the `.fixed` file, the files are identical.

However when I run the unit tests, the tests fail.
`phpunit --filter WordPress /path/to/PHP_CodeSniffer/tests/AllTests.php`

When running the unit tests, the `cs` part is reporting errors I cannot reproduce when I manually run:
`phpcs -p -s ./Arrays/ArrayIndentationUnitTest.inc --standard=WordPress-Core --sniffs=WordPress.Arrays.ArrayIndentation`

And the `cbf` part is reporting differences in the `fixed` file, which again, I cannot reproduce when running `phpcbf` manually.

Bright ideas to help me debug this would be very welcome as I've run out of ideas.

**Comment by jrfnl** [comment]
Further debugging of this has revealed that the root cause of the issue is to do with tabs in `T_WHITESPACE` being replaced with spaces when doing the normal command line run, while they are *not* being replaced with spaces when running the unit tests, which results in the `column` values being wrong when the sniff is being tested via PHPUnit.

Test setup:
PHP 5.6.23 (though also tested with several other PHP versions) 
PHPCS 2.9.1
PHPUnit 4.8.19
And in case it matters: Windows 7

**Comment by gsherwood** [comment]
> urther debugging of this has revealed that the root cause of the issue is to do with tabs in T_WHITESPACE being replaced with spaces when doing the normal command line run, while they are not being replaced with spaces when running the unit tests

If that's the case, you'll need to ensure that your sniffs that rely on tabs being replaced are setting that command line argument. The ScopeIndent sniff is an example of this, although it only wants tabs replaced in the file that is checking tab indentation: https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/Generic/Tests/WhiteSpace/ScopeIndentUnitTest.php#L26

**Comment by jrfnl** [comment]
The ruleset which contains the sniff were I'm running into trouble with contains the `<arg name="tab-width" value="4"/>` directive, doesn't that cover it ? or do I need to add this at the top of the unit test file as well (or something along those lines) ?

**Comment by jrfnl** [comment]
@gsherwood Thanks for your help with this. That fixes it. I clearly don't write enough whitespace related sniffs ;-)

**Comment by gsherwood** [comment]
> That fixes it.

Good news. Thanks.
