### ISSUE TITLE
PHP 7 array return type token

### ISSUE THREAD

**Issue by webimpress** [squizlabs/PHP_CodeSniffer#1528]
```php
function a() : array {
}
```

Return type `array` is tokenized as `T_RETURN_TYPE`, but token contains also keys:
  - `parenthesis_opener`
  - `parenthesis_closer`
  - `parenthesis_owner`

I think these keys shouldn't be there.

**Comment by gsherwood** [comment]
No, they shouldn't be there. Thanks for reporting this.

**Comment by gsherwood** [comment]
The keys themselves don't change the behaviour of the system, but they didn't need to be there and could be confusing if you looked at them - especially given they were mostly empty. They are being cleaned up now.
