### ISSUE TITLE
PHP_CodeSniffer\Standards\Squiz\Sniffs\Strings\DoubleQuotesUsageSniffs makes invalid changes

### ISSUE THREAD

**Issue by bpicolo** [squizlabs/PHP_CodeSniffer#1534]
It makes the following replacement: "\\$foo" => '\\$foo'

Unfortunately, these are not equivalent. It probably shouldn't replace any string using escaping, or it should unescape if they are

**Comment by jrfnl** [comment]
AFAIK this was already fixed in #1496 and included in the 3.0.1 release. Or are you still seeing this when using PHPCS 3.0.1 ?

**Comment by bpicolo** [comment]
@jrfnl aha, looks like that's recent. We'll upgrade to 3.0.1. Thanks!
