### ISSUE TITLE
Prevent Error Message If Ignore File doesn't Exist?

### ISSUE THREAD

**Issue by mikebronner** [squizlabs/PHP_CodeSniffer#1538]
Is there a way to keep PHPCS from throwing an error and aborting if an ignore folder or file doesn't exist? I am running a generic command with a set of folders I want to ignore in all my projects, but those folders may not exist.

Thanks :)

**Comment by gsherwood** [comment]
All the ignore settings in PHPCS are regular expressions and are not evaluated to be exact file paths. What ignore setting are you using that is throwing an error?

**Comment by mikebronner** [comment]
I was doing the following:

```
/vendor/bin/phpcs --standard=PSR1,PSR2 --report-width=9999 --report=json --ignore=/tests /public /vendor /
ERROR: The file "/public" does not exist.

Run "phpcs --help" for usage information
```

**Comment by gsherwood** [comment]
The CLI args `--ignore=/tests /public /vendor /` tell PHPCS to ignore `/tests` and check `/public`, `/vendor` and `/`.

Maybe you want: `--ignore=/tests,/public,/vendor,/`

Or are you asking for PHPCS to not throw errors when you ask it to check files and folders that don't exist?

**Comment by mikebronner** [comment]
Let me retry and get back to you. :)

**Comment by mikebronner** [comment]
@gsherwood Perfect, thanks ... I used to have it comma-separated, but got confused somewhere reading the documentation and removed the commas. Thanks for setting me straight!
