### ISSUE TITLE
Generic.WhiteSpace.ScopeIndent fixer has issues with multi-line comments and inline HTML

### ISSUE THREAD

**Issue by jrfnl** [squizlabs/PHP_CodeSniffer#1539]
As part of the WordPress Core drive to fix the codestyle in the codebase, I've been reviewing fixes made by the auto-fixers and came across some weird indentation inconsistencies in the fixes made by the `Generic.WhiteSpace.ScopeIndent` sniff.

The issues exist in both PHPCS 2.x as well as 3.x, though with slightly different characteristics.

~~If at all possible, if would be very much appreciated if any fixes for this could be backported to the PHPCS 2.x branch.~~ _This is no longer needed for the WP Core project as WPCS is compatible with PHPCS 3.x by now._

### Command used:
`phpcbf -p -s ./test.php --standard=Generic --sniffs=Generic.WhiteSpace.ScopeIndent`

### Test code:
```php
switch ( $a ) {
case 'a':
	$b = 2;
	/**
	 * A comment.
	 */
	apply_filter( 'something', $b );
	break;

case 'aa':
	$b = 2;
	/*
	 * A comment.
	 */
	apply_filter( 'something', $b );
	break;

case 'b':
	$b = 3;
?>
	<input name="something" value=<?php echo $b; ?>
<?php
	$b = 4;
	break;

default:
	$b = 3;
	?>
	<input name="something" value=<?php echo $b; ?>
	<?php
	$b = 4;
	break;
}
```

### Result with PHPCS 2.x:

Notable issues:
* Indentation of inside-case lines is **9** spaces, not the expected 8.
* Docblock lines after the opener.
* PHP (re-)open tag alignment when scope had to be increased (4 not 8 spaces) and lines following it (5 not 4) in case `b`.
* PHP close (13 not 8), inline HTML (9 not 8), PHP (re-)open tag (13, not 8) and the lines following it (13, not 8) in the `default` case.

```php
switch ( $a ) {
    case 'a':
         $b = 2;
         /**
	 * A comment.
	 */
         apply_filter( 'something', $b );
	break;

    case 'aa':
         $b = 2;
         /*
          * A comment.
          */
         apply_filter( 'something', $b );
	break;

    case 'b':
         $b = 3;
        ?>
         <input name="something" value=<?php echo $b; ?>
    <?php
     $b = 4;
	break;

    default:
         $b = 3;
            ?>
         <input name="something" value=<?php echo $b; ?>
            <?php
            $b = 4;
	break;
}
```

### Result with PHPCS 3.x:

Notable issues:
* Docblock lines after the opener.
* Multi-line non-docblock comment, lines after opener
* PHP close, inline HTML, PHP (re-)open tag and the lines following it in case `b`.
* Inline HTML alignment in the `default` case.

```php
switch ( $a ) {
    case 'a':
        $b = 2;
        /**
	 * A comment.
	 */
        apply_filter( 'something', $b );
	break;

    case 'aa':
        $b = 2;
        /*
        * A comment.
        */
        apply_filter( 'something', $b );
	break;

    case 'b':
        $b = 3;
    ?>
     <input name="something" value=<?php echo $b; ?>
<?php
	$b = 4;
	break;

    default:
        $b = 3;
        ?>
     <input name="something" value=<?php echo $b; ?>
        <?php
        $b = 4;
	break;
}
```

**Comment by gsherwood** [comment]
I've been looking at this and it's not as easy as I thought. Even with just the commenting changes, the sniff is designed to skip comments so that is doesn't need to worry about precision alignment and all sorts of weird indentations someone might have done. It positions the comment opener and then lets other sniffs decide how the comment itself should be indented.

The changes would be too risky to include in a micro release, so I'm removing this one from 3.1.1.

**Comment by gsherwood** [comment]
I've committed some changes to try and make multi-line comment fixing better. Your sample code block is now being fixed like this:
```php
<?php
switch ( $a ) {
    case 'a':
        $b = 2;
        /**
         * A comment.
         */
        apply_filter( 'something', $b );
    break;

    case 'aa':
        $b = 2;
        /*
         * A comment.
         */
        apply_filter( 'something', $b );
    break;

    case 'b':
        $b = 3;
    ?>
    <input name="something" value=<?php echo $b; ?>
<?php
    $b = 4;
    break;

    default:
        $b = 3;
        ?>
    <input name="something" value=<?php echo $b; ?>
    <?php
    $b = 4;
    break;
}
```
I think that's getting better, but I haven't looked into PHP open tags yet.

**Comment by gsherwood** [comment]
I might be able to change the indentation of the PHP open/close tags to make a few more lines look properly indented, but I'm worried about touching any of the HTML tags. Adding extra spaces or tabs there will affect frontend output, and the auto-fixer really shouldn't be doing that.

**Comment by gsherwood** [comment]
I've adjusted the code for how open and close tags set indents, and how their indents are checked. I know this change will result in new error messages for some code, but none of the existing unit tests required any changes, so they should hopefully be limited.

Your sample code block is now being fixed like this:
```php
<?php
switch ( $a ) {
    case 'a':
        $b = 2;
        /**
         * A comment.
         */
        apply_filter( 'something', $b );
    break;

    case 'aa':
        $b = 2;
        /*
         * A comment.
         */
        apply_filter( 'something', $b );
    break;

    case 'b':
        $b = 3;
        ?>
    <input name="something" value=<?php echo $b; ?>
        <?php
        $b = 4;
    break;

    default:
        $b = 3;
        ?>
    <input name="something" value=<?php echo $b; ?>
        <?php
        $b = 4;
    break;
}
```
The sniff doesn't adjust the indent of HTML, so I've left both those tags indented to the level that was set by the developer. I think that's fine, because I'm not keen on moving tags around and indentation problems that would cause.

I'll leave this open in case you have some time to do some testing as well, but I think this is done now.

**Comment by gsherwood** [comment]
Closing as I haven't had any additional issues reported.

**Comment by jrfnl** [comment]
@gsherwood Sorry for having been silent. Your responses to this issue caught me while traveling. Thank you very much for making the fixes to the ScopeIndent sniff. It definitely feels like things are fixed better now.
