### ISSUE TITLE
Switch statement metrics

### ISSUE THREAD

**Issue by jrfnl** [squizlabs/PHP_CodeSniffer#1541]
While analysing something for the WordPress Core CS project, I needed metrics on various bits of switch statements and realized that the most applicable sniff `PSR2.ControlStructures.SwitchDeclaration` does not record any metrics.

For my purposes, I've added these now locally, but I was wondering if there is any interest in (partially) adding these anyhow so they will be accessible for all analysed projects through https://squizlabs.github.io/PHP_CodeSniffer/analysis/

If so, I'd be happy to send in a PR based on the code I've already created.

**Comment by gsherwood** [comment]
Yes, I'd accept new metrics for a sniff. I have to manually add them to the analysis repo and regen all past metrics, so new metrics wont break what I have there.

**Comment by jrfnl** [comment]
@gsherwood Thanks for your response. I'll tidy up & create a PR for this. I'm going to presume it will only go into the 3.x branch ? (which in this case would be fine as far as WPCS is concerned).

**Comment by gsherwood** [comment]
> I'm going to presume it will only go into the 3.x branch

Yep
