### ISSUE TITLE
Disable css and js check in a custom ruleset

### ISSUE THREAD

**Issue by dingo-d** [squizlabs/PHP_CodeSniffer#1544]
I couldn't find what rule should I add to my `ruleset.xml` if I want to disable js and css checking in code sniffer?

**Comment by jrfnl** [comment]
@dingo-d Try using `--extensions=php` or if you use a custom ruleset: `<arg name="extensions" value="php"/>` ;-)

**Comment by dingo-d** [comment]
Thanks will do that :)
