### ISSUE TITLE
Wrong token type for backslash in use function

### ISSUE THREAD

**Issue by webimpress** [squizlabs/PHP_CodeSniffer#1547]
In case:
```php
use function \array_keys
```
backslash is tokenized as `T_STRING`.

In case:
```php
use function \MyNamespace\myFunction;
```
first backslash is tokenzed as `T_STRING` and the second one as `T_NS_SEPARATOR`.

---

If we import class:
   ```php
   use \DateTime;
   ```

or global constant:
   ```php
   use const \PHP_VERSION_ID;
   ```

or constant from other namespace:
   ```php
   use const \MyNamespace\MY_CONST;
   ```

all backslashes are tokenized as `T_NS_SEPARATOR`.

--- 

I would expect then the same behaviour for importing functions, so all backlashes should be there always tokenized as `T_NS_SEPARATOR`.

**Comment by gsherwood** [comment]
Fixed via PR #1548
