### ISSUE TITLE
Multiline string not indented

### ISSUE THREAD

**Issue by rezashamdani** [squizlabs/PHP_CodeSniffer#1557]
Hi,

I have problem with some string which span more than 1 line.

> $tes = "SELECT * FROM
THETABLE WHERE A=1 
AND B=2";

the string consist usually the long sql syntax which already been formatted, when i run the phpcbf, the output always stay the same.

can the output something like this

> $tes = "SELECT * FROM THETABLE WHERE A=1 AND B=2";

or even better

> $tes = "SELECT * FROM 
________THETABLE WHERE A=1 
________AND B=2";

above syntax, i can't put a space in it, so i put `_`. the point is the second sentence start after the `=` char.

i'm using phpcbf version;
> phpcbf --version
PHP_CodeSniffer version 3.0.1 (stable) by Squiz (http://www.squiz.net)

**Comment by gsherwood** [comment]
PHPCBF can't reformat a string for you by adding spaces. That would actually be changing the content of the string itself, and PHPCBF has no way of knowing if that matters.

In your very specific case, the extra whitespace doesn't matter. But if these string are content being printed to a text or CSV file (for example) then that extra whitespace is going to break the output.

The other thing is that PHPCBF only fixes errors reported by PHPCS. PHPCS doesn't come with any sniffs that would produce an error message for a multi-line strings, so there would also be no errors to fix by PHPCBF.

If you want your multi-line strings to be indented or converted to a single line, you'd need to first write a sniff to detect this and produce an error. Then you will need to write the auto-fixer into that sniff so it can reformat the string the way you want.

Does that explain why PHPCBF does not change multi-line strings?

**Comment by rezashamdani** [comment]
noted that, will find another way to fixed this then.

thanks @gsherwood
