### ISSUE TITLE
phpcs.xml should take precedence over 'default_standard' setting

### ISSUE THREAD

**Issue by Fischer-Bjoern** [squizlabs/PHP_CodeSniffer#1561]
I have defined my own coding standard and want to configure it as a default to automatically run for multiple projects via 'default_standard'.
Some of those projects need some additional tweaking though, because of some external dependencies.  To solve this I defined the needed changes in 'phpcs.xml' files.

Now when I try to set the 'default_standard' setting all of my settings in  'phpcs.xml' get ignored.
When I don't set the 'default_standard' setting on the other hand, the 'phpcs.xml' will work fine, but at the same time I will default to the 'PEAR' standard for other projects unless I always explicitly enter my own standard to run.

Could this behaviour be changed to first check for a 'phpcs.xml' file and only after for a 'default_standard' config value?

The change is basically just removing one line. [phpcsxml_precedence.txt](https://github.com/squizlabs/PHP_CodeSniffer/files/1149141/phpcsxml_precedence.txt)

**Comment by gsherwood** [comment]
The diff included in the linked file is:
```diff
--- Config.php	2017-07-14 18:53:50.711178942 +0200
+++ Config.php	2017-07-14 18:54:05.027233016 +0200
@@ -328,9 +328,7 @@
         $this->restoreDefaults();
         $this->setCommandLineValues($cliArgs);
 
-        if (isset($this->overriddenDefaults['standards']) === false
-            && Config::getConfigData('default_standard') === null
-        ) {
+        if (isset($this->overriddenDefaults['standards']) === false) {
             // They did not supply a standard to use.
             // Look for a default ruleset in the current directory or higher.
             $currentDir = getcwd();

**Comment by gsherwood** [comment]
I agree that this is the way it should work. Thanks for the report and the patch.

I like to mention contributors in the patch notes, so I'd like to add you in there if you can give me your name, especially given the commit has my name on it. Or happy for it to remain private - it's up to you.

Thanks again.

**Comment by Fischer-Bjoern** [comment]
Thank you very much. :)

Sure, my name is Björn Fischer.

**Comment by gsherwood** [comment]
Thanks again.
