### ISSUE TITLE
[Bug] Fatal error: Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: Undefined index: scope_opener

### ISSUE THREAD

**Issue by Aliance** [squizlabs/PHP_CodeSniffer#1565]
```
$ docker run --rm -v $(pwd)/src/:/scripts/ texthtml/phpcs phpcbf --standard=PSR2 --error-severity=1 --warning-severity=8 /scripts/

Fatal error: Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: Undefined index: scope_opener in /usr/local/lib/php/PHP/CodeSniffer/src/Standards/PSR2/Sniffs/ControlStructures/SwitchDeclarationSniff.php on line 103 in /usr/local/lib/php/PHP/CodeSniffer/src/Runner.php:504
Stack trace:
#0 /usr/local/lib/php/PHP/CodeSniffer/src/Standards/PSR2/Sniffs/ControlStructures/SwitchDeclarationSniff.php(103): PHP_CodeSniffer\Runner->handleErrors(8, 'Undefined index...', '/usr/local/lib/...', 103, Array)
#1 /usr/local/lib/php/PHP/CodeSniffer/src/Files/File.php(429): PHP_CodeSniffer\Standards\PSR2\Sniffs\ControlStructures\SwitchDeclarationSniff->process(Object(PHP_CodeSniffer\Files\LocalFile), 16835)
#2 /usr/local/lib/php/PHP/CodeSniffer/src/Files/LocalFile.php(92): PHP_CodeSniffer\Files\File->process()
#3 /usr/local/lib/php/PHP/CodeSniffer/src/Fixer.php(179): PHP_CodeSniffer\Files\LocalFile->process()
#4 /usr/local/lib/php/PHP/CodeSniffer/src/Reports/Cbf.php(47): PHP_CodeSniffer\Fixer->fixFile()
#5 /usr/local/lib/php/PHP/CodeSniffer in /usr/local/lib/php/PHP/CodeSniffer/src/Runner.php on line 504
```
```
$ docker run --rm -v $(pwd)/src/:/scripts/ texthtml/phpcs phpcbf --version
PHP_CodeSniffer version 3.0.0RC1 (beta) by Squiz (http://www.squiz.net)
```

https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/PSR2/Sniffs/ControlStructures/SwitchDeclarationSniff.php#L103

As I understand, some of my file brokes the code sniffer? How can I understand which one?

**Comment by jrfnl** [comment]
Could you upgrade PHPCS first to the current version - 3.0.2 - and test again ? This may well have been fixed in the mean time.

**Comment by Aliance** [comment]
Can't do this, because I'm using a docker: https://hub.docker.com/r/texthtml/phpcs/
So, this has already been fixed?

**Comment by jrfnl** [comment]
@Aliance I don't know whether it has been fixed or not as there is no code sample with which I could test, but a lot has changed since v3.0.0RC1, so it may well be.

**Comment by jrfnl** [comment]
@Aliance Based on the link you gave, there is a more recent docker image available which at least has PHPCS 3.0.0 (image name: `latest`). Still not the current version `3.0.2`, but worth trying maybe ?

**Comment by gsherwood** [comment]
> As I understand, some of my file brokes the code sniffer? How can I understand which one?

Run PHPCS with the `-v` command line argument and it will show you each file that it is processing. Your errors will appear right after it begins processing one of the files. If you run PHPCS directly on it, that should produce the error again for you.

But also, yes, upgrading would be useful if possible. Maybe just download the 3.0.2 phar file and run that to test:
```
curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
phpcs --standard=PSR2 --error-severity=1 --warning-severity=8 /scripts/ -v
```

**Comment by Aliance** [comment]
Thanks @jrfnl, what's why noone should use `latest` docker image tag, because it caches locally :) I had removed it and downloaded again, so not its version is: 
```
$ docker run --rm -v $(pwd)/src/:/scripts/ texthtml/phpcs phpcbf --version
PHP_CodeSniffer version 3.0.0 (stable) by Squiz (http://www.squiz.net)
```

And no bug hapenned now.
