### ISSUE TITLE
Consider adding leading dot to config files for visibility

### ISSUE THREAD

**Issue by skyrpex** [squizlabs/PHP_CodeSniffer#1566]
Pretty much what the title says. It's pretty common to use hidden files (aka leading dot filenames) for configuration files (see eslint and editorconfig).

_**Edit**: I mean `phpcs.xml` and its siblings._

* The config file will be hidden in UNIX systems.
* The config file will be naturally grouped with other config files whose name starts with dots (.editorconfig, .env, .gitattributes, .gitignore, etc...).

I'm wondering if you're open to MR for this change. I can contribute.

**Comment by gsherwood** [comment]
Which config file are you you talking about here?

There is the CodeSniffer.conf file that is used to store vars set using `--config-set` and there is the `phpcs.xml` file used to define a default coding standard for a project.

The .conf file is normally hidden away and user-specific while the phpcs.xml file is normally committed to a repo and used by multiple developers.

The .conf file probably doesn't need a name change given it is hidden, and the phpcs.xml file follows the same standard as other QA tools like PHPUnit. So I'm not sure why a name change of these files would make sense. Are there other config files I'm forgetting?

**Comment by skyrpex** [comment]
Sorry, I meant `phpcs.xml` and its variants.

> the phpcs.xml file follows the same standard as other QA tools like PHPUnit.

That's true. I'll ask the same thing to PHPUnit depending on how this discussion goes :+1:

> So I'm not sure why a name change of these files would make sense. Are there other config files I'm forgetting?

Basically, to follow the unspoken standard of files that don't "logically belong" to a project source code to start with a dot. Examples are `.eslintrc`, `.editorconfig`, `.npmignore`, even the git files (`.gitattributes`, ...). These files just tell how a project behaves, but are not source code.

**Comment by gsherwood** [comment]
I can allow the phpcs.xml file to be prefixed with a dot, but I can't ban the current format. This would extend to list of files PHPCS looks for to:
- phpcs.xml
- phpcs.xml.dist
- .phpcs.xml
- .phpcs.xml.dist

Is that what you're after?

**Comment by skyrpex** [comment]
Yes, it was my purpose. My guess is that people will slowly use the ones with initial dots, and eventually the other ones will be almost unused.

**Comment by gsherwood** [comment]
That's a pretty small change, so I've committed support for the dot prefix and people can make up their own mind as to how they want the files to be named. Thanks for the suggestion.

**Comment by jrfnl** [comment]
I was just having a play around with that and am wondering whether the order in which the files are searched for is intuïtive enough.

@gsherwood As the non-`dist` file(s) are supposed to overrule the `dist` file(s), I would consider the belo order more logical. I'd be happy to send in a PR to change this if you'd be open to the change.
1. `.phpcs.xml`
2. `phpcs.xml`
3. `.phpcs.xml.dist`
4. `phpcs.xml.dist`

**Comment by gsherwood** [comment]
> I'd be happy to send in a PR to change this if you'd be open to the change.

Seems like a fair enough change. I'd be happy to merge a PR for it.

**Comment by jrfnl** [comment]
@gsherwood Thanks for your response. PR #1693 should take care of it ;-)

**Comment by jrfnl** [comment]
@skyrpex Just wondering - did you ever open the issue for PHPUnit ? And if so, link please ? (I searched but couldn't find it)

**Comment by skyrpex** [comment]
I'm sorry, I totally forgot it. There it is 😆

**Comment by jrfnl** [comment]
@skyrpex Excellent! Thanks ;-)
