### ISSUE TITLE
Squiz.Arrays.ArrayDeclaration fixer removes comments between array keyword and open parentheses

### ISSUE THREAD

**Issue by jrfnl** [squizlabs/PHP_CodeSniffer#1570]
The auto-fixer for `Squiz.Arrays.ArrayDeclaration.SpaceAfterKeyword` could potentially remove comments which are between the `array` keyword and the open parenthesis as it removes tokens without checking that these are `T_WHITESPACE`.

While this is, of course, ugly code, I still don't think the fixer should be allowed to be triggered if there is anything, but whitespace, between the `array` keyword and the open parenthesis. It should just report the issue.
#### Test cases:

```php
$a = array
// comment
( 'a', 'b' );

$a = array /* comment */ ( 'a', 'b' );
```

**Comment by gsherwood** [comment]
Normally I'd try and find a new place to put the comment rather than just not fixing that code. I haven't put any thought into where it would go, but I'm pretty sure some other sniffs already do this.

**Comment by gsherwood** [comment]
I decided to do what you suggested and just not report these as fixable errors. I couldn't figure out where to put that comment - there probably isn't any good place. Thanks for the report.
