### ISSUE TITLE
Generic.InlineControlStructureSniff breaks with a comment between body and condition in do while loops

### ISSUE THREAD

**Issue by ht-bs** [squizlabs/PHP_CodeSniffer#1577]
A comment between the body and condition in do while loops, as illustrated below, breaks the Generic.InlineControlStructureSniff by producing the following error:

> Inline control structures are not allowed (Generic.ControlStructures.InlineControlStructure.NotAllowed)

```
do
{
}
// Comment
while (true);
```

Is this intended behavior? If not, a fix would be to replace the search for anything but a `T_WHITESPACE` token, with a search for anything but `Tokens::$emptyTokens` in line 86:
https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/Generic/Sniffs/ControlStructures/InlineControlStructureSniff.php#L86

**Comment by gsherwood** [comment]
Closed by PR #1587
