### ISSUE TITLE
Can I reindent code with phpcbf?

### ISSUE THREAD

**Issue by wowcut** [squizlabs/PHP_CodeSniffer#1588]
Is there a combination of rules that will reindent code? 
Sorry to ask here, I did not find any other comunication channel published in the Readme.md.
Than you very much for your attention!

**Comment by gsherwood** [comment]
You asked another question (https://github.com/squizlabs/PHP_CodeSniffer/issues/1589) that happens to incorporate this one as well, so I'll close this question so the discussion can remain in one place.

But the answer to this specific question is the `Generic.WhiteSpace.ScopeIndent` sniff.
