### ISSUE TITLE
How are multiple included rules handled?

### ISSUE THREAD

**Issue by davidwindell** [squizlabs/PHP_CodeSniffer#1596]
I've been trying to find an answer to this without success. I'd like to understand how using multiple included rulesets work when the same Sniff is included with different configuration in each inherited rule. For example;

```xml
<?xml version="1.0"?>
<ruleset name="Project Coding Standard Definition">
    <rule ref="EcgM2"/>
    <rule ref="MEQP2"/>
    <rule ref="OuterEdge"/>
    <rule ref="PSR2">
        <exclude name="PSR2.Classes.PropertyDeclaration.Underscore"/>
    </rule>
</ruleset>
```

Do rules from MEQP2 take priority/precedence over EcgM2 and so forth?

Also, in this example, [OuterEdge](https://github.com/outeredge/coding-standards/blob/master/OuterEdge/ruleset.xml) includes PSR2 and then makes some overrides. Am I doing the exclude for PropertyDeclaration.Underscore wrong (or should it be higher up the file).

Thanks!

**Comment by gsherwood** [comment]
Rules within rulesets are processed in the order they are encountered. Each time you include a ruleset, PHPCS will go into it and process all the rules within.

The best thing to do is to run PHPCS with the `-vv` command line argument. This will output a lot of debug information (so test a very small file) but the important bit is up the top. That part of the output will show you exactly how your ruleset was processed, and in what order the rules where executed.

**Comment by davidwindell** [comment]
Thanks @gsherwood, we'll take a look with the verbose command.
