### ISSUE TITLE
Improve documentation about testing own standard

### ISSUE THREAD

**Issue by evilebottnawi** [squizlabs/PHP_CodeSniffer#1598]
Before upgrade to `3` version, i used command for testing:
```
phpunit --filter ItgalaxyCodingStandards
```

After upgrade it is not works (`No tests executed!`) and i don't found how i can do this in new version. I spend about `5` hours for searching and nothing.
`phpunit.xml.dist`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://schema.phpunit.de/5.7/phpunit.xsd"
    bootstrap="ItgalaxyCodingStandards/Tests/bootstrap.php"
    backupGlobals="false"
    backupStaticAttributes="false"
    colors="false"
    convertErrorsToExceptions="true"
    convertNoticesToExceptions="true"
    convertWarningsToExceptions="true"
    processIsolation="false"
    stopOnError="false"
    stopOnFailure="false"
    syntaxCheck="true"
    verbose="true">
    <php>
        <ini name="error_reporting" value="-1"/>
        <ini name="intl.default_locale" value="en"/>
        <ini name="intl.error_level" value="0"/>
        <ini name="memory_limit" value="-1"/>
    </php>
    <testsuites>
        <testsuite name="ItgalaxyCodingStandards Sniffs Tests">
            <file>./vendor/squizlabs/php_codesniffer/tests/AllTests.php</file>
        </testsuite>
    </testsuites>
    <logging>
        <log type="coverage-text" target="php://stdout"/>
        <log type="coverage-html" target="build/coverage"/>
    </logging>
    <filter>
        <whitelist addUncoveredFilesFromWhitelist="true">
            <directory>./ItgalaxyCodingStandards/Sniffs/</directory>
        </whitelist>
    </filter>
</phpunit>
```

**Comment by gsherwood** [comment]
It's hard for me to comment when I don't have access to your tests. All I can really say is to ensure you've followed the upgrade guide for both your sniffs and your tests: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Version-3.0-Upgrade-Guide

And I can tell you that I've got the included unit tests working, as well as tests I've written for a custom coding standard (also works with the `--filter` command line arg).

If you can provide more information about what you've changed in your code, how PHPCS itself is working with your custom standard (assuming it is working), any error messages you get etc, then maybe I can help more.

**Comment by evilebottnawi** [comment]
@gsherwood thanks for answer, I solved the problem, but adding information about testing own sniffs to https://github.com/squizlabs/PHP_CodeSniffer/wiki/Coding-Standard-Tutorial be good.

**Comment by gsherwood** [comment]
> but adding information about testing own sniffs to https://github.com/squizlabs/PHP_CodeSniffer/wiki/Coding-Standard-Tutorial be good.

Agreed, but I know I'm not going to find time to do that any time soon. All my spare time goes into PHPCS itself.

Glad you've sorted out your specific problem though.
