### ISSUE TITLE
Break Tokenizers from PHPCS into Separate Project?

### ISSUE THREAD

**Issue by donatj** [squizlabs/PHP_CodeSniffer#1600]
I have made use of the PHPCS PHP tokenizer a handful of times for small projects where I needed to tokenize PHP. 

This is probably something for a major version, and I don't know if this is anything you would consider doing, but it would be amazing if you could break the parsers into a seperate composer require-able repo as a library?

It would be great if I could import it w/ composer using it's built in autoloader and just make use of it as it's own library.

Thanks!

**Comment by gsherwood** [comment]
I've thought about it, but just don't have the time. But the refactoring I did for 3.x was designed around making them more independent, so you can use the tokenizer without having to do a PHPCS run, which you've obviously discovered.

For anyone who hasn't tried that, here is an example of using the PHPCS JS tokenizer: https://gist.github.com/gsherwood/f17cfc90f14a9b29eeb6b2e99e6e7f66

**Comment by gsherwood** [comment]
Closing as this isn't something I'm intending to do.

**Comment by donatj** [comment]
I'm a little saddened but understand.
