### ISSUE TITLE
PHP_CodeSniffer-3.0.2 produces stack trace on every invocation

### ISSUE THREAD

**Issue by davidfavor** [squizlabs/PHP_CodeSniffer#1601]
After pear install PHP_CodeSniffer the following occurs...

All phpcs invocations generate bogus messages, seemingly related to command line argument processing.

All commands seem to work + error messages should be fixed, as this causes confusion about whether command has actually worked or not.
_______

lxd: net11-migration # phpcs --version
PHP PHP_CodeSniffer\Exceptions\DeepExitException:  PHP_CodeSniffer version 3.0.2 (stable) by Squiz (http://www.squiz.net)
 in /usr/share/php/PHP/CodeSniffer/src/Config.php on line 683
PHP Stack trace:
PHP   1. {main}() /usr/bin/phpcs:0
PHP   2. PHP_CodeSniffer\Runner->runPHPCS() /usr/bin/phpcs:18
PHP   3. PHP_CodeSniffer\Config->__construct() /usr/share/php/PHP/CodeSniffer/src/Runner.php:67
PHP   4. PHP_CodeSniffer\Config->setCommandLineValues() /usr/share/php/PHP/CodeSniffer/src/Config.php:330
PHP   5. PHP_CodeSniffer\Config->processLongArgument() /usr/share/php/PHP/CodeSniffer/src/Config.php:413
PHP_CodeSniffer version 3.0.2 (stable) by Squiz (http://www.squiz.net)

lxd: net11-migration # phpcs -i
PHP PHP_CodeSniffer\Exceptions\DeepExitException:  The installed coding standards are PEAR, PSR1, PSR2, Zend, Squiz, MySource and PHPCompatibility
 in /usr/share/php/PHP/CodeSniffer/src/Config.php on line 582
PHP Stack trace:
PHP   1. {main}() /usr/bin/phpcs:0
PHP   2. PHP_CodeSniffer\Runner->runPHPCS() /usr/bin/phpcs:18
PHP   3. PHP_CodeSniffer\Config->__construct() /usr/share/php/PHP/CodeSniffer/src/Runner.php:67
PHP   4. PHP_CodeSniffer\Config->setCommandLineValues() /usr/share/php/PHP/CodeSniffer/src/Config.php:330
PHP   5. PHP_CodeSniffer\Config->processShortArgument() /usr/share/php/PHP/CodeSniffer/src/Config.php:421
The installed coding standards are PEAR, PSR1, PSR2, Zend, Squiz, MySource and PHPCompatibility

**Comment by gsherwood** [comment]
I cannot replicate this issue with any type of PHPCS install. I also can't see how it could be happening given the code, so I don't know what is going on.

The Runner class catches the DeepExitException here: https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Runner.php#L130

Are you using a PHP extension that could be injecting a backtrace into exception messages?

**Comment by davidfavor** [comment]
Ah...

I'm using XDebug with a default **xdebug.show_exception_trace = 1** setting.

The fix...

```
phpcs -d xdebug.show_exception_trace=0 --version
```

Thanks for your assistance!

**Comment by davidfavor** [comment]
Closing as answered.

**Comment by paulobezerr** [comment]
On this method: `\PHP_CodeSniffer\Config::processLongArgument` we can see that an DeepExitException will be thown if you call phpcs with --help or --version options.

Maybe we should threat those parameters without throwing exception.

Then we will not have that anymore at any case.

In my case, if I turn on XDebug listening, everytime I receive this:

![image](https://user-images.githubusercontent.com/1123196/99464627-54e1c180-2917-11eb-881a-dfbc62338e48.png)

**Comment by nsrosenqvist** [comment]
> On this method: `\PHP_CodeSniffer\Config::processLongArgument` we can see that an DeepExitException will be thown if you call phpcs with --help or --version options.
> 
> Maybe we should threat those parameters without throwing exception.
> 
> Then we will not have that anymore at any case.
> 
> In my case, if I turn on XDebug listening, everytime I receive this:
> 
> ![image](https://user-images.githubusercontent.com/1123196/99464627-54e1c180-2917-11eb-881a-dfbc62338e48.png)

This happens to me constantly. Surely this issue must be reopened? @davidfavor

**Comment by jrfnl** [comment]
@nsrosenqvist As per the Xdebug documentation (emphasis is mine):

> When this setting is set to `1`, Xdebug will show a stack trace whenever an Exception or Error is raised - **_even if this Exception or Error is actually caught_**.

Ref: https://xdebug.org/docs/all_settings#show_exception_trace

The Exception trace you see is a consequence of your decision to turn that option in Xdebug on and not something PHPCS should need to take into account at runtime.

If you turn that Xdebug option off, you will still see an Exception stack trace, but no longer for caught (and correctly handled) Exceptions.
Also see @davidfavor's suggestion above: https://github.com/squizlabs/PHP_CodeSniffer/issues/1601#issuecomment-321990380
