### ISSUE TITLE
Squiz.WhiteSpace.OperatorSpacing false positive on unary minus after comment

### ISSUE THREAD

**Issue by umherirrender** [squizlabs/PHP_CodeSniffer#1605]
In the mediawiki/core code the Squiz.WhiteSpace.OperatorSpacing was added, but it reports (and fixed) a false positive for an unary minus, which has a comment before it, see [1]

`    | ERROR   | [x] Expected 1 space after "-"; 0 found
    |         |     (Squiz.WhiteSpace.OperatorSpacing.NoSpaceAfter)`

Maybe it is possible to allow this situation.

[1] https://gerrit.wikimedia.org/r/#/c/371474/1/includes/Sanitizer.php

**Comment by WMDE-Fisch** [comment]
again this is on version 3.0.2

**Comment by jrfnl** [comment]
@umherirrender @WMDE-Fisch I believe PR #1608 should fix this for you ;-)
