### ISSUE TITLE
Add sniff for error control (aka shut-up) operator

### ISSUE THREAD

**Issue by mbrodala** [squizlabs/PHP_CodeSniffer#1618]
I think a sniff for the [error control](https://secure.php.net/manual/en/language.operators.errorcontrol.php) (aka shut-up) operator (`@`) would be useful. A fix would be removing it.

**Comment by KacerCZ** [comment]
There is already Generic.PHP.NoSilencedErrors -
 see https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/Generic/Sniffs/PHP/NoSilencedErrorsSniff.php

**Comment by gsherwood** [comment]
Yes, this sniff already exists. It does not include an auto-fix because this would change the behaviour of the application. Auto-fixing in the included sniffs is restricted to formatting changes, although you could take this sniff and add an auto-fix to it if you like.

**Comment by mbrodala** [comment]
Thanks for the info. :-)
