### ISSUE TITLE
Installed path config option is suprising

### ISSUE THREAD

**Issue by PatrickRose** [squizlabs/PHP_CodeSniffer#1624]
I've been testing using a PHPCS 3.0 with two custom standards and PHPStorm's integration started throwing `UnexpectedValueException` because `src/Util/Standards.php` tried to open a non-existing directory.

We'd previous set the `installed_paths` config value to `vendor/wimg/php-compatibility,util/PHPCS/` which works if I run phpcs from the root of my git repository. However PHPStorm runs PHPCS from the directory that the file it's processing. An easy reproduction:

```bash
$ cd /path/to/git/repo

$ vendor/bin/phpcs --config-set installed_paths vendor/wimg/php-compatibility,util/PHPCS/

$ vendor/bin/phpcs -i
The installed coding standards are PSR1, Zend, PSR2, PEAR, MySource, Squiz, PHPCompatibility and ZedcoreStandard

$ cd subdir

$ ../vendor/bin/phpcs -i
The installed coding standards are PSR1, Zend, PSR2, PEAR, MySource and Squiz
```

If I update the `installed_paths` config to be `../../wimg/php-compatibility,../../../util/PHPCS/` then it works no matter which directory I'm in. Obviously, that's the behaviour I want - but the fact that it's not documented anywhere makes me think I'm getting lucky somehow because of how PHPCS is handling things.

Could this either be documented or made explicit somehow? Maybe if your path included `{phpcsroot}` it would replace that with the path to the current install of PHPCS so you can do relative paths without it changing?

**Comment by gsherwood** [comment]
Relative installed path are already resolved from a fixed location (the PHPCS root dir), but PHPCS only thinks a path is relative if it begins with a `.` because it can't rely on it being a `/` for Windows reason.

So you'd probably be best trying a setting like `./vendor/wimg/php-compatibility,./util/PHPCS/`

If that works for you, I can update the docs to reflect that.

**Comment by PatrickRose** [comment]
Updating to `../../wimg/php-compatibility,../../../util/PHPCS/` worked for me (since PHPCS was installed via composer, so it was in `vendor/squiz/phpcs/`. That documentation update would be wonderful!

**Comment by gsherwood** [comment]
I've updated the docs with information about relative installed paths: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options#setting-the-installed-standard-paths

Thanks for the suggestion.
