### ISSUE TITLE
CI problems with "File appears to be minified and cannot be processed" warning.

### ISSUE THREAD

**Issue by titanrat** [squizlabs/PHP_CodeSniffer#1626]
My CI Pipeline which have phpcs check fails with

> WARNING | File appears to be minified and cannot be processed

on minified js files.
How can i exclude this warning from checks and messages?
--warning-severity doesn't work.
exclude *\.min.js doesn't work.

**Comment by gsherwood** [comment]
Excluding these files from checking is the best way of removing the warning. You can mute the error by setting the severity of `Internal.Tokenizer.Exception` to `0` in a ruleset.xml file, but then you wouldn't see any more serious tokenizer errors if they occur.

Adding `--ignore=*.min.js` to the command should work, assuming your minified files all end with `.min.js`.

**Comment by titanrat** [comment]
Both methods works. Thank you.
