### ISSUE TITLE
Generic.Files.OneClass/Interface/TraitPerFile sniffs don't work for full PSR-4 compliance

### ISSUE THREAD

**Issue by legoktm** [squizlabs/PHP_CodeSniffer#1627]
Hi, we're currently working on migrating the MediaWiki codebase to adhere to [PSR-4](http://www.php-fig.org/psr/psr-4/). PSR-4 requires that each file contain only one class/trait/interface. So I added the following to our ruleset:
```xml
	<rule ref="Generic.Files.OneClassPerFile" />
	<rule ref="Generic.Files.OneInterfacePerFile" />
	<rule ref="Generic.Files.OneTraitPerFile" />
```

However, these three sniffs together still allow you to have one file with a class AND a trait in it. Is it possible to have a sniff that ensures there's only one class or one interface or one trait per file?

**Comment by gsherwood** [comment]
There is no included sniff to do this, although it would be pretty easy to take the OneClassPerFile sniff and have it register to look for classes, interfaces, and traits.

You'd change register() from:
return array(T_CLASS, T_INTERFACE, T_TRAIT);

**Comment by legoktm** [comment]
I've added a custom sniff with your suggested modification into our custom standard (https://gerrit.wikimedia.org/r/#/c/374026/) just so we're not blocked for now and it works perfectly, thanks!.

> If you're instead happy to wait for a release, I'll add a sniff to do this.

That would be fantastic, and I could remove the custom sniff once there's a new release :)

**Comment by gmponos** [comment]
I am trying to understand something here.

> PSR-4 requires that each file contain only one class/trait/interface.

Is the above also required from PSR-0?

If yes.. shouldn't the new sniff or all the above sniffs be included in PSR-1?

**Comment by gsherwood** [comment]
Regarding including this sniff in the PSR1 standard:

Neither PSR-0 or PSR-4 state that you must have one object defined per file. You do need to use a naming convention to ensure autoloading works, but you could have additional objects inside those files that are hidden from the autoloader. Maybe you are referencing them directly from other objects in the same file, or autoloading them in a custom way - the autoload PSRs don't look like they care.

So while this would be recommended, it doesn't appear to be a fixed requirement.
