### ISSUE TITLE
PHP Notice: Undefined variable: configFile in phpcs/src/Config.php on line 1574

### ISSUE THREAD

**Issue by JDGrimes** [squizlabs/PHP_CodeSniffer#1628]
Yesterday I got this when running against `master`:

>PHP Notice: Undefined variable: configFile in phpcs/src/Config.php on line 1574

I was able to trace it to 2d85de37a0948cdab55ae7a07e67f899e3ae15af.

https://github.com/squizlabs/PHP_CodeSniffer/blob/2d85de37a0948cdab55ae7a07e67f899e3ae15af/src/Config.php#L1574

A look at the surrounding code reveals that the issue is that `$configFile` is only set if `$temp === false`. In this case I am apparently using some code that passes `$temp` as `true`.

**Comment by gsherwood** [comment]
You're a legend. Thanks for finding this. Fixed now, and also spotted another place I should have had an error message.

**Comment by clintbingo** [comment]
so how do i fix the above problem

**Comment by jrfnl** [comment]
@clintbingo Well, the above was fixed two years ago, so without more information about the circumstances under which you are receiving the notice, the exact message, including file and line number and info on the PHP and PHPCS versions you are using, the answer to your question is impossible to give.
