### ISSUE TITLE
Squiz.WhiteSpace.ScopeClosingBraceclosure argument indenting incorrect with multi-line strings

### ISSUE THREAD

**Issue by turboatcrazyfactory** [squizlabs/PHP_CodeSniffer#1638]
Refer to issue https://github.com/squizlabs/PHP_CodeSniffer/issues/1637, the same problem still persist with
`Squiz.WhiteSpace.ScopeClosingBrace.Indent`

**Comment by gsherwood** [comment]
Same fix applied here.
