### ISSUE TITLE
comment not parsed as doc comment when tag directly follows star

### ISSUE THREAD

**Issue by umherirrender** [squizlabs/PHP_CodeSniffer#1649]
In the following code the comment before $var1 is T_DOC_COMMENT_OPEN_TAG, but comment before $var2 is T_COMMENT. 

	/** @var string $var1 */
	public $var1 = null;

	/**@var string $var2 */
	public $var2 = null;

In my opinion there should be no difference for both comments.

Or is there a reason for different tokens?

Used version is 3.0.2

**Comment by webimpress** [comment]
@umherirrender It is already resolved in https://github.com/squizlabs/PHP_CodeSniffer/pull/1525 and merged to master. Will be released with version 3.1.0 soon 😄

**Comment by umherirrender** [comment]
Nice, I was just searching through open issues ...
