### ISSUE TITLE
ScopeNotCamelCaps wrongly returning error

### ISSUE THREAD

**Issue by dakorpar** [squizlabs/PHP_CodeSniffer#1661]
Hi,
Generic.NamingConventions.CamelCapsFunctionName.ScopeNotCamelCaps
is returning error when you have a single letter word in some function name for example we have something that we're calling E-products so
hasEProduct IMHO is completelly correct, but code sniffer is returning error for this: 
"Public method name ::hasEProduct" is not in camel caps format "
Any notes?

**Comment by webimpress** [comment]
@dakorpar Please have a look here:
https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/Generic/Sniffs/NamingConventions/CamelCapsFunctionNameSniff.php#L71-L76

As you can see sniff is set in strict mode by default. You can change it in your `phpcs.xml` configuration:
```xml
    <rule ref="Generic.NamingConventions.CamelCapsFunctionName.ScopeNotCamelCaps">
        <properties>
            <property name="strict" value="false"/>
        </properties>
    </rule>
```

You can also have a look on similar sniffs in Squiz:
https://github.com/squizlabs/PHP_CodeSniffer/tree/master/src/Standards/Squiz/Sniffs/NamingConventions
and PSR-1:
https://github.com/squizlabs/PHP_CodeSniffer/tree/master/src/Standards/PSR1/Sniffs/Methods

**Comment by jrfnl** [comment]
What @webimpress said. The information about what properties can be set in the ruleset and what they mean, is also contained in the wiki: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Customisable-Sniff-Properties#genericnamingconventionscamelcapsfunctionname

**Comment by dakorpar** [comment]
thanks
