### ISSUE TITLE
Feature suggestion: sniff to discourage/forbid use of `goto` language construct

### ISSUE THREAD

**Issue by jrfnl** [squizlabs/PHP_CodeSniffer#1662]
Usage of `goto` is often seen as a typical code smell.

AFAICS there is currently no sniff to detect usage of `goto` and discourage/forbid it.

Is there any interest for a `Generic.PHP.DiscourageGoto` sniff to detect this ? I'd be happy to create a PR for this.

**Comment by gsherwood** [comment]
There is no sniff that I know of. Seems like a good idea, and happy to accept a PR for it.

**Comment by jrfnl** [comment]
Sniff created, see PR #1664
