### ISSUE TITLE
PSR2 formatting for accessing a member of a newly created object in a single expression

### ISSUE THREAD

**Issue by cdtweb** [squizlabs/PHP_CodeSniffer#1677]
<img width="833" alt="screen shot 2017-09-25 at 4 45 35 pm" src="https://user-images.githubusercontent.com/4228665/30835161-00aeb272-a214-11e7-8d1d-b137581c2118.png">

This diff shows a before and after of applying the PSR2 standard and using phpcbf. I am trying to figure out why the whitespace and comment was removed between the closing`}` of the if conditional and the opening`(` of my class method call. 

Any guidance is appreciated.  

Using version 3.1

**Comment by gsherwood** [comment]
Looks to be the same issue as #1669. Are you able to try the latest master and see if that works?

**Comment by cdtweb** [comment]
I can confirm that using the latest master resolves the issue.

**Comment by gsherwood** [comment]
Thanks a lot for checking that for me. Closing this as a duplicate.
