### ISSUE TITLE
Huge arrays are super slow to scan with Squiz.Arrays.ArrayDeclaration sniff

### ISSUE THREAD

**Issue by dawehner** [squizlabs/PHP_CodeSniffer#1681]
We recently had a file where scanning a single file takes > 40s

[RectangleTest.php.txt](https://github.com/squizlabs/PHP_CodeSniffer/files/1346274/RectangleTest.php.txt)

We've made some analysis why this was done https://www.drupal.org/node/2911280#comment-12270785

I'm wondering whether it would be possible to fix this in phpcs itself? For now we have a custom fix which involves moves the data to a json file.

**Comment by gsherwood** [comment]
Thanks for reporting this. The code looking to see if the array was contained within parenthesis didn't need to be there because all tokens already have that information populated for them. All tests are still passing, so I think it's a good fix.
