### ISSUE TITLE
customAutoEscapedFunctions doesn't allow spaces between items

### ISSUE THREAD

**Issue by paulschreiber** [squizlabs/PHP_CodeSniffer#1688]
In your ruleset file, `customAutoEscapedFunctions` allows comma-separated lists of values. However, if you put `, ` instead of just `,`, it ignores the second value.

Fails, allowing only `foo`:
```
<property name="customAutoEscapedFunctions" value="foo, bar" type="array" />
```

Works as expected:
```
<property name="customAutoEscapedFunctions" value="foo,bar" type="array" />
```

**Comment by jrfnl** [comment]
PR #1689 should fix this.
