### ISSUE TITLE
Squiz/SemicolonSpacing: semi-colons in for() control structures

### ISSUE THREAD

**Issue by jrfnl** [squizlabs/PHP_CodeSniffer#1690]
The `Squiz.WhiteSpace.SemicolonSpacing` sniff checks that there is no whitespace before a semi-colon.

This might however conflict with rules regarding spacing within a `for()` control structure:
```php
for ($i = 1; ; $i++) {}
for (; ; ) {}
```

See http://php.net/manual/en/control-structures.for.php examples 2 and 3.

I would like to fix this, but would like some guidance on what would be the preferred fix:
* Selectively exclude semi-colons found within a `for()` condition when they are preceded by the open parenthesis or by another `;`.
* Exclude semi-colons found within a `for()` condition completely from the sniff.
* Include them, but have a separate error code for semi-colons found within a `for()` condition so they can be modularly excluded.

@gsherwood What would you prefer ? Or maybe there is yet a fourth option I haven't thought of which would be an even better way to fix this ?

Related issue: https://github.com/squizlabs/PHP_CodeSniffer/pull/1670

**Comment by jrfnl** [comment]
FYI: I've gone ahead an pulled PR #1691 which is an implementation of the first bullet.

**Comment by gsherwood** [comment]
Option 1 sounded like the best one, so thanks for doing that PR.
