### ISSUE TITLE
Multiline arguments rules conflict

### ISSUE THREAD

**Issue by Assada** [squizlabs/PHP_CodeSniffer#1696]
PHP code:
```php
class ExceptionController extends BaseController
{
    public function showAction(
        Request $request,
        FlattenException $exception
    )
    {
        $code = $exception->getStatusCode();

        return $this->json(
            [
                'status'  => $code,
                'message' => isset(Response::$statusTexts[$code]) ? Response::$statusTexts[$code] : '',
            ]
        );
    }
}
```

```xml
<rule ref="Squiz.Functions.MultiLineFunctionDeclaration.NewlineBeforeOpenBrace"/>
<rule ref="Generic.Functions.OpeningFunctionBraceBsdAllman.BraceOnSameLine"/>
```

Result:
```bash
7 | ERROR   | [x] The closing parenthesis and the opening brace of a multi-line function declaration must be on the same line (Squiz.Functions.MultiLineFunctionDeclaration.NewlineBeforeOpenBrace)
```
Rules conflict...

But i want like this:
If function declaration multilined - opening brace must be on the same line
But if one-line declaration - opening brace must be on the new line

How i can to do that?

**Comment by jrfnl** [comment]
Eh.. by writing your own sniff for that specific behaviour ?

**Comment by gsherwood** [comment]
If you want to try writing a custom sniff to enforce this rule, you could start with the PEAR sniff and modify that: https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/PEAR/Sniffs/Functions/FunctionDeclarationSniff.php

If checks some things you might want to remove, but it runs different checks for single and multi-line declarations. For single lines, you'll want to run the K&R sniff and instead run the BSD sniff for multi-line declarations. That sniff does something similar (but for closures) in its processSingleLineDeclaration() method.
