### ISSUE TITLE
Show 100% on last line of progress meter

### ISSUE THREAD

**Issue by GaryJones** [squizlabs/PHP_CodeSniffer#1697]
![PHPCS progress meter](https://user-images.githubusercontent.com/88371/31416971-92f19d18-ae24-11e7-8fb8-5b3591fc0f48.png)

Only a minor UX improvement, but the last line of the progress meter may be clarified better by including the full number of files and percentage i.e. for the above example, `68/68 (100%)`.

**Comment by gsherwood** [comment]
If I make this change, the output will end up like this:
```
$ phpcs
............................................................ 60 / 71 (85%)
......E.E..                                                  71 / 71 (100%)
```
For short runs, you'll get something like this:
```
$ phpcs
..E.. 5 / 5 (100%)
```
I'm not really sure if this is a good change, so I'm hoping to get more feedback.

**Comment by gsherwood** [comment]
Git diff for this change if anyone wanted to try it:
```
$ git diff src/Runner.php
diff --git a/src/Runner.php b/src/Runner.php
index 75b8b1c7b..e9ce80ff4 100644
--- a/src/Runner.php
+++ b/src/Runner.php
@@ -810,6 +810,15 @@ class Runner
             echo str_repeat(' ', $padding);
             $percent = round(($numProcessed / $numFiles) * 100);
             echo " $numProcessed / $numFiles ($percent%)".PHP_EOL;
+        } else if ($numProcessed === $numFiles) {
+            $padding  = (strlen($numFiles) - strlen($numProcessed));
+            if ($numFiles > 60) {
+                $padding += (60 - ($numFiles - (floor($numFiles / 60) * 60)));
+            }
+
+            echo str_repeat(' ', $padding);
+            $percent = round(($numProcessed / $numFiles) * 100);
+            echo " $numProcessed / $numFiles ($percent%)".PHP_EOL;
         }

     }//end printProgress()

**Comment by jrfnl** [comment]
LGTM. It would also be more consistent with other industry standard tools like PHPUnit. I just came across their changelog entry from 2015 where they made the same change :wink: 

Refs:
* https://github.com/sebastianbergmann/phpunit/blob/5.0/ChangeLog-5.0.md#changed-2
* https://github.com/sebastianbergmann/phpunit/pull/1822

**Comment by GaryJones** [comment]
![screenshot of progress meter with final line numbers](https://user-images.githubusercontent.com/88371/31435342-28143732-ae77-11e7-8311-c56120654e30.png)

LGTM as well.

(Aside: The magic number `60` is now used several times, and could be moved into a descriptive variable.)

**Comment by gsherwood** [comment]
> The magic number 60 is now used several times, and could be moved into a descriptive variable.

I knew I shouldn't have posted rough code :) It's not what I would commit - just what I hacked up to see the result.

**Comment by gsherwood** [comment]
I found an issue when implementing this, which is that the progress report doesn't show skipped files. I'll fix that at the same time. It wasn't really a problem before, but now the progress needs to know that all files were processed to be able to print 100%.

**Comment by gsherwood** [comment]
This has been added now. Given it's also fixing the missing the display of skipped files, I've rolled it into the next bug fix release.
