### ISSUE TITLE
Handling of list() language construct

### ISSUE THREAD

**Issue by jrfnl** [squizlabs/PHP_CodeSniffer#1699]
### Proposal: add `list()` to the `Tokens::$functionNameTokens` property

While `list` is a language construct, for the purpose of formatting, it is normally treated as if it were a function call, similar to how `isset()` or `empty()` are treated.

To that end, I propose adding `list` to the `Tokens::$functionNameTokens` property.

There are two sniffs within PHPCS whose behaviour will change if this proposal is accepted:
* `Generic.Functions.FunctionCallArgumentSpacing`
* `PEAR.Functions.FunctionCallSignature` (and by extension `PSR2.Methods.FunctionCallSignature`)

For the `Generic.Functions.FunctionCallArgumentSpacing`, it would mean that a slight adjustment is needed to account for the possibility of an empty element, like in `list($drink, , $power) = $info;` which would otherwise trigger a `no space allowed before comma` error.

I'd be happy to create a PR to handle this if there is support for this proposal.

Opinions ?

**Comment by gsherwood** [comment]
> Have you had a chance to form an opinion about this yet ?

Sorry, I haven't got to this in my list yet. My immediate thought is that it sound reasonable though.

I'm not sure of all the implications, but if you want to create a PR for this then I trust that you'd give it the testing it needs.

**Comment by jrfnl** [comment]
Closing as replaced by PHPCSStandards/PHP_CodeSniffer#9
