### ISSUE TITLE
Setting the report won't override the one in the ruleset

### ISSUE THREAD

**Issue by dingo-d** [squizlabs/PHP_CodeSniffer#1734]
I created a custom ruleset for the company I work for and in there I defined the default report type as you can [see here](https://github.com/infinum/coding-standards-wp/blob/master/Infinum/ruleset.xml#L16).

But if I were to type in my project

`./vendor/bin/phpcs --report=json --standard=Infinum .`

What I will get is json report first, and then after it I'll get my full report defined in the `ruleset.xml`.

Why isn't `--report=json` overriding the report from the ruleset? This is an issue, because in vscode when using the [vscode-phpcs](https://github.com/ikappas/vscode-phpcs/issues/32) extension which would work like sublime linters in sublime text 3, I get an error which points out that there is an unexpected token in the json (the start of the full report). And this basically renders it unusable.

The sublime extension for phpcs doesn't seem to have that problem since there everything works fine.

**Comment by gsherwood** [comment]
This functionality is working fine for me. I included this line in a ruleset: `<arg name="report" value="full" />` and then used `--report=json` on the command line and only got the JSON report.

Looking at the code shows that this is how it is designed to work as well.

I notice that you've removed the full report line from your ruleset. Did you get it working?

As a side note, the default report format for PHPCS is `full` so there isn't any need to include that in a ruleset.

**Comment by dingo-d** [comment]
No I did not get it working, but I thought that, in order to fix this, I should just remove the full report from the ruleset (easiest solution). Plus I tested it without `<arg name="report" value="full" />`, and like you said, I got the full report when doing a manual check, so I guess I don't need it after all.

It is odd that I got 2 reports when trying to override one from the terminal.

**Comment by gsherwood** [comment]
I'll close this as I can't replicate any issues. But if you try again and find problems (or anyone else does) please comment again and I'll take a look. Thanks for getting back to me.
