### ISSUE TITLE
Not getting indentation error for variables

### ISSUE THREAD

**Issue by MaxBangma** [squizlabs/PHP_CodeSniffer#1742]
As you can see from the image below, I do get errors for if-statements in regards to wrong indentation. However, I do not get indentation errors for variables.

![image](https://user-images.githubusercontent.com/27278245/32288617-c3462742-bf34-11e7-9c0a-7d26907c5fbf.png)

**Comment by gsherwood** [comment]
The indent checks only ensure that lines are indented *at least* to a specific column.

See explanation [here](https://github.com/squizlabs/PHP_CodeSniffer/issues/1345) and [here](https://github.com/squizlabs/PHP_CodeSniffer/issues/1632).

Does that make sense?

**Comment by jrfnl** [comment]
@MaxBangma The sniff has some customizable properties you can pass from your ruleset which you may find useful: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Customisable-Sniff-Properties#genericwhitespacescopeindent

Hope that helps ;-)
