### ISSUE TITLE
unresolved merge conflict

### ISSUE THREAD

**Issue by Hoten** [squizlabs/PHP_CodeSniffer#1745]
https://github.com/squizlabs/PHP_CodeSniffer/blob/78aa3f3e8b75bdc94eb86caf35305a43f525e929/src/Standards/Squiz/Tests/PHP/HeredocUnitTest.inc#L21

**Comment by jrfnl** [comment]
No, it's not. See the comment above:
https://github.com/squizlabs/PHP_CodeSniffer/blob/78aa3f3e8b75bdc94eb86caf35305a43f525e929/src/Standards/Squiz/Tests/PHP/HeredocUnitTest.inc#L14-L17

**Comment by Hoten** [comment]
D’oh- my mistake.
