### ISSUE TITLE
Smarter cache

### ISSUE THREAD

**Issue by hakamairi** [squizlabs/PHP_CodeSniffer#1751]
Currently cache stores absolute paths. 
This makes it impossible to reuse same cache on different setup ups like dev and CI.

The use case here is execution based on initial git stored cache to gain performance on multibranch pipeline project on multiple jenkins nodes (otherwise full analysis is always performed on a node with no previous branch jobs executed).

**Comment by gsherwood** [comment]
Just trying to understand the use case:

Are you attempting to take a cache file generated from one machine, copy it to a second machine, then use that for a PHPCS run on the second machine?

**Comment by hakamairi** [comment]
Yes. I have 8 jenkins nodes and devs would like to have their newly created branches executes as fast as possible.
What jenkins2 does is create a directory per branch and work on the code there.
The initial run takes 3-4 minutes, after that I can reuse the cache (down to 1-5 seconds of execution) on a given node, but there's no way to tell on which node it will execute next time.

When someone creates a new branch, there's a new directory for it on executing jenkins node.

**Comment by gsherwood** [comment]
How would the cache file get from one node to the other? Is that something jenkins takes care of for you? And are you sure you wont ever have two phpcs instances running at the same time and fighting over the same cache file on a single node?

In general, using relative paths is pretty dangerous because the obvious question is "relative to what? and how do I figure out that base path?" and it assumes that files using the same relative path must be the same, which is absolutely not the case. So I'd need a really clear use case and protections to switch the relative paths, or I risk breaking caching for everyone else.

**Comment by hakamairi** [comment]
Good point.
I thought to just check it into version control, like git. 
If that's too dangerous I think I can deal with it another way. Like a common cache shared between the branches (maybe that would work).

Anyway thanks for your support!

**Comment by hakamairi** [comment]
One question though, the cache in CLI `--cache=mycache` it's only relative path or just file name? I'm not able to use absolute and level up `../ ` with it, right?

**Comment by gsherwood** [comment]
The path you supply on the CLI can be relative and use `../` because it is run through `realpath()`.

**Comment by hakamairi** [comment]
So in general, if I execute the phpcs from my app's root dir the phpcs cache has to be relative to this path. Could we leverage the same behavior with cache?

**Comment by gsherwood** [comment]
> Could we leverage the same behavior with cache?

Sorry, but I'm not sure what you mean.

**Comment by hakamairi** [comment]
My basic idea was to put the cache in `../` as it's shared by all the branches on a given Jenkins node (short sighted as the path to files still would be different). Since that's not possible I thought, hey, I install phpcs from composer.json, hence it's installed in the app's root dir under `./vendors/`, I'm not able to move the cache outside so why do I need absolute paths in cache file for?

My current workaround was to just download prewarmed cache and `sed -i` the paths. Curiously enough, some times it's still not valid between nodes (analysis saying that 0 files found in cache).

**Comment by hakamairi** [comment]
So my crazy idea to just change the paths actually fails. 
Codehash is the reason why. (while paths and hashes of the files actually match)

Running on one machine:
`{"config":{"tabWidth":0,"encoding":"utf-8","recordErrors":true,"annotations":true,"codeHash":"b505f757c1131a8323f6397f5746a800","rulesetHash":"dda56952bf799c9b76aa89100259ac0a"}`

Running on another one:
`"config":{"tabWidth":0,"encoding":"utf-8","recordErrors":true,"annotations":true,"codeHash":"c4beab5dc7db4c0f3e46c7de4129d4d8","rulesetHash":"dda56952bf799c9b76aa89100259ac0a"}`

Looking more into the calculation. Both machines have the same code base, local install of phpcs by composer.json. 

Here are the phpcs -vv logs.
Machine 1:
[cachdiffloc.txt](https://github.com/squizlabs/PHP_CodeSniffer/files/1499013/cachdiffloc.txt)
Machine 2:
[cachdiffsrv.txt](https://github.com/squizlabs/PHP_CodeSniffer/files/1499014/cachdiffsrv.txt)

Please notice that that's the same set of sniffs processed just in a different order, effecting in different codeHash. It this a bug?

**Comment by gsherwood** [comment]
> Please notice that that's the same set of sniffs processed just in a different order, effecting in different codeHash. It this a bug?

I wouldn't call it a bug unless you run PHPCS again on the same machine and it never uses the cache file. I don't know why recursing the same directory on different machines gives the files in a different order though, but I can change the cache to sort the file paths before hashing them. That's not going to add any significant time, and if it gets you a step closer to being able to reuse the cache file, then that's a good thing.

**Comment by gsherwood** [comment]
Files included in the code hash are now sorted before hashing, so they should give a consistent result across servers. It would be great if you could apply the patch and try it out.

**Comment by hakamairi** [comment]
Hi Greg,
It works 👍 

Result from machine 1 `	=> codeHash: 317dea23571e3060c8bf86b0530a72de
		=> rulesetHash: dda56952bf799c9b76aa89100259ac0a
		=> cacheHash: 3497e146c335`

Result from machine 2 `	=> codeHash: 317dea23571e3060c8bf86b0530a72de
		=> rulesetHash: dda56952bf799c9b76aa89100259ac0a
		=> cacheHash: 3497e146c335`

**Comment by gsherwood** [comment]
Good news. Thanks for testing that for me.

**Comment by hakamairi** [comment]
No problem. Glad to help. May I ask, when would you like to release?

**Comment by gsherwood** [comment]
> when would you like to release?

When my list is done: https://github.com/squizlabs/PHP_CodeSniffer/milestone/3
But there is no set time as I can only work on this project between other jobs.

**Comment by gsherwood** [comment]
This has been released, but I'm not sure if you need any more changes to support what you're doing. I'm not really keen on switching to relative paths for caching right now, so it would be good to know if you need anything else to help with a workaround.

**Comment by hakamairi** [comment]
Hi @gsherwood  sorry to get back to you so late.
Nah, it's great. I'm fine with the current solution, or relative path as long as the are ordered before calculations.

Thanks for your support! You're awesome.

**Comment by gsherwood** [comment]
Thanks for getting back to me.
