### ISSUE TITLE
Allow skipping tokenisation for certain files

### ISSUE THREAD

**Issue by rmccue** [squizlabs/PHP_CodeSniffer#1753]
For some files, we use external sniffers only (i.e. for JS, we exclusively use ESLint). It would be great if we could shortcircuit the tokenisation for these files (and have them just return the dummy `T_OPEN_TAG`), allowing us to trigger the external tools via phpcs without the overhead of tokenisation.

**Comment by gsherwood** [comment]
The only way I can think of doing this is to use the comment syntax. You can already put `// phpcs:ignoreFile` at the top of your file and PHPCS will skip tokenizing it completely.

I could add another comment option to fake the token list so it just appears as an open tag, but it does mean adding a comment to your files. This is a quick solution to implement though.

A more complex solution would involve a new syntax for rulesets that allows for a list of files (or patterns) to be specified for this feature. The obviously benefit here is that you can see a list of these files in a ruleset, and just exclude all JS files by using `*.js`.

Ultimately, both options should probably be implemented to provide a more complex feature.

**Comment by rmccue** [comment]
The temporary solution I've gone with is to create my own tokeniser class which simply returns the `T_OPEN_TAG`, but this also requires updating the sniffs to recognise the tokeniser. I could potentially override the `JS` tokeniser completely instead.

As it turns out, the overhead isn't that significant anyway, so this is pretty low-priority.

**Comment by gsherwood** [comment]
Closing due to lack of additional interest for this feature
