### ISSUE TITLE
Unknown type hint "object" in Squiz.Commenting.FunctionComment

### ISSUE THREAD

**Issue by oojacoboo** [squizlabs/PHP_CodeSniffer#1757]
PHP 7.2 introduced support for the `object` scalar type

https://wiki.php.net/rfc/object-typehint

```
Unknown type hint "object" found for $object
(Squiz.Commenting.FunctionComment.InvalidTypeHint)
```

**Comment by gsherwood** [comment]
Thanks for letting me know. This error will no longer be shown when running under PHP 7.2+
