### ISSUE TITLE
Error: Class 'PHP_CodeSniffer\Config' not found, failed autoloading for unit tests.

### ISSUE THREAD

**Issue by CMalvika** [squizlabs/PHP_CodeSniffer#1763]
Recently upgraded to version 3.*. And since i've now many many custom sniffs, i followed this guide -> https://github.com/squizlabs/PHP_CodeSniffer/wiki/Version-3.0-Upgrade-Guide.

All the sniffs are working greate! but my unit tests started failing with not any of PHP_CodeSniffer found. Although i've it namespaced correctly like below..
`use PHP_CodeSniffer\Config;
use PHP_CodeSniffer\Ruleset;
use PHP_CodeSniffer\Files\DummyFile;
use PHPUnit\Framework\TestCase;`

**Comment by jrfnl** [comment]
@CMalvika How are you executing the unit test command ?

Also: you might find the bit about the test bootstrap changes in the `3.1.0` release interesting to take note of: https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.1.0

**Comment by CMalvika** [comment]
@jrfnl yes, i execute unit test command vendor/bin/phpunit <path to file> like this.
Thank you for the note: i should check this.

**Comment by jrfnl** [comment]
You're welcome. Does this mean your issue is now solves ? In that case, you may want to close the issue :smile: .
