### ISSUE TITLE
A big thank you!

### ISSUE THREAD

**Issue by louisl** [squizlabs/PHP_CodeSniffer#1779]
I would just like to say a big thank you to Greg for developing PHP_Codesniffer and for your continued patience and timely support with issues. Your work has been much appreciated!

We've just officially launched the standard for CodeIgniter4 development.

[CodeIgniter4-Standard](https://github.com/bcit-ci/CodeIgniter4-Standard)

**Comment by jrfnl** [comment]
Congrats @louisl !

Asa side-note: would be great if you would add the standard to the list in issue #1165.

**Comment by gsherwood** [comment]
Thanks a lot for the kind words @louisl, and congrats on your release.

**Comment by louisl** [comment]
You're most welcome @gsherwood, thanks again.
