### ISSUE TITLE
Expected 1 blank line at end of file; 2 found

### ISSUE THREAD

**Issue by sandrodz** [squizlabs/PHP_CodeSniffer#1789]
<img width="1207" alt="screen shot 2017-12-14 at 11 00 33 pm" src="https://user-images.githubusercontent.com/8479569/34009525-b56570e6-e122-11e7-99ef-8161d9f93848.png">
<img width="1207" alt="screen shot 2017-12-14 at 11 00 55 pm" src="https://user-images.githubusercontent.com/8479569/34009526-b58a384a-e122-11e7-9269-1e8401d0649d.png">

it is not a vim issue, since it does same on cli

<img width="576" alt="screen shot 2017-12-14 at 11 03 11 pm" src="https://user-images.githubusercontent.com/8479569/34009607-ff81ad48-e122-11e7-9b11-f250ecf65569.png">

**Comment by gsherwood** [comment]
You've got 2 newline characters are the end of your file and the sniff is trying to enforce a single newline only. The wording of the error message comes from the PSR2 standard. In VIM, it obviously looks like one blank line while in other editors it would show as two blank lines.

**Comment by sandrodz** [comment]
@gsherwood indeed wording is misleading. Newline character and 1 blank line are not the same thing.

**Comment by gsherwood** [comment]
> Newline character and 1 blank line are not the same thing.

Oh, I know. When I first coded this standard into PHPCS back in 2012, it was one of the questions I asked of the PSR-2 authors: https://groups.google.com/forum/#!topic/php-fig/PSzmcFVQst0

But that was only the initial discussion. It was discussed again elsewhere and they eventually decided it was a single newline character. But I can't find the link to that discussion (it may have been a github issue) - only where I described the result of it: https://groups.google.com/d/msg/php-fig/T5RZlSt8G88/ZhvrtiSKUHcJ

Hope that clears this up though.

**Comment by gsherwood** [comment]
Actually, I found it: https://github.com/squizlabs/PHP_CodeSniffer/pull/42

**Comment by sandrodz** [comment]
@gsherwood piece of internet history ^_^ we can close this I guess.

Thanks for looking in!

**Comment by gsherwood** [comment]
> Thanks for looking in!

No problem.
