### ISSUE TITLE
Declare in files breaks Squiz.Commenting.BlockComment sniff

### ISSUE THREAD

**Issue by tobiastom** [squizlabs/PHP_CodeSniffer#1800]
When I use the following example file:

	<?php declare( strict_types=1 );
	
	/**
	 * Test File
	 **/
	namespace Lala;

and run phpcs with the following parameters:

	phpcs --sniffs=Squiz.Commenting.BlockComment Test.php

I get the following errors:

	FILE: /**********/Test.php
	----------------------------------------------------------------------
	FOUND 2 ERRORS AFFECTING 2 LINES
	----------------------------------------------------------------------
	 3 | ERROR | [x] Block comments must be started with /*
	 5 | ERROR | [x] Block comments must be ended with */
	----------------------------------------------------------------------
	PHPCBF CAN FIX THE 2 MARKED SNIFF VIOLATIONS AUTOMATICALLY
	----------------------------------------------------------------------

The problem seems to be the `declare` statement in the first line. The problem seems to originate in [`PHP_CodeSniffer/src/Standards/Squiz/Sniffs/Commenting/BlockCommentSniff.php` line 92](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/Squiz/Sniffs/Commenting/BlockCommentSniff.php#L92). It checks if the previous token is a file open one. Unfortunately the previous one is the declare statement.

**Comment by gsherwood** [comment]
This sniff is expecting you to put the file comment (assuming that's a file comment) first. It wants this:
```
<?php
/**
 * Test File
 **/

declare( strict_types=1 );

namespace Lala;
```
Otherwise, it think you're documenting the namespace line and requires you to use normal block comments for that.

If you prefer putting the declare statement before the file comment, then this sniff isn't going to work for you.
