### ISSUE TITLE
Make a Rule phpcbf only?

### ISSUE THREAD

**Issue by donatj** [squizlabs/PHP_CodeSniffer#1801]
This may already exist, but digging through the Github wiki and the code a bit I can't find any support for it. 

I'd like to be able to define a rule in my ruleset.xml as only running on `phpcbf`.

That is to say that it won't fail our CI but will get automatically cleaned up on our merge hook.

My thought would be either an attribute on the rule tag itself, or a `<cbf-only>` tag I could wrap my rule's in, but I'm pretty flexible as far as implementation goes.

**Comment by jrfnl** [comment]
Hi @donatj , as you guessed, this already exists. You can find the information on how to do this in the wiki: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-ruleset.xml#selectively-applying-rules

**Comment by donatj** [comment]
@jrfnl Thank you! This is exactly what I was looking for.
