### ISSUE TITLE
Test for file execute bit

### ISSUE THREAD

**Issue by szepeviktor** [squizlabs/PHP_CodeSniffer#1808]
It would add a value for users on non-unixy OS-es.

Thanks.

**Comment by jrfnl** [comment]
@szepeviktor Viktor, it's quite unclear to me what the issue is you're reporting. Would you mind expanding a bit ?

**Comment by szepeviktor** [comment]
The execute bit of files - git stores only this permission.

```
drwxr-xr-x 12 gtone gtone   4096 Oct 28 20:33 app
-rwxr-xr-x  1 gtone gtone   1646 Jul  9 22:12 artisan <-- see here the 3 x-es
drwxr-xr-x  3 gtone gtone   4096 Oct  9 19:43 bootstrap
-rw-r--r--  1 gtone gtone   2100 Dec 29 13:11 composer.json
-rw-r--r--  1 gtone gtone 172459 Dec 29 13:11 composer.lock
drwxr-xr-x  2 gtone gtone   4096 Dec 29 13:17 config
drwxr-xr-x  5 gtone gtone   4096 Jul  9 22:12 database
-rw-r--r--  1 gtone gtone    505 Dec 29 10:10 gulpfile.js
-rw-r--r--  1 gtone gtone    212 Jul  9 22:12 package.json
drwxr-xr-x 11 gtone gtone   4096 Dec 30 06:40 public
-rw-r--r--  1 gtone gtone   1264 Jul  9 22:12 readme.md
drwxr-xr-x  5 gtone gtone   4096 Nov 24  2016 resources
drwxr-xr-x  2 gtone gtone   4096 Jul  9 22:12 scripts
-rw-r--r--  1 gtone gtone    567 Jul  9 22:12 server.php
drwxr-xr-x  8 gtone gtone   4096 Apr 15  2017 storage
drwxr-xr-x 38 gtone gtone   4096 Dec 29 13:18 vendor
```

**Comment by szepeviktor** [comment]
As of now there is no phpcs rule to handle it.
Hint: the `chmod()` function handles it in PHP.

**Comment by jrfnl** [comment]
Ah! That makes it much clearer. So this is basically a feature request for a `Generic.Files.FilePermissions` sniff to check that all files in a project have file permissions set and potentially auto-fix this, if not ?

**Comment by szepeviktor** [comment]
Yes. Only check the execution bit, and turn it off as fix, as PHP file do not need execution bits.
Except `artisan` which is the CLI for Laravel.

**Comment by szepeviktor** [comment]
Git does not store other bits, so a files will either 644 or 755

**Comment by szepeviktor** [comment]
A friendly ping.

Could it be that we are waiting for a PR?
