### ISSUE TITLE
Cache not invalidated by using different PHP runtime

### ISSUE THREAD

**Issue by Majkl578** [squizlabs/PHP_CodeSniffer#1816]
Cache is currently not invalidated when different runtimes are used.
As an example, we have a sniff that reports errors for `object` (when native typehint is missing) on PHP 7.2+, but is quiet on PHP 7.1 for obvious reasons. When executed under PHP 7.2, error is correctly reported and cache is generated. Then under 7.1 the error is emitted as well, although it's not expected.

Reproducible with https://github.com/slevomat/coding-standard/blob/4.1.0/SlevomatCodingStandard/Sniffs/TypeHints/TypeHintDeclarationSniff.php.

**Comment by gsherwood** [comment]
I've changed the cache code to include the PHP version ID in the list of variables that are used to generate the cache key. Thanks for reporting this.
