### ISSUE TITLE
Blank line not enforced after control structure if comment on same line as closing brace

### ISSUE THREAD

**Issue by josephzidell** [squizlabs/PHP_CodeSniffer#1817]
```php
<?php

$true = true;
if ($true) {
	echo 'hi 1';
}
if ($true) {
	echo 'hi 2';
}//end if
if ($true) {
	echo 'hi 3';
}
```

Throws an error after the first `if`, but not after the second. When there's a closing comment, a blank line is not enforced.

This likewise affects `foreach`s etc...

**Comment by gsherwood** [comment]
Thanks for reporting this

**Comment by josephzidell** [comment]
Thanks @gsherwood really appreciate the quick fix
