### ISSUE TITLE
New phpcs: marker syntax incompatible with API reference generators

### ISSUE THREAD

**Issue by skyzyx** [squizlabs/PHP_CodeSniffer#1819]
I have some code which looks like this: [src/Mixin/DeepTypeTrait.php#L30-L48](https://github.com/simplepie/simplepie-ng/blob/d1a29ddae7cf5ae33589c3ffe8d6c8f94059ea44/src/Mixin/DeepTypeTrait.php#L30-L48)

I am using PHP CodeSniffer alongside [PHP CS Fixer](http://cs.sensiolabs.org) for keeping my code clean. Here's my [phpcs.xml](https://github.com/simplepie/simplepie-ng/blob/d1a29ddae7cf5ae33589c3ffe8d6c8f94059ea44/phpcs.xml) file, and the [Makefile command](https://github.com/simplepie/simplepie-ng/blob/d1a29ddae7cf5ae33589c3ffe8d6c8f94059ea44/Makefile#L61-L64) I run it with.

I recently switched the syntax for PHP CodeSniffer from `@codingStandardsIgnore(Start|End)` to the new `phpcs:(enable|disable)` syntax. PHP CodeSniffer works even better now that I understand how to temporarily prevent certain rules in certain situations.

#### Actual

But I'm also using [Sami](https://github.com/FriendsOfPHP/Sami) as my API reference generator. Now that I've moved away from using an annotation which begins with `@`, my documentation tool (and many others for PHP since all of the modern ones leverage the same underlying PHPDocumentor 2.x/PSR-5 libraries) now output the PHP CodeSniffer annotations as documentation (see screenshot).

![phpcs-in-sami](https://user-images.githubusercontent.com/39447/34449559-4d68f660-ecae-11e7-8e86-cb886492d677.png)

#### Expected

My expectation is that these tools should be able to work side-by-side without adverse affects.

#### Possible solution

One possible solution would be to allow the `phpcs:` annotation to be prefixed with a `@` character (i.e., `@phpcs:`) so that when it is used inside of docblocks (such as my case, where I need to tweak the rules for the function signature), it is ignored by PSR-5-compatible docblock parsers, and — in turn — does not end up in my public documentation.

Thanks!

**Comment by skyzyx** [comment]
![phpcs-in-sami](https://user-images.githubusercontent.com/39447/34449559-4d68f660-ecae-11e7-8e86-cb886492d677.png)

**Comment by gsherwood** [comment]
I don't see any issue with allowing a leading `@`. Seems like a good addition.

**Comment by gsherwood** [comment]
I've added the ability to optionally use a leading `@` for all `phpcs:` comments.

**Comment by skyzyx** [comment]
Awesome. When do you plan to cut a release? I’ll keep an eye out for it. :+1:

**Comment by gsherwood** [comment]
> When do you plan to cut a release?

This week might be pushing it, so probably next week.
