### ISSUE TITLE
Tag last PHPCS 2.x release ?

### ISSUE THREAD

**Issue by jrfnl** [squizlabs/PHP_CodeSniffer#1822]
As PHPCS 3.x has been out for more than six months and there is no continued development in PHPCS 2.x, it might be useful to tag a last/final PHPCS 2.x release ?

There are two fixes now in the `2.9` branch which are not yet in a tagged release.

**Comment by photodude** [comment]
See comment https://github.com/squizlabs/PHP_CodeSniffer/issues/1890#issuecomment-364299963

**Comment by jrfnl** [comment]
@gsherwood As the backports by @photodude have been merged quite a while back, could `2.9.2` be tagged so this issue can be closed (as well as the `2.9-dev` branch discontinued ?

**Comment by gsherwood** [comment]
2.9.2 has just been released

**Comment by gsherwood** [comment]
Note that I didn't release this via PEAR because everyone running a PEAR upgrade would immediately get 2.9.2 even if they are on a 3.x version.
