### ISSUE TITLE
Wiki: Default encoding info should be updated (ISO-8859-1 -> UTF-8)

### ISSUE THREAD

**Issue by zoliszabo** [squizlabs/PHP_CodeSniffer#1844]
Wiki is stating wrong/deprecated info about the default encoding phpcs is using, which may be misleading for some users:

- https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options#setting-the-default-encoding
- https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#specifying-an-encoding

**Comment by gsherwood** [comment]
Thanks for finding this. The wiki has been updated now.
