### ISSUE TITLE
Detect use statements starting with namespace separator

### ISSUE THREAD

**Issue by umherirrender** [squizlabs/PHP_CodeSniffer#1845]
The UseDeclarationSniff  does not check, if a use statement starts with a namespace separator. It is valid to write `use PHP_CodeSniffer\Sniffs\Sniff;` or `use \PHP_CodeSniffer\Sniffs\Sniff;`, but having all in the first code style would be nice.

Could be an autofixing issue, because it only has to remove the token (T_NS_SEPARATOR).

**Comment by VincentLanglet** [comment]
@gsherwood There is now the ImportStatementSniff from PSR12.
I think you can close this issue.

**Comment by gsherwood** [comment]
> I think you can close this issue.

Agreed. Thanks for pointing this out.
