### ISSUE TITLE
Warning "Unused bound variable" appears even if the bound variable is used.

### ISSUE THREAD

**Issue by alberto56** [squizlabs/PHP_CodeSniffer#1849]
I'm getting:

    FILE: /path/to/file.php
    ----------------------------------------------------------------------
    FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
    ----------------------------------------------------------------------
     223 | WARNING | Unused bound variable $simplified.
    ----------------------------------------------------------------------

My code is:

      $simplified = [];
      array_map(function ($item) use (&$simplified) {
        $simplified[$item['nid']] = preg_replace('/^www./', '', $item['domain']);
      }, $hospitals);

So, the bound variable is required, and used here. I think the warning is given my mistake.

**Comment by alberto56** [comment]
Here is how I avoid the warning:

      $simplified = [];
      // @codingStandardsIgnoreStart
      // See https://github.com/squizlabs/PHP_CodeSniffer/issues/1849
      array_map(function ($item) use (&$simplified) {
      // @codingStandardsIgnoreEnd
        $simplified[$item['nid']] = preg_replace('/^www./', '', $item['domain']);
      }, $hospitals);

**Comment by gsherwood** [comment]
This is not an error message produced by an included PHP_CodeSniffer sniff. You can use the `-s` command line argument to see the error code for the message and that will tell you what coding standard it is coming from. You'll need to open a report with the project that maintains that standard.

**Comment by alberto56** [comment]
Thanks for the quick reply. The standard is:

"DrupalPractice.CodeAnalysis.VariableAnalysis.UnusedVariable"

I have opened an issue with that project at https://www.drupal.org/project/coder/issues/2936066

This issue can be closed then.

**Comment by gsherwood** [comment]
Thanks for getting back to me.
