### ISSUE TITLE
[2.9.x] PSR2.Files.ClosingTag detects unexpected closing tag

### ISSUE THREAD

**Issue by photodude** [squizlabs/PHP_CodeSniffer#1850]
in PHPCS 2.9.1 the PSR2.Files.ClosingTag sniff detects unexpected PHP closing tag in the following mixed HTML/PHP cases

joomla-cms\administrator\components\com_users\views\user\tmpl\edit_groups.php
```php
<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_users
 *
 * @copyright   Copyright (C) 2005 - 2017 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

// Include the component HTML helpers.
JHtml::addIncludePath(JPATH_COMPONENT . '/helpers/html');
?>
<?php echo JHtml::_('access.usergroups', 'jform[groups]', $this->groups, true); ?>
```

joomla-cms\administrator\modules\mod_title\tmpl\default.php
```php
<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  mod_title
 *
 * @copyright   Copyright (C) 2005 - 2017 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;
?>
<?php if (!empty($title)) : ?>
	<?php echo $title; ?>
<?php endif; ?>
```

**Comment by gsherwood** [comment]
The only error I get is `A closing tag is not permitted at the end of a PHP file (PSR2.Files.ClosingTag.NotAllowed)`

Is that what you are getting as well?

If so, that's a pretty clear PSR-2 error, but I'm sure the PSR-2 authors didn't have template files in mind when they wrote that. You may want to skip checking template files or exclude that sniff in a ruleset.xml file using a regex to match the files.

**Comment by photodude** [comment]
Yes, that's the same error. 
I based my reasoning for filing an error on https://github.com/squizlabs/PHP_CodeSniffer/issues/453

We currently use Zend.Files.ClosingTag with exclusions. 

In these cases it's a template file that's mixed PHP/HTML but lacks the HTML which the sniff check would have used to skip the check as noted in these lines https://github.com/squizlabs/PHP_CodeSniffer/blob/2.9/CodeSniffer/Standards/PSR2/Sniffs/Files/ClosingTagSniff.php#L57-L64

**Comment by photodude** [comment]
Would it be possible (or better) to check if there are multiple pairs of `T_OPEN_TAG` and `T_CLOSE_TAG` or `T_OPEN_TAG_WITH_ECHO` rather than just looking for `T_INLINE_HTML` ?

**Comment by gsherwood** [comment]
> Would it be possible (or better) to check if there are multiple pairs of T_OPEN_TAG and T_CLOSE_TAG or T_OPEN_TAG_WITH_ECHO rather than just looking for T_INLINE_HTML ?

I don't think that is the intention of the standard. Is there a reason these PHP blocks aren't just one big block? It feels like I'd be changing the standard for everyone based on an edge case.

**Comment by photodude** [comment]
Only reason I know of for these not being just PHP blocks is due to these being template view files and that's the format used in the template view files. I don't know enough about the Joomla MVC to say if there is more to that or if it's a hard requirement.

**Comment by gsherwood** [comment]
> I don't know enough about the Joomla MVC to say if there is more to that or if it's a hard requirement.

Fair enough.

I do think it's a bit strange to say that these files are not *only* PHP given they contain only PHP tokens and don't even output whitespace when executed. My worry is that changing the definition of "php file" in the sniff will mean that some files that are not intended to be template files will be missed.

But I'm not strongly for that position and I'd certainly change it if that's the only real option. I just don't think I'd want to do it in the 2.9 branch though, which is probably going to be a problem for you.

**Comment by photodude** [comment]
Based on the current road map it will be summer 2018 before most Joomla projects will be transitioned/transitioning to phpcs 3.x

**Comment by gsherwood** [comment]
Closing due to lack of additional interest.
