### ISSUE TITLE
Major phar download links?

### ISSUE THREAD

**Issue by Soullivaneuh** [squizlabs/PHP_CodeSniffer#1855]
Here is some major specific download links?

Something like:

- `https://squizlabs.github.io/PHP_CodeSniffer/phpcs-1.phar`
- `https://squizlabs.github.io/PHP_CodeSniffer/phpcs-2.phar`
- `https://squizlabs.github.io/PHP_CodeSniffer/phpcs-3.phar`

**Comment by gsherwood** [comment]
There are no PHAR download links for the latest version of each branch. You'll need to go to the release list and grab the required PHAR from there if you want an old version. But PHARs were not generated for 1.x versions, so they are only available from version 2.0.0 onwards.

For reference, the last 2.x release was 2.9.1: https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/2.9.1

**Comment by gsherwood** [comment]
You can always get the latest version using the URL: https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar

Given PHPCS 2.x is discontinued, I'm not going to add any additional PHARs for it. But I'll consider this for future major version upgrades
