### ISSUE TITLE
composer install 

### ISSUE THREAD

**Issue by markobt** [squizlabs/PHP_CodeSniffer#1856]
root@921f7cc6e3dd:/var/www/html# php -v
PHP 7.1.12 (cli) (built: Dec  1 2017 01:55:23) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
root@921f7cc6e3dd:/var/www/html# cat composer.json
{
    "require-dev": {
        "squizlabs/php_codesniffer": "2.*"
    }
}
root@921f7cc6e3dd:/var/www/html# composer install
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information

  [Seld\JsonLint\ParsingException]
  "https://packagist.org/packages.json" does not contain valid JSON
  Parse error on line 1:
  ^
  Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

root@921f7cc6e3dd:/var/www/html# composer global require "squizlabs/php_codesniffer=*"
Changed current directory to /root/.composer
Do not run Composer as root/super user! See https://getcomposer.org/root for details

  [Seld\JsonLint\ParsingException]
  "https://packagist.org/packages.json" does not contain valid JSON
  Parse error on line 1:
  ^
  Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

root@921f7cc6e3dd:/var/www/html# composer --version
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Composer version 1.5.6 2017-12-18 12:09:18
root@921f7cc6e3dd:/var/www/html#

**Comment by webimpress** [comment]
@markobt looks like composer/packagist issue. I can see 502 on packagist.org right now 😢

**Comment by markobt** [comment]
oh(, thanks
