### ISSUE TITLE
phpcs: Unexpected end of JSON input

### ISSUE THREAD

**Issue by furkanuzun** [squizlabs/PHP_CodeSniffer#1858]
Already installed phpcs on extension manager. After that composer works done. When i tried to open vscode i have this error.

"phpcs: Unexpected end of JSON input"

**Comment by gsherwood** [comment]
I have no idea what that error could be. Given it doesn't come from PHPCS itself, all I can suggest is running PHPCS directly to see if it is working, or opening an issue with the IDE or plugin you are using.
