### ISSUE TITLE
File::findEndOfStatement() not working when passed a scope opener

### ISSUE THREAD

**Issue by webimpress** [squizlabs/PHP_CodeSniffer#1863]
```php
while(true) {}
$v = 1;
```

When `$stackPtr` is set on `while`:
```php
$end = $phpcsFile->findEndOfStatement($stackPtr);
```

then `$end` is the `;` not the `}`.

Do you think it's a bug or desired behaviour?

**Comment by gsherwood** [comment]
That's not desired behaviour, and my first instinct is to say "the end of the statement for scope blocks is always the scope closer" but I'd need to look into it before making a change like that. So I'll put it on 3.3.0 milestone instead of a straight bug-fix release.

**Comment by gsherwood** [comment]
I've fixed this up by doing when I described in my previous comment. Also added some unit tests. Thanks a lot for reporting this.
