### ISSUE TITLE
Not able to exclude or override ElseIfDeclarationSniff

### ISSUE THREAD

**Issue by bryan-kramer** [squizlabs/PHP_CodeSniffer#1895]
Version: 

       ~/.composer/vendor/bin/phpcs --version PHP_CodeSniffer version 3.2.2 (stable) by Squiz (http://www.squiz.net)

I tried excluding the ElseIfDeclarationSniff in my custom rule set:

    <ruleset name="MyStandard">
       <description>My custom coding standard.</description>
       <rule ref="PSR2">
         <exclude name="PSR1.Classes.ClassDeclaration.MissingNamespace" />
         <exclude name="Squiz.Sniffs.ControlStructures.ElseIfDeclarationSniff"/>
         <exclude name="PSR2.Sniffs.ControlStructures.ElseIfDeclarationSniff"/>
      </rule>
    </ruleset>

However, I still get the warning. I searched the composer install directory and found that these two sniffs seem to be the only sniffs responsible for the message. Excluding just one or the other makes no difference.

     1588 | WARNING | [x] Usage of ELSE IF is discouraged; use ELSEIF instead

I also tried the other suggestion which involves setting the severity property:

     <rule ref="Sniffs.ControlStructures.ElseIfDeclarationSniff">
        <severity>0</severity>
     </rule>

However everything that I tried for the ref here (I tried all sorts of combinations of the the words separated by ```.``` resulted in a variation of the error:

     ERROR: Referenced sniff "Sniffs.ControlStructures.ElseIfDeclarationSniff" does not exist

Does anyone know what I might be doing wrong? I just want to get rid of this one warning. Did I miss a sniff?

**Comment by jrfnl** [comment]
Excluding works using `source` codes. You can see the source code of each error message by running PHPCS with the `-s` option set.

The names you are using in the above examples to try and exclude the sniffs are not source codes and therefore are not matched/excluded.

Try this:
```xml
<ruleset name="MyStandard">
   <description>My custom coding standard.</description>
   <rule ref="PSR2">
     <exclude name="PSR1.Classes.ClassDeclaration.MissingNamespace" />
     <exclude name="Squiz.ControlStructures.ElseIfDeclaration"/>
     <exclude name="PSR2.ControlStructures.ElseIfDeclaration"/>
  </rule>
</ruleset>
```

**Comment by gsherwood** [comment]
Run PHPCS with the `-s` command line argument and the sniff code will appear next to each error message. Then you can copy/paste that into an exclude rule.

**Comment by bryan-kramer** [comment]
Thanks for the help. It worked.
