### ISSUE TITLE
Feature request: allow pragma and option to identify files to include

### ISSUE THREAD

**Issue by sirbrillig** [squizlabs/PHP_CodeSniffer#1896]
I work in a code base with hundreds of legacy files and I would like to be able to run phpcs on those files automatically as a commit hook. Unfortunately, work on non-standards-compliant files must continue and until all the files are cleaned up, it's far too noisy to have such a commit hook turned on.

Currently it's possible to _exclude_ a file simply by adding a comment like `// phpcs:ignoreFile` to the top of a file.

What I would like is a way to tell phpcs to run only on files which _include_ a specific comment (the opposite of the default behavior) such as `// phpcs:includeFile`. That way when a file is cleaned up, we could add that comment to protect it from having its standards invalidated in the future.

I know there are other ways of doing this, and perhaps this is an unnecessary feature but I thought I would ask.

**Comment by ht-bs** [comment]
Just as a note: We had a similar problem and solved it by enforcing that on each commit the error count for an already commited file has to be reduced by five. Maybe that is worth a thought.

**Comment by sirbrillig** [comment]
@ht-bs that's a neat idea. May I ask how you did that?

I'm imagining a script which loads the last version of the file, runs it through phpcs to get an error count, then runs phpcs on the new file and compares the error counts. 🤔

**Comment by jrfnl** [comment]
@sirbrillig 

> Currently it's possible to exclude a file simply by adding a comment like // phpcs:ignoreFile to the top of a file.
> 
> What I would like is a way to tell phpcs to run only on files which include a specific comment (the opposite of the default behavior) such as // phpcs:includeFile. That way when a file is cleaned up, we could add that comment to protect it from having its standards invalidated in the future.

Just an idea: what about reversing the process ? I.e. start off by adding `// phpcs:ignoreFile` to all files, and remove it from each file if/when its been cleaned.
That would also mean that once the code base is clean, all the `// phpcs:ignoreFile` comments have been removed along the way.
And you can verify where you are with the clean-up at any point by running `phpcs --ignore-annotations --report=summary` to see which files still contain issues.

**Comment by sirbrillig** [comment]
@jrfnl That's crossed my mind for sure. It's possible and would actually be very convenient once it's done, but (depending on how you count) I have between 13,000 and 22,000 files and that would be a lot of work (or at least a huge commit/tons of commits if it was automated). 😛 I'm just looking for a shortcut.

**Comment by jrfnl** [comment]
@sirbrillig OK, if you're talking shortcuts and don't want to add the `// phpcs:ignoreFiles` to all files to start with, you could just sort this out via the ruleset.
That would mean adding `<exclude-pattern>` directives for everything that should be excluded for now.
And changing those patterns, whenever a part has been cleaned up.

Note: you can use regular expressions for exclude patterns, just know that the `*` will be replaced with `.*`.

```xml
<?xml version="1.0"?>
<ruleset name="Custom ruleset">
	<file>.</file>

	<exclude-pattern>vendor/*</exclude-pattern>
	<exclude-pattern>dirtydir/*</exclude-pattern>
	<exclude-pattern>dirname/dirtysubdir/*</exclude-pattern>
	<exclude-pattern>dirname/mostlycleansubdir/dirty-file\.php$</exclude-pattern>
	...

</ruleset>
```

**Comment by sirbrillig** [comment]
Oh, good idea. That could certainly work. It just occurred to me that I could probably do the reverse as well: use `<file>` directives to only include specific files and directories.

**Comment by jrfnl** [comment]
@sirbrillig Correct, that would be the other way round, but either way would work. You'll probably switch over from one way to the other somewhere along the way in the project ;-)

**Comment by ht-bs** [comment]
@sirbrillig exactly. Using the xml output format this is rather simple to implement in a commit hook script.

**Comment by sirbrillig** [comment]
Cool. I'll mark this as resolved then.
