### ISSUE TITLE
Typehints tokens

### ISSUE THREAD

**Issue by webimpress** [squizlabs/PHP_CodeSniffer#1897]
Hello!
Yesterday I find out that typehint `callable` has token `T_CALLABLE`. Is it ok, right?

I thought that all typehints are strings, but obviously I was wrong, because I've noticed that we have `T_ARRAY_HINT` token for `array`.

Can we have any other tokens for typehints?

**Comment by gsherwood** [comment]
The array type hint is tokenised like that so sniffs that listen for "array" don't get confused by seeing a T_ARRAY. I don't have any plans to add different type hint codes.

**Comment by webimpress** [comment]
@gsherwood Thanks !
