### ISSUE TITLE
PHPCS erroneously identifying docblock as blank lines

### ISSUE THREAD

**Issue by dhensby** [squizlabs/PHP_CodeSniffer#1898]
When running PHPCS against a recent project using latest master (81c901f) the rule enforcing one blank line after the last `use` statement is failing.

The rule is reporting multiple blank lines when the last `use` statement is followed by a docblock.

**Comment by skyzyx** [comment]
Seeing this too, as of recently. I'm using c926d0baca5514f90880ce9892cb383a4c766671 via the `dev-master` designation in Composer (which I need to use for a bugfix that occurred after v3.2.2 was cut).

**Comment by gsherwood** [comment]
Closed by PR #1899
