### ISSUE TITLE
Exclude pattern issue for *.php in PHP Storm Inspections

### ISSUE THREAD

**Issue by tumerov** [squizlabs/PHP_CodeSniffer#1913]
In our project, we use custom coding standard. Some sniffs should not work inside .php files, so we've added `<exclude-pattern>*.php</exclude-pattern>` in our ruleset for these sniffs.

All worked well until we started to use our coding standard together with PHP Storm Inspection tool. Sniffs with exclude-pattern for PHP files were no longer find errors in the template files.

I've investigated its behavior and find out that PHP Storm uses temp directory for files when scans them, so their paths became to be like `/home/username/.phpstorm_helpers/...(some_path).../file.html`
PHPCS finds "`.php`" part of the word "`.phpstorm_helpers`" and ignores .html file.
When I use line end symbol in the pattern ($), all works fine - `<exclude-pattern>*.php$</exclude-pattern>`.

Should this behavior be fixed in PHPCS?

**Comment by jrfnl** [comment]
> Should this behavior be fixed in PHPCS?

No, this is a feature, not a bug. Exclude/ignore patterns are regular expressions, with the one caveat that `*` wildcards will be automatically replaced by `.*`.

Also, see #1592

From the wiki:
> The ignore patterns are treated as regular expressions. If you do specify a regular expression, be aware that `*` is converted to `.*` for the convenience in simple patterns, like those used in the example above. So use `*` anywhere you would normally use `.*`. Also ensure you escape any `.` characters that you want treated as a literal dot, such as when checking file extensions. So if you are checking for `.inc` in your ignore pattern, use `\.inc` instead.

Ref: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#ignoring-files-and-folders

**Comment by tumerov** [comment]
Thank you for your answer.
