### ISSUE TITLE
Generic.ControlStructures.InlineControlStructure fixer moves new PHPCS annotations

### ISSUE THREAD

**Issue by jrfnl** [squizlabs/PHP_CodeSniffer#1932]
This is one of the last few sniffs in which I *know* there are still issues with the PHPCS annotations.

In this case, the fixer moves trailing PHPCS annotations down to subsequent lines which changes their meaning completely.

Example code for the unit tests:
```php
while (!$this->readLine($tokens, $tag)); //phpcs:ignore Standard.Category.Sniff

foreach ($stringParade as $hit)
    $hitParade[] = $hit + 0; // phpcs:disable Standard.Category.Sniff

if ($bar)
    if ($foo) echo 'hi'; /* @phpcs:ignore Standard.Category.Sniff */
```

Expected fix:
```php
while (!$this->readLine($tokens, $tag)) {} //phpcs:ignore Standard.Category.Sniff
}
foreach ($stringParade as $hit) {
    $hitParade[] = $hit + 0; // phpcs:disable Standard.Category.Sniff
}

if ($bar) {
    if ($foo) { echo 'hi'; /* @phpcs:ignore Standard.Category.Sniff */
    }
}
```

Fix currently being made by the sniff as it is now:
```php
while (!$this->readLine($tokens, $tag)) {} //phpcs:ignore Standard.Category.Sniff

foreach ($stringParade as $hit) {
    $hitParade[] = $hit + 0;
} // phpcs:disable Standard.Category.Sniff

if ($bar) {
    if ($foo) { echo 'hi';
    }
} /* @phpcs:ignore Standard.Category.Sniff */
```

Changing conditions which look for `T_COMMENT`, to ones which also take `Tokens::$phpcsCommentTokens` into account, does not really help all that much (the first one is worse, the second better, the third still just as bad):
```php
while (!$this->readLine($tokens, $tag)) { 
//phpcs:ignore Standard.Category.Sniff
}
foreach ($stringParade as $hit) {
    $hitParade[] = $hit + 0; // phpcs:disable Standard.Category.Sniff
}

if ($bar) {
    if ($foo) { echo 'hi';
    }
} /* @phpcs:ignore Standard.Category.Sniff */
```

I've stared at this one way too long by now and haven't figured out a solution yet.

I'm pretty sure the issue is somewhere in these lines:
https://github.com/squizlabs/PHP_CodeSniffer/blob/1dede2176a12f0f0aa93f602984651d8fa22e178/src/Standards/Generic/Sniffs/ControlStructures/InlineControlStructureSniff.php#L220-L239

**Comment by gsherwood** [comment]
I have some hacked up code that may produce better results. But I'm about to rush out, so I
I've thrown the contents of the sniff here in case my machine blows up, or you want to take a look: https://gist.github.com/gsherwood/191464ec17838d3a53bb13bdd3f93dfa

**Comment by gsherwood** [comment]
I've had a shot at a complete fix. It's not 100% consistent but I don't really want to work on this sniff any more - it's taken too many hours already. It is better though, but could use more testing if you are able to help.

Your sample code block is now fixed like this:
```php
while (!$this->readLine($tokens, $tag)) {} //phpcs:ignore Standard.Category.Sniff

foreach ($stringParade as $hit) {
    $hitParade[] = $hit + 0; // phpcs:disable Standard.Category.Sniff
}
if ($bar) {
    if ($foo) { echo 'hi'; /* @phpcs:ignore Standard.Category.Sniff */
    }
}
```

**Comment by jrfnl** [comment]
@gsherwood You're a star! I'll try and have a look at this over the weekend, but have total confidence in your fix ;-)

**Comment by gsherwood** [comment]
Closing this as I haven't had any additional problems reported.
