### ISSUE TITLE
everything I do craps out with this phpcs junk. Mind numbingly frustrating.

### ISSUE THREAD

**Issue by lquessenberry** [squizlabs/PHP_CodeSniffer#1934]
lquessenberry@Lees-Mac-Pro:~/Sites/bdgenetics/drupal/web% composer require squizlabs/php_codesniffer:2.9 --ignore-platform-reqs
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 6 installs, 10 updates, 0 removals
  - Installing squizlabs/php_codesniffer (2.9.0): Downloading (100%)         

                                                                                                                                          
  [ErrorException]                                                                                                                        
  file_put_contents(/Users/lquessenberry/Sites/bdgenetics/drupal/web/vendor/bin/phpcs): failed to open stream: No such file or directory

**Comment by gsherwood** [comment]
I'm not really sure what I can do here as it doesn't look like an error caused by PHPCS itself.

Maybe it is a composer issue? Maybe something specific with your setup. I don't know composer anywhere near well enough to help out.

**Comment by glen-84** [comment]
@lquessenberry Greg puts a lot of work into this (extremely useful) software. The title of this issue is insulting. Please try to show some respect.

**Comment by lquessenberry** [comment]
Pardon my French. I meant no disrespect. I suspect that I was having issues related to NFS file synchronization and permissions. Please excuse my brevity. I will inspect further and get back to you. I appreciate the hard work.
