### ISSUE TITLE
Looking for a couple sniffs [question not bug]

### ISSUE THREAD

**Issue by AliceWonderMiscreations** [squizlabs/PHP_CodeSniffer#1935]
There are two sniffs I would like to add to my xml configuration, if they exist. If they do not I suppose I would have to write them, but...

1) I want a sniff that throws a warning if the boolean strict_types is not declared at the top of the file (preferably to 1 but I suppose someone may have a reason to declare it to 0)

2) I am very stubborn and really enjoy my closing ?> tag, but I would love a sniff that checks for extra white space after the last closing ?> and throws an error. Non-white space should not trigger an error, though I think it is bad practice to mix html and php it is legal - so only excessive white space (more than a single newline) should throw the error.

Do the sniffs I seek exist?

PSR2 actually catches the second but as a side effect of a different sniff.

**Comment by AliceWonderMiscreations** [comment]
Oh and a very big thank you to the developers, I use to hate style standards that don't impact how the code is interpreted - but phpcbf makes it very easy for me to code how I like and am use to and then make it "conform" with a single command and that has been a huge benefit to me, so thank you.

**Comment by gsherwood** [comment]
For strict types:
There is nothing currently included with PHPCS, but I've got a PR on the 3.3.0 roadmap to review and included. Take a look at that sniff and see if you think it will do what you need. If not, throw a comment on there to make sure it will work for you once merged: https://github.com/squizlabs/PHP_CodeSniffer/pull/1771

For end of file whitespace:
Try including `Squiz.WhiteSpace.SuperfluousWhitespace` in your ruleset. It does more than just end of file whitespace though (it does start of file, end of line, and multiple blank lines inside functions) so if you just want the end of file one, try just including `Squiz.WhiteSpace.SuperfluousWhitespace.EndFile` instead (assuming you are on PHPCS version 3).

**Comment by AliceWonderMiscreations** [comment]
I did not get the end of file whitespace sniff to work but I will investigate that further (3.0.2 is what composer.lock indicates I am using)

The suggested #1771 merge looks exactly like what I am looking for with strict_types.

**Comment by gsherwood** [comment]
Thanks for the feedback. I'm not sure what's going on with that whitespace sniff, but let me know if you need any help.

**Comment by tomasfejfar** [comment]
There is already a custom-made sniff in [Slevomat CS for strict types](https://github.com/slevomat/coding-standard#slevomatcodingstandardtypehintsdeclarestricttypes-)
