### ISSUE TITLE
Getting code consistency badge

### ISSUE THREAD

**Issue by dmzoneill** [squizlabs/PHP_CodeSniffer#1945]
Hi,

I would like for this project to be added to https://squizlabs.github.io/PHP_CodeSniffer/analysis/. Following is the project details:

    {
        "name": "php-binance-api",
        "url": "jaggedsoft/php-binance-api",
        "path": "./",
        "ignore": "*/vendors/*",
        "extensions": ""
    }

https://github.com/jaggedsoft/php-binance-api

thanks
Dave.

**Comment by dmzoneill** [comment]
https://github.com/squizlabs/PHP_CodeSniffer/pull/1946

**Comment by gsherwood** [comment]
Here you go: https://squizlabs.github.io/PHP_CodeSniffer/analysis/jaggedsoft/php-binance-api/index.html

**Comment by dmzoneill** [comment]
thanks
