### ISSUE TITLE
Cannot clear "installed_paths" config value

### ISSUE THREAD

**Issue by JanisE** [squizlabs/PHP_CodeSniffer#1972]
I had created a folder with standards for CodeSniffer to use. Now I've changed my mind and don't want to pre-configure any standard paths, but I cannot remove the configured value properly.

I can set the installed_path to any value, also to an empty string, by:
```bash
vendor/bin/phpcs --config-set installed_paths ""
```

But CodeSniffer then tries to load standards from an empty directory and throws an exception `Directory name must not be empty.`

Config deleter seems to have no effect whatsoever:
```bash
phpcs --config-delete installed_paths
```

It just says that `Config value "installed_paths" has not been set`, although I can see the value in `squizlabs/php_codesniffer/CodeSniffer.conf` all right.

[By the code](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Util/Standards.php#L29) it seems that the value should be set to `null` in order to be considered "not set".

**Comment by gsherwood** [comment]
This is working perfectly fine for me, even when I set an invalid value and get a PHPCS error message:
```
$ phpcs --config-show
Using config file: pear/data/PHP_CodeSniffer/CodeSniffer.conf

default_standard: PSR2

$ phpcs --config-set installed_paths /foo/bar
DirectoryIterator::__construct(/foo/bar): failed to open dir: No such file or directory

$ phpcs --config-show
Using config file: pear/data/PHP_CodeSniffer/CodeSniffer.conf

default_standard: PSR2
installed_paths:  /foo/bar

$ phpcs --config-delete installed_paths
Using config file: pear/data/PHP_CodeSniffer/CodeSniffer.conf

Config value "installed_paths" removed successfully; old value was "/foo/bar"

$ phpcs --config-show
Using config file: pear/data/PHP_CodeSniffer/CodeSniffer.conf

default_standard: PSR2
```
Do you get similar output?

**Comment by JanisE** [comment]
Oh, now I see that I tried
```bash
phpcs --config-delete installed_paths
```
instead of
```bash
vendor/bin/phpcs --config-set installed_paths
```
which ran successfully as I have phpcs installed globally, too. When I now run `vendor/bin/phpcs`, it deletes the `installed_paths` config all right.

---

However, about the invalid directory breaking the linting, it's true. Not sure what's the expected behaviour, if it is like this, then there is no problem in that, too.

```
$ vendor/bin/phpcs --config-set installed_paths ../../../.phpcs
Directory name must not be empty.
$ vendor/bin/phpcs app/
PHP Fatal error:  Uncaught RuntimeException: Directory name must not be empty.
[..]
  thrown in /var/www/kstars/vendor/squizlabs/php_codesniffer/src/Util/Standards.php on line 93
````

**Comment by gsherwood** [comment]
> Not sure what's the expected behaviour

I think they've always caused a fatal error, but that's not really a good experience. I've changed the code to just ignore invalid paths, which also means you can distribute a ruleset or conf file with an installed_paths setting that includes paths that might not be valid for all devs. Feels like a win for portability.

Thanks for bringing it to my attention.

**Comment by pixelmultiplo** [comment]
`vendor/bin/phpcs --config-show
Using config file: /Users/marek.maurizio/Projects/remedia-sanity-bridge/vendor/squizlabs/php_codesniffer/CodeSniffer.conf

installed_paths: ../../phpcompatibility/php-compatibility,../../phpcompatibility/phpcompatibility-paragonie,../../phpcompatibility/phpcompatibility-wp,../../phpcsstandards/phpcsextra,../../phpcsstandards/phpcsutils,../../wp-coding-standards/wpcs
`

`> vendor/bin/phpcs

ERROR: Referenced sniff "WordPress.PHP.DisallowShortTernary" does not exist`

After following the instructions on a dozen of places, I'm still getting this.
