### ISSUE TITLE
Tabs must be used to indent lines; spaces are not allowed

### ISSUE THREAD

**Issue by emfluenceindia** [squizlabs/PHP_CodeSniffer#1975]
I have lines indented with Tabs, but PHPCS still reports "Tabs must be used to indent lines; spaces are not allowed".

`32 | ERROR   | [x] Tabs must be used to indent lines; spaces are not allowed
      |         |     (Generic.WhiteSpace.DisallowSpaceIndent.SpacesUsed)`

Sample code snippet:

function __construct() {
[TAB]$this->plugin      = plugin_basename( __FILE__ );
}

Editor: PHPStorm
Coding standard used in project: WordPress Core

**Comment by gsherwood** [comment]
There are extensive tests for this, so I can't imagine a single tab being missed in the file.

Are you able to run PHPCS directly outside PHPStorm? If so, can you run it on a small sample file that causes the error, and use the `-vv` command line argument. That will print info about the ruleset and file contents and let me see what PHPCS thinks it is looking at.

**Comment by emfluenceindia** [comment]
@gsherwood Thank you for your reply. I will do as you said and get back to you asap.

**Comment by luisabritotl** [comment]
![fix phpstorm spaces tabs](https://user-images.githubusercontent.com/29883119/63761784-a4267700-c8b9-11e9-9bef-5641e53f46fe.png)
If you disable this the warning is gone.
