### ISSUE TITLE
New sniff(s) for @var annotations

### ISSUE THREAD

**Issue by glen-84** [squizlabs/PHP_CodeSniffer#1977]
Eclipse (PDT/Zend Studio) and Netbeans use `@var` comments that look like this:

```php
/* @var $object ClassName */
```

(note the single asterisk)

These are not handled by the current doc comment sniffs.

It would also be nice if `Squiz.Commenting.BlockComment.SingleLine` had an option to ignore/allow this format of single-line block comment.

**Comment by TomasVotruba** [comment]
It's better to have united format, that is used by other ides like PHPStorm, or PHP CS Fixer or PHPStan.

```diff
-/* @var $object ClassName */
+/** @var ClassName $object */
```

This might help: https://github.com/Symplify/Symplify/blob/e95b79f34e0525d17be6e3273730ed84125592bf/packages/CodingStandard/README.md#make-param-return-and-var-format-united

**Comment by glen-84** [comment]
@TomasVotruba,

I agree, and the double asterisk syntax now appears to be supported by both Eclipse (PDT/Zend Studio) and Netbeans.

I'll close this issue.
