### ISSUE TITLE
The use of function 0() is forbidden; use () instead

### ISSUE THREAD

**Issue by IvanMiIosevic** [squizlabs/PHP_CodeSniffer#2000]
Hi,
Sorry i'm new to PHPCS and i don't understand this rule

```
    <!-- Ban some functions -->
    <rule ref="Generic.PHP.ForbiddenFunctions">
        <properties>
            <property name="forbiddenFunctions" type="array">
            <element key="sizeof" value="count"/>
                <element key="delete" value="unset"/>
                <element key="print" value="echo"/>
                <element key="is_null" value="null"/>
                <element key="create_function" value="null"/>
            </property>
        </properties>
    </rule>
```
Because of this rule I get :
`` 13 | ERROR | The use of function 0() is forbidden; use () instead (Generic.PHP.ForbiddenFunctions.FoundWithAlternative)``

on this code : 
```
 $data = explode(':', $config['routes'][$request]);
 $controller_name = "Controller\\".$data[0].'Controller';
 $method_name = $data[1].'Action';
```

i need to get the first index on the $data array so its [0] but phpcs doesn't accept this ... how can i select the [0] index of an array ?

**Comment by gsherwood** [comment]
You might be getting that error if you're using that new array property syntax in your ruleset.xml but using a version of PHPCS that doesnt support it. There are no released versions of PHPCS that support that syntax so you need to make sure you are using master.

If you can't use the master version, you'll need to use the old syntax:
```xml
<property name="forbiddenFunctions" type="array" value="sizeof=>count,delete=>unset,print=>echo,is_null=>null,create_function=>null"/>
```

**Comment by IvanMiIosevic** [comment]
well it seems to work now with 
```
    <!-- Ban some functions -->
    <rule ref="Generic.PHP.ForbiddenFunctions">
        <property name="forbiddenFunctions" type="array" value="sizeof=>count,delete=>unset,print=>echo,is_null=>null,create_function=>null"/>
    </rule>
```

Thank you !
