### ISSUE TITLE
Cannot edit rule property

### ISSUE THREAD

**Issue by designermonkey** [squizlabs/PHP_CodeSniffer#2001]
I have the following:

```xml
    <rule ref="PSR2.Methods.FunctionCallSignature.ContentAfterOpenBracket">
        <properties>
            <property name="allowMultipleArguments" value="true" />
        </properties>
    </rule>
```

and I have also tried:

```xml
    <rule ref="PSR2.Methods.FunctionCallSignature">
        <properties>
            <property name="allowMultipleArguments" value="true" />
        </properties>
    </rule>
```

The latter is the name of the sniff file as I don't understand where the `ContentAfterOpenBracket` is even coming from :/

Neither of these allows me to set the property to true.

Any hints as to what's wrong?

**Comment by gsherwood** [comment]
This rule:
```xml
<rule ref="PSR2.Methods.FunctionCallSignature">
    <properties>
        <property name="allowMultipleArguments" value="true" />
    </properties>
</rule>
```
Is used to stop these errors: `Only one argument is allowed per line in a multi-line function call (PSR2.Methods.FunctionCallSignature.MultipleArguments)`

The one I think you are trying to stop is this one: `Opening parenthesis of a multi-line function call must be the last content on the line (PSR2.Methods.FunctionCallSignature.ContentAfterOpenBracket)`

The `PSR2.Methods.FunctionCallSignature` sniff extends the `PEAR.Functions.FunctionCallSignature` sniff, so you can use all of its properties as well (I need to update the docs for this). The properties are documented here: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Customisable-Sniff-Properties#pearfunctionsfunctioncallsignature

But, there is no property that will stop this error from being generated. When the function call exists over multiple lines, both the PSR2 and PEAR sniffs want the parenthesis to be the last content on the line. If you don't care, you can mute the `PSR2.Methods.FunctionCallSignature.ContentAfterOpenBracket` but there is way to have this sniff enforce that the first argument must start on the same line as the opening parenthesis. If you want to mute the error, you'd add this rule to your ruleset, in addition to (and after) the one you already have to set the property value.
```
<rule ref="PSR2.Methods.FunctionCallSignature.ContentAfterOpenBracket">
    <severity>0</severity>
</rule>
```

**Comment by designermonkey** [comment]
That was the one, thanks for the feedback!

**Comment by gsherwood** [comment]
> That was the one, thanks for the feedback!

You're welcome.
