### ISSUE TITLE
Squiz.Functions.FunctionDeclarationArgumentSpacing fixer removes comment between parens when no args

### ISSUE THREAD

**Issue by hchow77** [squizlabs/PHP_CodeSniffer#2006]
Interesting case I hit with SpacingBetween.

I have this code where in place of the parameters, there's a comment there that is meant to show that an arbitrary number of parameters can be passed into the function, as at a later point, it calls into another function with the result of `func_get_args()`:
```
<?php

class Foo {
    public function bar(/*...*/) {
        return call_user_func_array('baz', func_get_args());
    }
}

```
When running Squiz.Functions.FunctionDeclarationArgumentSpacing.SpacingBetween on this, I get an interesting message with PHPCS:
"Expected 0 spaces between brackets of function declaration; 0 found"

When running that rule with the PHPCBF, it ends up removing the comment so it's just `bar()`.

So beside the argument on whether the comment itself should or should not be there, I have some thoughts about this:
- As this is a spacing rule, I would expect the results of fixes to be only whitespace changes, not changes to any non-whitespace, comments included.
- The message is a little odd, given that 0 expected and 0 found sounds like it should not be an error. If anything, this case may deserve a separate message type that is more specific to the change that we expect it to make.

Thanks for the consideration.

**Comment by bobbykjack** [comment]
As an aside, you may want to document the [variable arguments explicitly](http://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.param.pkg.html). Further details [in this stackoverflow question](https://stackoverflow.com/questions/14513356/phpdoc-documenting-a-function-with-a-variable-number-of-arguments).

**Comment by gsherwood** [comment]
The change I've made treats `bar(/*...*/)` like a non-empty definition now, where it previously saw it as empty. So the sniff will enforce the correct number of spaces around the parenthesis instead of reporting that there should be no spaces. If the number of spaces is wrong, that will be corrected when fixing and the comment will be left alone.

Thanks for reporting this.

**Comment by hchow77** [comment]
And thank you for getting in a fix!
