### ISSUE TITLE
Error "Could not find 'phpcbf'. The program may not be installed."

### ISSUE THREAD

**Issue by meshuu** [squizlabs/PHP_CodeSniffer#2007]
Hi guys, I installed PHP_CodeSniffer to perform a beautification on WordPress files in synergy with Atom-Beautify. In the Atom-Beautify settings I set as Default Beautifier PHPCBF.
If I try to perform a beautification, however, it gives me this error message:

"Could not find 'phpcbf'. The program may not be installed.
See phpcbf installation instructions at https://github.com/Glavin001/atom-beautify#beautifiers or go to https://github.com/squizlabs/PHP_CodeSniffer#installation
You can configure Atom Beautify with the absolute path to 'phpcbf' by setting 'Executable - PHPCBF - Path' in the Atom Beautify package settings.
Your program is properly installed if running 'which phpcbf' in your Terminal returns an absolute path to the executable."

I read somewhere that I have to use it with WordPress-Coding-Standards, but honestly I'm not understanding anything anymore. Can someone help me? I'm a novice and working on unordered WordPress files is terrible.
Thanks in advance.

**Comment by gsherwood** [comment]
I'm not really sure if I can help you. I don't maintain the Atom plugin or the WordPress coding standards.

I'd suggest getting in touch with the maintainer of Atom-Beautify as maybe they've seen this issue reported before.

**Comment by meshuu** [comment]
Thanks anyway, I have already written in a post where it seems a similar problem has been addressed. However, it is very likely that the problem is due to incorrect installation. Maybe I'm jumping a few steps.
Let's see what they answer me.
