### ISSUE TITLE
Code Analysis Request

### ISSUE THREAD

**Issue by tudor-rusu** [squizlabs/PHP_CodeSniffer#2016]
Kind request to add our project to https://squizlabs.github.io/PHP_CodeSniffer/analysis/
Our data:
{
        "name": "DSU Report API",
        "url": "civictechro/DSU-reportapp-api",
        "path": "api",
        "ignore": "",
        "extensions": ""
}
Thank you very much.

**Comment by gsherwood** [comment]
Here you go: https://squizlabs.github.io/PHP_CodeSniffer/analysis/civictechro/DSU-reportapp-api/index.html

Thanks

**Comment by tudor-rusu** [comment]
Thank you very much

Tudor Rusu

________________________________
