### ISSUE TITLE
Accept any number of space superior at 2 for indentation

### ISSUE THREAD

**Issue by Paviluf** [squizlabs/PHP_CodeSniffer#2020]
Hello,

I work on project that have 2 or 4 spaces for indentation and I wonder if it's possible to set up phpcs to accept any number of space superior at 2 for indentation ?
If yes how ? If no is it possible to add it please ?

Thanks !

**Comment by gsherwood** [comment]
It's not possible for the included sniffs to accept either 2 or 4 spaces for indentation and I don't think that is an option I would spend time adding as I haven't encountered a standard like that before. So you would need to write a completely custom sniff for indentation checking (not an easy job), or decide on a standard (2 or 4 spaces), or check that manually.

**Comment by Paviluf** [comment]
Thank you. I won't check the indentation but how can I disable this check ?
It will be great if we can have a setting to detect the indentation and check the code accordingly.

**Comment by Paviluf** [comment]
> You'll need to have a ruleset.xml file to define your coding standard, and then exclude the indentation sniff from there. Do you have a ruleset?

I don't have one but I will take a look at this.
