### ISSUE TITLE
OpeningFunctionBraceKernighanRitchie.ContentAfterBrace sniff doesn't properly expand functions that were originally one line

### ISSUE THREAD

**Issue by SamanthaNguyen** [squizlabs/PHP_CodeSniffer#2021]
When enabling the `Generic.Functions.OpeningFunctionBraceKernighanRitchie.ContentAfterBrace` sniff and then running `composer test` as well as `composer fix`, the automatic fix didn't properly expand these functions which were originally on 1 line.

For reference: https://gerrit.wikimedia.org/r/#/c/426726/1/UserStats/includes/UserLevel.php

The original code was:
```php
	public function getLevelName() { return $this->level_name; }
	public function getLevelNumber() { return $this->level_number; }
	public function getNextLevelName() { return $this->next_level_name; }
```

----

When running `composer fix`, it expanded the functions improperly as shown below, which has:
 * mixed tabs and spaces
 * improper indentation
 * improper placement of closing brace
```php
	public function getLevelName() {
 return $this->level_name; }
	public function getLevelNumber() {
 return $this->level_number; }
	public function getNextLevelName() {
 return $this->next_level_name; }
```
When running `composer fix`, it **should've** looked like this below (which I had manually fixed in [patchset 2](https://gerrit.wikimedia.org/r/#/c/426726/1..2/UserStats/includes/UserLevel.php) for this file):

```php
	public function getLevelName() {
		return $this->level_name;
	}

	public function getLevelNumber() {
		return $this->level_number;
	}

	public function getNextLevelName() {
		return $this->next_level_name;
	}
```

**Comment by gsherwood** [comment]
That error code (and the fixer) only checks/fixes one single thing. The rest of your coding standard would be enforcing the rest of the formatting changes. For example, the included PSR2 standard would format the code like this during fixing.

Do you have a larger coding standard?

**Comment by gsherwood** [comment]
> So one of those additional sniffs is interfering with this one?

This sniff *only* checks and fixes the placement of the opening brace. It doesn't touch the closing brace, function indentation, tabs/spaces or anything else. So the MediaWiki standard may have different rules for these things that you don't agree with, or doesn't actually include any checks to enforce them.

If that's the case, you'd need to include more sniffs in your custom coding standard. Maybe try including PSR2 as well and see if that gets your closer.

(Sorry, I don't have time right now to test and customise the MediaWiki standard)
