### ISSUE TITLE
Allman style braces

### ISSUE THREAD

**Issue by scriptburn** [squizlabs/PHP_CodeSniffer#2025]
Is it possible to have braces like allman style?
Basically, forcing something like this on PSR2 standard:

```
if (TRUE)
{
     // Code logic
}
else
{
    // Code Logic
}
```
And

```
public function test()
{
     // Code logic
}
```

**Comment by jrfnl** [comment]
For functions this is already included and enforced in the PSR2 standard and there is also a separate sniff for this `Generic.Functions.OpeningFunctionBraceBsdAllman`.

For control structures (your first example), I don't think there is a sniff available within PHPCS which allows this, so you'd need to write your own sniff to enforce that or find one in an existing external standard.

**Comment by scriptburn** [comment]
I cam across this gist 
https://gist.github.com/gsherwood/9d22f634c57f990a7c64
And i think i will need something like this to extend PSR2 standard and add the application attributes which will make allman style work with control structure, but unable to find which option i need to modify

**Comment by gsherwood** [comment]
PHPCS does not have a sniff that can enforce the braces you want for control structures. None of the included coding standard enforce braces like this and nobody has contributed a sniff to do so yet. There are no options available to enforce this rule.

You might be able to find a sniff to do this in custom PHPCS standards people have written, but I do not know of one personally.

**Comment by Herz3h** [comment]
Is there a doc for how  to extend the PSR2 standard and change braces to Allman style ?

**Comment by mikkorantalainen** [comment]
Any change to incorporate Allman style from https://github.com/Linnk/Allman_CodeSniffer ? The License seems to be compatible.
