### ISSUE TITLE
contradictory PHP coding standard error

### ISSUE THREAD

**Issue by bhumiradixweb** [squizlabs/PHP_CodeSniffer#2026]
If i have 8 line space at 1552 line, getting this error

----------------------------------------------------------------------
 1552 | ERROR | [x] Line indented incorrectly; expected 0 spaces,     |       |     found 8

And if i remove 8 line space, getting this error
----------------------------------------------------------------------
 1552 | ERROR | [x] Closing brace indented incorrectly; expected 8     |       |     spaces, found 0

**Comment by jrfnl** [comment]
Without a code sample and knowing against which standard you are running, there is nothing anyone can do with your report. Please add more information.

**Comment by bhumiradixweb** [comment]
at that line on curly braces `}` and I am using PSR2

**Comment by jrfnl** [comment]
A code sample should be slightly more than just `}`. Someone will need to be able to reproduce the error, so the code and indentation of the surrounding lines is needed too....

**Comment by gsherwood** [comment]
Are you able to provide a code sample I can use to replicate this issue?

**Comment by bhumiradixweb** [comment]
@gsherwood It's fixed. There was an issue in code formatting. Please close ticket and thanks for your help.

**Comment by gsherwood** [comment]
@bhumiradixweb Good news. Thanks for letting me know.
