### ISSUE TITLE
Squiz fixer conflict in file with side effects

### ISSUE THREAD

**Issue by jrfnl** [squizlabs/PHP_CodeSniffer#2033]
The following code sample will give a fixer conflict when the `Squiz` ruleset is run against it as the `Squiz.Classes.ClassDeclaration` sniff demands exactly one blank line after a class, while the `Squiz.WhiteSpace.FunctionSpacing` sniff demands exactly two blank lines before a function.

```php
class MyClass2
{
    var $x;
}

/** ************************************************************************
 * Example with no errors.
 **************************************************************************/
function example() {}
```

This can be prevented from either sniff by checking either that the next non-empty token is a `function` keyword (`ClassDeclaration`) or that the previous non-empty token is a close brace of an OO construct (`FunctionSpacing`) and bowing out if that's the case.

@gsherwood I'm not sure which of the two sniffs should have precedence, i.e. which sniff should be adjusted ? Guidance appreciated.
I'm happy to prepare the PR once it's clear what the desired fix should be.

Also: there are a number of unintentional parse errors in test files where global functions are prefixed with a visibility keyword. Those would need to be fixed too, as otherwise the fixer conflict would still show (previous/next non-empty would be the visibility keyword breaking the fix).

**Comment by gsherwood** [comment]
> @gsherwood I'm not sure which of the two sniffs should have precedence, i.e. which sniff should be adjusted ? Guidance appreciated.

I think I'd get ClassDeclaration to not throw an error if the class is followed by a function. But it probably doesn't matter given this sort of code is unlikely to be encountered anyway, so whatever is easier is fine I think.

**Comment by gsherwood** [comment]
I ran those two sniffs over the test files and they produced fixed content without issue, so I'm not sure if there are any conflicts in the test files. If you find some though, please let me know and I'll fix.

**Comment by jrfnl** [comment]
@gsherwood Thank you! I hadn't gotten round to doing this myself yet.
