### ISSUE TITLE
Potential endless loop in getTokensAsString when used wrong

### ISSUE THREAD

**Issue by edorian** [squizlabs/PHP_CodeSniffer#2042]
Hey,

while writing a custom sniff I made a mistake in not checking the result of findPrevious and found an endless loop in `getTokensAsString` that I'm not sure you want to fix. But I thought I'll write and see.

A sniff containing:
```php
$commentStart = $phpcsFile->findPrevious(T_DOC_COMMENT_OPEN_TAG, $stackPointer);
$commentEnd = $phpcsFile->findPrevious(T_DOC_COMMENT_CLOSE_TAG, $stackPointer);

$content = $phpcsFile->getTokensAsString($commentStart, $commentEnd - $commentStart + 1);
```

Min reproduce of the core issue: 

https://3v4l.org/LuUS9

For reference: https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Files/File.php#L1905

```php
public function getTokensAsString($start, $length, $origContent=false)
    {
        $str = '';
        $end = ($start + $length);
        if ($end > $this->numTokens) {
            $end = $this->numTokens;
        }
        for ($i = $start; $i < $end; $i++) {
            // If tabs are being converted to spaces by the tokeniser, the
            // original content should be used instead of the converted content.
            if ($origContent === true && isset($this->tokens[$i]['orig_content']) === true) {
                $str .= $this->tokens[$i]['orig_content'];
            } else {
                $str .= $this->tokens[$i]['content'];
            }
        }
        return $str;
    }//end getTokensAsString()
```

When calling this with `(false, false)` $end will be set to numTokens but $i will always be false as `false++` is also `false` so it keeps looping until $str exceed the memory limit.

Of course it doesn't make any sense to call this with (false, false) at all and after debugging I've fixed the issue in the code using the phpcs API :) 

Hope this is useful and understandable!
Cheers,
Volker

**Comment by Pierstoval** [comment]
Could be fixed by casting `$start` and `$length` to integers

**Comment by gsherwood** [comment]
> Could be fixed by casting $start and $length to integers

Either that or throwing an exception like a few other methods do. I'm not sure the exception is the best way to go here, but it's another option.
