### ISSUE TITLE
Styling the output of generated HTML

### ISSUE THREAD

**Issue by GrahamLab** [squizlabs/PHP_CodeSniffer#2044]
Hi
From HTML.php

 * Output is in one large HTML file and is designed for you to style with
 * your own stylesheet. It contains a table of contents at the top with anchors
 * to each sniff.

But it is not clear how to make this work and there is nothing in the documentation
Please can someone advise on how this is achieved

**Comment by gsherwood** [comment]
You'd have to take the HTML output and do post-processing to put your own header/footer/stylesheet etc. There are include features to help with this.

**Comment by GrahamLab** [comment]
Thanks
Can you please point out the features you spoke of.
I guess I could also write my own documentor

**Comment by gsherwood** [comment]
> Can you please point out the features you spoke of.

Sorry, I missed a critical word in my comment and didn't realise. I meant to say: There are **_no_** included features to help with this.

My apologies.

**Comment by gsherwood** [comment]
Closing as there isn't any included PHPCS features to help. If you have suggestions, please open a new issue with them. Thanks.
