### ISSUE TITLE
Sniff with T_RETURN_TYPE not triggered at all

### ISSUE THREAD

**Issue by Majkl578** [squizlabs/PHP_CodeSniffer#2049]
Sniffs that are registered for T_RETURN_TYPE are not triggered at all. Therefore sniffs for return type colon spacing do not work.

This completely breaks [Slevomat Coding Standard](https://github.com/slevomat/coding-standard) and [Doctrine Coding Standard](https://github.com/doctrine/coding-standard).

https://travis-ci.org/doctrine/coding-standard/builds/389215937
downstream tracking issue for PHPCS 3.3: https://github.com/slevomat/coding-standard/issues/360

**Comment by jrfnl** [comment]
Please read the changelog for PHPCS 3.3.0 and issue https://github.com/squizlabs/PHP_CodeSniffer/issues/1527 for the discussion around this.

**Comment by Majkl578** [comment]
Sorry, I really have no words if you truly think BC breaks like this are ok in a minor release. :(
