### ISSUE TITLE
Ignore missing @return tag on void methods

### ISSUE THREAD

**Issue by player259** [squizlabs/PHP_CodeSniffer#2051]
I want to ignore missing `@return` tag when method return type is void

Currently I have error
`Missing @return tag in function comment (Squiz.Commenting.FunctionComment.MissingReturn)`

Is there way to achieve this?

**Comment by dereuromark** [comment]
You can just exclude certain parts, e.g.

```xml
    <rule ref="SlevomatCodingStandard.TypeHints.TypeHintDeclaration">
        <exclude name="SlevomatCodingStandard.TypeHints.TypeHintDeclaration.MissingTraversableParameterTypeHintSpecification"/>
        <exclude name="SlevomatCodingStandard.TypeHints.TypeHintDeclaration.MissingTraversablePropertyTypeHintSpecification"/>
        <exclude name="SlevomatCodingStandard.TypeHints.TypeHintDeclaration.MissingTraversableReturnTypeHintSpecification"/>
        <exclude name="SlevomatCodingStandard.TypeHints.TypeHintDeclaration.UselessParameterAnnotation"/>
        <exclude name="SlevomatCodingStandard.TypeHints.TypeHintDeclaration.UselessDocComment"/>
    </rule>
```

**Comment by player259** [comment]
Currently PhpStorm generates this for regular method
```
    /**
     * @param QueryBuilder $qb
     *
     * @return string
     */
    protected function getRootEntityName(QueryBuilder $qb): string
    {
```

And no return tag on void
```
    /**
     * @param QueryBuilder $qb
     * @param array        $filter
     *
     * @throws ValidationException
     */
    public function apply(QueryBuilder $qb, array $filter): void
```
It is suitable for me, `@return void` feels unnecessary

I want to leave checking return tag, but make it optional if it is void.

**Comment by dereuromark** [comment]
" feels unnecessary"
IMO you shouldnt care about it if it can be autoadded via sniff. All works fine then.

**Comment by player259** [comment]
Autofix doesn't available for `Squiz.Commenting.FunctionComment.MissingReturn`
So there is no way to implement such feature?

**Comment by player259** [comment]
Wow, thanks!

**Comment by gsherwood** [comment]
Closing as question has been answered. Thanks @dereuromark.
