### ISSUE TITLE
Blank line required before tag even if comment contains only one line

### ISSUE THREAD

**Issue by player259** [squizlabs/PHP_CodeSniffer#2052]
I want to make descriptions in docblock optional, so disabled `Generic.Commenting.DocComment.MissingShort`.

Now this code
```
    /**
     * @var EntityManagerInterface $em
     */
    protected $em;
```
produces `There must be exactly one blank line before the tags in a doc comment (Generic.Commenting.DocComment.SpacingBeforeTags)`

It doesn't work without description

**Comment by dereuromark** [comment]
You can just exclude certain parts, e.g.

```xml
    <rule ref="SlevomatCodingStandard.TypeHints.TypeHintDeclaration">
        <exclude name="SlevomatCodingStandard.TypeHints.TypeHintDeclaration.MissingTraversableParameterTypeHintSpecification"/>
        <exclude name="SlevomatCodingStandard.TypeHints.TypeHintDeclaration.MissingTraversablePropertyTypeHintSpecification"/>
        <exclude name="SlevomatCodingStandard.TypeHints.TypeHintDeclaration.MissingTraversableReturnTypeHintSpecification"/>
        <exclude name="SlevomatCodingStandard.TypeHints.TypeHintDeclaration.UselessParameterAnnotation"/>
        <exclude name="SlevomatCodingStandard.TypeHints.TypeHintDeclaration.UselessDocComment"/>
    </rule>
```

**Comment by gsherwood** [comment]
Your sample code produces both the `MissingShort` and `SpacingBeforeTags` errors messages. You've only disabled one, so the other one is still going to show up.

I suggest disabling the other one as well.

**Comment by dereuromark** [comment]
SpacingBeforeTags should only be relevant though if there is any text before the tags :)
If they are already on line 1 there should be no such error.

**Comment by gsherwood** [comment]
> SpacingBeforeTags should only be relevant though if there is any text before the tags :)

Actually, making this change would be helpful for times when you don't want to always mute the SpacingBeforeTags message, so I think you're right. Worth looking into.

**Comment by gsherwood** [comment]
I've made this change. The sample code from the original comment will now only produce a `MissingShort` error message, making it easier to disable this error code and make short descriptions optional.

**Comment by yssambare12** [comment]
Hi I also got something like the same error 
_There must be exactly one blank line before the tags in a doc comment phpcs_

what's the solution to this?
