### ISSUE TITLE
PHPCBF hangs fixing attached file

### ISSUE THREAD

**Issue by paulschreiber** [squizlabs/PHP_CodeSniffer#2060]
### config
macOS 10.12.6 (16G1408)
PHPCS 3.3.0
PHP 7.2.2

### file
[idna_convert.class.php.zip](https://github.com/squizlabs/PHP_CodeSniffer/files/2099129/idna_convert.class.php.zip)

### summary
Running this command:
```
phpcbf --standard=WordPress-VIP idna_convert.class.php
```

causes `phpcbf` to use 90% CPU for several minutes. The command never finished. File is 113K.

**Comment by paulschreiber** [comment]
`phpcs` processes this file in ~25s.

**Comment by jrfnl** [comment]
@paulschreiber Just had a quick look at the file and I suspect that the already open PR #2056 will fix this, but I haven't tested it yet.
If you'd be willing to test it, that would awesome!

The file contains a huge array with layouts like this:
```php
            ('map_nothing' => array
                    (0xAD, 0x34F, 0x1806, 0x180B, 0x180C, 0x180D, 0x200B
                    ,0x200C, 0x200D, 0x2060, 0xFE00, 0xFE01, 0xFE02, 0xFE03
                    ,0xFE04, 0xFE05, 0xFE06, 0xFE07, 0xFE08, 0xFE09, 0xFE0A
                    ,0xFE0B, 0xFE0C, 0xFE0D, 0xFE0E, 0xFE0F, 0xFEFF
                    )
```

The comma at the start of these lines is the problematic part which causes two sniffs to conflict. This is exactly the issue which the PR addresses.

**Comment by paulschreiber** [comment]
That doesn't seem to be working. I tried:
```
$ git clone https://github.com/squizlabs/PHP_CodeSniffer.git
$ cd PHP_CodeSniffer/
$ git remote add jrfnl https://github.com/jrfnl/PHP_CodeSniffer.git
$ git fetch jrfnl
$ git co -b feature/generic-functioncallargumentspacing-fixer-conflict
$ php bin/phpcbf --config-set installed_paths /Users/paul/.dev/WordPress-Coding-Standards
$ php bin/phpcbf --standard=WordPress-VIP ~/Downloads/idna_convert.class.php 
```

I let it run for 3 minutes before I pressed `^C` to kill it.

**Comment by gsherwood** [comment]
I've pushed a fix for the issue I outlined in my previous comment. I can now take the original sample file and fix it using phpcbf with the included standards. It would be great if you could try that fix and see if it helps.

**Comment by paulschreiber** [comment]
I pulled master (and confirmed it contains e39a44a). I again ran:
```
$ php bin/phpcbf --standard=WordPress-VIP ~/Downloads/idna_convert.class.php
```
…and waited three minutes. (MBP, 2.5 GHZ i7, 16 GB RAM)

@gsherwood How long did `phpcbf` take to clean idna_convert.class.php?

**Comment by gsherwood** [comment]
I took a look at the sample file using the WordPress-VIP standard and it appears there is a problem with the WordPress.Arrays.ArrayIndentation sniff and commented out array indexes. The following sample code will cause PHPCBF to reach max loops:
```php
<?php
    
$NP = array
    'replacemaps' => array
            (0x41 => array(0x61)
            ,0x33C1  => array(0x6D, 0x3C9) /*
            ,0x33C2  => array(0x61, 0x2E, 0x6D, 0x2E) */
            ,0x33C3  => array(0x62, 0x71)
            )
);
```

**Comment by gsherwood** [comment]
> Do you want to file a bug on WPCS, or do you want me to do it?

Sorry, that was a progress comment. I didn't see your previous comment so thought I was working on this alone today :)

I'm currently looking at the included standards to see if I can replicate that issue now that I've got a smaller piece of code. That will let me know if this is a problem with a core sniff being extended or an entirely new sniff in WordPress. So leave it with me for now.

**Comment by gsherwood** [comment]
I've found a conflict between `Squiz.WhiteSpace.FunctionSpacing` and `Squiz.WhiteSpace.MemberVarSpacing` on this code:
```php
<?php
class Foo
{


    private function foo()
    {
    }

    private $bar = false;
}
```
But it doesn't have anything to do with the WordPress issue I don't think. I will resolve this conflict and re-test to confirm.

**Comment by gsherwood** [comment]
I fixed my conflict and now PHPCBF no longer hangs on the file. But there is still a problem fixing arrays with the comma on the front of the value. I'll see if I can fix that before saying this is a WordPress CS issue.

**Comment by gsherwood** [comment]
I fixed the problem I found fixing arrays with leading commas. I can now fix the sample file using the included standard for PHPCS. It takes 14 passes, but it gets the job done and no longer creates any parse errors:
```
$ php bin/phpcbf -v temp.php
Registering sniffs in the PHP_CodeSniffer standard... DONE (62 sniffs registered)
Creating file list... DONE (1 files in queue)
Changing into directory .
Processing temp.php [PHP => 27802 tokens in 2706 lines]... DONE in 472ms (5583 fixable violations)
        => Fixing file: 0/5583 violations remaining [made 14 passes]... DONE in 10.34 secs
	=> Fixed file written to temp.php

PHPCBF RESULT SUMMARY
----------------------------------------------------------------------
FILE                                                  FIXED  REMAINING
----------------------------------------------------------------------
temp.php                                              5583   515
----------------------------------------------------------------------
A TOTAL OF 5583 ERRORS WERE FIXED IN 1 FILE
----------------------------------------------------------------------

Time: 10.93 secs; Memory: 78Mb
```
I also tested the fix by @jrfnl and can confirm that also works:
```
$ php bin/phpcbf -v temp.php --standard=WordPress-VIP
Registering sniffs in the WordPress VIP standard... DONE (86 sniffs registered)
Creating file list... DONE (1 files in queue)
Changing into directory .
Processing temp.php [PHP => 27802 tokens in 2706 lines]... DONE in 7.18 secs (12241 fixable violations)
        => Fixing file: 0/12241 violations remaining [made 8 passes]... DONE in 81.72 secs
	=> File was overwritten

PHPCBF RESULT SUMMARY
-----------------------------------------------------------------------------
FILE                                                         FIXED  REMAINING
-----------------------------------------------------------------------------
/Users/gsherwood/Sites/Projects/PHP_CodeSniffer/temp.php     12241  73
-----------------------------------------------------------------------------
A TOTAL OF 12241 ERRORS WERE FIXED IN 1 FILE
-----------------------------------------------------------------------------

Time: 1 mins, 29 secs; Memory: 90.01Mb
```
So I'm going to close this now. Thanks for reporting and testing.
