### ISSUE TITLE
PSR-2 special if indenting with function

### ISSUE THREAD

**Issue by TakeMeNL** [squizlabs/PHP_CodeSniffer#2069]
When running PHP CodeSniffer with PSR2 on the code the formatting is different then then the formatting of PHPStorm.
I have have search and tried to fix it, but either i can't find it or its a "not implemented feature"
Attached the code style

What is the expected result? (As of what PHP CodeFixer says)
```php
if ($method === 'POST' && in_array(
    $request->getMediaType(),
    ['application/x-www-form-urlencoded', 'multipart/form-data']
)) {
    // parsed body must be $_POST
    $request = $request->withParsedBody($_POST);
}
```
What happens instead? (As of what PHPStorms says, this should be the correct PSR-2 formatting)
```php
if ($method === 'POST' && in_array(
        $request->getMediaType(),
        ['application/x-www-form-urlencoded', 'multipart/form-data']
    )) {
    // parsed body must be $_POST
    $request = $request->withParsedBody($_POST);
}
```

Output of PHP CodeSniffer
```
----------------------------------------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 3 LINES
----------------------------------------------------------------------------------------------------
 105 | ERROR | [x] Multi-line function call not indented correctly; expected 4 spaces but found 8
 106 | ERROR | [x] Multi-line function call not indented correctly; expected 4 spaces but found 8
 107 | ERROR | [x] Multi-line function call not indented correctly; expected 0 spaces but found 4
----------------------------------------------------------------------------------------------------
PHPCBF CAN FIX THE 3 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------------------------------------
```

As i first thought this was a PHPStorm formatting issue the folks there don't think it is. Ref to issue: https://youtrack.jetbrains.com/issue/WI-42618
They think PHPStorm follows the PSR-2 norm is this case.

Running PHPCS with this config
```
<?xml version="1.0" encoding="UTF-8"?>
<ruleset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/squizlabs/PHP_CodeSniffer/master/phpcs.xsd"
         name="Coding standard"
>
    <description>Coding standard</description>

    <!-- Paths to check -->
    <file>framework</file>
    <file>addons</file>
    <file>components</file>
    <exclude-pattern>**/vendor/*</exclude-pattern>

    <arg name="basepath" value="."/>
    <arg name="cache" value=".php_cs.cache"/>
    <arg name="colors" />
    <arg value="p"/>

    <!-- Include the whole PSR2 standard -->
    <rule ref="PSR2"/>

    <!-- Include some sniffs from other standards that don't conflict with PEAR/PSR2 -->
    <rule ref="Generic.Arrays.DisallowLongArraySyntax"/>
</ruleset>
```

What is the correct formatting?

**Comment by gsherwood** [comment]
This is pretty much the same conversation as the one here: https://github.com/squizlabs/PHP_CodeSniffer/issues/2010

The summary is: PHPCS doesnt change indent rules for function calls just because the call is inside an IF condition because the PSR-2 standard doesn't define those rule differently. So I think the PHPCS indent is correct.

**Comment by TakeMeNL** [comment]
Hey there, thanks for the reply.
Because off the differance between IDE and this tool i raised the issue to see what is correct.
One of the Jetbrains team came with this:
```
if (
    $method === 'POST' && in_array(
        $request->getMediaType(), ['application/x-www-form-urlencoded', 'multipart/form-data']
    )) {
    // parsed body must be $_POST
}
```

As far i can find there is not really a rule for this because of the special case. Personally agree with CS on the indent makes more sense and better readability

**Comment by gsherwood** [comment]
> One of the Jetbrains team came with this:

Or, if you want to mix in some of the PEAR standard, you could do this:
```php
if ($method === 'POST'
    && in_array(
        $request->getMediaType(),
        ['application/x-www-form-urlencoded', 'multipart/form-data']
    )
) {
    // parsed body must be $_POST
    $request = $request->withParsedBody($_POST);
}
```
That's compatible with the PSR2 rules as well and is how I personally do multi-line IF statements.
