### ISSUE TITLE
Declare File::$tokenizerType property ?

### ISSUE THREAD

**Issue by jrfnl** [squizlabs/PHP_CodeSniffer#2079]
The constructor of the `File` class sets a `tokenizerType` property, however, this property is not declared at the top of the class.
Is there any particular reason why it's not ?

https://github.com/squizlabs/PHP_CodeSniffer/blob/ccb2118232a8cb919e75e60a4ea9acf3385df14f/src/Files/File.php#L229-L234

**Comment by gsherwood** [comment]
I think that's just a mistake. Thanks for picking it up.
