### ISSUE TITLE
"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"

### ISSUE THREAD

**Issue by CMalvika** [squizlabs/PHP_CodeSniffer#2087]
Travis is failing on this issue for below files:

vendor/squizlabs/php_codesniffer/src/Tokenizers/Tokenizer.php:637
vendor/squizlabs/php_codesniffer/src/Files/File.php:1341

**Comment by jrfnl** [comment]
This has already been fixed via https://github.com/squizlabs/PHP_CodeSniffer/pull/2086. I suggest closing this issue.

**Comment by CMalvika** [comment]
@jrfnl i guess the version isn't released yet!

**Comment by jrfnl** [comment]
@CMalvika Correct, the fix will be included in the upcoming `3.3.1` release.

**Comment by OneCodeMonkey** [comment]
face the same question too.

**Comment by jrfnl** [comment]
@OneCodeMonkey As stated above: upgrade your PHPCS version to 3.3.1 or higher.

**Comment by anshulsh13m** [comment]
You install the Latest PHPCS version (above 3.3.x).

Try the following command

uninstall the PHPCS
**sudo apt-get autoremove --purge php-codesniffer**

Install the new  version of PHPCS
**sudo apt install php-pear
sudo apt-get update -y
sudo pear install PHP_CodeSniffer-3.5.4**
