### ISSUE TITLE
How to align PHP code with html code

### ISSUE THREAD

**Issue by muuvmuuv** [squizlabs/PHP_CodeSniffer#2089]
I posted the same on https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3702

I‘m trying to find a solution to format my PHP files but without losing the indention of the HTML. I thought one time I got it working with **PHP_CodeSniffer**, but I can not remember what I‘ve done exactly.

Is this possible with **PHP_CodeSniffer** or does anyone know a project that can handle mixed content?

**Comment by gsherwood** [comment]
PHPCS uses your opening and closing tags to set indents so that you can indent your HTML the way you like. It wants your PHP code to be aligned to where you place your opening PHP tag. The following code is an example:
```php
<html>
    <head>
        <title><?php echo $title; ?></title>
    </head>
    <body>
        <div class="menu">
            <ul>
            <?php
            $items = getMenuItems();
            foreach ($items as $name => $link) {
                ?>
                <li class="menu-item"><a href="<?php echo $link; ?>"><?php echo $name; ?></a></li>
                <?php
            }
            ?>
            </ul>
        </div>
    </body>
</html>
```

**Comment by muuvmuuv** [comment]
@gsherwood I‘m sorry, I where on vacation. I‘ll look into this again later at work.  

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by muuvmuuv** [comment]
Ok that work. It seems my Editor is just not formatting both (html and php) so it is a issue with VSCode. Thanks anyway! I just thought it was a problem with PHPCS 😁
