### ISSUE TITLE
Suggestions to improve readability of the `info` report

### ISSUE THREAD

**Issue by jrfnl** [squizlabs/PHP_CodeSniffer#2102]
Example of an `Info` report:
```
Control structure defined inline: no [25600/25600, 100%]

EOL char: \n [1260/1261, 99.92%]
        \r\n => 1 (0.08%)

Line indent: tabs [339424/339431, 100%]
        spaces => 4 (0%)
        mixed => 3 (0%)
```

When I look at this, I personally find the metrics with more than one "answer" substantially harder to read because of the current format.

For a single line - 100% - entry, the current format is fine.

For multiline entries, the current format makes the first entry hard to distinguish.

There are a number of readability improvements which come to mind for multi-line metrics:
1. Start the first metric value on a new line.
2. Align the arrows, and by extension the counts, of the metrics.
3. Keep the totals with the metric name or as a `Totals` line underneath it.
4. Right align the counts.
5. Add thousands separators to the counts.
6. Right align the percentages.

If these changes were made, the report would look like this:
```
Control structure defined inline: no [25600/25600, 100%]

// Variant 1 of suggestion 3.
EOL char: [1,261]
        \n   => 1,260 (99.92%)
        \r\n =>     1 (0.08%)

// Variant 2 of suggestion 3
Line indent:
        tabs   => 339,424 (100%)
        spaces =>       4   (0%)
        mixed  =>       3   (0%)
        -----------------
        total  => 339,431 (100%)
```

:point_right: @gsherwood Would you be open to these changes ?

If I understand things correctly, the CMS reports published in the `gh-pages` branch are based on the `Info` report. Would a change like this impact that report generation ?

**Comment by gsherwood** [comment]
> If I understand things correctly, the CMS reports published in the gh-pages branch are based on the Info report. Would a change like this impact that report generation ?

The coding standard reports use a custom reporting class, so any changes to this report format wouldn't impact them.

> Would you be open to these changes ?

This report was pretty much the minimal amount of work I could do to expose the metrics that I was recording for the coding standards reports project, so I'm definitely open to improving it. I quite like variant 2 in your example. Did you have a preference?

My other suggestion would be to stop it reporting `0%` for metrics and report `<0.01%` instead because the inaccuracy gets to me :)

**Comment by jrfnl** [comment]
> My other suggestion would be to stop it reporting 0% for metrics and report <0.01% instead because the inaccuracy gets to me :)

Yup, that sounds like a good addition.

I'll have a go and see how I fare with sorting this out.
