### ISSUE TITLE
Breaking changes in 3.3.1 patch release?

### ISSUE THREAD

**Issue by legoktm** [squizlabs/PHP_CodeSniffer#2108]
As someone who still needs to care about HHVM support, I understand why others are ready to drop it, but I'm pretty surprised that a breaking change of dropping HHVM support happened in a patch release.

**Comment by gsherwood** [comment]
Yeah, it's unfortunate. But given how little time I get to work on PHPCS, I can't really keep going with broken HHVM support and I don't know when a major release will be available. The two bugs I reported to the project in March still haven't been fixed, and things aren't going to get easier for me with the dropping on PHP5 support and the vision of a "less compatible PHP 7 runtime".

I'm going to close this as it isn't an actual issue I can resolve in any way. If I was getting paid to work on PHPCS, I could have put in the hours to keep support. But I'm not, so I can't.
