### ISSUE TITLE
Verify that phpcs returns a valid json object

### ISSUE THREAD

**Issue by wills-web** [squizlabs/PHP_CodeSniffer#2111]
When performing any kind of edit, save, etc, an error window appears in the bottom right of VS Code, contains the following message.

`phpcs: Unknown error ocurred. Please verify that C:\Users\<username>\AppData\Roaming\Composer\vendor\bin\phpcs.bat --report=json -q --encoding=UTF-8 --error-severity=5 --warning-severity=5 --stdin-path=C:\Clones\<projectname>\app\Lib\PoGenerator.php - returns a valid json object.`

`<projectname>` and `<username>` fields have been omitted.

I have used a global installation and have run the following commands, as well as installed the VS Code plugin.
`composer global require squizlabs/php_codesniffer`
`phpcs --version`
`phpcs --config-set default_standard PSR2`

When running phpcs commands, I am shown a warning that `openssl` is already running.

**Comment by gsherwood** [comment]
I'm not sure how the VS Code integration works as it's not part of this project, but have you tried running PHPCS directly and seeing if you get valid JSON output or not?

Also, PHPCS does not use openssl, so I don't know why that error would be reported.

**Comment by wills-web** [comment]
Running PHPCS directly through Git Bash in a Laravel project Controller returns the following.
`$ phpcs DashboardController.php
PHP Warning:  Module 'openssl' already loaded in Unknown on line 0

FILE: C:\Clones\<projectname>\app\Http\Controllers\DashBoardController.php
--------------------------------------------------------------------------------------
FOUND 4 ERRORS AND 6 WARNINGS AFFECTING 10 LINES
--------------------------------------------------------------------------------------
   1 | ERROR   | [x] End of line character is invalid; expected "\n" but found "\r\n"
  33 | WARNING | [ ] Line exceeds 120 characters; contains 124 characters
  75 | WARNING | [ ] Line exceeds 120 characters; contains 142 characters
  83 | ERROR   | [x] Whitespace found at end of line
  87 | ERROR   | [x] Opening brace should be on a new line
  98 | ERROR   | [x] Opening brace should be on a new line
 120 | WARNING | [ ] Line exceeds 120 characters; contains 146 characters
 125 | WARNING | [ ] Line exceeds 120 characters; contains 129 characters
 127 | WARNING | [ ] Line exceeds 120 characters; contains 125 characters
 144 | WARNING | [ ] Line exceeds 120 characters; contains 130 characters
--------------------------------------------------------------------------------------
PHPCBF CAN FIX THE 4 MARKED SNIFF VIOLATIONS AUTOMATICALLY
--------------------------------------------------------------------------------------

Time: 145ms; Memory: 6Mb`

Is it safe to assume that the issue is being caused by the VS Code plugin, as it scans the files fine here?

Thanks for your help.

**Comment by gsherwood** [comment]
> PHP Warning:  Module 'openssl' already loaded in Unknown on line 0

That shouldn't be happening, but that's not PHPCS itself causing that error. Maybe there is a duplicate module line in php.ini? (maybe this: https://stackoverflow.com/questions/36675348/xampp-warning-module-openssl-already-loaded-in-line-0)

This might be output when running PHPCS through VS Code as well, causing the JSON output to be corrupted. If you find the source of this problem, you may fix your VS Code issue as well.

**Comment by wills-web** [comment]
By disabling the openssl extension in my php.ini, normal function resumed. Thanks for your help.

**Comment by gsherwood** [comment]
Good news. Thanks for getting back to me.
