### ISSUE TITLE
Failed to download squizlabs/php_codesniffer from dist: Invalid argument 

### ISSUE THREAD

**Issue by limabibi** [squizlabs/PHP_CodeSniffer#2112]
Hello,

I'm trying to download the squizlabs / php_codesniffer through composer.json file for the third time, but it's returning this message:

Failed to download squizlabs / php_codesniffer from dist: Invalid argument (C: \ Users \ web3 \ Desktop \ newphpp-master-new \ vendor / squizlabs / php_codesniffer / 5136d02caa2d9a8d5f791fd7c1aa9e)

Excerpt from require:

require-dev ": {
         "squizlabs / php_codesniffer": "^ 2.8",
         "phpunit / phpunit": "^ 5.7",
         "scrutinizer / ocular": "^ 1.3",
         "phpmd / phpmd": "dev-master",
         "sebastian / phpcpd": "^ 3.0"
     },

Could you please help me?

Thanks.

**Comment by gsherwood** [comment]
I don't think this has anything to do with PHPCS itself. It looks like a composer problem, but hard to tell without a backtrace of that error message.

I did some searching but all I could find was someone saying that the error means that the file path is too long (more than 77 chars apparently) or it contains special characters. I don't see any special chars, but I'm not sure why a long file path would cause any errors and I don't see how 77 chars could be considered long anyway. So I'm not sure how to help.

All I can suggest is asking on the composer project as you'll find people there that know composer and might be able to track down an error message.
