### ISSUE TITLE
PSR2.Namespaces.NamespaceDeclaration has changed behaviour for namespace scopes

### ISSUE THREAD

**Issue by fenetikm** [squizlabs/PHP_CodeSniffer#2117]
Before the change made in https://github.com/squizlabs/PHP_CodeSniffer/issues/2095 / https://github.com/squizlabs/PHP_CodeSniffer/commit/8e2b57047d6fe049da1178d7074f6f4e71469141 the following would be picked up:

```php
namespace FirstNamespace{
  /**
   * FirstClass for the test.
   */
  class FirstClass{

  }
}
```

as there needing to be a blank line between the `namespace` line and the start of the block comment, thus throwing `PSR2.Namespaces.NamespaceDeclaration.BlankLineAfter`.

**Comment by fenetikm** [comment]
Thanks for the useful feedback and detail. I too would have thought a blank line _after_ the complete block would have made sense.

This came about from a PR to the Drupal coder module which has some tests that check for namespaces that are bracketed... and in the many years that I have worked on Drupal I have never seen such a thing in the wild. They may have been a left over from very old Drupal versions but I am just guessing.

I think I will just update the tests in this other PR to be more in line with the tests in php code sniffer. 

Thanks again for your great work on PHP_CodeSniffer.

**Comment by gsherwood** [comment]
No problem. Thanks for the feedback.
