### ISSUE TITLE
Don't truncate path

### ISSUE THREAD

**Issue by MichaelMallett** [squizlabs/PHP_CodeSniffer#2124]
Is there a switch to stop the path from being truncated? Using full report or summary, I just get a list that looks like this, when I could really use the full (relative or absolute) path.

...c/Controller/FooEntityAutocompleteController.php  2       0
...utocomplete/src/FooEntityAutocompleteMatcher.php  1       3
...e/src/Routing/FooAutocompleteRouteSubscriber.php  2       0
...ntSubscriber/BaiduAnalyticsResponseSubscriber.php  4       0
...Plugin/Field/FieldFormatter/FooBlogFormatter.php  7       0
..._blog/Tests/Controller/FooBlogControllerTest.php  0       1
...stom/Foo_clear_cache/src/Form/ClearCacheForm.php  0       1
...rPlugin/FooDefaultProductLinksCKEditorButton.php  4       4
...ct_links/src/Plugin/Filter/FilterProductLinks.php  21      13
...t_links/tests/src/Unit/FilterProductLinksTest.php  5       6

**Comment by MichaelMallett** [comment]
Found the answer in here

https://pear.php.net/manual/en/package.php.php-codesniffer.config-options.php

`phpcs --config-set report_width 120`

**Comment by jrfnl** [comment]
@MichaelMallett You may also find the `basepath` option useful: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Usage
