### ISSUE TITLE
SemicolonSpacingSniff deletes semicolon

### ISSUE THREAD

**Issue by mambax7** [squizlabs/PHP_CodeSniffer#2130]
The SemicolonSpacingSniff deletes semicolon:

original code:
```php
function GetFolders($currentFolder, $type)
{
    $trust_mode = $type != 'Image' ;

    // Array that will hold the folders names.
    $aFolders    = array() ;

    $sServerDir = $trust_mode ? FCK_TRUSTUPLOAD_PATH . $currentFolder : FCK_UPLOAD_PATH . $currentFolder ;
    $oCurrentFolder = opendir($sServerDir) ;

    while (($sFile = readdir($oCurrentFolder)) !== false) {
        if ($sFile != '.' && $sFile != '..' && is_dir($sServerDir . $sFile)) {
            $aFolders[] = '<Folder name="' . ConvertToXmlAttribute($sFile) . '" />' ;
        }
    }

    closedir($oCurrentFolder) ;

    // Open the "Folders" node.
    echo "<Folders>" ;
    
    sort($aFolders) ;
    foreach ($aFolders as $sFolder) {
        echo $sFolder ;
    }

    // Close the "Folders" node.
    echo "</Folders>" ;
}
```

converted code:
![image](https://user-images.githubusercontent.com/613686/44334427-7b1a0d80-a43f-11e8-877f-19ad7a65c116.png)

**Comment by jrfnl** [comment]
@mambax7 Which standard are you using ?
I've tried to reproduce the issue with just the `Squiz.WhiteSpace.SemiColonSpacing` sniff and the fixer works just fine, so it must be a combination of sniffs which is causing the issue.

**Comment by mambax7** [comment]
I was using https://github.com/lmc-eu/php-coding-standard

**Comment by jrfnl** [comment]
In that case, as it's based on EasyCodingStandard, @TomasVotruba might be better placed to see what is wrong.

**Comment by TomasVotruba** [comment]
@symplify is the correct place. @mambax7 Please provide full CLI command and also try the sniff standalone in config

**Comment by mambax7** [comment]
This is what I was using
[lmc.zip](https://github.com/squizlabs/PHP_CodeSniffer/files/2303779/lmc.zip)
I copied it to ECS config folder and used from there:
\vendor\symplify\easy-coding-standard\config\

**Comment by TomasVotruba** [comment]
Report at @symplify, so we don't polute this issue

**Comment by mambax7** [comment]
Done
