### ISSUE TITLE
Is it possible to append multiple runs to a code report?

### ISSUE THREAD

**Issue by MichaelMallett** [squizlabs/PHP_CodeSniffer#2135]
I'm trying to run phpcs on circleci for all the files in a pull request only (due to some legacy errors that we're working through). This means that I'm basically using xargs to call phpcs multiple times, and as such I can't generate a report as I would like as it generates multiple.

git --no-pager diff --diff-filter=AM --name-only $(git log --format="%H" -n 1)..origin/develop | xargs -I{} bash -c 'if test -f {} ; then vendor/bin/phpcs --standard=Drupal --extensions=php,module,inc,install,test,profile,theme,info --ignore=md {} ; fi'

One workaround might be to copy everything to a single folder and then run codesniffer on that perhaps if there's no other way to do this. Tho I think that might introduce more problems

**Comment by gsherwood** [comment]
PHPCS can't read report output (like full or summary) and then combine that with the report output of another run.

You can, of course, pipe the output to the same file and append, but the data won't be merged - it will just be several reports in the one file. I'm assuming you want something a bit smarter than that.

I'm not sure what report format you are using, but if you're using one like csv/xml/checkstyle/json it might be easier to just write your own script to merge the files together after your runs.
