### ISSUE TITLE
Add support for Bitwise not (~)

### ISSUE THREAD

**Issue by Zutatensuppe** [squizlabs/PHP_CodeSniffer#2145]
Currently there is no token for bitwise not (~) 

http://php.net/manual/en/language.operators.bitwise.php

I am working around this in my sniff:

```
public function register()
{
    return [
        T_NONE, // there is no support for ~ in php sniffer
    ];
}
public function process(File $phpcsFile, $stackPtr)
{
    $tokens = $phpcsFile->getTokens();
    if ($tokens[$stackPtr]['content'] === '~') {
        // found the bitwise not operator
    }
}
```

Supporting bitwise not should be relatively easy by adding 'T_BITWISE_NOT' to the `resolveSimpleToken` function in https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Tokenizers/PHP.php#L1966 and adding according constants, but I did not check exactly where else it could be relevant, hence the issue instead of pull request.

**Comment by gsherwood** [comment]
I added the new T_BITWISE_NOT token but didn't change any sniffs (none were looking for T_NONE). Thanks for bringing this to my attention.

**Comment by jrfnl** [comment]
@gsherwood Should the new token be added to the `Tokens:;$operators` array ?

**Comment by gsherwood** [comment]
> Should the new token be added to the `Tokens::$operators` array ?

The operator arrays are only for operators that can have two sides, which is why boolean not is not part of the boolean operators array. I did briefly add bitwise not to the array by mistake and sniffs started throwing errors, which is how I remembered that exception.

**Comment by jrfnl** [comment]
@gsherwood Understood.
