### ISSUE TITLE
XML schema not updated with the new array property syntax

### ISSUE THREAD

**Issue by Majkl578** [squizlabs/PHP_CodeSniffer#2151]
#1665 added new format to declare array properties (which is a good move btw!), but didn't update `phpcs.xsd` appropriately.
Using this syntax results in invalid XML according to the schema.

See https://github.com/doctrine/coding-standard/pull/84 for more details & xmllint report.

cc @webimpress

**Comment by gsherwood** [comment]
Yep, I missed updating that file. Thanks for reporting this.

The new xsd will be in 3.3.2, or you can grab it from master for testing: https://github.com/squizlabs/PHP_CodeSniffer/blob/master/phpcs.xsd

**Comment by Majkl578** [comment]
Thanks, works. :+1: Looking forward to 3.2.2 now. 😊

**Comment by Majkl578** [comment]
@gsherwood Do you please have some ETA for 3.2.2? I see the milestone is 100% and it'd help us with planning the next release of our CS. Thanks. :+1:

**Comment by gsherwood** [comment]
@Majkl578 I don't know when. I don't like to promise because I'm almost always wrong due to how often things come up with my job, but 3.2.2 does feel very close.
