### ISSUE TITLE
phpcs:ignore usage unclear

### ISSUE THREAD

**Issue by marcelloh** [squizlabs/PHP_CodeSniffer#2157]
The documentation only mentioned the way is is set,
but what I miss, is:
is it set only for that file, or method, or next line?
and how is it unset?

**Comment by jrfnl** [comment]
The PHPCS annotations are documented quite extensively in the wiki: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#ignoring-parts-of-a-file

> You can also ignore a single line using the phpcs:ignore comment. This comment will ignore the line that the comment is on, and the following line. 

Does that answer your question ?

**Comment by marcelloh** [comment]
Again, you can selectively ignore one or more specific error message codes, sniffs, categories of sniffs, or entire standards.

Does this still applies to one single line?
(this part is unclear to me)

**Comment by jrfnl** [comment]
`phpcs:ignore` -> applies to the line the comment is on and the following line.
`phpcs:disable` -> applies from that point forward to the end of the file or till the next `phpcs:enable` - Also see #1986.
`phpcs:enable` -> (only after a disable) applies from that point forward to the end of the file.

All of these can be combined with (parts of) sniff codes and those, in that case, will be applied only for the parts of the file the `phpcs:...` annotation applies to.

`phpcs:ignoreFile` can **_not_** be combined with sniff codes and when set at the beginning of the file, will prevent the file from being tokenized (performance shortcut). Also see #1903.

`phpcs:set` can be used to change sniff properties in-line - mostly used for the unit test files -. Any changed property setting will be applied from that point forward for the rest of the file **_and all files after it_**. Also see #2126.

Does that clarify it ?

**Comment by marcelloh** [comment]
yes (I asked because I didn't find that particular case in the documentation)
So I can safely assume:
// phpcs:ignore someSpecificSniff
// phpcs:ignore someOtherSniff
myBadCode('partly', true);
will both skip the 2 sniffs on the first PHP line that is followed (so not: the next line, but the next real PHP line)

**Comment by jrfnl** [comment]
No, it will not. It will literally skip the line it is on and the next line - not the _next line of real PHP_.

So, this will not work:
```php
// phpcs:ignore someSpecificSniff -- This will ignore the annotation line below for someSpecificSniff.
// phpcs:ignore someOtherSniff -- This will ignore the code line below for someOtherSniff.
myBadCode('partly', true);
``` 

However, this will work:
```php
// phpcs:ignore someSpecificSniff,someOtherSniff -- Skipping the next line for both sniffs.
myBadCode('partly', true);
```

**Comment by marcelloh** [comment]
clear enough, thanks for the explanation
