### ISSUE TITLE
3.3.2 release?

### ISSUE THREAD

**Issue by TysonAndre** [squizlabs/PHP_CodeSniffer#2161]
All tickets in the 3.3.2 milestone are closed: https://github.com/squizlabs/PHP_CodeSniffer/milestone/13

The previous release was on July 26th, various bug fixes and other changes were added since then.

What tasks/verification still need to be done prior to creating a release?

**Comment by gsherwood** [comment]
> What tasks/verification still need to be done prior to creating a release?

None. I need time. I don't get paid for PHPCS development, so I need to prioritise my paying job and family before this project, both of which take considerable time.

The fact that that all issues in the milestone are closed means a release is very close. Maybe I'll find time this week to package a release and monitor it, but I can't promise anything.
