### ISSUE TITLE
Code consistency badge

### ISSUE THREAD

**Issue by nhuhoai** [squizlabs/PHP_CodeSniffer#2164]
I don't know how to contact you then I write here. I just make a tiny tool to create a code consistency badge from shields.io before commiting changes or pushing data. It is based on your Analysis of Coding Conventions. Is it okay for you guys?

You can found the project here: https://github.com/FranicFlow/php-code-consistency

Thanks in advance.

**Comment by gsherwood** [comment]
> Is it okay for you guys?

Yes. I'm happy for you to use the code or results in any way you want.
