### ISSUE TITLE
How to use phpcbf with Netbeans 8.2 (phpcs is working fine.)

### ISSUE THREAD

**Issue by tphobe9312** [squizlabs/PHP_CodeSniffer#2166]
ERROR: The file "fix" does not exist.

Run "phpcbf --help" for usage information

**Comment by gsherwood** [comment]
I don't think I can help here. I'm not sure how the Netbeans integration works as I have not been involved with it. It's probably better to ask on a Netbeans forum or issue tracker.

**Comment by gsherwood** [comment]
Closing with no feedback + no idea how to help here.
