### ISSUE TITLE
Needs attention on Packages on Packagist.org

### ISSUE THREAD

**Issue by truls1502** [squizlabs/PHP_CodeSniffer#2168]
Your package on packagist.org have `(Legacy Auto-Update, Needs Attention)`

> If you have published packages from GitHub on http://packagist.org  please logout/login with GitHub to let us upgrade the auto-update hooks and remove the deprecated GitHub service hooks. See “GitHub Hook” on https://packagist.org/about#how-to-update-packages for more details.

> Note that things will keep working fine as-is until January 2019 so no rush doing this but do it when you get a chance to make sure your packages keep updating smoothly.</blockquote>

Source about how-to-do: https://twitter.com/packagist/status/1037035587453235201

**Comment by truls1502** [comment]
ping @gsherwood

**Comment by truls1502** [comment]
Have you tried to re-authorized Packagist as was suggested in composer/packagist#907?

**Comment by truls1502** [comment]
I just took a quick look on Packagist.org and it looks it is fixed now 👍

**Comment by crisu83** [comment]
Unlinking and relinking my account (GitHub) seem to have fixed the issue for all of my 65 repositories. 👍

**Comment by gsherwood** [comment]
No webhook exists inside this repo for packagist, so there is currently no integration configured at all. I don't think it's working, so I'll keep this open and check up on it from time to time. But pretty sure it's broken.

**Comment by gsherwood** [comment]
This has been sorted out now. Thanks for letting me know this was required.
