### ISSUE TITLE
include-pattern broken

### ISSUE THREAD

**Issue by brandonkal** [squizlabs/PHP_CodeSniffer#2177]
It seems the include-pattern directive is broken. It does not work on the ruleset level or the rule level. When set at the rule level, extra files are included, but not as many.

I cannot do this:

```
<include-pattern>public/app/plugins/my-plugin</include-pattern>
```
This also does not work:
```
<exclude-pattern>*</exclude-pattern>
<include-pattern>public/app/plugins/my-plugin</include-pattern>
```

This makes it really hard to enforce coding standards for wordpress projects where it is not as simple as ignoring `*/vendor/*` because much of the third party code is all over the place, including the plugins directory where project specific code is.
Blacklisting everything installed is not really ideal here but it seems to be the only option.

Another solution to this problem would be to support parsing gitignore, or detecting folders managed by composer and then ignoring them.

Here is an example:

phpcs.xml
```
<?xml version="1.0"?>
<ruleset name="MyStandard">
	<description>A base ruleset for EventsMadeLive projects</description>
	<rule ref="NeutronRefined">
		<include-pattern>./public/app/plugins/perfmatters/*</include-pattern>
	</rule>

	<arg name="colors" />
    <arg name="parallel" value="75" />
	<arg value="p"/>

</ruleset>
```
command:
```
vendor/bin/phpcs --report=summary --basepath=public/app/ .
```
The Output:
```
plugins/jetpack/modules/module-headings.php                0        1
plugins/perfmatters/perfmatters.php                                14       3
plugins/perfmatters/inc/EDD_SL_Plugin_Updater.php     101     22
...
```

**Comment by gsherwood** [comment]
Have you been able to test this again? I don't think I can help with that debug info.

**Comment by brandonkal** [comment]
Hmm, I have attempted removing all excludes from my ruleset so I only had 
```
<include-pattern>public/app</include-pattern>
```

However, it still checked the whole WordPress codebase. (in `public` outside of `app`).

**Comment by gsherwood** [comment]
Thanks for setting that up - it helps me see what you're doing.

The first thing I can tell you from those ruelsets is that include-pattern wont be doing anything when you set it directly in a ruleset. It only applies to rules. To tell PHPCS what files to check, you need to either pass them on the command line or use one or more `<file>` tags to pass file or directory paths to.

I've still got to look at your basic.xml ruleset where you are setting include patterns for the PEAR standard.

**Comment by gsherwood** [comment]
For the basic.xml file, all include-pattern checks are being run correctly, but you are getting some `Internal.NoCodeFound` warnings beings generated. These are not being filtered out by the include rules because these are not errors generated from a standard.

If you added this to the basic ruleset:
```xml
<rule ref="Internal.NoCodeFound">
    <include-pattern>public/app/my-plugin</include-pattern>
    <include-pattern>public/app/themes/my-theme</include-pattern>
    <include-pattern>public/my-custom-file.php</include-pattern>
</rule>
```
Then you wont get any errors from your basic run.

Or if you don't care about this error at all, you can mute it permanently:
```xml
<rule ref="Internal.NoCodeFound">
    <severity>0</severity>
</rule>
```
It looks to me like the patterns are working correctly.

**Comment by gsherwood** [comment]
> Notice that `check-email` and `wordpress-importer` plugins are being included in the report even though they are not part of the include-pattern in phpcs.xml

This is because include-pattern only applies to rules - not to the whole ruleset, as per my previous comment:
> The first thing I can tell you from those rulesets is that include-pattern wont be doing anything when you set it directly in a ruleset. It only applies to rules. To tell PHPCS what files to check, you need to either pass them on the command line or use one or more <file> tags to pass file or directory paths to.

But I think I've found an issue with the include pattern in the basic ruleset. Looking into it now.

**Comment by brandonkal** [comment]
Yes, after moving the include pattern to the rule instead of the ruleset, no errors are found.

**Comment by gsherwood** [comment]
The issue with the include pattern is that multiple patterns for the same rule are causing it to break. If a path doesn't match the first pattern, PHPCS considers it a "not included file" and doesn't check the second and third patterns to see if it should be included. I'm fixing this now.

**Comment by gsherwood** [comment]
Sorry, I got really busy today. I've committed a change to get include-patterns working the way they should, but it would be great if you had a chance to try out the fix and make sure everything is working the way you expect.

**Comment by brandonkal** [comment]
@gsherwood Awesome! I'll give it a thorough test in the AM here.

**Comment by gsherwood** [comment]
> Looks good to me.

Thanks a lot for testing this out. Good news :)
