### ISSUE TITLE
Check visibility before static for properties in PropertyDeclarationSniff

### ISSUE THREAD

**Issue by umherirrender** [squizlabs/PHP_CodeSniffer#2198]
MethodDeclarationSniff checks that visibility (public, private, protected) is before the static keyword, but I have not found a sniff to do this check for properties.

It is possible to add the check from MethodDeclarationSniff to PropertyDeclarationSniff to check for visibility before static? The final and abstract keyword is not needed.

It seems there is no Tokens::$propertyPrefixes similar to Tokens::$methodPrefixes for this purpose.

Thanks.

**Comment by jrfnl** [comment]
PR #2218 addresses this feature request.
