### ISSUE TITLE
Cache should respect $XDG_CACHE_HOME

### ISSUE THREAD

**Issue by legoktm** [squizlabs/PHP_CodeSniffer#2200]
See <https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html>.

It would be nice if the `--cache` functionality would respect `$XDG_CACHE_HOME` so it works with other tools and environments that set that. In Wikimedia's CI setup, we have this pointing to `/cache`, which is shared across all of our runners.

Many PHP tools use the https://github.com/dnoegel/php-xdg-base-dir/blob/master/src/Xdg.php library to implement the XDG spec. But it's also pretty simple and could be copied/inlined instead of depending upon the library.

**Comment by gsherwood** [comment]
As per the spec, if `XDG_CACHE_HOME` is not set, I should instead use `HOME/.cache`. But this is now going to result in a `.cache` dir being created under a user's home directory (like it does for me on Mac OS) which wont be cleaned up like the temp dir is.

So to implement this, I will instead directly fall back to using the temp dir (as I do now) if `XDG_CACHE_HOME` is not set. I assume that's going to be okay for you, but please let me know if not.

**Comment by gsherwood** [comment]
Committed here: https://github.com/squizlabs/PHP_CodeSniffer/commit/a7e631bd58d516fe865efafe62db2add4e93168d

`XDG_CACHE_HOME` must be set *and* point to a valid directory (I'm not going to create it in PHPCS) in order to use it for caching. Fallback is the system temp dir in both cases.

**Comment by legoktm** [comment]
Thanks, I think what you've implemented will meet our needs for now. One question though:

> ...which wont be cleaned up like the temp dir is.

Is there a reason it needs to be cleaned up?
