### ISSUE TITLE
PHP version not specified

### ISSUE THREAD

**Issue by Have-a-Laugh** [squizlabs/PHP_CodeSniffer#2203]
Hi, please can someone show me how to clear this error for PHP 7.2.10, I've spend hours on Google and drawn a blank, thank you.

**Comment by Have-a-Laugh** [comment]
Edit: I've just came across "PHP Version 5" which clears the error, but PHP 5 is out of date surely? my system is on PHP 7.2.10

**Comment by Have-a-Laugh** [comment]
@gsherwood thank you very much, that cleared it up, cheers, much appreciated.

**Comment by Have-a-Laugh** [comment]
@gsherwood one quick question before this is closed, please could you point me in the right direction for  what "@category", "@package" and "@link" are used for, I can't seem to see them explained in the documentation, (I'm writing code from scratch), thanks.

**Comment by jrfnl** [comment]
For an explanation of these documentation tags, you might find the following links useful:
* [PHPDocumentor tag reference](https://docs.phpdoc.org/references/phpdoc/index.html)
* [PSR-5](https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md) (draft)

**Comment by Have-a-Laugh** [comment]
@jrfnl thanks for the reply, sorry I'm struggling to understand the meanings for the category, package and link

**Comment by gsherwood** [comment]
Those comment tags are very PEAR-centric. You may prefer to use the PSR2 standard that comes with PHPCS, although this does not contain any rules for docblocks. Or you might want to create your own standard using a ruleset.xml file and exclude the errors you don't care about, like missing `@package` tags.

**Comment by Have-a-Laugh** [comment]
@gsherwood thanks, that's much better :+1:
