### ISSUE TITLE
.inc files trigger merge conflicts

### ISSUE THREAD

**Issue by BonBonSlick** [squizlabs/PHP_CodeSniffer#2204]
I was   confused when got merge conflicts during rebase, but version control tab was empty, after manual check, figured out that there are vendor files with conflicts!

```
 grep -H -r "<<<<<<< HEAD" /var/www/site/site/

/var/www/site/site/vendor/squizlabs/php_codesniffer/src/Standards/Generic/Tests/Arrays/DisallowLongArraySyntaxUnitTest.2.inc:<<<<<<< HEAD

/var/www/site/oppassiteand/vendor/squizlabs/php_codesniffer/src/Standards/Generic/Tests/Arrays/DisallowLongArraySyntaxUnitTest.2.inc.fixed:<<<<<<< HEAD

/var/www/site/site/vendor/squizlabs/php_codesniffer/src/Standards/Squiz/Tests/PHP/HeredocUnitTest.inc:<<<<<<< HEAD
```

In this files I see

```
<?php
$var = array();

// The following function has a simulated git conflict for testing.
// This is not a merge conflict - it is a valid test case to test handling of arrays without associated closer.
// Please do not remove.
function test()
    {
        $arr = array(
            'a' => 'a',
<<<<<<< HEAD
            'b' => 'b'
=======
            'c' => 'c'
>>>>>>> master
        );
    }

```

This does not allow us to do rebase. Changing it says that it is vendor package, changes will be overwritten.  Package must not generate such files. Why it generated them?

**Comment by BonBonSlick** [comment]
It is ignored by git.
`/vendor/`

**Comment by gsherwood** [comment]
If you can't have PHPCS in your vendor folder because of this, maybe install it globally.

I'm going to close this as the conflicts must stay as they are part of tests, and the test will be removed in version 4 so this is already on the roadmap.
