### ISSUE TITLE
Visibility must be declared on method / Method name is not in camel caps format

### ISSUE THREAD

**Issue by Have-a-Laugh** [squizlabs/PHP_CodeSniffer#2205]
Hi, I'm struggling with these two errors, I've tried Google but no answer turned up for these, if anyone could guide me to an answer it would be much appreciated, thank you very much

1st message: "Visibility must be declared on method "changePassword""
```
    function changePassword()
    {
        code
    }
```
2nd message: "Method name "User::countAll_BySearch" is not in camel caps format"
```
    public function countAll_BySearch($search_term)
    {
        code
    }
```

**Comment by gsherwood** [comment]
> 1st message: "Visibility must be declared on method "changePassword""
For this one, it wants you to explicitly say that the method is public. So like this:
```php
public function changePassword()
{
    // code
}
```
> 2nd message: "Method name "User::countAll_BySearch" is not in camel caps format"
For this one, it wants the name of your functions to be [camelCase](https://en.wikipedia.org/wiki/Camel_case), so something more like this:
```php
public function countAllBySearch($search_term)
{
    // code
}
```

**Comment by Have-a-Laugh** [comment]
@gsherwood thank you so much! that fix it, i really appreciate your help, many thanks!

**Comment by gsherwood** [comment]
You're welcome :)
