### ISSUE TITLE
Is it possible to run gulp-phpcbf if errors found?

### ISSUE THREAD

**Issue by sofyansitorus** [squizlabs/PHP_CodeSniffer#2208]
Hello,

I am really appreciate this gulp tools. It really helpful to spot any code errors right away while doing changes. I was thinking if it can trigger to run [gulp-phpcbf](https://github.com/gaving/gulp-phpcbf) if errors found. Is it possible?

Sofyan

**Comment by gsherwood** [comment]
The PHPCS plugin for gulp is not managed by this project, so I don't know how that plugin works and can't help you out.

It looks like it is managed here: https://github.com/JustBlackBird/gulp-phpcs

It is probably worth opening an issue over there to see if anyone can help.
