### ISSUE TITLE
HTML styling issue after PHP

### ISSUE THREAD

**Issue by Have-a-Laugh** [squizlabs/PHP_CodeSniffer#2209]
Hi, I've been working on this pagination for my website, I've ran it through PHP CS and the code has no errors, but if I view the HTML source, their's an issue with what appears to be the closing ?> php tags causing some lines to be indented incorrectly, I have attached a screenshot below to show the whitespace, I know it shouldn't be worried, but if I'm making a mistake I'd really like to learn from it, any advice would be much appreciated, thank you very much

![2018-10-29-205758_1366x768_scrot](https://user-images.githubusercontent.com/36129882/47680079-c5e19f80-dbbd-11e8-8ca2-4e7918ec6fb0.png)

```
    <ul class="pagination margin-zero">
<?php if ($page>1) : ?>
        <li>
            <a href='<?php echo $page_url; ?>' title='Go to the first page.'>
                First Page
            </a>
        </li>
<?php endif;
for ($x = $initial_num; $x<$condition_limit_num; $x++) :
    if (($x > 0) && ($x <= $total_pages)) :
        if ($x == $page) : ?>
        <li class='active'>
            <a href="#"><?php echo $x; ?> <span class="sr-only">(current)</span></a>
        </li>
        <?php else : ?>
        <li>
            <a href='<?php echo $page_url; ?>page=<?php echo $x; ?>'><?php echo $x; ?></a>
        </li>
        <?php
        endif;
    endif;
endfor;
if ($page<$total_pages) : ?>
        <li>
            <a href='<?php echo $page_url; ?>page=<?php echo $total_pages; ?>' title='Last page is <?php echo $total_pages; ?>'>
                Last Page
            </a>
        </li>
<?php endif; ?>
    </ul>
```

**Comment by gsherwood** [comment]
There is no right and wrong answer for this, but my personal preference is the format the code in a way that is readable to the developer. I don't really care how nice the HTML is. If I need to worry about that, I run it through a beautifier on the way out.

For your specific code, I would format it like this:
```php
<ul class="pagination margin-zero">
    <?php
    if ($page>1) :
        ?>
        <li>
            <a href='<?php echo $page_url; ?>' title='Go to the first page.'>
                First Page
            </a>
        </li>
        <?php
    endif;
    for ($x = $initial_num; $x<$condition_limit_num; $x++) :
        if (($x > 0) && ($x <= $total_pages)) :
            if ($x == $page) :
                ?>
                <li class='active'>
                    <a href="#"><?php echo $x; ?> <span class="sr-only">(current)</span></a>
                </li>
                <?php
            else :
                ?>
                <li>
                    <a href='<?php echo $page_url; ?>page=<?php echo $x; ?>'><?php echo $x; ?></a>
                </li>
                <?php
            endif;
        endif;
    endfor;
    if ($page<$total_pages) :
        ?>
        <li>
            <a href='<?php echo $page_url; ?>page=<?php echo $total_pages; ?>' title='Last page is <?php echo $total_pages; ?>'>
                Last Page
            </a>
        </li>
        <?php
    endif;
    ?>
</ul>
```
This is my personal/company coding style and it creates a lot of whitespace in the HTML output. But I write it like this because I find it easier to read.

**Comment by Have-a-Laugh** [comment]
@gsherwood that makes a lot of sense, thanks, I don't know why I was trying to put so much effort in the HTML side of it, it's the developer view point and the output to the user that's important, thanks again, I really appreciate your replies to my questions :+1:

**Comment by gsherwood** [comment]
> I really appreciate your replies to my questions

No problem.
