### ISSUE TITLE
Issue with files not having .php

### ISSUE THREAD

**Issue by muuvmuuv** [squizlabs/PHP_CodeSniffer#2225]
I have noticed that phpcs and phpcbf are kind of ignoring files that has no file extension or any other then .php. They both just print out:

```

No fixable errors were found

Time: 49ms; Memory: 6Mb

```

I have two files that are configs for php dependencies that have no php at the end

**Comment by gsherwood** [comment]
PHPCS will only check files that it thinks are PHP files (.php and .inc). You can tell it to check files with different extensions (often used for things like .tpl) but you can't tell it to check files with no extension.

I'm going to close this as it is being tracked here: https://github.com/squizlabs/PHP_CodeSniffer/issues/1754
