### ISSUE TITLE
UselessOverridingMethodSniff  should consider return type

### ISSUE THREAD

**Issue by marcospassos** [squizlabs/PHP_CodeSniffer#2230]
`UselessOverridingMethodSniff ` currently does not consider return type narrowing:

```php

class Foo {
    public function getBar() {
       return $this->value;
    }
}

class Bar extends Foo {
   // Possible useless method overriding detected
    public function getBar() : int {
        return parent::getBar();
    }
}
```

**Comment by jrfnl** [comment]
True, just like it doesn't consider a change in visibility for a method either.

Neither of these are things PHPCS can reliably determine as to do so it would need to know the signature of the method in the (grand-)parent class.

The sniff is currently not set up to keep track of method signatures or of the class extend-tree and would not be able to do so reliably anyway, as:
* Files are scanned in an undetermined order, meaning that the child class might be scanned before the (grand-)parent class.
* When using the parallel option, the parent class and the child class may not even be scanned in the same process.
* The parent-class may be in the `vendor` directory (or similar) which is generally speaking excluded from being scanned.

All in all, this is the best this sniff can do.

You can use the inline [`//phpcs:..` annotations](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#ignoring-parts-of-a-file) to ignore the issue or exclude a particular file from this sniff from your custom ruleset using:
```xml
<rule ref="Generic.CodeAnalysis.UselessOverridingMethod">
    <exclude-pattern>path/to/file\.php</exclude-pattern>
</rule>
```

Does that solve your issue ?

**Comment by marcospassos** [comment]
Thank you very much for such a detailed answer, I can see the problem now. I will try one of those options.
