### ISSUE TITLE
Is it possible to set custom location of the .phpcs.xml file

### ISSUE THREAD

**Issue by sandrodz** [squizlabs/PHP_CodeSniffer#2231]
I've a peculiar setup where I need to have a static place fro the .phpcs.xml file, for it to be read from subdirectories of a project.

Something like this would work:
`let g:syntastic_php_phpcs_args = '--standard='.projectroot#guess().'/.phpcs.xml'`

but obviously it doesn't work, --standard expects an actual name `PSR2` or similar.

**Comment by gsherwood** [comment]
The `--standard` option takes the name of a built-in standard, or the path to a ruleset file. If you are constructing the path and it points to a valid file, PHPCS will be able to read it.

**Comment by sandrodz** [comment]
@gsherwood I will briefly describe my problem, maybe there are better ways to solve it.

I'm using a dockerized phpcs.
```
#!/bin/bash
sudo docker run -i --rm -v "$(pwd)":/app phpcs phpcs --basepath=/app/ "$@"
```

I use vim+syntastic setup in the following way
```
let g:syntastic_php_checkers = ['php', 'phpcs']
let g:syntastic_php_phpcs_exec = '/usr/local/bin/phpcs'
```
I used to have:
`let g:syntastic_php_phpcs_args = '--standard=PSR2'`
and would often change this global option per project. I'd like to move away from this and have a file inside project root so I don't have to edit `.vimrc` every time I jump from project to project with different standards.

If I don't define `--standard` phpcs reads from the root .phpcs.xml file. But it works only for the root files, if I navigate to some other folder and open php files in sub directories, .phpcs.xml is not being found - this is expected because of the container setup, phpcs container doesn't know of any parent directories.

So my idea was to have static path to the phpcs.xml file, like so:
```
let g:syntastic_php_phpcs_args = '--standard='.projectroot#guess().'/'
```

I am using this file as .phpcs.xml to test the setup -> https://raw.githubusercontent.com/WordPress-Coding-Standards/WordPress-Coding-Standards/develop/phpcs.xml.dist.sample

But I get following error:

>  ['ERROR: the "/srv/www/plugandpay.test/public/plugins/kubikplugins-custom-drill-down-maps/" coding standard is not installed. The installed coding standards are
> MySource, PEAR, PSR1, PSR2, Squiz, Zend, WordPress, WordPress-Core, WordPress-Docs, WordPress-Extra and WordPress-VIP', '']

**Comment by sandrodz** [comment]
Since https://github.com/squizlabs/PHP_CodeSniffer/blob/c1aa7a156a5058d4ffac09ac27cf2b5bd8de4d46/src/Config.php#L337 --standard needs to be false for the .phpcs.xml to be read in, I guess I'm out of luck without adding a new flag.
Correct?

**Comment by sandrodz** [comment]
shoot, stupid me, `--standard=file` is looking inside container. I've .phpcs.xml outside the container.

**Comment by sandrodz** [comment]
I'm closing this, it seems more of a vim/docker issue than phpcs.

**Comment by gsherwood** [comment]
Sorry I wasn't more help - looks like you figured it all out while I was sleeping :)
