### ISSUE TITLE
Question about the documentation of exclude patterns and absolute paths

### ISSUE THREAD

**Issue by mnapoli** [squizlabs/PHP_CodeSniffer#2241]
In the documentation we can read this:

```xml
 <!--
    You can hard-code ignore patterns for specific sniffs,
    a feature not available on the command line. Please note that
    all sniff-specific ignore patterns are checked using absolute paths.

    The code here will hide all messages from the Squiz DoubleQuoteUsage
    sniff for files that match either of the two exclude patterns.
 -->
 <rule ref="Squiz.Strings.DoubleQuoteUsage">
    <exclude-pattern>*/tests/*</exclude-pattern>
    <exclude-pattern>*/data/*</exclude-pattern>
 </rule>
```

More specifically:

> Please note that all sniff-specific ignore patterns are checked using absolute paths.

Let's say my project is cloned in `/home/tests/myproject` does that mean that the exclusion will apply to every file in my project? (because there is `tests` in the absolute path)

That sounds like an undesirable behavior to me because I can't control the directory in which contributors will clone the project, so I just want to make sure I understand that right.

Thanks.

**Comment by jrfnl** [comment]
> Let's say my project is cloned in /home/tests/myproject does that mean that the exclusion will apply to every file in my project? (because there is tests in the absolute path)

@mnapoli Yes, it does mean that.

However, there are two caveats which can prevent the issue:
1. You can use `<exclude-pattern type="relative">` to make the pattern relative to the location of the ruleset. The use of this is described a bit higher up on the Annotated ruleset page you quoted from.
2. The `exclude-pattern` is a [regular expression with the `*` replaced with `.*` automatically](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#ignoring-files-and-folders). Sometimes, just making the regex pattern more specific can also help.

**Comment by mnapoli** [comment]
Thank you for the answer!
