### ISSUE TITLE
Wrong link in the documentation

### ISSUE THREAD

**Issue by webimpress** [squizlabs/PHP_CodeSniffer#2257]
On page: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#using-a-default-configuration-file
we have invalid link on `ruleset.xml file` to:
https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-ruleset.xml

but it should be to:
https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-Ruleset

**Comment by gsherwood** [comment]
Thanks. I've fixed those up.
