### ISSUE TITLE
Feature suggestion: new sniff `EchoConcatenation`

### ISSUE THREAD

**Issue by jrfnl** [squizlabs/PHP_CodeSniffer#2259]
Inspired by [this Twitter thread](https://twitter.com/Rarst/status/1067354731293614080) and [this article](https://github.com/dseguy/clearPHP/blob/master/rules/no-unnecessary-string-concatenation.md).

Using concatenation exponentially increases the memory PHP uses. While in a lot of cases, there is no alternative, there are some specific situations, where there is, most notably when using `echo` where comma's  or interpolation can be used instead.

**Question: Would there be interest in a sniff to detect (and possibly auto-fix) this ?**

I image a sniff like this could go into the `Generic.CodeAnalysis` category.

Detect:
```php
echo "Hello " . $name . "! Welcome!"; // Use comma's or interpolation instead.
echo '<div><span>' . function_call($foo) . '</span>' . function_call($bar) . '</div>'; // Use comma's instead.
```

Recommended alternative way of writing this code:
```php
echo "Hello $name! Welcome!";
echo '<div><span>', function_call($foo), '</span>', function_call($bar), '</div>';
```

For more code examples, see the [ClearPHP article](https://github.com/dseguy/clearPHP/blob/master/rules/no-unnecessary-string-concatenation.md).

**Comment by gsherwood** [comment]
I like it

**Comment by jrfnl** [comment]
Closing as replaced by PHPCSStandards/PHPCSExtra#285
