### ISSUE TITLE
Fixer conflict Squiz/PostStatementComment vs multi-line control structures

### ISSUE THREAD

**Issue by jrfnl** [squizlabs/PHP_CodeSniffer#2293]
Given the below code sample, there is a fixer conflict in the Squiz standard as the `Squiz.ControlStructures.ForLoopDeclaration` sniff demands one space after the semi-colon, while the `Squiz.Commenting.PostStatementComment` sniff demands that the trailing comments are moved to a new line.

```php
for (
    $i = 0; /* Start */
    $i < 10; /* phpcs:ignore Standard.Category.SniffName -- for reasons. */
    $i++ // comment
) {}
```
	
`phpcbf ./testfile.php --standard=Squiz -vv`

Now there are a couple of options for solving this:
1. Make the `Squiz.Commenting.PostStatementComment` sniff ignore trailing comments within (multi-line) control structure conditions completely.
2. Allow the `Squiz.Commenting.PostStatementComment` sniff to report trailing comments within (multi-line) control structure conditions, but don't allow the fixer to kick in.
3. Make the `Squiz.ControlStructures.ForLoopDeclaration` sniff (and other control structure sniffs) report spacing issues in multi-line conditions, but don't let the fixer kick in if the next non-whitespace token is a comment.
4. Option 2 + 3 both.

Personally, I would go for option 1.

@gsherwood I'd be happy to make the changes, but would like some guidance as to which option you'd prefer.

Note: I have PRs open for both the above mentioned sniffs already - #2266 and #2286 -, so, to prevent conflicts between PRs, I would add a fix for this issue to the existing open PR in a separate commit.

**Comment by gsherwood** [comment]
I'd be happy with option 1 as well.

**Comment by jrfnl** [comment]
I've added a second commit to PR #2266 which implement this.
