### ISSUE TITLE
Sniffs for comparison operators

### ISSUE THREAD

**Issue by Kifah** [squizlabs/PHP_CodeSniffer#2302]
I want to make sure, my code always has Identical used, when using comparison operators

so this is false:
`$a == $b`
this is correct
`$a === $b`

so instead of re-inventing the wheel, is there some sniff available for that? I checked the available rules but was not lucky.

**Comment by webimpress** [comment]
@Kifah check this out:
https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/Squiz/Sniffs/Operators/ComparisonOperatorUsageSniff.php

`Squiz.Operators. ComparisonOperatorUsage` is what you are looking for!

**Comment by Kifah** [comment]
thank you. I also found this: https://github.com/slevomat/coding-standard which is pretty useful as well.
