### ISSUE TITLE
Allow inline @var

### ISSUE THREAD

**Issue by josephzidell** [squizlabs/PHP_CodeSniffer#2306]
The BlockComment sniff excludes comments above structural elements, including class properties. A common use-case in phpstan is an inline `@var`:

```php
function f()
{
    /** @var SomeType */
    $foo = 'bar';
}
```

How would I allow this, while still catching any other inline block comments?

https://github.com/phpstan/phpstan/issues/1710

**Comment by glen-84** [comment]
Related to #258?

**Comment by josephzidell** [comment]
Yes. Similar issue
