### ISSUE TITLE
[feature request] enforce double quote usage

### ISSUE THREAD

**Issue by mathroc** [squizlabs/PHP_CodeSniffer#2316]
Hi,

It looks like I can force single quote usage, or allow double quote usage only when interpolating variables. But I'm looking to prevent single quote usage instead.

**Comment by josephzidell** [comment]
In php 7, interpolation [is actually faster](https://blog.blackfire.io/php-7-performance-improvements-encapsed-strings-optimization.html) than concatenation. Perhaps we can detect single- or double-quoted strings that are currently concatenated and could use interpolation, which is basically a variable or class property (excludes constants, method calls).

**Comment by jrfnl** [comment]
Loosely related to #2259

**Comment by gsherwood** [comment]
Closing in favour of #1653 - please leave comments there instead.
