### ISSUE TITLE
Release notes for 3.4.0

### ISSUE THREAD

**Issue by phil-davis** [squizlabs/PHP_CodeSniffer#2320]
In https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.4.0 there is a section about:

--------
Array properties set inside a ruleset.xml file can now extend a previous value instead of always overwriting it

    e.g., if you include a ruleset that defines forbidden functions, can you now add to that list instead of having to redefine it
    To use this feature, add extends="true" to the property tag
        e.g., <property name="forbiddenFunctionNames" type="array" extend="true">
    Thanks to Michael Moravec for the patch
--------
The new property name is mentioned as both ``extends`` and ``extend``

Update the release notes to consistently use the correct property string ``extend`` (ref: https://github.com/squizlabs/PHP_CodeSniffer/pull/2154/files )

**Comment by gsherwood** [comment]
Thanks for picking that up. I've corrected it now.
