### ISSUE TITLE
Typos in Release Notes of 3.4.0v

### ISSUE THREAD

**Issue by carusogabriel** [squizlabs/PHP_CodeSniffer#2328]
Hello there 👋 

A couple of typos in our Release Notes of 3.4.0v:

~~> The functionality of this sniff is now available in the Generic.Formatting.SpaceAfterCast sniff. Include the Generic.Formatting.SpaceAfterCast sniff and set the spacing property to 0 to retain the existing functionality.~~

~~Aren't the default value `1` according to #2234?~~

> All types of binary casting are now tokenzied as T_BINARY_CAST
```diff
-tokenzied
+tokenized
```

> Ensures there is exactly 1 space before a type cast, unless the cast statement is indented or mutli-line
```diff
-mutli-line
+multi-line
```

**Comment by jrfnl** [comment]
> Aren't the default value 1 according to #2234?

It is, but to replace the `Generic.Formatting.NoSpaceAfterCast`, you need to change the property value to `0` ;-)

**Comment by glen-84** [comment]
Also, as mentioned on Gitter:

```
The File::getMethodParamaters() method now includes a has_body array index in the return value
    TRUE if the method has no body (as with abstract and interface methods) or FALSE otherwise
```

The method name is spelled incorrectly, and I think those Boolean values are swapped as well.

**Comment by gsherwood** [comment]
These are now fixed by the two PRs, and I've updated the github patch notes. Thanks.
