### ISSUE TITLE
Wiki: improve code samples annotated ruleset

### ISSUE THREAD

**Issue by jrfnl** [squizlabs/PHP_CodeSniffer#2330]
As the wiki is not publicly editable (or PR-able), leaving this feedback here.

Page: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-Ruleset

The two code samples for `<include-pattern>` near the bottom of the big code sample could use improvement:

#### Current code samples
```xml
<rule ref="Squiz.Strings.DoubleQuoteUsage">
    <include-pattern>*/templates/*</include-pattern>
    <include-pattern>*.tpl</include-pattern>
</rule>

<!-- ... -->
<rule ref="Squiz.Strings.DoubleQuoteUsage.ContainsVar">
    <include-pattern>*/templates/*</include-pattern>
    <include-pattern>*.tpl</include-pattern>
</rule>
```

#### The problem

As the patterns are "special" regexes, the second example pattern in each block is not specific enough and would match `path/to/project/tpl-directory/file.php` for instance.

Escaping the `.` and adding a `$` (end of string) at the end, fixes this and makes it match only files with a `tpl` extension which I presume is the intention of the code sample.

#### Fixed code samples
```xml
<rule ref="Squiz.Strings.DoubleQuoteUsage">
    <include-pattern>*/templates/*</include-pattern>
    <include-pattern>*\.tpl$</include-pattern>
</rule>

<!-- ... -->
<rule ref="Squiz.Strings.DoubleQuoteUsage.ContainsVar">
    <include-pattern>*/templates/*</include-pattern>
    <include-pattern>*\.tpl$</include-pattern>
</rule>
```

**Comment by gsherwood** [comment]
Good point. I've fixed those samples. Thanks.
