### ISSUE TITLE
Allow silencing errors for certain functions

### ISSUE THREAD

**Issue by josephzidell** [squizlabs/PHP_CodeSniffer#2335]
Certain functions ([`fopen`](https://secure.php.net/manual/en/function.fopen.php) for example) currently have no way to avoid a warning from being throw even if you check for it, and [the documentation suggests](https://secure.php.net/manual/en/function.fopen.php#refsect1-function.fopen-errors) silencing errors.

Can the `NoSilencedErrorsSniff` allow certain exceptions, and maybe by default none, but allow the user to specify?

This would be far superior than inlining `phpcs:ignore`s, and it would also be smarter and catch some if you have multiple error suppressors on one line.

**Comment by josephzidell** [comment]
@jrfnl Thanks. I installed it, then quickly realized it hasn't been updated for PHPCS 3.4.0

**Comment by josephzidell** [comment]
Hmm. For some reason, when I specified `"*"`, composer installed an older version. Will try again soon

**Comment by jrfnl** [comment]
@josephzidell If you wait two hours, the RC will be out ;-)

**Comment by josephzidell** [comment]
Holding my breath...

**Comment by jrfnl** [comment]
@josephzidell I just tagged the release ;-)
https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/releases/tag/2.0.0-RC1
