### ISSUE TITLE
Parenthesis should be Parentheses in PSR12.Classes.ClassInstantiation

### ISSUE THREAD

**Issue by glen-84** [squizlabs/PHP_CodeSniffer#2349]
On lines 3, 86, 90, and 91.

This might be considered a BC break, as the error code will be changed.

**Comment by gsherwood** [comment]
I think I copied and pasted this one straight from the standard:

> When instantiating a new class, parenthesis MUST always be present even when there are no arguments passed to the constructor.

But you are right, it should be using the plural form here. Given PSR12 is an in-progress standard and I have said as much, there is no need to wait for a major release. PSR12 itself (the one from PHP-FIG) is still in development as well.

**Comment by gsherwood** [comment]
Fixed. Thanks for reporting.
