### ISSUE TITLE
ERROR: Referenced sniff "Generic.PHP.LowerCaseType" does not exist

### ISSUE THREAD

**Issue by dimative** [squizlabs/PHP_CodeSniffer#2357]
Hello. Please help me fix this error.
ERROR: Referenced sniff "Generic.PHP.LowerCaseType" does not exist

phpcs -i
The installed coding standards are PSR12, PEAR, PSR2, Squiz, Zend, PSR1, MySource, WordPress-Docs, WordPress-Core, WordPress-Extra, WordPress, PHPCompatibility, WebDevStudios, Generic and Security
---------------------------------------------------------------------
phpcs --config-show
Using config file: /etc/php-codesniffer/CodeSniffer.conf

default_standard: Squiz
installed_paths:  /usr/share/php/PHP/CodeSniffer/src/Standards/WordPress-Coding-Standards/,/usr/share/php/PHP/CodeSniffer/src/Standards/PHPCompatibility/,/usr/share/php/PHP/CodeSniffer/src/Standards/WDS-Coding-Standards/,/usr/share/php/PHP/CodeSniffer/src/Standards/Generic,/usr/share/php/PHP/CodeSniffer/src/Standards/phpcs-security-audit
php_path:         /usr/bin/php

------------------------------------------------------------

phpcs --version
PHP_CodeSniffer version 3.2.3 (stable) by Squiz (http://www.squiz.net)

-----------------------------------------------------------------
php --version
PHP 7.2.10-0ubuntu0.18.04.1 (cli) (built: Sep 13 2018 13:45:02) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.10-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies

**Comment by jrfnl** [comment]
@dimative Please update your PHPCS install, the version of WPCS you are using has a minimum PHPCS requirement of PHPCS 3.3.1. You are using version 3.2.3.

**Comment by dimative** [comment]
@jrfnl Hello. Thanks for the reply. How can i update it? I am new in phpcs. My OS in Ubuntu 18.0.4

**Comment by dimative** [comment]
@jrfnl My problem already fixed. Thanks again.

**Comment by jrfnl** [comment]
@dimative Well, that depends on how you installed PHPCS.
* Phar: [download the latest release](https://github.com/squizlabs/PHP_CodeSniffer/releases) and copy it over the old version. If you don't know where the old version is, try `which phpcs` to find out.
* Composer: run `composer update squizlabs/php_codesniffer`
* PEAR: run `pear upgrade --alldeps PHP_CodeSniffer`
* Git clone: pull in the latest version.
