### ISSUE TITLE
Please use extension_loaded for required extensions

### ISSUE THREAD

**Issue by jrchamp** [squizlabs/PHP_CodeSniffer#2369]
#906 added the SimpleXML extension dependency to the composer.json, but if you use the curl/wget method to get the phar, there's no checking done and errors like this occur:
```
PHP Fatal error:  Uncaught Error: Call to undefined function PHP_CodeSniffer\Util\simplexml_load_string() in phar:[...]
```
Please check the extensions in the PHP code and return appropriate error messages by using ``extension_loaded()``. Thank you!

**Comment by jrfnl** [comment]
PR #2403 should fix this. Testing appreciated.
