### ISSUE TITLE
merge conflict

### ISSUE THREAD

**Issue by vlobovikov** [squizlabs/PHP_CodeSniffer#2370]
https://github.com/squizlabs/PHP_CodeSniffer/blob/cbe9b4ed5f2b73e6cb6a9adea3e745f9f8f9286d/src/Standards/Generic/Tests/VersionControl/GitMergeConflictUnitTest.1.inc#L26

**Comment by jrfnl** [comment]
Seriously ? Have you even looked at the file ? Or even the file name for that matter ?

**Comment by gsherwood** [comment]
This is a simulated conflict for testing - not a real one.
