### ISSUE TITLE
Disallow relative file includes

### ISSUE THREAD

**Issue by kkmuffme** [squizlabs/PHP_CodeSniffer#2374]
Like in VIP ruleset
https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/#relative-file-includes

**Comment by jrfnl** [comment]
IMO this is not a suitable suggestion for PHPCS, as PHPCS has no knowledge of framework specific helper functions or constants which would typically be used for this, so any generic type of sniff for this would have a 90% (or higher) false positive rating which is unacceptable.

I suggest checking if this is covered by https://github.com/Automattic/VIP-Coding-Standards/ and if not, reporting it there.

**Comment by kkmuffme** [comment]
Thanks, you are right, opened it in the WP specific ruleset as it makes more sense there.
