### ISSUE TITLE
Disallow use of non wp_remote_get functions

### ISSUE THREAD

**Issue by kkmuffme** [squizlabs/PHP_CodeSniffer#2375]
Like in VIP ruleset
https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/#remote-calls

**Comment by jrfnl** [comment]
IMO this is not a suitable suggestion for PHPCS, as PHPCS has no knowledge of framework specific helper functions which would typically be used for this, so any generic type of sniff for this would have a 90% (or more) false positive rating which is unacceptable.

I suggest checking if this is covered by https://github.com/Automattic/VIP-Coding-Standards/ and if not, reporting it there.

**Comment by kkmuffme** [comment]
Sorry I got my tabs mixed up & posted this to the wrong repo.
