### ISSUE TITLE
Test defines functions that conflict with keywords

### ISSUE THREAD

**Issue by Zarthus** [squizlabs/PHP_CodeSniffer#2381]
Not really an issue, but maybe there's something to improve here:

https://github.com/squizlabs/PHP_CodeSniffer/blob/8c94cf9231dc70e8cb45c52a8f3a34501e271da0/src/Standards/Squiz/Tests/Functions/FunctionDeclarationUnitTest.inc#L70-L74

For most IDEs and some text editors, this marks e.g. `false()` as a function.

I don't have a concrete way of solving the "problem" in mind and I don't really know if it's a problem to begin with. If there's a good solution to tackling this I'm open to discussion of it, and if there's not it's completely find to leave things as they are too.

**Comment by jrfnl** [comment]
#1908 will fix that at some point in the future. In the mean time, you may want to configure your IDE to ignore certain folders in `vendor` directory.

**Comment by Zarthus** [comment]
Looks like a "dupe" then, cheers.

Ignoring it in `vendor/` was a conclusion I drew myself too :)
