### ISSUE TITLE
Allow Generic.CodeAnalysis.UnusedFunctionParameter to ignore parameters whose name starts with an underscore

### ISSUE THREAD

**Issue by mwgamble** [squizlabs/PHP_CodeSniffer#2398]
It's a common convention to be able to mark a parameter as explicitly unused by prefixing its name with an underscore. This is sometimes necessary when you need to fulfil a contract, such as implementing an interface, overriding a method, or providing a method that is designed to be overridden but otherwise requires no default behaviour.

**Comment by jrfnl** [comment]
Duplicate of #1962

**Comment by gsherwood** [comment]
Closing as duplicate
