### ISSUE TITLE
Incorrect comment on "File::$content" property

### ISSUE THREAD

**Issue by aik099** [squizlabs/PHP_CodeSniffer#2400]
The "File::$content" property comment is copy/pasted from "File::$path" property:

https://github.com/squizlabs/PHP_CodeSniffer/blob/49a3e26aa3aa042fece78b0061ba46ccc5f51e76/src/Files/File.php#L30

I've tried looking back into PHP_CodeSniffer 2.x version to find correct comment and submit a PR, but there was not equivalent property at the time.

**Comment by gsherwood** [comment]
Thanks. I fixed the comment.
