### ISSUE TITLE
What are the command line options to query phpcs settings?

### ISSUE THREAD

**Issue by jmcd73** [squizlabs/PHP_CodeSniffer#2428]
There are many examples of using --config-set. 

1. Is there an option to query phpcs's settings? 
2. The docs mention being careful not to overwrite your current installed_paths how do I find out what they are currently set to?
3. When running --config-set by default where are the settings stored?, What is the filename or names?, Seeing as phpcs can be installed globally or in a project where would the settings be written in each case?

If the documentation could include information on the above that would be great.

**Comment by jrfnl** [comment]
> 1. Is there an option to query phpcs's settings?

Try running `phpcs --config-show`.

> 2. The docs mention being careful not to overwrite your current installed_paths how do I find out what they are currently set to?

See the output of the `--config-show` command.

> 3. When running --config-set by default where are the settings stored?, What is the filename or names?, Seeing as phpcs can be installed globally or in a project where would the settings be written in each case?

The file in which the settings are stored will be listed as part of the output of `--config-show`. If you have PHPCS installed in several places, the output will depend on which PHPCS you are calling, i.e., the output of `phpcs --config-show` (globaly installed version) will be different from the output of `vendor/bin/phpcs --config-show`.

**Comment by gsherwood** [comment]
Closing as all answers were provided.

**Comment by c33s** [comment]
shouldn't `phpcs --config-show` also provide the config which was set in `.phpcs_xml.dist`?
