### ISSUE TITLE
How to delete quotes in string using php?

### ISSUE THREAD

**Issue by M4Lien** [squizlabs/PHP_CodeSniffer#2430]

**Comment by M4Lien** [comment]
My substing is "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" alt="" class="no-mml-formula" data-formula-source='{"type" : "image", "src" : 
I want to delete it in total string using php.
If you know, can you help me?
Thanks.

**Comment by jrfnl** [comment]
Do you mean from within a PHP_CodeSniffer sniff ?
If not: this is not a generic PHP helpdesk. Try StackOverflow.
