### ISSUE TITLE
Use function/const not tokenized as T_STRING when preceded by comment

### ISSUE THREAD

**Issue by jrfnl** [squizlabs/PHP_CodeSniffer#2431]
The `function` and `const` keywords used in `use` statements are normally tokenized as `T_STRING`.

However, when there is a comment between the `use` keyword and the `function`/`const` keyword, this fails and they are tokenized as `T_FUNCTION`/`T_CONST`.

Example code where the tokenizer correction fails:

```php
use /* comment */ function bar\math\{
    Msin,
    level\Mcos as BarCos,
    Mcosh,
};

use // phpcs:ignore Standard.Category
    const
	    bar\math\{ BGAMMA as BAR_GAMMA, BGOLDEN_RATIO };
```

Relevant code in the Tokenizer:
https://github.com/squizlabs/PHP_CodeSniffer/blob/e4da24f399d71d1077f93114a72e305286020415/src/Tokenizers/PHP.php#L1418-L1427

As that code _appears_ to look at the `$lastNonEmptyToken`, I'm not sure how to fix this....

**Comment by gsherwood** [comment]
`$lastNonEmptyToken` was only used to store the last non-whitespace token. Changing this store the last non-empty token as per the token util class gets this working and doesn't look to break anything.
