### ISSUE TITLE
PHP tokenizer scopeOpeners

### ISSUE THREAD

**Issue by Beakerboy** [squizlabs/PHP_CodeSniffer#2439]
The docblock for the scopeOpeners describes two indexes as:

> if the token can share a scope closer, and who it can be shared with.

The T_IF, T_ELSE, and T_ELSEIF tokens are all defined as 

    'shared' => false,
    'with'   => [
        T_<other guy>,
        T_<other guy>,
    ],

So, I’m confused, should shared be true? Is the description of what these indexes do more complex than the description currently states?

**Comment by Beakerboy** [comment]
Similarly, the endScopeTokens array appears incomplete. There are several scope closers listed in the scopeOpeners array which do not appear in scopeClosers. Are there certain criteria in which it is necessary to include them, and some where it is okay to leave them out? Should that be documented? It should probably go in the parent, Tokenizer class since it probably applies to all children.

**Comment by Beakerboy** [comment]
SInce nobody has answered the first two questions, I'll just tack this on here. In the JS Tokenizer, what's the rationale for tokenizing comment, but not strings? When the tokenizer sees a string start character, it keeps adding `$chars` to `$buffer` until the string closer is found, `continuing` past any buffer tokenizeng. Conversely, for comments, it added the initial comment token to the token array, and continues to tokenize. After the initial pass, a separate code block collects all tokens between the comment start and comment end, and combines them together, then splits this one large comment token up by lines. It seems like the comments could just be joind together like the strings on the first pass. Is there a reason it doesn't?

**Comment by gsherwood** [comment]
> Is the description of what these indexes do more complex than the description currently states?

It's more complicated, but only for PHP I think. In version 4 of PHPCS, I will probably remove support for multiple tokenizers entirely because having these generic structures just makes things harder and the JS and CSS tokenizers are both completely outdated.

> Similarly, the endScopeTokens array appears incomplete.

Again, this is a PHP tokenizer thing. It really shouldn't apply for other languages, but I don't have time to debug through the JS again and confirm that.

> In the JS Tokenizer, what's the rationale for tokenizing comments, but not strings?

I don't remember the specifics, but it's just trying to replicate whatever the PHP tokenizer does.

**Comment by Beakerboy** [comment]
>  I will probably remove support for multiple tokenizers entirely

That's disappointing to hear but totally understandable. I'm having pretty good success with integrating support for VBA, and I have a map in my head on some small changes that would allow PHP_CodeSniffer to be made into a universal sniffing application. Basically, just like how the Standards are modular, and user extendable, the same could be done for "languages". As long as interfaces are set up in a generic way, there's no reason the scanning and reporting engines couldn't be reused for a different language. One of the biggest hurdles right now is the fact that all the PHP constants are global, and that so much of the code is undocumented. Small, concise functions with unit tests would help. Right now, the tokenizing functions are so big it's hard to figure out where problems come from, and with no unit tests for the pieces, it's difficult to know what the expectation of the function is without having to **really** read the code and run some sample data through.

**Comment by jrfnl** [comment]
>  Small, concise functions with unit tests would help. Right now, the tokenizing functions are so big it's hard to figure out where problems come from, and with no unit tests for the pieces, it's difficult to know what the expectation of the function is without having to really read the code and run some sample data through.

Once #2295 has been merged that should become a lot easier to do and I already have a PR waiting in the wings which will add that for a particular change I intend to propose to the `Tokenizer`. The unit tests I add for that change can serve as an example for how to add more unit tests for everything `Tokenizer`.
