### ISSUE TITLE
doc comment for parameter missing

### ISSUE THREAD

**Issue by codingfromhome** [squizlabs/PHP_CodeSniffer#2449]
Hello, I'm new to understanding the coding standards that come with php codesniffer, I've ran the code through the php codesniffer and managed to clear off most of the errors, but one still remains and I'm not sure why...

>  39 | ERROR | Doc comment for parameter "$templateFile" missing
 66 | ERROR | Doc comment for parameter "$tag" missing
 66 | ERROR | Doc comment for parameter "$value" missing
 76 | ERROR | Doc comment for parameter "$file" missing

I use to have an issue with missing return tag, but I was able to find on google adding void after it would make the error disappear, but I'm not sure if that's the best practice, any feedback on the code would be much appreciated, thank you

``` <?php

/**
 * Template File Doc Comment
 * 
 * PHP version 7
 *
 * @category Template_Class
 * @package  Template_Class
 * @author   Author <author@domain.com>
 * @license  https://opensource.org/licenses/MIT MIT License
 * @link     http://localhost/
 */

/**
 * Template Class Doc Comment
 * 
 * Template Class
 * 
 * @category Template_Class
 * @package  Template_Class
 * @author   Author <author@domain.com>
 * @license  https://opensource.org/licenses/MIT MIT License
 * @link     http://localhost/
 */

class Template
{
    /**
     * Tags array 
     **/
    private $_tags = [];

    /**
     * Template file 
     **/
    private $_template;

    /**
     * Define template file
     **/
    public function __construct($templateFile)
    {
        $this->template = $this->getFile($templateFile);

        /**
         * If the template file is not accessible 
         **/
        if (!$this->template) {
            return "Error! Can't load the template file $templateFile";
        }
    }

    /**
     * Render the build template 
     *
     * @return void
     **/
    public function render()
    {
        $this->_replaceTags();

        echo $this->template;
    }

    /**
     * Set the {tag} with value
     *
     * @return void
     **/
    public function set($tag, $value)
    {
        $this->tags[$tag] = $value;
    }

    /**
     * Get the template file
     *
     * @return void
     **/
    public function getFile($file)
    {
        if (file_exists($file)) {
            $file = file_get_contents($file);
            return $file;
        } else {
            return false;
        }
    }

    /**
     * Replaces all {tags} with corresponding values from $tags array
     *
     * @return void
     **/
    private function _replaceTags()
    {
        foreach ($this->tags as $tag => $value) {
            $this->template = str_replace('{'.$tag.'}', $value, $this->template);
        }

        return true;
    }
}```

**Comment by xuanquynh** [comment]
Please use code markdown syntax for better code viewing!

PHP CodeSniffer tells you that you have to add the `@param` notation each function parameter.

For example,

```php
/**
 * Define template file.
 * 
 * @param string $templateFile
 */
public function __construct($templateFile)
{
    // TODO
}
```

**Comment by codingfromhome** [comment]
> Please use code markdown syntax for better code viewing!
> 
> PHP CodeSniffer tells you that you have to add the `@param` notation each function parameter.
> 
> For example,
> 
> ```
> /**
>  * Define template file.
>  * 
>  * @param string $templateFile
>  */
> public function __construct($templateFile)
> {
>     // TODO
> }
> ```

thank you, that fixes that error but causes another error
> Missing parameter comment

**Comment by xuanquynh** [comment]
I don't often use these sniffs for file, parameter, method and property document.

You should better try to exclude some rules that you don't expect.

```php
/**
 * Define template file.
 * 
 * @param string $templateFile Describe what this parameter is
 */
public function __construct($templateFile)
{
    // TODO
}
```
Firstly, the default standard is PEAR, your code will be validate to match these [rules](https://pear.php.net/manual/en/standards.php). This is the [sample](https://pear.php.net/manual/en/standards.sample.php).

Secondly, you should follow a standard that you really understand. I follow [PSR-2](https://www.php-fig.org/psr/psr-2/) standard, so I usually run the command below.
```
phpcs --standard=PSR-2 /path/to/mycode/
```
I hope this will help.

**Comment by codingfromhome** [comment]
> I don't often use these sniffs for file, parameter, method and property document.
> 
> You should better try to exclude some rules that you don't expect.
> 
> ```
> /**
>  * Define template file.
>  * 
>  * @param string $templateFile Describe what this parameter is
>  */
> public function __construct($templateFile)
> {
>     // TODO
> }
> ```
> 
> Firstly, the default standard is PEAR, your code will be validate to match these [rules](https://pear.php.net/manual/en/standards.php). This is the [sample](https://pear.php.net/manual/en/standards.sample.php).
> 
> Secondly, you should follow a standard that you really understand. I follow [PSR-2](https://www.php-fig.org/psr/psr-2/) standard, so I usually run the command below.
> 
> ```
> phpcs --standard=PSR-2 /path/to/mycode/
> ```
> 
> I hope this will help.

Excellent, thank you!

That's much better, I appreciate that, thanks.

**Comment by xuanquynh** [comment]
@codingfromhome Could you close this issue? You don't need more help, do you?

**Comment by gsherwood** [comment]
Closing as I think this has been answered
