### ISSUE TITLE
Incorrect indentation is actually correct

### ISSUE THREAD

**Issue by NightJar** [squizlabs/PHP_CodeSniffer#2459]
Hi team,

I've recently made a JavaScript only update to a PHP module I help maintain, but then to my misfortune the CI build has failed stating that I have incorrect indentation in a file that has not changed.

This is an issue on a few fronts:
- the file is not altered
- the previous builds passed
- the indentation is actually correct

My colleague has identified that this seems to be a regression between `3.4.0` and `3.4.1`

The build failure can be seen on [TravisCI](https://travis-ci.org/silverstripe/silverstripe-userforms/jobs/510465004#L657)
The file related to this failure can be seen (at the correct commit) on [my branch](https://github.com/creative-commoners/silverstripe-userforms/blob/1d0c347d7ff80e756f489147ae83e61da58dfdb7/code/UserForm.php#L266-L278)
The version of codesniffer can be seen installed at [`3.4.1`](https://travis-ci.org/silverstripe/silverstripe-userforms/jobs/510465004#L631)
The previous build of this module can be seen passing [using codesniffer `3.4.0`](https://travis-ci.org/silverstripe/silverstripe-userforms/jobs/508150190#L617)

Cheers

**Comment by jrfnl** [comment]
Tested and confirmed as duplicate of #2450 which was fixed by e3467d77d00955a0c55f75740c35db8185a6cf74. The fix will be included in PHPCS 3.4.2 which is expected reasonably soon.

**Comment by NightJar** [comment]
Thanks @jrfnl, sorry I didn't see the other issue while searching.
