### ISSUE TITLE
The name seems malware.

### ISSUE THREAD

**Issue by Tails128** [squizlabs/PHP_CodeSniffer#2468]
the name `CodeSnffer` triggers various security issues automated software.
Consider renaming the project.

**Comment by jrfnl** [comment]
You're joking, aren't you ?

**Comment by Tails128** [comment]
wish I was.
This happened as soon as I uploaded the library to the host.

![Capture](https://user-images.githubusercontent.com/12231147/55289759-0fcbed00-53cb-11e9-83fc-f2a08cc0c748.PNG)

**Comment by jrfnl** [comment]
Eh... yikes.. time for a better host I suppose.

**Comment by Tails128** [comment]
Suggesting to remove "sniffing" from blacklisted third-parties is not the approach I'd suggest or I'd consider "better".

If you think this is not an issue just close the issue, it is undeniable that renaming an established library is not something you can do overnight or something which is easy to do, especially due to third parties writing tutorials for the library with the "old" name and software which already uses the library!

**Comment by gsherwood** [comment]
I'm sorry your account was suspended, but changing the name of this project over that ban is not something I would consider. Hopefully you can sort this out with your host.
