### ISSUE TITLE
Enable pcre.jit for PHP 7.3.x

### ISSUE THREAD

**Issue by gagan0123** [squizlabs/PHP_CodeSniffer#2475]
This is continuation of discussion of https://github.com/squizlabs/PHP_CodeSniffer/issues/2304 for which a partial patch was provided in https://github.com/squizlabs/PHP_CodeSniffer/commit/c09a4e1a2f3f6fe4a628e72b5e61ad35b309ed02 .

Disabling `pcre.jit` although resolved that issue, but loses performance benefits provided by 
  having `pcre.jit` enabled. Underlying cause of failure of child process needs to be examined thoroughly to resolve whats causing child processes to fail when `pcre.jit` is enabled in PHP7.3.x

With PHP 7.3, PCRE was upgraded to PCRE2, so most probable cause seems to be some PCRE2 incompatible regular expression as discussed in the original issue.

**Comment by gsherwood** [comment]
> but loses performance benefits

Note that these are not life changing or anything. On PHPCS itself, the difference is about 0.3-1.2% faster with the PCRE JIT enabled, which is up to 0.1 seconds over an 8.1s run. It's not a noticeable difference in most cases.

> most probable cause seems to be some PCRE2 incompatible regular expression as discussed in the original issue

That's actually not what the original issue is discussing. The issue might very well be core to PHP, which is why various distros (but not homebrew) have disabled the jit by default. Also note that without forking, the regular expressions all run fine, so it doesn't appear to be a simple compatibility issue.

**Comment by gagan0123** [comment]
@gsherwood 

Just doing some maths, assuming PHPCS is being used by at least 10,000 active projects, each having 20 commits a day on an average, having 0.1 seconds delay equates to 5.5 hours of wasted time everyday.

As discussed in original issue https://github.com/squizlabs/PHP_CodeSniffer/issues/2304, there's nothing wrong in PHPCS code, but its just an issue with PHP 7.3 running on Mac systems. I can confirm even with JIT enabled, it works just fine on Ubuntu, Fedora, CentOS and Alpine with PHP 7.3.x. @jrfnl also confirmed it works on Windows as well https://github.com/squizlabs/PHP_CodeSniffer/issues/2304#issuecomment-481304906

Assuming PHPCS runs more on CI servers running those platforms rather than MacOS, its a performance bottleneck we're having to put on this project just because MacOS can't run it with JIT enabled.

I'll look further into this, and keep this issue updated. Going through PHP's source code to figure out if there's anything thats causing MacOS to fail. Once someone will patch the PHP for MacOS, we can enable JIT for everyone.

**Comment by ryancco** [comment]
On this topic (without hijacking too much, hopefully) @gsherwood are you planning on tagging the changes in https://github.com/squizlabs/PHP_CodeSniffer/commit/c09a4e1a2f3f6fe4a628e72b5e61ad35b309ed02 in a release?

**Comment by jrfnl** [comment]
@ryancco Just in case you hadn't seen it: the changes you referred to, were released in v 3.4.2.

**Comment by rowild** [comment]
@gagan0123 Just sharing my experience without knowing, if this is of any help:
I run TYPO3 9 on a Mac 10.13.6 with php 7.3.9. Everything fails. Switching to php 7.2.22 makes everything work again.
In both php.ini files pcre.jit is actually *disabled* (via prepended semicolon), but phpinfo() knows better and shows that it is still enabled (both: 7.2 and 7.3).

![Bildschirmfoto 2019-09-17 um 11 02 09](https://user-images.githubusercontent.com/213803/65027434-a1f48d00-d93a-11e9-9497-f59182c74151.png)
![Bildschirmfoto 2019-09-17 um 11 04 38](https://user-images.githubusercontent.com/213803/65027622-fbf55280-d93a-11e9-9d74-e280ecd07240.png)

(Side info: I restart with `brew services restrat httpd`, `brew services restart php`)

**Comment by gagan0123** [comment]
Closing the issue, because with latest version of PHP 7.3 (7.3.28), this issue does not appear, even with `pcre.jit` enabled.
