### ISSUE TITLE
Add flag that allows phpcs to output a simple list of any files that don't pass the codestyles

### ISSUE THREAD

**Issue by Loupax** [squizlabs/PHP_CodeSniffer#2477]
First of all let me describe the use case I want to cover.

I am running `phpcs --cache=/path/to/cache_file` and this sped up my results from an amount of minutes to an amount of milliseconds.

What I want to do is output a list of any files that don't pass the tests and pass them to PHPCbf so I can really fast correct only any files that might fail.

An example use case:
```
$ phpcs --cache=/path/to/cache_file src -f
file1.php
file2.php
file2.php
...

$ phpcbf $(phpcs --cache=/path/to/cache_file src -f)
```

Is this possible somehow?

**Comment by gsherwood** [comment]
This would normally be done with a custom report, and then by using the `--file-list` command line argument.

You could write your own report class that only output the file paths, or you could write a wrapper script that uses an existing report (json, xml, csv might all be good options) and extracts the file paths into a seperate file for you.

So the process would go something like:
- phpcs src --report=json
- pipe that to some script you've got that takes the json and outputs a file list
- phpcbf --file-list=/path/to/filelist.txt

**Comment by Loupax** [comment]
This is the shell script I came up with:

```
#!/usr/bin/env bash
bin_path=$(dirname "$0")

tmpfile=$(mktemp)
echo "Gathering file list of all files that need corrections..."
php ${bin_path}/../vendor/bin/phpcs --cache=${bin_path}/../var/cache/.phpcs-cache --report=csv ${bin_path}/../src ${bin_path}/../tests -nq | tail -n+2 | cut -d \, -f 1 | cut -d "\"" -f 2 > $tmpfile

if [ -s ${tmpfile} ]
then
    echo "Found $(wc -l < ${tmpfile}) files with violations: Fixing..."
    php ${bin_path}/../vendor/bin/phpcbf --file-list=${tmpfile}
else
    echo "No fixable errors found"
fi
rm ${tmpfile}
```

Looks good enough :)

**Comment by gsherwood** [comment]
Thanks a lot for posting your result. I'll close this for now, but re-open if there is wider need for a built-in solution.
