### ISSUE TITLE
Force DocBlocks for classes methods

### ISSUE THREAD

**Issue by odan** [squizlabs/PHP_CodeSniffer#2487]
Hello! 

I'm trying to force DocBlocks for all class methods. Is there a rule/sniffer to force [DocBlocks](https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md) for class methods that don't have a docblock?

Here is an example:

```php
class Foo
{
    public function setTitle(string $title): void
    {
        $this->title = $title;
    }
}
```

Expected Error message: 

```
ERROR | Missing doc for method Foo::setTitle
```

**Comment by jrfnl** [comment]
Try the `Squiz.Commenting.FunctionComment` sniff ;-)

**Comment by odan** [comment]
Thanks for the tip. :-) It was the `Squiz.Commenting.FunctionComment.Missing` sniff. This sniff in combination with the `doctrine/coding-standard` causes some troubles.
