### ISSUE TITLE
Missing new-line for json output

### ISSUE THREAD

**Issue by kkmuffme** [squizlabs/PHP_CodeSniffer#2488]
When running a for loop over multiple files, each with this command:

>phpcs --standard=$phpcs_rules --report=json "$file" >> json.log 2>> error.log

The json it outputs to json.log is missing the new-line after each json, so my json.log ends up as a long sausage of jsons, instead of 1 json per line.

Obviously I can just add echo " " in the loop to manually add the newline, however this doesn't work when running the above phpcs async/in background with & argument

**Comment by gsherwood** [comment]
Makes sense to add a newline. Thanks.
