### ISSUE TITLE
PHPCS Documentation XSD

### ISSUE THREAD

**Issue by MasterOdin** [squizlabs/PHP_CodeSniffer#2489]
After looking through #1926, https://github.com/squizlabs/PHP_CodeSniffer/pull/2345#issuecomment-453264115, and especially #2213, I'd like to try and help make progress on a proposed XSD for the XML documentation, which in-turn could be used (I'm assuming) to auto-generate/populate the wiki with this information. However, I do think that any finalized XSD will probably require refactoring of the current xml doc files due to the lack of meaningful hierarchy of the connection between codes (and their name), their description, and a code sample.

From my understanding, for every Sniff, for any issue found, it has a unique Code, even if the Sniff only has one potential error/warning it'll catch (e.g. [Generic/Classes/DuplicateClassName](https://github.com/squizlabs/PHP_CodeSniffer/blob/af1bd4e/src/Standards/Generic/Sniffs/Classes/DuplicateClassNameSniff.php) only return "Generic.Classes.DuplicateClassName.Found").

Each of these Errors can be either an error or a warning.

Using that (and the above comment), here is an initial proposal.

```
<documentation>
    <title>Human name of sniff (e.g. Control Signature)</title>
    <name>Quantified name of sniff (e.g. Squiz.ControlStructures.ControlSignature)</name>
    <description>String describing what the Sniff is looking for</description>
    <since>Version String</since>   
    <properties>
        <property>
            <name>name of property in code (e.g. requiredSpacesBeforeColon)</name>
            <description>string description</description>
            <type>int | bool | array | string</type>
            <default></default>
            <since>Version String</since>
        </property>
    </properties>
    <code>
        <title>Human readable name of code (e.g. Space after closing bracket)</title>
        <name>Full name of code (e.g. Squiz.ControlStructures.ControlSignature.SpaceAfterCloseBrace)</name>
        <type>warning | error</type>
        <fixable>true | false</fixable>
        <description>String describing what the code is looking for</description>
        <code_comparison>
            <code title="Valid: string for why code is valid">
            </code>
            <code title="Invalid: string for why code is invalid">
            </code>
        </code_comparison>
    </code>
</documentation>
```

Looking through the current docs, I found the key "standard" to be confusing and makes the term overloaded (is the thing containing the sniffs a standard, or the sniff itself a standard, or each possible code of the sniff a standard?) and so went with a different keyword both to describe what a given sniff does (description) and then the individual things the sniff checks for (code, though rule might be better?).

I do think it's important to include the full name of the Sniff and each Code within this XML important as it makes searching this repo possible for the information as well as wherever this gets generated to for a given sniff/code.

**Comment by gsherwood** [comment]
Thanks for taking a look at this. I've put any documentation changes on hold as there is a concurrent project about product documentation ongoing where I work and I will probably use the format selected to continue PHPCS docs. This will include how the docs are written and where they are hosted. They will definitely not be XML, so I suspect the entire XML format will disappear in favour of an easier syntax to work with (I don't know what it is yet).

**Comment by MasterOdin** [comment]
I guess the follow-up question here is what could be done to help you bootstrap existing (and new) documentation into this future format. Is there any indication of how this new format might look or the sorts of data you'd like to display in it? Is there a timeline of when you think you'll restart and allow documentation changes?

**Comment by gsherwood** [comment]
> Is there any indication of how this new format might look or the sorts of data you'd like to display in it? Is there a timeline of when you think you'll restart and allow documentation changes?

I have no idea.

**Comment by MasterOdin** [comment]
Closing this issue as it sounds like the XML format will not continue and so the XSD is worthless in turn. Feel free to ping me if you would like documentation notes in some designated format (either in the first post of this issue, or https://github.com/squizlabs/PHP_CodeSniffer/issues/1926#issuecomment-406856679, or some other format) or if/when you have set what the new format will be and I will help with writing documentation.

**Comment by jrfnl** [comment]
@MasterOdin FYI: an XSD schema for the Docs XML files is now available via [PHPCSDevTools](https://github.com/PHPCSStandards/PHPCSDevTools) 1.2.0 (as it is unclear when the other format will be available, so we may as well have the XML files be valid in the mean time).
