### ISSUE TITLE
Non-letters can trigger Drupal.Commenting.DocComment.ShortNotCapital

### ISSUE THREAD

**Issue by lkmorlan** [squizlabs/PHP_CodeSniffer#2490]
This comment `'0' won't work as a key for checkboxes` triggers 
Drupal.Commenting.DocComment.ShortNotCapital. This should only be triggered for things that are lower-case, not characters that do not have case.

Related issues: #377, #855.

**Comment by jrfnl** [comment]
@lkmorlan Sorry, but you've reported this to the wrong repo. The Drupal standard is not part of PHPCS, but an external standard for PHPCS which is maintained separately by a different team.

When you report this issue to them, you may want to mention to them (draft) PR #2456 as that PR introduces some new utility methods which the Drupal sniff could use which would solve your issue (once the PR here has been merged, a new PHPCS release has been tagged and providing the Drupal standard would be willing to up the minimum PHPCS requirement).
For more info on the new methods, you can point them here: https://gist.github.com/jrfnl/16e1d64d9ec8efec7729e9bfbb05201a#in-php_codesnifferutilsniffsorthography

**Comment by lkmorlan** [comment]
Sorry about that. Thanks for the suggestions.

**Comment by lkmorlan** [comment]
Follow-up: https://www.drupal.org/project/coder/issues/2925237
