### ISSUE TITLE
Generic.CodeAnalysis.EmptyPhpStatement should look for more empty statement

### ISSUE THREAD

**Issue by VincentLanglet** [squizlabs/PHP_CodeSniffer#2493]
In the EmptyPhpStatement, the main condition is
```
if ($prevNonEmpty === false
    || ($tokens[$prevNonEmpty]['code'] !== T_SEMICOLON
    && $tokens[$prevNonEmpty]['code'] !== T_OPEN_TAG
    && $tokens[$prevNonEmpty]['code'] !== T_OPEN_TAG_WITH_ECHO)
) {
    return;
}
```

Which means it look for errors like this
```
something();;.
```

I think it should check also for errors like this
```
if (something) { something; };
```
Am I wrong or everytime we have a `}`, the `;` should removed ?

The condition should be
```
if ($prevNonEmpty === false
    || !in_array($tokens[$prevNonEmpty]['code'],  [T_SEMICOLON, T_CLOSE_CURLY_BRACKET, T_OPEN_TAG, T_OPEN_TAG_WITH_ECHO])
) {
    return;
}
```

I can make the PR

**Comment by jrfnl** [comment]
> Am I wrong or everytime we have a }, the ; should removed ?

Sorry, but yes, you're wrong. Blindly removing the `;` after every `}` would break closures and anonymous classes.

```php
$closure = function($a) { echo $a };
```

**Comment by VincentLanglet** [comment]
@jrfnl Thanks for your answer, since I never use closure, I didn't think about this case.

Is there a way to remove `;` in these case
```
if (foo) {
    return;
};
for ($i = 0; $i < 10; $i++) {
    echo $i;
};
```
And keeping it for anonymous functions/classes ?

**Comment by jrfnl** [comment]
> Is there a way to remove `;` in these case and keeping it for anonymous functions/classes ?

That is possible, but in that case, the curly brace needs to be examined more closely to see whether or not it is a `scope_closer` and if so, what the `scope_owner` is.

**Comment by VincentLanglet** [comment]
Ok, I understand what you mean. I didn't found a `scope_owner` but a `scope_condition`.

If `prevNonEmpty` is a `T_CLOSE_CURLY_BRACKET`, I should check for `$tokens[$tokens[$prevNonEmpty]['scope_condition']]['type']`. I'll get `T_FUNCTION`, `T_IF`, `T_FOR`, `T_ANON_CLASS`, `T_WHILE`, and maybe others.

I'll try a PR

**Comment by jrfnl** [comment]
@VincentLanglet Looking forward to the PR :smile: 
When creating it, please keep in mind that not all curlies will have a `scope_condition`, i.e.:
```php
echo $a{0};
```

**Comment by VincentLanglet** [comment]
@jrfnl Done ! https://github.com/squizlabs/PHP_CodeSniffer/pull/2495
