### ISSUE TITLE
Ignored files by @codingStandardsIgnoreFile are still processed

### ISSUE THREAD

**Issue by Majkl578** [squizlabs/PHP_CodeSniffer#2505]
Apparently it's not enough to specify `@codingStandardsIgnoreFile` in a file to be ignored by PHPCS. The file is still analyzed, only the report is suppressed.
This is a huge problem for generated code which could cause a lot of time to be spent on useless analysis.

Workaround is setting up file excludes.

**Comment by gsherwood** [comment]
When a file begins to process, PHPCS opens the file and reads the first 2 lines to see if there is an ignore file annotation at the top. If there is, it marks the file as ignored and doesn't even tokenise it.

If it can't find that annotation up the top, it tokenizes the file and begins to loop over the tokens. If it finds an ignore file annotation during that loop, it immediately stops processing the file, clears all errors, marks the file as ignored, and moves on.

If you are generating code files and want them ignored without using exclusions, start the file with:
```
<?php
// @codingStandardsIgnoreFile
```
Or the newer non-deprecated syntax:
```
<?php
// phpcs:ignorefile
```
But if your generated files are all inside a directly, or all follow a pattern, it is still better to using an exclude pattern inside your project's ruleset.

Does that help?

**Comment by Majkl578** [comment]
Hmm in this case, Codeception generates this annotation in the header but not in first 2 lines: https://github.com/Codeception/Codeception/blob/3daf21d311a1379546640fe9ca699c7090526585/src/Codeception/Lib/Generator/Actions.php#L13

But it seems strange that tokenizing the file would take so long, will try to see what's going on.

**Comment by gsherwood** [comment]
Closing as nothing more came from this.
