### ISSUE TITLE
PHPCS - Code Formatting and Quick Fix

### ISSUE THREAD

**Issue by TNHSAesop** [squizlabs/PHP_CodeSniffer#2510]
I've installed this extension and it's giving me a zillion errors mostly related to formatting.  Are there recommended and supplementary extensions for the WordPress coding standard to take advantage of the alt + shift + f auto format feature in VS Code?  Right now the auto format auto formats with spaces but phpcs WordPress standard requires tabs for instance.  There also seems to be lots of issue detection in code but the quick fix options aren't available.  

I'm wondering if there are supplemental extensions to fix these problems or if these are just feature gaps?

**Comment by jrfnl** [comment]
@TNHSAesop As this question is about the WordPress Coding Standards, this is not the right repo to ask in. This is the repo for PHPCS itself, not for WPCS. Please ask here: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/

Also have a look at the [WPCS Readme](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/#rulesets) regarding the various standards available and the [WPCS wiki](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki) to see about configuring WPCS to work with your IDE.
