### ISSUE TITLE
Squiz.PHP.NonExecutableCode does not support alternate SWITCH control structure

### ISSUE THREAD

**Issue by sybrew** [squizlabs/PHP_CodeSniffer#2512]
When using the alternative control structures, you'll encounter these issues.

```php
$_while = 1;

for ( $a = 0; $a++ < 1; ) :
	foreach ( [ 1 ] as $b ) :
		while ( $_while-- ) :
			if ( 1 ) :
				switch ( 1 ) :
					default:
						echo 'yay, we made it!';
						break; // trigger
				endswitch; // Squiz.PHP.NonExecutableCode.Unreachable
			endif; // Squiz.PHP.NonExecutableCode.Unreachable
		endwhile; // Squiz.PHP.NonExecutableCode.Unreachable
	endforeach; // Squiz.PHP.NonExecutableCode.Unreachable
endfor; // Squiz.PHP.NonExecutableCode.Unreachable
```

That's all 😄

**Comment by jrfnl** [comment]
@sybrew With just the code sample you've provided, I cannot reproduce the issue at all.

Could you show the wider context this snippet is used in ?

**Comment by sybrew** [comment]
In WordPress, for all long code blocks, we're urged to use the alternative syntax control.
I use it more often than I'm "required", as it helps with readability.

Whenever a break is used, as in `switch`, `while`, `foreach`, and `for`, this fires on the closing control structure: `end*`.

![image](https://user-images.githubusercontent.com/7662236/58254166-7259bd80-7d6a-11e9-99b2-662d7c060899.png)

**Comment by jrfnl** [comment]
Found it. PR #2518 should fix this.
