### ISSUE TITLE
Review that existing sniffs will handle PHP 7.4 typed properties correctly

### ISSUE THREAD

**Issue by jrfnl** [squizlabs/PHP_CodeSniffer#2517]
Follow up ticket after #2413.

Open action points:

- [ ] Adjust property docblock sniffs to allow finding the docblock of typed properties.
- [ ] Check that other sniffs which deal with properties handle typed properties correctly by adding unit tests and if necessary, adjusting the code within the sniff.

FYI: If/when PR #2456 gets merged, addressing action point 1 will be dead easy as it will just be a minor adjustment to one method in one of the new utility classes.

**Comment by gsherwood** [comment]
I tested all the var sniffs I could find and added some tests. Only 1 needed changing as it was looking backwards for a comment.
