### ISSUE TITLE
Custom sniff outside vendor dir

### ISSUE THREAD

**Issue by delboy1978uk** [squizlabs/PHP_CodeSniffer#2520]
According to your docs:
```
If you want your standard to be shown as installed, create the MyStandard directory 
inside the PHP_CodeSniffer install
```
As I'm using Composer to manage dependencies, this is not an option.
Can we define the location in the XML?

**Comment by dingo-d** [comment]
If you are creating a custom sniff, shouldn't you be creating a custom standard? Easier to maintain it that way imo.

**Comment by jrfnl** [comment]
@delboy1978uk The DealerDirect PHPCS Composer plugin can sort all that out for you, have a look and see if that works for you: https://github.com/Dealerdirect/phpcodesniffer-composer-installer/

**Comment by gsherwood** [comment]
If you want to reference a sniff by path, you can do that in an XML ruleset. Some examples [from the wiki](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-Ruleset):
```xml
 <!--
    Include all sniffs in an external standard directory. Note
    that we have to specify the full path to the standard's
    directory because it does not exist inside the PHP_CodeSniffer
    install directory.
 -->
 <rule ref="/home/username/standards/mystandard"/>

 <!--
    Include everything in another ruleset.xml file. This is
    really handy if you want to customise another developer's
    custom standard. They just need to distribute their single
    ruleset file to allow this.
 -->
 <rule ref="/home/username/standards/custom.xml"/>

 <!--
    Relative paths can also be used everywhere absolute paths are used.
    Make sure the reference starts with ./ or ../ so PHP_CodeSniffer
    knows it is a relative path.
 -->
 <rule ref="./standards/mystandard"/>
 <rule ref="../username/custom.xml"/>
```
If you want a custom standard to appears as "installed", which means you can reference it by name in the XML rather than by path, you can use the composer installer plugin that @jrfnl linked to, or you can [set a config option](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options#setting-the-installed-standard-paths) in PHPCS, but you can't set anything in the XML itself as you'd be using absolute or relative paths anyway.

**Comment by delboy1978uk** [comment]
> 
> 
> @delboy1978uk The DealerDirect PHPCS Composer plugin can sort all that out for you, have a look and see if that works for you: https://github.com/Dealerdirect/phpcodesniffer-composer-installer/

thanks i'll have a look next time i'm back on this task :-)

**Comment by delboy1978uk** [comment]
> 
> 
> If you want to reference a sniff by path, you can do that in an XML ruleset. Some examples [from the wiki](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-Ruleset):
> 
> ```
>  
>  <rule ref="/home/username/standards/mystandard"/>
> 
>  
>  <rule ref="/home/username/standards/custom.xml"/>
> 
>  
>  <rule ref="./standards/mystandard"/>
>  <rule ref="../username/custom.xml"/>
> ```
> 
> If you want a custom standard to appears as "installed", which means you can reference it by name in the XML rather than by path, you can use the composer installer plugin that @jrfnl linked to, or you can [set a config option](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options#setting-the-installed-standard-paths) in PHPCS, but you can't set anything in the XML itself as you'd be using absolute or relative paths anyway.

I didn't realise we could specify a path, I'll see if we can use that for now before looking at the composer solution.

Thanks everyone!
