### ISSUE TITLE
Custom ruleset is not compatible with project path

### ISSUE THREAD

**Issue by TomPradat** [squizlabs/PHP_CodeSniffer#2521]
Let's say i have a custom rule named "Toto".

If my project path has some path like `workspace/toto/project`, then this preg_match always evaluates to true.

https://github.com/squizlabs/PHP_CodeSniffer/blob/8ff9283ab30cd296293b57039efe573aaf669862/src/Filters/Filter.php#L270

It makes me impossible to use exclude-patterns for this custom rule 'Toto' because it ignores all my files.

For example :
```xml
<rule ref="Toto">
        <exclude-pattern>src/SomeFile.php<exclude-pattern>
</rule>
```

**Comment by jrfnl** [comment]
@TomPradat I believe this was fixed already via PR #2392, which will be included in the PHPCS 3.5.0 release.

**Comment by gsherwood** [comment]
@TomPradat are you able to test if that fix works for you?

**Comment by TomPradat** [comment]
Indeed it works on 8ff9283ab30cd296293b57039efe573aaf669862.

I should have checked it earlier. Thanks and sorry for the inconvenience

**Comment by gsherwood** [comment]
Thanks a lot for checking the fix.
