### ISSUE TITLE
XML report format has bad syntax on Windows

### ISSUE THREAD

**Issue by mvorisek** [squizlabs/PHP_CodeSniffer#2526]
Exactly the same source code of version 3.4.2 with default config with xml output format produces expected results on Linux, but bad results on Windows:

Windows output example:
```
<?xml version="1.0" encoding="UTF-8"?>
<phpcs version="3.4.2">
xml version="1.0" encoding="UTF-8"?>
<file ...removed... file>
xml version="1.0" encoding="UTF-8"?>
<file ...removed... file>
xml version="1.0" encoding="UTF-8"?>
<file ...removed...
```

Expected/Linux output:
```
<?xml version="1.0" encoding="UTF-8"?>
<phpcs version="3.4.2">
<file ...removed... file>
<file ...removed... file>
<file ...removed...
```

**Comment by jrfnl** [comment]
A quick check shows me that this is related to #1189 and that this issue (on Windows) was introduced by https://github.com/squizlabs/PHP_CodeSniffer/commit/8a18d4049dda4349cfe01dffc1420bbce31d304e

**Comment by jrfnl** [comment]
PR #2527 should fix this. @mvorisek would you be able to test the patch and confirm ?

Also: would be useful to have confirmation that this patch doesn't negatively impact users on MacOS and Linux as well, so if anyone else wants to test and confirm, please do!

**Comment by mvorisek** [comment]
The patch fixes it, but what about:
```
$content = preg_replace('~^\s*<\?xml[^<>]+\?>\s*~', '', $content);
```
It is very readable and it will work on any platform. The performance impact should be minimal.

**Comment by jrfnl** [comment]
@mvorisek Why make things more complicated than needs be ?  The regex presumes certain content and case of the content, while the current patch doesn't.

**Comment by mvorisek** [comment]
@jrfnl But I would say that is actually right. We expect exactly some kind of content and remove it. If something different is presented (do you know what other might?) it is right to leave the content there than to remove it.
