### ISSUE TITLE
Title spacing not rendering correctly in the text generator

### ISSUE THREAD

**Issue by marconmartins** [squizlabs/PHP_CodeSniffer#2536]
The following code renders "associative array" as "associativearray" when the text generator is used.

```xml
<code_comparison>
    <code title="Valid: Comma after item on their own line (associative array).">
    <![CDATA[
$arr = <em>[</em>
    1 => 'value',
    2 => <em>[</em> 1 <em>]</em>,
    3 => 'c',
<em>]</em>;
        ]]>
    </code>
    <code title="Invalid: Missing comma after item on their own line (associative array)">
    <![CDATA[
$arr = <em>[</em>
    1 => 'value',
    2 => <em>[</em> 1 <em>]</em>,
    3 => 'c'
<em>]</em>;
        ]]>
    </code>
</code_comparison>
```
<img width="359" alt="Screenshot 2019-06-20 at 13 08 43" src="https://user-images.githubusercontent.com/5478039/59855509-c06bdc00-937d-11e9-85af-5da83ed775fd.png">

**Comment by gsherwood** [comment]
I think this was fixed by this commit: https://github.com/squizlabs/PHP_CodeSniffer/commit/19de46142f3e337a1f45b9be2cbe0b6c2722ec46

The fix is unreleased, but it would be great if you could test the fix or latest master.

**Comment by jrfnl** [comment]
I have tested this with @marconmartins' PR and can confirm that 19de461 fixes this, so consider this issue fixed,

**Comment by gsherwood** [comment]
Closing. Going to trust @jrfnl on this one.
