### ISSUE TITLE
Option to run phpcs as if in a folder (setting config path)

### ISSUE THREAD

**Issue by VincentLanglet** [squizlabs/PHP_CodeSniffer#2540]
I have this project structure
```
project
-- symfony
----phpcs.xml.dist

When I'm in the project folder, I'd like to run something like
```
phpcs -c symfony/
```
Which is the same as
```
cd symfony && phpcs
```

For example phpunit has this option (https://phpunit.readthedocs.io/fr/latest/textui.html)

Does this option exist ?

**Comment by jrfnl** [comment]
Sound like you are looking for PHPCS to run with relative paths and in my experience that works fine.

Try this:
```bash
phpcs ./symfony/ --standard=./symfony/phpcs.xml.dist
```

**Comment by VincentLanglet** [comment]
> Try this:
> 
> ```shell
> phpcs ./symfony/ --standard=./symfony/phpcs.xml.dist
> ```

```
phpcs --standard=./symfony/phpcs.xml.dist
```
Is the solution

```
phpcs ./symfony/ --standard=./symfony/phpcs.xml.dist
```
Was overriding the config
```
    <file>bin/</file>
    <file>config/</file>
    <file>public/</file>
    <file>src/</file>
    <file>tests/</file>
```

Thanks !
I was looking a `configuration` option. I didn't think the `phpcs.xml.dist` was the standard.

**Comment by jrfnl** [comment]
Excellent! Glad to hear it worked.

Here's the more detailed info about providing `--standard`s to PHPCS: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Usage#specifying-a-coding-standard
