### ISSUE TITLE
How do I disable "only one argument is allowed per line"

### ISSUE THREAD

**Issue by kwhat** [squizlabs/PHP_CodeSniffer#2555]
Hi,

I cannot figure out how to disable the check for Only one argument is allowed per line in a multi-line function call.  I am running `phpcs --standard=PSR1,PSR2 --exclude=Squiz.Functions.FunctionDeclarationArgumentSpacing,Generic.Functions.FunctionCallArgumentSpacing,Squiz.Functions.FunctionDeclaration,Squiz.Functions.MultiLineFunctionDeclaration src/ tests/` and I keep getting this error.  

Any help would be appreciated.

**Comment by kwhat** [comment]
Well, I think the rule I was looking for is called "PSR2.Methods.FunctionCallSignature" although I'm still unsure how I was suppose to figure that out without this bug tracker.

**Comment by gsherwood** [comment]
If you run PHPCS with the `-s` command line argument, it will show the error code next to each error message. You can then exclude that specific code using a custom ruleset, or just exclude the entire sniff (the first 3 parts of the code) using the CLI argument.

**Comment by kwhat** [comment]
Awesome! That's much easier than digging though the code.  Thanks!
