### ISSUE TITLE
[question] about  Windows

### ISSUE THREAD

**Issue by lenamtl** [squizlabs/PHP_CodeSniffer#2556]
Hi,

I d'like to know if there are specific instructions to use it on Windows?
Let say I'm using Wampserver ?

Thanks

**Comment by jrfnl** [comment]
No specific instructions. Have a look at the [Readme](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/README.md) for installation options or the [Wiki](https://github.com/squizlabs/PHP_CodeSniffer/wiki) for usage instructions.

**Comment by gsherwood** [comment]
Are you having a specific problem you need help with?

**Comment by lenamtl** [comment]
Hi,
Sorry for the delay..
I was not able to run PHP in command line on Windows / Wampserver (I guess it is a Wampserver issue not a PHP_Code_Sniffer issue.
So I installed it on Linux using Composer and this is working fine.

Thanks

**Comment by jrfnl** [comment]
@lenamtl I'm running it on Windows on Wampserver, so it definitely can work.

**Comment by lenamtl** [comment]
@jjrfnl I was getting an unrecognized error...
If you have any info that can help me to use it on Windows Wampserver I would appreciate

**Comment by jrfnl** [comment]
@lenamtl I'll try to help, if I can. How did you try to set it up ? PEAR ? Composer global install ?

**Comment by lenamtl** [comment]
I 'm using packages that were already generate by Composer (from another computer)
Because I don't run Composer itself on my computer.

**Comment by jrfnl** [comment]
@lenamtl IIRC the current versions of WampServer come with Composer already installed. If you then do a `composer global install squizlabs/php_codesniffer`, the `phpcs` command should be available system-wide.

If the version of WampServer you are using does not have Composer installed, there are two other options I can suggest:
* Install Composer [via the Windows Installer](https://getcomposer.org/doc/00-intro.md#installation-windows) and then do the above anyway; òr
* Download the latest version of PHPCS as a `phar` file, make sure you place the file in a directory which is in the Windows `PATH` variable or add the directory where you placed it to the `PATH`.

Either way, you should then have the `phpcs` command available globally on your system.
