### ISSUE TITLE
PHPCBF format selection

### ISSUE THREAD

**Issue by dev4xy** [squizlabs/PHP_CodeSniffer#2557]
Hello

PHPCBF in VSCode only have `Format Document` in context menu. But I need `Format Selection`.

![Format Document](https://user-images.githubusercontent.com/36417203/61552001-f333ed80-aa6b-11e9-90bf-5832428976ac.png)

Also **⌘K, ⌘F** short code not work for this.

How can I do this?
Or Please add this features.

Thank you.

**Comment by jrfnl** [comment]
That sounds to me like something to ask the developers of VSCode...

**Comment by gsherwood** [comment]
Closing as this is something you need to speak to the VSCode team about - that formatting feature is not maintained by this project.
