### ISSUE TITLE
Author tag email validation doesn't support all TLDs

### ISSUE THREAD

**Issue by ScottJWalter** [squizlabs/PHP_CodeSniffer#2566]
The code validating the email address in the `@author` tag doesn't appear to support all current top level domains (TLDs), specifically `.consulting`

## To Duplicate ##

* Create an `@author` tag line with a "more traditional" email address (e.g. "Code Author <author@gmail.com>"
* Note that CS validates the line
* Change the line to "Code AUthor <author@gmail.consulting>"
* Note that CS errors the line

I've tried several different combinations of other new TLDs and they all seem to work.  `.consulting` is the only one I've found so far that doesn't.

**Comment by jrfnl** [comment]
@ScottJWalter Thanks for reporting. Confirmed. PR #2568 should fix this.
