### ISSUE TITLE
Token type documentation

### ISSUE THREAD

**Issue by VincentLanglet** [squizlabs/PHP_CodeSniffer#2576]
### Context
Recently, I wanted to write a rule about function return type.
```
public function foo(): ?string
```

But I didn't know the type of the `:` or `?` token. After some `var_dump`, I found it was `T_COLON` and `T_NULLABLE`. But I was asking myself "Is it the same than the `:` or `?`token in `$foo ? $a : $b`. After some others `var_dump` it seems like it was `T_SEMI_COLON` or `T_INLINE_THEN` in this case.

Every time I want to write a new rules, it starts like this. And I'm never sure about the token type condition.

### Doc request
Would it be possible to have a documentation of all the possible token type with an example ?

**Comment by dingo-d** [comment]
This is a start:

https://www.php.net/manual/en/tokens.php

But I agree, I often wonder what all the tokens mean. You can also find the tokens here

https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Util/Tokens.php
