### ISSUE TITLE
README.md: A lot of good installation instructions, and no instructions for actual use.

### ISSUE THREAD

**Issue by tchalvak** [squizlabs/PHP_CodeSniffer#2581]
I would recommend adding a section to the README for instructions on a good example command usage.  For instance, a trivial usage of `phpcs ./` just fatal errors on memory size on a clean wordpress install.  Without a clear, simple starting usage suggestion, it's much more difficult to determine whether individual configuration is the problem or otherwise debug.

**Comment by dingo-d** [comment]
There is a [wiki](https://github.com/squizlabs/PHP_CodeSniffer/wiki) filled with examples and explanations 🙂

**Comment by gsherwood** [comment]
@tchalvak is the stuff in the wiki what you were looking for in terms of a basic example of usage?

There isn't going to be any documentation about how to diagnose a fatal memory error in the docs though.

**Comment by tchalvak** [comment]
Yeah, the usage page there was pretty much what I was looking for.  I think there could be some major value in clarifying the expected usage of the command (very very briefly) in the README before recommending going to a second site for that.  Would y'all be open to a trivial PR to that effect?

**Comment by gsherwood** [comment]
> I think there could be some major value in clarifying the expected usage of the command (very very briefly) in the README before recommending going to a second site for that

Yeah, I'd be interested in seeing what you recommend here. Something basic that doesn't need to change much between PHPCS releases would probably be quite helpful. Then a link off to more documentation.

**Comment by tchalvak** [comment]
@gsherwood Created a PR for an example of the trivial change to the README that I mean.
https://github.com/squizlabs/PHP_CodeSniffer/pull/2583
