### ISSUE TITLE
phpcs fails to correctly see any files

### ISSUE THREAD

**Issue by davidfavor** [squizlabs/PHP_CodeSniffer#2584]
Seems possibly related to #2422.

```
net16 # phpcs --version
PHP_CodeSniffer version 3.5.0 (stable) by Squiz (http://www.squiz.net)

net16 # phpcs -i
The installed coding standards are PSR12, PSR2, MySource, PEAR, Zend, Squiz, PSR1 and PHPCompatibility

net16 # cat phpinfo.php
<?php
print_r (phpinfo());
?>

net16 # phpcs --standard=PHPCompatibility --encoding=utf-8 --extensions=php,inc,lib,js,css,html --runtime-set 7.3 ./phpinfo.php
ERROR: You must supply at least one file or directory to process.

Run "phpcs --help" for usage information
```
I've used phpcs many times. First time I've ever hit this problem.

I'm fairly adept on the command line, so any debug info you'd like me to provide or actions you'd like me to take, just let me know.

**Comment by jrfnl** [comment]
`--runtime-set` expect three parameters, you've passed two (missing the name of the config variable you are setting: `testVersion`), so the filename is being interpreted as the third instead of as a file.

Try:
```bash
phpcs --standard=PHPCompatibility --encoding=utf-8 --extensions=php,inc,lib,js,css,html --runtime-set testVersion 7.3 ./phpinfo.php
```

**Comment by davidfavor** [comment]
Duh...

I fat fingered the command.

Thanks!
