### ISSUE TITLE
Files failed to fix

### ISSUE THREAD

**Issue by NorthernDeveloperUK** [squizlabs/PHP_CodeSniffer#2587]
Hi, I recently acquired a project, I'm currently working on bringing it up to the latest coding standards, my first port of call was to run it through PHPCS, all files were sorted with the exception of these ones, although they aren't important as they are just javascript files, the rest of the javascript files were fixed, but these weren't and I thought I should attach them here in case there's a bug which could be fixed, but I welcome any questions/comments.

> PHPCBF RESULT SUMMARY
> ----------------------------------------------------------------------
> FILE                                                  FIXED  REMAINING
> ----------------------------------------------------------------------
> /home/linux/Desktop/broken/bootstrap.js               FAILED TO FIX
> /home/linux/Desktop/broken/carousel.js                FAILED TO FIX
> /home/linux/Desktop/broken/button.js                  FAILED TO FIX
> /home/linux/Desktop/broken/jquery-ui.js               FAILED TO FIX
> /home/linux/Desktop/broken/modal.js                   FAILED TO FIX
> ----------------------------------------------------------------------
> A TOTAL OF 22634 ERRORS WERE FIXED IN 5 FILES
> ----------------------------------------------------------------------
> PHPCBF FAILED TO FIX 5 FILES
> ----------------------------------------------------------------------
> 
> Time: 15 mins, 9.82 secs; Memory: 484.27MB

I have attached a log which indicates the files could be fixed as they have [ X ] for the lines, but as can be seen above they failed to fix.

[broken-files.zip](https://github.com/squizlabs/PHP_CodeSniffer/files/3516965/broken-files.zip)

**Comment by gsherwood** [comment]
PHPCS is not good at checking JS or CSS files because the tokenizer has not kept up with new syntax. I've scheduled the removal of this feature for version 4 and don't think it is worth attempting to fix any issues that come up in version 3 given the lack of usage this feature gets.

I suggest not checking JS or CSS files with PHPCS. Use a purpose-built tool for JS files instead, like eslint.

**Comment by NorthernDeveloperUK** [comment]
Thanks for the feedback, I'll be sure to check eslint out.

**Comment by gsherwood** [comment]
I'm going to close this as a known issue but not something I'm going to fix due to other priorities and my intention to remove the feature. Although happy to accept a PR if anyone else wants to look into it.
