### ISSUE TITLE
Require preg_quote for variables in preg_ functions

### ISSUE THREAD

**Issue by kkmuffme** [squizlabs/PHP_CodeSniffer#2592]
It would be great if there was a sniff for preg_ functions (https://www.php.net/manual/en/ref.pcre.php) that would throw an error for variables used in the match that are not enclosed in preq_quote:

`preg_match( '/asd' . $my_var . '/, ... )`

should be:
`preg_match( '/asd' . preg_quote( $my_var, '/' ) . '/, ... )`

Ideally also require the 2nd arg for preg_quote

**Comment by jrfnl** [comment]
@kkmuffme FYI: [WordPressCS](https://github.com/WordPress/WordPress-Coding-Standards) already has a sniff checking that the second argument is passed to `preg_quote()` and will have a sniff checking for use of `preg_quote()` where appropriate in the future too.

Not sure, but this might be a little too specific for PHPCS itself.

**Comment by kkmuffme** [comment]
@jrfnl thanks I am aware of that, that's why I thought it would make sense to include this additional check when checking the existence of preg_quote at all.

Since forgetting to use preg_quote for variables in preg_ functions is a common cause for errors (& PHP notices) I thought it would make sense in a general context.

If you know any phpcs plugin/ruleset where it would make more sense in your opinion, I would be happy to open a ticket there.

**Comment by gsherwood** [comment]
> Not sure, but this might be a little too specific for PHPCS itself

Feels a bit specific based on existing sniffs that are in there. I could be convinced otherwise.
