### ISSUE TITLE
Add T_BACKTICK to JS tokenizer

### ISSUE THREAD

**Issue by rebeccahum** [squizlabs/PHP_CodeSniffer#2594]
It would be nice if we can add `T_BACKTICK` in the JS tokenizer since template literals use backticks.

**Comment by gsherwood** [comment]
I'm planning on [removing support ](https://github.com/squizlabs/PHP_CodeSniffer/issues/2448) for JS and CSS tokenizing in version 4, so I'm not making any changes to the existing feature set. I suggest looking into dedicated JS linting tools like eslint.

**Comment by michelgokan** [comment]
@gsherwood one can simply add `<exclude-pattern>*\.(inc|css|js)</exclude-pattern>` in the rulesets, but then `Generic.Debug.ESLint` will not be effective on js files anymore.
