### ISSUE TITLE
Not using basepath results in write error

### ISSUE THREAD

**Issue by TonyGravagno** [squizlabs/PHP_CodeSniffer#2599]
Ref #1526. When arg "basefile" is not specified at the CLI, its value is assigned with the path to the folder of the arg "standard". So the following line gets executed:
https://github.com/squizlabs/PHP_CodeSniffer/blob/a10963bcd62286928e0d8a2f5caee92de1eb3354/src/Reports/Cbf.php#L86
The resulting path is corrupted, and the file_put_contents on line 90 aborts.

To reproduce, use this command-line:

```phpcbf -p -v -vv -vvv --standard="C:\path1\to\ruleset.xml" "C:\path2\to\code.php"```

If path1 and path2 are the same, or the code path is relative, it works, because replacing the path of path2 with path1 is valid. I believe it also works if the code.php is just a filename, relative to standard, which I think was the issue addressed by #1526.

But if the paths are not the same, basepath gets assigned to "C:\path1\to\". That gets prefixed onto the code path to become "C:\path1\to\C:\path2\to\code.php".

The temporary solution is to set basepath="" in the command-line or in config files.
I looked for places where config->basepath is assigned, but I was unable from just looking at code to confirm 100% where the standard value was assigned to it, so no PR, sorry. One guess is that in the [stripBasepath function](https://github.com/squizlabs/PHP_CodeSniffer/blob/9ae59b2b73550d86710a08befeeef5e74d9fbdc9/src/Util/Common.php#L113), a passed-in default is assigned to the basepath if basepath is empty. I'm thinking the issue occurs if/when standard and basepath are passed in together.

How could this have gone for so long with no one noticing? :confused:

**Comment by jrfnl** [comment]
@TonyGravagno Looks like you're on Windows. I've just tried to reproduce the issue on Windows 7, but haven't been able to. All seems to work fine and target file gets overwritten as expected.

Could you provide more information like the PHPCS version you are using, the ruleset and the `code.php` file and possibly more details on the difference between the paths used, so someone can try to reproduce this with a higher chance of succeeding ?

**Comment by TonyGravagno** [comment]
Completely understood. I will assemble all info as time permits. Thanks.

**Comment by TonyGravagno** [comment]
Reloaded PHPCS and am testing as possible. While I'm into this and looking into PHPCS code for another challenge, is there a forum somewhere to discuss the code and how to use a few of the options? I don't want to put such inquiries in an "issue" when I just have questions. Thanks!

**Comment by gsherwood** [comment]
> is there a forum somewhere to discuss the code and how to use a few of the options?

There is nowhere to get that kind of help. Best to ask questions on a related issue.

If you are just looking around in general you can email me directly (gsherwood at squiz dot net) but I can sometimes take a while to reply, unless I happen to be working on PHPCS that day.

**Comment by TonyGravagno** [comment]
It's going to take a while before I can get back into this - too many other projects. I did take a lot of time to verify it, but I strongly sense that this was my own problem, perhaps related to a specific VSCode extension that wrapped the functionality. I'm closing this as invalid, and I or someone else can re-open if it's a verified issue. Thank you Very much for all of the effort on this fine software.

About Q&A, please consider a gitter.im channel. I suspect it will draw some attention, for better or worse. :)

**Comment by gsherwood** [comment]
> About Q&A, please consider a gitter.im channel

There is one: https://gitter.im/squizlabs/PHP_CodeSniffer

But there is not an active community of people providing answers and I'm generally too busy to provide very quick feedback, so an instant messaging platform doesn't work very well in this case.
