### ISSUE TITLE
phpcs: Xdebug requires Zend Engine API version 320151012

### ISSUE THREAD

**Issue by conghua1013** [squizlabs/PHP_CodeSniffer#2605]
phpcs: Xdebug requires Zend Engine API version 320151012. The Zend Engine API version 320160303 which is installed, is newer. Contact Derick Rethans at http://xdebug.org/docs/faq#api for a later version of Xdebug.

**Comment by gsherwood** [comment]
This isn't an issue with PHPCS itself. Try clicking the link that was provided and seeing if you can sort the xdebug issue out. If not, try getting support from that project.
