### ISSUE TITLE
"ERROR: Referenced sniff does not exist" while trying to include custom sniff

### ISSUE THREAD

**Issue by range-of-motion** [squizlabs/PHP_CodeSniffer#2606]
I'm trying to include a custom sniff I made. PHPCS can't find it. What am I doing wrong?

`composer.json`

```json
"autoload": {
  "psr-4": {
    "Foo\\": ""
  }
}
```

`phpcs.xml`

```xml
<?xml version="1.0"?>
<ruleset name="mcp">
  <rule ref="Generic.Arrays.DisallowLongArraySyntax" />
  <rule ref="Foo.CodingStandards.MCP.Sniffs.ReturnTypeSniff" />
</ruleset>
```

`CodingStandards/MCP/ruleset.xml`

```xml
<?xml version="1.0"?>
<ruleset name="MCP">
  <description>Lorem ipsum</description>
</ruleset>
```

`CodingStandards/MCP/Sniffs/ReturnTypeSniff.php`

```php
<?php

namespace Foo\CodingStandards\MCP\Sniffs;

use PHP_CodeSniffer\Files\File;
use PHP_CodeSniffer\Sniffs\Sniff;

class ReturnTypeSniff implements Sniff
{
  public function register(): array
  {
    return [T_FUNCTION];
  }

  public function process(File $file, $position): void
  {
    // Yeetus deletus, logic comes here
  }
}
```

**Comment by jrfnl** [comment]
PHPCS requires a very specific directory layout, namespace and file name scheme. Your code doesn't comply with any of this, which is the reason it's not working.

Please read the following two references to understand how writing sniffs and creating your own standard works.
* https://github.com/squizlabs/PHP_CodeSniffer/wiki/Coding-Standard-Tutorial
* https://github.com/squizlabs/PHP_CodeSniffer/issues/2481#issuecomment-485145277

Once you've read them, feel free to ask any follow up questions.

**Comment by range-of-motion** [comment]
Thanks, gonna mess around with those. Can sniffs exist on their own or do they require parenthood of a standard?

**Comment by range-of-motion** [comment]
Can I mix standards? Do I **have to** define the standard using the `--standard` parameter, or can I just reference it in `phpcs.xml` like below?

```xml
<ruleset name="foo">
 <rule ref="Foo.CodingStandard.ReturnType" />
</ruleset>
```

**Comment by jrfnl** [comment]
@range-of-motion

> Can I mix standards?

Yes, you can. Either in a ruleset or using `--standard` like `--standard=PEAR,PSR12`, though mind conflicting sniffs in rulesets.

> Do I have to define the standard using the `--standard` parameter, or can I just reference it in `phpcs.xml` like below?

This is explained in detail in https://github.com/squizlabs/PHP_CodeSniffer/issues/2481#issuecomment-485145277

Short answer:
* A standard `ruleset.xml` will automatically include all sniffs from the standard, so you don't need to include individual sniffs.
* A custom `phpcs.xml[.dist]` ruleset can include both complete standards, categories from a standard, individual sniffs or even error codes.

Also see: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-Ruleset

**Comment by range-of-motion** [comment]
Thanks @jrfnl—I got it working. I ran into a few issues tho.

* Sniffs **need** to be inside a standard. What if I just want an extra sniff for my project? I don't want to make a standard in these situations. 
* The name of my coding standard gets ignored and I have to reference it as the folder name of the standard (`<ruleset name="ShittyCodingStandard">`, but it gets installed as `shitty-coding-standard`)
* Sniffs **need** to be inside a "category". Why can I not just have my "ShittyCodingStandard" with 1 or 2 sniffs, and without another sub-directory?

Don't get me wrong, I appreciate your help. But doing anything beyond what PHPCS comes shipped with is a frustrating experience.

**Comment by jrfnl** [comment]
@range-of-motion Sorry you feel that way, but those strict naming rules which I listed in the above mentioned comment are there for a reason.

PHPCS needs to be able to _load_ sniffs by name, as the name is what's used in rulesets, so the autoloader needs to be able to translate sniff names to the file name of the sniff in a predictable manner.

Secondly, the sniff file name is later used to create the error code as displayed in report when using the `-s` option.
This in turn allows for sniff names/error codes to be used to selectively ignore issues inline, so again a translation needs to take place checking if issues reported by a certain sniff file should be listed in the report or not.

Using file names is really not an option for any of this as the (absolute) install path would be different on different machines and various standards can contain sniffs with the same name.

I work with a lot of external standards and, as long as those few simple rules are followed everything works swimmingly.

**Comment by range-of-motion** [comment]
Right, I'm not suggesting using absolute paths either. But wouldn't it be nicer to have a more "modular" system?

Forgive me for being ignorant, but compare it to PHPUnit. Their tests are your sniffs, and your standards (or rulesets) are their testsuites. Isn't it possible to have separate sniffs, that can be used and defined wherever you want, but that **can** exist in a ruleset (or standard)?

**Comment by jrfnl** [comment]
I can't speak for the direction of the project and whether that would be a feature which is possible, but which I don't know about and/or whether that is a feature which could possibly be considered for the future.
@gsherwood is better positioned to answer that.

All I can do is help you get it working as things are now, and by the sounds of it, you got it working, so at least that's something :smiley:

**Comment by range-of-motion** [comment]
I mean, it kinda works? Thanks for the comments by the way, appreciate it.

@gsherwood what do you think about my comparison to PHPUnit and how it works as opposed to PHPCS' workings?

**Comment by gsherwood** [comment]
> what do you think about my comparison to PHPUnit and how it works as opposed to PHPCS' workings?

I can't see the relationship between them.

A sniff code inside a ruleset (Standard.Category.Sniff.Message) is used by PHPCS to discover where the sniff exists. Without those parts, and without the strict namespace requirements for custom sniffs, PHPCS would be unable to match a sniff code to a sniff file.

If PHPCS required people to specified fully qualified class names for sniffs instead of using sniff codes, then it would be achievable. But it doesn't, and I don't have any plans to change this.

Adding an optional feature to *also* be able to specify sniff files using a fully qualified class name would certainly be possible, but then no internal sniff code could be produced for the error messages it produces. Instead, I'd be introducing an entirely new way to reference sniffs and messages that would likely be quite confusing and result in incredibly long sniff codes. I don't see the benefit.

I'm going to close this issue now that you're original problem has been resolved (thanks @jrfnl - I appreciate the help you provided here) and because I don't have any plans to change this.

Feel free to open a feature suggestion about how you think PHPCS should work. Maybe there is more support out there than I believe.
