### ISSUE TITLE
Suggestion: only allow raising the memory limit

### ISSUE THREAD

**Issue by jrfnl** [squizlabs/PHP_CodeSniffer#2612]
Currently when setting the memory limit, it will just be "hard" set to whatever value is passed:
`$ phpcs -d memory_limit=32M /path/to/code`

In most cases, the `memory_limit` is passed - either from the command line or the ruleset via `<ini name="" value=""/>` - to attempt to _raise_ the memory limit, however, the existing memory limit is not checked, so in effect the `memory_limit` could currently be _lowered_.

Should a check be build in to only allow for raising the memory limit and to ignore (or raise a warning) about lowering the memory limit ?

**Comment by gsherwood** [comment]
> Should a check be build in to only allow for raising the memory limit and to ignore (or raise a warning) about lowering the memory limit ?

I don't think PHPCS should be doing this. I think it should be setting the values that are passed in and performing the run as instructed.
