### ISSUE TITLE
Report warnings but return a zero exit code

### ISSUE THREAD

**Issue by rcrowe** [squizlabs/PHP_CodeSniffer#262]
I want to report to console/checkstyle any warnings, but I do not want the exit code to be `> 0`. Currently warnings are returning a `1`.

All I could find was suppressing but this means nothing is output.

**Comment by tim-bezhashvyly** [comment]
It will make sense to add this to wiki.

Also why also not create `ignore_errors_on_exit` flag? As a usecase I'm running `phpcs` as a composer script and would like to just get the report w/o `1` response code as in this case composer goes all red telling that `phpcs` suffered a "RuntimeException".

**Comment by gsherwood** [comment]
That flag was already documented on the config options page of the wiki: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options#ignoring-warnings-when-generating-the-exit-code

Adding an `ignore_errors_on_exit` option was a good idea, so I committed it here: https://github.com/squizlabs/PHP_CodeSniffer/commit/897df04c518bcf0025247e2b523706a2e48ae767

And documented it here: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options#ignoring-errors-when-generating-the-exit-code

Thanks

**Comment by tim-bezhashvyly** [comment]
Great! Thanks a lot!

**Comment by tim-bezhashvyly** [comment]
Looking forward into having it tagged as a release.

**Comment by naxhh** [comment]
Yay! just trying to do this today for the same use case as @tim-bezhashvyly.

Waiting for release!

**Comment by tim-bezhashvyly** [comment]
2.3.1 release is there!

**Comment by naxhh** [comment]
Works like a charm! Thanks

**Comment by bradym** [comment]
Adding a comment because this issue came up in google before the wiki page. The option for this is now set using --config-set instead of --runtime-set as mentioned in this issue. The [wiki has the correct commands](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options#ignoring-errors-when-generating-the-exit-code) listed, but it took me a bit to realize it was different:

Here are the current correct flags:

```
phpcs --config-set ignore_warnings_on_exit 1
phpcs --config-set ignore_errors_on_exit 1
```

**Comment by jrfnl** [comment]
@bradym Actually, both will work.
The difference is that `--config-set` changes the default setup for your copy of PHPCS, while `--runtime-set` will change the value just and only for that specific run.

**Comment by lucaswerkmeister** [comment]
Another note to fellow search engine users – `ignore_warnings_on_exit` and `ignore_errors_on_exit` are only supported by `phpcs`, not `phpcbf`. (More specifically, the options are still parsed and result in `Runner::run()` returning 0, but `Runner::runPHPCBF()` ignores the return value of `Runner::run()` and instead returns exit codes based on the number of fixed/fixable errors in `$this->reporter`.)
