### ISSUE TITLE
Use statements are not in correct order (PSR12)

### ISSUE THREAD

**Issue by spaceemotion** [squizlabs/PHP_CodeSniffer#2629]
[According to the spec](https://www.php-fig.org/psr/psr-12/#3-declare-statements-namespace-and-import-statements) the order is as follows:

- [...]
- One or more class-based use import statements.
- One or more function-based use import statements.
- One or more constant-based use import statements.
- [...]

However, given the following code:
```php
use Exception;
use GuzzleHttp\Promise\Coroutine;
use function GuzzleHttp\Promise\settle;
use Illuminate\Http\Request;
use Meng\AsyncSoap\SoapClientInterface;
use stdClass;
```

`phpcbf --standard=psr12` reformats it as follows:
```php
use Exception;
use GuzzleHttp\Promise\Coroutine;

use function GuzzleHttp\Promise\settle;

use Illuminate\Http\Request;
use Meng\AsyncSoap\SoapClientInterface;
use stdClass;
```

And not as expected:

```php
use Exception;
use GuzzleHttp\Promise\Coroutine;
use Illuminate\Http\Request;
use Meng\AsyncSoap\SoapClientInterface;
use stdClass;

use function GuzzleHttp\Promise\settle;
```

---

```
$ php phpcbf.phar --version
PHP_CodeSniffer version 3.5.0 (stable) by Squiz (http://www.squiz.net)
```

**Comment by gsherwood** [comment]
If you look at the error report, you'll see something like this:
```
FILE: temp.php
----------------------------------------------------------------------------------------------------------------------------------
FOUND 5 ERRORS AFFECTING 4 LINES
----------------------------------------------------------------------------------------------------------------------------------
  4 | ERROR | [x] Header blocks must be followed by a single blank line
  5 | ERROR | [x] Header blocks must be followed by a single blank line
  6 | ERROR | [ ] Similar statements must be grouped together inside header blocks; the first "use" statement was found on line 3
 10 | ERROR | [ ] Each class must be in a namespace of at least one level (a top-level vendor name)
 10 | ERROR | [x] Opening brace of a class must be on the line after the definition
----------------------------------------------------------------------------------------------------------------------------------
PHPCBF CAN FIX THE 3 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------------------------------------------------------------------
```
The sniff error that tells you about similar blocks needing to be grouped together is not actually a fixable error. The blank line between blocks one is, so some blank lines are added to seperate the various types of use statements, but this sniff never attempts to move code around. This is why the PHPCBF run tells you that there are still errors remaining after it tried to fix the file.

I decided not to implement auto fixing for this because I thought it was too dangerous (I prefer to only change the position of code and not the order of the code) but I'll leave this open as a feature request in case anyone wants to make a case for doing so.

**Comment by spaceemotion** [comment]
Alright, that was indeed the case (only phpcs showed it though). Is there an API / mechanism in place to move lines around? Or is this something that has to be added in the PR?

**Comment by gsherwood** [comment]
> only phpcs showed it though

That's because PHPCS shows error reports and PHPCBF does auto fixing. It would show an left-over unfixed error in it's report though.

> Is there an API / mechanism in place to move lines around?

Code can already be moved around using the existing API, but you need to be very careful about how you manipulate the the file's tokens.

**Comment by simPod** [comment]
This sniff already does that https://github.com/slevomat/coding-standard#slevomatcodingstandardnamespacesalphabeticallysorteduses-

Not sure what policy is but don't think it's worth the effort to reimplement it.

**Comment by spaceemotion** [comment]
@simPod Sorry, forgot to update this issue. Yes, I indeed am using that sniff now and it works as expected. If anybody else wants to tackle this, feel free.
