### ISSUE TITLE
How to supply a list of forbidden functions (Generic.PHP.ForbiddenFunctions)

### ISSUE THREAD

**Issue by travispaul** [squizlabs/PHP_CodeSniffer#263]
I can't figure out how to provide a custom list of forbidden functions. I'm not sure if it's even possible, given that the $forbiddenFunctions property is protected. But the doc block says: "Can be used to forbid the use of any function." so perhaps I'm just doing something wrong.

I am using the following command:

```
$ phpcs -l -p src\lib --extensions=php --standard=phpcs.xml
```

And phpcs.xml looks like this:

```
<?xml version="1.0"?>
<ruleset name="Custom Standard">
    <description>Test Coding Standard</description>

    <rule ref="Generic.PHP.ForbiddenFunctions">
        <properties>
            <property name="forbiddenFunctionNames" type="array" value="eval,system,phpinfo"/>
        </properties>
    </rule>

</ruleset>
```

The error message is:

```
PHP Fatal error:  Cannot access protected property Generic_Sniffs_PHP_ForbiddenFunctionsSniff::$forbiddenFunctionNames
```

**Comment by Torte72** [comment]
Thanks for this improvement!
Unfortunately the assignment of null values doesn't work. It just takes "null" as a string which results in in messages like "The use of function is_null() is forbidden, use null() instead".
Could you please add a handling for that?

Thanks!

**Comment by aik099** [comment]
@Torte72 , this is because it's only how it was proposed in https://github.com/squizlabs/PHP_CodeSniffer/issues/263#issuecomment-56184111, but @gsherwood 's implementation was different.

So you want just to tell, that function is forbidden with no alternative functions to use?

**Comment by Torte72** [comment]
Exactly. I want to forbid the 'extract' function for wich there is no alternative.

**Comment by gsherwood** [comment]
Thanks for testing this change. I've pushed a fix to get those null replacements working.

**Comment by ankitadmanephp** [comment]
<rule ref="Generic.PHP.ForbiddenFunctions">
    <properties>
      <property name="forbiddenFunctions" type="array" value="exec=>null,shell_exec=>null,popen=>null,passthru=>null,proc_open=>proc_open,system=>null,pcntl_exec=>null"/>
    </properties>
  </rule>

**Comment by mbomb007** [comment]
For anyone looking here recently, the format has changed.

https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.3.0
