### ISSUE TITLE
Empty argument lines are not removed in the start of function calls (PSR2 + PSR12)

### ISSUE THREAD

**Issue by spaceemotion** [squizlabs/PHP_CodeSniffer#2630]
[PSR2](https://www.php-fig.org/psr/psr-2/#47-method-and-function-calls) and [PSR12](https://www.php-fig.org/psr/psr-12/#47-method-and-function-calls) both declare that:

> [...] When doing so, the first item in the list MUST be on the next line, and there MUST be only one argument per line. [...]

Given the following code:

```php
        $this->converter->convert(

            ['birthdate' => '1998-01-27'],
            []

        );
```

It gets incorrectly formatted as follows:

```php
        $this->converter->convert(

            ['birthdate' => '1998-01-27'],
            []
        );
```

And not as expected like this:

```php
        $this->converter->convert(
            ['birthdate' => '1998-01-27'],
            []
        );
```

---

```
$ php phpcbf.phar --version
PHP_CodeSniffer version 3.5.0 (stable) by Squiz (http://www.squiz.net)
```

**Comment by gsherwood** [comment]
Thanks for reporting this.

I've now implemented this check in both the PSR2 and PSR12 standards. It was also added to the PEAR standard because both PSR2 and PSR12 inherit their function call checks from there.
