### ISSUE TITLE
Sniff to check for duplicate array keys

### ISSUE THREAD

**Issue by o5** [squizlabs/PHP_CodeSniffer#2636]
Is there any sniff which check duplicated array keys? I mean something similar like [PHPStorm Code Inspection: Duplicate array keys](https://www.jetbrains.com/help/phpstorm/php-duplicate-array-keys.html?origin=old_help&search=inspection).

**Comment by gsherwood** [comment]
No, there is no included sniff that will check for duplicate array keys. I'll turn this into a feature request in case there is any support for it.

**Comment by jrfnl** [comment]
@o5 The external [PHPCSExtra standard](https://github.com/phpcsstandards/phpcsextra#universalarraysduplicatearraykey-books) has a sniff for this.
