### ISSUE TITLE
Squiz.CSS.DuplicateClassDefinitionSniff sees comments as part of the class name

### ISSUE THREAD

**Issue by rhorber** [squizlabs/PHP_CodeSniffer#2638]
This sniff threw false-positives in my code. After #985 was fixed, they disappeared. After the fix of #1657 they rose again.

The difference between my code and the same in #1657 is, that I have the comments before the class name:
`/* any comment */
.foo
{ color: red; }`

**Comment by gsherwood** [comment]
Thanks for the report, and the PR.

Just a warning that CSS and JS sniffing will be removed in version 4. That's quite a while away (no date set), but it would be worth thinking about switching to a different CSS linter when you get a chance.

**Comment by rhorber** [comment]
Okay, thank you for the heads-up.
