### ISSUE TITLE
PSR12 and ReturnTypeDeclarationSniff compatibility

### ISSUE THREAD

**Issue by shandyDev** [squizlabs/PHP_CodeSniffer#2643]
Hi, It seems you have check
> There must not be a space before the colon in a return type declaration

in ReturnTypeDeclarationSniff and this sniff included in PSR12 standard. 
BUT in PSR12 https://www.php-fig.org/psr/psr-12/ required only 2 checks:
> When you have a return type declaration present, there MUST be one space after the colon followed by the type declaration. The colon and declaration MUST be on the same line as the argument list closing parenthesis with no spaces between the two characters

So PSR12 DO NOT require "must not be a space before the colon" rule.

@ocramius What you think?

**Comment by shandyDev** [comment]
This is in one sniff (ReturnTypeDeclarationSniff), so this a bigger deal)
I think need split it on 2 sniff, and include in PSR12 ruleset only one sniff.

**Comment by gsherwood** [comment]
> So PSR12 DO NOT require "must not be a space before the colon" rule.

PSR12 does require this. It says:
> When you have a return type declaration present, there MUST be one space after the colon followed by the type declaration. The colon and declaration MUST be on the same line as the argument list closing parenthesis with no spaces between the two characters.

When it says "with no spaces between the two characters", it means no space between the colon and the closing parenthesis of the argument list.

If you don't want that rule applied, you can exclude the error message `PSR12.Functions.ReturnTypeDeclaration.SpaceBeforeColon` from your standard.

**Comment by VincentLanglet** [comment]
In https://www.php-fig.org/psr/psr-12/ all the example are given with no space between the colon and the closing parenthesis.

The sentence 
```
The colon and declaration MUST be on the same line as the argument list closing parenthesis with no spaces between the two characters.
```
Is clear.

**Comment by gsherwood** [comment]
Closing due to lack of feedback and because I think PSR-12 is pretty clear here.
