### ISSUE TITLE
False positiv: BooleanOperatorPlacementSniff

### ISSUE THREAD

**Issue by VincentLanglet** [squizlabs/PHP_CodeSniffer#2648]
This
```
if ($name
     && (false === $function || $name < $function)
     && substr($tokens[$name]['content'], 0, 8) !== 'Abstract'
)
```
Return an error for the `||` boolean operator.

When you read PSR12, the rule is about 
> Expressions in parentheses

So since `false === $function || $name < $function` is in parentheses and on the same line, there should be no error. It's not the same scope than the `&&` operators.

**Comment by jrfnl** [comment]
Duplicate of #2637 which has already been fixed in `master` and should be included in the next release.

**Comment by gsherwood** [comment]
Can confirm this is fixed in master.
