### ISSUE TITLE
CodeSniffer.conf is not writable

### ISSUE THREAD

**Issue by DerekCresswell** [squizlabs/PHP_CodeSniffer#2667]
I'm on Ubuntu and trying to install the drupal coding standard but when I try to set an installed path or any `--config-set` command I get the error :   
`ERROR: Config file /etc/php-codesniffer/CodeSniffer.conf is not writable`  
How do I change this?  
Ubuntu 19

**Comment by AliSal92** [comment]
if you have sudo access do this:
`sudo phpcs --config-set OTHER PARAMETERS HERE`
