### ISSUE TITLE
EnforceYodaConditionSniff

### ISSUE THREAD

**Issue by VincentLanglet** [squizlabs/PHP_CodeSniffer#2681]
In the same way the [DisallowYodaConditionSniff](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/Generic/Sniffs/ControlStructures/DisallowYodaConditionsSniff.php), what about a way to enforce Yoda condition ?

I can do it, but should it be another Sniff or a refactor of the Disallow with a parameter ?

**Comment by gsherwood** [comment]
Was raised here: #2039 

Two sniffs would be the preferred way.

Closing this one so we don't have two discussions.

**Comment by VincentLanglet** [comment]
Sorry for the duplicate
