### ISSUE TITLE
Syntax error in FunctionCommentUnitTest.inc

### ISSUE THREAD

**Issue by angellandros** [squizlabs/PHP_CodeSniffer#2682]
I am using PHP-compatibility to check compatibility of my PHP project. But, by running
```bash
$ vendor/bin/phpcs --cache=library/phpcscache --parallel=4 -p -n $pathsToExclude --standard=PHPCompatibility --runtime-set testVersion 7.2
```
I get the following error:
```text
Registering sniffs in the PHPCompatibility standard... PHP Parse error:  syntax error, unexpected 'public' (T_PUBLIC), expecting end of file in /builds/console/console-php/library/vendor/squizlabs/php_codesniffer/src/Standards/PEAR/Tests/Commenting/FunctionCommentUnitTest.inc on line 380
```
It refers to [this line](https://github.com/squizlabs/PHP_CodeSniffer/blob/6a4abf447866731eed5d4a944686992366840cc3/src/Standards/PEAR/Tests/Commenting/FunctionCommentUnitTest.inc#L380).

My `composer.json` looks like this:
```json
{
"require-dev": {	
        "phpunit/phpunit": "*",
        "dealerdirect/phpcodesniffer-composer-installer": "^0.5",
        "squizlabs/php_codesniffer": "^3.5.2",
        "phpcompatibility/php-compatibility": "^9.3.2"
    }
}
```

Any ideas?

**Comment by jrfnl** [comment]
@angellandros You may want to exclude the `vendor` directory from your scan, like so:
```bash
$ vendor/bin/phpcs --cache=library/phpcscache --parallel=4 -p -n $pathsToExclude --ignore=*/vendor/* --standard=PHPCompatibility --runtime-set testVersion 7.2
```

**Comment by jrfnl** [comment]
Either way, it's weird as PHPCS does not do a syntax check by default and the `PHPCompatibility` standard does not do so either (doesn't use the `Generic.PHP.Syntax` sniff), so I suspect the parse error check must be something Composer related.

I've seen errors like that before when running via Composer and it's just weird.

**Comment by gsherwood** [comment]
Closing as it sounds like this is something that might need to be discussed in the composer project.

**Comment by wietsewarendorff** [comment]
Had the same problem just now... turns out I had included the php-codesniffer classmap to run the tests for my custom sniff:

```
"autoload-dev": {
    "psr-4": {
        "MyCustomSniff\\Tests\\": "tests"
    },
    "classmap": [
        "vendor/squizlabs/php_codesniffer"
    ]
}
```

As a result all files (including .inc files) turned up in the composer-classmap and this results in the error above. As an alternative, I now added the codesniffer as psr-4 and included the autload-file:

```
"autoload-dev": {
    "psr-4": {
        "MyCustomSniff\\Tests\\": "tests/",
        "PHP_CodeSniffer\\": "vendor/squizlabs/php_codesniffer/src/"
    },
    "files": [
        "vendor/squizlabs/php_codesniffer/autoload.php"
    ]
}
```

**Comment by jrfnl** [comment]
@wietsewarendorff Just the autoload file should do, you don't need the PSR4 directive.

**Comment by wietsewarendorff** [comment]
You're right, I've update my answer. Thanks @jrfnl !
