### ISSUE TITLE
Phar version not running recursive

### ISSUE THREAD

**Issue by adamculp** [squizlabs/PHP_CodeSniffer#269]
I am using the latest RC2 version as a phar, and it is not sniffing recursively through a project.  I am specifying the location as '/path/of/my/project/' and also trying '/path/of/my/project/*', but it will not dig into sub-directories and find files.  However, it will sniff all files within a given directory, just not within sub-folders.

Command I'm using:
php phpcs.phar -sv --extensions='/home/adamculp/PHPCompatibility' --standard='PHPCompatibility' --report-file=/home/adamculp/codesniffer_results.txt --extensions=module/php /home/adamculp/site/*

The result file is created properly, and all files within the 'site' folder are parsed, but not sub-folders.

**Comment by natalisilverio** [comment]
Hello @adamculp 
I facing a similar issue. Could you please inform why did you use --extensions twice? Which one determines to check all the php files in your project folder? 

Thanks
