### ISSUE TITLE
PSR12 Traits usage - all on top of the class?

### ISSUE THREAD

**Issue by michalbundyra** [squizlabs/PHP_CodeSniffer#2690]
Consider the following example:

```php
<?php

namespace MyNamespace;

class MyExample
{
    use Trait1;

    protected $a = 1;
    use Trait2;
}
```

And using PSR12 check there is no any error.

I believe it is wrong, as ALL traits should be on top of the class.
I was checking wording in PSR12 and it is not clear, or not specified, but I believe it was the intention.

**Comment by gsherwood** [comment]
Going to close this as fixing one of the linked issues fixes the other. I'd rather keep a single conversation thread.
