### ISSUE TITLE
PHP 7.4 fn closure invalid scope closer with ternary

### ISSUE THREAD

**Issue by michalbundyra** [squizlabs/PHP_CodeSniffer#2715]
Example:

```php
<?php

$fn = fn ($a) => $a ? fn () : string => 'a' : fn () : string => 'b';

var_dump($fn(0)()); // string(a)
var_dump($fn(1)()); // string(b)
```

so what we should have here is:
- ✅ scope_closer for first fn should be the final `;`
- ❌ scope_closer for "then" fn should be `:` (else) - it is the final `;` instead
- ✅ scope_close for "else" fn should be the final `;`

Related to #2523

**Comment by gsherwood** [comment]
I've pushed a fix for this case. I'm not super happy with the code, but I feel like there are going to be a few more cases like this, so I can refactor later. At least there are tests cases for it.

Thanks a lot for reporting this.
