### ISSUE TITLE
PSR2.ControlStructures.ControlStructureSpacing.SpacingAfterOpenBrace conflicts with PSR12 but no conflict warning.

### ISSUE THREAD

**Issue by Girgias** [squizlabs/PHP_CodeSniffer#2721]
As I've just realized PSR2.ControlStructures.ControlStructureSpacing.SpacingAfterOpenBrace doesn't allow a new line after an opening bracket for example after an ``if``. This is well known (#460, #1829, and others), this has been clarified and fixed in PSR-12

However when including both PSR-12 and PSR-2 standards (which in all honesty I shouldn't have done but I've copy pasted my configuration file from project to project and it was created at the time PSR12 was still a W.I.P.) there is no mention of PSR-2 conflicting with PSR-12 which took me a bit of time to realise why I was getting the ``Expected 0 spaces after opening bracket; newline found`` errors and PHPCB couldn't fix it because it was bouncing back and forth between rules.

Would it be possible to add a mention to remove the PSR-2 standard when including the PSR-12 one as it is superseding it?

**Comment by gsherwood** [comment]
> Would it be possible to add a mention to remove the PSR-2 standard when including the PSR-12 one as it is superseding it?

No, there is no way to do this without hard-coding something into the core which tries to detect this during ruleset parsing. That's not something I want to set a precedent for.

**Comment by gsherwood** [comment]
Forgot to mention, plenty of sniffs from different standards will conflict, and I do not want to try and keep a record of all those in the code. It's also not possible to do for custom standards.

**Comment by Girgias** [comment]
I thought there was already a conflict mechanism, probably confusing with PHP-CS-FIXER in that case.

**Comment by gsherwood** [comment]
> I thought there was already a conflict mechanism

Only when auto-fixing. PHPCS can't determine if sniffs conflict until they start changing code.
