### ISSUE TITLE
Possible to ignore `OperatorSpacing` for concatenation only

### ISSUE THREAD

**Issue by coreyworrell** [squizlabs/PHP_CodeSniffer#2722]
```php
'string'.$var;
```
causes `PSR12.Operators.OperatorSpacing.NoSpaceBefore` and `PSR12.Operators.OperatorSpacing.NoSpaceAfter` errors. I would like there to be spaces around other operators (`$var = 'string';`), but not around the dot ever. Is this possible to configure? Right now I am just excluding both of those sniffs.

**Comment by gsherwood** [comment]
After you've excluded those PSR12 sniffs, try including `Squiz.WhiteSpace.OperatorSpacing` and `Squiz.Strings.ConcatenationSpacing`. By default, those 2 sniffs enforce 1 space around operators but no spaces around concat operators.

**Comment by coreyworrell** [comment]
Awesome, thanks very much @gsherwood
