### ISSUE TITLE
phpcs hangs in a particular file

### ISSUE THREAD

**Issue by ghnp5** [squizlabs/PHP_CodeSniffer#2723]
I understand I might not be giving all the details you need to investigate this, but please let me know what extra information you need.

This is in Windows.

I'm trying to run:
`phpcs --report=summary --standard=phpcs.xml --extensions=php F:\path\to\folder\ -v -p`

And it seems to work well and fast until it reaches a file with 4000+ lines.
Just hangs forever.

In order to understand better what's happening, I ran:
`phpcs --report=summary --standard=phpcs.xml --extensions=php F:\path\to\folder\huge_file.php -vv -p`

A HUUUUGE output is generated, so I'm just printing some parts:

```
Processing ruleset F:\path\to\phpcs.xml
	=> set config value installed_paths: ../../slevomat/coding-standard
	Processing rule "Generic.Classes.DuplicateClassName"
		=> F:\path\to\vendor\squizlabs\php_codesniffer\src\Standards\Generic\Sniffs\Classes\DuplicateClassNameSniff.php
	Processing rule "Generic.CodeAnalysis.EmptyStatement"
	
(...)

	=> added global absolute ignore pattern: /vendor/*
	=> added global absolute ignore pattern: /node_modules/*
	=> added global absolute ignore pattern: /build/*
=> Ruleset processing complete; included 48 sniffs and excluded 0
Creating file list... DONE (1 files in queue)
Changing into directory F:\path\to\folder
Processing huge_file.php 
	*** START PHP TOKENIZING ***
	Process token [0]: T_OPEN_TAG => <?php 
	
(...)


		Process token 43593 on line 4083 [col:1;len:1;lvl:1;conds;T_FUNCTION;]: T_CLOSE_CURLY_BRACKET => }
		=> Found scope closer for 43384:T_OPEN_CURLY_BRACKET
		* token T_FUNCTION removed from conditions array *
		* level decreased *
	Process token 43594 on line 4083 [col:2;len:0;lvl:0;]: T_WHITESPACE => \n
	*** END LEVEL MAP ***
	*** START ADDITIONAL PHP PROCESSING ***
	* token 37991 (T_CASE) on line 3566 closer changed from 38068 (T_RETURN) to 38068 (T_RETURN)
	* token 37837 on line 3546 changed from T_FUNCTION to T_CLOSURE
		* cleaned 37846 (T_WHITESPACE) *
		
(...)

		* cleaned 8626 (T_WHITESPACE) *
	* token 3752 (T_CASE) on line 384 closer changed from 3848 (T_RETURN) to 3848 (T_RETURN)
	*** END ADDITIONAL PHP PROCESSING ***
[PHP => 43595 tokens in 4083 lines]... 

```

And then just stays stuck in this last bit. Doesn't produce more output, and doesn't end the command, while a huge CPU usage is happening.

Any ideas of what this can be?

**Comment by gsherwood** [comment]
You may need to use `-vvv`, but expect a heap more output again. But this will show you which sniff is running so that you can determine where it is hanging.

**Comment by ghnp5** [comment]
Done that. Thank you for the tip.

The sniffer "SlevomatCodingStandard\Sniffs\Exceptions\ReferenceThrowableOnlySniff" seems to be the problem.

In that last part where it was hanging for me, it appears that several things are processed, but every time it hits "ReferenceThrowableOnlySniff", it hangs for ~30 seconds or so.

I'll contact the owners of this sniff, as most likely this is out of your scope :)

Really appreciate the help!!

**Comment by gsherwood** [comment]
Thanks. I'll close this for now. If a core issue is found, I'm sure the sniff developer will open a new issue.
