### ISSUE TITLE
Squiz Commenting not working on 3.5.3 and not show anything

### ISSUE THREAD

**Issue by harrisdt15f** [squizlabs/PHP_CodeSniffer#2740]
after **upgraded to 3.5.3 from 3.5.2** today and then comment anylizing functions below not pop error please check for it. And I am not sure some of other functions are if normal or not. Thanks you.

PHP version
PHP 7.3.11-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Oct 24 2019 18:23:06) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.11-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.7.2, Copyright (c) 2002-2019, by Derick Rethans

Framework
laravel 6.6.1

   ```
 <rule ref="Squiz.Commenting.FunctionComment" />
    <rule ref="Squiz.Commenting.FunctionCommentThrowTag" />
    <rule ref="Squiz.Commenting.ClassComment" />
   <rule ref="Squiz.PHP.DisallowMultipleAssignments"/>
    <rule ref="Squiz.PHP.DisallowSizeFunctionsInLoops"/>
    <rule ref="Squiz.PHP.EmbeddedPhp"/>
    <rule ref="Squiz.PHP.GlobalKeyword"/>
    <rule ref="Squiz.PHP.InnerFunctions"/>
    <rule ref="Squiz.PHP.LowercasePHPFunctions"/>
    <rule ref="Squiz.PHP.NonExecutableCode"/>
    <rule ref="Squiz.Scope.MemberVarScope"/>
    <rule ref="Squiz.Scope.MethodScope"/>
    <rule ref="Squiz.Scope.StaticThisUsage"/>
```

**Comment by gsherwood** [comment]
To help, I'd need a piece of sample code that you dont think is being checked correctly. All the sniffs you've listed have unit tests which are passing in both 3.5.2 and 3.5.3, so it's hard for me to say what wont be working.

**Comment by harrisdt15f** [comment]
I found the error is beacuse of
