### ISSUE TITLE
Generic.PHP.DeprecatedFunctions return PHP Fatal error:  Uncaught ReflectionException

### ISSUE THREAD

**Issue by harrisdt15f** [squizlabs/PHP_CodeSniffer#2742]
squizlabs/php_codesniffer   version   3.5.3 

PHP version
```
PHP 7.3.11-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Oct 24 2019 18:23:06) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
with Zend OPcache v7.3.11-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
with Xdebug v2.7.2, Copyright (c) 2002-2019, by Derick Rethans
```

**Framework    Laravel    6.6.1**

os version
```
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
xml file
[phpcs.xml.txt](https://github.com/squizlabs/PHP_CodeSniffer/files/3964899/phpcs.xml.txt)

Problem
`<rule ref="Generic.PHP.DeprecatedFunctions"/>`

> PHP Fatal error:  Uncaught ReflectionException: Function SjczTDG4TDK0Tweg() does not exist in /var/www/jianghu_entertain/vendor/squizlabs/php_codesniffer/src/Standards/Generic/Sniffs/PHP/DeprecatedFunctionsSniff.php:37
> Stack trace:
> #0 /var/www/jianghu_entertain/vendor/squizlabs/php_codesniffer/src/Standards/Generic/Sniffs/PHP/DeprecatedFunctionsSniff.php(37): ReflectionFunction->__construct('SjczTDG4TDK0Twe...')
> #1 /var/www/jianghu_entertain/vendor/squizlabs/php_codesniffer/src/Ruleset.php(1198): PHP_CodeSniffer\Standards\Generic\Sniffs\PHP\DeprecatedFunctionsSniff->__construct()
> #2 /var/www/jianghu_entertain/vendor/squizlabs/php_codesniffer/src/Ruleset.php(218): PHP_CodeSniffer\Ruleset->populateTokenListeners()
> #3 /var/www/jianghu_entertain/vendor/squizlabs/php_codesniffer/src/Runner.php(332): PHP_CodeSniffer\Ruleset->__construct(Object(PHP_CodeSniffer\Config))
> #4 /var/www/jianghu_entertain/vendor/squizlabs/php_codesniffer/src/Runner.php(70): PHP_CodeSniffer\Runner->init()
> #5 /var/www/jianghu_entertain/vendor/squizlabs/php_co in /var/www/jianghu_entertain/vendor/squizlabs/php_codesniffer/src/Standards/Generic/Sniffs/PHP/DeprecatedFunctionsSniff.php on line 37

The file on getting error
[BaseModel.php.txt](https://github.com/squizlabs/PHP_CodeSniffer/files/3964900/BaseModel.php.txt)

**Comment by gsherwood** [comment]
I don't know why a function returned from `get_defined_functions()` would not exist when calling `ReflectionFunction()`. Can you provide short sample code that can reproduce the issue?

**Comment by harrisdt15f** [comment]
[BaseModel.php.txt](https://github.com/squizlabs/PHP_CodeSniffer/files/3964825/BaseModel.php.txt)
```
PHP Fatal error:  Uncaught ReflectionException: Function SjczTDG4TDK0Tweg() does not exist in /var/www/tmp/pre-receive-hook-EFwx2/jianghu_entertain/vendor/squizlabs/php_codesniffer/src/Standards/Generic/Sniffs/PHP/DeprecatedFunctionsSniff.php:37        
Stack trace:        
#0 /var/www/tmp/pre-receive-hook-EFwx2/jianghu_entertain/vendor/squizlabs/php_codesniffer/src/Standards/Generic/Sniffs/PHP/DeprecatedFunctionsSniff.php(37): ReflectionFunction->__construct('SjczTDG4TDK0Twe...')        
#1 /var/www/tmp/pre-receive-hook-EFwx2/jianghu_entertain/vendor/squizlabs/php_codesniffer/src/Ruleset.php(1198): PHP_CodeSniffer\Standards\Generic\Sniffs\PHP\DeprecatedFunctionsSniff->__construct()        
#2 /var/www/tmp/pre-receive-hook-EFwx2/jianghu_entertain/vendor/squizlabs/php_codesniffer/src/Ruleset.php(218): PHP_CodeSniffer\Ruleset->populateTokenListeners()        
#3 /var/www/tmp/pre-receive-hook-EFwx2/jianghu_entertain/vendor/squizlabs/php_codesniffer/src/Runner.php(332): PHP_CodeSniffer\Ruleset->__construct(Object(PHP_CodeSniffer\Config))        
#4 /var/www/tmp/pre-receive-hook in /var/www/tmp/pre-receive-hook-EFwx2/jianghu_entertain/vendor/squizlabs/php_codesniffer/src/Standards/Generic/Sniffs/PHP/DeprecatedFunctionsSniff.php on line 37        
exist status is 255 
```

**Comment by harrisdt15f** [comment]
Hello Master, I already uploaded phpxml file and the file which report error on check and the version of os etc to the first comment. Thank you for your help.

**Comment by gsherwood** [comment]
I can't replicate any issue with any of the built-in standards. It's possible that one of the external sniffs you are using is causing this issue. I would suggest commenting out all the external sniffs and running PHPCS again.

If it not longer produces an error, uncomment each external sniff until you find the one that is causing the issue.

If it still produces an error with just the included sniffs then I'm not sure what it is.

**Comment by harrisdt15f** [comment]
I try it in  window docker but it now show me error, but in linux I get the above error. 
I will try comment out some external package as you guide.

**Comment by harrisdt15f** [comment]
I tried after upgrated to version 3.54 and tested the file below still have problem.I also uploaded the progress of running detail.
[helpers.php.txt](https://github.com/squizlabs/PHP_CodeSniffer/files/4213316/helpers.php.txt)
[running-detail and error with vvv.txt](https://github.com/squizlabs/PHP_CodeSniffer/files/4213325/running-detail.and.error.with.vvv.txt)

**Comment by harrisdt15f** [comment]
[running under linux.txt](https://github.com/squizlabs/PHP_CodeSniffer/files/4213419/running.under.linux.txt)
[running inside docker under windows error with vvv (2).txt](https://github.com/squizlabs/PHP_CodeSniffer/files/4213420/running.inside.docker.under.windows.error.with.vvv.2.txt)

**Comment by harrisdt15f** [comment]
[get_defined_functions_result_on_errors.txt](https://github.com/squizlabs/PHP_CodeSniffer/files/4213517/get_defined_functions_result_on_errors.txt)
[get_defined_functions_result_on_success.txt](https://github.com/squizlabs/PHP_CodeSniffer/files/4213518/get_defined_functions_result_on_success.txt)

**Comment by jrfnl** [comment]
@harrisdt15f That looks like an issue with PHP itself, not with PHPCS. What version of PHP are you using ?

**Comment by jrfnl** [comment]
@harrisdt15f Just for argument's sake and to exclude it: would you be able to test PR #2873 to see if that changes anything for you ?
I don't expect it to fix your issue, but it would be good to get confirmation one way or another.

(and yes, I've tried and failed to reproduce the issue myself, so can't test this)

**Comment by harrisdt15f** [comment]
php 7.3.13 ,could we have way to exclude like this kinds of methods and not to be exit.

**Comment by harrisdt15f** [comment]
Let it be ,its because of php itself error. Thank you for all trying to help me.
