### ISSUE TITLE
Generic.ControlStructures.InlineControlStructure.NotAllowed not part of PSR12 spec

### ISSUE THREAD

**Issue by hacktivista** [squizlabs/PHP_CodeSniffer#2744]
It seems like Generic.ControlStructures.InlineControlStructure.NotAllowed is not part of PSR12, but it's enabled by default when using that standard.

**Comment by gsherwood** [comment]
From PSR-12:

> 5. Control Structures
> The general style rules for control structures are as follows:
> ...
> The body of each structure MUST be enclosed by braces. This standardizes how the structures look and reduces the likelihood of introducing errors as new lines get added to the body.

This is the part that the `InlineControlStructure` sniff is enforcing. The same wording was in PSR-2 as well.

**Comment by hacktivista** [comment]
But it does not say that I must not use inline control structures such as

```
if (true) { $var = 'x'; }
```

Sometimes this rule just makes my code look funny.

**Comment by gsherwood** [comment]
> But it does not say that I must not use inline control structures such as

Yes, it does say that too:

> 5. Control Structures
> The general style rules for control structures are as follows:
> 
> ...
> The structure body MUST be indented once
> The body MUST be on the next line after the opening brace
> The closing brace MUST be on the next line after the body

> Sometimes this rule just makes my code look funny.

I didn't write the PSR12 standard. I've just made sure PHPCS can enforce it correctly. If you don't like the standard, all I can suggest is either don't use it, or complain to the PHP FIG (they wrote it).

**Comment by hacktivista** [comment]
Indeed, you are right. Completely by bad. I'll close this.
