### ISSUE TITLE
Generic.Array.ArrayIndent inconsistent behaviour with Closing brace and First Value

### ISSUE THREAD

**Issue by VincentLanglet** [squizlabs/PHP_CodeSniffer#2758]
There is a weird behaviour with nested array.
```
return [['c',
  'a',
  'b']];
```

Is fixed in
```
return [['c',
  'a',
  'b',
]
];
```

I expect it to be fixed in
```
return [[
  'c',
  'a',
  'b',
]];
```
Or at least
```
return [
  [
    'c',
    'a',
    'b',
  ]
];
```

**Comment by VincentLanglet** [comment]
It does not this seems neested-related at all.

```
return ['c', 'a',
  'd',
];
```
returns no error.

I expect it to be fixed in
```
return [
  'c',
  'a',
  'd',
];
```

**Comment by gsherwood** [comment]
That's just not how this sniff works. This sniff doesn't try to enforce that arrays have one element per line, but it does enforce that the closing brace is on a line by itself.

I agree it could be improved, but with a consideration for backwards compatibility.

**Comment by VincentLanglet** [comment]
> I agree it could be improved, but with a consideration for backwards compatibility.

It depends on the point of view: bugfix or improvement ?

I kinda think weird the fact that it checks the fact that
```
[
  'a','b']
```
is fixed to
```
[
  'a','b'
]
```

But 
```
['a','b'
]
```
Is untouched.

There should not be a different behaviour for the opening and the closing brace.
Similar to how this sniff checks element's indent it could be "If the closing brace start on a new line, check the indent" instead of enforcing the new line.

And then we can add a `strict` mode "All the element and the closing brace should start on a new line". The default value will be false for to avoid breaking changes (but I personally thinks this sniff is only useful with the strict mode).

---------

By the way, I looked at the code of the AbstractArraySniff and the first condition checks talk about nested array, but the `$lastToken = $checkToken` seems useless. Is it missing for nested array or it's just a useless line ?
![image](https://user-images.githubusercontent.com/9052536/70662903-7e09c480-1c67-11ea-91ed-37a528a0a6ba.png)
