### ISSUE TITLE
Can't resolve external standard files when using phar version of phpcs

### ISSUE THREAD

**Issue by burzum** [squizlabs/PHP_CodeSniffer#2762]
We started using [Phive](https://github.com/phar-io/phive) and by this are now using phpcs via phar file. When I now just execute `.\bin\phpcs` I'm getting this error:

> PHP Fatal error:  Uncaught Error: Class 'PSR2R\Tools\AbstractSniff' not found in \vendor\fig-r\psr2r-sniffer\PSR2R\Sniffs\Classes\ClassCreateInstanceSniff.php:9

I guess this is because its trying to access these files from a different root because it assumes the phar file as root or something like that? How can I fix that?

Here is our config file:

```xml
<?xml version="1.0"?>
<ruleset name="PSA">
	<rule ref="./vendor/fig-r/psr2r-sniffer/PSR2R/ruleset.xml"/>
	<file>./src</file>
	<file>./tests</file>
	<file>./plugins/Psa/Cms/src</file>
	<file>./plugins/Psa/Cms/tests</file>
	<file>./plugins/Psa/MailingLists/src</file>
	<file>./plugins/Psa/MailingLists/tests</file>
	<exclude-pattern>*/tests/bootstrap.php</exclude-pattern>
	<exclude-pattern>*/config/Migrations/*</exclude-pattern>
</ruleset>
```

**Comment by jrfnl** [comment]
@burzum For that repo, the command to use is `vendor/bin/sniff`.

Does the issue still occur when you use that ?

Ref: https://github.com/php-fig-rectified/psr2r-sniffer#usage

/cc @dereuromark

**Comment by burzum** [comment]
@gsherwood I don't know if the problem still persists, we "fixed" it by switching to PSR2 minus the silly spaces via our own config and this seems to work just fine.

**Comment by gsherwood** [comment]
Thanks for the feedback. I'll close this now that it is resolved for you, but will look into it if anyone reports it again.
