### ISSUE TITLE
PSR2.ControlStructures.ElseIfDeclaration not checking else if in file

### ISSUE THREAD

**Issue by harrisdt15f** [squizlabs/PHP_CodeSniffer#2765]
squizlabs/php_codesniffer 3.5.3
laravel 6.7.0
php
PHP 7.3.12-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Nov 28 2019 07:36:56) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.12, Copyright (c) 1998-2018 Zend Technologies
with Zend OPcache v7.3.12-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

rule 
`<rule ref="PSR2.ControlStructures.ElseIfDeclaration"/>`

php file 

[FrontendApiMainController.php.txt](https://github.com/squizlabs/PHP_CodeSniffer/files/3959490/FrontendApiMainController.php.txt)

config xml

[phpcs.xml.txt](https://github.com/squizlabs/PHP_CodeSniffer/files/3959497/phpcs.xml.txt)

**Problem** 

**PSR2.ControlStructures.ElseIfDeclaration 
not checking else if in file at line 101**

**Comment by gsherwood** [comment]
The ELSEIF declaration message is a warning. It looks like this:
```
 101 | WARNING | [x] Usage of ELSE IF is discouraged; use ELSEIF instead (PSR2.ControlStructures.ElseIfDeclaration.NotAllowed)
```
Your ruleset hard-codes the `-n` CLI argument, so warnings are hidden. That's why you can't see it. The sniff appears to be working fine.

**Comment by harrisdt15f** [comment]
OK, Thank you.
