### ISSUE TITLE
PHPCS hangs in Docker

### ISSUE THREAD

**Issue by danepowell** [squizlabs/PHP_CodeSniffer#2767]
I'm trying to implement a Docker-based testing environment for https://github.com/acquia/blt

BLT already has a PHPCS ruleset that works great on every native machine I've tried, as well as Travis CI. But when I try to run it in our new Docker testing environment, bizarre things happen.

If I just run `./vendor/bin/phpcs` from a Docker bash prompt, I get no output and the process never ends, consuming 100% of the container CPU.

Similarly, `./vendor/bin/phpcs -v` returns the following and hangs the same way:
> Registering sniffs in the blt standard... DONE (290 sniffs registered)
Creating file list... DONE (180 files in queue)

Here's where it gets **weird**. `./vendor/bin/phpcs -vv` and `./vendor/bin/phpcs -vvv` work exactly as expected, sniffing everything and finishing quickly.

I've tested with PHPCS 3.5.2 and 3.5.3. You can probably reproduce this yourself with this feature branch: https://github.com/danepowell/blt/tree/docker-testing

Just run `docker-compose up -d`, `docker-compose run drupal bash`, `./vendor/bin/phpcs`.

**Comment by gsherwood** [comment]
Related: https://github.com/squizlabs/PHP_CodeSniffer/issues/2659

No solution found, but explains why -vv and -vvv work.

The other issue looked like a gRPC bug - not sure if that helps: https://github.com/grpc/grpc/issues/20994

**Comment by danepowell** [comment]
Awesome, thanks so much for the reference! Indeed, disabling the php-grpc extension fixed it, so it seems like https://github.com/grpc/grpc/issues/20994 is related.

Disabling php-grpc is an acceptable workaround for my use case. I don't fully understand the underlying issue, so I'm not sure if it's practical to fix this upstream, or to implement a workaround in PHPCS. Feel free to keep this open or not as you wish.

**Comment by gsherwood** [comment]
I don't think this is something I can fix in PHPCS, so will close this. Thanks a lot for confirming the workaround is working.
