### ISSUE TITLE
vcruntime140.dll 14.0 is not compatible 

### ISSUE THREAD

**Issue by RienBijl** [squizlabs/PHP_CodeSniffer#2772]
When including PHP_CodeSniffer on PHPStorm 2019.3 as a Quality Tool it keeps giving the following error:

`phpcs: PHP Warning: 'vcruntime140.dll' 14.0 is not compatible with this PHP build linked with 14.16 in Unknown on line 0 `

I thought this might be a compatibility issue with PHP 7.4.0, but the requirements clearly state that 
> PHP_CodeSniffer requires PHP version 5.4.0 or greater

**Comment by RienBijl** [comment]
I have confirmed this as a compatibility issue on PHP 7.4.0. With PHP 7.2.19 it does not produce this error. I however do not have the knowhow to trace this issue back to any specific code in PHPCS.

**Comment by jrfnl** [comment]
@RienBijl As far as I know, this is unrelated to PHPCS, but has to do with your PHP install itself. The latest PHP versions for Windows need VC15. 
See: https://windows.php.net/download/ - there are links to the downloads you need in the column on the left.

**Comment by RienBijl** [comment]
I have VC15-19 on my machine. Furthermore, PHP 7.4.0 does run other applications. For me this problem is exclusively with PHPcs

**Comment by jrfnl** [comment]
@RienBijl Could you try running PHPCS from the command line using PHP 7.4.0 ? If the warning doesn't pop up, the problem is with the PHPStorm integration, not PHPCS.

(I've been running PHPCS with PHP 7.4.0 on Windows for quite a while now and never seen this).

**Comment by RienBijl** [comment]
Yes, this is a PHPStorm issue (https://prnt.sc/qc1qd7). I'll look some further into this. If I find a solution I'll post it here for others that might struggle with this issue @jrfnl.

**Comment by RienBijl** [comment]
For people having this problem, please follow this issue on the jetbrains bugtracker: https://youtrack.jetbrains.com/issue/WI-50383

**Comment by Alexandre-T** [comment]
The previous issue was judged as duplicate. Please follow [this issue](https://youtrack.jetbrains.com/issue/WI-50050) . It seems that the bug is only a PHPStorm bug. It is "blindly" fixed on PHPStorm 2019.3.1, but not for the PHP Mess Detector.

**Comment by TheLess** [comment]
> The previous issue was judged as duplicate. Please follow [this issue](https://youtrack.jetbrains.com/issue/WI-50050) . It seems that the bug is only a PHPStorm bug. It is "blindly" fixed on PHPStorm 2019.3.1, but not for the PHP Mess Detector.

not only in PHPStorm.
I just only install PHP7.4.3 in windows 10 x64
(I have already isntalled vc ++ 2015 ),
but the same problem occured 
I do not know it is vc's problem or php's problem

**Comment by Aaron-Code** [comment]
I tried to install VC++19 ,but still don't solve the problem.
I don't know the problem.

**Comment by zia-max** [comment]
download Microsoft Visual C++ Redistributable for Visual Studio 2019 from 
https://aka.ms/vs/16/release/VC_redist.x64.exe and install and chill.

**Comment by snehapkamble** [comment]
After install VC_redist.x64.exe issue got resolved. thanks

**Comment by deepsfriend4u** [comment]
Issue resolved after install VC_redist.x64.exe
thanks

**Comment by EmeditWeb** [comment]
I installed php 8.0.3 , changed the module test and tried running php --version and got these same error,,,any help?

**Comment by zjkal** [comment]
> 

me, too. help!!!
