### ISSUE TITLE
PHP extensions requirements missing

### ISSUE THREAD

**Issue by aminnairi** [squizlabs/PHP_CodeSniffer#2774]
There is no mentions of the PHP requirements in the `README.md` file. This can be quite handy for people using minimal distributions like Alpine Linux. For the latter, it is necessary to install all those packages.

```console
$ apk add --update composer php php-xml php-tokenizer php-simplexml php-xmlwriter
```

My guess, from here, is that `phpcs` uses — at least — the following PHP extensions.

- Tokenizer
- XML
- Simple XML
- XML Writer

I haven't tested the requirements for `phpcbf`.

Would it be possible to have something mentioning those extensions in the main documentation file?

**Comment by jrfnl** [comment]
Looking at the command, you are using Composer, so you can find the requirements documented there: https://github.com/squizlabs/PHP_CodeSniffer/blob/90b719decdb5009b9949cf51e7544c66f182cad1/composer.json#L27-L32

Additionally, The iconv extension is recommended.

**Comment by aminnairi** [comment]
@jrfnl Thanks for pointing that out, I understand now.

**Comment by gsherwood** [comment]
I've updated the requirements here: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Requirements

Also note that PHPCS checks these requirements on each run and produces a message letting the developer know what extensions are required if they are not enabled.

The phpcs and phpcbf commands use the same code-base and are both considered part of PHP_CodeSniffer, so have the same requirements.
