### ISSUE TITLE
How to find a sniff's name to exclude it?

### ISSUE THREAD

**Issue by mbomb007** [squizlabs/PHP_CodeSniffer#2779]
I have spent time looking for a way to discover a sniff's name (e.g. "Generic.Category.Specific") from its error message in order to exclude the sniff. I can't find anything about how to find this.

`// phpcs:ignore Generic.Category.Specific`

The only way I have found is to search using `phpcs -e --standard=[standard] | grep "Specific"`. And if I don't know what the name would contain, I have to look at every single sniff's name. Even then, I might not know which to exclude without trying them all. Either that, or I have to search the coding standard's source code and attempt to figure out the name that way.

Is there a better way to do this? It would be nice if the text of the error would contain the sniff name or something.

**Comment by jrfnl** [comment]
@mbomb007 Try running PHPCS with `-s` (source), it will show the error code for each message.
