### ISSUE TITLE
Runner.php:562

### ISSUE THREAD

**Issue by nevercodealone** [squizlabs/PHP_CodeSniffer#2783]
Version PHP_CodeSniffer version 3.2.3 (stable)

Run on Ubuntu 18.04.3 LTS

`PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /usr/share/php/PHP/CodeSniffer/src/Tokenizers/Tokenizer.php on line 654
PHP Stack trace:
PHP   1. {main}() /usr/bin/phpcs:0
PHP   2. PHP_CodeSniffer\Runner->runPHPCS() /usr/bin/phpcs:18
PHP   3. PHP_CodeSniffer\Runner->init() /usr/share/php/PHP/CodeSniffer/src/Runner.php:70
PHP   4. PHP_CodeSniffer\Ruleset->__construct() /usr/share/php/PHP/CodeSniffer/src/Runner.php:294
PHP   5. PHP_CodeSniffer\Ruleset->populateTokenListeners() /usr/share/php/PHP/CodeSniffer/src/Ruleset.php:218
PHP   6. PHP_CodeSniffer\Standards\PEAR\Sniffs\ControlStructures\ControlSignatureSniff->register() /usr/share/php/PHP/CodeSniffer/src/Ruleset.php:1175
PHP   7. PHP_CodeSniffer\Standards\PEAR\Sniffs\ControlStructures\ControlSignatureSniff->parse() /usr/share/php/PHP/CodeSniffer/src/Sniffs/AbstractPatternSniff.php:91
PHP   8. PHP_CodeSniffer\Standards\PEAR\Sniffs\ControlStructures\ControlSignatureSniff->createTokenPattern() /usr/share/php/PHP/CodeSniffer/src/Sniffs/AbstractPatternSniff.php:826
PHP   9. spl_autoload_call() /usr/share/php/PHP/CodeSniffer/src/Sniffs/AbstractPatternSniff.php:918
PHP  10. PHP_CodeSniffer\Autoload::load() /usr/share/php/PHP/CodeSniffer/src/Sniffs/AbstractPatternSniff.php:918
PHP  11. PHP_CodeSniffer\Autoload::loadFile() /usr/share/php/PHP/CodeSniffer/autoload.php:134
PHP  12. include() /usr/share/php/PHP/CodeSniffer/autoload.php:167
PHP  13. spl_autoload_call() /usr/share/php/PHP/CodeSniffer/src/Tokenizers/PHP.php:14
PHP  14. PHP_CodeSniffer\Autoload::load() /usr/share/php/PHP/CodeSniffer/src/Tokenizers/PHP.php:14
PHP  15. PHP_CodeSniffer\Autoload::loadFile() /usr/share/php/PHP/CodeSniffer/autoload.php:134
PHP Fatal error:  Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /usr/share/php/PHP/CodeSniffer/src/Files/File.php on line 1351 in /usr/share/php/PHP/CodeSniffer/src/Runner.php:562
Stack trace:
#0 /usr/share/php/PHP/CodeSniffer/autoload.php(167): PHP_CodeSniffer\Runner->handleErrors()
#1 /usr/share/php/PHP/CodeSniffer/autoload.php(167): include()
#2 /usr/share/php/PHP/CodeSniffer/autoload.php(134): PHP_CodeSniffer\Autoload::loadFile()
#3 [internal function]: PHP_CodeSniffer\Autoload::load()
#4 /usr/share/php/PHP/CodeSniffer/src/Files/LocalFile.php(16): spl_autoload_call()
#5 /usr/share/php/PHP/CodeSniffer/autoload.php(167): include('/usr/share/php/...')
#6 /usr/share/php/PHP/CodeSniffer/autoload.php(134): PHP_CodeSniffer\Autoload::loadFile()
#7 [internal function]: PHP_CodeSniffer\Autoload::load()
#8 /usr/share/php/PHP/CodeSniffer/src/Files/FileList.php(186): spl_autoload_call()
#9 /usr/share/php/PHP/CodeSniffer/src/Runner.php(383 in /usr/share/php/PHP/CodeSniffer/src/Runner.php on line 562
`

**Comment by jrfnl** [comment]
Please upgrade to PHPCS 3.3.1 or higher.

**Comment by nevercodealone** [comment]
Thx that fix the problem. Could install on local composer repo version 3.5.3.
Hope ubuntu will also update it on package manager.

Thx for your great support and passion. Marry xmas!!
