### ISSUE TITLE
phpcbf does nothing

### ISSUE THREAD

**Issue by leeisme** [squizlabs/PHP_CodeSniffer#2786]
Hi,

I'm playing around with this component since I am constructing PHP scripts dynamically and need to format the code that it outputted. I have tried the following:

`../../vendor/bin/phpcbf --standard=PSR1 -e --suffix=.fixed /tmp/script.php`

Output from the command:

"No fixable errors were found

Time: 51ms; Memory: 5.75MB"

The test file that I am trying to fix:

```
$testValue = new stdClass();
$g = new stdClass();
$testVal = 1;
 if

 (

 (
-1 !== 2
 && 2 !== 3
)
 && 5 === 5
 )
 {
$g->myVariable = 'TestValue!';
 }
return true;
```

I've tried using PSR1, PSR2, PSR12, and a couple others (also specify NO standards on the command line) and no changes are ever made to the file. I could be wrong, but the code above doesn't look compliant with any rule set supplied so I'm wonder what I could be doing wrong.

Any ideas?

Thanks!

**Comment by leeisme** [comment]
OMG ID-10T error. 

Very sorry for the premature post. I just realized that the files that I am outputting do not have the PHP tag and apparently, it affects the parsing of the file and possibly not recognized as PHP.

**Comment by jrfnl** [comment]
@leeisme If you want files with another extension than `php` or `inc` to be recognized as PHP you can use `--extensions=php,ext/php`.

Also, try running the command without the `-e` The `-e` means "explain" and only has effect when run with `phpcs`.

And to help debugging: try running `phpcs` first with `-v` to see which files are picked up and scanned (and if they yield any fixable errors/warnings).
