### ISSUE TITLE
Contradicting switch with return

### ISSUE THREAD

**Issue by mkroeders** [squizlabs/PHP_CodeSniffer#2789]
Currently there there are two contradicting rules. `return` requires no enters after it, while `case` requires enters after it. Both rules I want to keep but in this instance I want to use the `case` rule so it is more clear of the separate cases. unforunatly I cannot see a parameter option of any kind to do this.

Code

The following code states (correctly) that there is an enter missing

    switch ($baz) {
        case 'foo':
            return 'foo';
        case 'bar':
            return 'bar';
    }

(phpcs output)

    136 | ERROR | [x] Expected 1 lines after "case", found 0.
    (SlevomatCodingStandard.ControlStructures.BlockControlStructureSpacing.IncorrectLinesCountAfterControlStructure)
    138 | ERROR | [x] Expected 1 lines before "case", found 0.
    (SlevomatCodingStandard.ControlStructures.BlockControlStructureSpacing.IncorrectLinesCountBeforeControlStructure)

To fix this an enter is added between the two cases, however this triggers the an issue with an enter after the `return`

    switch ($orderType) {
        case 'foo':
            return 'foo';

        case 'bar':
            return 'bar';
    }

(phpcs output)

    137 | ERROR | [x] Expected 0 lines after "return", found 1.
    (SlevomatCodingStandard.ControlStructures.JumpStatementsSpacing.IncorrectLinesCountAfterLastControlStructure)

I am I missing an option that can fix this or is it one or the other rule?

The [phpcs config](https://gist.github.com/mkroeders/98b5f9e56e5e0f1e2c3b53a1e468c71a) in use

**Comment by jrfnl** [comment]
As those are sniffs from the [Slevomat Coding Standard](https://github.com/slevomat/coding-standard/), asking there may be the better place ?

**Comment by mkroeders** [comment]
Sorry, was not thinking clearly. Will close the issue
