### ISSUE TITLE
fileList tag in custom ruleset is not working

### ISSUE THREAD

**Issue by Pirozek** [squizlabs/PHP_CodeSniffer#2807]
Hey there, I have the same problem as this guy - https://github.com/squizlabs/PHP_CodeSniffer/issues/1275, using version 3 with command `docker run --rm -v my-project-path:/data cytopia/phpcs:3-php7.1` and in `phpcs.xml` file in root I have this `<file>app</file>`. And ofc, I have `app` directory. Still, when I run the docker, it just prints out the version of sniffer and nothing happens.

So I tried using fileList, created file `phpcs-files` with this content: `app`, added this tag to my `phpcs.xml` -> `<fileList>phpcs-files</fileList>` and tried running it. Nope, only prints out the version.  But when I run docker with `file-list` arg (like this `docker run --rm -v my-project-path:/data cytopia/phpcs:3-php7.1 --file-list=phpcs-files`), it checks the app directory, so I think the file is ok, but `phpcs` is ignoring `file` and `fileList` tags in custom ruleset.

Am I doing something wrong, or is ti just broken? :)

**Comment by gsherwood** [comment]
`fileList` is not a valid tag in ruleset.xml files. The `file` tag works fine though - I use it in the main PHPCS ruleset every day.

If the directory `app` could not be found, PHPCS would print an error and exit, so I assume it's being found. Try running PHPCS with the `-v` command line argument to make sure it is seeing a ruleset and that it has found files to check (first 2 lines of output).

You can also use the `-vv` command line argument to get a lot more output, which will show you exactly how the ruleset is being parsed, and to confirm your `file` tags are being processed. But this output is very verbose, so only run PHPCS on a single small file when debugging this way.
