### ISSUE TITLE
Suggestion: new option for showing version informations of rulesets

### ISSUE THREAD

**Issue by LukeWCS** [squizlabs/PHP_CodeSniffer#2808]
Regarding this issue on PHPCompatibility:

https://github.com/PHPCompatibility/PHPCompatibility/issues/958

I would be helpful to have another option to show a version information of a ruleset. Then CS ruleset authors can define her own version information. And then CS implementers like me can access this information under code control.

Example call:

`phpcs --version-ruleset="PHPCompatibility/ruleset.xml"`

or

`phpcs --version-ruleset --standard="PHPCompatibility/ruleset.xml"`

Example `ruleset.xml`:

```
<?xml version="1.0"?>
<ruleset name="PHPCompatibility">
    <description>Coding Standard that checks for PHP version compatibility.</description>

    <versioninfo>PHPCompatibility v9.3.5</versioninfo>

    <autoload>./../PHPCSAliases.php</autoload>

</ruleset> 
```

@gsherwood 

These are only examples. I don't know the tech behind all things regarding CS. So please see it simply as idea/thought.

edit: 

So that you can see where I want to display this additional information, I'll show you a report that was generated by Ext Check:

[Ext Check Report (Demo)](https://wcsaga.org/temp/phpBB_Ext_Check_Report_lukewcs_whowashere_2_0_0.html)

I mean this: "PHPCompatibility: 9.3.5". The version I read with RegEx from `CHANGELOG.md`.

**Comment by gsherwood** [comment]
I definitely wouldn't add a dedicated CLI option for this.

The best place to leave feedback about the ability to see more information about installed standards is on issue #2600. Please leave your thoughts there and I'll close this issue so there are no 2 conversations happening about the same thing.
