### ISSUE TITLE
Implement codeclimate reporter

### ISSUE THREAD

**Issue by stephanoff** [squizlabs/PHP_CodeSniffer#2813]
It is nice to have Codeclimate reporter plugin to be able to integrate codesniffer with gitlab-ci.

**Comment by jrfnl** [comment]
@stephanoff Could you elaborate a little on what you mean by this ? Maybe add some links too ?

**Comment by stephanoff** [comment]
There is existing tool called Codeclimate used for the GitLab CI AutoDevOps.
There is an example their report implementation https://github.com/codeclimate/codeclimate-phpcodesniffer
But running Codeclimate on the large project is not an option since common case is use PHPCS installed from composer.
I didn't happy about their approach hardcoding report generator inside their package.

**Comment by jrfnl** [comment]
@stephanoff Ah, I understand now and I agree it would be better to have a `report` type for that, but that doesn't necessarily have to be in PHPCS itself and as your PR contains hard-coded sniff names and such which would need regular maintenance and is tied into the `composer.json` for CodeClimate, I'm wondering if it wouldn't be better to pull your report to the CodeClimate repo ?

An external repo can use their own report by name. See https://github.com/squizlabs/PHP_CodeSniffer/issues/1942 and https://github.com/squizlabs/PHP_CodeSniffer/pull/1948 for how to implement this.

**Comment by stephanoff** [comment]
Great, thank you!
Will do it as a separate reporter. I am not sure about integrating this reporter into CodeClimate, will ask them.
