### ISSUE TITLE
[PEAR.Functions.FunctionCallSignatureSniff] Wording consistency

### ISSUE THREAD

**Issue by VincentLanglet** [squizlabs/PHP_CodeSniffer#2825]
In the FunctionCallSignatureSniff there is the following code

```
        if ($requiredSpacesAfterOpen === 0 && $tokens[($openBracket + 1)]['code'] === T_WHITESPACE) {
            $error = 'Space after opening parenthesis of function call prohibited';
            ...
        } else if ($requiredSpacesAfterOpen > 0) {
            ...
            if ($spaceAfterOpen !== $requiredSpacesAfterOpen) {
                $error = 'Expected %s spaces after opening bracket; %s found';
                ...
            }
        }//end if
        ...
        if ($spaceBeforeClose !== $requiredSpacesBeforeClose) {
            $error = 'Expected %s spaces before closing bracket; %s found';
```

Depends on the `requiredSpacesAfterOpen` value, the message does not have the same format. And we talked sometimes about `opening parenthesis`, sometimes about `opening bracket`.

I think using the same wording could be a small improvement. Which one do you prefer ?

**Comment by gsherwood** [comment]
I'd be okay changing "bracket" to "parenthesis" but the different error message for when no space is allowed is 100% intentional. I wouldn't change that.

**Comment by VincentLanglet** [comment]
> I'd be okay changing "bracket" to "parenthesis".

Yes, I was just talking about this ; I made a PR.
