### ISSUE TITLE
install with error

### ISSUE THREAD

**Issue by wenqinruan** [squizlabs/PHP_CodeSniffer#2832]
`execute:composer global require "squizlabs/php_codesniffer=*"  
`
[InvalidArgumentException]
  Could not find a matching version of package squizlabs/php_codesniffer. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum
  -stability (stable).

**Comment by jrfnl** [comment]
@wenqinruan Try `execute:composer global require squizlabs/php_codesniffer:"*"`
