### ISSUE TITLE
License comment in file header identified as docblock

### ISSUE THREAD

**Issue by nilmerg** [squizlabs/PHP_CodeSniffer#2835]
Hi,

using the latest 3.5.3 release and checking for the PSR-12 standard this code will cause an error: (`PSR12.Files.FileHeader.SpacingAfterBlock`)

```php
<?php
/* some license text */
```

The standard only speaks about docblocks which have to match the header rules:

> The header of a PHP file may consist of a number of different blocks. If present, each of the blocks below MUST be separated by a single blank line, and MUST NOT contain a blank line. Each block MUST be in the order listed below, **although blocks that are not relevant may be omitted.**
> 
> - Opening <?php tag.
> - File-level **docblock.**

Though, such a comment isn't exactly a docblock. My understanding of a docblock is a multiline comment starting with `/**`.

I have hundreds of files defining such a license comment in its header and I don't want to change all of them. Nor do I want to exclude this sniff from our ruleset, it's generally okay after all.

So I'm here to ask if this is intended or a misinterpretation of the standard? (Either on my side or yours :wink: )

**Comment by gsherwood** [comment]
I didn't write the standard so I can't talk for the authors, but the PHPCS implementation assumes that a comment in the header section of a file relates to the entire contents of the file, and so is the file docblock. There is no way for it to know that your specific comment is just licence text and not a comment describing the purpose of the file. Even if it did, I'm not sure it should be ignored as it still relates to the file itself.

Also note that "although blocks that are not relevant may be omitted" doesn't mean that the standard says to ignore things in the header that are not defined in the standard. It means that you don't have to use each of the 8 things than can be in a file header - you can omit the ones you don't need.

**Comment by nilmerg** [comment]
> a comment in the header section of a file relates to the entire contents of the file, and so is the file docblock.

Well, I just guessed that a file docblock is what its name implies: A block of text.

> There is no way for it to know that your specific comment is just licence text and not a comment describing the purpose of the file. Even if it did, I'm not sure it should be ignored as it still relates to the file itself.

But you're right with this, it's still a comment (although a single line :stuck_out_tongue: ) that relates to the file and not just the line(s) beneath it.

--

So seeing this as a comment relating to the entire file, it's a docblock. :thinking: 

I suppose it's just an inconvenience now and I disable the sniff. And keep for future projects this in mind:

```php
<?php

/* some license text */
```
