### ISSUE TITLE
On travisCI, when testing with PHP version >=7.3, it comes with this error? How could solve this?

### ISSUE THREAD

**Issue by OneCodeMonkey** [squizlabs/PHP_CodeSniffer#2841]
PHP Fatal error:  Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

**Comment by OneCodeMonkey** [comment]
On version <=7.2, it works well. I see some issue talk about this pointing to the php version change. But still don't know why?

**Comment by jrfnl** [comment]
@OneCodeMonkey Please upgrade your PHPCS version to 3.3.1 or higher. This was fixed more than a year ago. You are using an out of date version.

**Comment by OneCodeMonkey** [comment]
> @OneCodeMonkey Please upgrade your PHPCS version to 3.3.1 or higher. This was fixed more than a year ago. You are using an out of date version.

Thks, this works!
`
{
  "require-dev": {
    "squizlabs/php_codesniffer": "~3.5"
  }
}
`
