### ISSUE TITLE
AssignmentInConditionSniff - option allow in while loop (feature request)

### ISSUE THREAD

**Issue by bkdotcom** [squizlabs/PHP_CodeSniffer#2845]
`Generic.CodeAnalysis.AssignmentInCondition.FoundInWhileCondition`

```php
while ($var = getNext() ) {
  ...do something with var 
}
```

I don't think this is a code smell.   I think this is a common pattern

Option to allow assignment inside a while?

**Comment by jrfnl** [comment]
@bkdotcom And that's exactly why assignments in a `while` condition have a separate error code.

```xml
<rule ref="Generic.CodeAnalysis.AssignmentInCondition">
    <exclude name="Generic.CodeAnalysis.AssignmentInCondition.FoundInWhileCondition"/>
</rule>
```

**Comment by bkdotcom** [comment]
facepalm
