### ISSUE TITLE
Q: Changing ForbiddenFunctions list for one specific directory

### ISSUE THREAD

**Issue by AllenJB** [squizlabs/PHP_CodeSniffer#2855]
I have a ForbiddenFunctions rule with a custom list of forbiddenFunctions, which includes "is_object". But for one specific directory I want to allow the use of is_object() but still keep the other list entries forbidden.

Is there a way to adjust the property for a specific directory? Or what's the easiest way to achieve this?

**Comment by gsherwood** [comment]
> Is there a way to adjust the property for a specific directory?

No, this feature is not available.

> Or what's the easiest way to achieve this?

You can set different config options for a specific file, but there is no way to do this for an entire directory.

You'd need to create a new standard for that specific directory, which imports the main standard but sets the config differently for this sniff. The main standard would need to exclude this directory and then new standard would need to only check this directory. It's not a nice setup.

**Comment by AllenJB** [comment]
Thanks for the reply. It would be nice if you could do this without setting up a new standard. Something similar to using include/exclude path patterns to control the properties for a rule, or have rules appear multiple times in a standard as separate instances by giving them an alias.
