### ISSUE TITLE
Make properties on Config class less magic

### ISSUE THREAD

**Issue by vladyslavstartsev** [squizlabs/PHP_CodeSniffer#2861]
Currently Config class has properties accessed via `__get()`.

Other  tools like phpstan/psalm yell at me that I can't get undefined property (to quote phpstan output `Access to an undefined property PHP_CodeSniffer\Config::$basepath`).

My idea is to annotate every magic property that available on the Config class with `@property` annotation. And also move the description of `$this->settings` to them.

I'm talking about this part of code
https://github.com/squizlabs/PHP_CodeSniffer/blob/dceec07328401de6211037abbb18bda423677e26/src/Config.php#L100

**Comment by gsherwood** [comment]
If it is just docblock changes, then I don't see any problem with this. It's not a priority for me though.
