### ISSUE TITLE
Default --config-show output is empty

### ISSUE THREAD

**Issue by hackel** [squizlabs/PHP_CodeSniffer#2862]
Using the latest phpcs 3.5.4, I am unable to view my configuration:
```
> vendor/bin/phpcs --config-show
Using config file: 

```
I get this no matter what I have in my phpcs.xml file.  Looking through the code, it appears to be looking for `./vendor/squizlabs/php_codesniffer/CodeSniffer.conf` which does not exist.  If I manually copy `CodeSniffer.conf.dist` over to `CodeSniffer.conf` in my vendor directory, the config-show command works, but it still does not read the coding standard from my phpcs.xml.

I don't want to invest more time looking into this, as it seems like a remnant from an old configuration mechanism that isn't really used any more.  Obviously we should never be writing any files into a read-only vendor directory.  I'm sure there's a lack of understanding here on my part.

I just want to print out the configuration that phpcs is going to use, and in my mind that means which phpcs.xml file it is referencing and which options it has set based on its contents.  Is there currently any way to do this?

**Comment by gsherwood** [comment]
> I get this no matter what I have in my phpcs.xml file

As you've discovered, the config file has nothing to do with coding standard rulesets. It's for setting default config settings for PHPCS that are used if the CLI and rulesets don't specify anything.

> I just want to print out the configuration that phpcs is going to use, and in my mind that means which phpcs.xml file it is referencing and which options it has set based on its contents. Is there currently any way to do this?

Not without actually checking a file. Which ruleset is used depends on what file is selected for checking. If you want to see what PHPCS is doing, check a single file in a project and use the `-vv` CLI argument. PHPCS will output all the ruleset processing information at the top, including all the CLI and config options it discovered in your ruleset and any rulesets you've included.

Does that help?
