### ISSUE TITLE
Known issues in Windows?

### ISSUE THREAD

**Issue by bertheyman** [squizlabs/PHP_CodeSniffer#2879]
I'm really enjoying code sniffer (on Mac) and would like to recommend it to some Windows users. One of them has problems during install (sorry, don't have more detailed information at the moment).

Are there any known problems on Windows to take into account?

**Comment by gsherwood** [comment]
No, there are no known problems. PHP_CodeSniffer installs and works fine on Windows, MacOS, and Linux.

**Comment by bertheyman** [comment]
Nice! That's good to know.
