### ISSUE TITLE
Enforce/forbid usage of `and`, `or` (instead of &&, ||) in if(...) statements

### ISSUE THREAD

**Issue by m-ober** [squizlabs/PHP_CodeSniffer#2885]
I looked trough all available sniffs but found nothing that matches what I had in mind: I would like to enforce either of the following styles. 

This is not only important to have the same "look" in the whole codebase but also because `and` and `or` have different precedence than `&&` and `||`. Mixing the two styles could thus have confusing results.

```php
if ((isset($context[$name]) and $context[$name] === $value) or (!isset($context['submit']) and $default)) { /* ... */ }
````

```php
if ((isset($context[$name]) && $context[$name] === $value) || (!isset($context['submit']) && $default)) { /* ... */ }
````

**Comment by gsherwood** [comment]
You can use `Squiz.Operators.ValidLogicalOperators`, which will gives you errors like:
```
 2 | ERROR | Logical operator "and" is prohibited; use "&&" instead
 2 | ERROR | Logical operator "or" is prohibited; use "||" instead
 2 | ERROR | Logical operator "and" is prohibited; use "&&" instead
```
There isn't a sniff to enforce the reverse.

Does that sniff do what you want?

**Comment by m-ober** [comment]
That's indeed what I was looking for. I noticed this sniff does not offer automatic fixing, I guess this is n purpose because _may_ change the meaning of an expression? (Because of different precedence)

**Comment by gsherwood** [comment]
> I noticed this sniff does not offer automatic fixing, I guess this is on purpose because it _may_ change the meaning of an expression? (Because of different precedence)

100% correct.

I'm going to close this as it appears to be resolved.
