### ISSUE TITLE
[FunctionCallSignatureSniff] Endless Loop

### ISSUE THREAD

**Issue by xarem** [squizlabs/PHP_CodeSniffer#2889]
If I run phpcs with FunctionCallSignatureSniff enabled, I get an endless loop while having a comma at the end of the constructor parameters.

## Example
this results in an endless loop:
```php
$formBuilder
    ->add('example', TextType::class, [
        'constraints' => [
            new NotNull(),
            new Regex([
                'pattern' =>'/^[1-9]{6}$/',
            ],)
        ],
    ]);
```

this worked:
```php
$formBuilder
    ->add('example', TextType::class, [
        'constraints' => [
            new NotNull(),
            new Regex([
                'pattern' =>'/^[1-9]{6}$/',
            ])
        ],
    ]);
```

**Comment by gsherwood** [comment]
I've tried running PHPCS over this code with all the included standards and I don't get any endless loops. Can you please provide the exact steps to replicate this problem.
