### ISSUE TITLE
incorrect PHP syntax error: syntax error, unexpected end of file

### ISSUE THREAD

**Issue by mwoodpatrick** [squizlabs/PHP_CodeSniffer#2894]
When I run command:

    phpcs  --standard=WordPress heredoc.php

on attached file I get:

 FILE: /mnt/c/Users/mlwp/Sites/devilbox/data/www/my-wp/wordpress.git/heredoc.php
-------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-------------------------------------------------------------------------------
 40 | ERROR | PHP syntax error: syntax error, unexpected end of file
-------------------------------------------------------------------------------

Time: 161ms; Memory: 8MB

This seems to be incorrect & running with --standard=PEAR does not give this error nor does PHP object.

[heredoc.php.txt](https://github.com/squizlabs/PHP_CodeSniffer/files/4301865/heredoc.php.txt)

**Comment by jrfnl** [comment]
@mwoodpatrick Try running PHPCS on PHP 7.3 or higher and the notice will go away.

The error is coming from the `Generic.PHP.Syntax` sniff which lints your files for syntax errors, your file contains PHP 7.3 context, so running PHPCS over it with a lower PHP version in combination with that sniff would throw that error.

**Comment by mwoodpatrick** [comment]
Many thanks that worked
