### ISSUE TITLE
phpcs: Referenced sniff “WordPress” does not exist

### ISSUE THREAD

**Issue by insight47** [squizlabs/PHP_CodeSniffer#2901]
I've installed phpcs and added the following to my Visual Code settings.json:

```
{
    "phpcs.enable": true,
    "phpcs.composerJsonPath": "wp-content/themes/wprig/composer.json",
    "phpcs.standard": "WordPress",
    "phpcs.executablePath": "/Users/Chris/.composer/vendor/bin/phpcs",
}
```

However, when I edit a PHP file in a WordPress theme, Visual Code displays an error @ bottom right:

> phpcs: Referenced sniff "WordPress" does not exist

If I run `phpcs -i` I receive: `The installed coding standards are PEAR, Zend, PSR2, MySource, Squiz, PSR1 and PSR12.`

How do I install the WordPress coding standard for phpcs please?

Help appreciated.

**Comment by waelzd** [comment]
hello dear, I face the same problem if you solved it can you tell me how and thank you so much

**Comment by jrfnl** [comment]
You may want to check out the instructions available about working with the WordPress standard and IDEs in the readme of the WordPressCS project: https://github.com/WordPress/WordPress-Coding-Standards/#using-phpcs-and-wpcs-from-within-your-ide

**Comment by dackr** [comment]
Hello @insight47 , were you able to fix the problem?
Could you share the solution please?
