### ISSUE TITLE
How to include current directory in file list?

### ISSUE THREAD

**Issue by Synchro** [squizlabs/PHP_CodeSniffer#2910]
I have a project with a lot of PHP files directly in the top level. I have a `.phpcs.xml` file that contains some `file` directives:

    <file>includes</file>
    <file>templates</file>

and

    <arg name="basepath" value="."/>

but when I run phpcs with this config, it ignores files that are in the top level. I've tried various ways to make it point at the current dir. `<file></file>` is ignored altogether. `<file>.</file>` and `<file>./</file>` both throw this exception:

```
Fatal error: Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: Undefined index:  in /Users/marcus/Sites/project/includes/vendor/squizlabs/php_codesniffer/src/Files/FileList.php on line 187 in /Users/marcus/Sites/project/includes/vendor/squizlabs/php_codesniffer/src/Runner.php on line 606

PHP_CodeSniffer\Exceptions\RuntimeException: Undefined index:  in /Users/marcus/Sites/project/includes/vendor/squizlabs/php_codesniffer/src/Files/FileList.php on line 187 in /Users/marcus/Sites/project/includes/vendor/squizlabs/php_codesniffer/src/Runner.php on line 606

Call Stack:
    0.0008     405088   1. {main}() /Users/marcus/Sites/project/includes/vendor/squizlabs/php_codesniffer/bin/phpcs:0
    0.0125    1342032   2. PHP_CodeSniffer\Runner->runPHPCS() /Users/marcus/Sites/project/includes/vendor/squizlabs/php_codesniffer/bin/phpcs:18
    0.0709    4844568   3. PHP_CodeSniffer\Runner->run() /Users/marcus/Sites/project/includes/vendor/squizlabs/php_codesniffer/src/Runner.php:114
    3.2491    5219920   4. PHP_CodeSniffer\Files\FileList->current() /Users/marcus/Sites/project/includes/vendor/squizlabs/php_codesniffer/src/Runner.php:487
    3.2492    5220680   5. PHP_CodeSniffer\Runner->handleErrors() /Users/marcus/Sites/project/includes/vendor/squizlabs/php_codesniffer/src/Files/FileList.php:187
```

`<file>./*</file>` displays an error saying `ERROR: The file "./*" does not exist.`.

If I run phpcs on a command line with `phpcs .` it has no problem finding the files - what's the equivalent of that in the config file?

Do I really have to list each individual PHP file at the top level, or have I missed something simple?

**Comment by jrfnl** [comment]
He @Synchro, `<file>.</file>` should work fine, but it will add all files and directories recursively, so the other `<file>` directives are no longer needed. Instead you probably want to add some `<exclude-pattern>`'s.

Something like this:
```xml
    <file>.</file>

    <!-- Exclude dependency related directories. -->
    <exclude-pattern>*/vendor/*</exclude-pattern>
    <exclude-pattern>*/node_modules/*</exclude-pattern>
```

Hope that helps!

**Comment by Synchro** [comment]
Thanks Juliette! That did work. I'm not sure what those exceptions were about though.

**Comment by jrfnl** [comment]
As long as it works now, I'm not even going to try to reproduce them... Glad you got it working ;-)
