### ISSUE TITLE
Underscore prefixed

### ISSUE THREAD

**Issue by 200MPH** [squizlabs/PHP_CodeSniffer#2912]
Hi,
Thanks for a great tool.

Script return following error:
Private method name "ReturnsController::setCollection" **must be** prefixed with an underscore
wherease PSR-12 says:
Method names **MUST NOT** be prefixed with a single underscore to indicate protected or private visibility. That is, an underscore prefix explicitly has no meaning.

**Comment by gsherwood** [comment]
Are you sure you are using the PSR-12 standard (`--standard=PSR12`) and not the default PEAR standard?

The PEAR standard will generated this error, but the PSR12 standard will not.

**Comment by 200MPH** [comment]
You right, sorry for being dumb ass.
