### ISSUE TITLE
how to enable class and function comment check

### ISSUE THREAD

**Issue by sergeevpasha** [squizlabs/PHP_CodeSniffer#2915]
I did upgrade to v4 in order to get psr-12 support. And the first thing that I did mention was a missing of warnings over unexisted comments. How can I enable em back?

**Comment by gsherwood** [comment]
The PSR12 standard doesn't require comments, which is why you wont see any errors.

I don't know what standard you were using before so it is hard to help. But if you want PSR12 plus commenting checks, you'd need to define your own rules using a ruleset.xml file. Is that what you had before?
