### ISSUE TITLE
request rule for Class Name to Check Prefix or PostFix with Specific Directory

### ISSUE THREAD

**Issue by harrisdt15f** [squizlabs/PHP_CodeSniffer#2923]
for example in laravel there have controller directory.
class in subdirectory of "Http/Controller" directory or under of "Http/Controller" directory should end with "Controller" postfix.
class in subdirectory of "Http/Request" directory or under of "Http/Request" should end with "Request" postfix.
also for custom directory to end with custom postfix or prefix.
![image](https://user-images.githubusercontent.com/27404296/78095390-61a5b980-7409-11ea-88a2-fc137212286a.png)
not to allow classes without with standard declared name in the rule to stay in the forlder.
please provide if it is possible.

**Comment by jrfnl** [comment]
Sorry, but this sounds like something way too specific for PHPCS itself.

The [Slevomat](https://github.com/slevomat/coding-standard/) standard may have a configurable sniff which allows you to do this.

**Comment by harrisdt15f** [comment]
I 've read and try rules from slevomat coding standard but not found.

**Comment by gsherwood** [comment]
Closing as this is too specific for the core set of PHPCS sniffs.
