### ISSUE TITLE
FD_SETSIZE issues on server

### ISSUE THREAD

**Issue by dereuromark** [squizlabs/PHP_CodeSniffer#2928]
Since very recently, we now have these warnings on our servers:

> Warning (2): stream_select(): You MUST recompile PHP with a larger value of FD_SETSIZE.
It is set to 1024, but you have descriptors numbered at least as high as 1067.
--enable-fd-setsize=2048 is recommended, but you may want to set it
to equal the maximum number of open files supported by your system,
in order to avoid seeing this error again at a later date. in [/.../vendor/squizlabs/php_codesniffer/src/Config.php, line 385]

**Comment by gsherwood** [comment]
I'm not sure what needs to be done about this. Do you think PHPCS is doing something wrong?

**Comment by dereuromark** [comment]
This is the tool/code that throws this error.
I have not seen this anywhere else so far. Also trying to raise that limit was not successful.

**Comment by gsherwood** [comment]
Closing as I have no received any reports of issues and don't have enough information to reproduce this problem.
