### ISSUE TITLE
Confusing class names and php keywords?

### ISSUE THREAD

**Issue by galvao** [squizlabs/PHP_CodeSniffer#2938]
phpcs seems to confuse class names and reserved language keywords: I have a class named "List" and using the PSR1,PSR2,PSR12 standards I get this error:

`ERROR | [x] PHP keywords must be lowercase; expected "list" but found "List"`

Oddly enough I couldn't find any other case - tried renaming my class to "Array", "Define", "Implode" and all of these pass.

The class is, of course, "inside" a namespace.

**Comment by carusogabriel** [comment]
@galvao 

- Which version of PHP are you using?
- Which version of PHPCS are you using?

Is this the minimum code necessary to reproduce your issue? https://3v4l.org/pBk7N

**Comment by jrfnl** [comment]
Generally speaking, class/trait/interface/namespace/function names in PHPCS are (re-)tokenized to `T_STRING`, even when they use a reserved keyword and PHP itself may tokenize it as the keyword.

In this case, using the example code from @carusogabriel's 3v4l, I can confirm that the class name is tokenized as `T_LIST`, which is the reason the error is thrown.

All the same, as the 3v4l demonstrates, this is a parse error as it uses a [PHP reserved keyword](https://www.php.net/manual/en/reserved.keywords.php) in a place where it is not allowed and I don't think it is reasonable to expect PHPCS to work around all the possible parse errors people can introduce into code.

From the PHP manual (emphasis is mine):

> You **cannot** use any of the following words as constants, **class names**, function or method names. 
>
> As of PHP 7.0.0 these keywords are allowed as property, constant, and method names of classes, interfaces and traits, except that class may not be used as constant name. 

---
<details>
  <summary>Tokenlist</summary>

```
Ptr :: Ln :: Col  :: Cond :: Token Type                 :: [len]: Content       
-------------------------------------------------------------------------       
  0 :: L1 :: C  1 :: CC 0 :: T_OPEN_TAG                 :: [5]: <?php           
                                                                                
  1 :: L2 :: C  1 :: CC 0 :: T_WHITESPACE               :: [0]:                 
                                                                                
  2 :: L3 :: C  1 :: CC 0 :: T_NAMESPACE                :: [9]: namespace       
  3 :: L3 :: C 10 :: CC 0 :: T_WHITESPACE               :: [1]:                 
  4 :: L3 :: C 11 :: CC 0 :: T_STRING                   :: [3]: Foo             
  5 :: L3 :: C 14 :: CC 0 :: T_SEMICOLON                :: [1]: ;               
  6 :: L3 :: C 15 :: CC 0 :: T_WHITESPACE               :: [0]:                 
                                                                                
  7 :: L4 :: C  1 :: CC 0 :: T_WHITESPACE               :: [0]:                 
                                                                                
  8 :: L5 :: C  1 :: CC 0 :: T_CLASS                    :: [5]: class           
  9 :: L5 :: C  6 :: CC 0 :: T_WHITESPACE               :: [1]:                 
 10 :: L5 :: C  7 :: CC 0 :: T_LIST                     :: [4]: List            
 11 :: L5 :: C 11 :: CC 0 :: T_WHITESPACE               :: [1]:                 
 12 :: L5 :: C 12 :: CC 0 :: T_OPEN_CURLY_BRACKET       :: [1]: {               
 13 :: L5 :: C 13 :: CC 1 :: T_WHITESPACE               :: [0]:                 
                                                                                
 14 :: L6 :: C  1 :: CC 1 :: T_WHITESPACE               :: [0]:                 
                                                                                
 15 :: L7 :: C  1 :: CC 0 :: T_CLOSE_CURLY_BRACKET      :: [1]: }               
 16 :: L7 :: C  2 :: CC 0 :: T_WHITESPACE               :: [0]:                 
                                                                                
 17 :: L8 :: C  1 :: CC 0 :: T_WHITESPACE               :: [0]:                 
                                                                                
 18 :: L9 :: C  1 :: CC 0 :: T_NEW                      :: [3]: new             
 19 :: L9 :: C  4 :: CC 0 :: T_WHITESPACE               :: [1]:                 
 20 :: L9 :: C  5 :: CC 0 :: T_LIST                     :: [4]: List            
 21 :: L9 :: C  9 :: CC 0 :: T_OPEN_PARENTHESIS         :: [1]: (               
 22 :: L9 :: C 10 :: CC 0 :: T_CLOSE_PARENTHESIS        :: [1]: )               
 23 :: L9 :: C 11 :: CC 0 :: T_SEMICOLON                :: [1]: ;               
 24 :: L9 :: C 12 :: CC 0 :: T_WHITESPACE               :: [0]:                 
                                                                                
```
</details>

---

**Comment by galvao** [comment]
>     * Which version of PHP are you using?
7.4.5
>     * Which version of PHPCS are you using?
3.5.5
> Is this the minimum code necessary to reproduce your issue? https://3v4l.org/pBk7N
You can even lose the instantiation.

I see now that List is reserved in PHP (as @jrfnl pointed below). My bad. Thank you for the replies.
