### ISSUE TITLE
Redundant semicolon added to a file when fixing PSR2.Files.ClosingTag.NotAllowed

### ISSUE THREAD

**Issue by morozov** [squizlabs/PHP_CodeSniffer#2943]
Consider the following file:
```php
<?php
/*
 * Some comment goes here
 */
?>
```
Fixing it using `phpcbf --standard=PSR2 test.php` makes it look like:
```php
<?php
;/*
 * Some comment goes here
 */
```
The semicolon is needed to address #773 but it's only needed when there is something else than whitespace or comment after the opening `<?php` tag.

**Comment by gsherwood** [comment]
Thanks for reporting this bug. The fix will be released in 3.5.6.
