### ISSUE TITLE
which rule is able to check missing comment for constant.

### ISSUE THREAD

**Issue by harrisdt15f** [squizlabs/PHP_CodeSniffer#2946]
I am finding the rule which can check the constant to avoid without comments or docs.
but I cannot find which rule to check missing comment for constants for e.g  like 
Squiz.Commenting.VariableComment .
Has there a rule to be able to check missing comment or doc for below constant, please
### public const ENCRYPT_MODE_SECRET = 1;

**Comment by jrfnl** [comment]
Duplicate of #2221
