### ISSUE TITLE
Issue with alphabetical order of classes

### ISSUE THREAD

**Issue by orbex** [squizlabs/PHP_CodeSniffer#2953]
Weird behaviour occurs in sorting used classes in alphabetical order (see screenshot).
In my opinion a space comes before any letter...
![Alphabetical_order_classes](https://user-images.githubusercontent.com/2074126/81288759-91c62500-9065-11ea-9754-ed594cc1831d.png)
To fix the notice it wants me to place Ad **between** AdAdvertiser and AdGroupLeadgeneration.

**Comment by jrfnl** [comment]
AFAIK PHPCS does not contain any sniffs for this. Could it be you are using the [Slevomat sniffs](https://github.com/slevomat/coding-standard/) ? If so, please report this issue there.

**Comment by orbex** [comment]
My deepest apologies, further investigation revealed that the notice is coming from figr/psr2r-sniffer.
Will bring up the issue there.

**Comment by jrfnl** [comment]
@orbex No apology needed. I hope they can help you solve this.
