### ISSUE TITLE
Disallow putenv

### ISSUE THREAD

**Issue by kkmuffme** [squizlabs/PHP_CodeSniffer#2957]
in 99% of cases, this is a bad idea. I've seen people overwrite the HOME env causing havoc...

That's why I suggest phpcs should give an error/info if putenv is used.

**Comment by alexanderpas** [comment]
You can already do this in your coding standard using the Generic.PHP.ForbiddenFunctions sniff

See also: #263

**Comment by kkmuffme** [comment]
Thank you, solution is in this comment: https://github.com/squizlabs/PHP_CodeSniffer/issues/263#issuecomment-56625344
