### ISSUE TITLE
phpcbf doesn't work with network drives like WSL2 on Windows 10.

### ISSUE THREAD

**Issue by codebymikey** [squizlabs/PHP_CodeSniffer#2965]
This is a continuation of the #1116 issue.

There's a PHP bug relating to `is_readable` not working properly for Windows network drives, further details at https://bugs.php.net/bug.php?id=73543

This should ideally be fixed on the PHP side, but given that it's been an issue for a while and still hasn't been addressed, my hopes aren't too high.

`phpcs` currently works for my use case of running it via PHPStorm's integration, but if there's other pieces of code which rely on `is_readable`, then it'll also run into the same bug.

Just wanted to document it here for others running into issues with getting it to work with PHPStorm + WSL2.

I've attached a [patch](https://gist.github.com/codebymikey/0b812ece2052331e6fe9eb568b363018) here to address the behaviour.

**Comment by gsherwood** [comment]
Rather than swapping out the `is_readable()` call, a possible workaround for this might be to try a `fopen()` if `is_readable()` returns `FALSE`, just in case the file can actually be read.

**Comment by codebymikey** [comment]
Good point, I've added a new revision to the patch for that logic.

**Comment by gsherwood** [comment]
Thanks for this patch. I've incorporated this into PHPCS now, and it will be in the 3.6.0 release.
