### ISSUE TITLE
PSR-12 not added to PHP 7.1 and below

### ISSUE THREAD

**Issue by koffisani** [squizlabs/PHP_CodeSniffer#2969]
I'm running phpcs against my wordpress theme. 

Local config : 
- PHP 7.2
- Libraries : wpcs, php_codesniffer, php-compatibility, phpcompatibility-wp, phpcompatibility-paragonie

On gitlab-ci, testing against PHP 5.6, 7.0 and 7.1, I permanently getting this error : 

> ERROR: Referenced sniff "PSR12.Keywords.ShortFormTypeKeywords" does not exist
Run "phpcs --help" for usage information

after this command : 
```
phpcs --standard=WordPress -sp --basepath=. --ignore=vendor .
```
Trying to troubleshoot, I realised that PSR12 is not added : 

> $ phpcs -i
The installed coding standards are MySource, PEAR, PSR1, PSR2, Squiz, Zend, WordPress-Extra, WordPress-Core, WordPress-Docs, WordPress, PHPCompatibility, PHPCompatibilityWP, PHPCompatibilityParagonieSodiumCompat and PHPCompatibilityParagonieRandomCompat

What's wrong with my packages ? How can I fix this ?

**Comment by jrfnl** [comment]
I suspect the version of PHPCS you are using is too old. 

If you are installing the standards via Composer, make sure the Gitlab command uses the Composer version of PHPCS `./vendor/bin/phpcs` and not a potentially available global version of PHPCS.

**Comment by koffisani** [comment]
Thank you a lot. It's exactly the issue I'm facing. Thanks.
