### ISSUE TITLE
Squiz.CSS.ShorthandSize.NotAllowed false positive

### ISSUE THREAD

**Issue by djibarian** [squizlabs/PHP_CodeSniffer#2971]
`padding: 5px 0 10px;` gives a `Shorthand syntax not allowed here; use 5px 0 10px 0 instead (Squiz.CSS.ShorthandSize.NotAllowed)`. I think that’s not correct?

**Comment by gsherwood** [comment]
The CSS tokenizer and sniffs are being removed in version 4, so I'm not fixing any bugs reported with them. I suggest moving to a proper CSS analysis tool as soon as possible and leaving PHPCS to enforce standards for PHP code only.
