### ISSUE TITLE
Documentation is broken (PEAR web)

### ISSUE THREAD

**Issue by jrfnl** [squizlabs/PHP_CodeSniffer#2973]
The documentation of the last release: https://pear.php.net/package/PHP_CodeSniffer/docs/3.5.5/ is broken.

Clicking on the links in the list on the left will result in 404s for everything.
Example: https://pear.php.net/package/PHP_CodeSniffer/docs/3.5.5/PHP_CodeSniffer/_PHP_CodeSniffer-3.5.5---src---Files---File.php.html

The docs for the previous version are ok: https://pear.php.net/package/PHP_CodeSniffer/docs/3.5.4/PHP_CodeSniffer/_PHP_CodeSniffer-3.5.4---src---Files---File.php.html

**Comment by gsherwood** [comment]
I don't have any control over that documentation and I don't know how it is generated.

**Comment by gsherwood** [comment]
Closing. I don't think PEAR is going to get any love, and I'm dropping support for it in 4.0.
