### ISSUE TITLE
Undefined offset in PSR12.Functions.ReturnTypeDeclaration when checking function return type inside ternary

### ISSUE THREAD

**Issue by martin-heralecky** [squizlabs/PHP_CodeSniffer#2975]
```php
<?php return (!$a ? [ new class { public function b(): c {} } ] : []);
```

This code, when run against `PSR12.Functions.ReturnTypeDeclaration.SpaceBeforeReturnType`, throws `Undefined offset: -1 in
.../vendor/squizlabs/php_codesniffer/src/Standards/PSR12/Sniffs/Functions/ReturnTypeDeclarationSniff.php on line 89` error.

**Comment by gsherwood** [comment]
This is caused by the colon before the `c` return type being seen as a T_INLINE_ELSE instead fo T_COLON. It's a general tokenizer error while matching inline condition tokens.

**Comment by gsherwood** [comment]
I've fixed the core tokenizer issue, which has stopped that sniff from reporting errors. Thanks a lot for the bug report.
