### ISSUE TITLE
New rule to ban T_STRING_CONCAT

### ISSUE THREAD

**Issue by szepeviktor** [squizlabs/PHP_CodeSniffer#2980]
I see PHPCS identifies the concatenating operator `.`

What does it take to add a new rule to ban its usage?

String concatenation is not the nicest thing in the world.

**Comment by gmponos** [comment]
But it is needed in many projects.. especially "websites"

Why would you want to ban it? Do you have a more solid argument rather than "nice" (I am not ironic.. asking out of curiosity)

Also a rule like that would be extremely simple to have into a custom package of yours..

**Comment by szepeviktor** [comment]
Yes, plain old PHP 4 websites **do** need dots.

In an clean OOP environment

- the templating engine concatenates and outputs the HTML code
- all string operations are executed by special libs
- the remaining things can be done by `sprintf('%s%s' ...`
- we could use `// phpcs:ignore SniffName`

So usage of `.` in a web application's code is a source of problems.

I usually say: _Do not fiddle with low level things!_

**Comment by szepeviktor** [comment]
> Also a rule like that would be extremely simple to have into a custom package of yours..

Could you show me an example?

**Comment by szepeviktor** [comment]
Got it :)

https://github.com/szepeviktor/phpcs-psr-12-neutron-hybrid-ruleset/blob/master/PSR12NeutronRuleset/Sniffs/Strings/ConcatenationUsageSniff.php

What do you think?

**Comment by jrfnl** [comment]
@szepeviktor I think you'll get lots of questions why or people disabling the rule if it's part of a standard. Would probably help if the error message suggested what to use as an alternative. `Use (s)printf()` instead` or something.

**Comment by szepeviktor** [comment]
Thank you.

Developer should trust the framework: _Do not fiddle with low level stuff!_
