### ISSUE TITLE
hide messages for when used in CI

### ISSUE THREAD

**Issue by davileichs** [squizlabs/PHP_CodeSniffer#2985]
Hello,

I have checked the documentation relation with -q, to run in quiet mode. But I would like to suggest a total quiet mode to run in CI. Since CI returns fail when there is an output, it fails every time because it output the result of time and memory usage. 
Would be good to run a CI mode to not output when everything gone ok.

Thanks

**Comment by gsherwood** [comment]
Runtime is not currently printed when using the `-q` CLI option:
```
$ phpcs --version
PHP_CodeSniffer version 3.5.5 (stable) by Squiz (http://www.squiz.net)

$ phpcs src/Config.php
. 1 / 1 (100%)


Time: 173ms; Memory: 16MB

$ phpcs src/Config.php -q
$
```
What output are you seeing?

Also note that using the exit code is a better way of failing CI, if that's possible for you.

**Comment by davileichs** [comment]
The exit code should work as well. The point is, when I run the phpcbf, it fix some errors and at the end return failed, even with fixed code. Only if I run again with no errors that it return success for CI.
In fact, I would like only to adjust some fixable and indentable code and continues the job.

Thanks.

**Comment by gsherwood** [comment]
Closing as the exit code is the supported way of checking for run success at this time. I don't have any plans for an extra quiet  mode.
