### ISSUE TITLE
phpcbf ignores Generic.Files.LineLength rule, while phpcs does not

### ISSUE THREAD

**Issue by chillcaw** [squizlabs/PHP_CodeSniffer#2986]
Rule used:
```xml
<rule ref="Generic.Files.LineLength">
    <properties>
        <property name="lineLimit" value="80"/>
        <property name="absoluteLineLimit" value="130"/>
    </properties>
</rule>
```
When this is included in a ruleset and run with phpcbf, it reports there are no fixes to be made. When this same ruleset is included as a standard with phpcs it reports errors for lines over 100 characters.

I know that PSR-2 states that a hard limit shouldn't be used, but I need to use a hard limit for my use case.

**Comment by gsherwood** [comment]
PHPCBF only deals with fixable errors. The line length errors are not auto-fixable by PHPCBF, so it can't find anything to do.

When you run PHPCS, it will let you know which (if any) of the displayed errors are fixable. If none are, you wont get a message that PHPCBF can fix anything.
