### ISSUE TITLE
Feature request: CLI option to clear the results cache

### ISSUE THREAD

**Issue by jrfnl** [squizlabs/PHP_CodeSniffer#2993]
While testing #2992, I really missed an option to clear the cache, but allow for it to be set.

The `--no-cache` option only tells PHPCS to not _use_ the cache for that particular run.

It doesn't clear an _existing_ cache file, or in case of the temp directory being used: clear all _existing_ cache files, as those can accumulate to be quite a large number of files quickly.

Please consider this a feature request for a CLI argument to clear the cache(s) to be added.

**Comment by frankgraave** [comment]
Would also love to see this option. Also, I can't find where the cache files are being stored. Is there a command to retrieve the cache directory?

**Comment by jrfnl** [comment]
> I can't find where the cache files are being stored. Is there a command to retrieve the cache directory?

@frankgraave The cache is being stored in the system temp directory, unless you set a specific cache directory either via the command line `--cache[=<cacheFile>` or set the same in your custom ruleset.
