### ISSUE TITLE
declare(strict_types=1) throws an error

### ISSUE THREAD

**Issue by TMWagner** [squizlabs/PHP_CodeSniffer#3001]
According to Symfony, declaring strict mode should be done with the statement `declare(strict_types=1)`; as the first line following the` <?php `opening tag. 

Source code looks like this:
```
<?php

declare(strict_types=1);

/**
 * @file
```

However, PHP_CodeSniffer (v3.5.5) throws an error. 
![image](https://user-images.githubusercontent.com/5316689/85645436-91eaa600-b64e-11ea-8b9a-239d48cdd6b8.png)

**Comment by jrfnl** [comment]
@TMWagner What ruleset are you running PHPCS against ? In the screenshot it says something about Drupal, in your issue text you mention Symfony.

While rulesets for both [Symfony](https://github.com/djoos/Symfony-coding-standard) as well as [Drupal](https://www.drupal.org/project/coder) exist, both of these are projects maintained elsewhere.

Based on the command in the screenshot, your project contains a `[.]phpcs.xml[.dist]` file, so some insight into what's in there is needed to figure out what's going on.

If your project ruleset is just a wrapper around one of the previously mentioned external rulesets, you may want to ask there first as they may not have added a sniff to enforce this rule to their ruleset (yet).
