### ISSUE TITLE
Is it possible to exclude "Comment missing for @throws tag in function comment" error?

### ISSUE THREAD

**Issue by DmitryZelonkin** [squizlabs/PHP_CodeSniffer#3022]
Hello, 

I would like to exclude an error which causes "Comment missing for @throws tag in function comment". Is it possible?

Result:
![image](https://user-images.githubusercontent.com/17552058/87854579-90de2900-c91b-11ea-9850-ab79c59ba832.png)

My rule:
![image](https://user-images.githubusercontent.com/17552058/87854589-a7848000-c91b-11ea-9809-0aff946c5fc7.png)

Code:
![image](https://user-images.githubusercontent.com/17552058/87854600-c3882180-c91b-11ea-995b-32c6eebc96fb.png)

Best regards,
Dmitry

**Comment by jrfnl** [comment]
@DmitryZelonkin Try running PHPCS with the `-s` option to see the error code for that particular message and then exclude it.

**Comment by DmitryZelonkin** [comment]
@jrfnl my bad( I have not seen this option in the documentation. Thank you!

**Comment by jrfnl** [comment]
@DmitryZelonkin No worries, glad you got it working ;-)
