### ISSUE TITLE
It's hard to test different configurations in a unit test

### ISSUE THREAD

**Issue by morozov** [squizlabs/PHP_CodeSniffer#3024]
Consider the following test example:

```php
<?php

use PHP_CodeSniffer\Config;

require __DIR__ . '/vendor/autoload.php';

define('PHP_CODESNIFFER_CBF', false);

$c1 = new Config(['--basepath=' . __DIR__]);
var_dump($c1->basepath);
// string(35) "/home/morozov/Projects/diff-sniffer"

$c2 = new Config(['--basepath=' . __DIR__]);
var_dump($c2->basepath);
// NULL
```

The second instance didn't initialize properly because of the shared static state. As a workaround, the test may use reflection.

**Comment by jrfnl** [comment]
I hope I got it right, but I have a feeling this will be fixed in PHPCS 4.x - see https://github.com/squizlabs/PHP_CodeSniffer/issues/2675

**Comment by morozov** [comment]
Thank you @jrfnl. It looks the same. Closing as duplicate.
