### ISSUE TITLE
Getting identified as malware by windows defender

### ISSUE THREAD

**Issue by SteveMcArthur** [squizlabs/PHP_CodeSniffer#3042]
Whilst installing PHP_CodeSniffer via composer on windows, defender identifies PHP_CodeSniffer as a "Severe Threat" and removes it from the computer.

`Threat detected: Backdoor:PHP/Dirtelti.MTF`

```
Affected items:
file: \vendor\composer\ff331b7a\squizlabs-PHP_CodeSniffer-d7c00c3\src\Standards\Squiz\Tests\PHP\EvalUnitTest.inc
```
[Microsoft link to threat type](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Backdoor:PHP/Dirtelti.MUF&ThreatID=2147761431)

I know this is a false positive and probably linked to #2468 
You CAN tell defender to allow this exception

So I suppose it is just something to be aware of.

**Comment by n2diving-dgx** [comment]
![image](https://user-images.githubusercontent.com/17930467/89587655-09941f00-d810-11ea-914c-17694e6ee05c.png)

**Comment by gsherwood** [comment]
The contents of the file is:
```
<?php
eval('$var = 4;');
$string = '$var = 4;';
eval($string);
?>
```
It's used to test the sniff that detects and bans evals.

The tests are shipped in version 3 but have been removed in version 4 as this is a BC break.

Closing this as there is no change I can make to version 3 to resolve this.
