### ISSUE TITLE
PHPCS does not support composer-plugin-api 2.0

### ISSUE THREAD

**Issue by SalifT** [squizlabs/PHP_CodeSniffer#3045]
**Describe the bug**
Hi,
I wanted to report an issue when running ```composer global require "squizlabs/php_codesniffer=*"``` with composer 2.

**The error message**
```
  Problem 1
    - dealerdirect/phpcodesniffer-composer-installer is locked to version v0.5.0 and an update of this package was not requested.
    - dealerdirect/phpcodesniffer-composer-installer v0.5.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.

Use the option --with-all-dependencies to allow upgrades, downgrades and removals for packages currently locked to specific versions.

You are using a snapshot build of Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report an issue to them to ask them to support Composer 2. To work around this you can run Composer with --ignore-platform-req=composer-plugin-api, but this may result in broken plugins and bigger problems down the line.
```
Using ```--with-all-dependencies```doesn't help.

Composer suggests maintainers to update plugin's dependency to allow ```composer-plugin-api``` with ```2.0``` 
@see https://php.watch/articles/composer-2#plugin-api-2

**Comment by jrfnl** [comment]
@SalifT This is not a bug in PHPCS - which doesn't have the installer nor the plugin api as dependencies -, or even in the PHPCS Composer installer plugin, which does.

This is a bug in your own setup, where you appear to require the `dealerdirect/phpcodesniffer-composer-installer` plugin at version `0.5.0`. Version `0.5.0` is two years old, i.e. from long before Composer 2.0.

That plugin released [version `0.7.0`](https://github.com/Dealerdirect/phpcodesniffer-composer-installer/releases) over a month ago which has full support for Composer 2.0.0, so I suggest you upgrade.

**Comment by garyee** [comment]
I do get the exact same error, but I do not have any setup. I installed php, then composer then I ran the 
```composer create-project wp-coding-standards/wpcs --no-dev``` from the readme.

**Comment by jrfnl** [comment]
@garyee Your question is related to the WordPressCS external standard - you can find an answer here in that repo: https://github.com/WordPress/WordPress-Coding-Standards/issues/1979#issuecomment-787464170
