### ISSUE TITLE
Unexpected character in input

### ISSUE THREAD

**Issue by kkmuffme** [squizlabs/PHP_CodeSniffer#3048]
**Describe the bug**
Got an error for "Unexpected character in input:  "
in /opt/composer/vendor/squizlabs/php_codesniffer/src/Tokenizers/PHP.php on line 470

Unfortunately, I do not know what exactly triggered this, since it's not logged

**Versions (please complete the following information):**
 - OS: CentOs 8
 - PHP: 7.4
 - PHPCS: 3.5.5
 - Standard: WordPress

**Comment by jrfnl** [comment]
@kkmuffme Could you try running PHPCS with the `-v` option ? That should at least show which file is triggering the error.

**Comment by kkmuffme** [comment]
Tried it, unfortunately I cannot reproduce the error anymore now (since I don't know which file caused this)
Will keep the issue open for now, until I get the issue again
