### ISSUE TITLE
phpcs:ignore/disable in multiline comment is broken

### ISSUE THREAD

**Issue by raalderink** [squizlabs/PHP_CodeSniffer#3050]
Using `phpcs:` in any form in a multiline comment breaks the sniffer. It does work in a single-line comment, but sometimes you want to add it to a function or class, and add it to the already existing docblock

**Code sample**
```php
<?php

class bla {
    /**
     * phpcs:ignore
     */
    public function __construct($var)
    {

    }
}
```
```
phpcs: Internal.Exception: An error occurred during processing; checking has been aborted. The error message was: Undefined index: in ...\vendor\slevomat\coding-standard\SlevomatCodingStandard\Sniffs\Commenting\DisallowCommentAfterCodeSniff.php on line 57
```

**Versions (please complete the following information):**
 - PHP: 7.4.4
 - PHPCS: 3.5.5

This used to work on PHPCS 3.5.3 just fine.

**Comment by glen-84** [comment]
@gsherwood I think that this can be closed.
