### ISSUE TITLE
phpcbf returns exit-code 1 even if all errors were fixed

### ISSUE THREAD

**Issue by caugner** [squizlabs/PHP_CodeSniffer#3057]
**Describe the bug**
`phpcbf` returns exit-code 1 even if it fixed all errors (i.e. there are no remaining errors):
https://github.com/squizlabs/PHP_CodeSniffer/blob/68e0b062d012b93c7381096a6e14b6848cccfe27/src/Runner.php#L221-L224

This prevents `phpcbf` to be run using [lint-staged](https://github.com/okonet/lint-staged) as part of a [husky](https://github.com/typicode/husky) git pre-commit hook.

**Code sample**
`package.json`:
```json
{
  "devDependencies": {
    "husky": "^4.2.5",
    "lint-staged": "^10.2.13",
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "*.php": "vendor/bin/phpcbf"
  }
}
```

**Custom ruleset**
(Not relevant)

**To reproduce**
1. `yarn install` (or `npm install`) with above `package.json`
2. Make change to a PHP file so that it diverges from the coding standard and `git add` it.
3. Run `git commit -m "test"`
4. See that `lint-staged` rejects the commit because `phpcbf` returns a non-zero exit-code:
```
$ git commit -m "test"
husky > pre-commit (node v12.18.3)
[STARTED] Preparing...
[SUCCESS] Preparing...
[STARTED] Hiding unstaged changes to partially staged files...
[SUCCESS] Hiding unstaged changes to partially staged files...
[STARTED] Running tasks...
[STARTED] Running tasks for *.php
[STARTED] vendor/bin/phpcbf
[FAILED] vendor/bin/phpcbf [FAILED]
[FAILED] vendor/bin/phpcbf [FAILED]
[SUCCESS] Running tasks...
[STARTED] Applying modifications...
[SKIPPED] Skipped because of errors from tasks.
[STARTED] Restoring unstaged changes to partially staged files...
[SKIPPED] Skipped because of errors from tasks.
[STARTED] Reverting to original state because of errors...
[SUCCESS] Reverting to original state because of errors...
[STARTED] Cleaning up...
[SUCCESS] Cleaning up...

✖ vendor/bin/phpcbf:
F 1 / 1 (100%)



PHPCBF RESULT SUMMARY
----------------------------------------------------------------------
FILE                                                  FIXED  REMAINING
----------------------------------------------------------------------
C:\path\to\file.php                               5      0
----------------------------------------------------------------------
A TOTAL OF 5 ERRORS WERE FIXED IN 1 FILE
----------------------------------------------------------------------

Time: 160ms; Memory: 8MB


husky > pre-commit hook failed (add --no-verify to bypass)
```

**Expected behavior**
Like `eslint --fix` and `prettier --write`, `phpcbf` should return exit-code 0 if it was able to fix all issues.

Alternatively, it should be possible to trigger this behaviour with a new option `--ignore-fixed-on-exit`.

**Versions (please complete the following information):**
 - OS: Windows 10
 - PHP: 7.3.21
 - PHPCS: 3.5.6
 - Standard: PSR2

**Additional context**
Workaround:

`bin/phpcbf`

```php
#!/usr/bin/env php
<?php

use PHP_CodeSniffer\Runner;

include_once __DIR__.'/../vendor/squizlabs/php_codesniffer/autoload.php';

$runner   = new Runner();
$exitCode = $runner->runPHPCBF();
if ($exitCode === 1) {
    $exitCode = 0;
}
exit($exitCode);
```

`package.json`
```json
{
  "lint-staged": {
    "*.php": "bin/phpcbf"
  }
}
```

**Comment by gsherwood** [comment]
The exit code are going to be revised in version 4 so that 0 always means success. That's being tracked on issue #2898.

It's not something that I can fix before that due to the BC break, so I'm going to close this issue in favour of the 4.0 one. But this issue will be referenced over there to ensure it is revisited as part of that development.

Thanks for the detailed report.

**Comment by nelson6e65** [comment]
You can try this workaround in the meantime:

https://github.com/squizlabs/PHP_CodeSniffer/issues/1818#issuecomment-735620637

**Comment by koshuang** [comment]
fyi, I have a temporary solution for this by just creating a script file and then always return exit code 0.

tools/scripts/phpcbf.sh

```bash
#!/bin/bash

vendor/bin/phpcbf $@

exit 0
```

package.json

```json
{
  //...
  "lint-staged": {
    "*.php": "tools/scripts/phpcbf.sh"
  }
}
```

**Comment by caugner** [comment]
@koshuang I wouldn't recommend *always* returning 0, because an exit-code > 1 could mean there were unfixable errors, and your approach doesn't prevent these to be committed.

**Comment by nelson6e65** [comment]
I'm using a similar approach for lint-staged integration, using an composer script instead:

https://github.com/nelson6e65/php-code-sniffer-helpers
