### ISSUE TITLE
Codesniffer not working in AWS codebuild. 

### ISSUE THREAD

**Issue by akshaysgithub** [squizlabs/PHP_CodeSniffer#3109]
Hi, 

I am trying to run AWS codesniffer inside Codebuild. I want to run phpcs and send it's output to a file. I keep getting exit status 2. What am I doing wrong? 

Error log : 
```

[Container] 2020/09/09 08:44:48 Running command which phpcs

/usr/bin/phpcs

[Container] 2020/09/09 08:44:48 Running command phpcs $PWD/web/ > file.txt

[Container] 2020/09/09 08:44:49 Command did not exit successfully phpcs $PWD/web/ > file.txt exit status 2

[Container] 2020/09/09 08:44:49 Phase complete: BUILD State: FAILED

[Container] 2020/09/09 08:44:49 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: phpcs $PWD/web/ > file.txt. Reason: exit status 2


```

Code : 

```

      - file_Name=$(date +'%Y-%m-%d-%T')_supplier_code_sniffer_report.txt
      - backup_dir=$(date +'%Y/%m/%d')
  build:
    commands:
      - apt-get update && apt-get install -y sed php-codesniffer
      - which phpcs
      - phpcs $PWD/web/ > file.txt
      - cd .. && aws s3 cp file.txt s3://automated-testing-roobeo/supplier/${backup_dir}/

```

What am I missing?

**Comment by gsherwood** [comment]
Exit status 2 means errors were found in the code, and some were fixable by PHPCBF.

If you don't get an exit code of 0, it means coding standard errors were found in the code you are checking. If you want your build to pass even if errors are found, you'll need to figure out how to do that in whatever pipeline you are using.

**Comment by gsherwood** [comment]
Exit status 2 means errors were found in the code, and some were fixable by PHPCBF.

If you don't get an exit code of 0, it means coding standard errors were found in the code you are checking.

If you want to always return a 0 exit code, even if errors are found, you will need to all the following flags to your command:
`--runtime-set ignore_errors_on_exit 1 --runtime-set ignore_warnings_on_exit 1`

So you're build commands would be:
```
  build:
    commands:
      - apt-get update && apt-get install -y sed php-codesniffer
      - which phpcs
      - phpcs --runtime-set ignore_errors_on_exit 1 --runtime-set ignore_warnings_on_exit 1 $PWD/web/ > file.txt
      - cd .. && aws s3 cp file.txt s3://automated-testing-roobeo/supplier/${backup_dir}/
```

**Comment by akshaysgithub** [comment]
This worked nicely. Thanks a lot. :-)
