### ISSUE TITLE
Help: Getting PHPCS Response ERROR: Referenced sniff "PHPCSUtils" does not exist

### ISSUE THREAD

**Issue by CrowdForge** [squizlabs/PHP_CodeSniffer#3110]
I've installed codesniffer with homebrew on a mac using the guide here: https://luminfire.com/2017/03/01/wordpress-php-codesniffer-favorite-editor/

But I'm getting the following error in dev tools on atom:

PHPCS Response ERROR: Referenced sniff "PHPCSUtils" does not exist

I don't recognize PHPCSUtils from any of the process or configuration.  Any thoughts / ideas?

**Comment by jrfnl** [comment]
@CrowdForge Based on that tutorial, you would be using a git clone and based on the error, you seem to be using the `develop` version of the WordPress Coding Standards. Either switch to `master` or, better yet, use Composer to install WordPressCS to make sure you use a stable version.

See the installation instructions for WordPressCS; https://github.com/WordPress/WordPress-Coding-Standards

Regarding [PHPCSUtils](https://github.com/phpcsstandards/phpcsutils/): that is a new dependency which WordPressCS 3.0.0 (currently in development) will use, It is basically a layer between PHP_CodeSniffer and an external standard to help with some of the more complex logic used in sniffs and with PHPCS cross-version compatibility.

**Comment by kishanjasani** [comment]
Thanks, @jrfnl . Switching to the master branch is works for me. :+1:

**Comment by Micu22** [comment]
I am getting the same error on version 3.5.8, any idea why?

**Comment by jrfnl** [comment]
@Micu22 See theabove - you are using a non-released, development version of an external standard. Switch to using a tagged release and all will be fine.

**Comment by Micu22** [comment]
I can confirm that is the solution, I just thought that 3.5.8 has it already stable.

**Comment by jrfnl** [comment]
`3.5.8` is the version of PHPCS you are using, which is unrelated to the version of the external standard you are using (or the version of their dependencies).

**Comment by jagirbahesh** [comment]
> @CrowdForge Based on that tutorial, you would be using a git clone and based on the error, you seem to be using the `develop` version of the WordPress Coding Standards. Either switch to `master` or, better yet, use Composer to install WordPressCS to make sure you use a stable version.
> 
> See the installation instructions for WordPressCS; https://github.com/WordPress/WordPress-Coding-Standards
> 
> Regarding [PHPCSUtils](https://github.com/phpcsstandards/phpcsutils/): that is a new dependency which WordPressCS 3.0.0 (currently in development) will use, It is basically a layer between PHP_CodeSniffer and an external standard to help with some of the more complex logic used in sniffs and with PHPCS cross-version compatibility.

Thanks It is working 👌🏻

**Comment by brothman01** [comment]
I had this issue and switching WordPress coding standards to the master branch worked for me
