### ISSUE TITLE
Strange file CallTimePassByReferenceUnitTest.inc messes with PhpStorm's syntax highlighter

### ISSUE THREAD

**Issue by hopeseekr** [squizlabs/PHP_CodeSniffer#3114]
The file https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/Generic/Tests/Functions/CallTimePassByReferenceUnitTest.inc

interferes with PhpStorm's syntax error highlighter.

I can't even figure out why this file isn't excluded in your `.gitattributes`, which is why I opened this ticket.

**Comment by jrfnl** [comment]
Please see #1908 and #548.

Suggest: close.

**Comment by gsherwood** [comment]
Tests have been removed in version 4.0. Closing.
