### ISSUE TITLE
How to disallow solely `void` and solely `null` return types?

### ISSUE THREAD

**Issue by cliffordp** [squizlabs/PHP_CodeSniffer#3116]
I found https://github.com/squizlabs/PHP_CodeSniffer/tree/master/src/Standards/Squiz/Sniffs/Commenting and https://github.com/spryker/code-sniffer/blob/master/Spryker/Sniffs/Commenting/DocBlockParamNotJustNullSniff.php but didn't see an existing rule for disallowing `@return void` and `@return null` - where the suggestion is to _not_ have any `@return` at all.

Am I missing it somewhere or do I need to write my own sniff? Thanks for any help!

**Comment by gsherwood** [comment]
There isn't a sniff included with PHPCS to do this. I'm not sure if there is one written by someone else, so you would possibly need to write one.
