### ISSUE TITLE
Suggestion: make isset, unset and empty parenthesis owners

### ISSUE THREAD

**Issue by jrfnl** [squizlabs/PHP_CodeSniffer#3118]
I was just wondering why `isset()`, `unset()` and `empty()` - all language constructs which require parentheses - are not considered parentheses owners.

Would it make sense to change that ? Should be a relatively easy change to make as far as I can see.

Happy to make the changes if there is interest.

---

[Edit]: Might be useful to include `exit()`, `die()` and `eval()` as well, though these three don't _require_ parentheses, but are "owners" when the parentheses are present.

**Comment by gsherwood** [comment]
Makes sense to me. For the constructs that don't require parenthesis, just need to make sure they don't go hunting for unowned ones and claiming them, although this may already be protected against.

**Comment by jrfnl** [comment]
> For the constructs that don't require parenthesis, just need to make sure they don't go hunting for unowned ones and claiming them, although this may already be protected against.

Eh.. not really... that's part of the problem with closure `T_USE` as parenthesis owner for which PR #3104 is open.....

With that in mind, should this be addressed in PHPCS 3.x or 4.x ? (PR #3104 is for 4.x and includes part of the protection which would need to be added for the above as well.)

**Comment by jrfnl** [comment]
Closing as replaced by PHPCSStandards/PHP_CodeSniffer#23
