### ISSUE TITLE
PHPCS 4.x | Test suite broken

### ISSUE THREAD

**Issue by jrfnl** [squizlabs/PHP_CodeSniffer#3120]
While making some changes for PHPCS 4.x, I wasn't getting an expected error when I ran the unit tests on PHP 7.4/PHPUnit 9.x and when I looked more closely, I realized that the sniff tests weren't being run at all, only the "Core" tests were being run.

The same can be seen in the Travis runs:

#### PHP 7.2:
```
$ vendor/bin/phpunit tests/AllTests.php

PHPUnit 8.5.8 by Sebastian Bergmann and contributors.
...............................................................  63 / 567 ( 11%)
<snip>
...........................................S................... 567 / 567 (100%)
```

#### PHP 7.3:
```
$ vendor/bin/phpunit tests/AllTests.php

PHPUnit 9.3.10 by Sebastian Bergmann and contributors.
...............................................................  63 / 368 ( 17%)
<snip>
........................S............................           368 / 368 (100%)
```

#### PHP 7.4:
```
$ vendor/bin/phpunit tests/AllTests.php

PHPUnit 9.3.10 by Sebastian Bergmann and contributors.
...............................................................  63 / 368 ( 17%)
<snip>
........................S............................           368 / 368 (100%)
```

#### PHP nightly:
```
$ vendor/bin/phpunit tests/AllTests.php

PHPUnit 9.3.10 by Sebastian Bergmann and contributors.
...............................................................  63 / 368 ( 17%)
<snip>
........................S............................           368 / 368 (100%)
```

This will need further investigation.

**Comment by gsherwood** [comment]
Interesting. It's been working fine the entire time when I run it locally so have not noticed. Should be:
```
PHPUnit 9.1.2 by Sebastian Bergmann and contributors.

.........................................S.....................  63 / 567 ( 11%)
............................................................... 126 / 567 ( 22%)
............................................................... 189 / 567 ( 33%)
............................................................... 252 / 567 ( 44%)
............................................................... 315 / 567 ( 55%)
............................................................... 378 / 567 ( 66%)
..........S............................................S....... 441 / 567 ( 77%)
............................................................... 504 / 567 ( 88%)
............................................................... 567 / 567 (100%)


336 sniff test files generated 711 unique error codes; 417 were fixable (58%)

Time: 00:03.715, Memory: 60.00 MB
```

**Comment by gsherwood** [comment]
Forgot to say, that's my output on 7.3 and 7.4. I don't have a 7.2 version handy.

**Comment by jrfnl** [comment]
I'll have a look once I finish what I'm currently working on for #3115.

**Comment by jrfnl** [comment]
Might be something to do with PHPUnit. Based on what you posted, you are using PHPUnit 9.1 locally, while Travis (and me locally) are using PHUnit 9.3.x

**Comment by gsherwood** [comment]
I think you're right about the version:

Last build I found that looked ok: https://travis-ci.org/github/squizlabs/PHP_CodeSniffer/jobs/687256325
And the next one, showing a big drop in tests: https://travis-ci.org/github/squizlabs/PHP_CodeSniffer/jobs/710213845

Looks like something to do with 9.2

**Comment by gsherwood** [comment]
Updated and ran locally:
```
PHPUnit 9.3.10 by Sebastian Bergmann and contributors.

.........................................S.....................  63 / 567 ( 11%)
............................................................... 126 / 567 ( 22%)
............................................................... 189 / 567 ( 33%)
............................................................... 252 / 567 ( 44%)
............................................................... 315 / 567 ( 55%)
............................................................... 378 / 567 ( 66%)
..........S............................................S....... 441 / 567 ( 77%)
............................................................... 504 / 567 ( 88%)
............................................................... 567 / 567 (100%)


336 sniff test files generated 711 unique error codes; 417 were fixable (58%)

Time: 00:03.736, Memory: 66.00 MB
```

**Comment by jrfnl** [comment]
I can confirm now that it has something to do with PHPUnit. Will have a trawl through the changelog to see if I can figure out what's going on.

Seeing that things appear to be working on `9.1.2`, I suspect something may have changed in the `TestSuite` class between `9.1.2` and `9.1.5` in which the tests don't run anymore.

And it's weird that you seem to have it working locally on `9.3.10` as in that case it should work on Travis too, but it doesn't.

Results of test run for PSR1 against PHPUnit 9.0.2, 9.1.2 (the version you were originally using locally), 9.1.5, 9.2.6, 9.3.10:
```
# phpunit ./tests/AllTests.php --filter psr1
PHPUnit 9.0.2 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.4.8
Configuration: path/to/PHP_CodeSniffer/phpunit.xml

...................                                               19 / 19 (100%)

54 sniff test files generated 75 unique error codes; 63 were fixable (84%)

Time: 34.08 seconds, Memory: 34.00 MB

OK (19 tests, 0 assertions)
PHPUnit 9.1.2 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.4.8
Configuration: path/to/PHP_CodeSniffer/phpunit.xml

...................                                               19 / 19 (100%)

54 sniff test files generated 75 unique error codes; 63 were fixable (84%)

Time: 00:34.346, Memory: 36.00 MB

OK (19 tests, 0 assertions)
PHPUnit 9.1.5 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.4.8
Configuration: path/to/PHP_CodeSniffer/phpunit.xml

Time: 00:00.740, Memory: 14.00 MB

No tests executed!
PHPUnit 9.2.6 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.4.8
Configuration: path/to/PHP_CodeSniffer/phpunit.xml

No tests executed!
PHPUnit 9.3.10 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.4.8
Configuration: path/to/PHP_CodeSniffer/phpunit.xml

No tests executed!                                                                
```

**Comment by gsherwood** [comment]
> And it's weird that you seem to have it working locally on `9.3.10` as in that case it should work on Travis too, but it doesn't.

Yeah, not sure why it is working for me. I just installed PHP 7.4.10 to see if there was some combination of issues there, but still working for me on PHPUnit 9.3.10.

**Comment by jrfnl** [comment]
Got it! See #3122

**Comment by gsherwood** [comment]
Thank you very much! I have merged this and the general travis cleanup you did, so just waiting on results now.

**Comment by gsherwood** [comment]
It works 🎉 

Thank you for both noticing and fixing this.

**Comment by jrfnl** [comment]
I suspect it was caused by the changes made in response to this PHPUnit issue: https://github.com/sebastianbergmann/phpunit/issues/4232

One of the recommendations in that issue is to not use "underscore separated pseudo-namespaces", i.e. the class name `PHP_CodeSniffer_AllTests` which probably should have been changed to `AllTests` years ago when the `PHP_CodeSniffer\Tests` namespace was added to the file. Similarly, the `require_once` statements should probably be replaced by `use` statements or be moved to the `bootstrap.php` file.

Either way, the fix as pulled will get things working again, the rest can be addressed in separate tickets if someone feels the urge to do so.

I will open an issue in PHPUnit to inform them of the break we saw and the solution, just in case anyone else runs into the same thing.

**Comment by jrfnl** [comment]
Response from the PHPUnit maintainer:

> The "AllTests.php" approach of manually/programmatically creating a TestSuite object has not been supported for years.

Looking back at the PHPUnit commit history, support looks to be dropped in PHPUnit 3 / 2009, so I suppose an issue should be opened to modernize the test suite setup for PHPCS 4.x.
