### ISSUE TITLE
PHP Fatal error:  Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

### ISSUE THREAD

**Issue by OneCodeMonkey** [squizlabs/PHP_CodeSniffer#3123]
**Describe the bug**
When run in PHP version >= 7.3, it reports this. But no problem in PHP7.2 or lower.
PHP Fatal error:  Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

**Comment by OneCodeMonkey** [comment]
confusing  :(

**Comment by gsherwood** [comment]
This was fixed in #2086, and released in version 3.3.1. That's been for over 12 months now and I've had no other cases on this so I suspect you may be using an old version of PHP_CodeSniffer. Can you please provide the version you are using.

**Comment by OneCodeMonkey** [comment]
> This was fixed in #2086, and released in version 3.3.1. That's been for over 12 months now and I've had no other cases on this so I suspect you may be using an old version of PHP_CodeSniffer. Can you please provide the version you are using.

Ok, it is.
My composer is 
`"squizlabs/php_codesniffer": "~3.5",`

Thanks~!

**Comment by gsherwood** [comment]
👍  Update and you should be fine
