### ISSUE TITLE
PHPStorm 2020.2 compactability

### ISSUE THREAD

**Issue by reanim8ed** [squizlabs/PHP_CodeSniffer#3125]
**Describe the bug**
After PHPStorm update from 2020.1 to 2020.2 every file now has "Please trim any trailing whitespace" warning: https://i.imgur.com/ZzNOpb9.png

If I run Code Beautifier - nothing changes in file but the errors are gone: https://i.imgur.com/UlUn2TQ.png

**Comment by gsherwood** [comment]
I'm not sure what I can do to help here. That error message is not one that is included with PHPCS, so you may be using a coding standard not maintained here. You also said you run a fix over it and the error stops reporting, which could mean there was whitespace there and something removed it. Maybe it's not being shown in the editor?

The only way to know if this is a PHPCS issue is for you to run PHPCS outside of the editor and provide the file and standard as part of this bug report so I can try replicating the issue.

**Comment by reanim8ed** [comment]
Hi @gsherwood 
PHPStorm version I'm using: 2020.2
CodeSniffer is 3.5.6: https://bit.ly/32VZnzg
Symfony coding standard rules are from this repo: https://github.com/djoos/Symfony-coding-standard

**Comment by binary64** [comment]
@reanim8ed try running phpcbf -vv <file> - you will probably see it's doing 50 passes and giving up.
