### ISSUE TITLE
Exclude + Include not working correctly together

### ISSUE THREAD

**Issue by spaceemotion** [squizlabs/PHP_CodeSniffer#3136]
**Describe the bug**
In order to "upgrade" the style of our code base, we would like to incrementally introduce a new phpcs ruleset:
- Everywhere except `module/a`: legacy
- only in `module/a`: modern

**Code sample**
```php
<?php

class Icon
{
}
```

**Custom ruleset**
```xml
<?xml version="1.0"?>
<ruleset name="xxx">
  <arg value="p"/>
  <arg name="colors"/>

  <arg name="extensions" value="php" />

  <rule ref="PSR12"> <!-- modern -->
    <include-pattern>module/a/*</include-pattern>
  </rule>

  <rule ref="PSR2"> <!-- legacy -->
    <exclude-pattern>module/a/*</exclude-pattern>
  </rule>
</ruleset>
```

**To reproduce**
1. Create a file called `test.php` with the code sample above...
2. Run `phpcs test.php ...`
3. See no error
4. Disable the PSR12 rule and rerun phpcs
5. See the "Each class must be in a namespace of at least one level (a top-level vendor name)" error

```
. 1 / 1 (100%)


Time: 33ms; Memory: 8MB
```

```
E 1 / 1 (100%)



FILE: /var/www/html/xxxxx/test.php
-----------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-----------------------------------------------------------------------------------------------
 9 | ERROR | Each class must be in a namespace of at least one level (a top-level vendor name)
-----------------------------------------------------------------------------------------------

Time: 54ms; Memory: 8MB
```

**Expected behavior**
No interference between the rules.

**Versions (please complete the following information):**
 - OS: Docker-Image (Debian GNU/Linux 9 (stretch))
 - PHP: PHP 7.1.28 (cli)
 - PHPCS: 3.5.6
 - Standard: custom

**Comment by jrfnl** [comment]
I don't have a solution for you, but I can explain what's causing this: the PSR12 ruleset uses a lot of rules coming from the PSR2 standard, so while you include the files for the PSR12 standard, you subsequently exclude all rules which the PSR12 standard uses which come from PSR2 for those same files.

The only solution I can think of for now, would be to have two rulesets, one with `<file>` includes for all the code following the "modern" style and one with `<file>.</file>` and (top-level) `<exclude-pattern>`s for the updated files/directories to handle the "legacy" code. This would require running two separate scans, one against each ruleset.
