### ISSUE TITLE
Documentation: update code examples for array properties to new format

### ISSUE THREAD

**Issue by jrfnl** [squizlabs/PHP_CodeSniffer#3160]
As it's been more than two years since PHPCS 3.3.0 came out, I think we can safely assume that the majority of users will be on that version (or newer).

I'd like to suggest updating the code samples for array properties on the https://github.com/squizlabs/PHP_CodeSniffer/wiki/Customisable-Sniff-Properties page to use the new format.

The Annotated ruleset page contains information on both formats (old and new) already, so users on older PHPCS versions can see how the set them on PHPCS < 3.3.0 there.

**Comment by gsherwood** [comment]
Good idea. I've done that now.
