### ISSUE TITLE
Error message when running PHPCBF

### ISSUE THREAD

**Issue by jackjpdiscos** [squizlabs/PHP_CodeSniffer#3166]
Hi,

I get the following error when running the PHPCBF command:

> vendor/bin/phpcbf : PHP Fatal error:  Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: Trying to access array offset on value 
> of type null in C:\xampp\php\vendor\wp-coding-standards\wpcs\WordPress\Sniff.php on line 1291 in 
> C:\xampp\php\vendor\squizlabs\php_codesniffer\src\Runner.php:606
> At line:1 char:1
> + vendor/bin/phpcbf --standard=WordPress MDJM\includes\actions.php
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (PHP Fatal error...\Runner.php:606:String) [], RemoteException
>     + FullyQualifiedErrorId : NativeCommandError
>  
> Stack trace:
> 
> Fatal error: Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: Trying to access array offset on value of type null in C:\xampp\php
> \vendor\wp-coding-standards\wpcs\WordPress\Sniff.php on line 1291 in C:\xampp\php\vendor\squizlabs\php_codesniffer\src\Runner.php:606
> Stack trace:
> #0 C:\xampp\php\vendor\wp-coding-standards\wpcs\WordPress\Sniff.php(1291): PHP_CodeSniffer\Runner->handleErrors(8, 'Trying to acces...
> ', 'C:\\xampp\\php\\ve...', 1291, Array)
> #1 C:\xampp\php\vendor\wp-coding-standards\wpcs\WordPress\Sniffs\CSRF\NonceVerificationSniff.php(153): WordPress\Sniff->has_nonce_chec
> k(117)
> #2 C:\xampp\php\vendor\wp-coding-standards\wpcs\WordPress\Sniff.php(832): WordPress\Sniffs\CSRF\NonceVerificationSniff->process_token(
> 117)
> #3 C:\xampp\php\vendor\squizlabs\php_codesniffer\src\Files\File.php(496): WordPress\Sniff->process(Object(PHP_CodeSniffer\Files\LocalF
> ile), 117)
> #4 C:\xampp\php\vendor\squizlabs\php_codesniffer\src\Files\LocalFile.php(91): PHP_CodeSniffer\Files\File->process()
> #5 C:\xampp\php\vendor\squizlabs\php_cod in C:\xampp\php\vendor\squizlabs\php_codesniffer\src\Runner.php on line 606
> #0 C:\xampp\php\vendor\wp-coding-standards\wpcs\WordPress\Sniff.php(1291): PHP_CodeSniffer\Runner->handleErrors(8, 'Trying to 
> acces...', 'C:\\xampp\\php\\ve...', 1291, Array)
> #1 C:\xampp\php\vendor\wp-coding-standards\wpcs\WordPress\Sniffs\CSRF\NonceVerificationSniff.php(153): 
> WordPress\Sniff->has_nonce_check(117)
> #2 C:\xampp\php\vendor\wp-coding-standards\wpcs\WordPress\Sniff.php(832): 
> WordPress\Sniffs\CSRF\NonceVerificationSniff->process_token(117)
> #3 C:\xampp\php\vendor\squizlabs\php_codesniffer\src\Files\File.php(496): 
> WordPress\Sniff->process(Object(PHP_CodeSniffer\Files\LocalFile), 117)
> #4 C:\xampp\php\vendor\squizlabs\php_codesniffer\src\Files\LocalFile.php(91): PHP_CodeSniffer\Files\File->process()
> #5 C:\xampp\php\vendor\squizlabs\php_cod in C:\xampp\php\vendor\squizlabs\php_codesniffer\src\Runner.php on line 606

**Comment by jrfnl** [comment]
@jackjpdiscos You may want to report this to the [WordPressCS](https://github.com/WordPress/WordPress-Coding-Standards) repo instead, including a code samples with which this issue would be reproducable. Without more information, there is not much anyone can do about this.

**Comment by jackjpdiscos** [comment]
@jrfnl Thank you, I will do.
