### ISSUE TITLE
Can PHPCBF automatically fix Yoda conditions?

### ISSUE THREAD

**Issue by Luc45** [squizlabs/PHP_CodeSniffer#3169]
phpcs.xml.dist: `<rule ref="Generic.ControlStructures.DisallowYodaConditions.Found"/>`

Running PHPCS shows me all Yoda conditions in the codebase (there are a LOT).

Running PHPCBF tells me there's no fixable errors found.

Can PHPCBF fix Yoda conditions automatically?

Thanks.

**Comment by gsherwood** [comment]
No, the included sniff cannot fix yoda conditions. PHPCBF intentionally does not change code around as the meaning of the code may change. Instead, it focuses on fixing code formatting issues, which should not impact the functionality of the code itself.

Custom sniffs can do whatever they want, but I have set this rule for the built-in sniffs to make the fixing process a bit safer.

Does that answer you question?

**Comment by Luc45** [comment]
It does, thank you.

During my research, it seems that the only PHP tool that can convert Yoda conditions is the [yoda_style sniff](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.16/doc/rules/control_structure/yoda_style.rst) from PHP CS Fixer.

**Comment by Luc45** [comment]
Thanks for taking your time to answer this, @gsherwood. Closing this issue.

**Comment by jrfnl** [comment]
IIRC the [Slevomat](https://github.com/slevomat/coding-standard/) standard actually has a sniff for PHPCS which can handle auto-fixing yoda condition.
