### ISSUE TITLE
empty cache file === PHP Notice

### ISSUE THREAD

**Issue by voku** [squizlabs/PHP_CodeSniffer#3173]
**Describe the bug**

If the cache file (--cache=) is empty, I see this on the first run. 

```
PHP Notice:  Trying to access array offset on value of type null in phar:///home/lmoelleken/meerx/Framework/thirdparty/phpcs.phar/src/Util/Cache.php on line 2
PHP Stack trace:
PHP   1. {main}() /home/lmoelleken/meerx/Framework/thirdparty/phpcs.phar:0
PHP   2. PHP_CodeSniffer\Runner->runPHPCS() /home/lmoelleken/meerx/Framework/thirdparty/phpcs.phar:6
PHP   3. PHP_CodeSniffer\Runner->run() phar:///home/lmoelleken/meerx/Framework/thirdparty/phpcs.phar/src/Runner.php:2
PHP   4. PHP_CodeSniffer\Util\Cache::load() phar:///home/lmoelleken/meerx/Framework/thirdparty/phpcs.phar/src/Runner.php:2
```

```
        => Using cache file: /home/lmoelleken/meerx/App/tmp/cache/phpcs_6fc27bc317b46a21ef95763734f89a80
        * cache was invalid and has been cleared *
DONE (0 files in cache)
```

---

https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Util/Cache.php
```php
        if (file_exists(self::$path) === true) {
            self::$cache = json_decode(file_get_contents(self::$path), true); // NULL for empty files // https://3v4l.org/ADgWv

            // Verify the contents of the cache file.
            if (self::$cache['config'] !== $configData) { // <- we can get a PHP Notice here because of $cache['config'] === NULL
                self::$cache = [];
                if (PHP_CODESNIFFER_VERBOSITY > 1) {
                    echo "\t* cache was invalid and has been cleared *".PHP_EOL;
                }
            }
        } else if (PHP_CODESNIFFER_VERBOSITY > 1) {
            echo "\t* cache file does not exist *".PHP_EOL;
        }

        self::$cache['config'] = $configData;
```

**Versions (please complete the following information):**
 - OS: Ubuntu 20.04
 - PHP: 7.4
 - PHPCS: 3.5.8

**Comment by jrfnl** [comment]
@voku Could you provide steps to reproduce this issue ?

I've not been able to reproduce this unless I manually cleared out the content of a cache file (or replaced it with nonsense), but left the file in place.

Things I've tried:
1. Running with `--cache=` - results correctly in a `ERROR: The specified cache file path "_current directory_" is a directory` and breaks off before starting the run.
2. Running with `--cache=./path/to/dir/` - same thing.
3. Running with `--cache=phpcs.cache` - works without the error notice.
4. Deleting the previously created `phpcs.cache` file and running again with `--cache=phpcs.cache` - works without the error notice.
5. Manually created an empty `phpcs.cache` file and running again with `--cache=phpcs.cache` - this will throw the error notice.
6. Manually created a `phpcs.cache` file and just put some random text in it and running again with `--cache=phpcs.cache` - this will throw the error notice too.

This feels like an error which should not be possible if PHPCS is properly used, but I'd like to be proven wrong


Based on the code in the `Cache` class and the PHP manual, the only time this error could occur is if the cache file exists, but is an empty file or a file not created by PHPCS as a cache file.

From: https://www.php.net/manual/en/function.json-decode.php
_"NULL is returned if the json cannot be decoded or if the encoded data is deeper than the recursion limit. "_

**Comment by gsherwood** [comment]
I can't reproduce this even when I blank out the file or enter rubbish, but I can clearly see json_decode returning NULL.

I'm hesitant to merge in the PR that has been submitted for this as it feels like it is potentially masking an issue that should be tracked down and fixed properly. If the cache file is being produced incorrectly by PHPCS, that's a bigger issue. Hiding the error is just going to mean that the cache will never be used, hurting performance.

Are you able to provide some steps to reproduce the issue with PHPCS itself?
