### ISSUE TITLE
Report unfixable errors only

### ISSUE THREAD

**Issue by szepeviktor** [squizlabs/PHP_CodeSniffer#3193]
**Describe the ~~bug~~ new feature**
While running in CI PHPCS may hold back contributors by reporting fixable (e.g. formatting) errors.
Please see https://tomasvotruba.com/blog/2020/12/28/why-coding-standards-should-not-be-part-of-ci

**To reproduce**

1. vendor/bin/phpcs --unfixable-only
2. List only unfixable errors

**Expected behavior**

All fixable errors could then be fixed in another PR.

**Comment by jrfnl** [comment]
This is not a bug, but a feature request.

**Comment by szepeviktor** [comment]
I do not maintain big OSS project, so I allow my contributors anything.
In an agency everyone should clean up their code.

So I just follow the things in the above article...

**Comment by szepeviktor** [comment]
> Why allow "dirty" code to be merged when it could easily be "clean" ?

BTW If I contribute 2 hours of work to a project **for free** a single whitespace should not be a ❌ in CI.

**Comment by jrfnl** [comment]
@szepeviktor He, nobody is forcing you to use CS in your projects, let alone have it run in CI.

> BTW If I contribute 2 hours of work to a project for free a single whitespace should not be a x in CI.

So, instead, you think the maintainers of the projects you want to contribute to, should spend their spare and unpaid time cleaning up your code contribution ?

Sorry, but I don't get it. Personally, I'd rather - as a reviewer - be able to focus on the proposed change, then be distracted by horribly formatted code and miss something essential when reviewing.

**Comment by Dwarfex** [comment]
I noticed maintainers checking the Status of a failed build.
As this is an old, grown project i fully understand the wish to improve code quality and setting a goal for better readability.

IMHO: 
- Auto-fixable changes should be done by jenkins and included in the code if possible. (this solves 95% of the issues)(alternative: provide easy way to execute corrections for contributor)
- Non auto-fixable changes should be changed by the contributor. 
Doing both results in less pain for the contributor and better quality of the repository.
Which in the end results in less problems/bugs for the user :)
