### ISSUE TITLE
PHP Fatal error thrown with PHP 8.0.1

### ISSUE THREAD

**Issue by divineniiquaye** [squizlabs/PHP_CodeSniffer#3198]
I updated my PHP version from 7.3 to 8.0.1 in my [Scrutinizer Ci](https://scrutinizer-ci.com/) account. Anytime I run phpcs tests, it fails with this error message:

`PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /home/scrutinizer/.analysis/phpcs/vendor/squizlabs/php_codesniffer/src/Config.php on line 420`

Phpcs tests works quite well in both my local environment, Travis and GitHub action. I've gone through the code at https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Config.php#L420 but coudn't come up with a solution as I see no problem.

I will appreciate it if this issue get resolved.

**Comment by jrfnl** [comment]
@divineniiquaye Sounds like Scrutinizer is using an outdated version of PHPCS. Please contact their helpdesk and ask them to update to the latest release or set up Scrutinizer in a way that it will run the latest version via Composer yourself.

I suggest for this issue to be closed as there is nothing we can do about this as the code issues (PHP 7.4 related) was already fixed well over a year ago.

**Comment by divineniiquaye** [comment]
> @divineniiquaye Sounds like Scrutinizer is using an outdated version of PHPCS. Please contact their helpdesk and ask them to update to the latest release or set up Scrutinizer in a way that it will run the latest version via Composer yourself.
> 
> I suggest for this issue to be closed as there is nothing we can do about this as the code issue (PHP 7.4 related) was already fixed well over a year ago.

Alright I'll contact them.

**Comment by jrfnl** [comment]
Side-note: PHPCS has _run-time_ support for PHP 8.0 as of PHPCS 3.5.7 (i.e. all PHPCS functionality will work on PHP 8.0 without any errors), however, PHP 8.0 _syntax_ support is not complete yet, i.e. when using new, PHP 8.0+ specific syntax, sniffs may throw incorrect errors as not all PHP 8.0 syntaxes are recognized correctly yet.

**Comment by divineniiquaye** [comment]
Oh okay, then I'll rather downgrade my PHP version till all syntaxes in PHP 8.0 are completed. Thanks.
