### ISSUE TITLE
[FEATURE] disallow if statements as the only statement in else blocks (no-lonely-if)

### ISSUE THREAD

**Issue by danny007in** [squizlabs/PHP_CodeSniffer#3206]
Extra reference https://eslint.org/docs/rules/no-lonely-if add this feature

**Comment by danny007in** [comment]
HI @gsherwood , 
Can u guide me, about this issue resolve.
i will try.

**Comment by jrfnl** [comment]
@danny007in You may be interested in the new `Universal.ControlStructures.DisallowLonelyIf` sniff in the external [PHPCSExtra](https://github.com/PHPCSStandards/PHPCSExtra) standard, which can detect and auto-fix this (most of the time). See the above linked pull request for full details.
