### ISSUE TITLE
phpcs creating -report-diff file

### ISSUE THREAD

**Issue by ltdeta** [squizlabs/PHP_CodeSniffer#3212]
How to printing a Diff Report? 

The following description does not work => [https://github.com/squizlabs/PHP_CodeSniffer/wiki/Fixing-Errors-Automatically#printing-a-diff-report](url)

`phpcs --report-diff="D:/Temp/changes.diff"  "D:/php-code/index.php"`

=> The command "diff" is either spelled incorrectly or could not be found.

**Comment by jrfnl** [comment]
@ltdeta Could you please provide a little more information ? PHPCS version, OS, whether there is a `phpcs.xml` config in the directory from which you are running the command (and any relevant content of that file) etc

I've tried to reproduce the issue (on Windows 10) based on the information which is currently provided, but cannot reproduce the error and the `diff` file gets written correctly.

**Comment by ltdeta** [comment]
- Win10 - PHPCS 3.5.8

- Command line
phpcs -v -n --report-diff="D:\PSR2_Diff.txt" --standard="D:\project\phpcs-custom-ruleset-PSR2.txt"  7.4 "d:\project\portal_dev" --encoding=windows-1252

- xml ruleset file
[phpcs-custom-ruleset-PSR2.txt](https://github.com/squizlabs/PHP_CodeSniffer/files/5965359/phpcs-custom-ruleset-PSR2.txt)

**Comment by jrfnl** [comment]
@ltdeta Well, presuming the actual ruleset file is called `phpcs-custom-ruleset-PSR2.xml` and that name is used on the command-line and the stray `7.4` in the command is removed, I still cannot reproduce it.

Due to the `-v` it will also show the report on the CLI, but in my test runs, the file report gets written to the disk as well. Tested on Windows 10 with both PHPCS 3.5.8 as well as `master`.

**Comment by jrfnl** [comment]
Oh and just checking: if you run the same command with `--report=full,summary` does it show any auto-fixable errors ? (lines with `| X |` in the full report/summary line at the bottom of the `summary` report)

**Comment by jrfnl** [comment]
Hang on... does the `diff` command work for you at all ? Try this on the CLI: `diff -v` (nothing else).
The output should be something like:
```
diff (GNU diffutils) 3.7
Copyright (C) 2018 Free Software Foundation, Inc.
```

If, however, it says something like this:
```
'diff' is not recognized as an internal or external command,
operable program or batch file.
```
... that's the problem. The `diff` command is not natively available on Windows. However, if you have Git installed, it will be on your system - normally in the `C:\Program Files\Git\usr\bin` directory.

In that case, you can either add that whole directory to the Windows system `path` (though that will overwrite some Windows natively available commands - it's one of the questions asked during the normal gitForWindows install procedure) or you can copy the `diff.exe` file from that directory to somewhere else and put that other directory in the Windows path.

You will need to open a new CLI window for the new path to be available after changes.

**Comment by ltdeta** [comment]
@jrfnl 
The problem was really that `diff` was not installed.
Thanks a lot

Maybe it should be mentioned in the wiki that for using the parameter `--report-diff` `Git - Diff` is needed?

Since I did not want to install `Git` I extracted the necessary files from the setup() and made them available in a directory
msys-2.0.dll
msys-iconv-2.dll
msys-intl-8.dll
diff.exe
diff3.exe

**Comment by jrfnl** [comment]
@ltdeta Glad to hear you got it working.

> Maybe it should be mentioned in the wiki that for using the parameter --report-diff Git - Diff is needed?

`diff` is a *nix bash command, it's not specific to Git, but as it ships with Git and most devs have Git installed, that is just a convenient way to get access to it.

I believe the "official" downloads for when you don't have `diff` installed already can be gotten here:
* http://gnuwin32.sourceforge.net/packages/diffutils.htm
* https://www.gnu.org/software/diffutils/


I agree that it may be a good idea to add a small mention of this to the wiki here: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Fixing-Errors-Automatically#printing-a-diff-report

Something like:
> The *nix `diff` command is required for generating reports in `diff` format. Windows users may need to ensure that the `diff` command is available by either installing [DiffUtils](http://gnuwin32.sourceforge.net/packages/diffutils.htm) or - if available - adding the Git `/usr/bin/` subdirectory to the Windows system `PATH`.

@gsherwood As the wiki is not publicly editable, would you mind making this update if you agree ?

**Comment by gsherwood** [comment]
> @gsherwood As the wiki is not publicly editable, would you mind making this update if you agree ?

I've done this now. Thanks for the content.
