### ISSUE TITLE
Ability to ignore conditionally

### ISSUE THREAD

**Issue by weierophinney** [squizlabs/PHP_CodeSniffer#326]
In one repository I maintain, [zfcampus/zf-oauth2](https://github.com/zfcampus/zf-oauth2), we support PHP 5.3+. We provide a trait for those using PHP 5.4+, but it's not used internally.

On Travis-CI, we now have an interesting situation: phpcs runs fine for versions 5.4+, but for 5.3, fails due to phpcs -- which does not know how to process the trait file.

While we can do this via a shell script (and likely will), having the ability to automate it, what would be fantastic is a way to specify a way to ignore files matching a pattern based on PHP version: e.g., `--ignore-5.3=*Trait.php`.

**Comment by gsherwood** [comment]
Just going through old issues and found this one again. PHPCS now recognises traits (since 2.4.0) even when checking with PHP versions that don't support them, so this shouldn't be an issue. This was specifically done to make testing easier.
