### ISSUE TITLE
FR: order imports alphabetical

### ISSUE THREAD

**Issue by masi** [squizlabs/PHP_CodeSniffer#3266]
I would like to have my imports grouped as in PSR12, but at the same time ordered alphabetical within that group.

**Comment by jrfnl** [comment]
There is no sniff for this in PHPCS itself, but the external Slevomat standard has one which you could use for this - `SlevomatCodingStandard.Namespaces.AlphabeticallySortedUses`:
https://github.com/slevomat/coding-standard#slevomatcodingstandardnamespacesalphabeticallysorteduses-

**Comment by gsherwood** [comment]
Closing as there are no plans to add a sniff for this into the core set
