### ISSUE TITLE
SideEffectsSniff does not obey localised ignore annotations

### ISSUE THREAD

**Issue by andrewmatthews** [squizlabs/PHP_CodeSniffer#327]
It would be useful to ignore the SideEffectsSniff on certain files and/or lines.

A good example is a bootstrap file that sets INI values, includes files, defines constants, and declares functions/classes (autoloaders, etc).

**Comment by gsherwood** [comment]
From version 3.2, you'll be able to add the following comment to the top of your file to disable this sniff for a single file: `// phpcs:disable PSR1.Files.SideEffects`

See issue #604 for more details.
