### ISSUE TITLE
Is it possible to have the closing branch on the same line as the opening brace when using constructor promotion?

### ISSUE THREAD

**Issue by jensdenies** [squizlabs/PHP_CodeSniffer#3278]
Hey,

First of all, thanks for the amazing package! I'm trying to write my own code standard and I was wondering if it is possible to have the closing branch on the same line as the opening brace when using constructor promotion. Currently, when using PSR-12, it fixes my code as follows:

```PHP
public function __construct(
    protected string $test
) {
}
```

Ideally, I'd like to have the following:

```PHP
public function __construct(
    protected string $test
) {}
```

Is that something that's natively supported or do I need to write something custom to achieve this?

Thanks!

**Comment by gsherwood** [comment]
There is no native way to enforce this *only* when using constructor property promotion.

You can disable the check that is producing the error, but it's going to disable it for all methods. There also isn't a way to enforce that the closing brace must be on the same line as the opening brace.

**Comment by jensdenies** [comment]
Thanks @gsherwood for clarifying!

**Comment by oojacoboo** [comment]
@gsherwood What do you mean there isn't a way to enforce this?  Forget property promotion, what about an empty function?

**Comment by gsherwood** [comment]
The question was "is their a native way to enforce this", meaning "can PHPCS enforce this with the rules it ships with". The answer was NO, you'd need to write a custom rule to enforce it.

**Comment by siarheipashkevich** [comment]
@gsherwood do you have an example of this rule?

**Comment by jmfederico** [comment]
@gsherwood have a look at https://github.com/squizlabs/PHP_CodeSniffer/issues/3291#issuecomment-1838544056
