### ISSUE TITLE
update package from 3.5.6 to 3.5.8 Installion failed

### ISSUE THREAD

**Issue by pokemonhan** [squizlabs/PHP_CodeSniffer#3290]
**Describe the bug**
![image](https://user-images.githubusercontent.com/27404296/113671828-7508f600-96e9-11eb-8060-fec0fd19b623.png)

**To reproduce**
1. composer version 2;
2. composer update;

**Expected behavior**
Able to install normally.

**Versions (please complete the following information):**
 - OS: [Ubuntu"18.04.5 LTS (Bionic Beaver)"]
 - PHP: [7.4]

**Comment by jrfnl** [comment]
This is not an issue with PHP_CodeSniffer, but with Composer. You may want to try to report it there.
Please note: as it is, there is not enough information to even attempt to reproduce the issue, you will need provide a lot more info on what's in your `composer.json` and `composer.lock` file for anyone to be able to reproduce this.

**Comment by gsherwood** [comment]
Leaving open for a while in case you can post more information that shows this as a PHPCS issue, but PHPCS doesn't do anything tricky when installing via composer, so I can't think of what the problem could be.

**Comment by danny007in** [comment]
run with `sudo`

**Comment by jrfnl** [comment]
Closing for lack of response.
If this is still an issue, please provide the additional information requested and if the issue can then be reproduced, the ticket can be reopened.
