### ISSUE TITLE
 PHPCS is recommending something other than what appears in PSR12

### ISSUE THREAD

**Issue by douglasjordao** [squizlabs/PHP_CodeSniffer#3322]
**Describe the bug**
I'm not a 100% sure if this is really a bug because I'm new to PHP. But I read something about Properties and Constants on PSR12 that says:

> Property names MUST NOT be prefixed with a single underscore to indicate protected or private visibility. That is, an underscore prefix explicitly has no meaning.

I created a php file to study and when I run phpcs on that file it gives me the exact opposite of the one mentioned in PSR12 on Properties and Constants. It says on the output at line 7, 8 and 9 that  it must be prefixed with an underscore.

**Code sample**
```php
<?php

namespace Alura\Pdo\Domain\Model;

class Student
{
    private ?int $id;
    private string $name;
    private \DateTimeInterface $birthDate;

    public function __construct(?int $id, string $name, \DateTimeInterface $birthDate)
    {
        $this->id = $id;
        $this->name = $name;
        $this->birthDate = $birthDate;
    }

    public function id(): ?int
    {
        return $this->id;
    }

    public function name(): string
    {
        return $this->name;
    }

    public function birthDate(): \DateTimeInterface
    {
        return $this->birthDate;
    }

    public function age(): int
    {
        return $this->birthDate
            ->diff(new \DateTimeImmutable())
            ->y;
    }
}

```

**To reproduce**
1. Create a file called `Student.php` with the code sample above...
2. Run `phpcs src/Domain/Model/Student.php`...
3. See error message displayed
```
C:\Projetos\php-pdo\src\Domain\Model\Student.php
----------------------------------------------------------------------------------------
FOUND 10 ERRORS AND 1 WARNING AFFECTING 10 LINES
----------------------------------------------------------------------------------------
  2 | ERROR   | Missing file doc comment
  5 | ERROR   | Missing doc comment for class Student
  7 | ERROR   | Private member variable "id" must be prefixed with an underscore
  8 | ERROR   | Private member variable "name" must be prefixed with an underscore
  9 | ERROR   | Private member variable "birthDate" must be prefixed with an underscore
 11 | ERROR   | Missing doc comment for function __construct()
 11 | WARNING | Line exceeds 85 characters; contains 86 characters
 18 | ERROR   | Missing doc comment for function id()
 23 | ERROR   | Missing doc comment for function name()
 28 | ERROR   | Missing doc comment for function birthDate()
 33 | ERROR   | Missing doc comment for function age()
----------------------------------------------------------------------------------------

Time: 497ms; Memory: 6MB
```

**Expected behavior**
Phpcs should not recommend underscore prefix on property names.

**Versions (please complete the following information):**
 - OS: Windows 10
 - PHP: 7.4
 - PHPCS: 3.6
 - Standard: PSR12

**Additional context**
see: [https://www.php-fig.org/psr/psr-12/](url)

**Comment by jrfnl** [comment]
> Run `phpcs src/Domain/Model/Student.php`...

@douglasjordao Did you tell PHPCS to scan using the PSR-12 standard ? If no standard is provided, the `PEAR` standard is used.

Try:
```bash
phpcs src/Domain/Model/Student.php --standard=PSR12
```

See: https://github.com/squizlabs/PHP_CodeSniffer#getting-started

**Comment by douglasjordao** [comment]
> > Run `phpcs src/Domain/Model/Student.php`...
> 
> @douglasjordao Did you tell PHPCS to scan using the PSR-12 standard ? If no standard is provided, the `PEAR` standard is used.
> 
> Try:
> ```bash
> phpcs src/Domain/Model/Student.php --standard=PSR12
> ```
> 
> See: https://github.com/squizlabs/PHP_CodeSniffer#getting-started

It worked now. Ty so much!
