### ISSUE TITLE
default match intendent incorrectly on PHP8

### ISSUE THREAD

**Issue by bogdandubyk** [squizlabs/PHP_CodeSniffer#3330]
Such a code:

```
    private function createMethod(string $method): AbstractMethod
    {
        return match ($method) {
            Method::CATALOG_METHOD_A => new MethodA(),
            Method::CATALOG_METHOD_B => new MethodB(),
            default => throw InvalidMethodException::createWithContext([
                throw InvalidMethodException::createWithContext(
                    [
                        'Method' => sprintf(
                            'unsupported  method [%s] provided.',
                            $method
                        ),
                    ]
                ),
            ])
        };
    }
```
resulting with an error :

```
 254 | ERROR | [x] Line indented incorrectly; expected 8 spaces, found 12 (Generic.WhiteSpace.ScopeIndent.IncorrectExact)

```
where line 254 is `default` case, and I can fix it changing code to be like:

```
```
    private function createMethod(string $method): AbstractMethod
    {
        return match ($method) {
            Method::CATALOG_METHOD_A => new MethodA(),
            Method::CATALOG_METHOD_B => new MethodB(),
        default => throw InvalidMethodException::createWithContext([
                throw InvalidMethodException::createWithContext(
                    [
                        'Method' => sprintf(
                            'unsupported  method [%s] provided.',
                            $method
                        ),
                    ]
                ),
            ])
        };
    }
```
which is incorrect 

OS: MacOS 10.15
PHP: 8
PHPCS: 3.6.0

**Comment by jrfnl** [comment]
Issue cannot be reproduced on PHPCS 3.6.0 (with PHP 8).

@bogdandubyk That's the third bogus issue you are reporting...

**Comment by gsherwood** [comment]
I can't replicate this issue either. I suspect you are not actually running version 3.6.0 when getting these results as all the recent issues you've reported have been fixed and the tests are still passing.

**Comment by bogdandubyk** [comment]
solved, it was my fault, explained here : https://github.com/squizlabs/PHP_CodeSniffer/issues/3329
