### ISSUE TITLE
EvalUnitTest.inc being detected as malware

### ISSUE THREAD

**Issue by rendler-denis** [squizlabs/PHP_CodeSniffer#3359]
**Describe the bug**
Hello. Starting Thursday, May 13th 2021, it seems Windows Security is detecting the `vendor\squizlabs\php_codesniffer\src\Standards\Squiz\Tests\PHP\EvalUnitTest.inc` as being infected with `Backdoor:PHP/Dirtelti.MTF`

**To reproduce**
1) Install project locally, version 3.6.0
2) Run Windows Security over project

Has anyone else encountered this issue?? I am looking at the code, but I can't seem anything that would trigger Windows Security to think this is an obfuscated code.

**Comment by NulAsh** [comment]
This is a false positive from Windows Defender. After playing with it a lot, I deducted internal algorithm, and in PHP translation, it will look like this:
```
if (preg_match('/<\?php.*eval.*\(/', substr(file_get_contents($filename), 0, 68))) {
    echo 'Backdoor:PHP/Dirtelti.MTF';
}
```
Also, smallest file that will trigger it, here:
`<?phpeval(`

**Comment by NulAsh** [comment]
Sorry, I meant
```
if (preg_match('/<\?php.*eval.*\(/i', substr(file_get_contents($filename), 0, 68))) {
    echo 'Backdoor:PHP/Dirtelti.MTF';
}
```
It's case-insensitive.

**Comment by gsherwood** [comment]
Duplicate of #3042 and #3044

**Comment by spunkram** [comment]
so what is the result? Is this file a virus or not?

The contents of the file are as follows

```
<?php
eval('$var = 4;');
$string = '$var = 4;';
eval($string);
?>
```

**Comment by jrfnl** [comment]
> so what is the result? Is this file a virus or not?

@spunkram Absolutely not. It's a false positive from MS Defender.
