### ISSUE TITLE
PHP 8.0 | Squiz.WhiteSpace.MemberVarSpacing: add support for attributes

### ISSUE THREAD

**Issue by yariknechyporuk** [squizlabs/PHP_CodeSniffer#3360]
Seems like my PR #3334  being stuck, I made suggested fixes, but nobody responded for 4 days. For some reason "re-request review" button on Reviewers is not clickable for me.

It is my first contribution, so if it is not stucked, but just nobody has time to review, sorry and you may close an issue.

**Comment by jrfnl** [comment]
@yariknechyporuk There is only one active person with merge access to the repo and that person hasn't had time to review yet. Please have some patience and close this issue.

**Comment by yariknechyporuk** [comment]
Ok, sorry
