### ISSUE TITLE
Disallowing aligned statements

### ISSUE THREAD

**Issue by emielmolenaar** [squizlabs/PHP_CodeSniffer#3361]
I have this:

```
[
    'some_key'         => 'some_value',
    'another_long_key' => 'some_value',
]
```
And I need to enforce this:
```
[
    'some_key' => 'some_value',
    'another_long_key' => 'some_value',
]
```
So I want to disallow the multi line alignment of arrays, but also for other multi line statements. I have been reading around and trying to get it done with Squiz.Arrays and Generic.Formatting.MultipleStatementAlignment but I think I am still missing something.

I really think this is something trivial so I apologize if this is done by I rule I missed when searching for a solution 😄 Thanks in advance!

**Comment by gsherwood** [comment]
There is no sniff to enforce that statements are not aligned. This isn't something that normally comes up in a coding standard - they typically enforce alignment or just don't mention it - so it's just never been built before.

**Comment by emielmolenaar** [comment]
All right! Thanks for the clear feedback. We might just adopt a sniff that enforces aligned statements. Thanks again!
