### ISSUE TITLE
When I run phpcbf with stdin, the exit code is "1" instead of 0

### ISSUE THREAD

**Issue by yaegassy** [squizlabs/PHP_CodeSniffer#3367]
**Describe the bug**

In the case of stdin, the exit code always seems to be 1.

Is this behavior a bug?

**Code sample**

```php
<?php

function dummy() {
    return "dummy";
}
```

**Custom ruleset**

None

**To reproduce**

```
$ phpcbf --version
PHP_CodeSniffer version 3.6.0 (stable) by Squiz (http://www.squiz.net)
$ cat sample.php
<?php
function dummy() {
    return "dummy";
}
$ cat sample.php | phpcbf
<?php

function dummy()
{
    return "dummy";
}
$ echo $?
1
```

**Comment by jrfnl** [comment]
Duplicate of #1359, #2954, #3057. Also see https://github.com/squizlabs/PHP_CodeSniffer/issues/1818#issuecomment-354420927,  This is on the roadmap for PHPCS 4.0 as per #2898.

**Comment by yaegassy** [comment]
Thanks reply. This seems to be a duplicate issue, so I will close my issue.
