### ISSUE TITLE
How to add blank single line before namespace?

### ISSUE THREAD

**Issue by shivapoudel** [squizlabs/PHP_CodeSniffer#3371]
I want some `phpcs.xml.dist` rules to add a single blank line just above the namespace. Is that possible @gsherwood?

**Comment by sanzeeb3** [comment]
I think there is no built-in rule for such, and you need to [create your own sniff](https://pear.php.net/manual/en/package.php.php-codesniffer.coding-standard-tutorial.php).

There are similar built-in PSR rules.

> When present, there MUST be one blank line after the namespace declaration.
> When present, all use declarations MUST go after the namespace declaration.
> There MUST be one use keyword per declaration.
> There MUST be one blank line after the use block.

**Comment by shivapoudel** [comment]
@sanzeeb3 The alternative was to write a custom sniff OR switch to [PHP-CS-Fixer with this feature](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/3.0/doc/rules/namespace_notation/single_blank_line_before_namespace.rst) but both seems not an easy solution for me at least this time so I choose to go with the [Slevomat Coding Standard](https://github.com/slevomat/coding-standard) which provides all these sniffs including others until PHPCBF has this sniff. Because PSR12 already has this one but with WordPress Coding Standard seems incompatible with PSR12 as it has its own sniff rules. The below rules helped me to achieve the namespaces spacing goal currently.

```xml
<!-- SlevomatCodingStandard -->
<rule ref="SlevomatCodingStandard.Classes.MethodSpacing"/>
<rule ref="SlevomatCodingStandard.Classes.PropertySpacing"/>
<rule ref="SlevomatCodingStandard.Namespaces.UnusedUses"/>
<rule ref="SlevomatCodingStandard.Namespaces.NamespaceSpacing" />
<rule ref="SlevomatCodingStandard.Namespaces.UseSpacing" />
```

**Comment by gsherwood** [comment]
There is no sniff to just enforce the blank line. The closest is `PSR12.Files.FileHeader`, but it enforces the entire file header formatting part of the PSR12 standard. If you happen to like that, you could use it instead.

It's outlined here: https://www.php-fig.org/psr/psr-12/
Under the heading: **3. Declare Statements, Namespace, and Import Statements**

**Comment by shivapoudel** [comment]
@gsherwood I don't prefer using file docblock as I prefer class docblock so this rule perfectly aligned my files:

```xml
<!-- PSR12 -->
<rule ref="PSR12.Files.FileHeader.SpacingAfterBlock">
    <include-pattern>src/</include-pattern>
</rule>
```

Code before formatting:

```php
<?php
namespace App;
use App\Utilities\SingeletonTrait;
/**
 * Class documentation.
 *
 * @since 1.0.0
 */
class Test {
	use SingeletonTrait;
	/**
	 * Constructor.
	 *
	 * @since 1.0.0
	 */
	public function __construct(){}
}
```

Code after PHPCF formatting:

```php
<?php

namespace App;

use App\Utilities\SingeletonTrait;

/**
 * Class documentation.
 *
 * @since 1.0.0
 */
class Test {
	use SingeletonTrait;

	/**
	 * Constructor.
	 *
	 * @since 1.0.0
	 */
	public function __construct(){}
}
```

Thank you so much :)

**Comment by gsherwood** [comment]
Nice one :) Thanks for posting your solution.

**Comment by shivapoudel** [comment]
@gsherwood One more question hoping if there is any solution that persists. Can blank between multiple `use` declarations be removed?
