### ISSUE TITLE
Generic.ControlStructures.InlineControlStructure.NotAllowed autofix missing whitespace

### ISSUE THREAD

**Issue by DannyS712** [squizlabs/PHP_CodeSniffer#3372]
**Describe the bug**
`Generic.ControlStructures.InlineControlStructure.NotAllowed` autofix should add whitespace after the opening {

**Code sample**
```php
<?php

function demo ( $text ) {
	if ( $text === '' ) $text = 'empty';
	return $text;
}
```

**To reproduce**
1. Create a file called `demo.php` with the code sample above...
2. Run `phpcs -p -s '--standard=Generic' '--sniffs=Generic.ControlStructures.InlineControlStructure' 'demo.php'`
3. See error message displayed (this is correct)
```
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 4 | ERROR | [x] Inline control structures are not allowed
   |       |     (Generic.ControlStructures.InlineControlStructure.NotAllowed)
----------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------
```
4. Run `phpcbf '--standard=Generic' '--sniffs=Generic.ControlStructures.InlineControlStructure' 'demo.php'` with the following output or similar:
```
PHPCBF RESULT SUMMARY
---------------------------------------
FILE      FIXED  REMAINING
---------------------------------------
demo.php  1      0
---------------------------------------
A TOTAL OF 1 ERROR WERE FIXED IN 1 FILE
---------------------------------------
```
5. Check the updated contents of demo.php (this is the problem)
```php
<?php

function demo ( $text ) {
	if ( $text === '' ) { $text = 'empty';
	}
        return $text;
}
```

**Expected behavior**
The outfixed result was
```php
<?php

function demo ( $text ) {
	if ( $text === '' ) {
	$text = 'empty';
	}
	return $text;
}
```
(or with an extra tab before the `$text = 'empty';`, but it should have at least the one to align it with the opening and closing, instead of remaining on the same line

**Versions (please complete the following information):**
 - PHPCS: 3.6.0
 - Standard: Generic

**Additional context**
Originally reported at https://phabricator.wikimedia.org/T246630

**Comment by jrfnl** [comment]
The inline control structures sniff is intended to add the braces, but is not formatting aware. There are other sniffs which take care of formatting and IMO, this should be solved by adding one or more of those sniffs to whichever ruleset is being used to scan the code. (check through the `ControlStructures` folders in the various standards to find possible sniff to choose from)

**Comment by gsherwood** [comment]
As @jrfnl said, this sniff doesn't try and do anything except add braces where they need to go. This allows it to fit into pretty much any coding standard as other sniffs can take care of formatting rules. Most sniffs do this because some rules conflict if they dont, and determining correct indents is quite hard.

You probably want to include `Squiz.ControlStructures.ControlSignature` to enforce that the first line of the IF is on a new line, and `Generic.WhiteSpace.ScopeIndent` to ensure it is indented correctly. That should format the code the way you want.

Does that help?

**Comment by DannyS712** [comment]
Thanks for clarifying that it wasn't meant to be handling formatting
