### ISSUE TITLE
phpcs does not work when run from WSL drives

### ISSUE THREAD

**Issue by gwharton** [squizlabs/PHP_CodeSniffer#3388]
**Describe the bug**
When the project (including phpcs vendor folder) is run from a windows network drive (either mapped to drive, or by Path) phpcs cannot be run as it believes the config is not readable.

**Code sample**
N/A

**Custom ruleset**
N/A

**To reproduce**
1. Create project on mapped network drive
2. Run phpcs --version
3. See error message displayed
```
ERROR: Config file \\WSL$\UBUNTU\home\ubuntu\www\vendor\squizlabs\php_codesniffer\CodeSniffer.conf is not readable
```

```
ERROR: Config file U:\home\ubuntu\www\vendor\squizlabs\php_codesniffer\CodeSniffer.conf is not readable
```

**Expected behavior**
It should work

**Versions (please complete the following information):**
 - OS: Windows 10 with WSL
 - PHP: 7.4.21
 - PHPCS: 3.6.0
 - Standard: N/A

**Additional context**
It is the same issue with php's is_readable function that was worked round with this fix. https://github.com/squizlabs/PHP_CodeSniffer/commit/d56e167a5dea3550996f197b5d92b1418b1e3fab

is_readable is called here. https://github.com/squizlabs/PHP_CodeSniffer/blob/b6d6556733c00b406002d79d947ff72b17000f16/src/Config.php#L1659-L1662

is_readable should be changed to `Util\Common::isReadable` as per previous fix

**Comment by gwharton** [comment]
FIX
```
--- ./src/Config.orig.php	2021-07-15 10:47:29.220000000 +0100
+++ ./src/Config.php	2021-07-15 10:45:27.980000000 +0100
@@ -1656,7 +1656,7 @@
             return [];
         }

-        if (is_readable($configFile) === false) {
+        if (Util\Common::isReadable($configFile) === false) {
             $error = 'ERROR: Config file '.$configFile.' is not readable'.PHP_EOL.PHP_EOL;
             throw new DeepExitException($error, 3);
         }
```

**Comment by jrfnl** [comment]
@gwharton I've created PR #3428 to address this. Testing appreciated.

**Comment by gsherwood** [comment]
Thanks for this big report and for posting one of the fixes.
