### ISSUE TITLE
Line length exeeded: Empty function parameter list with returntypes

### ISSUE THREAD

**Issue by freshp** [squizlabs/PHP_CodeSniffer#3407]
**Describe the bug**
I dont know how to handle methods without any parameters and long names with return types.

My max line length is 120, so I want to break within the function parameter parenthesis. 
(FunctionDeclarationArgumentSpacingSniff && FunctionDeclarationSniff)

Another way could be to set a linebreak before the colon of the return type and before each pipe, but there are whitespaces expected too. 
(ReturnTypeHintSpacingSniff)

Maybe PSR-12 has another way for this case?

**Code sample**
FunctionDeclarationArgumentSpacingSniff  && FunctionDeclarationSniff:
```php
<?php

declare(strict_types=1);

namespace Test;

final class Test
{
    public static function foooBarBazFooBarBazFooBarBazFooBarBazFooBarBazFooBarBazFooBarBazFooBarBaz(
    ): null|\DateTimeInterface
    {
        return null;
    }
}
```

ReturnTypeHintSpacingSniff:
```php
<?php

declare(strict_types=1);

namespace Test;

final class Test
{
    public static function foooBarBazFooBarBazFooBarBazFooBarBazFooBarBazFooBarBazFooBarBazFooBarBaz()
        : null
        | \DateTimeInterface
    {
        return null;
    }
}
```

**To reproduce**
1. Create a file called `test.php` with the code sample above...
2. Run `./vendor/bin/phpcs --standard=PSR12 test.php`
3. See error message displayed
    FunctionDeclarationArgumentSpacingSniff  && FunctionDeclarationSniff:
    ```
    Expected 0 spaces between parenthesis of function declaration; newline found
    The closing parenthesis and the opening brace of a multi-line function declaration must be on the same line
    ```
    ReturnTypeDeclarationSniff:
    ```
    There must not be a space before the colon in a return type declaration
    ```

**Versions (please complete the following information):**
 - OS: MacOS 11.5.1
 - PHP: 8.0
 - PHPCS: 3.6.0
 - Standard: PSR12

**Comment by gsherwood** [comment]
One options it to just ignore the line length error, or mute it with a [phpcs:ignore](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#ignoring-parts-of-a-file) annotation.

But as to what PSR-12 says to do, I can't comment on. You'd need to ask the authors of the coding standard in the PHP-FIG to see if they have an opinion.

Unless I'm missing something, I don't think this is actually a bug report (seems more like a question) but please let me know if you think PHPCS is not working corrctly.

**Comment by kenguest** [comment]
Not to deflect, but maybe ask why the method name is so long? Is it overly verbose or an indicator that the method needs to be refactored?

**Comment by freshp** [comment]
I think this really can be a codesmell, but with union return types it is easier to exceed the line length. Some projects or packages have a 80 char line length and you can quickly touch this limit. 

I do not run into this problem every day, so the severity is maybe not as high as other problems, but I tought there is already a solution for this case and thatswhy I thought it would be a bug. Overall I dont really know, if it is a bug, but at the moment I have to ignore these lines of code and every kind of ignore feels wrong 😃

**Comment by freshp** [comment]
It seems like this case should not happen and thatswhy there is nothing wrong with PHPCS.

I  got the following answer on twitter. My conclusion:
In PSR-12 they relaxed the 120 length limit to be soft instead of hard.
This was also done because today, with 16:9 as the minimum, horizontal space on screen is less problematic.
Long method names are fine. We should use 120 character line length as soft limit, and we can just disable the rule for class files where it doesn't make sense (esp. test classes).
