### ISSUE TITLE
[PROPOSAL] Disallow empty if and else blocks

### ISSUE THREAD

**Issue by jlherren** [squizlabs/PHP_CodeSniffer#3408]
I'd like to propose a sniff that detects empty `if` and `else` blocks, since they never make any sense. Adding a comment inside the empty block would suppress the error, similar to `DisallowEmptyFunctionSniff`.

Empty `elseif` blocks can sometimes make sense if followed by other `elseif`s or an `else`.

Perhaps the sniff could even be fixable by extracting side-effects of the condition, however, it would be more useful if we can detect whether there are any side-effects at all, which I'm not sure is possible in phpcs.

**Comment by jlherren** [comment]
Oops, I meant to post this to `slevomat/coding-standard`, disregard that, sorry :(

**Comment by jrfnl** [comment]
@jlherren Just so you know, the `Generic.CodeAnalysis.EmptyStatement` would largely fit your needs. Could possibly do with some fine-tuning, in which case, I suspect a PR would be welcome.

```php
if ($true) {
} elseif($bar) {
} else {
	// Do something.
}
```

```
--------------------------------------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 3 LINES
--------------------------------------------------------------------------------------------------
 3 | ERROR | Empty IF statement detected (Generic.CodeAnalysis.EmptyStatement.DetectedIf)
 4 | ERROR | Empty ELSEIF statement detected
   |       | (Generic.CodeAnalysis.EmptyStatement.DetectedElseif)
 5 | ERROR | Empty ELSE statement detected (Generic.CodeAnalysis.EmptyStatement.DetectedElse)
--------------------------------------------------------------------------------------------------
```

**Comment by jlherren** [comment]
Thanks for the hint. I always find it somewhat hard to discover what sniffs already exists. I've created #3409 to improve it.
