### ISSUE TITLE
Squiz.WhiteSpace.ScopeClosingBrace fixer removes HTML content when fixing closing brace alignment

### ISSUE THREAD

**Issue by GlennBags** [squizlabs/PHP_CodeSniffer#3422]
**Describe the bug**
Div end tag removed when reformatting using phpcbf to reformat code to PSR-12 standard

**Code sample**
```php
// before reformatter
    </div> <?php endif; ?>

// after reformatter
    <?php endif; ?>
```

**Custom ruleset**
```xml
<?xml version="1.0"?>
<ruleset name="My Custom Standard">
  <description>If you are using a custom ruleset, please enter it here.</description>

  <description>Besides the below, have some exclude patterns that shouldn't affect the outcode.</description>

    <rule ref="PSR12"/>
    <arg name="extensions" value="php" />

</ruleset>
```

**To reproduce**
1. Create a file called `test.php` with the code sample above...
2. Run `php phpcbf.phar --standard=ruleset.xml test.php -v `
3. See code reformatted with the end div removed

**Expected behavior**
Should not remove HTML

**Versions (please complete the following information):**
 - OS:  MacOS 11.5.2
 - PHP: 8.0.2
 - $ php phpcbf.phar --version
PHP_CodeSniffer version 3.6.0 (stable) by Squiz (http://www.squiz.net)
 - Standard:  PSR12

**Comment by jrfnl** [comment]
@GlennBags The issue cannot be reproduced with the code sample you provided.

**Comment by GlennBags** [comment]
OK, apologies, the code sample was incomplete. Please try:
```
<?php if ($someConditional) : ?>
<div class="container">

</div> <?php endif; ?>
```
Using the above file as the test.php, I am able to replicate using the following ruleset:
```
<?xml version="1.0"?>
<ruleset name="Selective Standard">

    <rule ref="PSR12"/>

    <arg name="extensions" value="php" />

</ruleset>
```

**Comment by jrfnl** [comment]
@GlennBags Thanks, that's better. Reproduced the issue. Thanks for reporting it.

The problem is in the `Squiz.WhiteSpace.ScopeClosingBrace` sniff which doesn't handle non-whitespace inline HTML tokens on the same line as the scope closer correctly.

This will need looking into.

**Comment by jrfnl** [comment]
@GlennBags I've prepared a fix for this issue. See PR #3447. Testing appreciated.

**Comment by jrfnl** [comment]
@GlennBags Just thinking - if it helps, I could generate the PHAR file for the PR for you. Let me know if you want that.

**Comment by GlennBags** [comment]
@jrfnl Yes, apparently I can't get it from composer command line, or am I doing something wrong?
```bash-4.2# composer  squizlabs/php_codesniffer:"dev-feature/3422-squiz-scopeclosingbrace-bug-fix" --require-dev


  [Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "squizlabs/php_codesniffer" namespace.

**Comment by GlennBags** [comment]
Well, duh, I'm testing using the phar, so, yeah, a phar file would help. 
I haven't finished my first cup of coffee... that's my excuse and I'm sticking to it! heh

**Comment by jrfnl** [comment]
@GlennBags 😂  you were also missing the `require` keyword in Composer. The things lack of coffee makes us do ;-)

You can download zips containing the `phpcs` and `phpcbf` PHAR files for this PR here: https://github.com/jrfnl/PHP_CodeSniffer/actions/runs/1311950956
