### ISSUE TITLE
`phpcs` should print out the name of the rule being violated

### ISSUE THREAD

**Issue by posita** [squizlabs/PHP_CodeSniffer#3443]
Copied from [this comment](https://github.com/squizlabs/PHP_CodeSniffer/issues/1482#issuecomment-756120544) from @jigarius, which may have gotten lost in that thread:

> It'd be great if the following info were available for each error that `phpcs` reports:
>
> * Error message and line number (that's there).
> * Which rule caused the error to exist, e.g., `PSR1.Classes.ClassDeclaration.MissingNamespace`, maybe with a link to a page on which more info can be found.
>   * In this regard Rubocop (Ruby equivalent of PHPCS) is very transparent.
> * For each possible rule, there should be a way of seeing the possible configurations.
>
> I've been using PHPCS for years with Drupal, but that was very easy because all I had to do is use an existing `--standard=Drupal`. However, trying to use it for a quick, mini-project, I realized that it could use some easily-accessible documentation for the XML file.

**Comment by jrfnl** [comment]
Copying my answer verbatim from the same thread:

> > Which rule caused the error to exist
> 
> If you run `phpcs` with the `-s` option, it will show you exactly that.
> 
> > For each possible rule, there should be a way of seeing the possible configurations.
> 
> For the PHPCS rules, have a look here: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Customisable-Sniff-Properties

You may also want to have a look at the [annotated ruleset example in the wiki](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-Ruleset);


Not sure what you are trying to achieve, but as it is, this issue is just noise.

**Comment by posita** [comment]
I totally missed that. Apologies!
