### ISSUE TITLE
How to install PSR4

### ISSUE THREAD

**Issue by GeoffreyOlivier** [squizlabs/PHP_CodeSniffer#3475]
Hello, I would like install PSR4, I can't find how to install.

```
ERROR: the "PSR4" coding standard is not installed. The installed coding standards are MySource, PEAR, PSR1, PSR12, PSR2, Squiz, Zend, CodeatCodingStandard, PHPCompatibility, PHPCompat
ibilityParagonieRandomCompat, PHPCompatibilityParagonieSodiumCompat, PHPCompatibilityWP, SlevomatCodingStandard, WordPress, WordPress-Core, WordPress-Docs and WordPress-Extra
To skip commit checks, add -n or --no-verify flag to commit command
```

C:\wamp64\www\wordpress\wp-content\plugins\sync-woocommerce>phpcs -i
The installed coding standards are MySource, PEAR, PSR1, PSR12, PSR2, Squiz and Zend

Thanks for your help

**Comment by jrfnl** [comment]
As far as I know there is no PSR-4 standard available, not in PHPCS itself, not in userland.

**Comment by GeoffreyOlivier** [comment]
Oh ok, thanks.

**Comment by lgedeon** [comment]
What about https://github.com/suin/phpcs-psr4-sniff? Is this something that could be included as optional?
