### ISSUE TITLE
The "define" function triggers an error warning.

### ISSUE THREAD

**Issue by nateriver74** [squizlabs/PHP_CodeSniffer#3568]
Hello,
I am trying to define a constant using the "define()" function.

```php
<?php

define("CONSTANT", "Hello World!");
echo CONSTANT; // Print: "Hello World!"

?>
```

I don't know if I'm doing something wrong, but only when I use the define() function, I get an error message:

```
A file should declare new symbols (classes, functions, constants, etc.) and cause no 
other side effects, or it should execute logic with side effects, but should not do both. 
The first symbol is defined on line 3 and the first side effect is on line 4.
```

How can the problem be corrected?

**Versions:**
 - OS: [Windows 10]
 - PHP: [7.4.26]
 - PHPCS: [3.6.2]
 - Standard: [PSR2]

Thanks!

**Comment by gsherwood** [comment]
It's not the use of define; it's the fact that you are defining something and also outputting content.

This is part of the PSR1 standard, and thus PSR2 and PSR12 as well. The explanation is here: https://www.php-fig.org/psr/psr-1/#23-side-effects

Does that make the error message clearer?
