### ISSUE TITLE
Only shows the issue but do not edit the file automatically.

### ISSUE THREAD

**Issue by IvankvKharkiv** [squizlabs/PHP_CodeSniffer#3580]
Installation type - composer.
Environment: PHP8, symfony 6.
When running from command line:

```bash
$./vendor/bin/phpcbf /var/www/developstoday_test.com/src/ 
```
Returns error description but does not fix it:
```
PHPCBF RESULT SUMMARY
----------------------------------------------------------------------
FILE                                                  FIXED  REMAINING
----------------------------------------------------------------------
src/Entity/NewsPosts.php                              1      0
----------------------------------------------------------------------
A TOTAL OF 1 ERROR WERE FIXED IN 1 FILE
----------------------------------------------------------------------

Time: 153ms; Memory: 8MB
```
But in reality file stays the same.
The extra lines does not fixed in the file.
Frankly speaking it just does not work.
The most strange thing is that when i run command second time it does not show the files with issue even though the issue is still present.
So it does not work at all.
How to force it to fix autromatically and to work properly to show the mistakes if they are still in the file?

**Comment by jrfnl** [comment]
Please use the [Bug Report template](https://github.com/squizlabs/PHP_CodeSniffer/issues/new?assignees=&labels=&template=bug_report.md&title=) for opening bug report issues. The above is missing nearly all information needed to determine what is going on.

Either open a new issue using the [Bug Report template](https://github.com/squizlabs/PHP_CodeSniffer/issues/new?assignees=&labels=&template=bug_report.md&title=) or add the following information to your issue to allow someone to understand what you are reporting:
* PHPCS version used
* Your custom ruleset
* A code sample with which the described behaviour can be reproduced - preferably a code sample which shows _only_ the above.
    If you can't distill the file down to a small code sample, a link to the file in a public repo is also okay.
* The error which is reported for the file (which you are trying to fix with the fixer).

Without that information, there is nothing anybody can do.

**Comment by jrfnl** [comment]
Closing for lack of response.
If this is still an issue, please provide the additional information requested and if the issue can then be reproduced, the ticket can be reopened.
