### ISSUE TITLE
PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported

### ISSUE THREAD

**Issue by digitlimit** [squizlabs/PHP_CodeSniffer#3590]
**Describe the bug**
I am getting this error after switching to PHP8.1, any help will be appreciated.

phpcs: Unable to locate phpcs. Command failed: "/home/me/.config/composer/vendor/bin/phpcs" --version PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /home/,e/.config/composer/vendor/squizlabs/php_codesniffer/CodeSniffer/CLI.php on line 418 

**Versions (please complete the following information):**
 - OS: Ubuntu 21 running in WSL2 Windows 11
 - PHP: 8.1
 - PHPCS: 
 - Standard:cPSR2, PSR12, Squiz

**Comment by jrfnl** [comment]
@digitlimit Please update your PHPCS installation. Looks like you are still using PHPCS 2.x, which is no longer maintained. PHPCS 3.x has been out for years now and is compatible with this PHP 8.0 change since version 3.5.0.

**Comment by dopa515** [comment]
PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /home/kali/FakeCall/fakeCall.php on line 82

**Comment by gsherwood** [comment]
@dopa515 That's not a PHPCS file generating that error. I don't know what FakeCall is, but PHPCS doesn't use it either.

**Comment by kens-MKL** [comment]
Fatal error: Array and string offset access syntax with curly braces is no longer supported in C:\wamp64\apps\phpmyadmin4.5.2\libraries\url_generating.lib.php on line 239

**Comment by jrfnl** [comment]
@kens-MKL Wrong repo - try https://github.com/phpmyadmin/phpmyadmin . Better yet: try updating your PHPMyAdmin install to a more recent version before anything else. You can download new versions for Wampserver here: https://wampserver.aviatechno.net/

**Comment by Alprihi** [comment]
PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /home/kali/fakecall/call.php on line 82
 help me my broblem

**Comment by S0B3K-001** [comment]
same problem did u fix it?

**Comment by jrfnl** [comment]
@Alprihi @S0B3K-001 You might have a similar problem, but it is not a problem with PHP_CodeSniffer, so please take your questions to a generic support forum, like StackOverflow or something.
