### ISSUE TITLE
Disable rule via CLI does not work for full rule

### ISSUE THREAD

**Issue by kkmuffme** [squizlabs/PHP_CodeSniffer#3597]
phpcbf is quite slow, I'm trying to get it to run faster by disabling rules that are irrelevant for phpcbf (and only relevant for phpcs).

I pass `--exclude=Hello.World.Foo` => the rule is disabled.

However when I try to disable all "Hello" rules via `--exclude=Hello` I get an error:

>ERROR: The specified sniff code "Hello" is invalid

But my phpcs.xml has

```
<rule ref="Hello">
	<exclude name="bar"/>
</rule>
```

so this should be working.

I found the comment https://github.com/squizlabs/PHP_CodeSniffer/issues/1755#issuecomment-482394520 that says I always must specify the 3 part error code.
But why can I not disable the whole rule at once?

**Comment by jrfnl** [comment]
Without expressing an opinion on the request above - you could use the `phpcs-only` attribute within your ruleset to explicitely exclude sniffs from running when using `phpcbf`. This could be considered a work-around for now.
Ref: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-Ruleset#selectively-applying-rules

**Comment by kkmuffme** [comment]
Thanks a lot!

Even though the docs don't mention it, this can also be used in the rule like `<rule phpcs-only="true" ref="Hello"/>`
