### ISSUE TITLE
hangs forever while scanning CSS file

### ISSUE THREAD

**Issue by divinity76** [squizlabs/PHP_CodeSniffer#3598]
**Describe the bug**
phpcs hangs forever while scanning the attached css file: [fontAwesomeIE7.css.zip](https://github.com/squizlabs/PHP_CodeSniffer/files/8782059/fontAwesomeIE7.css.zip)

**Code sample**
see the attached css file (too large to *comfortably* inline.)

**Custom ruleset**
no custom ruleset..

**To reproduce**
1. unzip the attached css file
2. Run `./vendor/bin/phpcs -p fontAwesomeIE7.css -v`
3. check back 10 hours later, see that it's still working on that file, clearly frozen.. using 100% cpu of 1 core.

```
root@x2ratma:/home/hans/projects/phpstan# time ./vendor/bin/phpcs --runtime-set testVersion 8.1 -p fontAwesomeIE7.css -v
Registering sniffs in the PEAR standard... DONE (28 sniffs registered)
Creating file list... DONE (1 files in queue)
Changing into directory /home/hans/projects/phpstan
Processing fontAwesomeIE7.css
14:31

^C
real    499m15.578s
user    447m50.731s
sys     1m13.497s

root@x2ratma:/home/hans/projects/phpstan# ls^C
root@x2ratma:/home/hans/projects/phpstan# time ./vendor/bin/phpcs -p fontAwesomeIE7.css -v
Registering sniffs in the PEAR standard... DONE (28 sniffs registered)
Creating file list... DONE (1 files in queue)
Changing into directory /home/hans/projects/phpstan
Processing fontAwesomeIE7.css
```

**Expected behavior**
not freeze

**Versions (please complete the following information):**
 - OS: Ubuntu 20.04 x84-64
 - PHP: 7.4.3
 - PHPCS: 3.7.0-dev 
 - Standard: N/A

**Additional context**
was initially discovered with PHPCompatibility and reported over at https://github.com/PHPCompatibility/PHPCompatibility/issues/1337

**Comment by jrfnl** [comment]
Additional info: the scope map recursion goes into an infinite loop on that file.

**Comment by gsherwood** [comment]
Support for non-PHP files is being removed from PHP_CodeSniffer and I'm not fixing any bugs for these file types. Please switch to another tool to check CSS standards.
