### ISSUE TITLE
How does this package and the rulesets compare to HTMLcodeSniffer?

### ISSUE THREAD

**Issue by j-mendez** [squizlabs/PHP_CodeSniffer#3599]
Hello, I am trying to figure out the integrity of the core for lib to determine what issues are regardless of the language used. I was thinking the JS and php version of the libs would use the same core to gather the insight making it so that both repos or language of choice. This package seems to receive updates often opposed to https://github.com/A11yWatch/HTML_CodeSniffer. Is https://github.com/A11yWatch/HTML_CodeSniffer deprecated and the PHP lib is more of the central focus? If not what are the chances of getting PR's looked at in the HTML_CodeSniffer repo since the activity is looking non existent at the moment. This may not be the appropriate place to put the issue, but took to twitter and sent some emails trying to figure out the activity of the repo and have not received any replies yet.

**Comment by gsherwood** [comment]
This is an entirely different project with a different purpose and maintainers.

HTML_CodeSniffer is not deprecated or abandoned, but it's not actively being improved. Critical fixes will be done, or updates for new standard changes made, but likely not general improvements.
