### ISSUE TITLE
windows phpcbf file_put_contents(C:\/phpcbf-fixed.diff): failed to open stream: 

### ISSUE THREAD

**Issue by gmgj** [squizlabs/PHP_CodeSniffer#362]
I see the following errors when I capture output 
Warning: file_put_contents(C:\/phpcbf-fixed.diff): failed to open stream: Permission denied in ...php\PEAR\PHP\CodeSniffer\Reporting.php on line 189

Warning: file_put_contents(C:\/phpcbf-fixed.diff): failed to open stream: Permission denied in ...php\PEAR\PHP\CodeSniffer\Reporting.php on line 268

Windows Home Premium
Bitnami WAMP Stack
PHP 5.4.11 (cli) (built: Jan 16 2013 20:26:43)
I use this and it fails with ERROR

phpcbf.bat --standard=C:\GJCodeSniffer\Standards\RSI2\ C:\djdklj\djfsljf\ourAdmin\phpbasics.php

Changing into directory C:\djdklj\djfsljf\ourAdmin
Processing phpbasics.php [PHP => 6953 tokens in 1412 lines]... DONE in 694ms (406 fixable violations)
=> Fixing file: 5/406 violations remaining [made 50 passes]... ERROR in 33.49 secs
No fixable errors were found
Time: 34.26 secs; Memory: 26.5Mb

**Comment by jonnyijapan** [comment]
> Warning: file_put_contents(C:/phpcbf-fixed.diff): failed to open stream: Permission denied in ...php\PEAR\PHP\CodeSniffer\Reporting.php on line 189
> 
> Warning: file_put_contents(C:/phpcbf-fixed.diff): failed to open stream: Permission denied in ...php\PEAR\PHP\CodeSniffer\Reporting.php on line 268

Sorry to bump this, but how would I fix this? I need to use code sniffer 2.9.x

**Comment by gsherwood** [comment]
> Sorry to bump this, but how would I fix this? I need to use code sniffer 2.9.x

That version is trying to write a file into whatever directory you are running PHPCBF from (presumably `C:/` in the example output) . Maybe try running it from a directory in which you have write access.

**Comment by jonnyijapan** [comment]
Ok, it's VS Code running it, specifically the "phpcbf" extension. Not sure from what directory that is run, or using what user...

**Comment by gsherwood** [comment]
> Ok, it's VS Code running it, specifically the "phpcbf" extension. Not sure from what directory that is run, or using what user...

I don't know either, sorry. There isn't a way to change where that file gets written to in PHPCBF itself. So unless VS Code has a setting somewhere, you'd might have to run PHPCBF manually,.

**Comment by jonnyijapan** [comment]
Yes it does work if run manually 👍🏻
And I think I'm actually fine with only phpcs for now, it works well in vscode even with 2.9.2.
