### ISSUE TITLE
Catch and show informative error message for out of memory errors

### ISSUE THREAD

**Issue by jrfnl** [squizlabs/PHP_CodeSniffer#3621]
Depending on the size of a code base, the amount of sniffs run and the `memory_limit` set for PHP, PHPCS can run out of memory.

Depending on the point at which it runs out of memory, it may show the PHP native "out of memory" error or it may exit without any further information (seen that a number of times as well).

Catching out of memory errors and displaying a user-friendly error message isn't straight-forward, as one can't allocate anymore memory in PHP by that time.

However, my friend @schlessera has worked out a way to do it for another CLI tool and [shared the code with me](https://github.com/wp-cli/package-command/blob/afac00c12612ba13ed42bb0da2c76002b9a5d9e8/src/Package_Command.php#L1346-L1392).

@gsherwood Would you be interested in me implementing a user friendly error message for out of memory errors for PHPCS ?

**Comment by gsherwood** [comment]
I'm not against adding this kind of protection for OOM errors. I haven't seen PHPCS run out of memory without an error, but I'm sure it happens.
