### ISSUE TITLE
`Squiz.NamingConventions.ValidVariableName` Does Not Provide Fixes via `phpcbf`

### ISSUE THREAD

**Issue by Justintime50** [squizlabs/PHP_CodeSniffer#3633]
**Describe the bug**

I can run `phpcbf` for all my current rules and have them automatically fixed; however, there is no fixer for `Squiz.NamingConventions.ValidVariableName` rules to take my `$snake_case` variables and turn them into `$camelCase`. I would expect the tool to be able to do so as converting hundreds of those errors manually would be taxing and error-prone. The particular sniff I'm using is `Squiz.NamingConventions.ValidVariableName.NotCamelCaps` which should be pretty simple to determine which variables need correcting.

**Code sample**
```php
echo $snake_case_variable;
```

**Custom ruleset**
```xml
<?xml version="1.0"?>
<ruleset name="My Custom Standard">
  <description>If you are using a custom ruleset, please enter it here.</description>
</ruleset>
```

**To reproduce**
1. Create a file called `test.php` with the code sample above...
2. Run `phpcbf test.php ...`
3. See error message displayed
```
No fixable errors were found
```

**Expected behavior**
PHP_CodeSniffer would automatically correct my snake case variables to be camel case.

**Versions (please complete the following information):**
 - OS: MacOS 10.15
 - PHP: 7.4
 - PHPCS: 3.6
 - Standard: PSR12

**Comment by gsherwood** [comment]
None of the included checks in PHPCBF change code in a way that could break the code itself. All PHPCBF does is change formatting in ways that ensure the code itself is still the same.

Custom sniffs and standards can change code, but the included sniffs don't.

Closing this as it's not something I'd include in the core.
