### ISSUE TITLE
PHP Fatal error: Uncaught TypeError: vsprintf(): Argument #2 ($values) must be of type array, string given in

### ISSUE THREAD

**Issue by nikitasinelnikov** [squizlabs/PHP_CodeSniffer#3641]
**Describe the bug**
Getting PHP errors in the GitHub action build. But it works with my other repo properly. I'm trying to make the GitHub action and running code quality checking after the push of my code. Unfortunately, get the errors from
"squizlabs/php_codesniffer".

**Custom ruleset**
```xml
<?xml version="1.0"?>
<ruleset name="Ultimate Member CS">

	<description>Best practices Ultimate Member Coding Standards</description>
	<config name="testVersion" value="5.6-"/>

	<arg value="ps"/>
	<arg name="colors"/>
	<arg name="parallel" value="100"/>
	<arg name="extensions" value="php"/>
	<arg name="cache" value=".phpcs.cache"/>

	<exclude-pattern>\.github/*</exclude-pattern>
	<exclude-pattern>vendor/*</exclude-pattern>
	<exclude-pattern>node_modules/*</exclude-pattern>
	<exclude-pattern>documentor/*</exclude-pattern>
	<exclude-pattern>\.idea/*</exclude-pattern>

	<rule ref="WordPress-Extra"/>

	<rule ref="PHPCompatibilityWP">
		<include-pattern>*\.php$</include-pattern>
	</rule>

</ruleset>
```

**To reproduce**
1. Push the code through Git Bash on my Windows laptop
2. GitHub action is running on github.com
3. Getting the PHP errors related to squizlabs/PHP_CodeSniffer
```
GitHub action log is here
```
[raw_log.txt](https://github.com/squizlabs/PHP_CodeSniffer/files/9255505/raw_log.txt)

**Expected behavior**
I get a proper build with another one repo with a similar ruleset and action settings. It looks like there aren't issues with this one.

Let me know if you need other details

**Comment by jrfnl** [comment]
@nikitasinelnikov This is not an issue in PHP_CodeSniffer, but this is a known issue with WordPressCS and has already been fixed. Unfortunately, the release has been delayed for reasons.

If you set up the CS run in GH Actions to run on PHP 7.4, you should be fine. Once WordPressCS 3.0.0 has been released, you should be fine to run it on higher PHP versions.

In other words: make sure to include the below between your GH Actions `checkout` step and the actual PHPCS run:
```yaml
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
```

**Comment by afilina** [comment]
In what version has this been released and how do I check/fix it? I can't find `WordPressCS` in my composer.lock file.

I have the same fatal error as of today in PHP 8.2 while using PHPCS 3.9.1 (fresh installation of phpcompat).
