### ISSUE TITLE
Additonal report class for GitHub (Actions) to support direct annotations

### ISSUE THREAD

**Issue by indigoxela** [squizlabs/PHP_CodeSniffer#3648]
This is no bug report, but a feature request or actually a proposal.

I'm aware that there are already several report classes available with phpcs, but I was missing one for GitHub Action workflows, that provides annotations (small boxes displayed directly on the PR files).

It turned out, that it's easy to achieve. Now I wonder, if the PHP_CodeSniffer team is interested in integrating that report type. If so, I could provide a pull request. But I'm also fine if there's no interest.

Here's a workflow where I use that report type - and the class: https://github.com/backdrop-contrib/i18n/blob/1.x-1.x/.github/misc/Github.php

**Comment by jrfnl** [comment]
There are already two PRs open for the same: #2918 and #3628. Please have a read through the discussions there and also take note of the [`cs2pr` option which can do the same without a new PHPCS report type](https://github.com/squizlabs/PHP_CodeSniffer/pull/2918#issuecomment-1120062401).

**Comment by indigoxela** [comment]
Oh, I see, then this issue is a duplicate. Many thanks for pointing me to those.
