### ISSUE TITLE
Add "max execution time" configuration option to prevent keeping hanging phpcs processes active

### ISSUE THREAD

**Issue by MurzNN** [squizlabs/PHP_CodeSniffer#3649]
**Describe the bug**
I use phpcs with VS Code and sometimes `phpcs` processes keep active in background for hours and even days, with actively consuming CPU.  So I need to figure out what is the source of slow system performance, catch such processes and kill them manually.

So adding  "max execution time" configuration option should give a workaround for such problems, to not collect hung `phpcs` processes in background for a long time.

**To reproduce**
1. Try to use VS Code with phpcs with different PHP files, sometimes you probably will got hanging `phpcs` processes, like in mine environment.

**Expected behavior**
The proper solution for the hanging phpcs processes should be getting the logs and filling separate issues about them, but I can't find the way to get logs from already running phpcs, to report the issue.

So will be good to have a workaround like "max execution time" configuration option, that will kill hanging phpcs processes automatically.

**Versions (please complete the following information):**
 - OS: Ubuntu Linux 22.04
 - PHP: 7.4
 - PHPCS: 3.7.1
 - Standard: PSR12

**Comment by jrfnl** [comment]
@MurzNN PHPCS allows for setting PHP ini directives from the command line using the PHP native `-d key[=value]`, so in my opinion this doesn't need any additional PHPCS native options, it's just the command which VSCode uses to run PHPCS which should be adjusted.

Ref: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Usage
