### ISSUE TITLE
Language in Wiki is incorrect

### ISSUE THREAD

**Issue by crstauf** [squizlabs/PHP_CodeSniffer#3657]
> You can also ignore a single line using the phpcs:ignore comment. This comment will ignore the line that the comment is on, _AND_ the following line.

The emphasized "and" is incorrect... from my tests, it should be "or", as the ignore statement does not ignore the following line if an error was found on the line that the comment is on.

**Comment by gsherwood** [comment]
Yep, the comment is inaccurate for the examples given. The way it actually works is:

If the comment is the only thing on the line, PHPCS will ignore the comment line itself AND the following line. In the following example, lines 1 and 2 are ignored.
```phpcs
// phpcs:ignore
$foo = [1,2,3];
bar($foo, false);
```
But if the comment is at the end of a code line, then PHPCS will only ignore the line that the comment is on. In the following example, line 1 is ignored:
```
$foo = [1,2,3]; // phpcs:ignore
bar($foo, false);
```

I'll correct the docs. Thanks a lot for the report.

**Comment by gsherwood** [comment]
The new docs are available here: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#ignoring-parts-of-a-file
