### ISSUE TITLE
Readonly properties

### ISSUE THREAD

**Issue by sheridans** [squizlabs/PHP_CodeSniffer#3699]
**Describe the bug**

When declaring readonly properties, current can be `public readonly` or `readonly public` both will pass sniff. I would assume it should be `public readonly`. Not sure if this is down to the individual coding standards or the right place to post.

**Comment by jrfnl** [comment]
There is already a PR open for this. See #3637

**Comment by sheridans** [comment]
Missed that one! thank you will close.
