### ISSUE TITLE
@phpcsSuppress multiple rules defined for class property fails.

### ISSUE THREAD

**Issue by saas786** [squizlabs/PHP_CodeSniffer#3701]
**Describe the bug**
I have the code, where when I combine multiple `@phpcsSuppress` rules, it fails.

This works fine:

```php
class SomeClass {

    /**
     * @since 2022.10.27
     * @var array<string>
     * @phpcsSuppress SlevomatCodingStandard.TypeHints.PropertyTypeHint.MissingNativeTypeHint
     */
    public $required_data_items = [ 'order' ]; // phpcs:ignore SlevomatCodingStandard.Classes.ForbiddenPublicProperty.ForbiddenPublicProperty
    
}
```

This doesn't work:

```php
class SomeClass {

    /**
     * @since 2022.10.27
     * @var array<string>
     * @phpcsSuppress SlevomatCodingStandard.TypeHints.PropertyTypeHint.MissingNativeTypeHint
     * @phpcsSuppress SlevomatCodingStandard.Classes.ForbiddenPublicProperty.ForbiddenPublicProperty
     */
    public $required_data_items = [ 'order' ];

}
```

**To reproduce**
1. Create a file called `test.php` with the code sample above...
2. Run `phpcs test.php ...`
3. See error message displayed
```
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 29 | ERROR | Do not use public properties. Use method access
    |       | instead.
    |       | (SlevomatCodingStandard.Classes.ForbiddenPublicProperty.ForbiddenPublicProperty)
----------------------------------------------------------------------

Time: 719ms; Memory: 16MB

Script phpcs handling the __exec_command event returned with error code 1

```

**Expected behavior**
I was expecting `SlevomatCodingStandard.Classes.ForbiddenPublicProperty.ForbiddenPublicProperty` to work as `@phpcsSuppress` rule

**Versions:**
 - OS: Windows 10
 - PHP: 7.4.30
 - PHPCS: 3.7.1

**Comment by jrfnl** [comment]
Please report this to the Slevomat package (and close this ticket). The annotation you are using is not a PHPCS native one.

For information on th PHPCS native ignore annotations and how to use them, please see: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#ignoring-parts-of-a-file

**Comment by saas786** [comment]
> Please report this to the Slevomat package (and close this ticket). The annotation you are using is not a PHPCS native one.
> 
> For information on th PHPCS native ignore annotations and how to use them, please see: [squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#ignoring-parts-of-a-file](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#ignoring-parts-of-a-file)

I don't understand, are you suggesting `Slevomat` overrides `phpcs` core functionality, I am only aware of `Slevomat` as it provided additional rules?

I am not asking about specific rule, I just provided the rule which is causing the issue for me.

`@phpcsSuppress` is `phpcs` helper, is it not?

If you still think its not relevant to this repo, can you please elaborate it a bit more, why is that?

Thanks.

**Comment by gsherwood** [comment]
As @jrfnl has said, that `@phpcsSuppress` is not a feature of PHPCS itself. There is no code in this repo to support that helper. It's all in the SlevomatCodingStandard: https://github.com/slevomat/coding-standard/blob/master/SlevomatCodingStandard/Helpers/SuppressHelper.php
