### ISSUE TITLE
How can i disable single line rule in succession functions  ?

### ISSUE THREAD

**Issue by FikretCin** [squizlabs/PHP_CodeSniffer#3710]
Here is my code:
![Screenshot_2](https://user-images.githubusercontent.com/98125934/200409152-59cf038f-8269-4379-8974-c365c4aa2407.jpg)

When i format or save file:

![Screenshot_3](https://user-images.githubusercontent.com/98125934/200409168-02f20bac-e7d0-4ac4-a5b2-4f2cec35899d.jpg)

Exceeds lines and makes it difficult to read.

**Comment by jrfnl** [comment]
This issue contains too little information to provide specific advise.

As a general rule of thumb:
* Run `phpcs` using the `-s` flag to see the error cod of the sniff.
* Add something the lines of `<exclude name="Stnd.Category.Sniff.ErrorCode"/>` to your custom ruleset or use the `--exclude=Stnd.Category.Sniff` flag on the command line (only allows excluding based on sniff name, not error code).

**Comment by FikretCin** [comment]
Hello again; 
`<exclude name="Squiz.WhiteSpace.ObjectOperatorSpacing.Before" />`
 Solve my problem thx for help
