### ISSUE TITLE
PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /usr/share/php/PHP/CodeSniffer/src/Config.php on line 420

### ISSUE THREAD

**Issue by joelwinzer** [squizlabs/PHP_CodeSniffer#3719]
**Error:**
When I run this command "phpcs --version" in the terminal, it shows me this error:
```
PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /usr/share/php/PHP/CodeSniffer/src/Config.php on line 420
```

**Versions:**
 - OS: MacOS 13.0.1
 - PHP:  8.1.12
 - PHPCS: 3.7.1

**Comment by jrfnl** [comment]
That is not possible with PHPCS 3.7.1. You will need to figure out where the install is which is used and update it.
