### ISSUE TITLE
Install on Wordpress as a Plugin

### ISSUE THREAD

**Issue by huzanf** [squizlabs/PHP_CodeSniffer#3723]
Hi,
I'd like to know how can I install this on WordPress as a plugin?

Looking forward to your support.

**Comment by jrfnl** [comment]
Your question is unclear. This package is a static analysis tool for PHP code. It has nothing to do with WordPress.

There is a set of WordPress specific static analysis rules available in [WordPressCS](https://github.com/WordPress/WordPress-Coding-Standards), but again: those rules are intended to be run over PHP code written for WordPress or for WordPress plugins/themes. They have no value _as_ a WordPress plugin as it won't do anything.

**Comment by jrfnl** [comment]
Closing as answered (without follow-up questions).
