### ISSUE TITLE
PHP 8.1 Enum methods error

### ISSUE THREAD

**Issue by meego47** [squizlabs/PHP_CodeSniffer#3746]
**Describe the bug**
When you use `$this` in Enum methods it throws `<PHPCompatibility.Variables.ForbiddenThisUseContexts.OutsideObjectContext>`  failure.

**Code sample**
```php
<?php

declare(strict_types=1);

namespace App\Enums;

enum MyEnum: int
{
    case ZERO = 0;
    case ONE = 1;
    case TWO = 2;

    public function otherCases(): array
    {
        return match ($this) {
            self::ZERO => [
                self::ONE, self::TWO,
            ],
            default => self::cases()
        };
    }
}

```

**To reproduce**
1. Create a file called `test.php` with the code sample above...
2. Run `phpcs test.php ...`
3. See error message displayed
```
[checkstyle] MyEnum.php#L20 <PHPCompatibility.Variables.ForbiddenThisUseContexts.OutsideObjectContext>
"$this" can no longer be used in a plain function or method since PHP 7.1.
```

**Expected behavior**
No error

**Versions (please complete the following information):**
 - OS: [Ubuntu 22.04]
 - PHP: [8.1]
 - PHPCS: [3.7.1]
 - Standard: [PSR2]

**Comment by jrfnl** [comment]
@meego47 You're reporting this in the wrong repo. This is the repo for the PHP_CodeSniffer package, not for the external [PHPCompatibility PHPCS standard](https://github.com/PHPCompatibility/PHPCompatibility).

As a side-note: this has already been fixed in PHPCompatibility `develop`.
