### ISSUE TITLE
PHPCBF incorrectly indents statements when mixing PSR12 and basic indentation config

### ISSUE THREAD

**Issue by neerolyte** [squizlabs/PHP_CodeSniffer#3765]
**Describe the bug**

We have a large legacy repo with some PSR12 code and a lot of old code that is merely "tab indented". The config we thought was reasonably handling those two different code patterns turns out to be breaking some indentation when PHPCBF fixes the PSR12 code.

**Code sample**

When a PSR12 file starts like this:
```php
<?php
if (false) exit(1);
```

phpcbf adds the missing braces (`{}`), but moves the statement (`exit(1)`) on to its own line without indenting it e.g:

```php
<?php

if (false) {
exit(1);
}
```

**Custom ruleset**
```xml
<?xml version="1.0"?>
<ruleset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="Matrix"
		 xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/squizlabs/PHP_CodeSniffer/master/phpcs.xsd">
	<description>PHP_CodeSniffer Standard</description>

	<arg name="basepath" value="."/>
	<arg name="cache" value=".phpcs-cache"/>
	<arg name="colors"/>
	<arg name="tab-width" value="4"/>
	<arg name="parallel" value="20"/>

	<file>old-code/</file>
	<file>psr12/</file>

	<!-- Check PHP syntax (php -l) on all files -->
	<rule ref="Generic.PHP.Syntax" />

	<!-- Modern files all follow PSR12 -->
	<rule ref="PSR12">
		<exclude-pattern>old-code/</exclude-pattern>
	</rule>

	<!-- Legacy files just get tab based indentation enforced -->
	<rule ref="Generic.WhiteSpace.DisallowSpaceIndent">
		<exclude-pattern>psr12/</exclude-pattern>
	</rule>
	<rule ref="Generic.WhiteSpace.ScopeIndent">
		<exclude-pattern>psr12/</exclude-pattern>
		<properties>
			<property name="tabIndent" value="true"/>
		</properties>
	</rule>
</ruleset>
```

**To reproduce**
1. Create a file called `test.php` with the code sample above...
2. Run `phpcbf test.php ...`
3. See the incorrect indentation

**Expected behavior**

I'd like to either know how the config can be restructured so that the rules that are supposed to be excluding `psr12/` don't affect the behaviour there (e.g running `./vendor/bin/phpcbf --standard=PSR12 test.php` produces the correct indentation) or have `phpcbf` respect the current config as it seems like neither of the `Generic.WhiteSpace.*` rules we have should be affecting the behaviour under the `psr12/` directory.

**Versions (please complete the following information):**
 - OS: MacOS 13.2.1
 - PHP: 7.3 and 8.2.1
 - PHPCS: 3.7.2
 - Standard: PSR12 ish

**Additional context**

Demo repo: https://github.com/neerolyte/phpcbf-indentation-bug

**Comment by jrfnl** [comment]
> as it seems like neither of the `Generic.WhiteSpace.*` rules we have should be affecting the behaviour under the `psr12/` directory.

Well, that's true for the `DisallowSpaceIndent` rule, but no so for `ScopeIndent`. As [PSR12 includes the `ScopeIndent` sniff](https://github.com/squizlabs/PHP_CodeSniffer/blob/ed8e00df0a83aa96acf703f8c2979ff33341f879/src/Standards/PSR12/ruleset.xml#L60-L68), your ruleset as-is, explicitly turns that sniff off for the `psr12/` directory, effectively changing the behaviour of the PSR12 ruleset.

Okay, so solution-wise:
* Most stable would be to run PHPCS twice with separate rulesets for the separate parts of the codebase. That way you can differentiate to your hearts content without having to take into account what's already in PSR12.
* A "sneaky" solution just to fix this particular issue in the current ruleset and keep everything in one run: try swopping out the `Generic.WhiteSpace.ScopeIndent` sniff for the [`PEAR.WhiteSpace.ScopeIndent`](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/PEAR/Sniffs/WhiteSpace/ScopeIndentSniff.php) one. The sniffs are largely identical with one tiny difference, which for your purposes (legacy code) probably won't make much difference and the custom property which you are using with the `Generic.WhiteSpace.ScopeIndent` sniff is also supported by the `PEAR.WhiteSpace.ScopeIndent` sniff (via inheritance).

**Comment by neerolyte** [comment]
Ah thanks I didn't realise I was pulling a rule out of the PSR12 set, that does explain it.

> Most stable would be to run PHPCS twice with separate rulesets for the separate parts of the codebase

We've tried this in the past and couldn't get stable integration with IDE plugins as there's no (trivial) way to tell them to use different PHPCS configurations per directory either.

A clean way to have essentially incompatible configurations exist in the one `.phpcs.xml` file and have PHPCS internally do two separate runs would make this trivial, but I think I can close this off now.
