### ISSUE TITLE
Failed to set PHP CodeSniffer installed_paths Config

### ISSUE THREAD

**Issue by remayex** [squizlabs/PHP_CodeSniffer#3767]
Hi
Installing some module on a Drupal composer install, I have the following error with :
Upgrading squizlabs/php_codesniffer (3.7.1 => 3.7.2)

Failed to set PHP CodeSniffer installed_paths Config
> DrupalProject\composer\ScriptHandler::createRequiredFiles
Script DrupalProject\composer\ScriptHandler::createRequiredFiles handling the post-update-cmd event terminated with an exception
In ScriptHandler.php line 44:
  Use of undefined constant CONFIG_SYNC_DIRECTORY - assumed 'CONFIG_SYNC_DIRECTORY' (this will throw an Error in a future version of PHP)  

What can I possibly do to fix the issue ?
Thanks

**Comment by jrfnl** [comment]
This has got nothing to do with PHPCS, but with the PHP version.

Find whereever `CONFIG_SYNC_DIRECTORY` is used (without quotes) and then figure out whether the quotes are missing or whether the constant should be defined etc etc.

Also, please report this to the correct project. As per the error message: `DrupalProject\composer\ScriptHandler`.

**Comment by remayex** [comment]
Sorry... I was just figuring out this.
Switching to php 8 and composer update fix the problem.
Thanks for that quick reply !
