### ISSUE TITLE
[PEAR CS] Doc comment description must start with a capital letter

### ISSUE THREAD

**Issue by cmb69** [squizlabs/PHP_CodeSniffer#377]
Since PHPCS 2.0.0 an error is shown when a doc comment description doesn't start with a capital letter. That makes some sense, as it enforces the usage of proper English sentences. However, this new rule doesn't cater for HTML (PHPDocumentor 1) or Markdown (PHPDocumentor 2) markup, and shows an error when the comment starts with < or *, for instance.

Code to reproduce:

    /**
     * Wastes time.
     *
     * *Never ever* call this.
     *
     * @return void
     */
    function foo()
    {
    
    }

**Comment by gsherwood** [comment]
I've changed the DocComment sniff so that it only bans lowercase letters at the start of the long and short descriptions. All non-letter characters are allowed, including markdown special chars and numbers.

I did the same thing for Squiz BlockCommentSniff in case you are using that one as well.

**Comment by aik099** [comment]
Maybe you can do the same for `InlineComment` sniff as well? Currently I've needed to copy-paste that sniff to allow digits and braces in front of comments.

**Comment by gsherwood** [comment]
> Maybe you can do the same for InlineComment sniff as well?

Good idea. I've committed the change here: https://github.com/squizlabs/PHP_CodeSniffer/commit/c45a2a984919bd3d596c8d33f05ae3cb53728616
