### ISSUE TITLE
The 85 symbols per line in PHPCS standard

### ISSUE THREAD

**Issue by aik099** [squizlabs/PHP_CodeSniffer#378]
I'm using PHPCS standard to validate my own coding standard. Unfortunately max line length is set to 85 symbols in there, which IMO is wrong considering today's monitor sizes. Is there any way lift that restriction?

For my projects I'm using 120 symbols per line.

**Comment by towbeedaniels** [comment]
How do I input it to my project because it's just stressful

**Comment by mporam** [comment]
Just come across this while also trying to set the line length to 120 as per the PSR2 guidelines. when defining a custom ruleset, you can store the ruleset file anywhere on your HD, then run `phpcs --standard={path/to/ruleset.xml}` to use it.

If like me however, you are running PHPCS through your IDE, such as PHPStorm, there is a set of built-in rulesets which you can use to do this for you! In PHPStorm:
`Preferences > Editor > Inspections > PHP > Quality tools > PHP_CodeSniffer validation`
at the bottom of the right-hand window is a `Coding standard:` drop-down, this will likely be empty (or just contain Custom) initially, however, if you refresh the list (by pressing the circular arrow button) it will import the PSR standard rule sets for you to set. Selecting PSR2 (or PSR12 now) will set your line length to 120!
