### ISSUE TITLE
PHPCS reports many errors that are not errors

### ISSUE THREAD

**Issue by tolki5** [squizlabs/PHP_CodeSniffer#3788]
I ran the phpcs function over the php file which works normally and got this error report.

`<?xml version="1.0" encoding="UTF-8"?>
<checkstyle version="2.9.2">
<file name="D:\php\index.php">
 <error line="1" column="1" severity="error" message="End of line character is invalid; expected &quot;\n&quot; but found &quot;\r\n&quot;" source="Generic.Files.LineEndings.InvalidEOLChar"/>
 <error line="14" column="1" severity="error" message="Spaces must be used to indent lines; tabs are not allowed" source="Generic.WhiteSpace.DisallowTabIndent.TabsUsed"/>
 <error line="36" column="1" severity="error" message="Expected 1 space after FOREACH keyword; 0 found" source="Squiz.ControlStructures.ControlSignature.SpaceAfterKeyword"/>
 <error line="36" column="1" severity="error" message="Expected 1 space before &quot;=&gt;&quot;; 0 found" source="Squiz.ControlStructures.ForEachLoopDeclaration.NoSpaceBeforeArrow"/>
 <error line="36" column="1" severity="error" message="Expected 1 space after &quot;=&gt;&quot;; 0 found" source="Squiz.ControlStructures.ForEachLoopDeclaration.NoSpaceAfterArrow"/>
 <error line="36" column="30" severity="error" message="Expected 1 space after closing parenthesis; found 0" source="Squiz.ControlStructures.ControlSignature.SpaceAfterCloseParenthesis"/>
 <error line="37" column="1" severity="error" message="Spaces must be used to indent lines; tabs are not allowed" source="Generic.WhiteSpace.DisallowTabIndent.TabsUsed"/>
 <error line="38" column="1" severity="error" message="Spaces must be used to indent lines; tabs are not allowed" source="Generic.WhiteSpace.DisallowTabIndent.TabsUsed"/>
 <error line="38" column="5" severity="error" message="Expected 1 space after IF keyword; 0 found" source="Squiz.ControlStructures.ControlSignature.SpaceAfterKeyword"/>
 <error line="38" column="22" severity="error" message="Expected 1 space after closing parenthesis; found 0" source="Squiz.ControlStructures.ControlSignature.SpaceAfterCloseParenthesis"/>
 <error line="38" column="23" severity="error" message="Blank line found at start of control structure" source="Squiz.WhiteSpace.ControlStructureSpacing.SpacingAfterOpen"/>
 <error line="40" column="1" severity="error" message="Spaces must be used to indent lines; tabs are not allowed" source="Generic.WhiteSpace.DisallowTabIndent.TabsUsed"/>
 <error line="41" column="1" severity="error" message="Spaces must be used to indent lines; tabs are not allowed" source="Generic.WhiteSpace.DisallowTabIndent.TabsUsed"/>
 <error line="42" column="1" severity="error" message="Spaces must be used to indent lines; tabs are not allowed" source="Generic.WhiteSpace.DisallowTabIndent.TabsUsed"/>
 <error line="44" column="1" severity="error" message="Spaces must be used to indent lines; tabs are not allowed" source="Generic.WhiteSpace.DisallowTabIndent.TabsUsed"/>
 <error line="44" column="9" severity="error" message="Expected 1 space after WHILE keyword; 0 found" source="Squiz.ControlStructures.ControlSignature.SpaceAfterKeyword"/>
 <error line="44" column="37" severity="error" message="Expected 1 space after closing parenthesis; found 0" source="Squiz.ControlStructures.ControlSignature.SpaceAfterCloseParenthesis"/>
 <error line="44" column="38" severity="error" message="Blank line found at start of control structure" source="Squiz.WhiteSpace.ControlStructureSpacing.SpacingAfterOpen"/>
 <error line="45" column="1" severity="error" message="Spaces must be used to indent lines; tabs are not allowed" source="Generic.WhiteSpace.DisallowTabIndent.TabsUsed"/>
 <error line="46" column="1" severity="error" message="Spaces must be used to indent lines; tabs are not allowed" source="Generic.WhiteSpace.DisallowTabIndent.TabsUsed"/>
 <error line="47" column="1" severity="error" message="Spaces must be used to indent lines; tabs are not allowed" source="Generic.WhiteSpace.DisallowTabIndent.TabsUsed"/>
 <error line="47" column="13" severity="error" message="Expected 1 space after IF keyword; 0 found" source="Squiz.ControlStructures.ControlSignature.SpaceAfterKeyword"/>
 <error line="47" column="32" severity="error" message="Expected 1 space after closing parenthesis; found 0" source="Squiz.ControlStructures.ControlSignature.SpaceAfterCloseParenthesis"/>
 <error line="47" column="33" severity="error" message="Blank line found at start of control structure" source="Squiz.WhiteSpace.ControlStructureSpacing.SpacingAfterOpen"/>
 <error line="48" column="1" severity="error" message="Spaces must be used to indent lines; tabs are not allowed" source="Generic.WhiteSpace.DisallowTabIndent.TabsUsed"/>
 <error line="49" column="1" severity="error" message="Spaces must be used to indent lines; tabs are not allowed" source="Generic.WhiteSpace.DisallowTabIndent.TabsUsed"/>
 <error line="50" column="1" severity="error" message="Spaces must be used to indent lines; tabs are not allowed" source="Generic.WhiteSpace.DisallowTabIndent.TabsUsed"/>
 <error line="50" column="17" severity="error" message="Expected 1 space after IF keyword; 0 found" source="Squiz.ControlStructures.ControlSignature.SpaceAfterKeyword"/>
 <error line="50" column="36" severity="error" message="Expected 1 space after closing parenthesis; found 0" source="Squiz.ControlStructures.ControlSignature.SpaceAfterCloseParenthesis"/>
 <error line="50" column="37" severity="error" message="Blank line found at start of control structure" source="Squiz.WhiteSpace.ControlStructureSpacing.SpacingAfterOpen"/>
 <error line="51" column="1" severity="error" message="Spaces must be used to indent lines; tabs are not allowed" source="Generic.WhiteSpace.DisallowTabIndent.TabsUsed"/>
 <error line="52" column="1" severity="error" message="Spaces must be used to indent lines; tabs are not allowed" source="Generic.WhiteSpace.DisallowTabIndent.TabsUsed"/>
 <error line="53" column="1" severity="error" message="Spaces must be used to indent lines; tabs are not allowed" source="Generic.WhiteSpace.DisallowTabIndent.TabsUsed"/>
 <error line="53" column="54" severity="error" message="Spaces must be used for alignment; tabs are not allowed" source="Generic.WhiteSpace.DisallowTabIndent.NonIndentTabsUsed"/>
 <error line="53" column="54" severity="error" message="Whitespace found at end of line" source="Squiz.WhiteSpace.SuperfluousWhitespace.EndLine"/>
 <error line="54" column="1" severity="error" message="Spaces must be used for alignment; tabs are not allowed" source="Generic.WhiteSpace.DisallowTabIndent.NonIndentTabsUsed"/>
 <error line="55" column="1" severity="error" message="Spaces must be used for alignment; tabs are not allowed" source="Generic.WhiteSpace.DisallowTabIndent.NonIndentTabsUsed"/>
 <error line="56" column="1" severity="error" message="Spaces must be used for alignment; tabs are not allowed" source="Generic.WhiteSpace.DisallowTabIndent.NonIndentTabsUsed"/>
 <error line="57" column="1" severity="error" message="Spaces must be used for alignment; tabs are not allowed" source="Generic.WhiteSpace.DisallowTabIndent.NonIndentTabsUsed"/>
 <error line="57" column="21" severity="error" message="Expected 1 space after IF keyword; 0 found" source="Squiz.ControlStructures.ControlSignature.SpaceAfterKeyword"/>
 <error line="57" column="45" severity="error" message="PHP keywords must be lowercase; expected &quot;and&quot; but found &quot;AND&quot;" source="Generic.PHP.LowerCaseKeyword.Found"/>
 <error line="57" column="63" severity="error" message="Expected 1 space after closing parenthesis; found 0" source="Squiz.ControlStructures.ControlSignature.SpaceAfterCloseParenthesis"/>
 <error line="57" column="64" severity="error" message="Blank line found at start of control structure" source="Squiz.WhiteSpace.ControlStructureSpacing.SpacingAfterOpen"/>
 <error line="58" column="1" severity="error" message="Spaces must be used for alignment; tabs are not allowed" source="Generic.WhiteSpace.DisallowTabIndent.NonIndentTabsUsed"/>
 <error line="59" column="1" severity="error" message="Spaces must be used for alignment; tabs are not allowed" source="Generic.WhiteSpace.DisallowTabIndent.NonIndentTabsUsed"/>
 <error line="60" column="1" severity="error" message="Spaces must be used for alignment; tabs are not allowed" source="Generic.WhiteSpace.DisallowTabIndent.NonIndentTabsUsed"/>
 <error line="60" column="25" severity="error" message="Expected 1 space after IF keyword; 0 found" source="Squiz.ControlStructures.ControlSignature.SpaceAfterKeyword"/>
 <error line="60" column="47" severity="error" message="Expected 1 space after closing parenthesis; found 0" source="Squiz.ControlStructures.ControlSignature.SpaceAfterCloseParenthesis"/>
 <error line="61" column="1" severity="error" message="Spaces must be used for alignment; tabs are not allowed" source="Generic.WhiteSpace.DisallowTabIndent.NonIndentTabsUsed"/>
 <error line="61" column="29" severity="error" message="Expected 1 space after WHILE keyword; 0 found" source="Squiz.ControlStructures.ControlSignature.SpaceAfterKeyword"/>
 <error line="61" column="67" severity="error" message="Expected 1 space after closing parenthesis; found 0" source="Squiz.ControlStructures.ControlSignature.SpaceAfterCloseParenthesis"/>
</file>
</checkstyle>`

**This is my configuration file:**
` $phpCodeSnifferConfig = array (
  'default_standard' => 'PSR2',
  'encoding' => 'windows-1250',
  'show_warnings' => '0',
  'php_version' => '50606',
  'tab_width' => '4',
  'severity' => '5',
  'php_path' => 'C:\\PHP'
)`

I'm using this script:
`C:\Users\Tolki\AppData\Roaming\Composer\vendor\bin\phpcs.bat --report=checkstyle D:\php\index.php`

I would like to only return errors that are serious and prevent the script from running on the server. Such as a missing semicolon, parenthesis, etc. I don't care about errors like use spaces instead of tabs.

I read the forums and apparently the problem is in the rullset. However, I am not able to get a rullset anywhere that would meet my requirements. I only want to point out errors that make it impossible to run the script on the server.

Many thanks for support!

**Comment by fredden** [comment]
It sounds like you want the `-l` or `--syntax-check` flag for the `php` executable. https://www.php.net/manual/en/features.commandline.options.php

PHP_CodeSniffer is a tool for checking that code conforms to a particular coding standard.

**Comment by tolki5** [comment]
Yes, this is exactly what i need. However, when calling php, in the event of an error, I get a response in this format:

`Parse error: syntax error, unexpected '$resPcs' (T_VARIABLE) in D:\php\index.php on line 22
Errors parsing D:\php\index.php`

This format is not compatible with https://github.com/deadem/notepad-pp-linter, which I would like to use in notepad++ to pre-check scripts.

Only supported format is from phpcs:
`<?xml version="1.0" encoding="UTF-8"?> <checkstyle version="2.9.2"> <file name="D:\php\index.php"> <error line="1" column="1" severity="error" message="End of line character is invalid; expected &quot;\n&quot; but found &quot;\r\n&quot;" source="Generic.Files.LineEndings.InvalidEOLChar"/></file></checkstyle>`

**Comment by jrfnl** [comment]
@tolki5 Sounds like you are looking for a tool like [PHP Parallel Lint](https://github.com/php-parallel-lint/PHP-Parallel-Lint/).

Note: this repo is not a general PHP tooling support forum. You may be better off in StackOverflow or something.

**Comment by gsherwood** [comment]
Agree with @jrfnl - sounds like you're not looking for a tool to enforce coding standards. Try the linter and you'll get what you need.
