### ISSUE TITLE
PSR-PER 2.0.0  has been released

### ISSUE THREAD

**Issue by jrfnl** [squizlabs/PHP_CodeSniffer#3793]
PSR-PER is an evolving standard which builds onto PSR-12.

The first "release" (= updated standards publication) since the fork of PSR-12 has just been published.

I'm opening this ticket to allow for a discussion on if and if so, how to handle these evolving standards in PHPCS.

Refs:
* https://github.com/php-fig/per-coding-style/releases/tag/2.0.0
* https://github.com/php-fig/per-coding-style/compare/1.0.0...2.0.0
* https://github.com/php-fig/per-coding-style/blob/2.0.0/spec.md
* https://github.com/php-fig/per-coding-style/blob/2.0.0/meta.md

**Comment by viktorprogger** [comment]
Are there any plans on implementing this?

**Comment by jrfnl** [comment]
@viktorprogger Still up for discussion, but I'd deem it likely (once we've worked through most of the backlog).

**Comment by kenguest** [comment]
Is there anything that can be done to help nudge this along? :-)

**Comment by jrfnl** [comment]
@kenguest Well, aside from the decision which still needs to be taken about this, it might be good to create an action list of the differences between PSR-12 and PSR-PER ?

For each difference, it will need to be determined whether there is an existing sniff which could handle this (possibly with a `public` property setting) or whether a new sniff is needed.

Another thing to have a good think about would be how to handle versioning, as without some form of versioning, a PSR-PER ruleset would be a moving target which could randomly start failing CI builds due to new rules being introduced (and being sniffed for).

**Comment by kenguest** [comment]
@jrfnl I'm working on a list of changes between the two standards, then an action list.
PER-CS is at version 2 at the moment, and there will be distinct version numbers so it should just be a case of having one set of sniffs called PERCS200 (for v2.0.0) and so on.

**Comment by lombervid** [comment]
As far as I've seen, PER 2.0 only adds some rules on top of PSR-12 for the new language features.

Here the differences can be better appreciated:
https://github.com/php-fig/per-coding-style/compare/8201676d799ca5d03bec8ee702df1dd3fda8d2b0..2.0.0

**Comment by kenguest** [comment]
@jrfnl We've (php fig) got a migration document now, it's at https://github.com/php-fig/per-coding-style/blob/master/migration-2.0.md
