### ISSUE TITLE
Where is Security::getRequestData() defined?

### ISSUE THREAD

**Issue by srguglielmo** [squizlabs/PHP_CodeSniffer#3847]
In the `MySource.PHP.GetRequestData` sniff, it references using `Security::getRequestData()` instead of using `$_POST`/`$_GET`/etc directly.

[https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/MySource/Sniffs/PHP/GetRequestDataSniff.php](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/MySource/Sniffs/PHP/GetRequestDataSniff.php)

Where is the `Security` class defined...? How do I use this `getRequestData()` method? I've searched around on Google and it does not seem to be a public/standard library for PHP.

**Comment by jrfnl** [comment]
The `MySource` standard is a bit of an odd one out in that it appears to be a standard for a specific code base and shouldn't really be part of PHP_CodeSniffer.

The standard will be removed in PHPCS 4.0 in its entirety. See #2471

> Where is the Security class defined...? How do I use this getRequestData() method? I've searched around on Google and it does not seem to be a public/standard library for PHP.

Good question, probably in the codebase for which the MySource standard was written long ago, but where is now and whether it still exists is a mystery ;-)

**Comment by srguglielmo** [comment]
Got it. Thanks!
