### ISSUE TITLE
Cannot reference custom sniff via name

### ISSUE THREAD

**Issue by datadestroyd** [squizlabs/PHP_CodeSniffer#3849]
I am trying to create a custom standard including a few custom sniffs. I have the following directory structure:

```
ruleset.xml
Sniffs
    Category
        BarSniff.php
```

In `ruleset.xml` I set `namespace="MyStandard"` and the namespace in `BarSniff.php` is `MyStandard\Sniffs\Category`.

In the project to be linted I reference the custom standard in `phpcs.xml` with `<rule ref="../path/to/standard"/>`. This works like a charm. However, I don't seem to be able to reference the custom sniffs from `phpcs.xml` in any way. For instance, if I wanted to exclude BarSniff, I would add `<exclude name="MyStandard.Category.Bar"/>`, but phpcs complains that the sniff does not exist, even though it is executed when run without the exclude tag. It is also listed under this name if I run `phpcs -e`. What am I doing wrong?

**Comment by jrfnl** [comment]
@datadestroyd While you are providing a lot of useful info, I'm still missing the essential info to debug this.
* What is the directory in which you have your `ruleset.xml` file called ?
* Can you share the essential parts of your custom `phpcs.xml` file ?
* Do you use Composer to install the standard and if so, does your `composer.json` file contain and `autoload` directive ? (which could be problematic)

**Comment by datadestroyd** [comment]
> What is the directory in which you have your `ruleset.xml` file called ?

That was it!! I didn't know that the directory name determined the standard's name. It though it was based on the namespace. Duh. Thanks a bunch!

**Comment by jrfnl** [comment]
@datadestroyd Glad it helped and you got things working!
