### ISSUE TITLE
How to ignore subpath of scanned code?

### ISSUE THREAD

**Issue by jeritiana** [squizlabs/PHP_CodeSniffer#3859]
I get the `--ignore` flag and I've read [Advanced-Usage#ignoring-files-and-folders](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#ignoring-files-and-folders), but I don't see how to ignore a subdirectory of the scanned code.

Example:
```
$ phpcs --ignore=/path/to/code/libraries/* /path/to/code
```

This still scans `/path/to/code/libraries/db_errors.php` (there are bunch of files, not only a single one, so `// phpcs:ignoreFile` would not be a viable option).

Thanks!

**Comment by fredden** [comment]
Perhaps you want the `-l` flag ("Local directory only, no recursion")?

Looking at the example in the linked documentation, you may want `phpcs --ignore=/libraries/* /path/to/code`, but I've not tested this myself. Can you report back if this behaves any differently for you?

**Comment by jrfnl** [comment]
@jeritiana Did the above solve your issue ? If not, please report back. If it did, please this issue.

**Comment by jeritiana** [comment]
I believe there was some kind of issue on my setup, it is working now. No specific resolution or something. Thanks for your help
