### ISSUE TITLE
Shrink the scope of 3.8.0 and release ASAP?

### ISSUE THREAD

**Issue by someniatko** [squizlabs/PHP_CodeSniffer#3896]
Hi! It seems this project is not as actively maintained as we all would like.

I noticed there is a 3.8.0 milestone which is about 60% complete. Perhaps it makes sense to only release 3.8.0 with what's already done + mandatory fixes to support PHP 8.2, and postpone everything else to later versions? Thanks!

**Comment by jrfnl** [comment]
Asked & answered. Also see: #3861

And for the record: the *only* things in the 3.8.0 milestone which are waiting to be merged, are basically bug fixes, quick fixes and PHP 8.2/8.3 compatibility issues.

**Comment by someniatko** [comment]
Got it, sorry for the disturbance!
