### ISSUE TITLE
Indentation of non-control structures isn't adjusted when containing structure is fixed

### ISSUE THREAD

**Issue by aik099** [squizlabs/PHP_CodeSniffer#390]
In following file this isn't indented:
* closing parenthesis of array declaration (`);`)
* then `return` statement of a method

```php
<?php

	defined('FULL_PATH') or die('restricted access!');

	/**
	 * Extends default ArticlesEventHandler class
	 *
	 */
	class EArticleEventHandler extends ArticlesEventHandler {

		/**
		 * Checks user permission to execute given $event
		 *
		 * @param kEvent $event
		 * @return bool
		 * @access public
		 */
		public function CheckPermission(kEvent $event)
		{
			$skip_permissions_check_events = Array (
				'OnAnotherCustomEvent',
			); // not indented correctly

			if ( in_array($event->Name, $skip_permissions_check_events) ) {
				return true;
			}

			return parent::CheckPermission($event); // not indented correctly
		}

	}
```
and fixed version looks like:
```php
<?php

	defined('FULL_PATH') or die('restricted access!');

	/**
	 * Extends default ArticlesEventHandler class
	 */
class EArticleEventHandler extends ArticlesEventHandler
{

	/**
	 * Checks user permission to execute given $event
	 *
	 * @param  kEvent $event
	 * @return bool
	 * @access public
	 */
	public function CheckPermission(kEvent $event)
	{
		$skip_permissions_check_events = array(
			'OnAnotherCustomEvent',
			); // not indented correctly

		if ( in_array($event->Name, $skip_permissions_check_events) ) {
			return true;
		}

			return parent::CheckPermission($event); // not indented correctly
	}

}
```

**Comment by gsherwood** [comment]
That's because no standard actually enforces their placement. Those lines must be indented *at least* 4 spaces, but they can be indented as far in as they want to be. Control structures are special as they are supposed to enforce their placement exactly.

But in this case, the function line itself has had the indent changed, so I should be able to detect that and also move the lines within it so the indentation at least remains what it was before fixing. I'll see if that can be done.

**Comment by aik099** [comment]
> But in this case, the function line itself has had the indent changed, so I should be able to detect that and also move the lines within it so the indentation at least remains what it was before fixing.

Exactly. Thanks.

**Comment by gsherwood** [comment]
This should be working now.
