### ISSUE TITLE
Error executing phpunit.

### ISSUE THREAD

**Issue by nelson1995** [squizlabs/PHP_CodeSniffer#3909]
## PHP_CodeSniffer Bug
I want to contribute to PHP_Codesniffer and I followed the [CONTRIBUTING.md](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CONTRIBUTING.md) documentation and executed them. After executing `phpunit` I encountered this error.
![Screenshot from 2023-10-28 20-39-58](https://github.com/squizlabs/PHP_CodeSniffer/assets/17122386/5003ee30-c1f8-4977-a049-03965bcd2f0e)

### To reproduce
This is the steps I took to reproduce the behavior:
1. Ran `cd PHP_CodeSniffer`
2. Ran `bin/phpcs`
3. Ran `phpunit`

This was the output after executing script `bin/phpcs`
![Screenshot from 2023-10-28 21-22-44](https://github.com/squizlabs/PHP_CodeSniffer/assets/17122386/6a447a64-fc15-4700-a87b-1fc10d3fb0eb)

## My environment details

| | |
|-|-|
| Operating System | Ubuntu 22.04.2 LTS
| PHP version | 8.2.8
| PHP_CodeSniffer version | 3.5.5, master
| Standard | [e.g., PSR2, PSR12, Squiz, custom]
| Install type | git clone
| PHPUnit version | 9.5.10

## Please confirm:
- [x] I confirm that this bug is a bug in PHP_CodeSniffer and not in one of the external standards.

**Comment by jrfnl** [comment]
@nelson1995 Thank you for your interest in contributing to PHPCS.

This is not a bug, but a question though, so please don't open a bug report for something like this.

Now, as for running the unit tests, there are a couple of issues here:
1. You are trying to run the tests with an incompatible PHPUnit version. The tests are currently only compatible with PHPUnit 4 - 7, not with PHPUnit 9. There is a [PR open to change this](https://github.com/squizlabs/PHP_CodeSniffer/pull/3803).
2. You are trying to run the tests on PHP 8.2. While this is possible with PHPUnit 7, the config file will not parse, so you would need to pass the config via the command line.

To get up and running quickly, I'd suggest running `composer install` and then using `vendor/bin/phpunit` on PHP 7.4.

If you want more extensive information, I suggest you have a read through the [open PR which updates the `CONTRIBUTING.md` file](https://github.com/squizlabs/PHP_CodeSniffer/pull/3830/files).

**Comment by nelson1995** [comment]
@jrfnl my apologies for the error. Thank you for the feedback. I’m going to resolve it.

**Comment by nelson1995** [comment]
Hello Juliette,

A quick question. Why does PHPUnit return an error “class Php_Timer not
found” ?
I’m running PHPUnit via ./vendor/bin/phpunit with PHP version 7.4 and I
checked the installed PHPUnit version has “Php_Timer” class.

Regards,
Nelson Katale

**Comment by jrfnl** [comment]
@nelson1995 I honestly don't know. Try running `composer du` to make sure the autoload file is up to date.

**Comment by nelson1995** [comment]
I ran the “composer du”  command and everything is updated. Unfortunately
the error still persists.

**Comment by jrfnl** [comment]
@nelson1995 Well, as I don't see the error, there's not much I can do to help you without you providing more information....
