### ISSUE TITLE
Squiz.WhiteSpace.OperatorSpacing incorrectly adds space after bitwise operator

### ISSUE THREAD

**Issue by kkmuffme** [squizlabs/PHP_CodeSniffer#3922]
## Describe the bug
Space added before bitwise or

### Code sample
```php
array_multisort(
	array_column( $test, 's' ),
	SORT_DESC,
	SORT_NATURAL|SORT_FLAG_CASE,
	$test
);
```

### Custom ruleset
Using `WordPress` https://github.com/WordPress/WordPress-Coding-Standards

### To reproduce
1. Create a file called `test.php` with the code sample above...
2. Run `phpcs test.php ...`
3. See error message displayed
```
Squiz.WhiteSpace.OperatorSpacing:216 replaced token 49 (T_BITWISE_OR on line ...
```

With phpcbf it get's autofixed to

```php
array_multisort(
	array_column( $test, 's' ),
	SORT_DESC,
	SORT_NATURAL |SORT_FLAG_CASE,
	$test
);
```

## Expected behavior
No error/change.

Afaik this worked correctly before.

## Versions (please complete the following information)

| | |
|-|-|
| Operating System | Linux
| PHP version | 8.2
| PHP_CodeSniffer version | 3.7.2
| Standard | WordPress (however the error is in Squiz)
| Install type | composer

## Please confirm:

- [x] I have searched the issue list and am not opening a duplicate issue.
- [x] I confirm that this bug is a bug in PHP_CodeSniffer and not in one of the external standards.
- [] I have verified the issue still exists in the `master` branch of PHP_CodeSniffer.

**Comment by jrfnl** [comment]
Closing as invalid. This behaviour is unchanged. I've tested all the way back to PHPCS 2.6.0 and also tested with WPCS 2.3.0.

**Comment by jrfnl** [comment]
> But it's still wrong - there's no code standard that wants a space before a binary or, is there?

No, it's not wrong. Nearly all sniffs are opinionated in one way or another. Clearly the standard you are using is of the opinion that there should be a space as they selected and enabled this sniff.
