### ISSUE TITLE
JavaScript: Indentation after object parameter

### ISSUE THREAD

**Issue by szepeviktor** [squizlabs/PHP_CodeSniffer#3928]
## Describe the bug
PSR12: Indentation after object parameter.
When the second parameter of `React.createElement` is removed there is no error.

### Code sample
```js
function doit()
{
    window.wc.wcBlocksRegistry.registerPaymentMethod({
        label: React.createElement('img', {
            foo: 'bar'
        }),
        content: 'text'
    });
}
```

### To reproduce
```
 7 | ERROR | [x] Line indented incorrectly; expected 4 spaces, found 8
   |       |     (Generic.WhiteSpace.ScopeIndent.IncorrectExact)
```

## Expected behavior
No errors.

## Versions (please complete the following information)

| | |
|-|-|
| Operating System | Debian stretch
| PHP version | 7.4
| PHP_CodeSniffer version | 3.7.2
| Standard | PSR-12
| Install type | composer

## Please confirm:

- [ ] I have searched the issue list and am not opening a duplicate issue.
- [x] I confirm that this bug is a bug in PHP_CodeSniffer and not in one of the external standards.
- [x] I have verified the issue still exists in the `master` branch of PHP_CodeSniffer.

**Comment by jrfnl** [comment]
Thanks for reporting this. Javascript support will be removed in PHPCS 4.0, so this is unlikely to get fixed. There are other, JS specific, code styling tools available nowadays. I suggest you use those.

**Comment by szepeviktor** [comment]
You made me very glad that PHPCS will be a PHP-only tool.
