### ISSUE TITLE
> Where Excel file import in codeigniter, the problem exists for phpexcel 1.8.0 on PHP 7

### ISSUE THREAD

**Issue by HekaalXFG** [squizlabs/PHP_CodeSniffer#3931]
> Where Excel file import in codeigniter, the problem exists for phpexcel 1.8.0 on PHP 7
> 
> A PHP Error was encountered
> Severity: 8192
> 
> Message: Array and string offset access syntax with curly braces is deprecated
> 
> Filename: Shared/String.php
> 
> Line Number: 529
> 
> Backtrace:
> 
> File: /opt/lampp/htdocs/example/application/third_party/PHPExcel/Autoloader.php
> Line: 82
> Function: _error_handler
> 
> File: /opt/lampp/htdocs/example/application/third_party/PHPExcel/Autoloader.php
> Line: 82
> Function: require
> 
> File: /opt/lampp/htdocs/example/application/third_party/PHPExcel/Autoloader.php
> Line: 36
> Function: spl_autoload_call
> 
> File: /opt/lampp/htdocs/example/application/third_party/PHPExcel.php
> Line: 6
> Function: require
> 
> File: /opt/lampp/htdocs/example/application/controllers/Flats.php
> Line: 4
> Function: require_once
> 
> File: /opt/lampp/htdocs/example/index.php
> Line: 318
> Function: require_once

hi did you find the solution..if yes pls provide me I am unable to export the data in excel format it showing error same of deprecated

_Originally posted by @ravinegi17 in https://github.com/squizlabs/PHP_CodeSniffer/issues/2558#issuecomment-880459844_

**Comment by jrfnl** [comment]
@HekaalXFG You are reporting this to the wrong repo. Your problem sounds like it is related to the [PHPExcel](https://github.com/PHPOffice/PHPExcel) package which was archived in 2019 and for which [PHPSpreadsheet](https://github.com/PHPOffice/PhpSpreadsheet) is the replacement.

I suggest you upgrade your dependencies and report issues in the correct repo in the future.
