### ISSUE TITLE
PHPUnit 10 Support and Refactor of code required

### ISSUE THREAD

**Issue by nishant04412** [squizlabs/PHP_CodeSniffer#3950]
## Feature Request
Many applications are already working on PHPUnit 10 including mine and it uses [PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) for checking PHP coding standards.

My request is to release new version with PHPUnit 10 support.

Currently there is a file [AllSniffs](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/tests/Standards/AllSniffs.php) which we are using with our code but it has code related to suite() method which is removed from PHPUnit 10. I believe this has to be refactored completely in order to work as intended.

## Additional context
PHPUnit 10+ versions drops support for suite() method as suggested in https://github.com/sebastianbergmann/phpunit/commit/36354a9cdc69ecabd20ac505b07541cfdde50aaa

**Comment by jrfnl** [comment]
This repo is abandoned. Please do not open issues here anymore. See #3932. New issues can be opened in the [successor repo](https://github.com/PHPCSStandards/PHP_CodeSniffer).

Also note: the above is a known issue and will be addressed in the PHPCS 4.0 release.

**Comment by nishant04412** [comment]
Thank you for the update @jrfnl. Will wait for PHPCS 4.0 release then.

**Comment by jrfnl** [comment]
FYI: related issue which can be followed to keep informed of the status: https://github.com/PHPCSStandards/PHP_CodeSniffer/issues/25
