### ISSUE TITLE
حل مشكلة

### ISSUE THREAD

**Issue by Ahmed5megoo** [squizlabs/PHP_CodeSniffer#3953]
Fatal error: Array and string offset access syntax with curly braces is no longer supported in /data/data/com.termux/files/home/fakecall/call.php on line 82
~/fakecall $

### Code sample
```php
echo "A short code snippet that can be used to reproduce the bug. Do NOT paste screenshots of code!";
```

### Custom ruleset
```xml
<?xml version="1.0"?>
<ruleset name="My Custom Standard">
  <description>If you are using a custom ruleset, please enter it here.</description>
</ruleset>
```

### To reproduce
1. Create a file called `test.php` with the code sample above...
2. Run `phpcs test.php ...`
3. See error message displayed
```
PHPCS output here
```

## Versions (please complete the following information)

| | |
|-|-|
| Operating System | [e.g., Windows 10, MacOS 10.15]
| PHP version | [e.g., 7.2, 7.4]
| PHP_CodeSniffer version | [e.g., 3.5.5, master]
| Standard | [e.g., PSR2, PSR12, Squiz, custom]
| Install type | [e.g. Composer (global/local), PHAR, PEAR, git clone, other (please expand)]

## Please confirm:

- [ ] I have searched the issue list and am not opening a duplicate issue.
- [ ] I confirm that this bug is a bug in PHP_CodeSniffer and not in one of the external standards.
- [ ] I have verified the issue still exists in the `master` branch of PHP_CodeSniffer.

**Comment by jrfnl** [comment]
Bogus, not related to this repo.
