### ISSUE TITLE
Missing checks of whitespace of short and long description in *.FunctionCommentSniff 

### ISSUE THREAD

**Issue by Konafets** [squizlabs/PHP_CodeSniffer#396]
The ```PEAR.Commenting.FunctionCommentSniff``` and ```Squiz.Commenting.FunctionCommentSniff``` claim to check for:

```php
/**
 * Parses and verifies the doc comments for functions.
 *
 * Verifies that :
 * <ul>
 *  ...
 *  <li>There is a blank newline after the short description.</li>
 *  <li>There is a blank newline between the long and short description.</li>
 *  <li>There is a blank newline between the long description and tags.</li>
 *  ...
 * </ul>
 */
```

Neither of the sniffs checks for that.

**Comment by gsherwood** [comment]
This checks were moved into https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/Generic/Sniffs/Commenting/DocCommentSniff.php

I'll remove the comments for clarity.
