### ISSUE TITLE
Bitwise operators aren't listed in any known operator groups in PHP_CodeSniffer_Tokens class

### ISSUE THREAD

**Issue by aik099** [squizlabs/PHP_CodeSniffer#397]
I think that following must be added:
* `T_SL` (`<<`) and `T_SR` (`>>`) to the `knownLengths` and `operators` arrays
* `T_SL_EQUAL` (`<<=`) and `T_SR_EQUAL` (`>>=`) to the `assignmentTokens` array

Theoretically all existing tests should pass, but maybe they need to be adjusted to test also for these new tokens.

**Comment by gsherwood** [comment]
I've added the missing bitwise operators. You are right in that it wont actually affect anything, but there is a tiny performance improvement if you use them a lot, and added consistency.

**Comment by aik099** [comment]
You've added them to the `weightings ` and `knownLengths` properties. I thought that you'll also add them to the `operators` and `assignmentTokens` as I suggested?

**Comment by gsherwood** [comment]
Sorry, I forgot to add them there as well. Done now.
