### ISSUE TITLE
Don't override verbosity for "phpcbf"

### ISSUE THREAD

**Issue by aik099** [squizlabs/PHP_CodeSniffer#404]
Currently the "verbosity" is overwritten during "phpcbf" run to prevent some of the output from getting to the patched file (according to comment in file) - https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/CLI.php#L129.

This however has side effect on `Fixer.php` because https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Fixer.php#L167-L179 code never gets to display fixed file version at the beginning of each pass.

I've discovered this because I have some fixing loop where fixed error count jumps between 7 and 19 and never ends.

**Comment by gsherwood** [comment]
If you want to see what the fixer is doing, you use PHPCS instead:

    phpcs --report=diff -vv ...

PHPCS is for reporting and PHPCBF is for fixing. I want to keep them clear if I can. You don't want to be using PHPCBF for debugging.

**Comment by aik099** [comment]
I don't know why, but with `phpcs --report=diff` I wasn't getting same fixing issue as with `phpcbf`. Maybe `phpcbf` with `--no-patch` option is doing something more, then just `phpcs --report=diff`.

**Comment by gsherwood** [comment]
The --no-patch option simply replaces the file contents using PHP instead of using the patch command. The fixes are identical because they are all done in memory before writing.

If you have a problem that you can't debug, please report it as an issue and I'll look into it. But I'll need the code and the ruleset (if it is custom) please.

**Comment by aik099** [comment]
Yes, I have #405 , which resulted in parsing error for another sniff that relied on `scope_closer`, which wasn't there due removed `}` of the class declaration.
