### ISSUE TITLE
The "Squiz.WhiteSpace.FunctionSpacing" sniff removes class "}" during fixing

### ISSUE THREAD

**Issue by aik099** [squizlabs/PHP_CodeSniffer#405]
Test file (before and after): https://gist.github.com/aik099/2fe455db22145e69e73c

![php_codesniffer_closingbraceremoved](https://cloud.githubusercontent.com/assets/1277526/5564686/8e07a24a-8ed6-11e4-8952-dc90933e40df.png)

**Comment by gsherwood** [comment]
I can't replicate this, but I did find an error with try/catch statements in that sniff, which I've fixed here: https://github.com/squizlabs/PHP_CodeSniffer/commit/1d426d84c24e97d1f824d3d48ea731d399ad9831

I was using the Squiz standard to try and replicate this problem. What standard are you using?

**Comment by aik099** [comment]
I was using https://github.com/aik099/CodingStandard/ standard. The class closing brace is also removed when 2 classes are declared in same file.

**Comment by gsherwood** [comment]
The reason I couldn't replicate is because it only happens when the `$spacing` property is set to `1`. I can replicate this now. Thanks.

**Comment by gsherwood** [comment]
This is now fixed.

**Comment by aik099** [comment]
Thanks.

Beside spacing set to 1 what were criteria for this sniff to eat class declaration closing brace? 

Sometimes it did that when I had 2 classes in the file. Sometimes, when I had 1 class in the file.

**Comment by aik099** [comment]
By the way because of that issue the missing empty line after last class method declaration also wasn't reported as error.
