### ISSUE TITLE
The "Squiz.WhiteSpace.MemberVarSpacing" not respecting "var"

### ISSUE THREAD

**Issue by aik099** [squizlabs/PHP_CodeSniffer#410]
When class property is defined via `var` and not `public/protected/private` keywords, then it's reported as error and auto-fixer added empty line before property declaration.

```php
<?php

class ProductHelper extends kHelper
{

	/**
	 * Specification fields
	 *
	 * @var Array
	 */
	var $specificationFields = array();

}
```
Error: `Expected 1 blank line before member var; 0 found (Squiz.WhiteSpace.MemberVarSpacing.Incorrect)`

**Comment by gsherwood** [comment]
I've fixed this, and a related issue in another sniff.

**Comment by aik099** [comment]
Thanks. Now I don't need to manually revert auto-fixes for this sniff.
