### ISSUE TITLE
Optimized fully qualified class names

### ISSUE THREAD

**Issue by orlangur** [squizlabs/PHP_CodeSniffer#424]
I would like to solve problem which PHP Refactoring Browser [claims to solve](https://github.com/QafooLabs/php-refactoring-browser#optimize-use-statements): replace all fully qualified class names in code with shorter form and add corresponding `use` statements. Troubles with their solution: produced code is syntactically incorrect (`use` statements added between `class` and brace), PHPDoc blocks and methods type-hinting are ignored.

Did somebody try to implement something like that with PHP Code Beautifier and Fixer? Maybe it's not a good idea to try it and solution should be based on something different (PHP Manipulator/PHP-CS-Fixer/PHP Parser etc.) or there is a ready-to-use IDE plugin solving this?

Thanks in advance.

**Comment by aik099** [comment]
I'm not sure, that PHP_CodeSniffer is the tool for the job here, because it doesn't analyze class tree to know what should be replaced with what and also fix all DocBlocks in same file, where FQCN is used.

I know that PhpStorm has inspection that reports such places (where FQCN can be removed through `use` statement adding). But I don't know if you can mass-apply the fix. You can try that yourself and see if it helps.

**Comment by gsherwood** [comment]
I agree that this is not a job for PHP_CodeSniffer's auto-fixer. PHP_CodeSniffer is built to detect coding standard violations and the correct them. You're talking about code refactoring. And while technically possible in PHP_CodeSniffer, it wouldn't be as efficient at the job as a dedicated refactoring tool.

**Comment by orlangur** [comment]
Thanks for the feedback! Want to make such requirement a part of coding standard actually :)

Should [stick](https://github.com/magento/magento2/issues/872#issuecomment-68098378) to PHP Parser approach maybe.

**Comment by gsherwood** [comment]
You can certainly use PHPCS to confirm all your namespaces are correct, and that you are using them, but it's probably the wrong tool to go through and doing an initial replacement of class names and addition of namespace and use statements.

Maybe after you've converted the project over to use namespaces, you can build a check to ensure they are still being used and get PHPCS to do that.

**Comment by orlangur** [comment]
Yeah, sniff checking this would be much easier than sniff with auto-correction. And there is no way to check this properly without custom PHPCS sniff anyway, so such sniff implementation is a mandatory part for my plan.

Is there some place in PHPCS repository for custom sniffs not belonging to some standard yet, like [`Contrib` namespace in php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/master/Symfony/CS/Fixer/Contrib)? For example, [short array syntax enforcement](https://github.com/magento/magento2/blob/develop/dev/tests/static/framework/Magento/Sniffs/Arrays/ShortArraySyntaxSniff.php) would be quite common for projects with minimum supported version  PHP5.4+.

**Comment by gsherwood** [comment]
> Is there some place in PHPCS repository for custom sniffs not belonging to some standard yet

Yes, the Generic standard folder inside PHPCS. "Generic" isn't actually a standard, but a collection of sniffs. Most contributed sniffs end up in there.

The folder is here: https://github.com/squizlabs/PHP_CodeSniffer/tree/master/CodeSniffer/Standards/Generic
