### ISSUE TITLE
Line length for cyrillic comments

### ISSUE THREAD

**Issue by nikolaykovenko** [squizlabs/PHP_CodeSniffer#435]
After my code checking, the CodeSniffer generates warnings "Line exceeds 120 characters; contains ... characters" for lines with cyrillic symbols with are less than 120 characters long. It looks like CS gets wrong length of strings, which contain cyrillic symbols.

For example:
https://yadi.sk/i/OoP0KP6ge2S7x
https://github.com/nikolaykovenko/cv/blob/yii2/ncmscore/core/ModelColumnsExploder.php#L62
https://github.com/nikolaykovenko/cv/blob/yii2/ncmscore/models/ActiveModel.php#L19

**Comment by Konafets** [comment]
Which standard do you use?

**Comment by nikolaykovenko** [comment]
PSR-2

**Comment by gsherwood** [comment]
You might not have set the encoding for PHPCS to use. Try adding `--encoding=utf-8` to the PHPCS command or setting it as the default encoding by running `phpcs --config-set encoding utf-8`.

**Comment by nikolaykovenko** [comment]
@gsherwood Yes, that's it. Sorry, it's my fault. Thank you for such great support.

**Comment by gsherwood** [comment]
No problem. Hopefully I'll be able to make utf-8 the default encoding in a future version.
