### ISSUE TITLE
Rule exceptions based on file type

### ISSUE THREAD

**Issue by brunobg** [squizlabs/PHP_CodeSniffer#438]
I'd like to avoid certain checks on JS files but not on PHP files. Is there someway to do that?

Maybe this is not the right question, so let me explain the problem. JS has lots of anonymous functions like 
```
someCall(function() {
});
```

Which leads to those pesky 'Opening parenthesis of a multi-line function call must be the last content on the line'. This was related before http://pear.php.net/bugs/bug.php?id=19768 but it's clear to me if there is a way to avoid it. Is there?

**Comment by aik099** [comment]
You can use per-sniff/per-file exclude based on filename. Look at lines with `exclude` work in this example: http://pear.php.net/manual/en/package.php.php-codesniffer.annotated-ruleset.php

**Comment by brunobg** [comment]
Oh, sorry for not finding it before posting here. Thanks a lot :)
