### ISSUE TITLE
Extend the sniff PEAR.Commenting.ClassComment to Interfaces and Traits

### ISSUE THREAD

**Issue by Konafets** [squizlabs/PHP_CodeSniffer#439]
Does it makes sense to do this? If yes, I can add a patch.

**Comment by aik099** [comment]
I think it does. I've also seen some sniffs ignoring traits and this was also fixed in previous releases.

**Comment by Konafets** [comment]
Ah, yes, it listen to interfaces but not for traits and the error messages say "Missing class doc comment" instead of "Missing class/interface/trait doc comment".

**Comment by aik099** [comment]
You can use `$tokens[$stackPtr]['content']` to get `class`, `interface` or `trait` word in your error message.

**Comment by Konafets** [comment]
I do in my custom sniff. Just thought it might be a good idea for the the shipped sniff as well.

**Comment by gsherwood** [comment]
If you submit a PR for this, I will merge it. I think this sniff can do all 3.

**Comment by gsherwood** [comment]
Closing as their is a PR for this, although it can't yet be merged in.
