### ISSUE TITLE
PHPCS master: PSR2.Sniffs.Methods.FunctionCallSignatureSniff should allow single argument as multi line

### ISSUE THREAD

**Issue by xalopp** [squizlabs/PHP_CodeSniffer#445]
This issue was introduced with commit 961057c1b452d67594154e9984e4ac57d1723076 for issue #412 

In PHPCS 2.1.0, both were valid in Coding Standard PSR2

    ok1(
        'foo ... very long argument 0123456789 ...'
    );
    ok2('bar');
    ok3(
        1,
        2
    );

With the change introduced commit 961057c1b452d67594154e9984e4ac57d1723076 the function call for "ok1" is invalid.

Considering the old behavior of PHPCS and according to PSR2 Chapter 4.6. "Method and Function Calls", I understand this to be a bug.

**Comment by jian-wu** [comment]
@xalopp, why would you wrap the argument in the function call when there's only one?

**Comment by gsherwood** [comment]
I don't think that syntax is really covered in the standard, but that's the case with a lot of code as well, so I've made this work again.

Thanks a lot for testing the master branch before release.

**Comment by xalopp** [comment]
@jian-wu the example was quite simplistic. He a real world example:

        $qb->select('application')
            ->from(Application::NAME, 'application')
            ->where($qb->expr()->like('application.applicationDefineName', $qb->expr()->literal("applicationDefineName%")));

The line containing the where Clause is quite to long (more than 120 chars), so l split up the like into multi line

        $qb->select('application')
            ->from(Application::NAME, 'application')
            ->where($qb->expr()->like(
                'application.applicationDefineName',
                $qb->expr()->literal("applicationDefineName%")
            ));

This already look quite good, but my IDE reformats this code to

        $qb->select('application')
            ->from(Application::NAME, 'application')
            ->where(
                $qb->expr()->like(
                    'application.applicationDefineName',
                    $qb->expr()->literal("{$applicationDefineName}%")
                )
            );

In my opinion, this is quite expressive.


The mentioned bug was on the "where" line, which only has 1 argument.
