### ISSUE TITLE
Inline Shorthand IF statement must be declared on a single line

### ISSUE THREAD

**Issue by Codewolf** [squizlabs/PHP_CodeSniffer#448]
in the following segment of code the 3rd line (containing the inline if) flags up as an error stating:
Inline Shorthand IF statement must be declared on a single line.

As can be seen in the snippet the if statement /is/ on only one line, this error also appears on something as simple as:
$v = (1==0) ? "Y" : "N";

spl_autoload_register(
    function ($class) {
        $base = (strpos(getcwd(), INCLUDES_DIR) === FALSE) ? INCLUDES_DIR . DIRECTORY_SEPARATOR : "";
        include "./{$base}classes/{$class}.php";
    }
);

**Comment by aik099** [comment]
Could you please use fenced code blocks to enable code highlighting?

Please also specify PHP_CodeSniffer version you're using and output of running `phpcs` with `-s` (show standard name) option.

**Comment by Codewolf** [comment]
My apologies, wasnt 100% sure of the wiki markup on here
```PHP
spl_autoload_register(
    function ($class) {
        $base = (strpos(getcwd(), INCLUDES_DIR) === FALSE) ? INCLUDES_DIR . DIRECTORY_SEPARATOR : "";
        include "./{$base}classes/{$class}.php";
    }
);
```
I have (for now) excluded the standard name but it is:
 - Squiz.ControlStructures.InlineIfDeclaration.NotSingleLine

The versions are as follows
 - phpcs : 1.5.5 (stable)
 - php: PHP 5.4.36-0+deb7u3

**Comment by aik099** [comment]
Latest PHP_CodeSniffer version released is 2.1.0. Please try that.

**Comment by gsherwood** [comment]
This has been fixed in the 2.x releases. The only error you get from the Squiz standard now is `Inline IF statements are not allowed`, which comes from a different sniff.

The Squiz standard is currently conflicting between these 2 sniffs, so I'll need to eventually move that inline if spacing sniff into the Generic standard. But I wont do that in 2.x because it breaks backwards compatibility a fair bit.

Does the new PHPCS version work for you?

**Comment by Codewolf** [comment]
apologies for the delay, i haven't been able to use the newest version of PHPCS due to certain constraints, however knowing it is fixed in the newer versions means i can keep this standard in mind for when i upgrade.
