### ISSUE TITLE
Fixing errors removes tabs

### ISSUE THREAD

**Issue by VasekPurchart** [squizlabs/PHP_CodeSniffer#450]
In current master when the `phpcbf` is fixing errors it replaces existing tab indentation with spaces and even when the DisallowSpaceIndentSniff is enabled produces an "done" state. 
I found out the commit, which has probably broken this is: 85267e2b, maybe https://github.com/squizlabs/PHP_CodeSniffer/commit/85267e2b891f541eee6c2330f9cf1cdcb5322176#diff-acee2709ae4492fd666b32bf4ad8ef93R735 this could be related? On previous commits it works fine.

For example having this file:

``` php
<?php

namespace Foo;
class Bar
{

	public function lorem()
	{
		$ipsum;
	}

}
```
tabs are used for indentation, a simple fixable error is made (`PSR2.Namespaces.NamespaceDeclaration.BlankLineAfter`) and `Generic.WhiteSpace.DisallowSpaceIndent` is enabled, the result of the fixing is marked as successful, but the actual produced code is:

``` php
<?php

namespace Foo;

class Bar
{

	public function lorem()
	{
	 $ipsum;
	}

}
```
And when the `phpcs` is run again it detects the wrong indentation via `Generic.WhiteSpace.ScopeIndent.Incorrect`.

**Comment by aik099** [comment]
> In current master when the phpcbf is fixing errors it replaces existing tab indentation with spaces and even when the DisallowSpaceIndentSniff is enabled produces an "done" state. 

4 spaces are not replaced back with 1 tab when you don't have `<arg name="tab-width" value="4" />` in your `ruleset.xml` or not using `--tab-width` command-line option.

**Comment by VasekPurchart** [comment]
I am sorry, I forgot to mention this in the OP, I am aware of this and using this setting.

**Comment by aik099** [comment]
What is `OP`?

**Comment by VasekPurchart** [comment]
Opening post

**Comment by gsherwood** [comment]
You are 100% right about which changed caused that error. I can't thank you enough for finding this issue.

**Comment by VasekPurchart** [comment]
Thanks for such a fast reaction, works like a charm again :thumbsup:

**Comment by aik099** [comment]
:+1:

**Comment by aik099** [comment]
@VasekPurchart , how do you install PHP_CodeSniffer, PEAR or Composer?

I'm asking because I wanted to know how you're able to verify @gsherwood changes so quickly.

I've installed through PEAR (because it's system-wide), but that requires me to wait for next release to use latest bugfixes if I'm encountering these bugs on my projects.

**Comment by Konafets** [comment]
@aik099 It is not really important how to install PHPCS (btw. Composer provides an system-wide installation too. The README shows the command.)

So you can install PHPCS system-wide via PEAR or Composer and additionally you maintain a local git clone of PHPCS where you can test the latest master. At the end "system-wide" just means that ```phpcs``` is inside ```$PATH```.

To use the system-wide installation you just type ```phpcs --standard=...```; to use the development branch you go inside the development installation and type ```scripts/phpcs --standards=...````

Does this helps you?

**Comment by aik099** [comment]
> Composer provides an system-wide installation too.

It's not system-wide, but user account wide. And you need to include the `~/.composer/vendor/bin` in your `PATH` to use it.

> To use the system-wide installation you just type phpcs --standard=...; to use the development branch you go inside the development installation and type scripts/phpcs --standards=...`

I'm changing `phpcs` in my build scripts to `/path/where/PHP_CodeSniffer/cloned/repo/is/scripts/phpcs` and see if that worked.

What's interesting is how you can benefit from a fix before a release was made on production environment? If composer is used, then you can checkout `master` branch and use it instead I guess.

**Comment by gsherwood** [comment]
If you use PEAR, you can still update your package to the latest code whenever you want, assuming you have no local modifications you want to keep.
```
git clone git://github.com/squizlabs/PHP_CodeSniffer.git
cd PHP_CodeSniffer
sudo pear uninstall PHP_CodeSniffer
sudo pear install package.xml
```
I can't remember if this remove the config file or not. If you set any global PHPCS configs, you may need to set them again after doing this.

At any time in the future, you can update using:
```
cd PHP_CodeSniffer
git pull
sudo pear uninstall PHP_CodeSniffer
sudo pear install package.xml
```

Or you can just run PHPCS directly from the Git clone. Maybe alias the CodeSniffer/scripts/phpcs script.

**Comment by aik099** [comment]
Thanks.

**Comment by VasekPurchart** [comment]
I am using PHPCS via composer and I have it as a dev dependency for each project, because from my experience different projects have different pace of upgrading and fixing errors.

It  is beneficial also in that way, that I can have different versions tied to different branches, so for example now I have a branch `phpcs-master` with require-dev on dev-master and there I tested all these changes without worrying about breaking any of my projects.

I think having build tools tied to project is a really good idea (as opposed to global installation), because as the projects evolve, so do the requirements for the build tools. And If you ever need to go back in history, everything should work as expected.

**Comment by aik099** [comment]
> It is beneficial also in that way, that I can have different versions tied to different branches, so for example now I have a branch phpcs-master with require-dev on dev-master and there I tested all these changes without worrying about breaking any of my projects.

I think I must also do this for projects in my company, because with recent 2.2 version release I've upgraded system-wide PHPCS installation on Jenkins machine and suddenly all projects started to receive an errors. And I had to figure out what the issue was and upgrade standard used in each project.
