### ISSUE TITLE
Ruleset exclude-pattern for specific sniff code ignored when using CLI --ignore option

### ISSUE THREAD

**Issue by VasekPurchart** [squizlabs/PHP_CodeSniffer#452]
I just noticed that since the 2.0 version the `<exclude-pattern>` directive stopped working for a specific code. This still works for a complete sniff, but I've always wanted to be as specific with excludes as possible (and maybe this was the only way to exclude checking specific code for a part of the codebase - or is there any other?). 

Example:
``` xml
<?xml version="1.0"?>
<ruleset name="XXX">
	<rule ref="PSR1.Files.SideEffects.FoundWithSymbols">
		<exclude-pattern>foo/bar.php</exclude-pattern>
	</rule>
</ruleset>
```
worked in 1.5.6, but no longer works in 2.0.0, this still works:
``` xml
<?xml version="1.0"?>
<ruleset name="XXX">
	<rule ref="PSR1.Files.SideEffects">
		<exclude-pattern>foo/bar.php</exclude-pattern>
	</rule>
</ruleset>
```

Is this intentional or a bug? I haven't found any notes on this in the release and I sure would miss this feature.

**Comment by gsherwood** [comment]
This is still working fine for me in both 2.0.0 and the latest version. Are you sure the regex is correct?

**Comment by VasekPurchart** [comment]
Oh, there is probably one more thing playing role - using the `--ignore` CLI parameter. When it is not used it is ignored properly with the code, but when it is, only the complete sniff ignore works.

**Comment by gsherwood** [comment]
Thanks. I think I can replicate it now.

**Comment by gsherwood** [comment]
Fixed now. Thanks for reporting.

**Comment by VasekPurchart** [comment]
Tested on my real life use case and work great, thanks!
