### ISSUE TITLE
PSR2 standard does not allow closing tag for mixed PHP/HTML files

### ISSUE THREAD

**Issue by clamburger** [squizlabs/PHP_CodeSniffer#453]
PSR-2 states the following (emphasis mine):

>[The closing ?> tag MUST be omitted from files **containing only PHP**.](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#22-files)

Zend.Files.ClosingTag only checks for a closing tag at the end of the file, ignoring the bolded part.

Here's an [example Gist](https://gist.github.com/clamburger/b7cb83a9a670a1d9ddd6) which is valid according to PSR-2, but running `phpcs --standard=PSR2` on the file gives the following output:

    --------------------------------------------------------------------------------
    FOUND 1 ERROR AFFECTING 1 LINE
    --------------------------------------------------------------------------------
     7 | ERROR | [x] A closing tag is not permitted at the end of a PHP file
    --------------------------------------------------------------------------------
    PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
    --------------------------------------------------------------------------------

Running `phpcbf` will remove the final closing tag.

**Comment by gsherwood** [comment]
I'm pretty sure the `containing only PHP` part is there because if they said all files must omit closing tags, someone would rightly complain that they are needed for mixed file contents.

I think the primary reason the closing tag is omitted is to stop whitespace being accidentally included at the bottom of the file. If the last part of the file happens to be PHP, then adding the tag there defeats the purpose of the rule.

I'll ask on the PHP-FIG-CS mailing list and see what I can find out.

**Comment by clamburger** [comment]
Your interpretation certainly makes sense. Although there may theoretically be a functional difference to removing the last closing tag (if you have intentional whitespace after it and are doing some weird things with includes) it seems unlikely to affect anybody in practice (and in my case, it's a cosmetic difference only). I'll leave it to your discretion as to whether this is a bug or not.

**Comment by gsherwood** [comment]
I've posted over here for clarification: https://groups.google.com/forum/#!topic/php-fig-cs/d2f-bu2YtmM

**Comment by gsherwood** [comment]
Thanks for picking this up @clamburger. It looks like you are right about this rule.

I'll change PHPCS to ignore this rule if it finds any non-empty inline HTML tokens anywhere in the file. This will still ensure whitespace after a closing tag in a PHP-only file never causes any problems, but just means peoples need to be a bit more careful about things like newlines at the end of template files.

**Comment by gsherwood** [comment]
Fixed now. Thanks again for reporting.
