### ISSUE TITLE
phpcs --version == 2.0.0 ? by phpcs.phar

### ISSUE THREAD

**Issue by mkuh** [squizlabs/PHP_CodeSniffer#455]
Hi
for the phpcs Version 2.2.0 
have phpcs --version output 2.0.0

is this ok ?

bye 
mkuh

**Comment by aik099** [comment]
How do you know that you have PHP_CodeSniffer 2.2.0 installed?

**Comment by Konafets** [comment]
I can not confirm that. The commit is in master branch b301c98f19414d836fdaa678648745fcca5aeb4f and I get the correct version.

```
$ phpcs --version                                                                                                  
PHP_CodeSniffer version 2.2.0 (stable) by Squiz (http://www.squiz.net)
```

**Comment by gsherwood** [comment]
If you have phpcs 2.2.0, the version number will say 2.2.0.

How did you update phpcs?

**Comment by jian-wu** [comment]
I cannot reproduce the issue either.  It prints the version correctly.

**Comment by mkuh** [comment]
Dowlowd via 
curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar

mkuh@pc ~ $ php phpcs.phar --version
PHP_CodeSniffer version 2.0.0 (stable) by Squiz (http://www.squiz.net)
mkuh@pc ~ $ md5sum phpcs.phar
3704eede7e3664165db556f46e200505  phpcs.phar

**Comment by gsherwood** [comment]
Sorry mate. I forgot to upload the new phars. They are up there now. Thanks for letting me know.

**Comment by mkuh** [comment]
Thank you
