### ISSUE TITLE
Add a new section about Git Hooks to the wiki

### ISSUE THREAD

**Issue by Konafets** [squizlabs/PHP_CodeSniffer#456]
# First draft:
# Introduction of Git-Hooks

   (can be mainly taken from the current SVN-Hooks text)
# Create a Hook

Hooks in GIT are located inside /path/to/project/.git/hooks/. GIT is shipped with some examples which can be found in this folder. The hook itself is just a shell script, which gets executed when the hook is called.

We will create a pre-push hook, which calls the PHP_CodeSniffer before pushing to remote. 

Create a file `pre-push` inside `.git/hooks/`

```
$ cd /path/to/project/
$ touch .git/hooks/pre-push
$ chmod +x .git/hooks/pre-push
```

and insert the following content:

```
#! /bin/bash -l

echo "Executing pre-push hook"

git stash -q --keep-index
phpcs
RESULT=$?
git stash pop -q

if [[ $RESULT != 0 ]]; then
    echo "There are failing results. Aborting." 1>&2
    exit 1
fi
```

The script stashes files which are not commited yet and reapplies the stash after the actual check is made. **You are not losing any data by this script.**

The hook will be executed when you push to remote. You can bypass the hook with adding the option `--no-verify` to the push command.

**Comment by jian-wu** [comment]
Great writeup.  However, there's a few grammar/spelling issues.  How do I make inline comments?  Thanks.

**Comment by aik099** [comment]
> How do I make inline comments?

Google to the resque: https://help.github.com/articles/commenting-on-the-diff-of-a-pull-request/

**Comment by hugofonseca** [comment]
I think what @jian-wu  wanted was this
https://github.com/blog/1399-quick-quotes

**Comment by jian-wu** [comment]
Thanks @hugofonseca.  That's exactly what I needed.

**Comment by hugofonseca** [comment]
@jian-wu apart from this I think @Konafets should create a PR.

**Comment by jian-wu** [comment]
@Konafets, here's a few things I found.

> can be find

should be *can be found*

> which get executed

should be *which gets executed*

> hooks is called

should be *hook is called*

> reapply

should be *reapplies*

> check was made

should be *check is made*

> not loosing

should be *not losing*

> hooks will executed

should be *hook will be executed*

Thanks again.

**Comment by jian-wu** [comment]
@hugofonseca, I agree creating a PR will be most helpful for others to make inline comments easier.  However, he's trying to update a section of the Wiki.  I've never tried a PR for Wiki and am not sure how to do so.

**Comment by hugofonseca** [comment]
Sure, you're right @jian-wu :)

**Comment by Konafets** [comment]
As far as I know PRs for the wiki are not possible. However, I updated my text above and appled the changes from @jian-wu. Thanks!

**Comment by jian-wu** [comment]
:+1:

**Comment by gsherwood** [comment]
Closing as I've decided I don't want to maintain this sort of doc in the wiki. Instead of how-to's, I'd like to limit it to references as I don't have time to maintain much more. Plus, this is the kind of information people are already publishing about PHPCS, so I don't need to write an officially endorsed version.

Thanks for this contribution though.
