### ISSUE TITLE
The "$testFile" in "getErrorList" and "getWarningList" methods

### ISSUE THREAD

**Issue by aik099** [squizlabs/PHP_CodeSniffer#463]
Unit test engine always passes fixture filename in 1st argument to the `getErrorList` and `getWarningList` methods. Fact, that most of unit tests only operate on one fixture file and therefore have no need for this filename doesn't mean that the parameter should be omitted in base unit test class declaration.

**Comment by gsherwood** [comment]
I didn't do that because I didn't want to go through and change every test method at the time. And I still don't want to do that.

**Comment by aik099** [comment]
What if somebody, say me, will make a PR with that change. Will it be accepted?

I guess I can make IDE to automatically change method declaration of each sub-class (unit test) which is using it. Changing DocBlock of each method might tricky though.

**Comment by gsherwood** [comment]
> What if somebody, say me, will make a PR with that change. Will it be accepted?

Yeah, I have nothing against it. But it will break all 3rd-party unit tests, so that's a fairly large BC break. I'd have to consider if it is really worth putting that into the 2.x version or waiting for a 3.0.

**Comment by aik099** [comment]
We can make that parameter optional, e.g. `$testFile = ''` so that if sub-class method declaration doesn't have it then no problem.

**Comment by gsherwood** [comment]
I'm pretty sure I've tried that and it doesn't work. Maybe I was doing it wrong.

**Comment by gsherwood** [comment]
Closing as I can't see this going anywhere.
