### ISSUE TITLE
PropertyLabelSpacing JS fixer issue when there is no space after colon  

### ISSUE THREAD

**Issue by sertand** [squizlabs/PHP_CodeSniffer#466]
When fixing the following code PHPCS adds extra spaces between the string and the closing brace. Fixer works fine when there is a single space after phpcs: 
```js
// Original code:
fn.phpcs(
    {phpcs:'rocks my world'}
);

// After running fixer:
fn.phpcs(
    {phpcs:'rocks my world'    }
);

**Comment by aik099** [comment]
Please specify PHP_CodeSniffer version and used standard.

**Comment by gsherwood** [comment]
Looks to be latest PHPCS with Squiz standard running over JS.

The fixable error is `There must be a single space after the colon in a property/label declaration` but the fix is incorrect when there are no spaces after the colon.

**Comment by gsherwood** [comment]
This is now fixed. Thanks for reporting.
