### ISSUE TITLE
Basepath option to show relative path names in report output

### ISSUE THREAD

**Issue by Hounddog** [squizlabs/PHP_CodeSniffer#470]
I am currently running php_codesniffer on jenkins with a vagrant-aws plugin.
When i run phpcs on the vagrant box and generate the report i get a fullpath starting at /vagrant/src/...

Once i copy this back to jenkins however the path doesnt match anymore.

Is there a way to generate reports with a base path or relative path?

**Comment by aik099** [comment]
how come, that you generate report on one machine and use it on another machine?

**Comment by Hounddog** [comment]
As mentioned i use jenkins. I set up the test environment using vagrant-aws and also generate all the reports on the "vagrant" machine and then just syncronize the reports back to the host. This way i dont have to install any dependencies on jenkins and can keep my whole development/test environment boxed.

**Comment by gsherwood** [comment]
There is no base path setting. Have you tried just passing a relative path to phpcs?

`phpcs temp.php  --report-file=./report.txt`

**Comment by gsherwood** [comment]
Oh sorry, I think I misunderstood what you are asking.

If you mean: can the report output contain a relative path instead of an absolute path to the files

The answer is: no

Your best option right now is to generate the file and then run a command over it to replace the `/vagrant/src/...` bit with whatever prefix you need for the other machine.

**Comment by Hounddog** [comment]
i figured as much. Would be great to generate it relative or absolute or with an own base path. Thanks for the quick reply though

**Comment by gsherwood** [comment]
Thanks for clarifying for me. Seems like a good feature request.

**Comment by muffl0n** [comment]
@Hounddog like mentioned in #522 the violations plugin in jenkins works perfectly with absolute paths and even refuses to display the file content when I use relative paths. Maybe you have to modify your reports with a script after you moved them from your VM to your jenkins machine?

**Comment by aik099** [comment]
Maybe instead you need to have some kind of report file transformation script that would fix paths as needed by machine that reads the report.

**Comment by gsherwood** [comment]
I've added this option in. You can use `--basepath=<basepath>` to have a path stripped from the front of file paths output to reports and in debug output. The path can be absolute or relative to the current dir.

A handy settings is: `--basepath=.`

**Comment by GaryJones** [comment]
@gsherwood Did this functionality get removed again?

**Comment by gsherwood** [comment]
> @gsherwood Would it be possible to add this to the 2.x branch?

It is possible, but I don't have the time to backport features from 3.x. I'm trying to move towards a 3.0 version ASAP and stabilise 2.x so it can stay around for a while during the migration.
