### ISSUE TITLE
Why is a minimum of 80 characters enforced for the report width?

### ISSUE THREAD

**Issue by klausi** [squizlabs/PHP_CodeSniffer#471]
Problem: commit bb4dfac146b482bc98f3881e80d8fdf45c687836 introduced a minimum width of 80 characters for reports, why? On drupal.org we need --report-width=75, otherwise it looks broken in the issue queue. Example: https://www.drupal.org/node/2406223#comment-9578933

Unfortunately there is no comment explaining why the minimum is needed, could we roll this back or improve otherwise?

**Comment by gsherwood** [comment]
Sorry, it should have been 70. I got confused by the default report width of 80. Fixed now: https://github.com/squizlabs/PHP_CodeSniffer/commit/d4ae072615852c63f18ebe58bd096b5f0903f36e
