### ISSUE TITLE
Writing a report for an empty folder to existing file includes the existing contents

### ISSUE THREAD

**Issue by aadmathijssen** [squizlabs/PHP_CodeSniffer#473]
When phpcs is run on a folder that doesn't contain any php files, an empty report is generated that is valid for the report type. However, when using the `--report-file` flag with an existing report file, the contents of that report file are included in the new report file. For some report types, this can generate incorrect files.

For instance, consider the report file `test-report.xml` with the following contents:

```
Existing data
```

Then run `phpcs /path/to/empty/folder --report=checkstyle --report-file=test-report.xml`, after which the contents of `test-report.xml` becomes:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<checkstyle version="2.2.0">
Existing data
</checkstyle>

```
  
Running this command again, results in the following contents of `test-report.xml`:

 ```xml
<?xml version="1.0" encoding="UTF-8"?>
<checkstyle version="2.2.0">
<?xml version="1.0" encoding="UTF-8"?>
<checkstyle version="2.2.0">
Existing data
</checkstyle>

</checkstyle>

```

I think the existing report file contents should always be discarded when writing a new report file.

**Comment by gsherwood** [comment]
Thanks for the very detailed bug report. I've fixed the bug now.

**Comment by aadmathijssen** [comment]
Wow, thanks for the rapid fix!
