### ISSUE TITLE
Check embeded JS code in PHP file

### ISSUE THREAD

**Issue by muswanto** [squizlabs/PHP_CodeSniffer#475]
I can't check JS style coding which is embeded in .php file. The style or sniff for this js code are same as my php code style/sniff.
```php
<?php
// i can check this php code with my custom sniff
class Some_class {
    // statement
}
?>
<script language="javascript">
// but i cant check code style here
function test_js() {
    // statement for js code here
}
</script>
```

**Comment by aik099** [comment]
I bet you can't. Not with `[script language="javascript"]` tag (where `<` replaced with `[`).

PHP_CodeSniffer doesn't have HTML parser so it can't really detect XML-alike structure like `<script>` tag in the file. I guess `token_get_all()` is returning one large string for that HTML piece.

**Comment by muswanto** [comment]
I'm sorry, i'm new in github, i cant write < or >. So i write it with [ and ] lol

**Comment by gsherwood** [comment]
Closing in favour of #319
