### ISSUE TITLE
Ignore abstract sniff classes

### ISSUE THREAD

**Issue by Decave** [squizlabs/PHP_CodeSniffer#476]
It appears that if you define your own coding standard, then *all* classes, including abstract classes, in the `/Sniffs` directory that end with 'Sniff' are improperly instantiated when running `phpcs`.

There should be a check for whether a class is abstract before it is instantiated, even if its name ends in 'Sniff'. This could be useful if someone wants to maintain a naming convention in that namespace, but still make a class abstract (i.e. `BaseMyStandardSniff`) rather than changing it to `BaseMyStandardHelper` or something of the sort.

**Comment by Decave** [comment]
If others think this is a good idea I'm happy to do the PR myself

**Comment by aik099** [comment]
:+1:

**Comment by gsherwood** [comment]
You shouldn't be adding `Sniff` to the end of classes inside the `Sniffs` directory if they are not sniff files. Checking every sniff to see if it is abstract on every run is additional time that isn't needed. Just move your abstract class to outside the `Sniffs` directory, as PHPCS itself does.

Would this solution work for you?

**Comment by Decave** [comment]
Would the performance hit really be non-negligible? It seems like a generally less than ideal design requirement to force users to move their abstract classes out of the namespace of their children. I don't have a serious problem with that solution at all, but if we could determine that the performance hit is acceptable then I think this would be a cleaner solution.

**Comment by gsherwood** [comment]
I'm sure the check itself wont take that long. I personally don't think that code needs to be in there, but if you want to a submit a PR for it, I'll certainly take a look and probably still accept it.

Ultimately, it's better if your life is easier, even if we do things differently.

**Comment by Decave** [comment]
Awesome, thanks -- I'll try to add a PR soon. If you end up deciding not to accept it, no hard feelings.

**Comment by Decave** [comment]
Hi @gsherwood, where do you recommend that I put tests for this? It seems like it should go in the Core suite as it's testing the actual loading of sniffs from a standard rather than the application of a standard itself, but I'm having trouble finding where the broader functionality of registering sniffs is already tested.

**Comment by gsherwood** [comment]
This isn't something the custom test runner will be able to test, so don't worry about them. One day I might get around to figuring out how to properly test the loading of custom rulesets, but I don't have time for that at the moment.

**Comment by Decave** [comment]
Alright, I'll push a PR tonight. Let me know if / when you decide to test loading custom rulesets and I'll help out however I can.
