### ISSUE TITLE
PHP_CodeSniffer PEAR.Commenting.FunctionComment.ParamNameNoMatch error

### ISSUE THREAD

**Issue by Saneesh** [squizlabs/PHP_CodeSniffer#478]
My source code generates the following error with PHP_CodeSniffer. "Doc comment for var &$myVar does not match actual variable name $myVar at position 2"

PEAR.Commenting.FunctionComment.ParamNameNoMatch

The code:

   /**
   * Function comment  
   *
   * @param object $newVar some comment
   * @param array &$myVar some comment
   *
   * @return null
   
*/
    

private function _myFunction($newVar, &$myVar) {
          // my code here...
    }

What could be the reason?

**Comment by aik099** [comment]
Please use fenced code blocks (https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks) to enable nice formatting and syntax highlight.

**Comment by gsherwood** [comment]
You need to remove the ampersand from the comment.

**Comment by aik099** [comment]
You should remove `&` from DocBlock. There was an error in one of PHP_CodeSniffer sniffs, that caused opposite behavior (& absence in DocBlock, when parameter definition has it) to be reported as error, but this was fixed.

**Comment by Saneesh** [comment]
Thank you very much!
