### ISSUE TITLE
[Perf] PHP_CodeSniffer seems to try to load the configuration file in a loop.

### ISSUE THREAD

**Issue by csarrazi** [squizlabs/PHP_CodeSniffer#486]
I/O operations are of course expected to be relatively high using PHP_CodeSniffer. However, it seems that PHP_CodeSniffer tries to load its main configuration file inside a loop, as shown in the following strace output:

    stat("/home/myuser/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer.conf, 0x7fff996c7990) = -1 ENOENT (No such file or directory)
    stat("@data_dir@/PHP_CodeSniffer/CodeSniffer.conf, 0x7fff996c7990) = -1 ENOENT (No such file or directory)
    stat("/home/myuser/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer.conf, 0x7fff996c7990) = -1 ENOENT (No such file or directory)
    stat("@data_dir@/PHP_CodeSniffer/CodeSniffer.conf, 0x7fff996c7990) = -1 ENOENT (No such file or directory)
    stat("/home/myuser/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer.conf, 0x7fff996c7990) = -1 ENOENT (No such file or directory)
    stat("@data_dir@/PHP_CodeSniffer/CodeSniffer.conf, 0x7fff996c7990) = -1 ENOENT (No such file or directory)
    stat("/home/myuser/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer.conf, 0x7fff996c7990) = -1 ENOENT (No such file or directory)
    stat("@data_dir@/PHP_CodeSniffer/CodeSniffer.conf, 0x7fff996c7990) = -1 ENOENT (No such file or directory)
    stat("/home/myuser/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer.conf, 0x7fff996c7990) = -1 ENOENT (No such file or directory)
    stat("@data_dir@/PHP_CodeSniffer/CodeSniffer.conf, 0x7fff996c7990) = -1 ENOENT (No such file or directory)
    stat("/home/myuser/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer.conf, 0x7fff996c7990) = -1 ENOENT (No such file or directory)
    stat("@data_dir@/PHP_CodeSniffer/CodeSniffer.conf, 0x7fff996c7990) = -1 ENOENT (No such file or directory)
    ...

(it goes long for pages and pages)

I didn't have time to look into the code yet, so I hope I'll be able to look more into this issue by the end of the week.

Regardless, in the mean time, we can clearly see that PHPCS'  something's wrong and should be corrected.

**Comment by gsherwood** [comment]
I think this might happen when you don't have a config file. The config is normally cached, but I can see that isn't happening if the file isn't found at all. I'll fix this up. Thanks for finding and reporting.

**Comment by gsherwood** [comment]
I've just pushed a fix. Please let me know if that doesn't work for you.
