### ISSUE TITLE
PSR2 - blanks before and after operators

### ISSUE THREAD

**Issue by legionth** [squizlabs/PHP_CodeSniffer#489]
Hi,

Currently there is no rule to find blanks before and after operators.
We are currently using something like this:
```php
 $link = '?'.build_query(array($this->getName()=>$value)+(is_array($overview) ? $overview : $overview->getArguments()),'','&amp;');
```
PSR2 demands whitespace around operators like . and + .

**Comment by aik099** [comment]
There is `Squiz.WhiteSpace.OperatorSpacing` sniff (see https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/Squiz/Sniffs/WhiteSpace/OperatorSpacingSniff.php), but it works for all operators, not only `+` or `-`.

**Comment by aik099** [comment]
Can you also please paste a link to PSR2 definition that explains space usage?

**Comment by gsherwood** [comment]
I'm pretty sure PSR2 does not specify any rule like this. In the conclusion, they explicitly say that operators are intentionally omitted: https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#7-conclusion

**Comment by legionth** [comment]
Hm, I think you are right. Was pretty sure about this. Sorry!

**Comment by aik099** [comment]
That's why I prefer to use custom standard, where everything is checked.
