### ISSUE TITLE
Add fixing to "Generic.PHP.ForbiddenFunctions" sniff

### ISSUE THREAD

**Issue by aik099** [squizlabs/PHP_CodeSniffer#499]
If there is alternative to used function in `Generic.PHP.ForbiddenFunctions` sniff, then it also can automatically replace used function name.

Of course this is only valid for cases, when order of arguments of both functions matches.

**Comment by Konafets** [comment]
I wouldn't go so far and change a forbidden function into another function by the fixer. This is a not anymore just a style manipulation but a direct change of program logic.

**Comment by aik099** [comment]
If we're talking about aliased functions, like `implode` and `join` then this won't be a problem.
