### ISSUE TITLE
ScopeClosingBrace and ScopeIndent conflict with closures used as array values

### ISSUE THREAD

**Issue by keyermann** [squizlabs/PHP_CodeSniffer#501]
Hi,

With this solution I have a Squiz.WhiteSpace.ScopeClosingBrace.Indent error : Closing brace indented incorrectly; expected 5 spaces, found 8

```php
<?php

    array(
     'key1' => function($bar) {
            return $bar;
        },
     'key2' => function($foo) {
            return $foo;
        },
    );
```
If I correct it like this :

```php
<?php

    array(
     'key1' => function($bar) {
            return $bar;
     },
     'key2' => function($foo) {
            return $foo;
     },
    );
```
I have a Generic.WhiteSpace.ScopeIndent.IncorrectExact error : Line indented incorrectly; expected 8 spaces, found 5

**Comment by gsherwood** [comment]
Thanks for reporting a new bug for this. I've fixed this issue now.

**Comment by keyermann** [comment]
thank you !
