### ISSUE TITLE
Can we have tokenizer for Less CSS ?

### ISSUE THREAD

**Issue by umakantp** [squizlabs/PHP_CodeSniffer#510]
Many projects these days have started using Less CSS in there projects. Same is the case with me. My CSS is generated from Less CSS and is compressed, hence cannot sniff it. Can we introduce a tokenizer for Less CSS or Do you it in roadmap already?

**Comment by aik099** [comment]
Same for SASS/SCSS I guess.

**Comment by Decave** [comment]
Has anyone started working on this?

**Comment by aik099** [comment]
I guess not.

**Comment by Decave** [comment]
Cool. Well this would obviously be a big feature (and if it turns out I do have time which I'm not 100% on quite yet, I'd likely only be able to add a less tokenizer), so I have a few questions:
1. It looks like all Tokenizers implement `tokenizeString` and (optionally) `processAdditional`. Do you guys think it would make sense to have these tokenizers extend an abstract class?
2.
```
        self::_createPositionMap($tokens, $tokenizer, $eolChar, $encoding, $tabWidth);
        self::_createTokenMap($tokens, $tokenizer, $eolChar);
        self::_createParenthesisNestingMap($tokens, $tokenizer, $eolChar);
        self::_createScopeMap($tokens, $tokenizer, $eolChar);
        self::_createLevelMap($tokens, $tokenizer, $eolChar);
```
it would be helpful if you guys could take me through what these static functions are doing. I could pour through them but I'd probably move a lot more quickly if I knew what to expect before digging too much.
3. I can't find any tests related to tokenizing. Have you guys tested tokenizing yet and if so where could I find examples of how to mimic? If not I would probably add a suite for that and test what would be `PHP_CodeSniffer_Tokenizers_Less` if you were okay with me doing so.
4. Anything else I should know? I have a rough idea of what I would need to do but if there are subtleties I would likely miss then please let me know.

**Comment by gsherwood** [comment]
> 1. It looks like all Tokenizers implement tokenizeString and (optionally) processAdditional. Do you guys think it would make sense to have these tokenizers extend an abstract class?

This is what I've done in the 3.0 branch (incomplete, but here: https://github.com/squizlabs/PHP_CodeSniffer/tree/3.0) along with a heap of other refactoring. I wont be making a similar change in the current 2.x branch though - it's too much of a BC break for external scripts.

> 2.
>         self::_createPositionMap($tokens, $tokenizer, $eolChar, $encoding, $tabWidth);
>         self::_createTokenMap($tokens, $tokenizer, $eolChar);
>         self::_createParenthesisNestingMap($tokens, $tokenizer, $eolChar);
>         self::_createScopeMap($tokens, $tokenizer, $eolChar);
>         self::_createLevelMap($tokens, $tokenizer, $eolChar);
> it would be helpful if you guys could take me through what these static functions are doing. I could pour through them but I'd probably move a lot more quickly if I knew what to expect before digging too much.

You don't need to worry about these functions as they do not vary between tokenizers. But what they do is go through an analyse the initial token list and match tokens together so you can find matching braces, column positions of tokens, nesting levels, the end of an IF statement etc. All the extra indexes in the main tokens array are generated by these methods.

> 3. I can't find any tests related to tokenizing. Have you guys tested tokenizing yet and if so where could I find examples of how to mimic? If not I would probably add a suite for that and test what would be PHP_CodeSniffer_Tokenizers_Less if you were okay with me doing so.

Tokenizing is not unit tested; it use integration tests via the sniffs. If there are ever tokenizing errors found, I put that code into a sniff unit test to ensure it produces an error there first.

If you create a LESS tokenizer, you're obviously going to create sniffs that make use of that tokenizer. If those sniffs are working for any LESS code you throw at it, then your tokenizer is working well enough. Treat it like a private function and don't test it directly.

If you are creating a LESS tokenizer to use outside of PHPCS, then PHPCS probably isn't the project to be contributing to. The tokenizers are very well tested through the sniffs, but they aren't designed to be stand-alone libraries.

> 4. Anything else I should know? I have a rough idea of what I would need to do but if there are subtleties I would likely miss then please let me know.

The first decisions to make is if you start with the PHP tokenizer and extend tat (like CSS does) or if you go for a character-by-character tokenizer (like JS does). I don't know LESS, so I can't make that call.

**Comment by Decave** [comment]
Hi everyone, I apologize, but I did not have time to work on this as I expected. Just wanted to let everyone know in case someone else was considering working on this and/or needs this feature.

**Comment by gsherwood** [comment]
Closing as I'm never going to have time to work on this. If someone wants to, please submit a PR for the 3.0 branch.
