### ISSUE TITLE
The "Generic.CodeAnalysis.EmptyStatement" sniff shouldn't care about "catch"

### ISSUE THREAD

**Issue by aik099** [squizlabs/PHP_CodeSniffer#514]
Before 9d391876d86615636786beb46117043d8c0169e8 commit the "catch" statement was handled differently: the warning with different code was used for it instead of an error.

That way people could mute that specific warning and enable `Squiz.Commenting.EmptyCatchComment` to require a comment inside empty `catch` statements. Right now to do this I need to extend the `Generic.CodeAnalysis.EmptyStatement` and remove registration for T_CATCH token.

**Comment by aik099** [comment]
Maybe we can just check for T_CATCH inside process method without changing the array in register to true/false form.

**Comment by aik099** [comment]
Ups, I've totally missed that now error codes are different for each statement. So I just can mute `Generic.CodeAnalysis.EmptyStatement.DetectedCATCH` and that's all.

**Comment by gsherwood** [comment]
Yep, that's the correct way to mute it. Saves people having to deal with the registration bit.

I'm assuming this is all fine for you now, so I'll close this. If there is something else, just let me know.

**Comment by aik099** [comment]
Everything is perfect, thanks.
