### ISSUE TITLE
Merge Symfony2 code standard into the core?

### ISSUE THREAD

**Issue by FractalizeR** [squizlabs/PHP_CodeSniffer#516]
I can see this [separate repository](https://github.com/escapestudios/Symfony2-coding-standard), containing Symfony2 code style rules.

But I think Symfony is so widely used these days, so this standard should be really in the core of the CodeSniffer. Otherwise, to enable it in a project involves some file copying/moving like mentioned [here](https://confluence.jetbrains.com/display/PhpStorm/PHP+Code+Sniffer+with+Symfony2+Coding+Standards+Integration+in+PhpStorm+-+Symfony+Development+using+PhpStorm)

**Comment by aik099** [comment]
In fact if you search for Symfony2 coding standard then you'll also see various repositories with that name, thrus not marked as forks of some central repository. Some of them even have own rules.

It would be great if on Symfony's website @fabpot can put a link to official standard and then we can merge it in here.

**Comment by fabpot** [comment]
I have no problems in creating a "master" repository under the Symfony organization to host this. Just tell me which code I need to import there and who can manage the repo.

**Comment by fonsecas72** [comment]
Doesn't symfony2 follow the PSR-2 rules?

**Comment by fonsecas72** [comment]
I  mean, are there any extra rules in addiction to PSR-2?

**Comment by aik099** [comment]
Yeah, there are few extra rules and https://github.com/FriendsOfPHP/PHP-CS-Fixer is there to specifically follow them.

**Comment by aik099** [comment]
For one the Symfony prefers Yoda conditions.

**Comment by fonsecas72** [comment]
@aik099 Thanks for remind me of this.
So, it seems to me that the S2 CS must include all rules from PSR-2 plus some of their own rules. Being so, this is only doable in the code-sniffer core so we can use the PSR-2 dependency. Or am I wrong?

**Comment by aik099** [comment]
As I said before there are plenty of repos out there that claim (at least based on repo name) to be a PHPCS standard that Symfony2 uses. I agree with @fabpot , that these 22 repository (see https://github.com/search?utf8=%E2%9C%93&q=Symfony2-coding-standard) authors needs to be contacted and we create some central repo with official standard and let them fork it instead.

**Comment by fonsecas72** [comment]
@aik099 most of those are all the same and none includes PSR-2 as they should. It seems that we would need to create another one.

**Comment by FractalizeR** [comment]
I am not sure Symfony will create their ruleset because they already have some tool to fix code style: http://cs.sensiolabs.org/
But we should [suggest](https://github.com/symfony/symfony/issues/13952) anyway.

**Comment by fonsecas72** [comment]
I have to say that this symfony2 CS repos are all pretty much are lacking much of the symfony2 rules (based on S2 docs). 
So, I don't any advantage (on the contrary) on use one them instead of the PSR-2.
If we want to have a real/good Symfony2 CS we will probably to create many code-sniffer rules. But 'till then, I would use PSR-2.

**Comment by gsherwood** [comment]
Once I put a standard into the core distribution, I take on the responsibility of maintaining it. This involves changing it when the written standard changes, and fixing bugs in any of the custom sniffs written for it.

I don't use symfony or have any need to adhere to that coding standard, so I'm not able to take responsibility for it. I'm closing this issue because I wont be merging that standard into PHP_CodeSniffer.

**Comment by xalopp** [comment]
@fonsecas72 may be like to check out https://github.com/xalopp/symfony-coding-standard 
your feedback would be nice.

**Comment by fonsecas72** [comment]
@xalopp which I see that earlier. That looks awesome. 
There are a few things missing and some bugs.
Would you be willing to improve this repo and maybe help-maintain the official symfony coding standard?
I can help with that :)

**Comment by xalopp** [comment]
@fonsecas72 feel free to open issues and send PRs :)

**Comment by fonsecas72** [comment]
Sure, @xalopp can you create a new repo?

**Comment by mmoll** [comment]
@fonsecas72 in theory that new repo could live in a personal GitHub account of i.e. @xalopp or the mayflower organisation, but it would IMHO be better to have this in the symfony organisation or if that's not possible in an own organsation, yet to be founded. What's your take on this?

**Comment by fonsecas72** [comment]
@mmoll I think it should go to the Symfony org as Fabien suggested. 
All the standards I've seen so far are missing some of the symfony rules:  http://symfony.com/doc/current/contributing/code/standards.html . So I started my own https://github.com/fonsecas72/coding-standard just to try to create the missing rules meanwhile.
But it doesn't matter to me which one will go to the symfony org. I'll contribute to another repo if I need to.
