### ISSUE TITLE
Generic.CodeAnalysis.UselessOverridingMethod picking up construct despite "default" change.

### ISSUE THREAD

**Issue by donatj** [squizlabs/PHP_CodeSniffer#519]
The following is picked up by `Generic.CodeAnalysis.UselessOverridingMethod` even though __construct is being overriden to change the default of `$exit_code`.

```php
<?php

namespace Controller\Exceptions;

class CliRuntimeException extends \RuntimeException implements CliExceptionInterface {

	use CliExceptionTrait;

	public function __construct( $message = "", $exit_code = 3, \Exception $previous = null ) {
		parent::__construct($message, $exit_code, $previous);
	}

}
```

**Comment by aik099** [comment]
The PHPCS doesn't analyze class structure and it can't get method declaration from parent class to detect, that method signature has changed.

**Comment by gsherwood** [comment]
Sorry it's taken me a while to get to this.

@aik099 is correct - PHPCS is not analysing an entire project (you often only run it on single files or directories anyway) and so it is not well suited to this kind of work. I accepted those sniffs as a contribution many years ago before other tools were available to do things like that, but I'd recommend not using any more.

There isn't anything I can do to fix this, so I'll close the issue.
