### ISSUE TITLE
Generic ScopeIndent errors for IF in FINALLY

### ISSUE THREAD

**Issue by mhujer** [squizlabs/PHP_CodeSniffer#523]
When I have an `if` in the `finally` branch, it fails with *Line indented incorrectly; expected 8 spaces, found 12* error:

```
        try {
            echo 'foo';
        } catch (\Exception $e) {
            echo 'catch';
        } finally {
            if (false) { // <--- Line indented incorrectly; expected 8 spaces, found 12
                echo 'finally false';
            }
        }
```

**Comment by aik099** [comment]
The `finally` isn't supported at all currently. I guess simple search for `T_TRY` token should reveal all places, where `T_FINALLY` needs to be added. Also a `T_FINALLY` constant needs needs to be added for cases, when it's not there (e.g. PHP 5.4 is used to analyze PHP 5.5 codebase).

**Comment by gsherwood** [comment]
This is fixed now. T_FINALLY wasn't recorded as a scope opener in the main core list of scope openers.

**Comment by mhujer** [comment]
Thanks :+1:
