### ISSUE TITLE
phar file custom standards

### ISSUE THREAD

**Issue by tahongawaka** [squizlabs/PHP_CodeSniffer#525]
"The easiest way to get started with PHP_CodeSniffer is to download the Phar files for each of the commands:"

Now, where do I put my custom standards so phpcs will find them? I'd rather not place a phpcs.xml in every directory in my project.

**Comment by aik099** [comment]
You need to specify absolute/relative path to your standard when running `phpcs`.

**Comment by gsherwood** [comment]
What @aik099 said.

`php phpcs.phar --standard=/path/to/MyStandard /path/to/code`

If you want PHPCS to recognise your standard as "installed", you can tell it where else to look using a config option: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options#setting-the-installed-standard-paths

Then you can just run `php phpcs.phar --standard=MyStandard /path/to/code`
