### ISSUE TITLE
Suggestion guide for migrating from PHP_CodeSniffer 1.5.x to 2.3.x

### ISSUE THREAD

**Issue by photodude** [squizlabs/PHP_CodeSniffer#533]
Would be great to see a Guide for migrating from PHP_CodeSniffer 1.5.x to 2.3.x covering deprecated or obsolete functions and formatting and needs to change to make a functional migration. 

joomla/coding-standards would be a great test case for showing off migrating from PHP_CodeSniffer 1.5.x to 2.3.x

**Comment by aik099** [comment]
There was a detailed blog post about that: https://www.squizlabs.com/php-codesniffer/2.0.0a1-released

**Comment by photodude** [comment]
@aik099 Thanks, I've been looking for something like that. 

I think that link needs to be added to the [WIKI FAQ](https://github.com/squizlabs/PHP_CodeSniffer/wiki/FAQ) to make that information much easier to find.

**Comment by aik099** [comment]
If you need any help with migrating your standard to 2.x version (e.g. adding fixing capabilities to custom sniffs or figuring out how to avoid using comment parser), then ask right away.

**Comment by photodude** [comment]
@aik099 Thanks your offer of help is greatly appreciated, I'll let you know if I run into trouble. But feel free to review and help with the changes photodude/coding-standards pushing to https://github.com/joomla/coding-standards/tree/phpcs-2. 

As I've gone through the blog post about the changes to PHPCS coding, I've found the majority of the links are unfortunately broken. I'm guessing the links changed as PHPCS-2 changed from alpha release to a production release. ![phpcs-issue](https://cloud.githubusercontent.com/assets/10253980/7071522/191bb904-dea3-11e4-8ba2-cb66ba5a4f46.PNG)

The big key changes I've found in the post was 
PHPCS-1 code | Change to___ for PHPCS-2 
------------ | -------------
T_DOC_COMMENT | T_DOC_COMMENT_OPEN_TAG
addError() | addFixableError()
addWarning() | addFixableWarning()

**Comment by aik099** [comment]
The "phpcs-fixer" branch is merged to "master" now, so just replace branch name in url. @gsherwood , maybe you can restore that branch to fix 404 links?

**Comment by aik099** [comment]
I've also reported some issues to standard in general: https://github.com/joomla/coding-standards/issues/created_by/aik099 . This is indirectly related to upgrading to PHPCS2 because it will reduce the amount of code, that needs to be changed.

**Comment by gsherwood** [comment]
> I've found the majority of the links are unfortunately broken.

Yes, that was a very old post and the branch is now gone. I've updated the post to point the links to their new locations.

If you need help migrating a standard, it's probably worth joining this chat room (instead of using Github issues) and asking in there: https://gitter.im/squizlabs/PHP_CodeSniffer

**Comment by photodude** [comment]
@gsherwood Thanks for the updates to the post. 

I would suggest adding to the WIKI (and/or the readme) a topic on *where can I get help / ask questions* and/or in the FAQ *If you need help, or have a question about, migrating a standard* with a link to the gitter chat room. I think it would help point people in the right direction.
