### ISSUE TITLE
Add sniff for new reserved words in PHP7

### ISSUE THREAD

**Issue by fabiang** [squizlabs/PHP_CodeSniffer#535]
PHP7 will reserve some keywords for class-, interface-, trait names and namespaces:

- [PHP RFC: Reserve More Types in PHP 7](https://wiki.php.net/rfc/reserve_more_types_in_php_7)
- [PHP RFC: Reserve Even More Types in PHP 7](https://wiki.php.net/rfc/reserve_even_more_types_in_php_7)

Would be a nice feature if phpcs could have a sniff for those keywords

**Comment by GordonSchmidt** [comment]
+1

**Comment by aik099** [comment]
I recommend using http://php5.laurent-laville.org/compatinfo/ instead. It's a library designed to detect if a PHP code is compatible with any given PHP version. It can detect code, that would pass php linting, but would end up in parse/fatal error when executed. For example shorthand ternary operators (e.g. `$a ?: 'default`) would fail on PHP 5.2.

**Comment by aik099** [comment]
And before PHP 7 is released the PHP tokenizer won't recognize these words as new tokens, which would require changing PHP_CodeSniffer own tokenizer to analyze every string, it's context to determine if is what would be a token in PHP 7 or just a false positive.

**Comment by gsherwood** [comment]
I'm 100% confident I wont get time to do this before the PHP7 release or even slightly after it. But I also don't think this is the kind of thing that should be included within PHP_CodeSniffer itself. PHPCS is a good tool to be able to check for these sort of compat issues, but the included sniffs are all about coding style.

There are other standards available that help people move to other PHP versions, so I suggest helping them get their compat standards updated for PHP7. The one I've been most involved with (purely from testing) is this one: https://github.com/wimg/PHPCompatibility

**Comment by fabiang** [comment]
Ok, I'll open an issue at both projects.
