### ISSUE TITLE
PHP7 Removal of Depreciated Functions

### ISSUE THREAD

**Issue by PatrickRose** [squizlabs/PHP_CodeSniffer#536]
Similar to #535 - will PHPCS have a bunch of sniffs for the [removed functions](https://wiki.php.net/rfc/remove_deprecated_functionality_in_php7) before PHP7 is released?

Happy to do a PR if wanted - but if there's a plan for a lot of "Pre-PHP7" sniffs then I'd like to add it there.

**Comment by aik099** [comment]
I guess the answer here would similar to mentioned task :wink:

**Comment by PatrickRose** [comment]
Ah - but in this instance PHPCS can actually do something without too much work (see the ForbiddenFunctions sniff) and whether it'd be worth making it part of the core.

**Comment by gsherwood** [comment]
See my comment here: https://github.com/squizlabs/PHP_CodeSniffer/issues/535#issuecomment-90867705

Summary: I don't think this belongs in PHPCS. But there are other projects you can help out that are doing this.
