### ISSUE TITLE
SWITCH with closure in condition generates inline control structure error

### ISSUE THREAD

**Issue by tremby** [squizlabs/PHP_CodeSniffer#543]
With this file:

```php
<?php
namespace Acme;

class Foo
{

    public function bar()
    {
        switch($response = \Bar::baz('bat', function ($foo) {
            return 'bar';
        })) {
            case 1:
                return 'test';

            case 2:
                return 'other';
        }
    }
}
```

I get "Expected 0 spaces before opening parethesis; 1 found", on line 9 (the switch).

If I remove that space before the opening parenthesis (there's only one with a space before it) I then get "Expected 1 space after FUNCTION keyword; 0 found".

**Comment by gsherwood** [comment]
The master branch already has a fix for this, but your code found another error where the switch was seen as an inline control structure (only in the master branch). I've now fixed this error, so this code will no longer generate any PSR2 errors from the next release.

**Comment by tremby** [comment]
Great, thanks!
