### ISSUE TITLE
Long list of CASE statements can cause tokenizer to reach a depth limit

### ISSUE THREAD

**Issue by sebastianbergmann** [squizlabs/PHP_CodeSniffer#545]
Please consider making https://github.com/squizlabs/PHP_CodeSniffer/blob/33306db75b8dbedec4bc8c8914ead8ce1a1895f0/CodeSniffer/File.php#L2128 configurable.

**Comment by aik099** [comment]
Do you have the file, that isn't fixed at 100% with current depth?

**Comment by sebastianbergmann** [comment]
Yes: https://github.com/sebastianbergmann/php-code-coverage/blob/master/src/CodeCoverage/Report/HTML/Renderer/File.php

**Comment by gsherwood** [comment]
Instead of making this configurable, I'll change PHPCS to understand that these CASE statements do not need to take depth into account because they are not truly nested.

**Comment by gsherwood** [comment]
Fix has been added.
