### ISSUE TITLE
Generic.Files.LineLength.TooLong counts bytes instead of characters

### ISSUE THREAD

**Issue by Gisleburt** [squizlabs/PHP_CodeSniffer#549]
`Generic.Files.LineLength.TooLong` counts bytes instead of characters (obviously this is common issue in PHP).

```
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 22 | WARNING | Line exceeds 120 characters; contains 135 characters
----------------------------------------------------------------------
```

The line in question is 72 characters long but includes a load of 2 byte characters as shown below.

```php 
trait File
{

    protected function cleanFilename($filename)
    {

        // ...
        $filename = strtr(
            $filename,
            'ŠŽšžŸÀÁÂÃÄÅÇÈÉÊËÌÍÎÏÑÒÓÔÕÖØÙÚÛÜÝàáâãäåçèéêëìíîïñòóôõöøùúûüýÿ',
            'SZszYAAAAAACEEEEIIIINOOOOOOUUUUYaaaaaaceeeeiiiinoooooouuuuyy'
        );
        // ...
}
```

**Comment by aik099** [comment]
This can happen in 2 cases:

* you haven't specified charset, when invoking `phpcs`
* the `iconv` PHP extension isn't installed and therefore `strlen` is used instead of dedicated iconv function

**Comment by Gisleburt** [comment]
Right you are! This made my problem go away:

```bash
    $ bin/phpcs --config-set encoding utf-8
    Config value "encoding" added successfully
    $ bin/phpcs
```

Is there a way to suggest that in phpcs.xml so that when I move it on to my build machine I don't have to worry about that? It would seem like it is a property of the project rather than of the tool (if that makes sense).

**Comment by aik099** [comment]
Since PHP_CodeSniffer 2.0 it's possible to specify charset in `ruleset.xml` of your standard. This is how I've done it: https://github.com/aik099/CodingStandard/blob/master/CodingStandard/ruleset.xml#L6

**Comment by Gisleburt** [comment]
Ah, and a great example of other bits too. I wonder why I wasn't able to find that myself. Bad Google Fox I guess. :) 

Thank you.

**Comment by aik099** [comment]
Searching for `phpcs ruleset.xml` resulted in this official article: https://pear.php.net/manual/en/package.php.php-codesniffer.annotated-ruleset.php

**Comment by Gisleburt** [comment]
Which doesn't mention encoding or arguments ;)

**Comment by gsherwood** [comment]
> Searching for phpcs ruleset.xml resulted in this official article: https://pear.php.net/manual/en/package.php.php-codesniffer.annotated-ruleset.php

That's a very old PEAR doc, which I wish I could remove, but can't seem to.

All the docs are on the Github wiki, including the replacement for that page: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-ruleset.xml
