### ISSUE TITLE
Multiple catch blocks not checked in Squiz.ControlStructures.ControlSignature sniff

### ISSUE THREAD

**Issue by fbourigault** [squizlabs/PHP_CodeSniffer#551]
In PSR2, multiple catches block must be like this:

```php
<?php
try {
    // try body
} catch (FirstExceptionType $e) {
    // catch body
} catch (OtherExceptionType $e) {
    // catch body
}
```

but `phpcs --standard-PSR2` is ok with the following code:

```php
<?php
try {
    // try body
} catch (FirstExceptionType $e) {
    // catch body
}
catch (OtherExceptionType $e) {
    // catch body
}
```

Bug is present in `2.3.0` and `master`

**Comment by aik099** [comment]
Appears like `catch` statement formatting isn't checked at all. Can you please post a link in the PSR-2 specification where it describes how `catch` should be formatted?

**Comment by fbourigault** [comment]
When you run `phpcs --standard=PSR2` against the following code, it throw this error: `Expected 1 space after closing brace; newline found`

```php
<?php
try {
    // try body
}
catch (FirstExceptionType $e) {
    // catch body
}
```

PSR2 about `try, catch` : https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#56-try-catch

**Comment by aik099** [comment]
I see. The subsequential `catch` statements are ignored then.

**Comment by gsherwood** [comment]
Thanks for reporting this. It has been fixed now.
