### ISSUE TITLE
Invalid detection of boolean operators in PEAR.ControlStructures.MultiLineCondition

### ISSUE THREAD

**Issue by Konafets** [squizlabs/PHP_CodeSniffer#552]
The code example raise the error below

```
if (($tokens[$commentBeforeCase]['line'])
    !== ($tokens[$afterNextCase]['line'] - 1)
) {
...
}
```

```
Each line in a multi-line IF statement must begin with a boolean operator
(PEAR.ControlStructures.MultiLineCondition.StartWithBoolean)
```

I found the reason inside ```CodeSniffer/Tokens.php``` where I added ```T_IS_NOT_IDENTICAL``` and ```T_IS_IDENTICAL```.
```
    /**
     * Tokens that perform boolean operations.
     *
     * @var array(int)
     */
    public static $booleanOperators = array(
                                       T_BOOLEAN_AND         => T_BOOLEAN_AND,
                                       T_BOOLEAN_OR          => T_BOOLEAN_OR, 
                                       T_LOGICAL_AND         => T_LOGICAL_AND, 
                                       T_LOGICAL_OR          => T_LOGICAL_OR,
                                       T_LOGICAL_XOR         => T_LOGICAL_XOR,
                                       T_IS_NOT_IDENTICAL    => T_IS_NOT_IDENTICAL,
                                       T_IS_IDENTICAL        => T_IS_IDENTICAL,
                                      );
```

Is this behavior intended?  Could this be the solution? What is with the ```T_IS_NOT_EQUAL```, ```T_IS_GREATER_OR_EQUAL``` and ```T_IS_SMALLER_OR_EQUAL```.

**Comment by aik099** [comment]
I think, that there are equality tokens array where these 2 are listed.

**Comment by Konafets** [comment]
Yes the ```$equalityTokens``` array does that.

**Comment by aik099** [comment]
The code, that this sniff wants to see is:

```php
if (($tokens[$commentBeforeCase]['line']) !== ($tokens[$afterNextCase]['line'] - 1) ) {
...
}
```

or

```php
if ( $condition1
    && $condition2
) {
...
}

**Comment by Konafets** [comment]
I am aware of this but what you do when the CGL puts a limit to the line length ;-)

**Comment by gsherwood** [comment]
> I am aware of this but what you do when the CGL puts a limit to the line length ;-)

Either ignore the line length limit, or use variable assignment:
```php
$commentLine = $tokens[$commentBeforeCase]['line'];
$caseLine = ($tokens[$afterNextCase]['line'] - 1);
if ($commentLine !==  $caseLine) {
...
}
```
Personally, I just ignore the line length error in this case because I don't feel that the alternative code is actually more readable. If the line was incredibly long, then maybe.

But back to the original issue: I think you've already worked this out between yourselves, but the sniff is looking for boolean operators to start the line and not comparison operators.
