### ISSUE TITLE
Setting different ruleset relative include paths

### ISSUE THREAD

**Issue by rarila** [squizlabs/PHP_CodeSniffer#557]
Hello,
I'm in the situation that I have made a standard that is based on another standard and can be either installed with composer as dependency of a repository or cloned as standalone. So we end up either with a file structure like this

```
repository
repository/vendor/me/standard-a
repository/vendor/other/standard-b
```

or as standalone like this

```
me/standard-a
me/vendor/other/standard-b
```

We now simply call them with: `phpcs --standard=/path/to/standard-a`

Problem is that the first install needs

``` xml
<rule ref="../../other/standard-b">
```

and the second one

``` xml
<rule ref="../vendor/other/standard-b">
```

to get the base standard included.

`installed_paths` seems to need either absolute paths or relative ones are not based based to the main standard. Using two redundant witch just that line differing doesn't seem to be a good idea to me. So I have either overseen something and will be happy if someone will point me to it or it simply isn't possible to do at the moment.

If so I would like to suggest adding something like this to `ruleset.xml`

``` xml
<include path="../../other"/>
<include path="../vendor/other"/>
<rule ref="standard-b">
```

or 

``` xml
<include-path>../../other</include-path>
<include-path>../vendor/other</include-path>
<rule ref="standard-b">
```

The path should either be an absolute one or be handled relative to the `ruleset.xml` it is in.

**Comment by gsherwood** [comment]
This can't be done cleanly right now. Although I don't think putting relative include paths in a ruleset is clean either. This is one of those composer problems that can make life hard.

For now, you're probably better off running with 3 ruleset files; one for when the repo is cloned, one for when the repo is a dep, and one which holds all the common rules.

For example, a `ruleset.xml` file:
```xml
<?xml version="1.0"?>
<ruleset name="MyStandard">
    <description>My custom coding standard, for cloned installs</description>
    <rule ref="./common.xml">
    <rule ref="../vendor/other/standard-b">
</ruleset>
```

And a `composer-ruleset.xml` file:
```xml
<?xml version="1.0"?>
<ruleset name="MyStandard">
    <description>My custom coding standard, for composer installs</description>
    <rule ref="./common.xml">
    <rule ref="../../other/standard-b">
</ruleset>
```

And a `common.xml` file:
```xml
<?xml version="1.0"?>
<ruleset name="MyStandard (common)">
    <description>The common parts of my custom coding standard</description>
    <!-- Common rules and overrides here -->
</ruleset>
```

It's not great, but it's pretty much all there is if you don't want to hard code the `installed_paths`. I'll have a think more about a clean way to do this, but it will probably only be available in the 3.0 version, and have something to do with namespaces and composer autoloading.

**Comment by rarila** [comment]
Thank you very much for your detailed answer. I will try the multifile approach for now and hope you'll find a proper way to implement this in the future. Two files less to take care of is always good. Thanks!

**Comment by gsherwood** [comment]
Closing as I have not had time to come up with a solution and I haven't had any more requests for one.
