### ISSUE TITLE
PEAR.Commenting.ClassComment.Missing fails when it's the first comment in a file.

### ISSUE THREAD

**Issue by Celc** [squizlabs/PHP_CodeSniffer#561]
I tried disabling the file comment requirement, which works fine but class comment requirement gets confused:

````xml
<?xml version="1.0"?>
<ruleset name="patontheback">
    <file>example.php</file>
    <rule ref="PEAR.Commenting.ClassComment.Missing" />
</ruleset>
````
On

````php
<?php
/**
 * Class Test
 */
class Test
{

}
````

Fails.

**Comment by gsherwood** [comment]
That sniff assumes that a file with a class in it will always have a file comment and a class comment. It does this because the PEAR coding standard enforces both comments. If you don't want this, you can't use that sniff.
