### ISSUE TITLE
Phar class fatals in PHP < 5.3

### ISSUE THREAD

**Issue by Rarst** [squizlabs/PHP_CodeSniffer#570]
2.3.1 started to fatal in Travis/PHP 5.2 environment:

> Fatal error: Class 'Phar' not found in /tmp/wordpress/src/wp-content/plugins/wordpress-seo/vendor/squizlabs/php_codesniffer/CodeSniffer.php on line 2363

Since Phar is optional extension before PHP 5.3, it probably shouldn't be called unconditionally.

**Comment by aik099** [comment]
Related issue: #537

**Comment by gsherwood** [comment]
You are right. I don't want the Phar PECL package to be a requirement in the 2.x version, so I've committed a fix for this. I'll do a release soon.
