### ISSUE TITLE
UnusedFunctionParameterSniff conflicts with Interfaces

### ISSUE THREAD

**Issue by Floyd25** [squizlabs/PHP_CodeSniffer#573]
I'm often running into the same problem with this sniff when implementing interfaces with symfony for example:

public function buildForm(FormBuilderInterface $builder, array $options)

To fulfill the interface I have to include $options in the signature of method buildForm. But what if $options is never used inside my implementation? I feel that deleting $options from the method signature would break the interface. What's the best practice here? Should the sniff check against the interface or should I delete the unused parameter?

**Comment by aik099** [comment]
> I feel that deleting $options from the method signature would break the interface.
> or should I delete the unused parameter?
It will result in the error.

> What's the best practice here?

I personally don't use this sniff, but instead use PHP Mess Detector rule, that does the same.

> Should the sniff check against the interface

It's impossible, because PHP_CodeSniffer analyzer project file-by-file and doesn't know where each class/interface is detected.

**Comment by Floyd25** [comment]
Thanks for the quick reply. Could you please tell me the PHPMD Rule that you use instead?

**Comment by aik099** [comment]
Sure: `UnusedFormalParameter` (http://phpmd.org/rules/unusedcode.html#unusedformalparameter).

**Comment by Floyd25** [comment]
It looks like PHPMD has the same problem: https://github.com/phpmd/phpmd/issues/180

**Comment by gsherwood** [comment]
I'll close this because PHPCS processes file independently, so it's not the right tool for this kind of job. I probably should have never accepted those code analysis sniffs, but it was a very long time ago. I'm going to consider removing them in 3.0 though, because I don't think they are useful for today's PHP code.
