### ISSUE TITLE
PSR1 shows 6 dots

### ISSUE THREAD

**Issue by ilhanyumer** [squizlabs/PHP_CodeSniffer#574]
![......](http://i.imgur.com/CUxXJfD.png)

Instead of a result it prints dots.

**Comment by aik099** [comment]
Maybe you have default reporting type set to dots? Try adding `--report=full` to your command.

**Comment by aik099** [comment]
Also, when no error/warning are found, then report looks like you've shown :)

**Comment by ilhanyumer** [comment]
> Also, when no error/warning are found, then report looks like you've shown :)

Thanks.

**Comment by aik099** [comment]
Feel free to close the issue if my answer helped you solve it :wink:

**Comment by gsherwood** [comment]
Just to clarify what the dots are: you have the `show progress` setting on. Each dot is a file that is being checked and no errors or warnings were found. Read about that setting here: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Usage#printing-progress-information

The fact that you have not put `-p` on the command line probably means that you've set the `show_progress` config var. You can use `phpcs.bat --config-show` to see the values that have been set. The section of the wiki I linked to has a link in there to the docs about that config option.
