### ISSUE TITLE
Non-standard use case question

### ISSUE THREAD

**Issue by ghost1227** [squizlabs/PHP_CodeSniffer#576]
Is it possible to run phpcs from inside another PHP script? IE, could a web-based version be written?

**Comment by gsherwood** [comment]
Yes, it is possible to put a wrapper around PHPCS, although I think it is easier with the 3.0 branch as I've refactored everything to break away from the PEAR way of doing things.

But I have no documentation for using PHPCS like this, so you'd need to start at scripts/phpcs (or bin/phpcs in 3.0) and follow the code from there.

**Comment by aik099** [comment]
Questions can be asked on Gitter channel as well: https://gitter.im/squizlabs/PHP_CodeSniffer .
