### ISSUE TITLE
phpcs could hangs on invalid php code

### ISSUE THREAD

**Issue by sormy** [squizlabs/PHP_CodeSniffer#580]
In some conditions phpcs could hang and eat 100% cpu and never exit.

General topic is here: https://github.com/SublimeLinter/SublimeLinter-php/issues/12

Environment: 
- Mac OS X 10.10
- PHP_CodeSniffer version 2.3.0 (stable) by Squiz (http://www.squiz.net)
- PHP 5.6.7 (cli) (built: Apr 24 2015 15:49:52) 

Killing code:
```php
<?php

class PhpCsHang
{
    private function magicMethod()
    {
        $this->service1->doIt(
            $this->service2-"patient_last_name"),
            $this->service2-"patient_first_name"),
            $this->service2-"patient_middle_name")
        );
    }
}
```

warnings:
```
PHP Notice:  Undefined index:  in /usr/local/Cellar/php-code-sniffer/2.3.0/CodeSniffer/File.php on line 3411
PHP Stack trace:
PHP   1. {main}() /usr/local/Cellar/php-code-sniffer/2.3.0/scripts/phpcs:0
PHP   2. PHP_CodeSniffer_CLI->runphpcs() /usr/local/Cellar/php-code-sniffer/2.3.0/scripts/phpcs:25
PHP   3. PHP_CodeSniffer_CLI->process() /usr/local/Cellar/php-code-sniffer/2.3.0/CodeSniffer/CLI.php:95
PHP   4. PHP_CodeSniffer->processFiles() /usr/local/Cellar/php-code-sniffer/2.3.0/CodeSniffer/CLI.php:867
PHP   5. PHP_CodeSniffer->processFile() /usr/local/Cellar/php-code-sniffer/2.3.0/CodeSniffer.php:619
PHP   6. PHP_CodeSniffer->_processFile() /usr/local/Cellar/php-code-sniffer/2.3.0/CodeSniffer.php:1679
PHP   7. PHP_CodeSniffer_File->start() /usr/local/Cellar/php-code-sniffer/2.3.0/CodeSniffer.php:1801
PHP   8. Generic_Sniffs_WhiteSpace_ScopeIndentSniff->process() /usr/local/Cellar/php-code-sniffer/2.3.0/CodeSniffer/File.php:567
PHP   9. PHP_CodeSniffer_File->findFirstOnLine() /usr/local/Cellar/php-code-sniffer/2.3.0/CodeSniffer/Standards/Generic/Sniffs/WhiteSpace/ScopeIndentSniff.php:219
```
and
```
PHP Notice:  Undefined index:  in /usr/local/Cellar/php-code-sniffer/2.3.0/CodeSniffer/File.php on line 3423
PHP Stack trace:
PHP   1. {main}() /usr/local/Cellar/php-code-sniffer/2.3.0/scripts/phpcs:0
PHP   2. PHP_CodeSniffer_CLI->runphpcs() /usr/local/Cellar/php-code-sniffer/2.3.0/scripts/phpcs:25
PHP   3. PHP_CodeSniffer_CLI->process() /usr/local/Cellar/php-code-sniffer/2.3.0/CodeSniffer/CLI.php:95
PHP   4. PHP_CodeSniffer->processFiles() /usr/local/Cellar/php-code-sniffer/2.3.0/CodeSniffer/CLI.php:867
PHP   5. PHP_CodeSniffer->processFile() /usr/local/Cellar/php-code-sniffer/2.3.0/CodeSniffer.php:619
PHP   6. PHP_CodeSniffer->_processFile() /usr/local/Cellar/php-code-sniffer/2.3.0/CodeSniffer.php:1679
PHP   7. PHP_CodeSniffer_File->start() /usr/local/Cellar/php-code-sniffer/2.3.0/CodeSniffer.php:1801
PHP   8. Generic_Sniffs_WhiteSpace_ScopeIndentSniff->process() /usr/local/Cellar/php-code-sniffer/2.3.0/CodeSniffer/File.php:567
PHP   9. PHP_CodeSniffer_File->findFirstOnLine() /usr/local/Cellar/php-code-sniffer/2.3.0/CodeSniffer/Standards/Generic/Sniffs/WhiteSpace/ScopeIndentSniff.php:219
```

and stupid workaround:
```php
    public function findFirstOnLine($types, $start, $exclude=false, $value=null)
    {
        if (is_array($types) === false) {
            $types = array($types);
        }

        $foundToken = false;

        if ($start === "" || $start === null) {
            throw new \UnexpectedValueException("Died to save your money on electricity bill =)");
        }

        for ($i = $start; $i >= 0; $i--) {
            if ($this->_tokens[$i]['line'] < $this->_tokens[$start]['line']) {
                break;
            }
            ...
        }
        ...
    }
```

**Comment by aik099** [comment]
Does it work in 2.3.2 or master branch?

**Comment by sormy** [comment]
just upgraded, phpcs v2.3.2 is not affected

**Comment by aik099** [comment]
Then I guess it was fixed.

**Comment by sormy** [comment]
Yes, i think it could be closed.

But one of possible fixes for future bugs is to prevent code style checking if `php -l` do not see that code is valid. A lot of IDEs running phpcs in background when you type in IDE so sometime code became invalid because it's incomplete and it cause delays in phpcs and hangs in IDE (phpcs v2.3.0)

**Comment by Konafets** [comment]
But the IDE (like PHPStorm) shows you syntax errors. Actually the PHPCS is running constantly while you typing and most of the time the syntax is invalid. I never had any problems with that.

**Comment by sormy** [comment]
Actually phpcs v2.3.0 + sublime 3.x + sublimelinter-php plugin converts my macbook pro into heater =)

**Comment by sormy** [comment]
Ok, it seems like there are a lot of conditions when phpcs could hangs.
The best way is to find all of them and fix. But the quick fix is to prevent code sniffer to work if `php -l` see that php code is invalid.

this easy sample makes phpcs burn your cpu:
```
<?php
foreach
```

If you will type not enough fast in IDE there is a change that background process will get intermediate result with incomplete foreach statement and will hang

PHP_CodeSniffer version 2.3.2 (stable) by Squiz (http://www.squiz.net)
PHP 5.6.7 (cli) (built: Apr 24 2015 15:49:52)

**Comment by gsherwood** [comment]
You should probably submit a bug to your IDE's creator so that it stops running code checking tools in the background if it finds a parse error.

The tokenizer has enough guard code in it that it shouldn't get hung up on syntax errors, but some of the sniffs are not as good. I'll fix the ones I can find with the invalid control structure syntax, but I'm not at a point where I want to run a syntax check on every file before checking. I shouldn't need to do that because the sniffs should be good enough to deal with errors.

**Comment by gsherwood** [comment]
I've fixed all the sniffs I could find for the code provided. If you find more, submit more and I'll fix whatever sniffs are breaking.

**Comment by sormy** [comment]
What do you think about "convert all warnings and notices into exceptions" on phpcs level?

**Comment by gsherwood** [comment]
> What do you think about "convert all warnings and notices into exceptions" on phpcs level?

That's an interesting idea. I'll take a look into doing that in PHPCS version 3 (currently in development on the 3.0 branch).

**Comment by gsherwood** [comment]
Committed the error handler change here: https://github.com/squizlabs/PHP_CodeSniffer/commit/fbda38faf9ae23a271481150bf8db80f89e54e23

**Comment by sormy** [comment]
Neverending bug. Another sample how to burn cpu with phpcs. Now without any warnings/notices.
```php
<?php

class Test
{
    public function burn()
    {
        foreach

        switch ($anything) {
        }
    }
}
```

BTW, I'm still thinking that `php -l <file>` is the fastest, easiest and 100% solution for that problem.

**Comment by gsherwood** [comment]
Fixed that new issue here: https://github.com/squizlabs/PHP_CodeSniffer/commit/9d4b31143ff1164c9bdc77255e6934ad7516532d
