### ISSUE TITLE
Add support for phpcs.xml.dist files

### ISSUE THREAD

**Issue by ofbeaton** [squizlabs/PHP_CodeSniffer#583]
This is a feature request. It is similar to https://github.com/squizlabs/PHP_CodeSniffer/issues/465 however I felt that it was narrow enough that it could be implemented much quicker.

I would like phpcs to pick up a phpcs.xml.dist file if present, but prefer to use the phpcs.xml file if present. This would mimic other PHP phar's that use .xml files for default configuration, like phpunit.

This would allow the phpcs.xml.dist file to be checked in your CVS, while an individual team member could create their own phpcs.xml file to override it. But they would not be required to.

Interestingly this just burned me hard, where I checked out a new project with a "phpcs.xml.dist" file but forgot to copy it to "phpcs.xml". I then ran "phpcs", and it seemed to just hang. Devoid of any parameters, it just sat there doing nothing, providing no output. I spent a good half hour trying to figure it out until I realized what the problem was.

Btw, I love the new code fixer (phpfcb), though I wish it's name wasn't so similar to the "phpcb" phar for Code Browser that is also often used along with Code Sniffer.

**Comment by gsherwood** [comment]
I've added this feature now. As you've said, `phpcs.xml` is preferred over `phpcs.xml.dist`.

**Comment by ofbeaton** [comment]
Thank you! Very welcome change.

**Comment by pfrenssen** [comment]
Great! thanks a lot!

**Comment by alexpott** [comment]
Thanks we're just incorporating phpcs into Drupal's continuous integration.

**Comment by kminh** [comment]
Is this feature still working? I'm having only `phpcs.xml.dist` (no `phpcs.xml`) and running `phpcs` does not seem to take into account its contents. Renaming `phpcs.xml.dist` to `phpcs.xml` works though.

I'm installing `phpcs` globally using composer, and is currently using version 2.3.4.

**Comment by gsherwood** [comment]
@kminh Not from a PHP_CodeSniffer point-of-view. If the feature exists in a newer PHPCS version, you need to upgrade to use it.

I'd recommend speaking to the maintain of the PHPCompatibility standard and asking if they support the latest PHPCS version. I have no idea what specifically would be stopping that.

**Comment by pfrenssen** [comment]
@kminh it seems like they just need to update the composer.json file. Can you check if https://github.com/wimg/PHPCompatibility/pull/106 solves it for you? I haven't tested it but I don't see why it shouldn't work. At first glance it doesn't seem that anything added in PHP_CodeSniffer 2.5.0 would break it.

**Comment by kminh** [comment]
@pfrenssen thank you for creating the pull request. I might simply fork PHPCompatibility if your pull request is not merged.
