### ISSUE TITLE
Inherit only specific errors from sniff in rulset

### ISSUE THREAD

**Issue by JDGrimes** [squizlabs/PHP_CodeSniffer#586]
Is it possible to inherit only specific errors from a rule in a ruleset? I know that it is possible to inherit the entire rule and exclude certain errors, like this:

```xml
	<rule ref="Squiz.Arrays.ArrayDeclaration">
		<exclude name="Squiz.Arrays.ArrayDeclaration.SingleLineNotAllowed" />
	</rule>
```

But what if you wanted to include this, and only inherit that single error? This doesn't work:

```xml
	<rule ref="Squiz.Arrays.ArrayDeclaration.SingleLineNotAllowed" />
```

The use-case here is better forward-compatibility if more errors are added to the sniff being included.

**Comment by aik099** [comment]
If you're using core sniffs in your custom ruleset, then it's perfectly normal to expect BC break in major PHPCS version releases. Even if added these new checks can prove useful.

**Comment by gsherwood** [comment]
This isn't currently possible, but it's already on my todo list.

**Comment by GaryJones** [comment]
> If you're using core sniffs in your custom ruleset, then it's perfectly normal to expect BC break in major PHPCS version releases.

The use case here is where:

* WordPress Core ruleset says to include a rule (that has errors a, b, c and d), but excludes certain checks (b and d).
* PHPCS updates to a new version, and adds checks e and f.
* If e and f aren't compatible with the desired WP coding standards, then there will be incorrect errors reported.

By being able to whitelist which checks we want (a and c), then PHPCS can add whatever new checks it likes, and it won't affect the WPCS results.

**Comment by gsherwood** [comment]
I've added support for this feature now, and a couple of related ones. Here are some code examples from the commit message:

Import the Squiz standard but set all Squiz sniffs to warnings:
```xml
<rule ref="Squiz">
    <type>warning</type>
</rule>
```
Turn off all errors in the Squiz Array sniff category:
```xml
<rule ref="Squiz.Arrays">
    <severity>0</severity>
</rule>
```
Include one error message from the Squiz ArrayDeclaration sniff:
```xml
<rule ref="Squiz.Arrays.ArrayDeclaration.SingleLineNotAllowed" />
```
Import all Squiz Array sniffs as warnings, but turn off all ArrayDeclaration errors, except for one:
```xml
<rule ref="Squiz.Arrays">
    <type>warning</type>
</rule>
<rule ref="Squiz.Arrays.ArrayDeclaration">
    <severity>0</severity>
</rule>
<rule ref="Squiz.Arrays.ArrayDeclaration.SingleLineNotAllowed" />
```
