### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by kaystrobach** [squizlabs/PHP_CodeSniffer#591]
Please add the following links to the Documentation.

These links point to the install instructions for the external parsers and linters.

# CSS Lint
* Source: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options#setting-the-path-to-csslint
* Link to be added: https://github.com/CSSLint/csslint/wiki/Command-line-interface

# JSHint

* Source: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options#setting-the-path-to-jshint
* Link to be added: http://jshint.com/install/

# JavaScript Lint

* Source: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options#setting-the-path-to-javascript-lint
* Link to be added: http://www.javascriptlint.com/download.htm

**Comment by aik099** [comment]
I have doubts that sniffs that just execute other programs are really useful. I personally configure a build script, that invokes above tools and also PHP_CodeSniffer and then aggregate their report results on Jenkins page.

**Comment by kaystrobach** [comment]
but due to the documentation it is possible and the docs do not contain the links ... and it took some time to find the download uris ;)

**Comment by aik099** [comment]
From that point of view, yes you're correct.

**Comment by kaystrobach** [comment]
i do not have the right to edit the wiki, so please just add them ;)

**Comment by aik099** [comment]
Me neither, so we'll just wait for @gsherwood to do this if he agrees with you.

**Comment by gsherwood** [comment]
I don't want to deep link to various install and download guides because these could change in the future and I wont know about them.

But also, all of the projects I link to have install guides linked directly from their front project pages. If you had trouble finding them, it might be worth talking to the projects directly and asking them to revise their site.
