### ISSUE TITLE
What is the easiest way of testing custom coding standard

### ISSUE THREAD

**Issue by loonies** [squizlabs/PHP_CodeSniffer#596]
Is there any easy way of running tests for custom coding standard sniffs, without running tests for all standards? I've found couple of approaches:

 - symlinking custom standard to the PHPCS vendor directory where coding standards are defined
 - copying base test classes from PHPCS vendor source to the custom standards source directory and modifying them

Both of those approaches feel cumbersome.
 
What I'm really after is writing sniff tests extending `AbstractSniffUnitTest` class and running tests with something like `phpunit --standard=MyStandard src/MyStandard`.

The [Coding Standard Tutorial](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Coding-Standard-Tutorial) page describes how to write and use custom sniffs, but does not explain how to write and run sniff tests.

**Comment by gsherwood** [comment]
You can set the `installed_paths` config option to point to where you custom standard lives: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options#setting-the-installed-standard-paths

Then when you run phpunit, PHPCS will test all included standards, and your custom standard. You can use phpunit filtering to just run your own: `phpunit --filter [YOUR STANDARD NAME]`

**Comment by loonies** [comment]
I've added `installed_paths` as suggested, and tried to run tests with:

~~~
./vendor/bin/phpunit --testdox vendor/squizlabs/php_codesniffer/tests/AllTests.php
~~~

I got the `PHP Fatal error:  Cannot redeclare class MyStandard\Tests\Classes\FooUnitTest` error.

I'm pretty sure there is only one "FooUnitTest" class definition (`ag --php FooUnitTest`), so I tried to change `CodeSniffer::autoload` [include L282](https://github.com/squizlabs/PHP_CodeSniffer/blob/2.3.2/CodeSniffer.php#L282) and [include L289](https://github.com/squizlabs/PHP_CodeSniffer/blob/2.3.2/CodeSniffer.php#L289) to `include_once`, but I'm getting this error:

~~~
PHP Fatal error:  Uncaught PHPUnit_Framework_Exception: Argument #1 (No Value) of PHPUnit_Framework_TestSuite::addTestSuite() must be a class name or object

vendor/squizlabs/php_codesniffer/tests/Standards/AllSniffs.php:118
vendor/squizlabs/php_codesniffer/tests/AllTests.php:77

vendor/phpunit/phpunit/src/Util/InvalidArgumentHelper.php on line 35
~~~

Any idea? ATM I'm not sure what is going on, I'll have to dig further.

**Comment by aik099** [comment]
The namespaces in sniff classes are not supported until PHP_CodeSniffer 3.0.

**Comment by loonies** [comment]
I'm pretty sure that I ran those namespaced tests before, since I wrote
them couple of months ago. I remember that it was some kind of hack
including and running them, though.

Anyway, I managed to sort things out without hacks. Thanks for help!
