### ISSUE TITLE
Hacklang CodeSniffer?

### ISSUE THREAD

**Issue by skyzyx** [squizlabs/PHP_CodeSniffer#602]
Is there an interest in, or work underway to, implement support for Hack in addition to PHP?

**Comment by aik099** [comment]
All the standard php stuff should work without changes I guess. But supporting Hack-only syntax is tricky. Right now no matter which PHP version (e.g. 5.2) is used to run `phpcs` it can check code for future (e.g. 5.6) PHP versions as well. That's really cool.

This means if a hack support would be introduced, then you can use regular php to hack-specific stuff, but this creates an issue making hack-specific code valid for projects, that only need regular PHP.

I'm not sure what will happen with hack considering accepted RFC into PHP7 with all these scalar type hints and all.

**Comment by gsherwood** [comment]
There is no work underway to implement support for Hack by myself, or anyone I know of.
