### ISSUE TITLE
Issue with braces

### ISSUE THREAD

**Issue by copycut** [squizlabs/PHP_CodeSniffer#606]
Hi, 
I have a issue with this case (when you mix two different kind of notation) : 
```php
<?php
if ($test) :
    if ($testA) {
        $var = 'A';
    } else if ($testB) {
        $var = 'B';
    } else {
        $var = 'C';
    }
?>
<p>... html content is $test is true ...</p>
<?php
endif
?>
```

Code sniffer says "*ERROR | [x] Closing brace must be on a line by itself*"

when I change this code like below there is no more error :
```php
<?php
if ($test) :
    if ($testA) :
        $var = 'A';
    else if ($testB) :
        $var = 'B';
    else :
        $var = 'C';
    endif;
?>
```

**Comment by gsherwood** [comment]
I can't replicate that error message using any of the included sniffs on either the latest stable version (2.3.2) or the current master code.

I did manage to get that error on the old 1.5.6 version. **If this the version you are using?** If so, you'll need to upgrade to the latest stable to get better alternate control structure syntax support and a heap of other bug fixes as well.

**Comment by copycut** [comment]
Yes maybe we have a older version.
Now it's updated.
PHP_CodeSniffer version 2.3.0 (stable) by Squiz (http://www.squiz.net)

Thanks.

**Comment by gsherwood** [comment]
> Now it's updated.

Do you still have the same problem or is it fixed now?

**Comment by copycut** [comment]
I can't reproduce this case. Sorry :sob: 
I assume that is fix

**Comment by gsherwood** [comment]
Thanks for testing the new version and getting back to me.
