### ISSUE TITLE
PSR-2 coding standard?

### ISSUE THREAD

**Issue by mainalikishan** [squizlabs/PHP_CodeSniffer#610]
Does 'PHP_CodeSniffer' follow PSR-2 coding standard?

**Comment by aik099** [comment]
Not really. It follows PEAR standard because it's a PEAR package.

**Comment by aik099** [comment]
You can ask questions in our chat room as well: https://gitter.im/squizlabs/PHP_CodeSniffer

**Comment by mainalikishan** [comment]
It would be awesome if we could scan code for particular coding standard.
E.g: php scripts/phpcs -psr2

**Comment by gsherwood** [comment]
This conversation was moved to the gitter room.

But essentially, checking code against the PSR2 standard is done by running `phpcs --standard=PSR2 /path/to/code`
