### ISSUE TITLE
Invalid numeric literal on CSS files under PHP7

### ISSUE THREAD

**Issue by redaxmedia** [squizlabs/PHP_CodeSniffer#611]
This used to happen on CSS files, I lint them with a couple of custom Squiz.CSS, but even with a empty ruleset.xml this error happens.

<pre>
Parse error: Invalid numeric literal in  on line 1
Warning: PHP Parse error:  Invalid numeric literal in  on line 1
Use --force to continue.
</pre>

A research on the CSS files showed that # and maby other special characters cause the parse error.

**Comment by aik099** [comment]
It would be great if you could attach, in gist form for example, the actual CSS you're checking and ruleset you're using.

**Comment by aik099** [comment]
Maybe you can send PR adding PHP7 to Travis CI build of PHPCS so that we can see if it works in there at all.

**Comment by redaxmedia** [comment]
Let me show you a couple of examples, it somehow is hex related:

Working:

<pre>
.test
{
	background: #999;
}
</pre>

Failing:

.test
{
	background: #078;
}

I can see no pattern here... #000 to #077 is working ^^ but from #078 to #099 fails

**Comment by gsherwood** [comment]
> Maybe you can send PR adding PHP7 to Travis CI build of PHPCS so that we can see if it works in there at all.

Travis has been testing PHPCS on PHP7 since it was supported, so no need for a PR. PHP7 was actually fully passing until a recent PHP7 nightly build, where something broke. There were no code changes in PHPCS to cause the break (just a new PHP7 build) and I have not been able to replicate any issues locally. So I'm still working on it.

**Comment by gsherwood** [comment]
This is a new syntax error in PHP7 that I'll need to guard against. Specifically, the CSS tokenizer asks the PHP tokenizer to parse the contents of comments and it doesn't need to for things like this. Thanks for reporting.

**Comment by gsherwood** [comment]
I've committed a fix that looks to be working.

**Comment by redaxmedia** [comment]
Thank you, seems to work now.

**Comment by ka636-cyber** [comment]
Hi
