### ISSUE TITLE
Unable to run test suite with PHP_CodeSniffer installed globally via Composer

### ISSUE THREAD

**Issue by aik099** [squizlabs/PHP_CodeSniffer#614]
I have PHPUnit and PHP_CodeSniffer installed globally via Composer. When I attempt to run `phpunit` command on cloned PHP_CodeSniffer repo I'm getting this error:

```
PHP Fatal error: Cannot redeclare class PHP_CodeSniffer in /home/alex/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer.php on line 69
```

I guess this might be happening due issues in test suite where PHP_CodeSniffer class is included regardless of the fact, that it's already loaded through Composer's autoloader.

Maybe, on the other hand, the wrong PHP_CodeSniffer class is picked by autoloader (one from global composer install and not from cloned repo) and that causes the issue.

Theoretically if an autoloader is used in test suite then it should be used first before any composer autoloader kicks in.

**Comment by gsherwood** [comment]
Closing this as you reported it a second time (issue #1016) and found the problem yourself.
