### ISSUE TITLE
Space after switch keyword in PSR-2 is not being enforced

### ISSUE THREAD

**Issue by kokokurak** [squizlabs/PHP_CodeSniffer#617]
PSR-2 standard requires exactly one space after `switch` statement, but PHP CodeSniffer doesn't show that requirement.

This is invalid, but not marked as such:
```php
switch($value) { // no space after switch
```

**Comment by gsherwood** [comment]
Thanks for finding that. Looks like I just forgot about SWITCH when writing that sniff. Fixed now.

**Comment by kokokurak** [comment]
Thank you very much. You are not the only one who tends to forget about `switch` :)
