### ISSUE TITLE
Fixer makes a syntax error in closures with 'use' with PSR2

### ISSUE THREAD

**Issue by rrehbeindoi** [squizlabs/PHP_CodeSniffer#619]
`bin/phpcbf --standard=PSR2 sample.php`

```diff
-     function ($a) use ($b)
-     {
+     function ($a) {
+         use ($b)
+     
```

PHP Parse error:  syntax error, unexpected 'use' (T_USE) in sample.php on line 7

PHP_CodeSniffer version 2.3.2 (stable)

**Comment by gsherwood** [comment]
This has been reported and fixed in bug #592 and will be released in the new version (this week or next week).
