### ISSUE TITLE
Update your wiki page 'Coding Standard Tutorial'

### ISSUE THREAD

**Issue by christian-weiss** [squizlabs/PHP_CodeSniffer#627]
Wiki page to update:
https://github.com/squizlabs/PHP_CodeSniffer/wiki/Coding-Standard-Tutorial

See diff for details:
https://github.com/christian-weiss/PHP_CodeSniffer_wiki/commit/f80ba1db45bfd7aadadfb201946ddf9035d39c51

**Comment by gsherwood** [comment]
I made a slight change that I think makes the sub-directory requirement even more clear in the tutorial, without beating people over the head with it.

https://github.com/squizlabs/PHP_CodeSniffer/wiki/Coding-Standard-Tutorial/_compare/194f0525ba774c3a418426b46314c99ff6d3a0b3...ba8dd0ae9a72c1d1d80f91046a17363105683aaf
