### ISSUE TITLE
Release version 2.3.3

### ISSUE THREAD

**Issue by klausi** [squizlabs/PHP_CodeSniffer#632]
Hi,

we have a couple of nice fixes in the master branch, when do you plan the next release? I'd like to depend on that future release in Drupal's Coder next release. I don't want to depend on a git commit hash version in my composer.json file, which is also painful for end users when they need to configure dev dependencies in their Composer config to even install Coder.

Thanks!

**Comment by gsherwood** [comment]
Hopefully this week. My life is incredibly busy at the moment.
