### ISSUE TITLE
Windows patch.exe error

### ISSUE THREAD

**Issue by iongion** [squizlabs/PHP_CodeSniffer#637]
On windows because of `patch.exe`(provided by gnuwin32, gow or unixutils) one gets this error:
```
Assertion failed: hunk, file ../patch-2.5.9-src/patch.c, line 354
```
Apparently this can be solved on windows if you invoke patch with binary option
```
patch {file} {patch} --verbose --binary
```
as explained here https://www.drupal.org/node/23844#comment-41593

**Comment by gsherwood** [comment]
I've decided to remove the use of `diff` and `patch` for PHPCBF in the 3.0 version, and have committed that change to the 3.0 branch already. I don't want to make any changes to the process in the existing 2.x version for backwards compatibility reasons.

For 2.x versions, please use the `--no-patch` command line argument. This will replicate the default behaviour of the 3.0 version.
