### ISSUE TITLE
VCS blame reports output error content from the blame commands for files not under VC

### ISSUE THREAD

**Issue by manquer** [squizlabs/PHP_CodeSniffer#638]
gitblame stype reports throwing 
````fatal: no such path 'path/to/file/'  in HEAD````
errors for files which exist locally but not there in repo

While ````.gitignored```` files can also be ignored in phpcs runs, 
ideally these files should not be scanned in gitblame report style in the first place

**Comment by aik099** [comment]
> gitblame stype reports throwing 
> fatal: no such path 'path/to/file/' in HEAD
> errors for files which exist locally but not there in repo

1. Does this happen with any git repo or with some specific repo?
2. What command are you using to execute PHP_CodeSniffer?

> ideally these files should not be scanned in gitblame report style in the first place

Maybe, but then you'll have 2 different scopes of files scanned based on selected report, which might be confusing.

**Comment by manquer** [comment]
1. It usually happens for all my repos where my local configuration files (in php) are not part of the repo.

2. I run something like this. ````phpcs --extensions=php --standard=MyStandard --ignore=./vendor --report-gitblame ./````

I agree that it is confusing to have 2 different scopes basis the selected report. However these type of files are not in the repo, and they are already not part of the gitblame report, therefore it makes sense to not parse them in the gitblame report case only.

In any case the error is coming from git-blame not phpcs and is bit confusing to understand what is happening and why, a better way to show the error with clearer explanation will help users would be good

**Comment by gsherwood** [comment]
The files need to be scanned, but they are recorded as an Unknown user because the author of each line is still unknown. I'll look at just getting the VCS commands to mute their errors.
