### ISSUE TITLE
typo in wiki

### ISSUE THREAD

**Issue by voda** [squizlabs/PHP_CodeSniffer#640]
in https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#viewing-configuration-options the `--config-show` argument is surrounded by the number 1 instead of backticks.

**Comment by aik099** [comment]
Here is an image of that:

![php_codesniffer_wikitypo](https://cloud.githubusercontent.com/assets/1277526/8648718/a5bd4aea-296b-11e5-83cf-89803c6f789f.png)

**Comment by gsherwood** [comment]
Thanks. Fixed now.
