### ISSUE TITLE
Release 2.3.4

### ISSUE THREAD

**Issue by bc-petrkotek** [squizlabs/PHP_CodeSniffer#653]
Hi & thanks for all great work!

I was wondering when is 2.3.4 planned to be released?

There are some good commits in master - I'm especially waiting for this bugfix to be released: https://github.com/squizlabs/PHP_CodeSniffer/commit/c95da5f6f7ec9606ec28dcb6bfc12e275f74e3f7

Thanks!

**Comment by gsherwood** [comment]
The earliest would be the week staring 17th August. Work is too crazy right now to consider it before then. Sorry I can't be more specific.
