### ISSUE TITLE
Comments affect indent check for BSDAllman brace style

### ISSUE THREAD

**Issue by Danack** [squizlabs/PHP_CodeSniffer#654]
It appears that having a `//` comment on the line before a method affects the code analysis of the method e.g. 

```
<?php

namespace Whatever;

class Foo
{
//Comments should not affect code
    public function bar()
    {
      
    }
//Comments should not affect code
}
```

Output is

```
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 9 | ERROR | [x] Opening brace indented incorrectly; expected 0 spaces,
   |       |     found 4
   |       |     (Squiz.Functions.MultiLineFunctionDeclaration.BraceIndent)
```

The code itself is fine - it's just that the comment before it has confused the parser apparently.

For the record, I am using comments to mark code that needs to be extracted as an example of how to use something (e.g. all of the examples on the site http://phpimagick.com/Imagick/adaptiveBlurImage).

**Comment by aik099** [comment]
I guess this is because comments should be indented properly.

**Comment by gsherwood** [comment]
Bug is now fixed. Thanks for reporting.
