### ISSUE TITLE
How to do hashes using properties xml?

### ISSUE THREAD

**Issue by ofbeaton** [squizlabs/PHP_CodeSniffer#655]
I was going to ask if `Squiz.PHP.DiscouragedFunctions` could be changed to use a regular array instead of a hash table for the list of functions. It's a trivial sniff to copy to your own and change, but if it's trivial, then it should be doable in your ruleset only no?

Then I realized that you probably have a way of doing this using properties. *The [Annotated ruleset.xml Documentation](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-ruleset.xml) does not mention the support of arrays or hash tables at all.* Peeking in the [Squiz ruleset.xml](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/Squiz/ruleset.xml) however and I spot that you have added support for arrays on the line `<property name="ignoreCodes" type="array" value="0001,0110,0240"/>`. 

Unfortunately I'm unsure how/if you also support hash tables, where I can set the key as well as the value.

Is it something like?:
`<property name="ignoreCodes" type="array" value="key1=>0001,key2=>0110,key3=>0240"/>`

Or maybe more xml like?:
```xml
<property name="ignoreCodes" type="array">
  <node value="0001"/>
  <node key="key1" value="0002"/>
  <node valueType="int" value="0003"/>
  <node keyType="int" key="8" valueType="boolean" value="false"/>
</property>
```

Please let me know if this is a feature, and how it is implemented. If it isn't, then this is a feature request! It is easier to just change the sniff to use an array, but supporting hash tables would go a long way to allowing complex reconfigurations of sniffs (and may already be supported).

**Comment by gsherwood** [comment]
The sniff uses a hash table because the error message can optionally suggest a different function to use when a discouraged function is found. This is the same for the Forbidden Functions sniff as well. Specifying NULL just reports that the function is now allowed and provides no alternative.

Try this for the property setting. If that works for you, I'll make sure I document it on the ruleset page.

```xml
<property name="forbiddenFunctions" type="array" value="delete=>unset,print=>echo,create_function=>null" />
```

**Comment by ofbeaton** [comment]
That worked great, thanks! I would have preferred the xml syntax but this did the trick. Thanks again for the support. Feel free to close this ticket, or if you'd like to keep it around to remind you to update the documentation, that's OK too!

**Comment by gsherwood** [comment]
I've finally gotten around to adding basic docs so it isn't forgotten.
