### ISSUE TITLE
Multi-line method declaration support

### ISSUE THREAD

**Issue by gl3n** [squizlabs/PHP_CodeSniffer#661]
Hi,

We are severals developers getting an error on multi-line methods (constructor in our case), here is the related issue : https://github.com/escapestudios/Symfony2-coding-standard/issues/12

Could you add a check for multi-line function declaration ?

Thanks

**Comment by jum4** [comment]
:+1:

**Comment by gsherwood** [comment]
There are already sniffs that check multii-line function declarations. Maybe your custom standard is including conflicting sniffs?

Maybe try this one: https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/PEAR/Sniffs/Functions/FunctionDeclarationSniff.php

Or this one, which PSR2 uses: https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/Squiz/Sniffs/Functions/FunctionDeclarationSniff.php

These sniffs will enforce different brace rules depending on if the function is a multi-line declaration or not.

Does that help?

**Comment by nesl247** [comment]
It's the Symfony2 standard's importing of Zend's ruleset that is causing the problem.

**Comment by gsherwood** [comment]
The Zend ruleset isn't a complete standard (just a collection of a few sniffs that Zend people submitted many many years ago) so it's highly unlikely that you want to be doing that. Cherry pick the specific sniffs that you want so you don't choose any that conflict with each other.

**Comment by nesl247** [comment]
Yep. I discovered the rule that was causing the problem and updated the issue there. Hopefully they fix it. This issue can be closed though.

**Comment by gsherwood** [comment]
Thanks for getting back to me. If you need more help over there, just mention me and I'll get an alert (or I should).
