### ISSUE TITLE
ClassCommentSniff incorrectly handles class comments as file comments

### ISSUE THREAD

**Issue by SebastianZ** [squizlabs/PHP_CodeSniffer#671]
As far as I can see [according to the *File-level DocBlocks* section at PHPDoc](http://phpdoc.org/docs/latest/getting-started/your-first-set-of-documentation.html) a comment before a class is associated with the class, also when it comes directly after the first open tag.

So there should *not* be an error message output for the following code:

    <?php
    /**
     * Class description
     */
    class MyClass
    {
    }

Related CodeSniffer code:
https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/Squiz/Sniffs/Commenting/ClassCommentSniff.php#L74-L92

Sebastian

**Comment by gsherwood** [comment]
I finally got around to looking at this. Sorry for the massive delay.

It makes sense to have the included sniffs match the same logic as phpdoc, so I've changed them.

Thanks.
