### ISSUE TITLE
Unexpected "Expected next thing to be a escaping function" error

### ISSUE THREAD

**Issue by paulschreiber** [squizlabs/PHP_CodeSniffer#673]
When I run the WordPress ruleset over a function with ternary functions nested in an escape call, I get an unexpected "Expected next thing to be a escaping function" error.

```
phpcs -s --standard=WordPress ~/test.php
```

Output:
```
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 6 | ERROR | Expected next thing to be a escaping function, not '$r'
   |       | (WordPress.XSS.EscapeOutput.OutputNotEscaped)
----------------------------------------------------------------------
```

Code:
```php
<?php
	echo '<div class="'
		. esc_attr( 'baz-'
			. $r
			. ( $r === $active_round ? ' foo' : '' )
			. ( $r < $active_round ? ' bar' : '' )
		)
		. '">';
?>
```

If you remove line 6 (`. ( $r < $active_round ? ' bar' : '' )`), the error goes away.

**Comment by JDGrimes** [comment]
I think this is an issue in [WPCS](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues), not PHPCS itself. Maybe you could open an issue there instead?

**Comment by gsherwood** [comment]
Closing as this is likely a WordPress sniff issue. If there is a core problem stopping the sniff from working, please reopen.
