### ISSUE TITLE
phpcbf not checking if patch is installed

### ISSUE THREAD

**Issue by manquer** [squizlabs/PHP_CodeSniffer#675]
If patch is not installed phpcbf fails with the following error
````
sh: patch: command not found
Array
(
)
````

**Comment by aik099** [comment]
Please use `--no-patch` option of `phpcbf` to prevent usage of `patch` program. This way diff will be created using pure PHP code without Unix-specific program usage.

**Comment by manquer** [comment]
of course thanks for the info ..
shouldn't the fall back happen automatically if patch does not exist ? alternatively, the error message can suggest the --no-patch option ?

**Comment by aik099** [comment]
Maybe. Theoretically Cygwin can install patch command on Windows as well and then it could work.

**Comment by manquer** [comment]
of course, also for me this actually happened on a *nix machine which for some reason did not have patch installed.

**Comment by gsherwood** [comment]
I've decided to remove the use of `diff` and `patch` for PHPCBF in the 3.0 version, and have committed that change to the 3.0 branch already. I don't want to make any changes to the process in the existing 2.x version for backwards compatibility reasons.

For 2.x versions, please use the `--no-patch` command line argument. This will replicate the default behaviour of the 3.0 version.
