### ISSUE TITLE
starting curly bracket in same line?

### ISSUE THREAD

**Issue by JurekRaben** [squizlabs/PHP_CodeSniffer#676]
Hi,

have can I change the standard to accept the starting curly bracket in the same line as the method name?

Cannot find any docs...
The command to set it seems to be "phpcs --config-set xxx"

Is there a command to get all available config switches? "phpcs --config-show" does not show anything here...

Thx!

**Comment by aik099** [comment]
The ruleset is code concept of PHP_CodeSniffer. Each ruleset is composed of sniffs (different kinds checks that are performed). Then only way to alter used ruleset is to:

1. create new ruleset that would inherit currently used ruleset
2. exclude unwanted sniff
3. add another sniff

**Comment by gsherwood** [comment]
As @aik099 has said, you'll need to create a custom ruleset.xml file to decide what checks you want PHPCS to run. You wont be able to use --config-set to change something like the curly bracket rule.

You'll find the documentation for the ruleset.xml here: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-ruleset.xml
