### ISSUE TITLE
PSR2.Methods.FunctionCallSignature.Indent forces exact indent of ternary operator parameters

### ISSUE THREAD

**Issue by mattsnowboard** [squizlabs/PHP_CodeSniffer#698]
I keep hitting a violation for PSR2.Methods.FunctionCallSignature.Indent with code like the following:

        $this->log(
            'error',
            sprintf(
                '[Stripe] Dispute created for charge %s, reason: %s, evidence due by: %s',
                $e->getData()['object']['charge'],
                $e->getData()['object']['reason'],
                isset($e->getData()['object']['evidence_details'])
                    ? $e->getData()['object']['evidence_details']['due_by']
                    : ''
            ),
            array($e->getData()['object'])
        );

phpcbf wants to fix it as

        $this->log(
            'error',
            sprintf(
                '[Stripe] Dispute created for charge %s, reason: %s, evidence due by: %s',
                $e->getData()['object']['charge'],
                $e->getData()['object']['reason'],
                isset($e->getData()['object']['evidence_details'])
                ? $e->getData()['object']['evidence_details']['due_by']
                : ''
            ),
            array($e->getData()['object'])
        );

1) Is there a way to avoid that?
2) Is there any accepted standard that has a rule specifically for this case?

I'm generally trying to stick to PSR-2 style rules, but I don't like the way the auto-fix tries to put that all at the same indent level

**Comment by aik099** [comment]
Probably an error, but I'm not aware of any ternary operator formatting sniffs out there.

Since we're talking about code style I don't recommend putting complex constructs right inside method/function calls in general.

**Comment by evilebottnawi** [comment]
@aik099 Writing code in this code style is often very convenient. i think it is bug

**Comment by gsherwood** [comment]
The sniff had various param types hard-coded so it could relax the indent for them. I've changed this to now relax the indent for all multi-line params, including ternary operators. Thanks for reporting the bug.

**Comment by westonruter** [comment]
It seems this may have introduced a regression since 2.3.4. See https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/525

**Comment by gsherwood** [comment]
@westonruter I think I found the problem. I replicated with the PEAR coding standard and checked the fix against the WordPress one as well. All seems to be working now. Thanks for reporting this.

**Comment by westonruter** [comment]
:heart: :exclamation:

**Comment by SidIcarus** [comment]
Using 2.7. Unfortunately still happens in a similar situation:
<img width="650" alt="screen shot 2017-01-30 at 01 06 13 pm" src="https://cloud.githubusercontent.com/assets/3842798/22435179/0a8a0aae-e6ed-11e6-9ff1-95d43cbea75b.png">

Note: I didn't write the code, just running my ruleset against it
