### ISSUE TITLE
How to Unset Config Values

### ISSUE THREAD

**Issue by GaryJones** [squizlabs/PHP_CodeSniffer#719]
![screenshot 2015-09-25 08 50 23](https://cloud.githubusercontent.com/assets/88371/10095606/d9d0dd0c-6362-11e5-96a5-20e67d002b6d.png)

At some point in time, I've obviously tried to set the default standard, without remembering the exact name of the key. They aren't causing any problem, but how can I get rid of `default-standard` and `standard` config values?

**Comment by gsherwood** [comment]
Try:
```
phpcs --config-delete default-standard
phpcs --config-delete standard
```

**Comment by GaryJones** [comment]
Perfect. And apologies for a total failure on my part to read `phpcs --help` more closely.

**Comment by gsherwood** [comment]
Not a problem.
