### ISSUE TITLE
Internal.Tokenizer.Exception

### ISSUE THREAD

**Issue by attiks** [squizlabs/PHP_CodeSniffer#720]
We're setting up phpcs for the Drupal project, but we're having troubles with some files, we tried:

- excluding them using ```<exclude-pattern>```
- excluding the rule using ```<exclude name="Internal.Tokenizer.Exception"/>```
- changing the severity using ```<rule ref="Internal.Tokenizer.Exception"><severity>0</severity></rule>```

But the following output is still generated

```
FILE: .../Asset/css_test_files/css_input_without_import.css.optimized.css
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 1 | WARNING | File appears to be minified and cannot be processed
   |         | (Internal.Tokenizer.Exception)
----------------------------------------------------------------------
```

Related issue on drupal.org: https://www.drupal.org/node/2573377

Are we missing something obvious?

**Comment by aik099** [comment]
The `Internal.Tokenizer.Exception` seems to be an exception thrown and wrapped to look like the sniff error so it can be displayed in reports.

I think, that instead of attempting excluding it you need to exclude minified files. You can use `*` and similar patters to match all minified files at once.

**Comment by attiks** [comment]
There's something strange going on, will investigate further. As a test I copied the file to another directory and used ``` <exclude-pattern>./comment_hacks.css.optimized.css</exclude-pattern> ``` and it **does** work.

**Comment by attiks** [comment]
Found it, we had the following in our phpcs.xml

```
  <file>./core</file>
  <exclude-pattern>./core/vendor/*</exclude-pattern>
  <exclude-pattern>./core/assets/vendor/*</exclude-pattern>
  <exclude-pattern>*optimized.css</exclude-pattern>
  <arg name="extensions" value="css,inc,info,install,js,module,php,profile,test,theme"/>
```

which should obviously be

```
  <arg name="extensions" value="css,inc,info,install,js,module,php,profile,test,theme"/>
  <file>./core</file>
  <exclude-pattern>./core/vendor/*</exclude-pattern>
  <exclude-pattern>./core/assets/vendor/*</exclude-pattern>
  <exclude-pattern>*optimized.css</exclude-pattern>
```
