### ISSUE TITLE
When running php code sniffer on files which use other lanages it causes line length warrning

### ISSUE THREAD

**Issue by paladox** [squizlabs/PHP_CodeSniffer#728]
Hi when running php code sniffer on files that use for example other lanages like this lang code as. it cause line length warning even though it is only for example 50 characters.

Please could this be fixed to support other languages.

**Comment by aik099** [comment]
Please post example file here.

**Comment by paladox** [comment]
<?php

$languageNames = array(
	'ab' => 'абхазская',
	'ady' => 'адыгейская',
	'af' => 'афрыкаанс',
	'akk' => 'акадзкая',
	'ale' => 'алеуцкая',
	'am' => 'амхарская',
	'an' => 'арагонская',
	'ang' => 'стараанглійская',
	'ar' => 'арабская',
	'arc' => 'арамейская',
	'as' => 'асамская',
	'ast' => 'астурыйская',
	'av' => 'аварская',
	'ay' => 'аймара',
	'az' => 'азербайджанская',
	'ba' => 'башкірская',
	'be' => 'беларуская',
	'bg' => 'балгарская',
	'bn' => 'бенгальская',
	'br' => 'брэтонская',
	'bs' => 'баснійская',
	'bua' => 'бурацкая',
	'ca' => 'каталонская',
	'ce' => 'чачэнская',
	'chb' => 'чыбча',
	'cop' => 'копцкая',
	'cs' => 'чэшская',
	'cv' => 'чувашская',
	'cy' => 'валійская',
	'da' => 'дацкая',
	'de' => 'нямецкая',
	'de-at' => 'нямецкая (аўстр.)',
	'de-ch' => 'нямецкая (швейц.)',
	'egy' => 'стараэгіпецкая',
	'el' => 'грэцкая',
	'en' => 'англійская',
	'en-au' => 'англійская (аўстрал.)',
	'en-ca' => 'англійская (канад.)',
	'en-us' => 'англійская (ЗША)',
	'eo' => 'эсперанта',
	'es' => 'іспанская',
	'es-419' => 'іспанская (лацінаамер.)',
	'et' => 'эстонская',
	'eu' => 'баскская',
	'fa' => 'фарсі',
	'fi' => 'фінская',
	'fil' => 'тагальская',
	'fo' => 'фарэрская',
	'fr' => 'французская',
	'fr-ca' => 'французская (канад.)',
	'fr-ch' => 'французская (швейц.)',
	'fro' => 'старафранцузская',
	'fy' => 'фрызская',
	'ga' => 'ірландская',
	'gd' => 'шатландская гэльская',
	'gl' => 'галісійская',
	'gn' => 'гуарані',
	'grc' => 'старагрэцкая',
	'gu' => 'гуяраці',
	'he' => 'іўрыт',
	'hi' => 'хіндзі',
	'hr' => 'харвацкая',
	'hu' => 'венгерская',
	'hy' => 'армянская',
	'ia' => 'інтэрлінгва',
	'id' => 'інданезійская',
	'ie' => 'інтэрлінгве',
	'is' => 'ісландская',
	'it' => 'італьянская',
	'ja' => 'японская',
	'jv' => 'яванская',
	'ka' => 'грузінская',
	'kk' => 'казахская',
	'kn' => 'каннада',
	'ko' => 'карэйская',
	'ku' => 'курдская',
	'la' => 'лацінская',
	'ln' => 'лінгала',
	'lo' => 'лаоская',
	'lol' => 'монга',
	'lt' => 'літоўская',
	'luo' => 'луо',
	'lv' => 'латышская',
	'man' => 'мандынга',
	'mas' => 'масаі',
	'men' => 'мендэ',
	'mg' => 'мальгашская',
	'mk' => 'македонская',
	'ml' => 'малаяламская',
	'mn' => 'мангольская',
	'mos' => 'мосі',
	'mr' => 'маратхі',
	'ms' => 'малайская',
	'mt' => 'мальтыйская',
	'nb' => 'нарвэская букмал',
	'ne' => 'непальская',
	'nl' => 'галандская',
	'nl-be' => 'фламандская',
	'nn' => 'нарвежская (нюнорск)',
	'no' => 'нарвежская',
	'nog' => 'нагайская',
	'non' => 'старанарвежская',
	'oc' => 'правансальская',
	'oj' => 'аджыбве',
	'or' => 'орыя',
	'os' => 'асецінская',
	'pa' => 'панджабі',
	'peo' => 'стараперсідская',
	'phn' => 'фінікійская',
	'pl' => 'польская',
	'pro' => 'стараправансальская',
	'ps' => 'пушту',
	'pt' => 'партугальская',
	'pt-br' => 'партугальская (бразіл.)',
	'qu' => 'кечуа',
	'raj' => 'раджастханская',
	'rm' => 'рэта-раманская',
	'ro' => 'румынская',
	'ro-md' => 'малдаўская',
	'ru' => 'руская',
	'sa' => 'санскрыт',
	'sah' => 'якуцкая',
	'sd' => 'сіндхі',
	'sga' => 'стараірландская',
	'sh' => 'сербска-харвацкая',
	'si' => 'сінгальская',
	'sk' => 'славацкая',
	'sl' => 'славенская',
	'so' => 'самалійская',
	'sq' => 'албанская',
	'sr' => 'сербская',
	'su' => 'суданская',
	'sux' => 'шумерская',
	'sv' => 'шведская',
	'sw' => 'суахілі',
	'ta' => 'тамільская',
	'te' => 'тэлугу',
	'tg' => 'таджыкская',
	'th' => 'тайская',
	'ti' => 'тыгрынья',
	'tk' => 'туркменская',
	'tlh' => 'клінгон',
	'tr' => 'турэцкая',
	'tt' => 'татарская',
	'tyv' => 'тувінская',
	'ug' => 'уйгурская',
	'uk' => 'украінская',
	'und' => 'невядомая мова',
	'ur' => 'урду',
	'uz' => 'узбекская',
	'vi' => 'в’етнамская',
	'vo' => 'валапюк',
	'xh' => 'хоса',
	'yi' => 'ідыш',
	'zap' => 'сапатэкаў',
	'zh' => 'кітайская',
	'zh-hans' => 'спрошчаная кітайская',
	'zh-hant' => 'традыцыйная кітайская',
	'zu' => 'зулу',
);

$currencyNames = array(
	'AUD' => 'аўстралійскі даляр',
	'BRL' => 'бразільскі рэал',
	'BYR' => 'беларускі рубель',
	'CNY' => 'кітайскі юань',
	'ERN' => 'эрытрэйская накфа',
	'EUR' => 'еўра',
	'GBP' => 'англійскі фунт',
	'INR' => 'індыйская рупія',
	'JPY' => 'японская іена',
	'NOK' => 'нарвэская крона',
	'RUB' => 'рускі рубель',
	'USD' => 'долар ЗША',
	'XXX' => 'невядомая або недапушчальная валюта',
);

$currencySymbols = array(
	'BYR' => 'р.',
	'JPY' => '¥',
	'RUB' => 'рас. руб.',
	'USD' => '$',
);

$countryNames = array(
	'AD' => 'Андора',
	'AE' => 'Аб’яднаныя Арабскія Эміраты',
	'AF' => 'Афганістан',
	'AG' => 'Антыгуа і Барбуда',
	'AI' => 'Ангілья',
	'AL' => 'Албанія',
	'AM' => 'Арменія',
	'AN' => 'Нідэрландскія Антылы',
	'AO' => 'Ангола',
	'AQ' => 'Антарктыка',
	'AR' => 'Аргенціна',
	'AS' => 'Амерыканскае Самоа',
	'AT' => 'Аўстрыя',
	'AU' => 'Аўстралія',
	'AW' => 'Аруба',
	'AX' => 'Аландскія астравы',
	'AZ' => 'Азербайджан',
	'BA' => 'Боснія і Герцагавіна',
	'BB' => 'Барбадас',
	'BD' => 'Бангладэш',
	'BE' => 'Бельгія',
	'BF' => 'Буркіна-Фасо',
	'BG' => 'Балгарыя',
	'BH' => 'Бахрэйн',
	'BI' => 'Бурундзі',
	'BJ' => 'Бенін',
	'BL' => 'Сен-Бартэльмі',
	'BM' => 'Бермудскія астравы',
	'BN' => 'Бруней',
	'BO' => 'Балівія',
	'BR' => 'Бразілія',
	'BS' => 'Багамы',
	'BT' => 'Бутан',
	'BV' => 'Бувэ востраў',
	'BW' => 'Батсвана',
	'BY' => 'Беларусь',
	'BZ' => 'Беліз',
	'CA' => 'Канада',
	'CC' => 'Какосавыя астравы',
	'CD' => 'Конга, Дэмакратычная Рэспубліка',
	'CF' => 'Цэнтральна-Афрыканская Рэспубліка',
	'CG' => 'Конга',
	'CH' => 'Швейцарыя',
	'CI' => 'Кот-д’Івуар',
	'CK' => 'Астравы Кука',
	'CL' => 'Чылі',
	'CM' => 'Камерун',
	'CN' => 'Кітай',
	'CO' => 'Калумбія',
	'CR' => 'Коста-Рыка',
	'CU' => 'Куба',
	'CV' => 'Каба-Вердэ',
	'CW' => 'Востраў Кюрасаа',
	'CX' => 'Востраў Ражства',
	'CY' => 'Кіпр',
	'CZ' => 'Чэхія',
	'DE' => 'Германія',
	'DJ' => 'Джыбуці',
	'DK' => 'Данія',
	'DM' => 'Дамініка',
	'DO' => 'Дамініканская Рэспубліка',
	'DZ' => 'Алжыр',
	'EC' => 'Эквадор',
	'EE' => 'Эстонія',
	'EG' => 'Егіпет',
	'EH' => 'Заходняя Сахара',
	'ER' => 'Эрытрэя',
	'ES' => 'Іспанія',
	'ET' => 'Эфіопія',
	'EU' => 'Еўрапейскі Звяз',
	'FI' => 'Фінляндыя',
	'FJ' => 'Фіджы',
	'FK' => 'Фолклэндскія астравы',
	'FM' => 'Мікранезія',
	'FO' => 'Фарэрскія астравы',
	'FR' => 'Францыя',
	'GA' => 'Габон',
	'GB' => 'Вялікабрытанія',
	'GD' => 'Грэнада',
	'GE' => 'Грузія',
	'GF' => 'Французская Гвіяна',
	'GG' => 'Востраў Гернсі',
	'GH' => 'Гана',
	'GI' => 'Гібралтар',
	'GL' => 'Грэнландыя',
	'GM' => 'Гамбія',
	'GN' => 'Гвінея',
	'GP' => 'Гвадэлупа',
	'GQ' => 'Экватарыяльная Гвінея',
	'GR' => 'Грэцыя',
	'GS' => 'Паўднёвая Джорджыя і Паўднёвыя Сандвічавы астравы',
	'GT' => 'Гватэмала',
	'GU' => 'Гуам',
	'GW' => 'Гвінея-Бісау',
	'GY' => 'Гаяна',
	'HK' => 'Ганконг',
	'HM' => 'Востраў Херд і Астравы Макдоналд',
	'HN' => 'Гандурас',
	'HR' => 'Харватыя',
	'HT' => 'Гаіці',
	'HU' => 'Венгрыя',
	'ID' => 'Інданезія',
	'IE' => 'Ірландыя',
	'IL' => 'Ізраіль',
	'IM' => 'Востраў Мэн',
	'IN' => 'Індыя',
	'IO' => 'Брытанская тэрыторыя ў Індыйскім акіяне',
	'IQ' => 'Ірак',
	'IR' => 'Іран',
	'IS' => 'Ісландыя',
	'IT' => 'Італія',
	'JE' => 'Востраў Джэрсі',
	'JM' => 'Ямайка',
	'JO' => 'Іарданія',
	'JP' => 'Японія',
	'KE' => 'Кенія',
	'KG' => 'Кыргызстан',
	'KH' => 'Камбоджа',
	'KI' => 'Кірыбаці',
	'KM' => 'Каморскія Астравы',
	'KN' => 'Сент-Кітс і Невіс',
	'KP' => 'Паўночная Карэя',
	'KR' => 'Паўднёвая Карэя',
	'KW' => 'Кувейт',
	'KY' => 'Кайманавы астравы',
	'KZ' => 'Казахстан',
	'LA' => 'Лаос',
	'LB' => 'Ліван',
	'LC' => 'Сент-Люсія',
	'LI' => 'Ліхтэнштэйн',
	'LK' => 'Шры-Ланка',
	'LR' => 'Ліберыя',
	'LS' => 'Лесота',
	'LT' => 'Літва',
	'LU' => 'Люксембург',
	'LV' => 'Латвія',
	'LY' => 'Лівія',
	'MA' => 'Марока',
	'MC' => 'Манака',
	'MD' => 'Малдова',
	'ME' => 'Чарнагорыя',
	'MG' => 'Мадагаскар',
	'MH' => 'Маршалавы Астравы',
	'MK' => 'Македонія, БЮР',
	'ML' => 'Малі',
	'MM' => 'М’янма',
	'MN' => 'Манголія',
	'MO' => 'Макаа',
	'MP' => 'Паўночныя Марыянскія астравы',
	'MQ' => 'Марцініка',
	'MR' => 'Маўрытанія',
	'MS' => 'Мантсерат',
	'MT' => 'Мальта',
	'MU' => 'Маўрыкій',
	'MV' => 'Мальдывы',
	'MW' => 'Малаві',
	'MX' => 'Мексіка',
	'MY' => 'Малайзія',
	'MZ' => 'Мазамбік',
	'NA' => 'Намібія',
	'NC' => 'Новая Каледонія',
	'NE' => 'Нігер',
	'NF' => 'Востраў Норфалк',
	'NG' => 'Нігерыя',
	'NI' => 'Нікарагуа',
	'NL' => 'Нідэрланды',
	'NO' => 'Нарвегія',
	'NP' => 'Непал',
	'NR' => 'Науру',
	'NU' => 'Ніуэ',
	'NZ' => 'Новая Зеландыя',
	'OM' => 'Аман',
	'PA' => 'Панама',
	'PE' => 'Перу',
	'PF' => 'Французская Палінезія',
	'PG' => 'Папуа — Новая Гвінея',
	'PH' => 'Філіпіны',
	'PK' => 'Пакістан',
	'PL' => 'Польшча',
	'PM' => 'Сен-П’ер і Мікелон',
	'PN' => 'Астравы Піткэрн',
	'PR' => 'Пуэрта-Рыка',
	'PS' => 'Палестынскія тэрыторыі',
	'PT' => 'Партугалія',
	'PW' => 'Палау',
	'PY' => 'Парагвай',
	'QA' => 'Катар',
	'QO' => 'Вонкавая Акіянія',
	'RE' => 'Рэюньён',
	'RO' => 'Румынія',
	'RS' => 'Сербія',
	'RU' => 'Расія',
	'RW' => 'Руанда',
	'SA' => 'Саудаўская Аравія',
	'SB' => 'Саламонавы Астравы',
	'SC' => 'Сейшэльскія Астравы',
	'SD' => 'Судан',
	'SE' => 'Швецыя',
	'SG' => 'Сінгапур',
	'SH' => 'Святой Алены, Востраў',
	'SI' => 'Славенія',
	'SJ' => 'Свальбард (Паўночна-Усходняя Зямля) і Ян-Маен',
	'SK' => 'Славакія',
	'SL' => 'Сьера-Леонэ',
	'SM' => 'Сан-Марына',
	'SN' => 'Сенегал',
	'SO' => 'Самалі',
	'SR' => 'Сурынам',
	'SS' => 'Паўднёвы Судан',
	'ST' => 'Сан-Тамэ і Прынсіпі',
	'SV' => 'Сальвадор',
	'SY' => 'Сірыя',
	'SZ' => 'Свазіленд',
	'TC' => 'Цёркс і Кайкас',
	'TD' => 'Чад',
	'TF' => 'Французскія Паўднёвыя тэрыторыі',
	'TG' => 'Тога',
	'TH' => 'Тайланд',
	'TJ' => 'Таджыкістан',
	'TK' => 'Такелау',
	'TL' => 'Усходні Тымор',
	'TM' => 'Туркменістан',
	'TN' => 'Туніс',
	'TO' => 'Тонга',
	'TR' => 'Турцыя',
	'TT' => 'Трынідад і Табага',
	'TV' => 'Тувалу',
	'TW' => 'Тайвань',
	'TZ' => 'Танзанія',
	'UA' => 'Украіна',
	'UG' => 'Уганда',
	'US' => 'Злучаныя Штаты Амерыкі',
	'UY' => 'Уругвай',
	'UZ' => 'Узбекістан',
	'VA' => 'Ватыкан',
	'VC' => 'Сент-Вінсент і Грэнадзіны',
	'VE' => 'Венесуэла',
	'VG' => 'Брытанскія Віргінскія астравы',
	'VI' => 'Амерыканскія Віргінскія астравы',
	'VN' => 'В’етнам',
	'VU' => 'Вануату',
	'WF' => 'Уоліс і Футуна',
	'WS' => 'Самоа',
	'YE' => 'Емен',
	'YT' => 'Востраў Маёта',
	'ZA' => 'Паўднёва-Афрыканская Рэспубліка',
	'ZM' => 'Замбія',
	'ZW' => 'Зімбабвэ',
);

$timeUnits = array(
	'day-few' => '{0} дні',
	'day-many' => '{0} дзён',
	'day-one' => '{0} дзень',
	'day-other' => '{0} дня',
	'hour-few' => '{0} гадзіны',
	'hour-many' => '{0} гадзін',
	'hour-one' => '{0} гадзіна',
	'hour-other' => '{0} гадзіны',
	'minute-few' => '{0} хвіліны',
	'minute-many' => '{0} хвілін',
	'minute-one' => '{0} хвіліна',
	'minute-other' => '{0} хвіліны',
	'month-few' => '{0} месяца',
	'month-many' => '{0} месяцаў',
	'month-one' => '{0} месяц',
	'month-other' => '{0} месяца',
	'second-few' => '{0} сэкунды',
	'second-many' => '{0} сэкунд',
	'second-one' => '{0} сэкунда',
	'second-other' => '{0} сэкунды',
	'week-few' => '{0} тыдні',
	'week-many' => '{0} тыдняў',
	'week-one' => '{0} тыдзень',
	'week-other' => '{0} тыдня',
	'year-few' => '{0} гады',
	'year-many' => '{0} гадоў',
	'year-one' => '{0} год',
	'year-other' => '{0} году',
);

**Comment by paladox** [comment]
I ran php code sniffer on windows

**Comment by aik099** [comment]
Looks like you're not passing `--encoding=utf8` when running `phpcs` command.

**Comment by paladox** [comment]
Hi no but it shoulden be doing that.

**Comment by gsherwood** [comment]
You need to pass `--encoding=utf-8` to tell PHPCS to do extra processing on strings. This slows things down a little, but it gets rid of these (and other) errors.

You can also set your default encoding: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options#setting-the-default-encoding

Or hard-coded it into a ruleset.xml file: `<arg name="encoding" value="utf-8"/>`

Does that make sense?
