### ISSUE TITLE
`switch` related problem when using PSR2 standard

### ISSUE THREAD

**Issue by raincious** [squizlabs/PHP_CodeSniffer#735]
So, this happened after I committed my code:
![](https://cloud.githubusercontent.com/assets/4244947/10332045/eec535e2-6d0c-11e5-8e09-8c5d132e1dfb.png) 
Notice the CI (running `dev-master` version of the PHP_CodeSniffer) tells me my code had problem, and my local `phpcs` (stable version `2.3.4`) tell my everything is fine.

And I don't think there should be 16 spaces right? :P

Please investigate.

Code example:
https://github.com/raincious/facula/blob/4b1bc7bfe754b5031f015f094ed4a567e455d518/src/Facula/Base/Tool/Misc/ConfigParser.php#L129

CI Result:
https://travis-ci.org/raincious/facula/jobs/84041382

Minimized example code:

    function blabla()
    {
        switch ($dataType) {
            case static::DATA_LIST:
            case static::DATA_LIST_FORMATSTR:
            case static::DATA_HASHTABLE:
                return array();
            case static::DATA_VECTOR:
                return '';
        }

        throw new Exception\FailedGetDataTypeBase(
            $dataType
        );
    }

Result:

    $ ./vendor/bin/phpcs /tmp/phpcstest.php --standard=PSR2

    FILE: /tmp/phpcstest.php
    ----------------------------------------------------------------------
    FOUND 1 ERROR AFFECTING 1 LINE
    ----------------------------------------------------------------------
     10 | ERROR | [x] Line indented incorrectly; expected 12 spaces,
        |       |     found 8
    ----------------------------------------------------------------------
    PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
    ----------------------------------------------------------------------

And if I change above code to:

    function blabla()
    {
        switch ($dataType) {
            case static::DATA_LIST:
            case static::DATA_LIST_FORMATSTR:
            case static::DATA_HASHTABLE:
                return; // Notice this line. bool, integer, string etc will also work.
            case static::DATA_VECTOR:
                return '';
        }

        throw new Exception\FailedGetDataTypeBase(
            $dataType
        );
    }

It passes. 

I heavily suspect it related to `()[]` symbol matching.

**Comment by aik099** [comment]
@raincious , any more details you can provide about this problem except that it's `switch` and PSR-2 related?

**Comment by raincious** [comment]
Hi @aik099, 

Sorry, my Internet is slow, I had to disconnect and reconnect my VPN 6 times to get the issue posted. Which caused the delay and other chaos :(

The information I had already pasted. If you need anything else, please reply.

**Comment by aik099** [comment]
There was 2 or 3 fixes to sniff that checks indentation that are only present in `master`. This might as well be the cause why no error shown using `master` version of PHP_CodeSniffer.

**Comment by gsherwood** [comment]
This is a bug in the dev version of the code that is not present in the current stable release. Thanks for reporting it.
