### ISSUE TITLE
Download url per version

### ISSUE THREAD

**Issue by javaguirre** [squizlabs/PHP_CodeSniffer#739]
Hi!

It would be nice to have an url per version of `phpcs` `phpcbf`, so you could install different versions and knowing which one you are supposed to be downloading.

Instead of having:

`https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar`

We could have

`https://squizlabs.github.io/PHP_CodeSniffer/2.3.4/phpcs.phar`

Thank you!

**Comment by aik099** [comment]
There are already. On the releases page (see https://github.com/squizlabs/PHP_CodeSniffer/releases) each version have PHAR in that version attached.

**Comment by javaguirre** [comment]
You are right! Silly me. :-)
