### ISSUE TITLE
Enhancement to the Squiz_Sniffs_Commenting_FileCommentSniff Sniff

### ISSUE THREAD

**Issue by techxplorer** [squizlabs/PHP_CodeSniffer#747]
Hi,

Would you consider making the author and copyright values in the [Squiz_Sniffs_Commenting_FileCommentSniff](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/Squiz/Sniffs/Commenting/FileCommentSniff.php) sniff properties that could be overridden by configuration? 

I'm using many of the other comment related tests for my own development, and would like to be able to use this one as well. However I don't want to create my own standard for just one sniff. 

If you would consider it, and would prefer a pull request, please let me know.

**Comment by gsherwood** [comment]
I've been meaning to remove them for a long time. I'd be happy to make them configurable instead. If you'd like to submit a PR, please do so. It would make things move a lot faster.

**Comment by techxplorer** [comment]
Hi,

I've been working on this issue, the progress commit is [available here](https://github.com/techxplorer/PHP_CodeSniffer/commit/3f9b3548ab437e918806d3a2a0bd127319a1c703).

The unit tests are failing for the author tag sniff, which is odd as my changes are not substantial. I've had a quick look and it appears that with my changes in place the fixer is not enabled. 

Could you investigate and let me know what I'm getting wrong?

**Comment by gsherwood** [comment]
I got this when running your new sniff: PHP Notice:  Undefined property: Squiz_Sniffs_Commenting_FileCommentSniff::$expectedCopyright in /Users/gsherwood/Sites/Projects/PHP_CodeSniffer/CodeSniffer/Standards/Squiz/Sniffs/Commenting/FileCommentSniff.php on line 159

You're using the wrong member var name inside your code. Fixing that gets the tests passing again.

Just a quick related comment: I don't think having the regex as a member var is a good idea. It looks very error prone, and you've hard-coded the fact that the years should be in the fixed version as well with `str_replace('xxxx-xxxx', '', $this->expectedCopyright)`.

I think the sniff should enforce the copyright years bit, but allow you to decide what string goes after that. Then you don't need a regex sitting in a ruleset.xml file.

It might also be worth considering breaking author into a name and email. This, along with the copyright change, would allow the sniff to enforce a specific format for these tags, but not make assumptions about the values that go in there.

So I'd have member vars like: authorName, authorEmail, copyrightName, copyrightMinYear

Then figure out the formats and regexes from those values.

**Comment by techxplorer** [comment]
Hi @gsherwood,

Apologies in taking so long to reply. I've amended the commit and have a new progress commit [available here](https://github.com/techxplorer/PHP_CodeSniffer/commit/4d90c5c0cd405406881b7a8466700054a46cbd1c).

The tests now pass, except for the ones related to fixing the copyright message. When I run the unit tests I get this:

 ```
$ phpunit

PHPUnit 5.0.0 by Sebastian Bergmann and contributors.

...............................................................  63 / 222 ( 28%)
...S........................................................... 126 / 222 ( 56%)
......F...............................SS....................... 189 / 222 ( 85%)
..............................S..                               222 / 222 (100%)

Tests generated 599 unique error codes; 327 were fixable (54.59%)

Time: 17.25 seconds, Memory: 58.00Mb

There was 1 failure:

1) Squiz_Tests_Commenting_FileCommentUnitTest::testSniff
Failed to fix 3 fixable violations in FileCommentUnitTest.inc
Failed to fix 3 fixable violations in FileCommentUnitTest.js

/Users/techxplorer/github/PHP_CodeSniffer/tests/Standards/AbstractSniffUnitTest.php:172
/Users/techxplorer/github/PHP_CodeSniffer/tests/TestSuite.php:48

FAILURES!
Tests: 222, Assertions: 81, Failures: 1, Skipped: 4.
```

What am I missing? 

Many thanks for your continued patience.

-Corey

**Comment by oanhnn** [comment]
I think we need a sniff for `FileComment` like HeaderComment of `php-cs-fixer`

```
<?php
class Squiz_Sniffs_Commenting_FileCommentSniff implements PHP_CodeSniffer_Sniff
{
    /**
     * The expected header comment.
     *
     * @var string
     */
    public $headerComment = '';

    // ...
}
```

**Comment by gsherwood** [comment]
Closed along with the PR.
