### ISSUE TITLE
Bump php requirement to 5.2 or 5.3

### ISSUE THREAD

**Issue by paladox** [squizlabs/PHP_CodeSniffer#755]
Please bump the required php version to 5.2 or 5.3 preferably 5.3 since I woulden think a lot of people use php 5.1 or 5.2. And this would allow us to use more of the features avalible in 5.3.

**Comment by gsherwood** [comment]
I can't change a major requirement like that in a minor release - I'd need to wait for version 3.0.

And that's exactly what I did in version 3.0, which is here: https://github.com/squizlabs/PHP_CodeSniffer/tree/3.0

The new requirement is 5.4: https://github.com/squizlabs/PHP_CodeSniffer/blob/3.0/src/Runner.php#L224

**Comment by paladox** [comment]
Hi could the requirement be instead of 5.4 be 5.3. Since 5.3 is more widely used. Including in Wikimedia which use this software.

**Comment by gsherwood** [comment]
I use 5.3 in production as well because we run RHEL servers, but 3.0 isn't going to be released this year, so 5.4 might be fine once it comes out. So far, I really only need 5.3 features, so it may work on 5.3 as well.

**Comment by paladox** [comment]
Ok. next year if php 5.3 usage hasent decreased and not many have upgraded to 5.6 or 7 could we keep 5.3 support please.

**Comment by gsherwood** [comment]
Maybe. I can't make a call on that now.
