### ISSUE TITLE
PHAR: Improve installation for different versions

### ISSUE THREAD

**Issue by helmer** [squizlabs/PHP_CodeSniffer#759]
I am looking for a phar package of v2.3.2, the installation guide gives me the latest. Do you keep older packages around and accessible?

If yes, perhaps you could update the installation guide to be able to pinpoint a specific version for download?

Cheers!

**Comment by gsherwood** [comment]
> Do you keep older packages around and accessible?

Nope.

**Comment by helmer** [comment]
Damn, shucks. Thanks.

**Comment by aik099** [comment]
There are PHARs for each release at https://github.com/squizlabs/PHP_CodeSniffer/releases page.
