### ISSUE TITLE
Consider UTF-8 as the default encoding

### ISSUE THREAD

**Issue by item4** [squizlabs/PHP_CodeSniffer#760]
I heared some incomprehensible feature about phpcs.

I'm Korean and I can write source with korean.

But, We(=Korean) must use phpcs with `--endoing=utf-8` option. If we didn't, we encountered some message like "line is too long".

I think default encoding must be utf-8. Some RDF about PHP 7 features say ["UTF-8 is now the de facto standard encoding for PHP"](https://wiki.php.net/rfc/unicode_escape)

How do you think about change default encoding?

**Comment by aik099** [comment]
For historical reasons only I guess. Changing default encoding in feature release would be considered as BC break for people that rely on fact, that default encoding isn't UTF-8.

In 3.0 release I guess it's possible to change default encoding value.

For now I recommend you:
* if you're using custom standard, then add `<arg name="encoding" value="utf-8"/>` to it
* if you're using built-in standard, then create `phpcs.xml` file with basically same content (of course add root node around it)

**Comment by gsherwood** [comment]
I am considering it as the default for 3.0, but I can't make a big BC break like that in 2.0. It also requires a PHP extension that is not universally installed, so I have to check for that as well.

**Comment by item4** [comment]
@gsherwood Can you add milestone to it for don't forget?

**Comment by barbu110** [comment]
Anything on this yet?

**Comment by gsherwood** [comment]
> Anything on this yet?

My last comment is still the current status.

**Comment by gsherwood** [comment]
This is now done in the 3.0 branch. The iconv functions will be used by default as long as that extension has not been disabled.
