### ISSUE TITLE
Class Anonymous problem

### ISSUE THREAD

**Issue by oxman** [squizlabs/PHP_CodeSniffer#763]
Hello,

            $test = new class() implements MapperToDatabase

With this code, phpcs say : Class name "()" is not in camel caps format

**Comment by aik099** [comment]
Probably not all PHP_CodeSniffer sniffs are PHP 7 compatible.

**Comment by gsherwood** [comment]
Added support here, although no sniffs will be checking anon classes yet given that they are likely to have very different rules: https://github.com/squizlabs/PHP_CodeSniffer/commit/bb107695fafae1a55d188eaf2b0a8d17f4e7c283
