### ISSUE TITLE
PHP tokenizer resolves bitwise xor operator as power operator

### ISSUE THREAD

**Issue by smatyas** [squizlabs/PHP_CodeSniffer#765]
The exponentiation arithmetic operator in PHP is `**`, and only exists since PHP 5.6
The `^` operator is only the bitwise XOR operator.

See: 
http://php.net/manual/en/language.operators.arithmetic.php
http://php.net/manual/en/language.operators.bitwise.php

The wrong code is here: https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Tokenizers/PHP.php#L1307

```
        case '^':
            $newToken['type'] = 'T_POWER';
            break;
```

I'm not familiar enough with PHP_CodeSniffer's code yet, so I cannot make a PR now, but I'm sure that this is a tokenizer bug.

**Comment by gsherwood** [comment]
I'm pretty sure that's always been like that, and I have no idea why. Thanks for picking it up.

**Comment by smatyas** [comment]
Thanks for the fix, great work! :)
