### ISSUE TITLE
Syntax error when stripping trailing PHP close tag and previous statement has no semicolon

### ISSUE THREAD

**Issue by adduc** [squizlabs/PHP_CodeSniffer#773]
When running CBF with the PSR-2 standard against the sample file below, the trailing PHP close tag is omitted from output, causing a syntax error. 

### Sample File

```php
<?php echo $data ?>


```

### Output
```php
<?php echo $data
```

**Comment by bpicolo** [comment]
The stripped closing tag seems right. Semicolon is missing though

**Comment by gsherwood** [comment]
The semicolon is now added.
