### ISSUE TITLE
Incorrect checking for PHP7 return types on multi-line function declartions

### ISSUE THREAD

**Issue by oxman** [squizlabs/PHP_CodeSniffer#781]
Hello,

With a code like that : 
```
    public function driverIsConnectedWithIdentifierForQuery(
        DriverInterface $driver,
        $identifier,
        QueryInterface $query
    ): ConnectionPool {
```
PHPCS : There must be a single space between the closing parenthesis and the opening brace of a multi-line function declaration

**Comment by gsherwood** [comment]
See my comment here: https://github.com/php-fig/fig-standards/issues/658#issuecomment-158761265
