### ISSUE TITLE
Conditional function declarations cause fixing conflicts in Squiz standard

### ISSUE THREAD

**Issue by klausi** [squizlabs/PHP_CodeSniffer#782]
The following file triggers an endless fixer loop when invoking `phpcbf --standard=Squiz Kint.class.php`

[Kint.class.php.txt](https://github.com/squizlabs/PHP_CodeSniffer/files/41163/Kint.class.php.txt)

Not sure how we should test for something like this when multiple fixers interfere with each other. In Drupal's Coder we always run all fixers on a file in unit tests to prevent interference of fixers.

**Comment by gsherwood** [comment]
Smallest bit of code to replicate:
```php
<?php
if ($foo) {
    function bar() {}
}
```

**Comment by gsherwood** [comment]
Thanks for reporting. That file is fixable now.
