### ISSUE TITLE
$this->trait is seen as a T_TRAIT token

### ISSUE THREAD

**Issue by msteltenpool** [squizlabs/PHP_CodeSniffer#784]
```php
public function register()
{
    return [T_TRAIT];
}
```

It will spot this '$this->trait' as a T_TRAIT that it needs to return. Didn't check the underlying reason, but my tests suddenly trigger on places where it shouldn't after the 2.4.0 update.

**Comment by aik099** [comment]
That seems to be a side effect from allowing parsing PHP 5.4+ code on PHP 5.3 and below, where T_TRAIT token doesn't exist. @gsherwood , we can just check if `{` is present (excluding whitespaces) after the `trait` word and only then consider it as T_TRAIT.

**Comment by gsherwood** [comment]
Thanks for reporting this.
