### ISSUE TITLE
SpacingAfterDefaultBreak confused by multi-line statements

### ISSUE THREAD

**Issue by okdana** [squizlabs/PHP_CodeSniffer#787]
Maybe i just don't understand its purpose, but i don't think the `Squiz.ControlStructures.SwitchDeclaration.SpacingAfterDefaultBreak` sniff behaves as expected wrt statements spanning multiple lines.

Test file:

```
<?php
switch ($foo) {
    default:
        throw new \Exception(
            'bar'
        );
}
```

PHPCS reports:

```
 4 | ERROR | [ ] Blank lines are not allowed after the DEFAULT case's
   |       |     breaking statement
   |       |     (Squiz.ControlStructures.SwitchDeclaration.SpacingAfterDefaultBreak)
```

Putting the statement on a single line (`throw new \Exception('bar');`) makes the error go away.

**Comment by gsherwood** [comment]
Thanks for reporting.

**Comment by okdana** [comment]
Thank you!
