### ISSUE TITLE
Allow optional @throws tags for RuntimeExceptions

### ISSUE THREAD

**Issue by mindplay-dk** [squizlabs/PHP_CodeSniffer#806]
There are generally two classes of exceptions - checked `Exception` types, and un-recoverable `RuntimeException` types.

Enforcing documentation of un-recoverable runtime exceptions with `@throws` doesn't make much sense - in fact, I find that it adds a lot of noise to my documentation, and it becomes very difficult (as a consumer) to know whether a documented exception condition is recoverable, e.g. intended for you to handle, or not.

**Comment by gsherwood** [comment]
Closing this as I can't see this change ever being made. Happy to review a PR anyone wants to submit though.
