### ISSUE TITLE
Zend Naming Convention Sniff bug

### ISSUE THREAD

**Issue by ARH-Digital** [squizlabs/PHP_CodeSniffer#810]
Using Zend rules. 
Zend/Sniffs/NamingConventions/ValidVariableNameSniff.php

Incorrectly ignores T_OBJECT_OPERATOR,
example, 

`$Index->short_name = $Data;`
`135 | ERROR | Variable "short_name" is not in valid camel caps format`

`short_name` should not be considered a variable, or it should be excluded due to the operator. This is a snake_cased value for a database column. It is not proceeded by a $ either.

**Comment by gsherwood** [comment]
There is no way for PHPCS to know if that member var has been set with an invalid name, or if it has been set to match a DB column name, or if it is being access using __get(). Either way, the member var name is now in the correct format and so it throws an error.

The alternative is to never check any accessed member vars. I'm not sure that it is a good change.

**Comment by aik099** [comment]
In my standard I've modified the `ValidVariableNameSniff` to only check class property declaration, not usage. This way if the property name is wrong I get 1 error instead lots of them on every usage place.

**Comment by arlaneenalra** [comment]
I just ran into this.. Looking at the code I can see a few possible fixes ...

- Remove this block: 
 https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/Zend/Sniffs/NamingConventions/ValidVariableNameSniff.php#L83-L112
  Which would get rid of all reference time checks of member vars ..
 - Change the reported sniff here https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/Zend/Sniffs/NamingConventions/ValidVariableNameSniff.php#L104 to match the sniff here https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/Zend/Sniffs/NamingConventions/ValidVariableNameSniff.php#L185  This should probably also be done on the contains Numbers sniffs and would make this a maskable sniff while maintaining the disallowance of snake_case for variables in the local scope.  I'll probably be throwing a PR out there in a bit ...

**Comment by gsherwood** [comment]
Closing this as this isn't a change I intend to make to the sniff.
