### ISSUE TITLE
Add option to force all errors to display, even within @codingStandardsIgnore sections

### ISSUE THREAD

**Issue by davidscotson** [squizlabs/PHP_CodeSniffer#811]
If you're running CodeSniffer against code written by other people, you might want to get a full report of potential issues without giving them the ability to suppress any errors by using // @codingStandardsIgnore comments to skip files, or lines.

Reading through the docs there doesn't seem to be an override setting that allow this level of reporting.

**Comment by gsherwood** [comment]
I've added an `--ignore-annotation` CLI argument to ignore all `@codingStandard..`. code comments. You can also set this value in a ruleset.xml file if you don't want to allow these annotations in your coding standard.
