### ISSUE TITLE
Long method arguments should allow brace on same line as closing )

### ISSUE THREAD

**Issue by angelsk** [squizlabs/PHP_CodeSniffer#814]
http://www.php-fig.org/psr/psr-2/#4-4-method-arguments

```
    public function aVeryLongMethodName(
        ClassTypeHint $arg1,
        &$arg2,
        array $arg3 = []
    ) {
        // method body
    }
```

Currently I have the same set up, but am getting the following error when running phpcs; am I missing something?

```
    |  ERROR | [x] Opening brace should be on a new line
    |        |     (Generic.Functions.OpeningFunctionBraceBsdAllman.BraceOnSameLine)
```

**Comment by gsherwood** [comment]
I can't replicate any errors. This is the sample file I am using for testing:
```php
<?php
namespace Foo;

class Bar
{
    public function aVeryLongMethodName(
        ClassTypeHint $arg1,
        &$arg2,
        array $arg3 = []
    ) {
        // method body
    }
}
```
What version of PHPCS are you using? And what command are you running?

**Comment by angelsk** [comment]
Ah, it must be the coding standards I'm using. Will report over there, thank you.
