### ISSUE TITLE
Ignoring anything with "documents" ignores everything

### ISSUE THREAD

**Issue by rdoursenaud** [squizlabs/PHP_CodeSniffer#816]
Just lost a few hours trying to figure this one out.

Tried
```
phpcs --ignore=documents […]
```
and in my ruleset.xml
```xml
<exclude-pattern>documents</exclude-pattern>
```
Both leads to 0 files in queue instead of the 2349 expected in my use case.

```
phpcs --version
PHP_CodeSniffer version 2.4.0 (stable) by Squiz (http://www.squiz.net)
```

Please let me know if you need any debugging informations.

**Comment by aik099** [comment]
1. there is such `--ignore` command line option
2. you need to specify the actually scanned directly to the `phpcs` command and then the `exclude-pattern` would not scan `documents` sub-folder folders in given folder (yes it's recursive)

**Comment by rdoursenaud** [comment]
@aik099 Yes, I'm aware of the command.
I'm reporting that it does not work as expected when the parameter is "documents":
- Passing --ignore=documents ignores all my files!
- Passing anything else works a treat.

Please see the following screecast to better understand the problem https://asciinema.org/a/85flj6rjt61kjun7ohr7acr0b

**Comment by rdoursenaud** [comment]
Realized that the check is on the full path.
And of course, I had a "documents" directory in the path above the one one I was checking.
So the feature indeed works as intended.
Sorry for the noise!
