### ISSUE TITLE
Install PHPCompatibility

### ISSUE THREAD

**Issue by hadisajj2** [squizlabs/PHP_CodeSniffer#817]
I just installed CodeSniffer using Pear. So I can run the phpcs command etc. How can I install PHPCompatibility? I didn't pull anything directly from git.

**Comment by gsherwood** [comment]
That project lives here: https://github.com/wimg/PHPCompatibility

It seems to have clear install instructions, so I'd try following those first. I don't have any involvement with that project, so it's best to ask over there if you have any problems.
