### ISSUE TITLE
Squiz CSS standard and media queries

### ISSUE THREAD

**Issue by vrobic** [squizlabs/PHP_CodeSniffer#818]
Hi,

I'm having an issue using Squiz standard.

```
@media (max-width: 767px) {
    .white {
        color: #ffffff;
    }
    .black {
        color: #000000;
    }
}
```

The `Squiz.CSS.DuplicateStyleDefinition.Found` sniff sees that the `colour` statement is duplicated. But it's not! It's not in the same class definition. It seems that the tokenizer ignores the 2nd level class definitions.

**Comment by gsherwood** [comment]
This is a duplicate of #622. I still don't have a solution, but it is on my todo still.
