### ISSUE TITLE
whitelist sanitization usages when input var is used in array_key_exists()

### ISSUE THREAD

**Issue by paulschreiber** [squizlabs/PHP_CodeSniffer#821]
Per https://github.com/Automattic/Co-Authors-Plus/pull/310

I had made this change:
```diff
-		if ( isset( $_REQUEST['filter'] ) && array_key_exists( $_REQUEST['filter'], $this->filters ) ) {
+		if ( isset( $_REQUEST['filter'] ) && array_key_exists( sanitize_text_field( wp_unslash( $_REQUEST['filter'] ) ), $this->filters ) ) {
```
It was suggested by @mjangda and @westonruter that this wasn't necessary and `array_key_exists()`  and `in_array()` could be whitelisted.

**Comment by gsherwood** [comment]
This isn't a check provided by PHP_CodeSniffer. It's probably a custom sniff for WordPress. You'll need to file a bug with whoever manages the WP standard.
