### ISSUE TITLE
PEAR.Functions.FunctionCallSignature broken when closure uses return types

### ISSUE THREAD

**Issue by Majkl578** [squizlabs/PHP_CodeSniffer#835]
The following code is considered as invalid:
```php
<?php

array_filter(
    [1, 2],
    function ($i) : bool {
        return $i === 0;
    }
);
```

Although the indenation is correct, the error is generated: `Multi-line function call not indented correctly; expected 4 spaces but found 8.` Note that when you remove `: bool`, it works fine.
Affects phpcbf as well (changes code to invalid format).

**Comment by gsherwood** [comment]
Thanks for reporting this bug.
