### ISSUE TITLE
phpcs.phar hangs in Windows

### ISSUE THREAD

**Issue by relipse** [squizlabs/PHP_CodeSniffer#837]
I'm on Win 10 and if I run php phpcs.phar -h it shows the help, but if I run
```$ php phpcs.phar drupal-b/sites/howto/css/howto.css```

it just hangs.
I tried also downloading the source and doing 
```php PHP_CodeSniffer-2.5.0/scripts/phpcs ../web/drupal-b/sites/howto/```
but it also just hangs.

Any ideas? By the way I am using Git Bash mingw64 to execute commands.

**Comment by relipse** [comment]
Ok I finally got it to work doing something like this:
```cd /c/util/apps/PHP_CodeSniffer-2.5.0``

```php scripts/phpcs.php --standard=PSR2 --extensions=php,module,inc,test,profile,theme,css,js ../../web/drupal-b/sites/howto/css/howto.css```

**Comment by gsherwood** [comment]
This has previously been reported as bug #831 and has been fixed but not released (I don't have the time right now due to holidays). A work-around is to specify a standard using `--standard` as you have done.
