### ISSUE TITLE
Allow CLI args specified in ruleset.xml files to be relative to the ruleset file location

### ISSUE THREAD

**Issue by JohnMaguire** [squizlabs/PHP_CodeSniffer#847]
Hi, I'm the implementer of the bootstrap file functionality. I discussed a little bit in #793 how we wanted to use it to be able to set some options prior to our running of the sniffs (for example, setting the `$allowedTypes` class member.) Unfortunately, we ran into an issue given the fact that there's no relative way to set the `bootstrap` file.

We ship our CodeSniffer configuration in its own repository: https://github.com/barracudanetworks/Cuda-PHP-Code-Standards/

We have dozens of repositories that use it (we include it as a submodule, or you can just clone it once and setup your editor to look at the main repository.) The issue is that we need a way to be able to define the `bootstrap` file in the `ruleset.xml`, but we have no way of knowing the user's system layout (Do you keep your repos in `/home/jmaguire/repos`? `/Users/jmaguire/repos`? `/Users/jmaguire/Repositories`? What did you name the `Cuda-PHP-Code-Standards` clone?)

It'd be great to get support for this.

**Comment by gsherwood** [comment]
I'm going to use `chdir()` to make all relative paths inside ruleset CLI args be relative to the ruleset, but I want to release a 2.5.1 bugfix before I make a change like this.

If you'd like to test it out beforehand, you can apply this diff to CodeSniffs.php:
```
diff --git a/CodeSniffer.php b/CodeSniffer.php
index 19ea3e6..66927d8 100644
--- a/CodeSniffer.php
+++ b/CodeSniffer.php
@@ -831,7 +831,13 @@ class PHP_CodeSniffer
         }

         if (empty($cliArgs) === false) {
+            // Change the directory so all relative paths are worked
+            // out based on the location of the ruleset instead of
+            // the location of the user.
+            $currentDir = getcwd();
+            chdir($rulesetDir);
             $this->cli->setCommandLineValues($cliArgs);
+            chdir($currentDir);
         }

         // Process custom sniff config settings.
```

**Comment by aik099** [comment]
Support for T_SPACESHIP operator seems like a feature, not a bugfix. This way it should be 2.6.0 release.

**Comment by gsherwood** [comment]
> Support for T_SPACESHIP operator seems like a feature, not a bugfix. This way it should be 2.6.0 release.

It's a bug because it wasn't set as an operator and PHPCS didn't properly support PHP7. There is no BC break either. The next release will be 2.5.1, hopefully next week.

**Comment by aik099** [comment]
Ok.

**Comment by gsherwood** [comment]
Change has been pushed now that 2.5.1 is out.

**Comment by JohnMaguire** [comment]
:+1: Thank you! Sorry, I was hoping to test this out but didn't get a chance. It looks like this will work great though! Really appreciate this.
