### ISSUE TITLE
The "PSR1_Sniffs_Methods_CamelCapsMethodNameSniff" constructor has no effect

### ISSUE THREAD

**Issue by aik099** [squizlabs/PHP_CodeSniffer#849]
In the `PSR1_Sniffs_Methods_CamelCapsMethodNameSniff` class the parent constructor is called, but it doesn't accept any arguments.

There are several solutions possible:

1. remove constructor call (because both classes have identical constructor)
2. make parent constructor accept all 3 arguments, but default to currently used values, when not given
3. something else

Issues created as per discussion in #840.

**Comment by gsherwood** [comment]
It's a copy/paste error I think. I'll just remove the constructor.

**Comment by aik099** [comment]
Thanks.
