### ISSUE TITLE
Link to the example phpcs.xml in wiki is broken

### ISSUE THREAD

**Issue by nemeth** [squizlabs/PHP_CodeSniffer#850]
Since the phpcs.xml was renamed to phpcs.xml.dist in [commit 673474](https://github.com/squizlabs/PHP_CodeSniffer/commit/673474) the link to the example file [in the wiki](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#using-a-default-configuration-file) is broken.

**Comment by gsherwood** [comment]
Thanks for reporting this. I've fixed the link and rewritten that section of the docs slightly as I realised I forgot to do that during the last release.
