### ISSUE TITLE
composer custom standard

### ISSUE THREAD

**Issue by gondo** [squizlabs/PHP_CodeSniffer#856]
where should i install custom standard when i've installed CodeSniffer via composer globally?
`which phpcs` yells `/Users/user/.composer/vendor/bin/phpcs`

**Comment by aik099** [comment]
You can place your standard anywhere you like and then specify absolute path to it via `--standard` option in your `phpcs` or `phpcbf` command.

**Comment by gondo** [comment]
cool thanks
