### ISSUE TITLE
Create a new kind of annotation to ignore some specific rules inside a class, method, ...

### ISSUE THREAD

**Issue by benjamin-rtblw** [squizlabs/PHP_CodeSniffer#866]
I've two classes as following : 

```php
<?php
interface MyInterface
{
    public function myMethod($myParameter);
}

class MyClassConcrete implements MyInterface
{
    public function myMethod($myParameter)
    {
        // Parameter $myParameter not used here but required to respect interface declaration
    }
}

?>

```

It would be great to create the following annotation :
@suppressWarnings(PHPCS.Generic.CodeAnalysis.UnusedFunctionParameter)

What do you think ?

**Comment by gsherwood** [comment]
It is probably best done using the existing annotation style rather than having PHPCS parse docblocks. There is a request for that already (#604), so I'll close this one. Feel free to comment over there on possible alternative syntax.

**Comment by navarr** [comment]
I think having PHPCS parse dockblocks would be better.  It's the way PHPMD does it and it ends up being a lot cleaner.
