### ISSUE TITLE
Incorrect detection of blank lines between CSS class names 

### ISSUE THREAD

**Issue by h3xx** [squizlabs/PHP_CodeSniffer#872]
This may just be an issue of a confusing error message. What the error message state is not what the file contains. It reports the presence of "blank lines" even though there are **no blank lines in the file**.

Tested using version dc42502de400bb8b860b4960c5bc05fa30d8635e.

Sniffs affected:
* Squiz.CSS.ClassDefinitionNameSpacing.BlankLinesFound

Files affected:
* CodeSniffer/Standards/Squiz/Sniffs/CSS/ClassDefinitionNameSpacingSniff.php

Steps to reproduce:

Create a css file with the following contents:

    .foo,
    .bar
    {
        border: none;
    }

Run phpcs:

    phpcs --standard=Squiz -s --sniffs=Squiz.CSS.ClassDefinitionNameSpacing noblanks.css

This is the output:

    FILE: noblanks.css
    ----------------------------------------------------------------------
    FOUND 1 ERROR AFFECTING 1 LINE
    ----------------------------------------------------------------------
     3 | ERROR | Blank lines are not allowed between class names
       |       | (Squiz.CSS.ClassDefinitionNameSpacing.BlankLinesFound)
    ----------------------------------------------------------------------

**Comment by gsherwood** [comment]
Thanks for reporting this. The error is now gone.

I found a couple of unrelated errors in other sniffs for the same code, which I have also fixed here (https://github.com/squizlabs/PHP_CodeSniffer/commit/9a6fa4633f296d97879e46408198a9abddeba5d0) and here (https://github.com/squizlabs/PHP_CodeSniffer/commit/39bcf4e6f80f9d759ab0d644421599ecc959cf15).
