### ISSUE TITLE
Reports Error about some internal markup

### ISSUE THREAD

**Issue by tmcconechy** [squizlabs/PHP_CodeSniffer#874]
On the current bookmarklet (live)

- click to open - its on WCAGAA and seems correct
- select WCAGAAA - it reports and seems correct
- select WCAGAA again
- select WCAGAAA again

Each time the number of errors increases. Showing errors in some markup analytical tags....

{code}
...53325325.1453325328.8%3B&amp;"><img style="display: none;" src="http://www.google-analytics.com/__utm.gif?utmwv=0.0&amp;utmn=2029587981&amp;utmhn=localhost&amp;utmp=/controls/buttons&amp;utmac=UA-359178-17&amp;utme=8%28Standard*Errors*Warnings*Notices%299%28WCAG2AAA*7*8*46%29&amp;utmcc=__utma%3D111872281.316246636.1453302834.1453325325.1453325328.8%3B&amp;">
{code}

**Comment by gsherwood** [comment]
I think you meant to report this for HTML_CodeSniffer: https://github.com/squizlabs/HTML_CodeSniffer

**Comment by tmcconechy** [comment]
Yes, i did. Sorry.
