### ISSUE TITLE
Ignore specific warnings

### ISSUE THREAD

**Issue by anubisthejackle** [squizlabs/PHP_CodeSniffer#875]
I've read the Wiki and I can't find a way to do this. I'm building a standards ruleset custom, and I want to use the MultiLineFunctionDeclaration sniff, but I want to ignore the BraceOnSameLine warning, as we define all our classes as

```
class ClassName {
    ...
}
```

**Comment by aik099** [comment]
Relevant example from https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-ruleset.xml wiki page:

```xml
 <!--
    If you want to completely disable an error message in a sniff
    but you don't want to exclude the whole sniff, you can
    change the severity of the message to 0. In this case, we
    want the Squiz DoubleQuoteUsage sniff to be included in our
    standard, but we don't want the ContainsVar error message to
    ever be displayed.
 -->
 <rule ref="Squiz.Strings.DoubleQuoteUsage.ContainsVar">
  <severity>0</severity>
 </rule>
```

In example above the sniff name is `Squiz.Strings.DoubleQuoteUsage` and the error code it generates is `ContainsVar`.

In your case the error code would be something like `...MultiLineFunctionDeclaration.BraceOnSameLine` (replace `...` with complete name of the sniff).

**Comment by anubisthejackle** [comment]
Thank you that worked perfectly.

**Comment by aik099** [comment]
It's also a possibility to ask questions git Gitter chat channel at https://gitter.im/squizlabs/PHP_CodeSniffer .
