### ISSUE TITLE
Sniffing html inside of .php

### ISSUE THREAD

**Issue by corysimmons** [squizlabs/PHP_CodeSniffer#882]
Currently sniffs get spaces vs tabs in my php in my .php, but not in my html in my .php.

This means I can have tabs and spaces inside the same .php file.

Is there any configuration for enforcing sniffs in html in .php?

**Comment by aik099** [comment]
I think not, because phpcs doesn't check/tokenize html inside PHP files.

**Comment by corysimmons** [comment]
html inside .php is still php right?

**Comment by aik099** [comment]
Nope, it's HTML. The PHP tokenizer, that is used by PHP_CodeSniffer is just tokenizing it as one big string. It doesn't split it into lines to understand where indentation is or where it's actually thing like `<pre>` tag, where indentation matters.

**Comment by corysimmons** [comment]
Why doesn't it convert the entire file into a string instead of just stuff in between php tags? It's still a php file.

**Comment by aik099** [comment]
Indentation fixing doesn't work like this:

1. get file as a string
2. split by new line symbol
3. replace spaces with tabs

How it actually works is:

1. tokenize each file
2. process each token to identify tokens at the beginning of each line
3. determine based on PHP file structure (e.g. `{` and `}` around it) how intended it should be
4. apply needed indentation using 4 spaces (4 is configurable)
5. replace 4 spaces with 1 tab in places, where previous replacement has been made

**Comment by corysimmons** [comment]
Okay, so this isn't getting fixed right?

**Comment by aik099** [comment]
Let's wait for @gsherwood opinion on this. Maybe there is a way.

**Comment by gsherwood** [comment]
There is no technical limitation that prevents sniffing and fixing of leading whitespace in HTML. It wasn't a conscious decision not to do it - the sniffs just didn't evolve to look at content outside of the code.

I did a quick test by adding `T_INLINE_HTML` to the array here: https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/Generic/Sniffs/WhiteSpace/DisallowTabIndentSniff.php#L72

That works fine for both checking and fixing. I just need to do a bit more testing before I commit that.

**Comment by corysimmons** [comment]
Awesome! Thanks @gsherwood

**Comment by gsherwood** [comment]
That one-liner seems to have worked fine in both sniffs, so the change is committed.

**Comment by corysimmons** [comment]
Awesome @gsherwood Good work :100: :+1:
