### ISSUE TITLE
Squiz_Sniffs_Operators_ComparisonOperatorUsageSniff 

### ISSUE THREAD

**Issue by AlexHowansky** [squizlabs/PHP_CodeSniffer#886]
Not sure if I consider this a bug or a feature request. The Squiz_Sniffs_Operators_ComparisonOperatorUsageSniff will warn about using implicit true comparisons. For example, it disallows this:

```
if ($x) {
}
```

In favor of this:

```
if ($x === true) {
}
```

This is what I want. However, it also disallows standalone booleans:

```
while (true) {
}
```

And wants me to write:

```
while (true === true) {
}
```

Which seems rather silly. I think the standalone boolean usage should be an exception to this sniff. Thoughts?

**Comment by aik099** [comment]
Seems like a bug.

**Comment by gsherwood** [comment]
It is a bug, but has already been fixed in master. It's funny how a bug can exist in the codebase for so long and suddenly 3 people found it in the space of 2 weeks. Here is the commit: https://github.com/squizlabs/PHP_CodeSniffer/commit/490f858e449c4db5b9525525f9cbb0f823f2ddbf
