### ISSUE TITLE
Remove unnecessary/outdated //end comments

### ISSUE THREAD

**Issue by dereuromark** [squizlabs/PHP_CodeSniffer#895]
I wrote a sniffer to remove all those `//end method()` noise in the code.
This seems to be something from PHP3/4 and bears no value in modern PHP5/7 code IMO.
It is basically just noise, because every IDE can tell you very well, where what closes, additionally, the indentation makes this super clear.

If you are interested in removing this from your code as well, feel free to use (and inherit it into your sniffer package) that sniff.
Just check out my [sniffer](https://github.com/php-fig-rectified/psr2r-sniffer) and run this specific one:

    vendor/bin/phpcbf --standard=PSR2R/rulesuet.xml --sniffs=PSR2R.Commenting.NoControlStructureEndComment /path/to/your/sniffs

**Comment by gsherwood** [comment]
Thanks, but it's part of my coding standard so I'm not going to remove them.
