### ISSUE TITLE
[InvalidArgumentException] $from (/path/bin/phpcs) and $to () must be absolute paths

### ISSUE THREAD

**Issue by pawarsameer553** [squizlabs/PHP_CodeSniffer#905]
While installing it using composer, I got error like '[InvalidArgumentException] $from (/path/bin/phpcs) and $to () must be absolute paths'.  I'm using cakePHP.

**Comment by gsherwood** [comment]
You get this error while installing PHPCS or after installing PHPCS? PHPCS doesn't have any post-install scripts, so no code should be running.

If you mean that you are getting the error when just running PHPCS, I'll need more information to help replicate the issue.

Firstly, what command are you using the run PHPCS?

You say you are using cakePHP, but I don't know if that means you are checking the cakePHP code or you are using a custom cakePHP standard. What did you mean?

If you are using a custom coding standard, can you replicate the issue with any of the built-in standards, such as PEAR, PSR2 or Squiz? If not, the error is probably with the custom standard and you'll need to report a bug to them.

If you can replicate with a built-in standard, which standard caused the error? Can you also provide the code that you are running PHPCS on?

**Comment by pawarsameer553** [comment]
my composer.json file look like :
{
    "require-dev": {
        "phpunit/phpunit": "4.2.*",
         "squizlabs/php_codesniffer": "2.*"
    },
    "config": {
        "vendor-dir": "Vendor/"
    }
}

After running the 'composer update' command, it gives that error. It might not related to cakePHP as I already install other libraries using composer for cakePHP.

**Comment by gsherwood** [comment]
I can't replicate any problems during a composer install, which is to be expected given that no PHPCS code actually runs during install.

I think the errors you are getting is probably coming from composer itself and I suggest you open an issue with that project so they can help you debug it.

**Comment by neoplomero** [comment]
I have the same error, this ticket shouldn't be closed. And by the way @gsherwood you don't sound any helpful at all.

**Comment by jrfnl** [comment]
@neoplomero:
1. You are responding to a thread which is over three years old.
2. Aside from one person, nobody has reported similar issues in the past three years.
3. You are not providing any info with which anyone could even attempt to replicate the issue.
4. And then you straight off say that people are not being helpful ?

Hmm.. what do you expect ?

**Comment by gsherwood** [comment]
> I have the same error, this ticket shouldn't be closed.

I couldn't reproduce the issue and didn't receive any additional feedback, so it was closed. I haven't received any further reports of this issue until you, today, so it has not be looked at again.

If you have any additional information that would help me replicate the problem, please open a new issue and provide steps to replicate.

> And by the way @gsherwood you don't sound any helpful at all.

Thanks for the feedback, although I think I was appropriately helpful for the amount of feedback I received in this case. There is very little a maintainer can do when they cannot reproduce an issue. I need the person reporting the problem to be as invested in finding a solution as I am in those sort of cases. It didn't happen this time, but I'm confident that the thousands of hours I've put into this open source project show my willingness to help PHP developers enforce coding standards using PHPCS.

**Comment by neoplomero** [comment]
Found the solution, installing the unzip extension (centos, Ubuntu). And by the way... You're right my comment was silly, you're great. Thanks. 😊

**Comment by gsherwood** [comment]
> Found the solution, installing the unzip extension (centos, Ubuntu).

Good news. Thanks for posting the solution here.
