### ISSUE TITLE
Add an option --stop-on-failure

### ISSUE THREAD

**Issue by gnutix** [squizlabs/PHP_CodeSniffer#922]
I really like PHPUnit's options --stop-on-failure and --stop-on-error. Very useful for quality control, so it doesn't take minutes to run if there's an error in the first line it checks.

What about adding it for this tool too ? As it been discussed already (couldn't find an issue for that) ? Is it technically possible ?

**Comment by gsherwood** [comment]
PHPCS already has an interactive option. This pauses checking after the first file with errors is found. You then get the option of fixing that file manually and having PHPCS recheck it, or you can exit.

That feature has existed for over 6 years but isn't widely used. So I don't think adding additional options that do the same thing except force an exit is going to be that useful. Most people run PHPCS over individual file in an IDE, or they run it over an entire code base to produce a report and stats.

Maybe try that interactive option and see if you find it useful. Just add `-a` to the command line to use it. You'll end up with output like this:
```
FILE: temp.php
--------------------------------------------------------------------------
FOUND 2 ERROR(S) AND 1 WARNING(S) AFFECTING 1 LINE(S)
--------------------------------------------------------------------------
 2 | WARNING | Inline control structures are discouraged
 2 | ERROR   | Missing file doc comment
 2 | ERROR   | TRUE, FALSE and NULL must be lowercase; expected "true" but
   |         | found "TRUE"
--------------------------------------------------------------------------

<ENTER> to recheck, [s] to skip or [q] to quit :
```

**Comment by gnutix** [comment]
`echo -e 'q' | phpcs -a` works for me ! Thanks :D

**Comment by gsherwood** [comment]
Whatever works :)

**Comment by murrant** [comment]
That doesn't seem to work for me.  I think one use case that you may be discounting is git commit hooks.
