### ISSUE TITLE
The junit report format is not shown in the help output

### ISSUE THREAD

**Issue by torkiljohnsen** [squizlabs/PHP_CodeSniffer#923]
The help output `phpcs -h` does not list `junit` as a valid report format output under `<report>`.

**Comment by aik099** [comment]
Is `junit` format even supported? If so, then please send PR with a fix.

**Comment by torkiljohnsen** [comment]
It has been supported since 1.4.7, according to the [release notes](https://www.squizlabs.com/php-codesniffer/1.4.7-1.5.0rc4-released). I just tested it on 2.5.1 and it works fine. I use the junit output for XML reports in Circle CI (CI tool).

**Comment by gsherwood** [comment]
Not sure how I missed that. Thanks a lot for noticing and fixing it up.

**Comment by torkiljohnsen** [comment]
:+1:
