### ISSUE TITLE
CodeSniffer.conf packaged in PHAR is ignored

### ISSUE THREAD

**Issue by morozov** [squizlabs/PHP_CodeSniffer#949]
Starting release 2.3.1 (a90531b), CodeSniffer.conf placed inside PHAR is not considered when reading configuration data. The file instead is looked for in the same directory as the *.phar file itself.

The original behavior makes sense in cases when PHP_CodeSniffer is packaged as part of another application inside its own PHAR, and the package contains with the default settings (say I want the default standard to be PSR2 instead of PEAR).

A possible solution is to consider two files: the external file overrides the settings defined in internal file. All changes are saved to the external file.

**Comment by morozov** [comment]
@gsherwood do you mind reviewing #1254, please?

**Comment by gsherwood** [comment]
> do you mind reviewing #1254, please?

I'm sorry, but I don't know when I'm going to get time. My current focus is the 3.1.1 release, but I'm currently travelling for work and haven't been able to make progress on that either.

**Comment by gsherwood** [comment]
Closing this as it's not a feature I've had anyone else request and the config file is no longer as important (in terms of priority) as it once was. It can now be overwritten by standards and CLI args very easily, so packaging it probably isn't a good idea. It's for user preferences and not hard-coded dist values.
