### ISSUE TITLE
Null coalescing operator (??) not detected as a token

### ISSUE THREAD

**Issue by joelposti** [squizlabs/PHP_CodeSniffer#962]
I’m extending Squiz.WhiteSpace.OperatorSpacing to check for whitespace around elvis operator (?:) and null coalescing operator (??). I already managed to get the sniff to work correctly with elvis operator. The sniff is registered to listen to tokens `T_INLINE_THEN` and `T_INLINE_ELSE` which match the elvis operator correctly. I would have guessed that null coalescing operator would be equal to two `T_INLINE_THEN` tokens, but instead the operator is not detected at all. I could not find a token for the operator in `CodeSniffer/Tokens.php`.

**Comment by aik099** [comment]
I think token isn't supported currently and isn't considered as operator token. I've sent #844 PR before to add support for spaceship operator. You can send new PR for `??` operator using my PR as base.

**Comment by aik099** [comment]
> elvis operator 

Elvis operator, really? Maybe you wanted to say `elseif` operator?

**Comment by aik099** [comment]
Another thing is that PHP < 7.0 needs to recognize this new PHP 7 token as well to ease test writing.

**Comment by joelposti** [comment]
Thanks for the pull request tip! However, I do not believe we can add support for the null coalescing operator as easily because PHP itself does not provide a token for the operator (https://secure.php.net/manual/en/tokens.php). I believe it is required to code support for the operator into `CodeSniffer/Tokenizers/PHP.php`.

I really did mean to say elvis operator. Elvis operator is a compression of the ternary operator. `$oof = $foo ?: $bar` is equal to `$oof = $foo ? $foo : $bar`. https://en.wikipedia.org/wiki/Elvis_operator

**Comment by aik099** [comment]
> However, I do not believe we can add support for the null coalescing operator as easily because PHP itself does not provide a token for the operator (https://secure.php.net/manual/en/tokens.php)

That's not a problem. PHP_CodeSniffer has many useful tokens, that PHP tokenizer doesn't provide.

**Comment by joelposti** [comment]
I found out the token name while running phpcs in extra verbose mode (-vv). The token is `T_COALESCE`. If there is a space between the question marks (syntax error), they are recognized as two `T_INLINE_THEN` tokens. I’m in the process of creating a pull request.

**Comment by gsherwood** [comment]
Thanks for the report and the fix.
