### ISSUE TITLE
online documentation for sniffs

### ISSUE THREAD

**Issue by UziTech** [squizlabs/PHP_CodeSniffer#965]
is there online documentation for the sniffs

I noticed in the Standards folder there is a Docs folder in each standard with xml files for documentation but I don't see anything online.

It would be nice if a linter could link to documentation on a rule showing a valid and invalid example.

**Comment by aik099** [comment]
I haven't found any maintained website, but running `phpcs --generator=HTML` command would get you HTML of documentation built from specified/default standard`. The `HTML` can be replaced with `Text` or `Markdown`.

**Comment by gsherwood** [comment]
No, there is no online documentation. I've never had a spare moment to create a PHPCS website. If I ever do, I'll probably try and document the included sniffs up there, but I wouldn't hold my breath.
