### ISSUE TITLE
Sort methods of the classes

### ISSUE THREAD

**Issue by kodermax** [squizlabs/PHP_CodeSniffer#986]
I'd like to have feature which check sort functions in the class.

**Comment by gsherwood** [comment]
What exactly would be checked?

Is this something you think would be useful to many developers or is it specific to your own project? If it is specific, a custom sniff would be best.

**Comment by kodermax** [comment]
this is reareange code in phpstorm.
![image](https://cloud.githubusercontent.com/assets/590985/14910556/1567ce7c-0df7-11e6-9308-284c8afcb5c2.png)

**Comment by gsherwood** [comment]
I think I know what you are asking for now. This is the PHPStorm feature: http://blog.jetbrains.com/webide/2013/03/arrange-your-code-automatically-with-phpstorm-rearranger/

You want a sniff to check if the code is arranged in a specific way, and presumably an auto-fixer to rearrange it if it isn't.

Sounds like a big job, but one that would be generic.

**Comment by kodermax** [comment]
I suggest sorting alphabetically

**Comment by KacerCZ** [comment]
Good start would be at least check if class declaration is in standard order - first constants, second fields, then methods.

**Comment by gsherwood** [comment]
Closing this as I no longer have any intention of working on it. Could be implemented as a custom sniff though.
