### ISSUE TITLE
Update Wiki to keep in sync with inline comments

### ISSUE THREAD

**Issue by DanielSiepmann** [squizlabs/PHP_CodeSniffer#989]
I would like to provide more documentation about the possible inline comments, currently partial documented.

As Github doesn't allow forks or pull requests for wikis, you can find the commit here:
https://github.com/DanielSiepmann/PHP_CodeSniffer-Wiki/commit/c0b69c579c383d3c7d93dc49ae2e7f25010dfabf

Would be nice to see this parts documented.

**Comment by aik099** [comment]
Internally wiki is a Git repository, that can be cloned using url with `.wiki` suffix, e.g. `git@github.com:squizlabs/PHP_CodeSniffer.wiki.git` would represent a wiki. Not sure if there is UI for sending PR to it.

**Comment by DanielSiepmann** [comment]
I know, and that's how I've "forked" the wiki.

Github doesn't allow foreign ones to push or create pull requests for wikis at the moment. That's why I provide the change this way.

**Comment by gsherwood** [comment]
I've added docs for @codingStandardsIgnoreLine, but changing sniff settings is really not something that should be done inside files. Those settings will affect the checking of subsequent files if the settings are not reverted, but there is no way to actually "revert". That comment trick is just in the code for unit tests, so it should be in some doc about testing if one is ever written.

Thanks for letting me know about the lack of docs though.
