### ISSUE TITLE
Problem with nested if-else Inline Control Structure code formating with PSR2

### ISSUE THREAD

**Issue by sanjay-rakholiya** [squizlabs/PHP_CodeSniffer#997]
I have installed & using PHPCS & PHPCBF version 2.6.0 (stable) by Squiz (http://www.squiz.net)

Problem with nested if-else Inline Control Structure code formating with PSR2, 
I have some legacy code like this and need to format it correct way using phpcbf,

Creating testing file same as my legacy code : test.php
<pre>
function testPhpCode($abc, $xyz)
{
    if ($abc == 1)
        if ($xyz == 1)
            echo 'Its Ok..';
        else
            echo 'Its NOT Ok..';
}
</pre>
Run php code beautifier : **phpcbf -p --standard=PSR2  test.php**
Its formating wrong way like,
<pre>
function testPhpCode($abc, $xyz)
{
    if ($abc == 1) {
        if ($xyz == 1) {
            echo 'Its Ok..';
        }
    } else {
        echo 'Its NOT Ok..';
    }
}
</pre>

It should be format this correct way,
<pre>
function testPhpCode($abc, $xyz)
{
    if ($abc == 1) {
        if ($xyz == 1) {
            echo 'Its Ok..';
        } else {
            echo 'Its NOT Ok..';
        }
    }
}
</pre>

**Comment by gsherwood** [comment]
Same issue as #940 

Diff for PHPCS 2.6.0
```
--- temp.php
+++ PHP_CodeSniffer
@@ -1,9 +1,11 @@
 <?php
 function testPhpCode($abc, $xyz)
 {
-    if ($abc == 1)
-        if ($xyz == 1)
+    if ($abc == 1) {
+        if ($xyz == 1) {
             echo 'Its Ok..';
-        else
-            echo 'Its NOT Ok..';
+        }
+    } else {
+        echo 'Its NOT Ok..';
+    }
 }
```

Diff for master branch:
```
--- temp.php
+++ PHP_CodeSniffer
@@ -1,9 +1,11 @@
 <?php
 function testPhpCode($abc, $xyz)
 {
-    if ($abc == 1)
-        if ($xyz == 1)
+    if ($abc == 1) {
+        if ($xyz == 1) {
             echo 'Its Ok..';
-        else
+        } else {
             echo 'Its NOT Ok..';
+        }
+    }
 }
```

So issue is confirmed in 2.6.0, but has already been fixed, but unreleased. Thanks for the report.

**Comment by sanjay-rakholiya** [comment]
Ok, Thanks a lot ... :+1:
